### ISSUE TITLE
Integrate element templates

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1001]
* use element templates
* refactor [use of client config](https://github.com/camunda/camunda-modeler/blob/next/app/lib/index.js#L269)

Consider implementing: https://github.com/camunda/camunda-modeler/issues/951

**Comment by barmac** [comment]
[ ] hot reload (whenever editor is opened)
[ ] apply templates to present elements

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1069.
