### ISSUE TITLE
Deployment: Success while it isn't a success

### ISSUE THREAD

**Issue by Citrullin** [camunda/camunda-modeler#1004]
__Describe the Bug__

If you provide an incorrect BPMN diagram and deploys it via the deployment button, the tool reports a success, even if the response of the server returns another status code.

__Steps to Reproduce__

1. Add a service task without configure it
2. Add your configuration for your deployment endpoint
3. Deploy with some name
4. Check the deployment in the Camunda Cockpit. There is no new deployment
5. Deploy the diagram via the REST Interface. The Endpoint reports:
```
{
    "type": "ProcessEngineException",
    "message": "ENGINE-09005 Could not parse BPMN process. Errors: \n* One of the attributes 'class', 'delegateExpression', 'type', or 'expression' is mandatory on serviceTask. | diagram_1.bpmn | line 4 | column 43"
}
```
with an 500 Error.

__Expected Behavior__

An error message in the camunda modeler tool

__Environment__

Please complete the following information:

 - OS: Debian 8
 - Camunda Modeler Version: 1.16.2

**Comment by pinussilvestrus** [comment]
@Citrullin Thanks for reporting. Is there any reason you use a very old version of the modeler? There are couple of releases made after your version ...

However I can reproduce this on v2.0.3. 

```
15:51:19,558 ERROR [org.camunda.bpm.engine.context] (default task-85) ENGINE-16004 Exception while closing command context: ENGINE-09005 Could not parse BPMN process. Errors:
* One of the attributes 'class', 'delegateExpression', 'type', or 'expression' is mandatory on serviceTask. | diagram_4.bpmn | line 8 | column 41: org.camunda.bpm.engine.ProcessEngineException: ENGINE-09005 Could not parse BPMN process. Errors:
* One of the attributes 'class', 'delegateExpression', 'type', or 'expression' is mandatory on serviceTask. | diagram_4.bpmn | line 8 | column 41
	at org.camunda.bpm.engine.impl.util.EngineUtilLogger.exceptionDuringParsing(EngineUtilLogger.java:58)
	at org.camunda.bpm.engine.impl.util.xml.Parse.throwExceptionForErrors(Parse.java:191)
	at org.camunda.bpm.engine.impl.bpmn.parser.BpmnParse.execute(BpmnParse.java:267)
	at [...]
```

I think a proper error handling should be implemented here. I think this should go with the [deploy toolbar refactoring
](https://github.com/camunda/camunda-modeler/issues/906).

**Comment by nikku** [comment]
Closed on `next` via https://github.com/camunda/camunda-modeler/pull/1041.
