### ISSUE TITLE
Dirty state is broken

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1006]
__Describe the Bug__

On the actual `next` branch the dirty state is broken. When editing a diagram the tab does not change the unsaved/saved status. Furthermore when closing the tab and there are unsaved changes, it will not ask to save them.

![nov-14-2018 10-58-02](https://user-images.githubusercontent.com/9433996/48475051-39a9bc00-e7fc-11e8-9f3a-c9b13e986f3e.gif)

__Steps to Reproduce__

1. Open a diagram
2. Make some changes --> dirty state not set to true

__Expected Behavior__

Restore the broken dirty state behavior.

__Environment__

Please complete the following information:

 - OS: MacOS 10.14.1
 - Camunda Modeler Version: current `next` branch

---

Related issues: https://github.com/camunda/camunda-modeler/issues/1007, https://github.com/camunda/camunda-modeler/issues/1023

**Comment by pinussilvestrus** [comment]
This will probably fixed by #1007

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1073.
