### ISSUE TITLE
Switching the editor tab breaks current changes

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1007]
__Describe the Bug__

On current version of `next` branch, previously made changes were ignored when switching from Diagram to Xml Editor tab. When switching for the second time, it shows the changes, when a third time not and so on ...

![nov-14-2018 12-28-23](https://user-images.githubusercontent.com/9433996/48479863-d4a89300-e808-11e8-9178-d742f90229df.gif)

This only appears when editing Bpmn Diagrams. It could be based on the same bug as #1006 

__Steps to Reproduce__

1. Open a diagram
2. Make some changes (don't save!)
3. Switch between Diagram and Xml tab

__Expected Behavior__

Changes should be shown all the time.

__Environment__

 - OS: MacOS 10.14.1
 - Camunda Modeler Version: current `next`

**Comment by pinussilvestrus** [comment]
Progress on [this branch](https://github.com/camunda/camunda-modeler/tree/1007-switching-breaks-changes).

The issue is happened because of `BpmnDiagram` is rerendered again with old xml (without any changed). This should not happen.

Following function calls are leading to this bug: 
[`MutliSheetTab#switchSheet`](https://github.com/camunda/camunda-modeler/blob/next/client/src/app/tabs/MultiSheetTab.js#L230) --> [`BpmnEditor#getXml`](https://github.com/camunda/camunda-modeler/blob/next/client/src/app/tabs/bpmn/BpmnEditor.js#L362) -->`Modeler.saveXML` --> [`BpmnEditor#handleChanged`](https://github.com/camunda/camunda-modeler/blob/next/client/src/app/tabs/bpmn/BpmnEditor.js#L320) --> [Rerendering MultiSheetTab](https://github.com/camunda/camunda-modeler/blob/next/client/src/app/tabs/MultiSheetTab.js#L311) (with old xml) --> [`BpmnEditor#checkImport` ](https://github.com/camunda/camunda-modeler/blob/next/client/src/app/tabs/bpmn/BpmnEditor.js#L349)

**Comment by pinussilvestrus** [comment]
This will be touched again with the major dirty state refactoring: #1023.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1073.
