### ISSUE TITLE
"Disabled" save button actually still calls callback for `click` events

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1010]
__Describe the Bug__

"Disabled" save button actually still calls callback for `click` events.

__Steps to Reproduce__

1. Open a file but do not modify anything
2. Click on "disabled" save button

__Expected Behavior__

It should not react on `click` events.

__Environment__

Please complete the following information:

 - OS: MacOS 10.14.1
 - Camunda Modeler Version: `next@2.0.3`

**Comment by nikku** [comment]
Closed via #1014
