### ISSUE TITLE
Basic Snap-to-Grid

### ISSUE THREAD

**Issue by PwrSrg** [camunda/camunda-modeler#1019]
__Describe the feature you'd like to see__

Can we please get even **_basic_** Snap-to-Grid functionality?

__Context__

Checkout [this comment](https://github.com/camunda/camunda-modeler/issues/1019#issuecomment-444851052) for the actual rational + example where this may be useful.

**Comment by philippfromme** [comment]
+1 I might provide this as a plugin in the meantime.

**Comment by nikku** [comment]
May I ask _why_ you'd like such functionality? What will it help you with? Should it be configurable?

**Comment by rvaneerd** [comment]
+1 for me too.
Although (or maybe because of) I'm using the modeler for now for only "Documenting" purposes, having some kind of feature to properly align nodes / keep nodes with equal distance, will improve the overal view of the processes.

Regards,
Rob.

ps. I know about the alignment and distribution tools, but they dont work as expected and I'll raise a separate feature request for that,

**Comment by nikku** [comment]
Which part of the element should snap to grid exactly? The element middle? Any / all corners?

**Comment by rvaneerd** [comment]
> Which part of the element should snap to grid exactly? The element middle? Any / all corners?

IMHO, when it comes to the elements, the middle would be sufficient. As long as we can position the elements properly.
When it comes to connecting the elements through routes, I would prefer more "anchor-points" on the element-sides.
Would this all not be depending on the size of the grid?

Regards,
Rob.

**Comment by nikku** [comment]
> IMHO, when it comes to the elements, the middle would be sufficient. As long as we can position the elements properly.

We already offer snap lines on various angles. What is the benefit of the grid compared to snap lines. To be honest I was not able to grasp this one yet.

**Comment by rvaneerd** [comment]
The Snap lines only work with objects that already have a vertical / horizontal reference.
However when objects are placed "in the open" that's where "snap to grid" would be of use:
![image](https://user-images.githubusercontent.com/4356502/49583395-5b5c1600-f958-11e8-8187-b21ee2b8bfd6.png)
Hope this helps.

Regards,
Rob.

**Comment by nikku** [comment]
Thanks for the clarification.

I can definitely see that as an extension we provide (and eventually merge into the core tool).

**Comment by philippfromme** [comment]
Work is happening on the following branches:

* https://github.com/bpmn-io/diagram-js/tree/snap-to-grid
* https://github.com/bpmn-io/bpmn-js/tree/snap-to-grid
* https://github.com/bpmn-io/bpmn-font/tree/snap-to-grid

Needs clean-up and proper integration into palette and tool manager.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1404.

**Comment by philippfromme** [comment]
🔥 🔥 🔥 🔥 🔥
