### ISSUE TITLE
gracefully handle depricated async attribute

### ISSUE THREAD

**Issue by gimbel** [camunda/camunda-modeler#102]
Reproduce:
- open diagram that uses old async attribute

Problem:
- attribute gets lost in the new camunda modeler

Expected
- attribute is kept or transformed to asyncBefore

**Comment by mschoe** [comment]
This Issue is related to: https://app.camunda.com/jira/browse/SUPPORT-1969

**Comment by gimbel** [comment]
has been fixed in the properties panel
