### ISSUE TITLE
Renderer crashes when switching from XML editor to DMN table editor

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1023]
__Describe the Bug__

Renderer crashes when user switches from XML editor to DMN table editor. The console indicates that there is an infinite rerender loop (_max depth of rerender exceeded_). 

__Steps to Reproduce__

1. Open new DMN tab
2. Open XML editor
3. Open DMN table editor

![crash](https://user-images.githubusercontent.com/28307541/48852022-bdd7e280-edac-11e8-8cbd-995aa5b85e6b.gif)

Logs:
[crash.log](https://github.com/camunda/camunda-modeler/files/2604836/crash.log)

__Expected Behavior__

Show DMN table editor and do not crash.

__Environment__

 - OS: MacOS 10.14.1
 - Camunda Modeler Version: `next@e725255`

**Comment by barmac** [comment]
Confirmed on production version.

**Comment by barmac** [comment]
It seems like the whole App component falls into this loop. Further investigation should reveal what actually causes the problem.

**Comment by nikku** [comment]
> Confirmed on production version.

You mean `v2.x`?

**Comment by pinussilvestrus** [comment]
I can reproduce it on `next` branch, but not inside the current production version (master).

**Comment by pinussilvestrus** [comment]
Maybe this related to this [switching sheet bug](https://github.com/camunda/camunda-modeler/issues/1007)? Need more investigation here.

**Comment by barmac** [comment]
@nikku @pinussilvestrus 
I meant the current `next` generated with `npm run all`

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1073.
