### ISSUE TITLE
Restore Edit Menu Actions

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1024]
A quick test surfaced that the edit menu does not work as expected (yet).

__Tasks__

* [x] Ensure all entries in edit menu work

---

Things broken right now:

#### DRD

* [x] `direct edit`
* [x] `undo`, `redo`
    * [x] not properly indicating enabled state

#### Decision Table

* [x] `undo`, `redo`
    * [x] not working via shortcut
    * [x] not properly indicating enabled state
    * [x] breaks other editors undo redo actions, when switching from Decision Table

#### BPMN

* [x] `direct edit`
* [x] `undo`, `redo` 
    * [x] not properly indicating enabled state
    * [x] using keyboard shortcuts randomly breaks when doing `undo` -> `redo` in succession
* [x] `distributeElements`
    * [x] always disabled
* [x] `move to origin`
    * [x] shortcut changed, was `Ctrl/Cmd + 0` before, now it is `Ctrl/Cmd + Shift + O`
* [x] move canvas / selection
    * [x] movecanvas does not work (needs rebase on top of latest master?)
    * [x] move selection (not done yet)

#### CMMN

...

**Comment by philippfromme** [comment]
`Ctrl+<number>` doesn't work on Windows. Doesn't work in latest stable either. Can anyone check if this issue exists only on Windows?

**Comment by philippfromme** [comment]
Proper undo/redo behavior when editing DMN decision table cells will be tackled seperately: https://github.com/camunda/camunda-modeler/issues/1061
