### ISSUE TITLE
Proper Integration Testing

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1025]
__Is your feature request related to a problem? Please describe.__

As it came out in [this PR ](https://github.com/camunda/camunda-modeler/pull/1018) there are scenarios which currently can't be tested. That is caused by using _mocks_ in all kind of specs, e.g.  [`MultiSheetTabSpec`](https://github.com/camunda/camunda-modeler/blob/next/client/src/app/tabs/__tests__/MultiSheetTabSpec.js).

__Describe the solution you'd like__

We have to think about a way to implement integration tests for the modeler. In this it should be possible to test real user scenarios and to prevent certain bugs came out again. This will help us to avoid using mocks.

**Comment by nikku** [comment]
Next step: Just doing it!
