### ISSUE TITLE
Invisible character in properties panel inputs

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1034]
When editing an empty input in the properties panel an invisible character appears.

Related to https://github.com/bpmn-io/bpmn-js-properties-panel/commit/206b3f84d848952fbec4c68bad3a7955fdfead2a.

![2018-11-27_17-33-39](https://user-images.githubusercontent.com/7633572/49096318-9da39a00-f26a-11e8-9130-f618a6800345.gif)

**Comment by yanavasileva** [comment]
The same is valid for `Element Documentation`.

**Comment by nikku** [comment]
This should not be the case [in the nightly](https://camunda.org/release/camunda-modeler/nightly/) anymore.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/1411.
