### ISSUE TITLE
Open empty file throws an error

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1036]
__Describe the Bug__

When opening an empty file in the modeler, an error is thrown in the console and the file will not be opened.

![image](https://user-images.githubusercontent.com/9433996/49156144-eae04400-f31c-11e8-9646-11d790a7309b.png)

__Steps to Reproduce__

1. Open empty bpmn file
2. Error appears

__Expected Behavior__

Empty file will be opened as intended.

__Environment__

Please complete the following information:

 - OS: e.g. MacOS 10.14
 - Camunda Modeler Version: current `next`

**Comment by pinussilvestrus** [comment]
hint: [`Dialog.js#showEmptyFileDialog`](https://github.com/camunda/camunda-modeler/blob/next/client/src/remote/Dialog.js#L116) has to be called with `type`, but `App.js#openEmptyFile` is calling it with `fileType`

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1037/commits/f3e7d262887acc2c51b59b69323dfdbb3c1765bb.
