### ISSUE TITLE
Action in multitask?

### ISSUE THREAD

**Issue by knursultan** [camunda/camunda-modeler#1038]
I want to do multi task, where we can vote. If percentage of whole votes over 50%, it must go to next state, else it must finish. Can anybody help?
![screenshot from 2018-11-29 14-28-20](https://user-images.githubusercontent.com/9606441/49208953-6b697800-f3e3-11e8-8e85-e2e142459d46.png)

**Comment by pinussilvestrus** [comment]
So you ask for general modeling help here, right? If so please go to the [forum](https://forum.camunda.org/c/modeler), search for similar topics or open a thread with your task.

If you a [feature request ](https://github.com/camunda/camunda-modeler/issues/new?template=FEATURE_REQUEST.md) or find a [bug](https://github.com/camunda/camunda-modeler/issues/new?template=BUG_REPORT.md) inside the camunda modeler application, please open another issue for that. We want to keep general questions away from the issues.
