### ISSUE TITLE
Camunda Modeler Keyboard Shortcuts shown in Help are incorrect

### ISSUE THREAD

**Issue by rvaneerd** [camunda/camunda-modeler#1039]
Hi,

From what I can see in both Camunda Modeler V2.0.3 as well as in V2.2.1, the referenced Keyboard Shortcuts in Camunda Modeler Help are incorrect!

From what I experience:

- the “Control” key should NOT be used for scrolling, it manages the Zooming (not listed)
- instead “Control + Mouse Drag” it should be “Shift + Mouse Drag”

As mentioned, I frst noticed it using Camunda Modeler v2.0.3 (on Windows 10) but after upgrading to Camunda Modeler V2.2.1, the issue still exists.

__Steps to Reproduce__

1. Click on "Help" from the menu
2. Click on "Keyboard Shortcuts" from the drop-down Help menu.`
3. ![image](https://user-images.githubusercontent.com/4356502/49211912-fab16400-f3c0-11e8-8a25-0e10123395e4.png)
4. The pop-up screen shown above is presented but the keys listed do not work as mentioned

__Expected Behavior__

Instead of using the Control key in three different shortcuts, I need to use the keys as displayed here:
![image](https://user-images.githubusercontent.com/4356502/49211882-e40b0d00-f3c0-11e8-8083-167a32528b5c.png)

__Environment__

 - OS: Windows 10
 - Camunda Modeler Version: 2.0.3 as well as 2.2.1

**Comment by nikku** [comment]
Thanks for reporting.

It is indeed a bug, as the keybindings changed with `v2.0.0`.

**Comment by pinussilvestrus** [comment]
Closed via 37e2ba3.
