### ISSUE TITLE
Restore ability to infer diagram type from file contents

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1044]
__Tasks__

* [ ] If file does not have `bpmn`, `cmmn` or `dmn` extension, infer type via file contents

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/0317ccb85260b81ccc5e428b5ed725d9e659472a.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1054

**Comment by barmac** [comment]
😬
