### ISSUE TITLE
Nightly build not flagged as <nightly> on MacOS

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1047]
__Reproduce__

* Download [MacOS nightly](https://camunda.org/release/camunda-modeler/nightly/)
* Unzip and Open
* __Version is `2.x`, indicating an actual release__

__Expected Behavior__

* [ ] Version should be `2.x-nightly`, indicating a nightly build

__Environment__

Please complete the following information:

 - OS: MacOS 10.x
 - Camunda Modeler Version: `2.3.0-nightly`

**Comment by pinussilvestrus** [comment]
I can't reproduce this on my mac (`v10.14.6`)

![image](https://user-images.githubusercontent.com/9433996/64408188-70e8a280-d086-11e9-9127-7e62c88ac9a1.png)

**Comment by nikku** [comment]
Thanks for the heads up. Closing this then.
