### ISSUE TITLE
distro:test-archives fails on MacOS

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1048]
__Describe the Bug__

Whenever I run `npm run all` or `npm run distro:test-archives`, I get an error when the script is trying to decompress ZIP file. See logs below:

```
Verifying <mac> distributables

 - camunda-modeler-2.0.3-mac.dmg
 - camunda-modeler-2.0.3-mac.zip
     > extracting
FAILURE Error: invalid comment length. expected: 51859. found: 0
    at /workspace/bpmn-io/camunda-modeler/node_modules/yauzl/index.js:133:25
    at /workspace/bpmn-io/camunda-modeler/node_modules/yauzl/index.js:631:5
    at Immediate.<anonymous> (/workspace/bpmn-io/camunda-modeler/node_modules/fd-slicer/index.js:202:5)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! camunda-modeler-builder@0.0.0 distro:test-archives: `node tasks/test-distro.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the camunda-modeler-builder@0.0.0 distro:test-archives script.```
```

So it seems we have a problem with yauzl.

__Steps to Reproduce__

1. Run `npm ci`
2. Run `npm run all`

__Expected Behavior__

🎉SUCCESS 🎉 

__Environment__

Please complete the following information:

 - OS: MacOS 10.14.1
 - Camunda Modeler Version: `next`, `new-next-merge` branches

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1064/commits/5966d0fafa0251f76ade912da89baea057caeae0.
