### ISSUE TITLE
Message referenced via Message Event not copied across between diagrams

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#1049]
__Reproduce__

* Open [example file](https://github.com/camunda/camunda-modeler/files/2639372/issue.1049.bpmn.txt)
* Copy all elements
* Create new diagrams
* Paste elements 

__Observed Behavior__

* The Message definition is not copied to other diagram

__Expected Behavior__

* [ ] Message definition gets copied to other diagram

__Environment__

Camunda Modeler `v2.2`
OS: Any

---

Related to https://github.com/camunda/camunda-modeler/issues/586, https://github.com/camunda/camunda-modeler/issues/1463.

**Comment by falko** [comment]
It's not exactly a duplicate, because this issue is about the Message Definition that doesn't get copied between two BPMN files.

**Comment by nikku** [comment]
> It's not exactly a duplicate, because this issue is about the Message Definition that doesn't get copied between two BPMN files.

If that is the case, please follow our [bug report template](https://github.com/camunda/camunda-modeler/issues/new?template=BUG_REPORT.md) and add the exact steps to reproduce your issue. 

This allows us to understand what is going on and improve things.

**Comment by falko** [comment]
Example file:
[issue 1049.bpmn.txt](https://github.com/camunda/camunda-modeler/files/2639372/issue.1049.bpmn.txt)

Copy all elements from this BPMN file into another file.

Expected: The Message definition is kept.
Actual: The Message definition is not copied.

Sorry, for my brevity. I was with a customer and first wanted ensure to capture it.

**Comment by falko** [comment]
- OS: Ubuntu 16.04
 - Camunda Modeler Version: 2.2.0

**Comment by nikku** [comment]
Updated the issue based on the input you provided. 

Thanks for reporting this issue.

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js/pull/1245.
