### ISSUE TITLE
copy&paste not working in fields (and objects)

### ISSUE THREAD

**Issue by bartoleo** [camunda/camunda-modeler#105]
copy&paste not working in fields (and objects)
on Mac OSX Yosemite (10.10.5)

**Comment by ricardomatias** [comment]
Hello @bartoleo.

Could you please specify the place where copy & paste don't work ?

**Comment by bartoleo** [comment]
All property fields (right panel)
Inside tasks
On objects (tasks, events, gateways... etc)

**Comment by bartoleo** [comment]
I found this post about electron & clipboard... 
http://www.pracucci.com/atom-electron-enable-copy-and-paste.html
