### ISSUE TITLE
Label of former child element deleted when deleting Sub-Process

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#1050]
__Describe the Bug__

The Label of a former child element gets deleted when deleting a Sub-Process.

![2018-12-03 label of former child element deleted when deleting sub-process](https://user-images.githubusercontent.com/40038/49374236-0377a200-f701-11e8-972b-e600e26c6aa5.gif)

__Steps to Reproduce__

1. Open the attached BPMN file 
[2018-12-03 Label of former child element deleted when deleting Sub-Process.bpmn.txt](https://github.com/camunda/camunda-modeler/files/2639445/2018-12-03.Label.of.former.child.element.deleted.when.deleting.Sub-Process.bpmn.txt)

2. Move the End Event "Dokument in Akte abgelegt" out of the Event Sub-Process.
3. Delete the Event Sub-Process.

__Expected Behavior__

The End Event "Dokument in Akte abgelegt" keeps its Label, because it is no longer a child of the Sub-Process.

__Environment__

Please complete the following information:

 - OS: Ubuntu 16.04.5 LTS
 - Camunda Modeler Version: 2.2.0

**Comment by nikku** [comment]
There seems to be a bug in the way labels move on the diagram. 

The following screencast shows a related issue: 

![foo](https://user-images.githubusercontent.com/58601/49429050-dd590d00-f7a7-11e8-8fa4-b6013d607ece.gif)

**Comment by falko** [comment]
If you say that it is about how labels are moved, could #1011 be related as well?

**Comment by nikku** [comment]
Unfortunately not. We simply do not support embedded labels.

**Comment by nikku** [comment]
Gets addressed via https://github.com/bpmn-io/bpmn-js/pull/920.
