### ISSUE TITLE
Remove selected Delete shortcut does not work anymore

### ISSUE THREAD

**Issue by vbelinic** [camunda/camunda-modeler#1051]
__Describe the Bug__

When selecting an element delete shortcut does not work.

__Steps to Reproduce__

1. Open any kind of diagram in camunda-modeler
2. Select one (or more) element(s) in the diagram
3. Press shortcut for Remove selected (deleted)
4. Nothing happens

__Expected Behavior__

Element should be deleted 

__Environment__

Please complete the following information:

 - OS: Linux Ubuntu 16.04 LTS
 - Camunda Modeler Version: 2.2.3 (with version 2.0.3 it was still working)

**Comment by nikku** [comment]
I cannot reproduce your issue.

**Comment by pinussilvestrus** [comment]
I was also not able to reproduce it on `v2.2.3`. 

![dec-04-2018 14-29-18](https://user-images.githubusercontent.com/9433996/49444994-0b9f1280-f7d1-11e8-8405-30674ad40534.gif)


@vbelinic Can you verify the version in which the deletion does not work for you?

**Comment by vbelinic** [comment]
@pinussilvestrus @nikku Did you try to reproduce it on a PC with Linux? On my Windows PC I also have no problem but on my other one with Linux it's not working (also not for all my other colleagues which are using linux). We tried one three different laptops.
Here's a screen cast trying to delete something by pressing the delete button. Basically nothing is happening when pressing delete button, each element has to be deleted over the menu.

![screencast](https://user-images.githubusercontent.com/2853099/49446249-0394a200-f7d4-11e8-8679-87a67d513cec.gif)

With the previous version I had 2.0.3 it's was working on Linux.
I do not us any plugin, it's the fresh dowloaded tar.gz from camunda page.

You can reproduce by downloading linux 64bit tar.gz from camunda page.
Unpack and run the modeler.
Select one or more elements and try to delete them by pressing the Delete button, it won't work.

**Comment by nikku** [comment]
I could not reproduce it on Arch Linux (`4.19.4-arch1-1-ARCH`).

**Comment by nikku** [comment]
Please provide us with the exact download link.

**Comment by nikku** [comment]
@vbelinic Can you verify whether you're able to delete elements in [our online toolkit demo](https://demo.bpmn.io/new)?

**Comment by mschoe** [comment]
I was also not able to reproduce it with Linux Mint 19 which is based on Ubuntu 18.04

**Comment by nikku** [comment]
So it seems to be a problem that specifically occurs on Ubuntu 16.

**Comment by nikku** [comment]
@vbelinic Could you check whether the issue is still present in our [latest nightly](https://camunda.org/release/camunda-modeler/nightly/)? That would be wonderful.
