### ISSUE TITLE
Sequenceflow is hidden behind task when connected to boundary event 

### ISSUE THREAD

**Issue by vbelinic** [camunda/camunda-modeler#1052]
__Describe the Bug__

When adding a boundary event to a task, and boundary event is connected to another task, and this task is placed over the boundary event, sequence flow is partly hidden behind the task.

__Steps to Reproduce__

1. Open new BPMN diagram 
2. add new Task (T1)
3. add boundary event (B) to Task (T1)
4. connect new Task (T2) to boundary event (B)
5. place Task (T2) over boundary event (B)
6. Sequence flow from boundary event (B) to Task (T2) is partly hidden behind Task (T2)

![bug](https://user-images.githubusercontent.com/2853099/49433852-31b5ba00-f7b3-11e8-8d59-7174121a6ca4.png)

__Expected Behavior__

Sequence flow should be visible and not partly hidden behind some element.

__Environment__

Please complete the following information:

 - OS: Linux Ubuntu 16.04 LTS
 - Camunda Modeler Version: 2.0.3 

---

Depends on https://github.com/bpmn-io/bpmn-js/issues/891

**Comment by nikku** [comment]
Needs fix via https://github.com/bpmn-io/bpmn-js/issues/891.

**Comment by nikku** [comment]
Thanks for reporting.

**Comment by barmac** [comment]
This will be adressed via https://github.com/bpmn-io/bpmn-js/pull/994

**Comment by pinussilvestrus** [comment]
Closed via aafbda44795d7e2c0bb00aa8a4bbe81956b17b1b
