### ISSUE TITLE
Integrate CommandStack#undo and CommandStack#redo when working with the properties panel

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1059]
Integrating `CommandStack#undo` and `CommandStack#redo` when working with the properties panel was previously implemented in [ShortcutsFix](https://github.com/camunda/camunda-modeler/blob/master/client/lib/external/shortcuts-fix.js). This fix was initially implemented to work around issues with overriding default keyboard bindings on Linux and Windows which is a different issue. The fix has since been re-implemented. This particular behavior should be implemented in a different place.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1101
