### ISSUE TITLE
Restore custom copy/cut/paste behavior in decision table depending on selection range

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1060]
The behavior implemented in dmn-js's [CopyCutPasteKeyBindings](https://github.com/bpmn-io/dmn-js/blob/master/packages/dmn-js-decision-table/src/features/copy-cut-paste/key-bindings/CopyCutPasteKeyBindings.js) triggers a custom copy/cut/paste behavior if the selection range has a lenght > 0. Currently this behavior doesn't work since the keyboard is not bound in the Camunda Modeler. It was before the refactoring. We have to decide if and how to re-implement this behavior.

**Comment by nikku** [comment]
I don't see a reason why we'd not like to have this one. Am I missing something? Bindings should work properly for copying rows / colums _and_ selections (if an actual selection exists).
