### ISSUE TITLE
Properly wire all decision table keyboards shortcuts

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1061]
#### Description

Since we do not bind the keyboard feature of dmn-js after the refactoring we have to manually add the keyboard bindings that are implemented in [Keyboard](https://github.com/bpmn-io/dmn-js/blob/master/packages/dmn-js-decision-table/src/features/keyboard/Keyboard.js).

#### Current Behavior

When editing a DMN decision table cell using `CommandOrControl + Z` and `CommandOrControl + Y` will trigger native undo and redo.

#### Expected Behavior

When editing a DMN decision table cell using `CommandOrControl + Z` and `CommandOrControl + Y` triggers native `CommandStack#undo` and `CommandStack#redo`.

__Tasks__

* [ ] Undo / Redo works as expected, via command stack operation
* [ ] TAB / SHIFT + TAB navigate cells (horizontally)
* [ ] ENTER / SHIFT + ENTER navigate cells (vertically)
* [ ] CTRL+ENTER adds new line in cell

__Note:__ May be worth double checking against Camunda Modeler `v2.2.x` or [demo.bpmn.io/dmn](https://demo.bpmn.io/dmn/s/check-order).

__QA__

* [ ] Works reliably on Mac OS
* [ ] Works reliably on Windows / Linux

**Comment by pinussilvestrus** [comment]
Seems like we are already using [`CommandStack#undo`](https://github.com/bpmn-io/diagram-js/blob/master/lib/command/CommandStack.js#L212) and [`CommandStack#redo`](https://github.com/bpmn-io/diagram-js/blob/master/lib/command/CommandStack.js#L238) when editing inside a decision table. In the case of undo it got fired by following trace:

`AppParent#triggerAction` --> `DmnEditor#triggerAction` --> `EditorActions#undo` --> `CommandStack#undo`.

Lead me to the opinion we already integrate the keyboard binding and no more work is needed.

**Comment by pinussilvestrus** [comment]
Regarding the[ last thought](https://github.com/camunda/camunda-modeler/issues/1061#issuecomment-456817453) above, I did some investigation.

The undo/redo behavior works as expected and there seemed to be no side affects on this regarding a possible additional native event. It also worked the same way as in the [dmn-js demo](https://demo.bpmn.io/dmn/new). 

Via the DevTools, following listeners revealed for the `keydown-event`:

![image](https://user-images.githubusercontent.com/9433996/51670067-20747700-1fc6-11e9-9d22-e5dd1f4d8167.png)

I just [monitored](https://developers.google.com/web/tools/chrome-devtools/console/events) the fired events, and found out just first, global one defining inside the KeyboardBindings.js got fired on Pressing `Command + Z`.

Therefore really no more work is needed here and the issue can be closed.

**Comment by nikku** [comment]
What about the other interactions (TAB, ENTER, SHIFT + ENTER, SHIFT + TAB) to navigate the table?

**Comment by nikku** [comment]
Updated the issue with list of concrete tasks.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1148#pullrequestreview-198052224
