### ISSUE TITLE
Remember authentication details with endpoint configuration

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1067]
__Is your feature request related to a problem? Please describe.__

As a user I am frustrated if I need to re-configure the authentication details every time I re-deploy a diagram.

__Describe the solution you'd like__

* [ ] Deployment details, including authentication type (+ user name) (+ credentials _?_) are stored within the user data `config.json` upon successful deployment and restored on deploy dialog re-open.

__Describe alternatives you've considered__

Don't store the details (password / token) if we don't find a way to secure it.

**Comment by barmac** [comment]
I had a look at how [VS Code Docker Extension](https://github.com/microsoft/vscode-docker) handles the passwords and noticed that:
* the passwords are stored in the system's keychain using https://github.com/atom/node-keytar
* once the credentials are used they are kept in a session cache to not overuse the keychain

**Comment by barmac** [comment]
Idea: Checkbox for remembering details

**Comment by barmac** [comment]
Idea: Remember auth per endpoint url and the auth type.

**Comment by nikku** [comment]
Removed from https://github.com/camunda/camunda-modeler/issues/1439. We'll ship this with a future version of the tool.
