### ISSUE TITLE
Edit menu stays when last tab is closed

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1070]
__Describe the Bug__

Edit menu stays and editor actions are still emitted on shortcuts despite the last tab being closed:

![foo](https://user-images.githubusercontent.com/58601/49928430-64049d00-fec0-11e8-8dfd-a408d3989c5e.gif)

__Steps to Reproduce__

* Create BPMN tab
* Close BPMN tab
* (no tabs are open anymore at this point)
* __Edit Menu is still active, keyboard shortcuts still trigger__

__Expected Behavior__

* [ ] No tabs are open -> Edit menu is not visible, keyboard shortcuts don't trigger

__Environment__

 - OS: Any
 - Camunda Modeler Version: `next`

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1072
