### ISSUE TITLE
Log -> Copy log does not work anymore

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1079]
__Reproduce__

* Import diagram with warning
* Open Log
* Press _Copy_ 
* __Nothing happens__

__Expected Behavior__

* [ ] Copy selects all log contents and adds them to clipboard

**Comment by pinussilvestrus** [comment]
Seems that the div itself is not selectable, as `user-select` is set to 'none'. This leads that the content is not able to be copied. Maybe setting the css attribute `user-select` to 'auto' would do the trick.

![image](https://user-images.githubusercontent.com/9433996/50597077-71e98480-0ea6-11e9-965c-972bc93c2629.png)
