### ISSUE TITLE
Restore plugin system

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1083]
__Is your feature request related to a problem? Please describe.__

There is currently no plugins system on `next` branch Modeler.

__Describe the solution you'd like__

We need to restore plugin system as it was in old Camunda Modeler. To achieve this, we need to: 

* [ ] Restore menu endpoint
* [ ] Restore style endpoint
* [ ] Restore script endpoint

__Additional context__

Previously, we provided endpoints to add custom style, menu and script. The script could register additional `bpmn-js` and `bpmn-moddle` modules thanks to https://github.com/camunda/camunda-modeler-plugin-helpers

**Comment by barmac** [comment]
Related respos:
https://github.com/camunda/camunda-modeler-plugin-example
https://github.com/camunda/camunda-modeler-plugin-helpers

**Comment by pSub** [comment]
Support for dmn plugins would be really nice! Do you have plans for it?

**Comment by nikku** [comment]
Not on our immediate roadmap (but definitely nice to have some day, maybe).

How would you like to extend dmn-js?

**Comment by pSub** [comment]
I am developing an analysis tool for dmn (https://github.com/red6/dmn-check). That tool started out as a Maven plugin, but I would like to integrate it into the modeler (ie. highlighting errors in the decision table / diagram).
