### ISSUE TITLE
Restore file drop feature

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1085]
__Is your feature request related to a problem? Please describe.__

As a user I want to open files by dragging and dropping on application window.

__Describe the solution you'd like__

Allow to drag a file and drop it on the app so that it is automatically opened. See: https://github.com/camunda/camunda-modeler/issues/607

Mind the bug on `master` that `file-drop.js` never stops to add event listeners.

__Describe alternatives you've considered__

🙊

**Comment by pinussilvestrus** [comment]
Will this be part of the `Pre-Release` or `RC.1`?
