### ISSUE TITLE
npm run all error

### ISSUE THREAD

**Issue by yanwencheng** [camunda/camunda-modeler#1087]
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-27T06_19_02_361Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! camunda-modeler-builder@0.0.0 client:build: `(cd client && npm run build)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the camunda-modeler-builder@0.0.0 client:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-27T06_19_02_400Z-debug.log
ERROR: "client:build" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! camunda-modeler-builder@0.0.0 build: `run-s client:build "distro -- {@}" "distro:test-archives -- {@}" --`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the camunda-modeler-builder@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-27T06_19_02_459Z-debug.log
ERROR: "build --" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! camunda-modeler-builder@0.0.0 all: `run-s clean lint test "build -- {@}" --`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the camunda-modeler-builder@0.0.0 all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-27T06_19_02_512Z-debug.log

**Comment by pinussilvestrus** [comment]
Please give us more information on your problem. Try to use the [`bug-template`](https://github.com/camunda/camunda-modeler/issues/new?template=BUG_REPORT.md).
