### ISSUE TITLE
Shape attribute isHorizontal is not set by modeler

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#1096]
* Create a new model with a pool
* Try to import this into Signavio
* This will break the layout because the modeler does not set the (optional?) attribute isHorizontal

<img width="630" alt="screenshot 2019-01-15 at 11 01 20" src="https://user-images.githubusercontent.com/17595149/51173066-f2e84900-18b4-11e9-8aec-1c77ae2c1082.png">

Although the attribute might be optional, users who use a combination of Signavio and Camunda and try to do a roundtrip are affected by this issue if the model was created with Camunda modeler in the first place - import to Signavio is close to impossible in this case.

If the model is created with Signavio first, the attribute is set and the roundtrip works.

#### Tasks

* [ ] `isHorizontal` is set to `true` for `bpmn:Participant` and `bpmn:Lane`

#### Additional Context

This is an actual problem at one of our customers

**Comment by nikku** [comment]
I got a couple of questions on this issue:

* Is this an issue with Signavio or our tools? 
* What is the default value for `isHorizontal`?
* How does it _break_ the diagram?

**Comment by benhoffmann** [comment]
I guess the problem is that Signavio expects this attribute, although I guess it's optional (maybe worth some research in the specs). I am not even sure if that is specified by BPMN. It shows up in some bpmn.js source code though: https://github.com/bpmn-io/bpmn-js/blob/ef09e1a68e59171dfc9569f04b55146d19c06cb5/test/fixtures/bpmn/collaboration-data-items.bpmn#L35 

The value should be isHorizontal=true. 

It breaks the diagram in a way that the layout and labels are completely chaotic in a way that it is impossible to recover from that. (Maybe that is due to Signavio trying to calculate something, see the screenshot - who knows)

**Comment by nikku** [comment]
> It breaks the diagram in a way that the layout and labels are completely chaotic in a way that it is impossible to recover from that.

Please share a screenshot / example diagram so we can reproduce this issue.

**Comment by nikku** [comment]
> The value should be isHorizontal=true.

There is no default value so it seems like indeed, we should set a value.

**Comment by nikku** [comment]
Thanks for sharing that additional information. We got https://github.com/camunda/camunda-modeler/issues/982 to automatically align elements @ 0,0 upon export.

**Comment by nikku** [comment]
Will be addressed via https://github.com/bpmn-io/bpmn-js/issues/934.
