### ISSUE TITLE
Switching to DMN diagram removes Edit menu

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1097]
__Describe the Bug__

The `Edit` menu hides when switching to the DMN tab.

__Steps to Reproduce__

* Open BPMN Tab
* Open DMN Tab
* Switch BPMN -> DMN tab
* __See the `Edit` menu vanishing__

__Expected Behavior__

Edit menu stays available.

__Environment__

Please complete the following information:

 - OS: Linux, Windows, ...
 - Camunda Modeler Version: `next`

**Comment by barmac** [comment]
I can reproduce this.

**Comment by barmac** [comment]
Fixed in https://github.com/bpmn-io/dmn-js/pull/386. As soon as I update the libraries it should be all right.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1110
