### ISSUE TITLE
Error when trying to export diagram as a jpg file

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1103]
__Describe the Bug__

I can't export diagram as a jpg file. It happens on MacOS as well as on Linux.

__Steps to Reproduce__

![extensions](https://user-images.githubusercontent.com/28307541/51185369-3784dc00-18d7-11e9-978b-b708cbdaaa86.gif)

__Expected Behavior__

A jpg file is saved.

__Environment__

* OS: MacOS 10.14.2
* Camunda Modeler Version: next

**Comment by philippfromme** [comment]
Hint: Change `jpg` to `jpeg`.

```javascript
// generateImage.js

// list of defined encodings
const ENCODINGS = ['image/png', 'image/jpeg'];

function generateImage(type, svg) {
  const encoding = 'image/' + type;

  let context, canvas;

  if (ENCODINGS.indexOf(encoding) === -1) {
    throw new Error('<' + type + '> is an unknown type for converting svg to image');
  }

// ...
```

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1106
