### ISSUE TITLE
Consider integrating fork synchronization task via workflow bot

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1108]
Inside the [Zeebe modeler](https://github.com/zeebe-io/zeebe-modeler) we've created a [sync task](https://github.com/zeebe-io/zeebe-modeler/blob/master/tasks/sync-fork.js) which helps automatically making changes from the base `camunda-modeler` to it's zeebe fork. For now it has to be manually triggered by executing `npm run sync` locally. Furthermore the resulted commit has to be pushed remotely, left and not cleaned conflicts has to be fixed on the machine by the user itself, also a Pull request with the changes has to be opened manually.

Moreover there is no guideline on _when_ doing the sync. Should we do it once a week? Once a month? On every new `camunda-modeler` release?

As a future task we should consider to do this all _automatically_ via a GitHub bot. It should include different tasks:

* Trigger sync task automatically in a _certain period_ on `zeebe-modeler`, e.g. on every new `camunda-modeler` tag
* Create a pull request on `zeebe-modeler` side with made changes
* Verifies made changes are stable in the `zeebe-modeler` (CI)
* Give an overview of merged changes
* Give an overview of cleaned changes
* Give an overview of unresolved conflicts which have to be merged manually after synchronization

Maybe the workflow could be orientated by the way [Dependabot](https://dependabot.com/) keep dependencies in sync. Also the [merge-me bot](https://github.com/nikku/merge-me) could be an example on how building a proper [Probot workflow bot](https://github.com/probot).

**Comment by nikku** [comment]
We may spike this once we got a little more experience with our Camunda Modeler to Zeebe Modeler update procedures.

**Comment by nikku** [comment]
We'll merge both editors, mid-term.
