### ISSUE TITLE
Add ability to run scenario tests on the DMN model

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#111]
When creating a large and complex DMN model, you should be able to test the DMN model in the modeller. Each input should be a available text field to populate with values and see what the output is.

This would work really well if it could be used with CSV/YML files so you could batch test to ensure your large models are providing the correct output.

This example of a decision table to determine costs of a animal license comes to mind.  When changes are made to the table, you would want to test to ensure all the proper values are coming out.

![screen shot 2015-12-15 at 6 14 20 pm](https://cloud.githubusercontent.com/assets/1994838/11827124/e25ace8a-a357-11e5-9738-f51ca1b73fff.png)
![screen shot 2015-12-15 at 6 14 27 pm](https://cloud.githubusercontent.com/assets/1994838/11827125/e4cf29c2-a357-11e5-874a-5ef2a83b2cbd.png)
![screen shot 2015-12-15 at 6 14 35 pm](https://cloud.githubusercontent.com/assets/1994838/11827127/e6a3fda4-a357-11e5-9977-458b3c7c34ce.png)
![screen shot 2015-12-15 at 6 14 43 pm](https://cloud.githubusercontent.com/assets/1994838/11827130/e8d87c4e-a357-11e5-8aeb-f6bc5f6103bc.png)
![screen shot 2015-12-15 at 6 14 58 pm](https://cloud.githubusercontent.com/assets/1994838/11827132/ea714da6-a357-11e5-8b19-d156aaf31656.png)

**Comment by berndruecker** [comment]
Hi Stephan.

By the way – I think the Camunda BPM Forum is better suited for these discussions: http://camunda.org/community/forum.html.

Di you try Fitnesse for this purpose? I used the wiki style tables to define and run scenario tests for Camunda DMN tables – this is how it looks like:

[cid:image001.png@01D137D6.9E4DE890]

Cheers
Bernd

Von: Stephen Russett [mailto:notifications@github.com]
Gesendet: Mittwoch, 16. Dezember 2015 00:42
An: camunda/camunda-modeler <camunda-modeler@noreply.github.com>
Betreff: [camunda-modeler] Add ability to run scenario tests on the DMN model (#111)


When creating a large and complex DMN model, you should be able to test the DMN model in the modeller. Each input should be a available text field to populate with values and see what the output is.

This would work really well if it could be used with CSV/YML files so you could batch test to ensure your large models are providing the correct output.

This example of a decision table to determine costs of a animal license comes to mind. When changes are made to the table, you would want to test to ensure all the proper values are coming out.

[screen shot 2015-12-15 at 6 14 20 pm]<https://cloud.githubusercontent.com/assets/1994838/11827124/e25ace8a-a357-11e5-9738-f51ca1b73fff.png>
[screen shot 2015-12-15 at 6 14 27 pm]<https://cloud.githubusercontent.com/assets/1994838/11827125/e4cf29c2-a357-11e5-874a-5ef2a83b2cbd.png>
[screen shot 2015-12-15 at 6 14 35 pm]<https://cloud.githubusercontent.com/assets/1994838/11827127/e6a3fda4-a357-11e5-9977-458b3c7c34ce.png>
[screen shot 2015-12-15 at 6 14 43 pm]<https://cloud.githubusercontent.com/assets/1994838/11827130/e8d87c4e-a357-11e5-8aeb-f6bc5f6103bc.png>
[screen shot 2015-12-15 at 6 14 58 pm]<https://cloud.githubusercontent.com/assets/1994838/11827132/ea714da6-a357-11e5-8b19-d156aaf31656.png>

**Comment by StephenOTT** [comment]
https://camunda.org/dmn/simulator/?utm_source=Camunda+BPM+Network+-+Newsletter&utm_campaign=fa5faafbf2-DMN_Simulator_EN12_21_2015&utm_medium=email&utm_term=0_70076642a1-fa5faafbf2-98332501

Based from the most recent email from Camnuda :+1: 

The DMN online simulator has inputs and outputs simulator:

![screen shot 2015-12-21 at 11 17 52 am](https://cloud.githubusercontent.com/assets/1994838/11935196/8bc3b4a2-a7d4-11e5-8615-0494cd9d0bfa.png)
![screen shot 2015-12-21 at 11 18 05 am](https://cloud.githubusercontent.com/assets/1994838/11935200/8ebe55b8-a7d4-11e5-96c3-08f5d6f66f51.png)
