### ISSUE TITLE
Release Camunda-Modeler@3.0.0-0

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1112]
Checklist:
* [x] merge `next` to `master`
* [x] make sure dependencies are released (`rm -rf node_modules && npm i && npm run all` works)
    * `bpmn-js`, `dmn-js`, `cmmn-js`, `*-properties-panel`, `*-moddle`, ...
* [x] smoke test to verify all diagrams can be created
* [x] update CHANGELOG before releasing @philippfromme 
* [x] semantic release (`npm run release`)
* [x] wait for [Travis](https://travis-ci.org/camunda/camunda-modeler) to build the release
* [x] execute [integration test](https://github.com/camunda/camunda-modeler/blob/master/docs/.project/INTEGRATION_TEST.md) on [released artifacts](https://github.com/camunda/camunda-modeler/releases)
    * [x] Works on Linux
    * [x] Works on Mac
    * [x] Works on Windows
* [x] publish release on [Github Releases](https://github.com/camunda/camunda-modeler/releases)
* [x] write blog post on [blog.camunda.org](https://github.com/camunda/blog.camunda.org)
* [x] trigger mirroring of release to https://camunda.org/release/camunda-modeler/ via [Jenkins](https://ci.cambpm.camunda.cloud/job/sideprojects/job/camunda-modeler-desktop-RELEASE/build?delay=0sec)
* [x] ~~update download version of Camunda Modeler at [camunda.com](https://github.com/camunda/camunda.com-new/blob/live/data/releases.json)~~ It's a pre-release, we're not going to do that.
* [x] spread the word
    * [x] `@alle` to trigger customer mail
    * [x] tweet
* [x] close [current milestone](https://github.com/camunda/camunda-modeler/milestones)

**Comment by barmac** [comment]
We're working on `release-3.0.0-0` branch.

**Comment by barmac** [comment]
@philippfromme I'm going to perform the integration test on both Ubuntu and MacOS.

**Comment by barmac** [comment]
@philippfromme The draft release is available at: https://github.com/camunda/camunda-modeler/releases/tag/untagged-773780698e0a67aeda47

@mschoe Feel free to test it if you want :)

**Comment by philippfromme** [comment]
@barmac I'm doing Windows.

> Hint: Dirty state indication is broken: https://github.com/camunda/camunda-modeler/issues/1117

**Comment by barmac** [comment]
I'm doing MacOS at the moment and then Ubuntu.

**Comment by barmac** [comment]
We did it.

Blog post:
https://blog.camunda.com/post/2019/01/camunda-modeler-3.0.0-0-released/
Tweet:
https://twitter.com/maciejbarel/status/1086234120018161664
Release:
https://camunda.org/release/camunda-modeler/3.0.0-0/
https://github.com/camunda/camunda-modeler/releases/tag/v3.0.0-0
