### ISSUE TITLE
Tab links not updating properly

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1117]
# Description

Dirty state is not correctly indicated by tab links:

![2019-01-17_15-56-05](https://user-images.githubusercontent.com/7633572/51327149-f9bbbb00-1a70-11e9-8ee6-da9b3307bd89.gif)

> Hint: After converting all of our components to pure components the `TabLinks` component doesn't update anymore. Therefore, the callback that asks for the dirty state is not being called any more.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1125
