### ISSUE TITLE
CMD+SHIFT+Z does not redo command in the diagram

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1119]
__Describe the Bug__

When I press CMD+SHIFT+Z in the diagram, it does not execute redo command. It works perfectly fine, however, in the properties panel.

__Steps to Reproduce__

1. Do something in diagram
2. CMD+Z for undo
3. CMD+SHIFT+Z for redo

__Expected Behavior__

Redo.

__Environment__

 - OS: MacOS
 - Camunda Modeler Version: 3.0.0-0

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/0732741abd8de0d54dc7e1464ce768784d4249c3.
