### ISSUE TITLE
Add support for element templates

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#113]
Developers may provide custom element templates with the modeler.

* [ ] read custom templates from `$MODELER_CWD/resources/templates` _and_ `$USER_DIR/resources/templates`. Directories contain individual files (JSON descriptors with template definitions
* [ ] inject the configuration into the modeler during bootstrapping
* [ ] allow selection of task template and editing of defined properties via properties-panel (bpmn-io/bpmn-js-properties-panel#171)

**Comment by gimbel** [comment]
Feedback from a customer: it would be great to have the opportunity to define drop down lists in the template.

e.g.

Field Name: Age
Possible values:
 *  0-10
 * 11-20
 * 21-50
 * 50-99
Binding: To some input mapping
