### ISSUE TITLE
Compensation task should not have connectors displayed in context pad

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#1130]
![screenshot 2019-01-22 at 13 30 45](https://user-images.githubusercontent.com/17595149/51548763-45070c80-1e69-11e9-9032-04a7e54376ff.png)

There is nothing one can connect from a compensation task, so the context pad should not be offering connectors as an option.

**Comment by nikku** [comment]
> There is nothing one can connect from a compensation task, so the context pad should not be offering connectors as an option.

Is this by the Spec?

**Comment by benhoffmann** [comment]
> This compensation is modeled with a specialized Compensation Activity, which is connected to the boundary Event through an Association (see Figure 10.121). The Compensation Activity, which can be either a Task or a Sub-Process, has a marker to show that it is used for compensation only and is **outside the normal flow** of the Process.

That's how it's specified - maybe not that clearly, but there is nothing reasonable that should be connected to a compensation activity except from maybe text annotations by using associations - but this is handled differently in the modeler anyway.

Maybe @falko can confirm?

**Comment by falko** [comment]
Compensation Activities can have Message Flows, Data Associations, and Associations for Text Annotations. So there are enough reasons to have the connection icon and correctly follows the connection rules. I would find it uncomfortable if I would be forced to always use the global connect tool for these connections.

**Comment by nikku** [comment]
Thanks for the clarification.

**Comment by benhoffmann** [comment]
I didn't think about messages and data flows, thanks for clarifying this @falko !
