### ISSUE TITLE
Automatically adjust javascript field to fit contents

### ISSUE THREAD

**Issue by ghost** [camunda/camunda-modeler#1131]
If you are trying to avoid java delegate code for like a camunda-app you possibly get a lot of javascript code. For better usability the java-content-field maybe automatically adjusts the content size.

**Comment by nikku** [comment]
Please update your issue, using one of the [issue templates provided](https://github.com/camunda/camunda-modeler/issues/new/choose). Add the relevant information that provide the necessary context. As an example, a screenshot would help us tremendously to understand which _javascript field_ you're referring to.

**Comment by nikku** [comment]
Closing as duplicate of #1139.
