### ISSUE TITLE
Plugins stored in userData directory can't access static resources

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1135]
__Describe the Bug__

`Failed to load resource: net::ERR_FILE_NOT_FOUND` error thrown even though logo is in the plugin directory.

__Steps to Reproduce__

1. Create a plugin from https://github.com/camunda/camunda-modeler-plugins
2. Drop plug-in into `${userData}/plugins` 
3. Open BPMN editor
4. Check console

__Expected Behavior__

No error and image attached.

__Environment__

Please complete the following information:

 - OS: Any
 - Camunda Modeler Version: 2.2.4, 3.0.0-0

---

__Solution Approach__

Based on [this comment](https://github.com/camunda/camunda-modeler/issues/1135#issuecomment-456843972), the following sketches the solution to this problem:

* Let plug-ins load resources via custom protocol, i.e. `foobar://${pluginName}/${nameOfResource}`
* Intercept loading of these resources via [webrequest filter](https://electronjs.org/docs/api/webhttps://github.com/camunda/camunda-modeler/issues/1135#issuecomment-456843972-request), figure out actual plugin folder and redirect to the appropriate `file://...` url

**Comment by nikku** [comment]
Affects any OS, as long as the plug-in is stored in the userData directory (the only way to store plug-ins on MacOS; no workaround exists on that platform). I updated the issue accordingly.
