### ISSUE TITLE
Element / collection variables lost when morphing from Parallel to Sequential Multi Instance

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#114]
__Describe the Bug__

Changing a Sub Process in from sequential to parallel multi instance drops the multi-instance related configuration.

__Steps to Reproduce__

1. Open [test diagram](https://github.com/camunda/camunda-modeler/files/5494525/mi-subprocess.bpmn.txt)
2. Change sub-process from parallel multi instance to sequential multi instance via the wrench menu
3. The multi-instance related information is gone

__Expected Behavior__

The multi instance related information is kept, where applicable.

__Environment__

- OS: All
- Camunda Modeler Version: v4.4.0

**Comment by nikku** [comment]
Should get fixed via bpmn-io/bpmn-js#415

**Comment by falko** [comment]
I experienced this today in 1.11.3 at an EE customer.

**Comment by smbea** [comment]
Duplicate of https://github.com/bpmn-io/bpmn-js/issues/1581
