### ISSUE TITLE
Property panel: process id and process name are not aligned

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#1151]
__Describe the Bug__

The process name is not aligned to the process id. I tried to delete the space, but there is nothing to delete.

![grafik](https://user-images.githubusercontent.com/7870843/52047931-61cad080-254a-11e9-8957-7126ff3c12e5.png)

__Steps to Reproduce__

1. create a new bpmn diagram
2. open the property panel and fill in a process id and a process name

__Expected Behavior__

both field values should be vertically aligned.

__Environment__

Please complete the following information:

 - OS: Windows 10
 - Camunda Modeler Version: 3.0.0-0

---

Related to [SUPPORT-5965](https://app.camunda.com/jira/browse/SUPPORT-5965)

**Comment by nikku** [comment]
Thanks for the report.

**Comment by mschoe** [comment]
this applies to the following fields too:
- Element Documentation
- Listeners > Field Injection > Value
- Input/Output > Input Paramter > Value
- Input/Output > Output Paramter > Value

**Comment by nikku** [comment]
Fixed with recent modeler release.

**Comment by nikku** [comment]
Pending properties panel releases:

* dmn-js
* bpmn-js
* cmmn-js

**Comment by nikku** [comment]
@kurtudis Thanks for adding the label `channel:support`. Could you link the relevant support case, too?

**Comment by kurtudis** [comment]
> @kurtudis Thanks for adding the label `channel:support`. Could you link the relevant support case, too?

relates to https://app.camunda.com/jira/browse/SUPPORT-5965

**Comment by nikku** [comment]
Thanks! I've updated the issue description accordingly.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1411#pullrequestreview-253232169
