### ISSUE TITLE
Add deployment source as Camunda Modeler

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#1153]
__Is your feature request related to a problem? Please describe.__

When I deploy a process from the modeler, I could not find any hint where the process definition comes from. Source is null.

![grafik](https://user-images.githubusercontent.com/7870843/52050707-adcd4380-2551-11e9-8b77-cb4f0e7c8557.png)

__Describe the solution you'd like__

I would like to see on the deployment page in Camunda cockpit, that the deployment was done from the Camunda Modeler

__Describe alternatives you've considered__

this is 'Alternativlos'

__Additional context__

Solution is to add a form field name=depolyment-source, value=Camunda Modeler (maybe the version, if it's available). Should be an easy pick.

**Comment by nikku** [comment]
It is indeed an easy pick that is worth implementing right now.

We can refine the source string in the future, possibly adding version, env, ...

![image](https://user-images.githubusercontent.com/58601/52053929-0ead4980-255b-11e9-8f5f-e1f2fcfa5fcf.png)

**Comment by nikku** [comment]
Will be addressed via https://github.com/camunda/camunda-modeler/pull/1154.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1154

**Comment by ingorichtsmeier** [comment]
Great, Thank you. What are your plans to release a new preview version where this is included?

**Comment by nikku** [comment]
Next pre-release is [pending a few issues](https://github.com/camunda/camunda-modeler/issues/1116).
