### ISSUE TITLE
Modeler fails to start with <#> in folder path

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1158]
__Steps to Reproduce__

* Download Camunda Modeler
* Extract to path with `#` in the name
* Run
* __Modeler shows white canvas__

__Expected Behavior__

* [ ] Modeler is able to handle `#` in path
* [ ] Modeler plug-ins work with `#` in folder names

__Alternative Solutions__

* Show a message that `#` in folder names are not supported

__Environment__

* Camunda Modeler Version: v2.x, v3.x
* Operating System: Any (confirmed on Windows and Linux)

__Additional Context__

The issue is that we do not properly escape `#` in the file we tell the app to open (cf. https://github.com/camunda/camunda-modeler/blob/master/app/lib/index.js#L328).

This results in the client opening for the URL `file://parts-before-hash`.

Unfortunately we cannot simply escape all hashes, as these may be used as actual path to search delimiters, too. Example: As anchors in SVGs (cf. https://github.com/camunda/camunda-modeler/blob/master/client/src/app/primitives/icon/Icon.less#L4).

---

Referenced via [`SUPPORT-5362`](https://app.camunda.com/jira/browse/SUPPORT-5362)

**Comment by nikku** [comment]
We are not going to address this issue any time soon. A simple workaround exists: Move the modeler into a path without a `#` and you are going to be :cool:.

**Comment by yT0n1** [comment]
FYI, we just had this issue in a training. A descriptive error message would have been helpful in that case. Maybe it is possible to do a sanity check, by checking if a certain file exists?

**Comment by nikku** [comment]
@yT0n1 Happy to take contributions that improve the situation.

We do regard `#` in folder names as edge cases and, thus, decided to close this one as _won't fix_ a while back.

**Comment by yT0n1** [comment]
@nikku Just wanted to let you know, that this does happen in the wild and can cause confusion 😉. I agree it is an edge case. I'll leave it to you to decide if it remains _won't fix_
