### ISSUE TITLE
Cursor auto-moves to end of Expression Inputs

### ISSUE THREAD

**Issue by julrichkieffer** [camunda/camunda-modeler#116]
OS: MacOS X Yosemite (10.10.5)
Browser: Chrome 47.0.2526.106 (64-bit)

In the Modeller's property panel, when typing '$' or '{', the input cursor automatically moves to the end of the current value.  This behaviour is benign when first populating the Expression field. But when editing an existing expression, it gives rise to input errors.

I suggest 2 alternate solutions:
1.  Either disable the cursor-to-end behaviour when there is already an expression (ie editing)
2.  Or have the cursor-to-end behaviour trigger only on the '{' key (ie not '$')

**Comment by nikku** [comment]
Closed via #101

**Comment by nikku** [comment]
If you'd like to be sure whether an issue has already been addressed, check our [nightly builds](https://camunda.org/release/camunda-modeler/nightly/) or search the closed issue for the Camunda Modeler.
