### ISSUE TITLE
Error on open last tab when there is no last tab

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1173]
__Describe the Bug__

When the user clicks on `Reopen Last File` in the menu (or press `Shift + Cmd/Ctrl + T`) on a new modeler instance (or when no tab was closed before), nothing happens. Instead of there is an [(intended) error](https://github.com/camunda/camunda-modeler/blob/master/client/src/app/App.js#L1120) thrown. It might be better to just disable the menu action.

__Steps to Reproduce__

1. Open new modeler
2. File ->  `Reopen Last File`, or press `Shift + Cmd/Ctrl + T` 

__Expected Behavior__

* [ ] Menu action is disabled, if no last tab exists

__Environment__

Please complete the following information:

 - OS: MacOS 10.14
 - Camunda Modeler Version: 3.0.0 (current `master`)

**Comment by nikku** [comment]
What is the impact? Does the log open? Does the app break? Depending on this we should decide whether or not to add it to [our next release](https://github.com/camunda/camunda-modeler/issues/1116).

**Comment by pinussilvestrus** [comment]
Neither nor. It's just showing inside the browser log (developer tools).

![image](https://user-images.githubusercontent.com/9433996/52343374-2b90c380-2a18-11e9-9459-351b9797b746.png)


So this doesn't seem to be too urgent right now. Maybe it's just confusing when the action is available but does not do anything in this case.
