### ISSUE TITLE
Remember previous window size / prevent open flicker

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1175]
__Description__

The modeler currently resizes / maximizes upon opening the main window. This results in flickering that makes me nervous all the time.

__Suggested Improvement__

* [ ] Remember previous window size and restore the modeler with the appropriate size

__Alternatives__

* Is there a better way to maximize the modeler main window upon start? If that is the case we could also improve the situation like that

__Environment__

* OS: Windows / Linux
* Modeler Version: any, including `3.0.0-0`

**Comment by barmac** [comment]
Duplicate of https://github.com/camunda/camunda-modeler/issues/576
