### ISSUE TITLE
Tab errors don't provide relevant context

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1176]
__Describe the Bug__

In the old version of the Camunda Modeler (v2.x) errors logged in the log panel would provide the relevant context (the file displayed in the tab that reported the error).

In the new version of the Modeler (v3) we simply display the error messages without providing the relevant context:

![image](https://user-images.githubusercontent.com/58601/52402813-803e4800-2ac5-11e9-9a3d-c4091dcd75c9.png)

__Steps to Reproduce__

* Open BPMN diagram
* _break it via XML tab_
* Import again
* See error message being logged without context information

__Expected Behavior__

* Error messages are logged with the relevant context attached:

    ```
    { path to displayed / opened file}
    { error messages }
    ```

__Environment__

Please complete the following information:

 - OS: Any
 - Camunda Modeler Version: 3.0.0-0

**Comment by pinussilvestrus** [comment]
Closed via #1284
