### ISSUE TITLE
Restore "Diagram opened with warnings" hint

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1177]
__Is your feature request related to a problem? Please describe.__

Camunda Modeler v2.x displayed a nice little warning to the user, if the diagram opened with errors.
That meant that the user had the choice to ignore the warning (which is fine to do) or inspect it in the logs.

![image](https://user-images.githubusercontent.com/58601/52402725-4e2ce600-2ac5-11e9-9b8d-b7a51504d724.png)

The current version of the modeler always opens the logs which may lead to confusion.

__Describe the solution you'd like__

* Restore old behavior: User may decide whether to see the warnings in the logs or simply ignore them

__Describe alternatives you've considered__

Accept new behavior.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1296
