### ISSUE TITLE
Details inside a collapsed subprocess should not be allowed

### ISSUE THREAD

**Issue by leolux** [camunda/camunda-modeler#118]
Collapsed sub-processes must not contain any visible children and must not allow addition of children.

Original question: https://network.camunda.org/forum/133

**Comment by nikku** [comment]
With a little bit of hacking the modeler currently allows this:

![image](https://cloud.githubusercontent.com/assets/58601/12537241/500fa91a-c2ba-11e5-93d1-3ac8767e76f4.png)

**Comment by pedesen** [comment]
Resolved via https://github.com/bpmn-io/bpmn-js/commit/e568312a68d7303dd06b3870b3cec1f038e4b6c2
