### ISSUE TITLE
Improve origin adjustment feature

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1183]
In order to limit the effect of this, could we also update the default template for new files to place the start event at x="140" y="188". Why that position? The x coordinate allows a start event with a maximally wide label to be visible when a model is opened and the palette uses two columns. The y coordinate allows using a standard-size embedded sub-process behind the start event without triggering the behavior implemented for this issue.

![20190209 camunda modeler 001](https://user-images.githubusercontent.com/40038/52522369-1c915780-2c4a-11e9-9a95-26a28b3d6b30.png)

In fact the x="140" should be the destination to move to, because otherwhise the two-column palette on small screens covers the start event or its label.

![20190209 selection 002](https://user-images.githubusercontent.com/40038/52522482-91b15c80-2c4b-11e9-8808-ed18a752d925.png)
![20190209 selection 003](https://user-images.githubusercontent.com/40038/52522484-94ac4d00-2c4b-11e9-8c32-86b83e6da980.png)

Furthermore, I think the 'Move to origin' should be aligned with this, because otherwise users that used 'Move to origin' will have a hard time moving their diagrams to a position where its start event is not hidden behind the palette when they open the file. Basically, their only chance would be to use the space tool or create new elements in negative areas, to trigger the behavior implemented for this issue.

_Originally posted by @falko in https://github.com/camunda/camunda-modeler/issues/982#issuecomment-462052615_

**Comment by nikku** [comment]
Thanks for your further input on the automatic alignment topic. Some remarks / questions:

> In order to limit the effect of this, could we also update the default template

I agree with you that we should minimize the initial noise that https://github.com/camunda/camunda-modeler/issues/982 is generating. https://github.com/camunda/camunda-modeler/pull/1186 adds additional measures to prevent re-positioning on minimal updates, e.g. labels being added / expanded to full width. It assumes the default offset of `(150, 150)`, taking into account your comment on the palette, too. You may checkout out [bpmn-io/align-to-origin](https://github.com/bpmn-io/align-to-origin), the actual utility being used under the hood.

> Furthermore, I think the 'Move to origin' should be aligned with this, because otherwise users that used 'Move to origin' will have a hard time moving their diagrams to a position where its start event is not hidden behind the palette when they open the file.

Is there a good reason to keep the manual alignment action around with the new feature being present? Pull request https://github.com/camunda/camunda-modeler/pull/1186 removes it if automatic alignment is set up.

**Comment by ingorichtsmeier** [comment]
If I want to export a diagram as picture, I didn't want to crop the picture manually afterwards.

The exported diagram should have a minimal border.

Maybe this implemented already, I want to make you to have this in mind when deciding how to progress.

**Comment by nikku** [comment]
> If I want to export a diagram as picture, I didn't want to crop the picture manually afterwards.

The diagram will always be exported with a minimal border only.

**Comment by ingorichtsmeier** [comment]
Thank you for the clarification

**Comment by pinussilvestrus** [comment]
Closed via #1186

**Comment by falko** [comment]
> Is there a good reason to keep the manual alignment action around with the new feature being present? Pull request #1186 removes it if automatic alignment is set up.

Yes, since the auto re-alignment is only triggered when elements are in the negative space, there might still be a use case, where one wants to bring a model that is too far down or too far right back to the "sweet spot" in the upper left corner.

**Comment by nikku** [comment]
> Yes, since the auto re-alignment is only triggered when elements are in the negative space.

Automatic re-alignment is triggered all the time, as soon as diagrams are away from the _sweet spot_ you mention by a considerable offset, cf. [this visualization](https://github.com/bpmn-io/align-to-origin#readme).

From my point of view this makes the move-to-origin feature obsolete. Let's wait for additional feedback regarding this and incorporate it.

**Comment by nikku** [comment]
Especially due to the fact that the used does not know if a diagram is _too far down_ anymore makes it hard to argue for the move-to-origin feature to be accessible.

**Comment by falko** [comment]
Okay, let's see how it feels.
