### ISSUE TITLE
As a user I am able to distinguish files by save location

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1187]
__Is your feature request related to a problem? Please describe.__

As a user I usually got multiple diagrams open, sometimes these diagrams even have the same names.
I am always frustrated when I'd like to understand which diagram (opened in the modeler) corresponds with which file on disk.

__Describe the solution you'd like__

* [x] Show path to diagram when hovering diagram title
* [ ] Show `~` prefix for user home on non-Windows operating systems (moved to https://github.com/camunda/camunda-modeler/issues/1191)

__Describe alternatives you've considered__

No real alternatives.

__Additional context__

* Editors commonly display the diagram path on hover
* On Mac OS and Linux the user home is commonly abbreviated to `~`
* Not available in Camunda Modeler `v2.x`, too

**Comment by pinussilvestrus** [comment]
Closed via #1190.

Second task described in description is going to be implemented by #1191.
