### ISSUE TITLE
Make Call Activity clickable

### ISSUE THREAD

**Issue by leolux** [camunda/camunda-modeler#119]
If it would be possible to link a Call Activity to the corresponding called element (inspecting only the files currently opened in the modeler and making simple assumptions about element bindings) it would be a very nice to feature to make that link clickable. So a double-click would open the called element directly.

**Comment by nikku** [comment]
We will work on the whole topic at some point, maybe also taking something like a "workspace" or folder for searching into account.

I like the idea of only considering currently open elements, too!

**Comment by nikku** [comment]
Related to https://github.com/camunda/camunda-modeler/issues/112.

**Comment by nikku** [comment]
Closing this in favor of #112.
