### ISSUE TITLE
No error dialog when broken diagram is opened

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1192]
__Describe the Bug__

When I open a broken diagram or break the diagram in XML tab, Camunda Modeler shows a never ending loading indicator. There is no error dialog.

__Steps to Reproduce__

1. Open a broken diagram.
2. ...

or

1. Open a valid diagram.
2. Break it in XML tab.
3. Open the diagram tab.

__Expected Behavior__

An error dialog is shown.

__Environment__

Please complete the following information:

 - OS: MacOS
 - Camunda Modeler Version: `master`

**Comment by barmac** [comment]
It seems that the problem is caused by an unhandled exception when the namespace url is checked: https://github.com/camunda/camunda-modeler/commit/c7f06ab992de74722a25329fb44d4ed46bb09681#diff-c8076a7c2e47036acdb6ea50cef6d96fR339

**Comment by barmac** [comment]
Currently, we parse XML twice:
1) to check whether the namespace should be changed (https://github.com/camunda/camunda-modeler/blob/master/client/src/app/tabs/bpmn/util/namespace.js#L46)
2) to actually import and draw the diagram

This leads to a problem that we need to handle import errors in the namespace related code. Also, parsing and serializing XML twice is a performance overhead that we might want to avoid.

In Camunda Modeler before refactoring, we used to replace properties in the XML string with RegEx (https://github.com/camunda/camunda-modeler/blob/v2.2.4/client/lib/app/util/namespace.js#L69). This may lead to a situation that we replace the namespace and then it occurs that the diagram is broken so it can't be imported anyway.

The third potential solution which feels the best for me would be to ask the user whether they want to replace the namespace after the XML was parsed but before drawing the diagram. However, the import utility in bpmn-js allows to manipulate the definitions only in a blocking way (https://github.com/bpmn-io/bpmn-js/blob/master/lib/Viewer.js#L168), so it seems we would have to modify `Modeler#importDefinitions` to walk the definitions tree and replace what we need before drawing.

@nikku Can you please share your opinion on this matter?

**Comment by nikku** [comment]
[`parseDiagramType.js`](https://github.com/camunda/camunda-modeler/blob/master/client/src/app/util/parseDiagramType.js) sketches a simple and safe way to start parsing a diagram to figure out certain pieces of information. We should follow that approach and properly handle errors during namespace parsing (i.e. just pretend there is no conversion required).

**Comment by barmac** [comment]
In the current wip commit, namespace conversion works pretty well, but the dirty state is broken again. Once user agrees on conversion, the diagram remains clean due to our [dirty check](https://github.com/camunda/camunda-modeler/blob/master/client/src/app/tabs/bpmn/BpmnEditor.js#L392): 
```javascript
  isDirty() {
    const {
      modeler,
      stackIdx
    } = this.getCached();

    const commandStack = modeler.get('commandStack');

    return commandStack._stackIdx !== stackIdx;
  }
```

Newly imported diagram will never be dirty, because the cached stackIdx is always [set to the current one](https://github.com/camunda/camunda-modeler/blob/master/client/src/app/tabs/bpmn/BpmnEditor.js#L298) once the import succeeds: 
```javascript
  handleImport = (error, warnings) => {
    const {
      onImport,
      xml
    } = this.props;

    const modeler = this.getModeler();

    const commandStack = modeler.get('commandStack');

    const stackIdx = commandStack._stackIdx;

    onImport(error, warnings);

    if (!error) {
      this.setCached({
        lastXML: xml,
        stackIdx
      });

      this.setState({
        importing: false
      });
    }
  }
```

What we could do now is to introduce a force dirty cache value, but this smells dirty to me. Maybe I'll figure out some other solution. I'm open for suggestions.

**Comment by pinussilvestrus** [comment]
Pretty interesting that #1228 inside the DMNEditor is also caused by a wrong `stackIdx` value inside the cache (I'll follow up with more information next week). Maybe we have the chance here to investigate for some improvements to achieve a better way of dirty checking via the commandStack stack index.

**Comment by barmac** [comment]
Instead of modifying definitions, I'll just prepare a regex to replace prefixes and namespace params.
