### ISSUE TITLE
Token simulation not working with v3.0.0

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1193]
* [ ] It does not turn off (https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/15)
* [x] It turns on when typing `T` (https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/14), #1275

**Comment by pinussilvestrus** [comment]
Tried to reproduce the broken behaviors on MacOS 10.14.3.

- https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/15: I was able to turn the simulation off with pressing 'T' anywhere. Can't reproduce the misleading behavior.
- https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/14: was able to reproduce the bug

**Comment by nikku** [comment]
Should work on next nightly with latest token simulation.

**Comment by pinussilvestrus** [comment]
💪🏻
