### ISSUE TITLE
Improve sequence flow segment move

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1197]
It is hard to hit the parallel movement handle due to the fact that it quite short.

![sequence flow move handle](https://user-images.githubusercontent.com/232571/52638734-e6b2d400-2ed2-11e9-9268-65deb3c7ddbc.gif)

__Solution__

* [ ] Activate segment move on two thirds of the segment (counted from middle). 
* [ ] Ensure there is always a small draggable area on the start and end of a segment to create a new bendpoint from

__Alternative Solutions__

* Add modifier key to trigger either parallel move or bendpoint move (not really an alternative, but an additional feature)

__Context__

This needs a fix in [diagram-js `Bendpoints`](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/bendpoints/Bendpoints.js).

```
// when
I try to move a sequence flow in parallel

// then
it is hard to hit the parallel movement handle
```

**Comment by nikku** [comment]
Any idea how to improve the situation?

**Comment by volkergersabeck** [comment]
make the parallel movement handle at least 2/3 of the length of the line segment

**Comment by nikku** [comment]
Thanks for your feedback.

**Comment by pinussilvestrus** [comment]
Fixed upstream (cf. [`bpmn-io/diagram-js#30bfb94`](https://github.com/bpmn-io/diagram-js/commit/30bfb9401c02e1eb14949b2ee95e6852da4d7c2c))
