### ISSUE TITLE
Bend point not deleted after relayouting sequence flow (attached to boundary event)

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1204]
// given
see attached screen cast

// when
I move an element on bend point

// then
the sequence flow is attached from the wrong side to the element. The bend point is not deleted.

![1204 move task of boundary event breaks sequence flow layout](https://user-images.githubusercontent.com/232571/52640554-0ba94600-2ed7-11e9-93bb-e0275b2e836c.gif)

---

Depends on https://github.com/bpmn-io/bpmn-js/issues/891

**Comment by barmac** [comment]
Will be adressed via https://github.com/bpmn-io/bpmn-js/pull/994

**Comment by pinussilvestrus** [comment]
Closed via aafbda44795d7e2c0bb00aa8a4bbe81956b17b1b
