### ISSUE TITLE
Improve label positioning of boundary events

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1206]
// given
see attached screenshot

// when
I add a label for a boundary event

// then
the label will be placed on top of the event which is in most cases inside the parent activity. The label has to removed manually afterwards.

![1206 boundary event label position](https://user-images.githubusercontent.com/232571/52641081-655e4000-2ed8-11e9-9197-4b5e7bdd736a.gif)

__Expected Behavior__

* [ ] Consider boundary events and their docking when calculating label positions in [`AutoPlace`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/auto-place/AutoPlace.js)
* [ ] Do not place labels onto the target element (or its border)

In the particular case, keep the label at the default position.

**Comment by nikku** [comment]
We do not properly handle that case in our auto-placement algorithm.

In the described situation I'd assume that the label is not moved at all (as there is no apparent _good_ place to put it anyway.

**Comment by pinussilvestrus** [comment]
We should consider improving the situation in the [`AdaptiveLabelPositioningBehavior`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/behavior/AdaptiveLabelPositioningBehavior.js)

**Comment by pinussilvestrus** [comment]
Fixed upstream by [`bpmn-js#8862865 `](https://github.com/bpmn-io/bpmn-js/commit/8862865e2a6eafc884d61b1a3b02bdc2d5912c8b)

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1404.
