### ISSUE TITLE
Event and Gateway Label position should stick to the parent element when using the space tool

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1208]
// given
see attached screen cast

// when 
I use the space tool 

// then
I can move event and gateway labels without moving the parent element

// expected behavoir
The label position stays with the parent element position

![1208 event labels stick to parent element with space tool](https://user-images.githubusercontent.com/232571/52641600-81aeac80-2ed9-11e9-958b-92bc5e53a2ea.gif)

**Comment by nikku** [comment]
What is the rationale behind this feature request? Any other tools that adopt that kind of pattern?

**Comment by nikku** [comment]
We discussed this internally and decided the most predictable space tool behavior is the one that actually moves all affected elements.

Closing this issue as won't fix.
