### ISSUE TITLE
Improve auto layout of sequence flow when deleting an element

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1209]
// given
see attached screen cast

// when
I remove an element after an L-shaped sequence flow

// then
the sequence flow will be routed on the direct way to the next element and is not L-shaped anymore

![1209 auto layout of sequence flow when deleting intermediate event](https://user-images.githubusercontent.com/232571/52641998-6b552080-2eda-11e9-8d5b-e20495a1689c.gif)

---

Depends on https://github.com/bpmn-io/bpmn-js/issues/718

**Comment by nikku** [comment]
This is related to https://github.com/camunda/camunda-modeler/issues/672 and needs a fix via https://github.com/bpmn-io/bpmn-js/issues/718.

**Comment by barmac** [comment]
This will be fixed by https://github.com/bpmn-io/bpmn-js/pull/971

**Comment by pinussilvestrus** [comment]
Closed via aafbda44795d7e2c0bb00aa8a4bbe81956b17b1b
