### ISSUE TITLE
CallActivity#camunda:calledElementBinding is set to "undefined" in resulting BPMN 2.0 xml

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda-modeler#121]
**Steps to reproduce:**
1. Create a new bpmn diagram
2. Create a task
3. Change the task type to `CallActivity`
4. Choose `BPMN` as call activity type in the properties panel
5. Insert a random `Called Element`
6. Change call activity type to `CMMN`
7. Insert a random `Case Ref`
8. Save the diagram

**Problem:**
The resulting xml looks as follows:

```xml
<bpmn:callActivity id="CallActivity_06j10pv"
                   camunda:calledElementBinding="undefined"
                   camunda:caseRef="def"
                   camunda:caseBinding="latest" />
```

**Comment by nikku** [comment]
Did you address this in the properties panel?

**Comment by gimbel** [comment]
@romansmirnov Can you comment on this?

**Comment by romansmirnov** [comment]
@nikku This bug is already fixed on the current master by setting the default value instead of `undefined` in the properties-panel (see https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/parts/CallActivityProps.js#L35)
