### ISSUE TITLE
Adjust height of pool when toggle collapse/expand button

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1210]
// when
I collapse a pool

// then
* [ ] Then collapsed pool should be flat (`60px` in height).

![1210 pool collapsing](https://user-images.githubusercontent.com/232571/52642036-80ca4a80-2eda-11e9-967e-ba5f0e5e4dfc.gif)

**Comment by nikku** [comment]
Needs actual fix in [bpmn-js](https://github.com/bpmn-io/bpmn-js).

**Comment by gustavjf** [comment]
Following up on the conversation with @philippfromme and @mschoe, we've decided to set the size of expanded/collapsed pools to their default size.

Additionally, we will change the default width of a collapsed pool to match that of an expanded pool.

**Comment by gustavjf** [comment]
Reopening since the fix has not yet been released via bpmn-js.

**Comment by pinussilvestrus** [comment]
Closed via aafbda44795d7e2c0bb00aa8a4bbe81956b17b1b
