### ISSUE TITLE
Difficult to attach a message flow to a pool with lanes

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1213]
__Description__

You cannot conveniently connect message flows to participants with contained lanes right now:

![1213 connect message flow to pool with lanes](https://user-images.githubusercontent.com/232571/52642647-b0c61d80-2edb-11e9-9a1e-dff0352b257c.gif)

__Steps to Reproduce__

* Model Pool with Lanes
* Try to attach message flow to it
* Presence of lanes make it super difficult

__Expected Behavior__

* [ ] I can easily connect message flows to the pool borders, even in the presence of lanes

__Environment__

* Camunda Modeler `v2.x`

---

Depends on https://github.com/bpmn-io/bpmn-js/issues/950

**Comment by mitchhanks** [comment]
Is this issue related to it?
https://www.screencast.com/t/B4kNQG7VBA

**Comment by pinussilvestrus** [comment]
@mitchhanks I can't reproduce the behavior shown in the video. Can you maybe open [another issue](https://github.com/camunda/camunda-modeler/issues/new/choose) where you briefly describe the bug shown in your screencast?

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/f16835b4f31d6932ca2dc921e68d661db66e8242.
