### ISSUE TITLE
Improve Tab Error handling

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1214]
__Is your feature request related to a problem? Please describe.__

Tabs may throw errors and technically we got the [`EditorTab`](https://github.com/camunda/camunda-modeler/blob/master/client/src/app/tabs/EditorTab.js#L20) to handle errors gracefully and propagate them. Unfortunately triggering an actual error, e.g. by inserting a line such as

```
throw new Error('FOO');
```

into a tab constructor, e.g. the `BpmnTab` is not properly handled and results in the app being unmounted.

__Describe the solution you'd like__

* [ ] Tab errors are handled gracefully
* [ ] Logged to log panel
* [ ] A error placeholder is shown to the user in place of the defective tab

__Describe alternatives you've considered__

None.

**Comment by barmac** [comment]
The reason why we don't handle errors gracefully is that `EditorTab` is an incomplete error boundary. Namely, it does not implement `static getDerivedStateFromError`. 
Cf. https://reactjs.org/docs/error-boundaries.html; also this codesandbox https://codesandbox.io/s/202l1xyk0r?fontsize=14

**Comment by nikku** [comment]
> The reason why we don't handle errors gracefully is that `EditorTab` is an incomplete error boundary. Namely, it does not implement `static getDerivedStateFromError`.

We don't have to implement `getDerivedStateFromError`. It should be sufficient to unmount the broken editor (replacing it with an ErrorTab or the like).

**Comment by nikku** [comment]
Suggestion: Find an icon to make someones day, if the editor fails, e.g. https://thenounproject.com/term/open-source/?search=error

Caveat: We need to make sure we use free icons or provide proper attribution.

**Comment by barmac** [comment]
Notice: Enzyme does not support `getDerivedStateFromError` yet (https://github.com/airbnb/enzyme/issues/1553#1797). Because of this, the tests will be a bit different from what we already have in our code base.
