### ISSUE TITLE
Multiple undo/redo trigger necessary using BPMN after adding label

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1218]
__Describe the Bug__

The moment I added a label to an element undo / redo via keyboard shortcut does not work reliably anymore.

__Steps to Reproduce__

* create new diagram
* add label to start event
* try undo via `CTRL+Z`

__Expected Behavior__

* [ ] Undo / Redo work immediately

__Environment__

OS: Win 10, Linux
Camunda Modeler Version: `v3.0.0-beta.0`

__Hint__

* The problem is persistent; I must restart the modeler to restore the fixed behavior.
* Undo/Redo work fine using the menu / the toolbar buttons
* The problem occurs as soon as someone completes a direct editing operation. It seems like we're not properly registering / de-registering keyboard handlers.

**Comment by nikku** [comment]
Reproduced this and verified it is a regression from our `v2.2.4` release.

**Comment by pinussilvestrus** [comment]
I was _not_ able to reproduce it on MacOS 10.14.3.

![feb-14-2019 10-45-36](https://user-images.githubusercontent.com/9433996/52778189-b2135980-3045-11e9-9b9b-a75db2677e4b.gif)

**Comment by barmac** [comment]
The problem here is the Chromium's bug: https://bugs.chromium.org/p/chromium/issues/detail?id=566343
