### ISSUE TITLE
Position of sequence flow label out of range after using space tool

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1222]
__Describe the Bug__

The position of sequence flow labels is out of range after using the space tool

![sequenceflow_label_space_tool](https://user-images.githubusercontent.com/2777965/52714507-4e802200-2f9a-11e9-8950-ad48003e496b.gif)

__Steps to Reproduce__

See attached screen cast. 

when I use the space tool to enlarge a sequence flow
then the sequence flow label will be positioned beyond the range of the sequence flow.  

__Expected Behavior__

The label will not will not moved further than the sequence flow length

__Environment__

Please complete the following information:

 - OS: win10
 - Camunda Modeler Version: 3.0.0-beta-0

**Comment by pinussilvestrus** [comment]
This seems to be the consequence of [another bug inside `bpmn-js`](https://github.com/bpmn-io/bpmn-js/issues/878)
