### ISSUE TITLE
Missing listener after copying pool

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1223]
__Describe the Bug__

Listener is missing after copying a pool

__Steps to Reproduce__

- create a pool and add a listener
- copy the pool

__Expected Behavior__

Listener will be copied too

__Environment__

Please complete the following information:

 - OS: win10
 - Camunda Modeler Version: 3.0.0-beta0

---

Depends on https://github.com/camunda/camunda-modeler/issues/1223

**Comment by mschoe** [comment]
related to #681 and #540

**Comment by nikku** [comment]
Fixed in Camunda Modeler 3.3+.
