### ISSUE TITLE
DMN input modal closes when highlighting input expression

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1225]
__Describe the Bug__

Input modal view will be closed when highlighting text in the input expression field when the mouse will be moved out of the modal size

![textmarker](https://user-images.githubusercontent.com/2777965/52719214-745ef400-2fa5-11e9-8c9d-a6bc21788217.gif)

__Steps to Reproduce__

- Open the input modal view in the dmn editor
- move the mouse to the input expression field
- press the mouse button
- highlight the text in the input expression field
- move the mouse beyond the border of the modal view
- release the mouse button

--> the modal view will be closed

__Expected Behavior__

modal view will not be closed

__Environment__

Please complete the following information:

 - OS: win10
 - Camunda Modeler Version: 3.0.0-beta-0

**Comment by pinussilvestrus** [comment]
Was able to reproduce it on MacOS 10.14.3.

**Comment by pinussilvestrus** [comment]
This might need a fix inside [`dmn-js`](https://github.com/bpmn-io/dmn-js).

**Comment by barmac** [comment]
I was able to reproduce it on Camunda Modeler 2.2.4. @mschoe can you please confirm it? In that case we'll remove it from the current milestone as it's not a regression.

**Comment by nikku** [comment]
@barmac It is not a regression indeed but a bug long present in the dmn-js toolkit.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1593.
