### ISSUE TITLE
I can edit extensionElements on the process level

### ISSUE THREAD

**Issue by jhorstmann** [camunda/camunda-modeler#123]
Especially the `camunda:properties` that can be edited using the eclipse based modeler.

**Comment by gimbel** [comment]
This issue is related to the properties panel: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/118

**Comment by nikku** [comment]
@pedesen Did we implement this?

**Comment by nikku** [comment]
Implemented as it seems.
