### ISSUE TITLE
Notify third parties for changes in the license book

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1235]
As part of our license process we must notify third parties, e.g. LEGAL with every change in the license book (or with every release we ship that may introduce changes in the license book).

Carried out as a post-release step, cf. [`SRE-403`](https://app.camunda.com/jira/browse/SRE-403).

**Comment by nikku** [comment]
Ideas: 

* Sending mails via [nodemailer](https://nodemailer.com)

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1305
