### ISSUE TITLE
Standard Event Label is not connected to cmmn sequence flow

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1236]
__Describe the Bug__

In cmmn I can display the standard event for a connection. If I change the connection layout the event label remains on its initial position and I have to move it in a second step.

![event_label](https://user-images.githubusercontent.com/2777965/52780269-17694980-304a-11e9-9f6c-4f5b09dc354e.gif)

__Steps to Reproduce__

- Connect two tasks
- Enable the 'Show Standard Event' checkbox
- Move on task like in the screen cast

__Expected Behavior__

Like sequence flow labels in bpmn the event label should be connected to cmmn connection

__Environment__

 - OS: win10
 - Camunda Modeler Version: 3.0.0-beta.0

**Comment by pinussilvestrus** [comment]
Was able to reproduce it inside the [demo](https://demo.bpmn.io/cmmn/new). It will probably need a fix in [`cmmn-js`](https://github.com/bpmn-io/cmmn-js).

**Comment by barmac** [comment]
We are not actively developing CMMN modeler anymore.
