### ISSUE TITLE
Plugins menu shows, despite no plug-ins registered

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1239]
__Describe the Bug__

* Given I got no plug-ins installed
* I don't need to see the plug-ins menu

This is a regression from `v2.x`.

__Screenshot__

![image](https://user-images.githubusercontent.com/58601/52847169-c15cda80-310b-11e9-89cc-9c846d6e4d5a.png)

__Environment__

 - OS: Linux
 - Camunda Modeler Version: v3.0.0-beta.2

**Comment by pinussilvestrus** [comment]
Closed via 15ffba6.
