### ISSUE TITLE
Unable to paste text within the Modeler on Mac

### ISSUE THREAD

**Issue by stefan7jahn** [camunda/camunda-modeler#124]
Hi together,

it is not possible to post anything from the clipboard into the camunda modeler. 
This would be a quite nice feature, because it's annoying to type every full path of a classname (for example com.agency.mypackage.mypackage.averylonglonglonglongclassname.java).

Best regards,
Stefan

**Comment by gimbel** [comment]
I am not able to repoduce this problem. Which operating system are you using?

**Comment by stefan7jahn** [comment]
ah sorry, forgot the operating system. I am using Mac OS X El Capitan v. 10.11.3

**Comment by nikku** [comment]
Already closed in latest nightly I guess: #105
