### ISSUE TITLE
Improve batch closing of all tabs

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1240]
__Is your feature request related to a problem? Please describe.__

Given I have a number of tabs open and I'd like to close them in a batch, e.g. via `Close All Tabs` or when closing the application.

In these cases there is a lot of unnecessary tab loading / dirty checking going on.

__Describe the solution you'd like__

During the tab closing process...

* [ ] Do not open tabs that have not previously been opened
* [ ] Do not perform the dirty check if the next thing we're going to do is closing the tab
* [ ] Do not open tabs that are not dirty

__Describe alternatives you've considered__

No real alternatives.

---

Related to [`SUPPORT-5401`](https://app.camunda.com/jira/browse/SUPPORT-5401).

**Comment by pinussilvestrus** [comment]
We have a big chance here to improve some crucial dirty check workflows here. Should we pull it in our current (or even next) milestone?

**Comment by nikku** [comment]
How much is broken right now? I'd suggest we create a test case that verifies the above first and assert how much is actuall broken.

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2709
