### ISSUE TITLE
Add subprocess with start event included

### ISSUE THREAD

**Issue by volkergersabeck** [camunda/camunda-modeler#1242]
Sub-Processes with contents _always_ require a single start event. Right now, the user needs to manually add it every time she creates a new expanded sub-process:

![1242 add subprocess with start event](https://user-images.githubusercontent.com/232571/52943603-c91bb980-336d-11e9-923b-995020ddd346.gif)

__Expected Behavior__

* [ ] When adding an expanded subprocess from the palette, always add a start event to it.
* [ ] When transforming a task to an expanded sub-process, add a start event to it

To be discussed: Do we want to extend this behavior, i.e. add the start event  for collapsed sub processes, too?

**Comment by nikku** [comment]
Implemented upstream.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1404.
