### ISSUE TITLE
Turn start event into message start when adding a message flow

### ISSUE THREAD

**Issue by volkergersabeck** [camunda/camunda-modeler#1245]
When the user connects a message flow with a none start event
Then turn that none start event into a message start event

Same could apply for end events and outgoing message flows.

![1245 turn start event into message start when message gets attached](https://user-images.githubusercontent.com/232571/52943992-b35ac400-336e-11e9-90a4-1c613a3f9fc4.gif)

**Comment by nikku** [comment]
Thanks for reporting this issue.

I'll close it as a duplicate of the more general enhancement described in https://github.com/camunda/camunda-modeler/issues/914.
