### ISSUE TITLE
Copy / Paste in DMN is broken

### ISSUE THREAD

**Issue by volkergersabeck** [camunda/camunda-modeler#1246]
When a user edits a DMN table
And the user copies and pastes a DMN row into the table
Then the system copy paste does not work anymore
And pressing cmd+v adds the DMN row again into the table

Expected behaviour: when pressing cmd+v the text from a different application (Numbers in this case) is pasted into the cell.

![1246 copy paste in dmn is broken](https://user-images.githubusercontent.com/232571/52945755-c2437580-3372-11e9-9d43-969a04194d4e.gif)

---

Related to https://github.com/camunda/camunda-modeler/issues/1262

**Comment by volkergersabeck** [comment]
One idea could be to only offer to duplicate DMN rows or columns and not have a specific copy/paste. Then the only copy/paste would be the system default one and it would not interfere with the DMN copy/paste.
For the user, the goal of pasting a DMN row in the same table would be possible via duplicate and move instead of copy and paste. What would not be possible is a copy/paste of entire rows across different files.

**Comment by nikku** [comment]
Integrating with native copy and paste could be an appropriate measure to circumvent this bug. I've created https://github.com/camunda/camunda-modeler/issues/1262 to track that improvement.
