### ISSUE TITLE
DMN column labels are not default input

### ISSUE THREAD

**Issue by volkergersabeck** [camunda/camunda-modeler#1247]
When a user starts creating a DMN table
And the user wants to label the input and output columns
Then the focused text input is the Input Expression for Input columns
Or no focused text input for Output columns

Expected behaviour: focus the label text inputs for both columns types, since this is what people starting a DMN will most likely want to fill in first.

![1247 dmn column labels default input](https://user-images.githubusercontent.com/232571/52946105-89f06700-3373-11e9-85bb-73308162c05a.gif)

**Comment by ingorichtsmeier** [comment]
There is an open pull request to sort this out: https://github.com/bpmn-io/dmn-js/pulls.

**Comment by barmac** [comment]
It will be adressed in https://github.com/bpmn-io/dmn-js/pull/395

**Comment by nikku** [comment]
Fixed in dmn-js. 

Needs library release + integration into modeler.

**Comment by pinussilvestrus** [comment]
Closed via latest dmn-js release (cf. https://github.com/camunda/camunda-modeler/commit/b18976450e43dc6e5071a8cfd242027b37a3ae89)
