### ISSUE TITLE
Automatically scroll canvas when creating new elements

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1249]
__Is your feature request related to a problem? Please describe.__

It may quite easily happen that new elements added to the diagram are placed not fully visible, either because they are placed above the current element (as seen below) or to the right (when using the auto-place functionality, e.g. to add a new task).

![ezgif com-crop 1](https://user-images.githubusercontent.com/58601/52949926-fa03ea80-337d-11e9-99ba-026fdec5b2ba.gif)

__Describe the solution you'd like__

I'd expect that the canvas automatically moves with the element, so that newly created elements are always fully visible (+ a reasonable padding).

__Describe alternatives you've considered__

Keep things as is, because we believe canvas movement may confuse users.

__Additional context__

* We already support automatic scrolling when inside a drag operation.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2246
