### ISSUE TITLE
Make all available tools available via modifier keys

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1250]
__Is your feature request related to a problem? Please describe.__

As an expert user of a number of desktop applications it does not feel native to press shortcuts such as `<l>` for lasso tool and `<g>` for global connect before a tool is activated. Instead, I'd like to start the related mouse interaction right away and activate distinguish the respective tool to activate via modifier key (`CTRL/CMD`, `SHIFT`, `ALT`) + context.

As an additional rationale [mode less user interfaces](https://en.wikipedia.org/wiki/Mode_(user_interface)) are said to be less error prone. 

__Describe the solution you'd like__

* Drop single letter keyboard shortcuts to toggle modes
* Each tool (Global Connect, Lasso Tool (currently `SHIFT`), Hand Tool (currently `CTRL`), Space Tool) is activated via a distinct modifier key

This should render https://github.com/camunda/camunda-modeler/issues/664 obsolete, too.

__Describe alternatives you've considered__

Keep existing behavior.

**Comment by barmac** [comment]
Shall we close this and https://github.com/camunda/camunda-modeler/issues/1251 as not planned? We are clearly going in another direction via https://github.com/camunda/camunda-modeler/pull/3479

**Comment by nikku** [comment]
I think it is OK to leave it open. Or we close https://github.com/camunda/camunda-modeler/issues/1251 with it.

**Comment by nikku** [comment]
Cf. https://github.com/camunda/camunda-modeler/issues/1250#issuecomment-1446064076
