### ISSUE TITLE
Cannot move any Element

### ISSUE THREAD

**Issue by jwhoeche** [camunda/camunda-modeler#1256]
__Describe the Bug__

I cannot move any elements in the modeler. 
If I try it the elements will jump back to its start position.

Also the bounded events were shown under the task element. But it was possible to select the bounded event.

After a restart the moved element was not on the expected position.  The moved element was not in the view of the modeler. But after the restart it is possible to move the element to the right position and it works fine.

![bug](https://user-images.githubusercontent.com/6008420/53018327-618b6a00-3452-11e9-825a-058ca1d19b93.PNG)

__Environment__

Please complete the following information:

 - OS: Windows 10
 - Camunda Modeler Version: 3.0.0-beta.2

__LOG__

[bug.log](https://github.com/camunda/camunda-modeler/files/2880146/bug.log)

**Comment by jwhoeche** [comment]
[bug.log](https://github.com/camunda/camunda-modeler/files/2880146/bug.log)
![bug](https://user-images.githubusercontent.com/6008420/53018327-618b6a00-3452-11e9-825a-058ca1d19b93.PNG)

**Comment by nikku** [comment]
Could you provide us with the diagram you reproduced the error with? As indicated in the log it seems to be a layouting related issue that prevents the modeler from working.

We'd need your diagram to start with to see if we can create a reproducible test case for the behavior you describe.

**Comment by jwhoeche** [comment]
This was my starting process. 
I did not saved the version after the restart. Sorry. 

[payment-process_start.bpmn.txt](https://github.com/camunda/camunda-modeler/files/2880218/payment-process_start.bpmn.txt)

**Comment by nikku** [comment]
And what exactly did you model before the editor broke? Can you recall?

**Comment by jwhoeche** [comment]
I tried to model Error Boundary Event to task "Charge Credit card" and add a compensation boundary event to the task "Charge existing credit".  
I did some mistakes so I tried to undo some steps (ctrl+z).  I think at this moment the modeler stopped working well. When I tried to add the  compensation boundary event again the modeler did not work at all.

I added my solution of the exercise.
[payment-process - end.bpmn.txt](https://github.com/camunda/camunda-modeler/files/2880376/payment-process.-.end.bpmn.txt)

**Comment by nikku** [comment]
Thanks for your further feedback. An error such as the one you reported should not ever happen (and does not usually happen, too :wink:). 

We'll give it a try to reproduce the issue based on your additional input. Unfortunately we can only do so much, if we're not able to reproduce it.

**Comment by jwhoeche** [comment]
[log-windows.log](https://github.com/camunda/camunda-modeler/files/2884229/log-windows.log)

I am at the training with Ingo.  Maciej is here as well. He said I should attach the log of the application from Windows. The log file is copied from ..\AppData\Roaming\Camunda Modeler\logs.

**Comment by barmac** [comment]
Logs implicate a problem within Layout module, but unfortunately, I can't reproduce it. If you ever are able to reproduce the bug, please reopen this issue.
