### ISSUE TITLE
Process created is not executable per default

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1259]
__Description__

All processes created by the user in the Camunda Modeler should be executable. 

The [executable fix](https://github.com/camunda/camunda-modeler/tree/master/client/src/app/tabs/bpmn/modeler/features/executable-fix) we employ should take care of this.

--- 

_Originally posted by @nikku in https://github.com/camunda/camunda-modeler/issues/1258#issuecomment-465525241_

**Comment by nikku** [comment]
Original issue: https://github.com/camunda/camunda-modeler/issues/99

**Comment by ingorichtsmeier** [comment]
This is not a bug. As in Chapter 4.4.2 of Real-Life BPMN (3rd ed.) (Freund/Rücker) it makes sense to add pools that are not executable. See the diagram on page 129.

From my experinence, it's the exception to have more than one executable pool in the same diagram.

**Comment by nikku** [comment]
Thanks for your feedback @ingorichtsmeier. 

Closing this issue, as #99 was not ever about making all participants executable.
