### ISSUE TITLE
use text-anchor=middle for center aligned text rendering

### ISSUE THREAD

**Issue by volkergersabeck** [camunda/camunda-modeler#1261]
When rendering text in bpmn.js the position of each line is calculated with the actual text length in pixel. With the text-anchor attribute of svg text nodes, the x coordinate could be in the center of the line, such that the position needs not be calculated with the actual text length.

An additional benefit could be that right-to-left text would automatically be rendered within each bpmn node and not outside to the left of it.

**Comment by nikku** [comment]
Sounds like this issues is not related to the Camunda Modeler but rather belongs to bpmn-js. 

Is that the case? If so, [please open an issue](https://github.com/bpmn-io/bpmn-js/issues) in that issue tracker and we'll continue the discussion there.
