### ISSUE TITLE
Missing feedback when opening diagram

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1295]
__Description__

As a user I do not receive feedback, if I open files without a well-known extension:

![confusing](https://user-images.githubusercontent.com/28307541/53945792-abb35300-40c2-11e9-8ac0-065b4aad0e6a.gif)

__Reproduce__

* Create an empty file
* Rename it to `FOO.bpmn.txt`
* open it (via dropping or via file open)
* __No feedback is given to user__

__Expected Behavior__

* [x] We give appropriate feedback to a user for _any file_ that could not be opened

__Consideration__

We must ensure that the feedback is non-intrusive. If users batch-open files, should they still be able to do that efficiently.

_Originally posted by @barmac in https://github.com/camunda/camunda-modeler/pull/1292#issuecomment-470448645_

**Comment by philippfromme** [comment]
This has been fixed. I cannot reproduce this behavior anymore.

![drop-error-compressed](https://user-images.githubusercontent.com/7633572/54439109-6df4a100-4738-11e9-905a-92f7c6fe367c.gif)

**Comment by nikku** [comment]
:+1:
