### ISSUE TITLE
Changes get lost on save

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1298]
__Describe the Bug__

On the current nightly build, made changes inside any editor got lost when pressing on `save`. Furthermore, after this, when making more changes and saving the diagram again, the editor restores the state after the first save:

![Mar-13-2019 09-18-27](https://user-images.githubusercontent.com/9433996/54263387-017b7580-4571-11e9-9bd1-2923ac8f35f0.gif)

__Steps to Reproduce__

1. open any diagram, e.g. bpmn-file
2. make some changes inside the editor
3. press on save: old xml restored inside editor (before making the changes)
4. making more changes
5. press on save: xml after first save action is restored inside editor

__Expected Behavior__

It doesn't restore xml inside the editor on save action.

__Environment__

Please complete the following information:

 - OS: MacOS 10.14
 - Camunda Modeler Version: current nightly (master)

__Aditional Context__

* This bug is not present inside the latest pre-release `v3.0.0-beta.2`. 
* The changes are saved _correctly_ on disk. When closing and reopening the diagram, it shows the correct state.

**Comment by pinussilvestrus** [comment]
Seems like the error starts occuring with the import refactoring in all editors (e.g. bpmn cf. https://github.com/camunda/camunda-modeler/commit/b00ede8c1b81d57f7b9b6120437357e91c039bac).

**Comment by philippfromme** [comment]
It breaks the import that was initially fixed in [this commit](https://github.com/camunda/camunda-modeler/commit/05d8e4ab88a73b3027e3d908c5db79096d31b102#diff-c8076a7c2e47036acdb6ea50cef6d96f).

**Comment by pinussilvestrus** [comment]
Closed via #1299
