### ISSUE TITLE
Opening empty file error dialog is empty

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1301]
![dialog](https://user-images.githubusercontent.com/7633572/54281573-4962c280-459a-11e9-9e5d-9af51551db30.gif)

Hint: [`Dialog#showDialog`](https://github.com/camunda/camunda-modeler/blob/master/app/lib/dialog.js#L52) called with wrong arguments.

**Comment by pinussilvestrus** [comment]
Closed via #1303
