### ISSUE TITLE
DMN editor navigation broken

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1309]
Navigation through bottom tab links doesn't work.

![dmn-compressed](https://user-images.githubusercontent.com/7633572/54522462-95807f00-496d-11e9-8ad8-e9ac7dd7d148.gif)

**Comment by barmac** [comment]
I'm on it - found out that the bug got into 572a6412.

**Comment by philippfromme** [comment]
You simply threw away everything I implemented to fix this stuff in the first place. 😅


Kind Regards
Philipp Fromme
Software Developer
---------------------------------------------

Camunda Services GmbH

Zossener Str. 55 – 58

10961 Berlin

Telefon +49 30 664 04 09 - 00

---------------------------------------------
Amtsgericht Charlottenburg: HRB 113230 B
Geschäftsführer: Jakob Freund, Bernd Rücker

________________________________
Von: Maciej Barełkowski <notifications@github.com>
Gesendet: Montag, 18. März 2019 11:17
An: camunda/camunda-modeler
Cc: Philipp Fromme; Author
Betreff: Re: [camunda/camunda-modeler] DMN editor navigation broken (#1309)


I'm on it - found out that the bug got into 572a641<https://github.com/camunda/camunda-modeler/commit/572a641213fda72a0b7d775b9dd96a55df226673>.

**Comment by barmac** [comment]
...and the tests allowed me to do it 😓

**Comment by philippfromme** [comment]
A case for integration tests. 🔧🔨


Kind Regards
Philipp Fromme
Software Developer
---------------------------------------------

Camunda Services GmbH

Zossener Str. 55 – 58

10961 Berlin

Telefon +49 30 664 04 09 - 00

---------------------------------------------
Amtsgericht Charlottenburg: HRB 113230 B
Geschäftsführer: Jakob Freund, Bernd Rücker

________________________________
Von: Maciej Barełkowski <notifications@github.com>
Gesendet: Montag, 18. März 2019 11:45
An: camunda/camunda-modeler
Cc: Philipp Fromme; Author
Betreff: Re: [camunda/camunda-modeler] DMN editor navigation broken (#1309)


...and the tests allowed me to do it 😓

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1310
