### ISSUE TITLE
No feedback when dropping non-empty file

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1314]
![drop-compressed](https://user-images.githubusercontent.com/7633572/54601615-c204cb80-4a3f-11e9-83bb-4dbd175757da.gif)

__Steps to Reproduce__

1. Drop non-empty file (e.g. txt)

__Expected Behavior__

I get feedback that the file could not be opened.

__Actual Behavior__

I get NO feedback that the file could not be opened.

__Environment__

Please complete the following information:

 - OS: Windows 10
 - Camunda Modeler Version: 3.0.0-beta.3

**Comment by pinussilvestrus** [comment]
I was able to reproduce it on MacOS. Since the error does not crash, we do not have to fix inside the current release, I guess.

**Comment by philippfromme** [comment]
We simply [do not handle errors when opening existing files](https://github.com/camunda/camunda-modeler/blob/master/client/src/app/App.js#L658).
