### ISSUE TITLE
DMN navigation messed up when adding more than 8 decisions

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1317]
__Describe the Bug__

DMN navigation bar is messed up

__Steps to Reproduce__

// when 
I add more than 8 decisions to a DRD

// then
the navigation bar is not in order any more

![mod_dmn_navigation_01](https://user-images.githubusercontent.com/2777965/54611972-482d0c00-4a58-11e9-9fe0-44ef30486d3c.png)

![mod_dmn_navigation_02](https://user-images.githubusercontent.com/2777965/54611976-4a8f6600-4a58-11e9-9f9e-efa5778b3089.png)

__Expected Behavior__

navigation bar keeps the order

__Environment__
- Linux
- Camunda Modeler Version: 3.0.0-beta3

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1321
