### ISSUE TITLE
Copy&Paste changes label position of Boundary Events

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#1325]
__Describe the Bug__

![2019-03-20 Copy+Paste changes label position of Boundary Events](https://user-images.githubusercontent.com/40038/54701468-5c930680-4b35-11e9-90c8-adc8667d4d6f.png)

__Steps to Reproduce__

1. Create a boundary event and move its label
2. Copy&paste

__Expected Behavior__

Label position is maintained relative to the other copied elements

__Environment__

Please complete the following information:

 - OS: Ubuntu 18.04.2 LTS
 - Camunda Modeler Version: 3.0.0-nightly of 2019-03-20

This issue has been discovered during the preparation for the upcoming BPMN MIWG demo in June 2019 in Amsterdam.

**Comment by nikku** [comment]
This seems to be a boundary event related edge case, as copying and pasting work properly in many other cases I've tested.

Thanks for reporting.

**Comment by nikku** [comment]
Fixed via `bpmn-js@5`:

![capture Q3ne1n_optimized](https://user-images.githubusercontent.com/58601/62846448-99bc8880-bcd0-11e9-927a-6f6b54db4e45.gif)
