### ISSUE TITLE
Cannot collapse an embedded subprocess that has an event based subprocess within it

### ISSUE THREAD

**Issue by Camunda-ChrisAllen** [camunda/camunda-modeler#1328]
__Describe the Bug__

After collapsing an embedded subprocess that has an event based subprocess within it, the collapse shows some orphaned artifacts that did not get embedded.

__Steps to Reproduce__

1. create an embedded subprocess.  
2. create small basic model within it.  
3. add an event based subprocess within it.  
4. add a similar simple model within that.  
5. then try to collapse the embedded subprocess.  

__Expected Behavior__

everything gets collapsed

__Environment__

Please complete the following information:

 - OS: ubuntu linux 18.04
 - Camunda Modeler Version: 2.2.4

**Comment by nikku** [comment]
Thanks for reporting this issue.

Could you provide us with an example diagram that we can reproduce the described behavior with?

**Comment by Camunda-ChrisAllen** [comment]
[1328_example.zip](https://github.com/camunda/camunda-modeler/files/3003780/1328_example.zip)

Once you collapse the embedded subprocess, you will see that the content of the event subprocess does not fold with it.

HTH.

Chris

**Comment by pinussilvestrus** [comment]
I was able to reproduce this with your example diagram (thanks for sharing!)

![Apr-03-2019 09-32-23](https://user-images.githubusercontent.com/9433996/55460909-6e73af80-55f3-11e9-9f6c-a4c3f779cd98.gif)

This seems to belong with https://github.com/bpmn-io/bpmn-js/issues/925
