### ISSUE TITLE
Fix version display in bundled app

### ISSUE THREAD

**Issue by ricardomatias** [camunda/camunda-modeler#133]
* [ ] MacOS: Fix it in "About Camunda Modeler" menu entry (`info.plist` needs to be updated)
* [ ] Windows/Linux/MacOS:  fix it in the `version` file

At the moment the displayed version is from electron.

**Comment by nikku** [comment]
@ricardomatias Is this something we can already address and ship with the next Camunda Modeler release, `master` branch version?
