### ISSUE TITLE
I can define an Error Message for an error End Event

### ISSUE THREAD

**Issue by meyerdan** [camunda/camunda-modeler#1333]
## Scenario:

A user has two different Error End Events, each referencing a different `<error />` and a "catch-all" error start event in an event subprocess. Since the start event can catch two different errors, the user wants to reason about which error has been caught by the start event by storing error code and error message as variables. While it is currently possible to specify an error message when throwing an error from delegation code with `new BpmnError(code, message)` it is not possible to do so when defining the error end event.

![image](https://user-images.githubusercontent.com/488063/54981244-224bbe00-4fa8-11e9-8f28-fc51ab334ce2.png)

## Proposed solution

When selecting the error end event, I can provide an error message which is stored in the error definition:

```xml
<bpmn:error id="Error_1x1ymni" name="INVALID_DATA" errorCode="1231" camunda:errorMessage="The data provided is invalid" />
```

---
Related to [CAM-9994](https://app.camunda.com/jira/browse/CAM-9994), [SUPPORT-5568](https://app.camunda.com/jira/browse/SUPPORT-5568)

**Comment by volkergersabeck** [comment]
In our user test today, it was mentioned that one cannot edit the Error ID in the properties panel. Should this also be something the user can edit?

**Comment by ingorichtsmeier** [comment]
It's the same for message IDs, escalation IDs and signal IDs. 

I would vote against it as it is too confusing and developers will start referencing the IDs instead names in their code and will be frustated that it didn't work.

**Comment by nikku** [comment]
Pending release in bpmn-js-properties-panel (https://github.com/bpmn-io/bpmn-js-properties-panel/pull/313#pullrequestreview-272399902) and integration to app.
