### ISSUE TITLE
modeler icon missing after using xdg_register script

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1334]
__Describe the Bug__

Modeler icons in the main menu, panel and at window switch are missing

__Steps to Reproduce__

- execute xdg_register.sh
- open the modeler

__Expected Behavior__

Icons are visible

__Environment__

 - OS: linux mint 19
 - Camunda Modeler Version: 3.0.0

**Comment by nikku** [comment]
The icon files in `support` get corrupted during packaging.

Trying to open any of the files should result in an error / missing image.
