### ISSUE TITLE
Visual diffing of BPMN diagrams

### ISSUE THREAD

**Issue by asys3** [camunda/camunda-modeler#134]
__Tasks__

* [ ] As a User I am able to diff two versions of a process visually.
* [ ] Graphical diffing includes invisible properties (documentation, execution listeners and other `camunda` extensions).

__Note__

* Diffing could be based on [demo.bpmn.io/diff](http://demo.bpmn.io/diff).

---

See also [SUPPORT-2942](https://app.camunda.com/jira/browse/SUPPORT-2942).

**Comment by nikku** [comment]
We have no intend to provide diffing as a core feature of the Camunda Modeler, because of that I'll close this issue.

[Cawemo](http://cawemo.com), our collaborative, cloud-based modeling solution will soon ship with cross-version diagram diffing.

**Comment by renis1235** [comment]
FYI 
I wrote a plugin that does exactly this:

https://github.com/renis1235/camunda-modeler-diffing

**Comment by oliver-v** [comment]
We ran into the same thing and felt the need for such tool. At first we to included images of the model/property changes to the PRs (it worked but was very tedious, especially if there will be changes requested during the code review). Now we're in the process of building a GitHub App that does it automatically.

Still WIP, but if you're curious: [flowver.dev](https://www.flowver.dev/)
