### ISSUE TITLE
How do I embed Camunda Modeler into a browser

### ISSUE THREAD

**Issue by yujl** [camunda/camunda-modeler#1350]
How do I embed Camunda Modeler into a browser. I'd like to make the Camunda Modeler into my web app. not the bpmn-js,  i need the camunda bpmn js

**Comment by nikku** [comment]
Camunda modeler is a desktop application that is not meant to run in the browser.

Which exact parts do you need? We may help you to understand how to integrate them.

**Comment by yujl** [comment]
Which package is the thumbnail of the editor

**Comment by nikku** [comment]
Closing this issue as off-topic.

**Comment by caiohsfar** [comment]
Can i run the client folder into a browser?

**Comment by mingfang** [comment]
Why is the modeler a desktop app when web apps are much easier to deploy to a large team?
Please convert the modeler to be a web app

**Comment by philippfromme** [comment]
See my answer here: https://github.com/zeebe-io/zeebe-modeler/issues/127#issuecomment-541720686
