### ISSUE TITLE
Keyboard shortcuts menu crashes modeler 3.0.1

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#1357]
- Hit Help -> Keyboard Shortcuts menu
- a blank screen appears
- Modeler freezes

reproduced on Windows and Mac

**Comment by nikku** [comment]
Thanks for reporting.

Closing this as an exact duplicate of https://github.com/camunda/camunda-modeler/issues/1357.

We are working on a fix.

**Comment by benhoffmann** [comment]
The other issue is #1358, just for reference here.

**Comment by nikku** [comment]
Thanks for the pointer, I pasted the wrong issue link :wind_face:.
