### ISSUE TITLE
Modeler freezes when using menu Help-> Shortcuts

### ISSUE THREAD

**Issue by McAlm** [camunda/camunda-modeler#1358]
When clicking Menu Help-> Keyboard Shortcuts the modeler freezes and needs to be killed and restarted.

 - OS: Mac and Windows
 - Camunda Modeler Version: [3.0.1]

**Comment by nikku** [comment]
I can reproduce this on Linux, too.

**Comment by nikku** [comment]
I'm looking into the issue.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1361.

**Comment by nikku** [comment]
Released as [`v3.1.0`](https://github.com/camunda/camunda-modeler/releases/tag/v3.1.0)
