### ISSUE TITLE
I have JavaScript error when created flags.json in Resources folder

### ISSUE THREAD

**Issue by slizenko** [camunda/camunda-modeler#1363]
Error message:
![image](https://user-images.githubusercontent.com/50139137/56957174-f09db800-6b4e-11e9-8813-066e2a68cd19.png)

flags.json:
{
  "disable-plugins": false,
  "disable-adjust-origin": false,
  "disable-cmmn": false,
  "disable-dmn": false,
  "single-instance": false
}

Environment: 
- Windows 10 x64
- Camunda Modeler 3.1.0

**Comment by pinussilvestrus** [comment]
Hi @slizenko , thanks for sharing! This is definitely a bug, I found out that it came with the `single-instance` flag. I'll have a look at this.

**Comment by pinussilvestrus** [comment]
Update: I found the issue and opened a pull request (cf. #1364). 

After merged, it will prevent the app to crash with the `single-instance` flag set to false. We should consider shipping a patch release after it 🚀

**Comment by pinussilvestrus** [comment]
Closes via #1364 

@barmac @philippfromme should we ship a patch release with this fix (`v3.1.1`)?
