### ISSUE TITLE
Find in BPMN view deactivated in Modeler 3.1.0

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#1365]
I can no longer search for elements using Cmd-F in Diagram view. The Edit -> Find option is  disabled once I hit Cmd-F, but doesn't show the search bar. This seems to be a new problem.

Even more disturbing in combination with the ongoing problem that I cannot copy and paste in the XML view. Now I have to manually type the activity id from the exception message into the XML view to find problems in a diagram. Please bring copy & paste in XML back - is has been reported a while ago.

![May-06-2019 16-04-06](https://user-images.githubusercontent.com/17595149/57230474-b5046180-7018-11e9-97cb-04d3c47e4782.gif)

**Comment by pinussilvestrus** [comment]
I wasn't able to reproduce it on macOS 10.14:

![May-07-2019 08-36-18](https://user-images.githubusercontent.com/9433996/57276937-3f91a300-70a3-11e9-9bf6-c75023d0ac44.gif)

Are there any errors printed inside the Log Panel / the Developer Tools console / in the Application Log . Last option you're able to find in your local `Library/Logs/Camunda Modeler` directory.

The last thing you mentioned is disabled for a while ago. As you say, it is already reported (cf. https://github.com/camunda/camunda-modeler/issues/868), but seems to be not in our current roadmap.

**Comment by benhoffmann** [comment]
Hi @pinussilvestrus,

thanks for the reply. After a few modeler restarts, I can also not reproduce the issue anymore. Maybe that was some weird edge case. The log doesn't show anything unusual.

I think we can close this issue for now, I'll reopen it once it happens again and I find a way to reproduce.

Btw: Since 3.0, I keep getting uncaught exception messages when closing the modeler from time to time (at least once a week). This is unrelated to this issue, but another thing I haven't been able to reproduce yet.

**Comment by pinussilvestrus** [comment]
Thanks for the clarification! Yes, feel free to re-open if the error occurs again (same thing with the issues when modeler closes) 👍
