### ISSUE TITLE
Space Tool forces outgoing Flow around Sub-Process

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#1368]
__Describe the Bug__

Before Space Tool:
![2019-05-07 Space Tool in Sub-Process messes with outgoing Flow 01 before](https://user-images.githubusercontent.com/40038/57348553-c05da700-7156-11e9-8318-b0036edc23bc.png)

After Space Tool:
![2019-05-07 Space Tool in Sub-Process messes with outgoing Flow 02 after](https://user-images.githubusercontent.com/40038/57348554-c05da700-7156-11e9-8a51-50fca70684c8.png)

Using the Space Tool inside a Sub-Process correctly moves the following elements but forces the outgoing Sequence Flow to leave at the top of the Sub-Process and around it.

__Steps to Reproduce__

1. Create a Sub-Process and an End Event after it.
2. Use the Space Tool to expand the Sub-Process to the right.

__Expected Behavior__

The outgoing Sequence Flow leaves the Sub-Process at the same position.

__Environment__

 - OS: Kubuntu 18.04.2 LTS
 - Camunda Modeler Version: 3.1.1-nightly from 2019-05-08

**Comment by pinussilvestrus** [comment]
Relates to https://github.com/bpmn-io/bpmn-js/issues/1019

**Comment by nikku** [comment]
Will be fixed with `v3.7` release of the app.

**Comment by falko** [comment]
Awesome! Thx.
