### ISSUE TITLE
Do not resize text annotation box when it's affected by create/remove space tool

### ISSUE THREAD

**Issue by slizenko** [camunda/camunda-modeler#1371]
__Describe the Bug__

When a TextAnnotation would be affected by the Space Tool, it will be resized.

![May-09-2019 10-10-59](https://user-images.githubusercontent.com/9433996/57437776-c466f300-7242-11e9-9f20-f0066449572d.gif)

This also leads that the Space Tool does not affect any change when a TextAnnotation would be resized to an impossible size (below 0)

![May-09-2019 10-13-10](https://user-images.githubusercontent.com/9433996/57437911-10b23300-7243-11e9-89e1-2fc80ccc1a03.gif)

__Steps to Reproduce__

1. Create a simple process with a TextAnnotation
2. Enable the create/remove space tool
3. Make changes which would affect the TextAnnotations (like screencast above)

__Expected Behavior__

The space tool should not resize TextAnnotations.

__Environment__

Please complete the following information:

 - OS: all
 - Camunda Modeler Version: 3.1.0, but also appears on older versions.

This will need a fix inside `bpmn-js`.

**Comment by pinussilvestrus** [comment]
I was able to reproduce this on macOS:

![May-09-2019 10-10-59](https://user-images.githubusercontent.com/9433996/57437776-c466f300-7242-11e9-9f20-f0066449572d.gif)

Furthermore, it is not possible to use the space tool when a TextAnnotation would be resized under a size of 0:

![May-09-2019 10-13-10](https://user-images.githubusercontent.com/9433996/57437911-10b23300-7243-11e9-89e1-2fc80ccc1a03.gif)

**Comment by pinussilvestrus** [comment]
I updated the description to fit our bug report schema 👍 

Thanks for sharing @slizenko 🙂

**Comment by philippfromme** [comment]
Is this actually a bug?

**Comment by nikku** [comment]
It is a feature.

In most cases it is not appropriate to resize text annotations, as they fit the contained text.
