### ISSUE TITLE
Segmentation fault on Arch Linux with modeler 3.1.0 

### ISSUE THREAD

**Issue by Krever** [camunda/camunda-modeler#1372]
On Arch Linux camunda-modeler 3.1.0 refuses to start with segfault. Stdout is as follows:

```
$ camunda-modeler-3.1.0-linux-x64/camunda-modeler 
app:main:bootstrap starting Camunda Modeler v3.1.0
app:cli parsing [ '/home/plpitulw/Downloads/camunda-modeler-3.1.0-linux-x64/camunda-modeler' ] in '/home/plpitulw/Downloads'
app:config loading from /home/plpitulw/.config/camunda-modeler/config.json
app:flags searching for flags.json in paths [ '/home/plpitulw/.config/camunda-modeler/resources',
  '/home/plpitulw/Downloads/camunda-modeler-3.1.0-linux-x64/resources' ]
app:flags found []
app:flags active {}
app:plugins searching for plugins/*/index.js in paths [ '/home/plpitulw/.config/camunda-modeler/resources',
  '/home/plpitulw/Downloads/camunda-modeler-3.1.0-linux-x64/resources',
  '/home/plpitulw/.config/camunda-modeler',
  '/home/plpitulw/Downloads/camunda-modeler-3.1.0-linux-x64' ]
app:plugins found plug-in entries []
app:plugins registered []
app:main:bootstrap received ready
[1]    31193 segmentation fault (core dumped)  camunda-modeler-3.1.0-linux-x64/camunda-modeler
```
and coredumpctl:
```
$ coredumpctl info -1
           PID: 31193 (camunda-modeler)
           UID: 1000 (plpitulw)
           GID: 1000 (plpitulw)
        Signal: 11 (SEGV)
     Timestamp: Thu 2019-05-09 19:29:37 CEST (1min 24s ago)
  Command Line: /home/plpitulw/Downloads/camunda-modeler-3.1.0-linux-x64/camunda-modeler
    Executable: /home/plpitulw/Downloads/camunda-modeler-3.1.0-linux-x64/camunda-modeler
 Control Group: /user.slice/user-1000.slice/session-8.scope
          Unit: session-8.scope
         Slice: user-1000.slice
       Session: 8
     Owner UID: 1000 (plpitulw)
       Boot ID: 2da1233fdf1e446f9bfdb7187395c9d2
    Machine ID: 6dfdd71f3cb54036bc2d1ef3f80569e4
      Hostname: plpitulw-pc
       Storage: /var/lib/systemd/coredump/core.camunda-modeler.1000.2da1233fdf1e446f9bfdb7187395c9d2.31193.1557422977000000.lz4
       Message: Process 31193 (camunda-modeler) of user 1000 dumped core.
                
                Stack trace of thread 31206:
                #0  0x0000000004b56dbb n/a (/home/plpitulw/Downloads/camunda-modeler-3.1.0-linux-x64/camunda-modeler)
```

Let me know what more info I can provide.
It seems that this is a recurring issue caused by electron, but right now there is no way of runinng camunda-modeler on my machine. I tried versions 2.0.3, 2.2.4, 3.0.0, 3.1.0 and nightly, all with the same result. If its glibc problem I would be greatful for the information on what version is confirmed to be working fine.

**Comment by nikku** [comment]
I cannot reproduce your issue using an up-to-date version of Arch Linux.

Are you running against the latest Arch Linux version? Do you have a pinned / outdated version of glibc on your system? We have had [segfault issues](https://github.com/camunda/camunda-modeler/issues/869) with Arch Linux some time ago, maybe you could look up that thread and see if it is related.

**Comment by Krever** [comment]
My glibc in in version 2.29. Could you share what is yours?
I updated the packages just before raising this issue but I will try it again, maybe something changed till then.

**Comment by nikku** [comment]
```
$ pacman -Q | grep glibc          
glibc 2.29-1
```

**Comment by nikku** [comment]
The Camunda Modeler runs on [Electron](https://github.com/electron/electron), `v3.1.x`. 

You could try to investigate whether this is a general known issue on your distribution.

**Comment by Krever** [comment]
Thanks, I will try to investigate the root cause.

**Comment by Krever** [comment]
Problem disappeard. I would still love to know what was the root cause but it works know. Thanks for you attention!
