### ISSUE TITLE
Default Element Templates Always Applied

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1373]
![foobar](https://user-images.githubusercontent.com/7633572/57528489-bf816c80-7332-11e9-91fc-99fd1dc0198e.gif)

__Describe the Bug__

When opening a diagram that contains a `camunda:property` set using an element template the property value is not shown in the properties panel.

__Steps to Reproduce__

1. Use the following element template:

```javascript
[
  {
     "name":"Test",
     "id":"test",
     "isDefault":true,
     "appliesTo":[
        "bpmn:Process"
     ],
     "properties":[
        {
           "label":"Test",
           "description":"This is a test.",
           "type":"String",
           "binding":{
              "type":"camunda:property",
              "name":"Test Property"
           },
           "constraints":{
              "notEmpty":true
           }
        }
     ]
  }
]
```

2. Open this diagram:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="3.1.0">
  <bpmn:process id="Process_1" isExecutable="false" camunda:modelerTemplate="test">
    <bpmn:extensionElements>
      <camunda:properties>
        <camunda:property name="Test Property" value="foobar" />
      </camunda:properties>
    </bpmn:extensionElements>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1" />
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

__Expected Behavior__

Property is shown.

__Environment__

 - OS: Windows 10
 - Camunda Modeler Version: 3.1.0

**Comment by nikku** [comment]
Is it a regression? Does this work in Camunda Modeler v2.2.x?

**Comment by philippfromme** [comment]
Yes, it's a regression.

**Comment by philippfromme** [comment]
The issue is that default element templates are always applied. [They used to only be applied to the initial diagram](https://github.com/camunda/camunda-modeler/blob/v2.2.4/client/lib/app/editor/bpmn-editor.js#L91).

**Comment by philippfromme** [comment]
Lol. This: https://github.com/camunda/camunda-modeler/blob/master/client/src/app/tabs/bpmn/BpmnEditor.js#L457

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/1373.
