### ISSUE TITLE
I color sequence flows and lose the arrowheads

### ISSUE THREAD

**Issue by sebwarnke** [camunda/camunda-modeler#1377]
__Describe the Bug__

![LoZWp0B18Z](https://user-images.githubusercontent.com/26740468/58023738-dc772600-7b10-11e9-8c32-53cb686b7cd0.gif)

__Expected Behavior__

I expect the arrowhead to stay and take the color.

__Environment__

Please complete the following information:
Camunda Modeler 3.1.0

**Comment by tasso94** [comment]
Hi,

this is a known issue, see #1342.

Cheers,
Tassilo

**Comment by nikku** [comment]
Will be fixed with next Camunda Modeler release.

**Comment by slizenko** [comment]
Problem is still here.
Reproduced in Camunda 3.1.2
