### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1384]
__Is your feature request related to a problem? Please describe.__

Contributing guidlines are missing which makes it more difficult for external contributors to propose their changes.

__Describe the solution you'd like__

Add CONTRIBUTING.md like [the one we have in bpmn-js](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md).

__Describe alternatives you've considered__

Do nothing.

**Comment by nikku** [comment]
If it is a quick fix, could you simply add the file? 

If not I'm worried such documentation issue will never be closed (and thus lie around open, forever :angel:).

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1395.
