### ISSUE TITLE
Report generated from BPMN file

### ISSUE THREAD

**Issue by slizenko** [camunda/camunda-modeler#1391]
Such feature would be a big help for us, for preparation of technical documentation.

For documentation purpose I would like to have ability to generate the report from the Modeller.
The content of this report is very basic -
* Pool - ID, Name, Documentation
** Swim Lane - ID, Name, Documentation
*** Artifact (Task, Event, DataObject) - ID, Name, Documentation

The report should be in editable format.

**Comment by nikku** [comment]
There exist various means of parsing the BPMN diagrams outside the modeler:

* [bpmn-moddle](https://github.com/bpmn-io/bpmn-moddle) if you use JavaScript
* [camunda-bpmn-model](https://github.com/camunda/camunda-bpmn-model) if you use Java

I suggest you to build your own tools for parsing the XML (and generating documentation) outside the modeler. 

Closing this as I see this as out of scope for the tool.
