### ISSUE TITLE
Be able to store and retrieve information local to a diagram

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1397]
__Is your feature request related to a problem? Please describe.__

Plug-ins add features need the ability to store information local to the diagram that cannot be stored within the diagram.

Potential places to store:
 
* right next to the diagram (TBD)
* in project scope (TBD)
* in workspace

__Describe the solution you'd like__

* A simple API allows components and plug-ins to retrieve and set information stored on the diagram, project or workspace level.

__Additional Context__

* This is required for the Camunda Modeler <> Cawemo sync.
* This is required by https://github.com/camunda/camunda-modeler/issues/1066
* This is required by https://github.com/camunda/camunda-modeler/issues/1067

**Comment by volkergersabeck** [comment]
Closed via #1494
