### ISSUE TITLE
"Zoom to Fit Diagram" should resize the diagram to area not covered by toolbox on the left

### ISSUE THREAD

**Issue by slizenko** [camunda/camunda-modeler#1401]
Each time I "zoom to fit diagram", I have to shift it right since swimlane names are under toolbox -
![image](https://user-images.githubusercontent.com/50139137/59369384-fe974900-8d48-11e9-813e-0f2e8c682025.png)

Would be good to fit the diagram to this area -
![image](https://user-images.githubusercontent.com/50139137/59369603-71a0bf80-8d49-11e9-92eb-dc39a430dcb4.png)

**Comment by nikku** [comment]
Thanks for your feedback. Definitely makes sense.

**Comment by nikku** [comment]
Closing this as a duplicate of https://github.com/camunda/camunda-modeler/issues/650.
