### ISSUE TITLE
QUESTION: How to activate Modeler to be multi-instance?

### ISSUE THREAD

**Issue by slizenko** [camunda/camunda-modeler#1402]
I created flags.json file in resource folder.
How I can open another diagram in another Modeler?
Or give me ref to the doc on the camunda site where I can read about it.

**Comment by nikku** [comment]
You must disable the single-instance feature [as documented here](https://github.com/camunda/camunda-modeler/tree/master/docs/flags).

**Comment by nikku** [comment]
Note that multi-instance is not an officially supported feature.

**Comment by slizenko** [comment]
Multi-instance works, thanks!
Several processes on several monitors that's what I wanted!
Hope this unofficial feature will not go down the road.
