### ISSUE TITLE
Camunda Modeler reported as Virus by some scanners

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1403]
This is a tracking issue for reports that flag the Camunda Modeler (v3.0.0+) as a virus.

__v3.1.2__

* Reported as issue by: Symantec, [WS.Reputation.1](https://www.symantec.com/security-center/writeup/2010-051308-1854-99?vid=4294919973)
* VirusTotal scan results: [NOT A VIRUS](https://www.virustotal.com/gui/file/80497e2d8f9a535d4c669e60919266b8b7be2cb57e4076eb133ded15952d5286/detection)

**Comment by slizenko** [comment]
FYI - when installing nighty versions, Avast is saying it's ok

**Comment by nikku** [comment]
It reports the app as a virus on the released version? If so, could you post additional details?

**Comment by slizenko** [comment]
Avast never reported on the released versions as virus.
Windows 10 x64

**Comment by pinussilvestrus** [comment]
Current Camunda-Modeler nightly version `v3.2.0-nightly` (3rd July 2019) was detected as virus from Avast on my Windows 10 x64 machine.

**Comment by tobiasoort** [comment]
We're having this issue right now too with Symantec Endpoint Protection.

**Comment by nikku** [comment]
Which version are you on?

**Comment by nikku** [comment]
Did you double check against [virustotal](https://www.virustotal.com/)?

**Comment by tobiasoort** [comment]
I can't reproduce on my system (same version of Symantec EP) so i've asked the collegue that reported it to me to provide full details.

No hits on virustotal for my download, i'll ask him to do the same. To be continued.
