### ISSUE TITLE
First time trying to close "Deploy Diagram" dialog leads to error "Deployment name must not be void."

### ISSUE THREAD

**Issue by Endogen** [camunda/camunda-modeler#1405]
__Describe the Bug__
Opening the "Deploy Diagram" dialog and immediately closing it with the Close-button leads to the error "Deployment name must not be void.". After clicking the button again, the dialog closes.

__Steps to Reproduce__

1. Open dialog "Deploy Diagram"
2. Click button "Cancel"

__Expected Behavior__
After clicking the Close-button, the dialog should close without the error message

__Environment__
 - OS: Windows 7
 - Camunda Modeler Version: 3.1.2

--- 

Child of https://github.com/camunda/camunda-modeler/issues/1439

**Comment by pinussilvestrus** [comment]
Confirmed on macOS with modeler version `3.1.2` and current `master`.

![Jun-19-2019 09-39-35](https://user-images.githubusercontent.com/9433996/59746148-8bc12d00-9276-11e9-8b63-262f33cdf393.gif)

Let's tackle this when we improve the deploy functionality in the next quarter! Or what do you think @nikku @volkergersabeck ?

**Comment by nikku** [comment]
Makes sense, as this is a very nice easy pick.
