### ISSUE TITLE
Update package process to use grunt

### ISSUE THREAD

**Issue by vladimirskatusenoks** [camunda/camunda-modeler#141]
- [x] Make a package for each of the existing supported platform
- [x] Restructure back-end folders test/src
- [x] Make sure app tests are running
- [x] Linting *.js files
- [x] `grunt auto-build` spins up development setup; changes in client / app restart the app (see old `gulp auto-build` task)

**Comment by vladimirskatusenoks** [comment]
Please review and merge into [`next` branch](https://github.com/camunda/camunda-modeler/tree/next).

**Comment by nikku** [comment]
Need to restore the development setup (check old `gulp auto-build`). Seems like that got lost with the refactoring.
