### ISSUE TITLE
Participant to participant message flow prevents copy and paste

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1413]
__Describe the Bug__

Given I have a participant to participant message flow, that thing prevents copy and paste from working: 

![out pqUMc](https://user-images.githubusercontent.com/58601/60185567-73c74b80-982a-11e9-91e6-9b75f9cf73fe.gif)

__Steps to Reproduce__

* Open [test diagram](https://github.com/camunda/camunda-modeler/files/3330329/test.bpmn.txt)
* SELECT ALL
* Copy + paste
* Editor shows error message "Flow elements must be children of..."

__Expected Behavior__

I can paste such construct.

__Environment__

Please complete the following information:

 - OS: Any
 - Camunda Modeler Version: v3.1.0

**Comment by nikku** [comment]
Possibly related to it, you cannot copy and paste a participant + linked text annotation, too:

* [test diagram](https://github.com/camunda/camunda-modeler/files/3330341/test.bpmn.txt)
* Demonstration

    ![out BD7DY](https://user-images.githubusercontent.com/58601/60185956-27c8d680-982b-11e9-9bd3-5dbce02f1c47.gif)

**Comment by philippfromme** [comment]
Will be fixed through https://github.com/bpmn-io/bpmn-js/pull/1137. 💪

**Comment by nikku** [comment]
Fixed via https://github.com/bpmn-io/bpmn-js/pull/1137.

**Comment by nikku** [comment]
:mushroom:
