### ISSUE TITLE
QUESTION: How to control size of generated PNG file?

### ISSUE THREAD

**Issue by slizenko** [camunda/camunda-modeler#1414]
We use PNGs for previewing WFs in our application.

in version 2.2.4 PNG file was 190 KB -
![image](https://user-images.githubusercontent.com/50139137/60195042-1a1f4b00-9843-11e9-8ef8-9751d1ed1244.png)

in version 3.1.2 it is 1.2 MB -
![image](https://user-images.githubusercontent.com/50139137/60195067-25727680-9843-11e9-88af-f013bf8183a8.png)

Any setting to control PNG generation?

**Comment by nikku** [comment]
Upon user request we changed the PNG generation to export high resolution images (https://github.com/camunda/camunda-modeler/issues/486). 

We do not allow you to control the generation and do not intend to offer these tools.

To bring back the smaller PNGs you could add automatic downscaling to your workflow.

**Comment by slizenko** [comment]
Wandering is it a bit problem to generate big/small raster file?
Especially as you have flags.json file just to add one more option to control the generation mode.
