### ISSUE TITLE
Cannot reassign task with h2 database

### ISSUE THREAD

**Issue by neplatnyudaj** [camunda/camunda-modeler#1415]
__Describe the Bug__

When using H2 database, it is impossible to reassign tasks. 
`ENGINE-03004 Exception while executing Database Operation 'INSERT AuthorizationEntity[769d38b0-980e-11e9-a093-144f8adf0ac5]' with message ' ### Error updating database. Cause: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "ACT_UNIQ_AUTH_GROUP_INDEX_6 ON PUBLIC.ACT_RU_AUTHORIZATION(TYPE_, GROUP_ID_, RESOURCE_TYPE_, RESOURCE_ID_) VALUES (1, NULL, 7, 'a8daf824-980d-11e9-a093-144f8adf0ac5', 51)"; SQL statement: insert into ACT_RU_AUTHORIZATION ( ID_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_, REV_ ) values ( ?, ?, ?, ?, ?, ?, ?, 1 ) [23505-197] ### The error may involve org.camunda.bpm.engine.impl.persistence.entity.AuthorizationEntity.insertAuthorization-Inline ### The error occurred while setting parameters ### 
SQL: insert into ACT_RU_AUTHORIZATION ( ID_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_, REV_ ) values ( ?, ?, ?, ?, ?, ?, ?, 1 ) ### Cause: org.h2.jdbc.JdbcSQLException: 
Unique index or primary key violation: "ACT_UNIQ_AUTH_GROUP_INDEX_6 ON PUBLIC.ACT_RU_AUTHORIZATION(TYPE_, GROUP_ID_, RESOURCE_TYPE_, RESOURCE_ID_) VALUES (1, NULL, 7, 'a8daf824-980d-11e9-a093-144f8adf0ac5', 51)"; 
SQL statement: insert into ACT_RU_AUTHORIZATION ( ID_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_, REV_ ) values ( ?, ?, ?, ?, ?, ?, ?, 1 ) [23505-197]'. 
Flush summary: [ INSERT AuthorizationEntity[769d38b0-980e-11e9-a093-144f8adf0ac5] INSERT HistoricIdentityLinkLogEventEntity[769d38b1-980e-11e9-a093-144f8adf0ac5] UPDATE TaskEntity[a8daf824-980d-11e9-a093-144f8adf0ac5] UPDATE HistoricActivityInstanceEventEntity[Task_07vabcb:a8daf823-980d-11e9-a093-144f8adf0ac5] UPDATE HistoricTaskInstanceEventEntity[a8daf824-980d-11e9-a093-144f8adf0ac5] ]
`

The problem is in the init script https://github.com/camunda/camunda-bpm-platform/blob/master/engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql
It is caused by these constraints: 
`alter table ACT_RU_AUTHORIZATION
    add constraint ACT_UNIQ_AUTH_USER
    unique (TYPE_, USER_ID_,RESOURCE_TYPE_,RESOURCE_ID_);

alter table ACT_RU_AUTHORIZATION
    add constraint ACT_UNIQ_AUTH_GROUP
    unique (TYPE_, GROUP_ID_,RESOURCE_TYPE_,RESOURCE_ID_);
`

**This seems to be the problem only for H2 database, with Oracle database it is working as expected**, because there are null checks: https://github.com/camunda/camunda-bpm-platform/blob/master/engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql

`-- see http://stackoverflow.com/questions/675398/how-can-i-constrain-multiple-columns-to-prevent-duplicates-but-ignore-null-value
create unique index ACT_UNIQ_AUTH_USER on ACT_RU_AUTHORIZATION
   (case when USER_ID_ is null then null else TYPE_ end,
    case when USER_ID_ is null then null else RESOURCE_TYPE_ end,
    case when USER_ID_ is null then null else RESOURCE_ID_ end,
    case when USER_ID_ is null then null else USER_ID_ end);

create unique index ACT_UNIQ_AUTH_GROUP on ACT_RU_AUTHORIZATION
   (case when GROUP_ID_ is null then null else TYPE_ end,
    case when GROUP_ID_ is null then null else RESOURCE_TYPE_ end,
    case when GROUP_ID_ is null then null else RESOURCE_ID_ end,
    case when GROUP_ID_ is null then null else GROUP_ID_ end);`

__Steps to Reproduce__

1. Start a process with some user task
2. Login with User1 and find the user task
3. Claim and unclaim the task
4. Login with User2 and find the user task
5. Claim the task -> error from the description appears

__Expected Behavior__

No error. The task is claimed by User2

__Environment__

 - Camunda Version: 7.10, 7.11

**Comment by nikku** [comment]
This is the Camunda Modeler issue tracker. 

Please raise this engine bug in our [Camunda Community Forum](https://forum.camunda.org).
