### ISSUE TITLE
Copy&Paste restricted by improved container navigation 

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1416]
__Describe the Bug__

Given the [new container interaction](https://github.com/camunda/camunda-modeler/issues/238) you cannot paste into containers anymore.

__Reproduce__

- create a pool or sub process that contains at least one element
- select the element and copy it
- hover over the pool
- trigger paste
- __paste is restricted or, if possible paste happens outside the container element__
    ![ezgif-2-d5fa4140f9a4](https://user-images.githubusercontent.com/2777965/60333465-641a4500-9999-11e9-98e5-140a57a29ad7.gif)
    ![ezgif-2-04989fedc2a3](https://user-images.githubusercontent.com/2777965/60333554-a17ed280-9999-11e9-8510-efdf1c59e967.gif)

__Expected Behavior__

* [ ] Pasting elements works without hazzles like in Camunda Modeler v3.1

__Environment__

Please complete the following information:

 - OS: Any
 - Camunda Modeler Version: 3.2-nightly

**Comment by nikku** [comment]
This is a UX issue that got introduced via https://github.com/camunda/camunda-modeler/issues/238.

**Comment by barmac** [comment]
Idea: allow paste if participant is selected.

**Comment by nikku** [comment]
That is the idea worth exploring :+1:

**Comment by barmac** [comment]
Paste-on-selection approach does not fix another problem related to this issue, cf.:

![paste](https://user-images.githubusercontent.com/28307541/60425885-c5d5eb80-9bf3-11e9-9d32-30a5e469b775.gif)

**Comment by barmac** [comment]
Second idea: Use rules to introduce the improved navigation. This way we could potentially resolve the current issue and save the feature.

**Comment by barmac** [comment]
We decided to revert the _improved navigation_ and return back to it in the future.

**Comment by barmac** [comment]
Fixed via https://github.com/camunda/camunda-modeler/commit/7c48975ea920f07ef621606296a58875f5dfd682

**Comment by nikku** [comment]
We investigate two-step pasting as a solution for this issue: https://github.com/camunda/camunda-modeler/issues/1421
