### ISSUE TITLE
Group label disappears after Copy&Paste

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1417]
__Describe the Bug__

Group label disappears after Copy&Paste

__Steps to Reproduce__
// given
a group with a label (name)

// when
I copy and paste the group element

// then
1. the label is not displayed
2. the complete element disappears when I edit the name attribute in the properties panel

![ezgif-2-84418efd6b9c](https://user-images.githubusercontent.com/2777965/60334617-3c78ac00-999c-11e9-9575-77ab2eb87193.gif)

__Expected Behavior__

label is visible afte copy and paste an the element does not disappear

__Environment__

Please complete the following information:

 - OS: linux
 - Camunda Modeler Version: [3.2.0 nightly 190628]

**Comment by barmac** [comment]
Idea: create a separate category value for the pasted group.

**Comment by pinussilvestrus** [comment]
This relates to https://github.com/bpmn-io/bpmn-js/issues/1055

**Comment by barmac** [comment]
Fixed via https://github.com/camunda/camunda-modeler/commit/7c48975ea920f07ef621606296a58875f5dfd682
