### ISSUE TITLE
Spike: Run from App

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1424]
As a user I can run a modeled diagram directly on the Camunda Engine.

![image](https://user-images.githubusercontent.com/58601/60810887-57160680-a18e-11e9-8946-14d5e0ba4d78.png)

__Rational and UI Sketches__

Cf. [slide deck](https://docs.google.com/presentation/d/1Zw7Kq9RNyG8VUAX6NO5Qi65Ziak-jIX_3ciCfk8l2q0/edit?usp=sharing)

**Comment by volkergersabeck** [comment]
Assumptions:
* we can assume that having max one process instance running in parallel is ok for this scenario
* while a process instance is running, the process model needs not be changed

Suggestion:
* we can have one view in two modes (modeling vs running) that work as described above.
* clicking the RUN button switches to the "running" mode
* closing the "running" mode makes sure the process instance is stopped
* restarting is simply to hit the RUN button again from the "modeling" mode
* the same way as we store the deployment config, we can store the process input variables for subsequent runs, making it easy to restart a process in the very same configuration

**Comment by ingorichtsmeier** [comment]
What about deploying the first version of my model in a process application?

Usually, if I redeploy and start a process instance I will get ClassNotFoundExceptions.

It's a different problem, but you should be aware that many users fall into this trap.

**Comment by nikku** [comment]
Thanks for mentioning this. 

We are aware of the many ways how simply deploying a diagram via the modeler can break automation.

The aim of this feature is not to replace production deployments but to learn and discover how Camunda works:

![image](https://user-images.githubusercontent.com/58601/60950847-3bc70a80-a2f8-11e9-84f7-80382c8379b0.png)

 It will be of less use for advanced setups (at least as far as this spike is concerned).

**Comment by nikku** [comment]
We've investigated this and came up with the [camunda-playgrund](https://github.com/nikku/camunda-playground).
