### ISSUE TITLE
Improve display of deployment parse errors

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1426]
__Is your feature request related to a problem? Please describe.__

We currently display deployment errors in the log. When dealing with validation errors (i.e. missing condition) the user should be able to get the relevant information from them in order to fix them. 

![screely-1568186722616](https://user-images.githubusercontent.com/7633572/64676542-19777780-d476-11e9-9807-eb9c96f38261.png)

__Possible solutions__

* Display human-readable error message as notification
* For more details click notification to open log

---

Linked to [Prodpad idea](https://app.prodpad.com/ideas/159/canvas)

Child of https://github.com/camunda/camunda-modeler/issues/1439

**Comment by barmac** [comment]
For now, we can simply display the error message instead of stringified error.
