### ISSUE TITLE
Add start and end event listener icons to diagram

### ISSUE THREAD

**Issue by voidkor** [camunda/camunda-modeler#1428]
__Is your feature request related to a problem? Please describe.__

Listeners provide implicit functionals which may affect to execution of process but they does not displayed on diagram. It makes debugging and undestanding of diagram a little harder.

__Describe the solution you'd like__

I think it would be useful if we can see which activities have configured start/end listeners as icon on activity in modeler UI.

__Describe alternatives you've considered__

None

**Comment by ingorichtsmeier** [comment]
Hi @voidkor ,

there is a plugin available for this feature: https://github.com/umb/camunda-modeler-property-info-plugin.

Hope this helps, Ingo

**Comment by voidkor** [comment]
Hi @ingorichtsmeier ,
it works fine! Thank you!
