### ISSUE TITLE
Write Camunda Modeler v3.2.0 release blog post

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1430]
Required by https://github.com/camunda/camunda-modeler/issues/1422

**Comment by nikku** [comment]
Closed via https://github.com/camunda/blog.camunda.org/pull/85.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/blog.camunda.org/pull/85

**Comment by barmac** [comment]
![image](https://user-images.githubusercontent.com/28307541/61638686-370c3a00-ac9a-11e9-8e72-fd01632fd1af.png)
