### ISSUE TITLE
Deployment to HTTPS endpoint fails with SELF_SIGNED_CERT_IN_CHAIN, even though certificate is trusted by OS

### ISSUE THREAD

**Issue by TheNikosCode** [camunda/camunda-modeler#1432]
__Describe the Bug__

The app does not pick up custom root certificates that have been added to the OS trust store. When trying to deploy to a server with a `self signed cert -> self imported self signed CA cert`, the deployment fails and an error is logged:

```
{"code":"SELF_SIGNED_CERT_IN_CHAIN","deploymentName":"test","errno":"SELF_SIGNED_CERT_IN_CHAIN","message":"request to https://localhost:8443/engine-rest/deployment/create failed, reason: self signed certificate in certificate chain","type":"system"} [ deploy-error ]
```

__Steps to Reproduce__

Prerequisite:

* Setup your environment, generate a CA certificate, generate a server certificate, import the CA certificate in your OS trust store, start a test server with the server certificate. Cf. [this project](https://github.com/nikku/camunda-modeler-self-signed-root-ca-test) that does the stuff on Arch Linux)

Reproduce bug:

1. In the App, create a diagram.
2. Press "Deploy Current Diagram".
3. Fill in the "Name" - Test.
4. Fill in the "URL" - https://localhost:8443/engine-rest/deployment/create.
5. Press "Deploy".

Additional information:
1. Apache Tomcat uses a certificate issued by a certification authority.
2. Deploy via HTTP works good.
3. Camunda APPs (e.g. admin, coсkpit, tasklist) works good via HTTPS (Сertificate is valid).

__Expected Behavior__

Diagram deployed via HTTPS.

__Environment__

 - OS: [CentOS 7.6, Windows 10]
 - Camunda Modeler Version: [3.1.2]
 - Apache Tomcat Version: [9.0.19]
 - Camunda Community Platform: [7.11.0]

**Comment by nikku** [comment]
It appears as if you're using a self-signed certificate somewhere in the chain. That certificate is configured allowed by the browser but rejected by our deployment utility.

Could you provide details on your certificate (__not the private key :warning:__)?
How do you configure / add the certificate to your browser?

**Comment by TheNikosCode** [comment]
> It appears as if you're using a self-signed certificate somewhere in the chain. That certificate is configured allowed by the browser but rejected by our deployment utility.
> 
> Could you provide details on your certificate (**not the private key ⚠️**)?
> How do you configure / add the certificate to your browser?

I'm use a certificates issued by a corporate certification authority.
Certificate hierarchy below:
ROOT CA (corporate) issued by ROOT CA   <= self-signed for Modeler, i think.
---CORP CA (corporate) issued by ROOT CA
------Web-server (corporate) issued by CORP CA

The ROOT and CORP certificates listed above are installed in my browser (Google chrome, Settings -> Advanced -> Manage certificates) and OS.
Is it possible to import the ROOT and CORP certificates into Camunda Modeler so that it can trust them?
We are well aware of what the problem is, but do not know how to solve it, because it is not clear how to make Camunda Modeler trust our corporate certificates.
Thanks in advance.

**Comment by nikku** [comment]
What does the following mean?

> [Installed] in OS

For obvious reasons stuff that you configured as trusted in your Browser does not automatically mean it is trusted by the OS.

**Comment by nikku** [comment]
If you provide me with a way to generate the certificate chain and private keys as a unix command I could attempt to reproduce the issue on my machine (Arch Linux).

**Comment by nikku** [comment]
We won't be able to follow up on this issue without additional input from your side.

**Comment by TheNikosCode** [comment]
Sorry for the delay on my part. 
You can use openssl for generate certificate chain on Unix.
Please, see details how [here](https://superuser.com/questions/126121/how-to-create-my-own-certificate-chain).
You need to create this chain: ROOT -> A -> B.
Next, you need Importing Certificates (details [here](https://tomcat.apache.org/tomcat-9.0-doc/ssl-howto.html#Importing_the_Certificate)).
Next step, you need Edit the Tomcat Configuration File (details [here](https://tomcat.apache.org/tomcat-9.0-doc/ssl-howto.html#Edit_the_Tomcat_Configuration_File)). I use the APR connector:
>            protocol="org.apache.coyote.http11.Http11AprProtocol"
>            port="8443" maxThreads="200"
>            scheme="https" secure="true" SSLEnabled="true"
>            SSLCertificateFile="/usr/local/ssl/server.crt"   <-- use cert B
>            SSLCertificateKeyFile="/usr/local/ssl/server.pem"
>            SSLVerifyClient="optional" SSLProtocol="TLSv1+TLSv1.1+TLSv1.2".

**Comment by nikku** [comment]
How did you tell your OS to trust the self-signed certificate?

**Comment by TheNikosCode** [comment]
For CentOS [this ](https://ahmermansoor.blogspot.com/2019/01/configure-certificate-authority-ca-centos-7.html) guide (section: Add CA Certificate to CentOS 7 clients’ Trusted Store).
For your system you can check [this](https://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list) or [this](https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html).

**Comment by nikku** [comment]
After spending some time on the issue I can verify that this is a BUG.

It appears that the app does not pick up the certificates in the OS trust store.

This is an issue we got to work around somehow, as it seems to be broken upstream in Electron, cf. https://github.com/electron/electron/issues/11741 and https://github.com/electron/electron/issues/10257.

**Comment by TheNikosCode** [comment]
**nikku**, thank you very much!

**Comment by nikku** [comment]
We'll not fix this any time soon.

**Comment by jamesgiu** [comment]
FYI, adding your CA certs as trusted CAs to Chrome fixes this. Tested on Modeler 4.2.0 running on Fedora 29. It _has_ to be your installation of Chrome. Not sure what your "OS truststore" might be a reference to specifically, but that's what's solved this in a use case I encountered.

Don't know much about Electron but I suppose being Chromium based, it must check your Chrome's truststore.

**Comment by nikku** [comment]
Thanks for providing that workaround. I guess the trust store is being shared between different instances of Chrome / Chromium then? 

For anyone else encountering this, would be interesting if the same workaround works on Windows/MacOS, too.

**Comment by StephenOTT** [comment]
So does that mean that self-signed ssl/https certs that are not supported by the modeler for deployment?

**Comment by StephenOTT** [comment]
It seems that self-signed cert is not supported:

<img width="1578" alt="Screen Shot 2021-04-26 at 8 06 52 AM" src="https://user-images.githubusercontent.com/1994838/116079883-5f427d00-a666-11eb-9361-4dc7e05a74dc.png">

**Comment by nikku** [comment]
> So does that mean that self-signed ssl/https certs that are not supported by the modeler for deployment?

Yes. At the moment these are not supported. A workaround [exists though](https://github.com/camunda/camunda-modeler/issues/1432#issuecomment-724441183).

**Comment by asoltesz** [comment]
@nikku 
As of Camunda Modeller 4.9, the workaround doesn't seem to work.

My case is a bit different though, because it is the "net::ERR_CERT_COMMON_NAME_INVALID" type.

**Comment by djhuertasg** [comment]
I have a related issue. I'm getting in Camunda Modeler 4.9 the following error: "Should point to a running Camunda Platform REST API." As far as I know the problem is caused by the self signed certificated that is not accepted as valid by Chrome.
