### ISSUE TITLE
Context menu causes jump (to the top) in Modeler view when opened

### ISSUE THREAD

**Issue by srazavi** [camunda/camunda-modeler#1433]
__Describe the Bug__

When the context menu is opened on a large enough DMN table, the Modeler view jumps to the top of the table.

![support-6122-modeler](https://user-images.githubusercontent.com/8934001/61718053-7bfba380-ad62-11e9-96e1-578b4095dff2.gif)

__Steps to Reproduce__

1. import [`table.dmn`](https://github.com/camunda/camunda-modeler/files/3422391/test-for-supp-6122.dmn.txt) or any diagram with a sufficient amount of rows
2. open the context menu on the lowest rule (in my case, rule 24)

__Expected Behavior__

The context menu opens next to the item that was selected when the menu was opened (at least one corner of the menu being located within the cell where the menu was opened).

__Environment__

 - OS:  MacOS 10.14.5 (MacBook Pro 13") --> for screen size as a reference
 - Camunda Modeler Version: 3.2.1

---

Related to [SUPPORT-6122](https://app.camunda.com/jira/browse/SUPPORT-6122)

**Comment by srazavi** [comment]
This popped up in support. I linked relevant support case in issue description.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1593.
