### ISSUE TITLE
Find shortcut disabled for no reason

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1450]
__Describe the Bug__

The "Find" shortcut stops to work after the first use in a tab. Then it comes back when the tab is switched.

__Steps to Reproduce__

1. Open a new tab.
2. Use Find shortcut (`Cmd+F`).
3. Notice that the menu item is disabled and the shortcut does not work anymore.

__Expected Behavior__

Find shortcut still works.

__Environment__

 - OS: MacOS, Linux
 - Camunda Modeler Version: 3.2.1

**Comment by nikku** [comment]
Same on Linux. Menu item is disabled, you can still open the search box sporadically though.

**Comment by nikku** [comment]
Were you able to get to the root of this issue?

**Comment by barmac** [comment]
Nope, but I didn't debug it thoroughly.

**Comment by barmac** [comment]
`BpmnEditor#handleChanged` is not triggered when we exit the Find input without selecting an element. This seems to be an easy fix.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1461.
