### ISSUE TITLE
Release v3.2.2

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1455]
* [x] smoke test to verify all diagrams can be created
* [x] update CHANGELOG
* [x] semantic release (`npm run release`), cf. [release schema](https://github.com/bpmn-io/internal-docs/tree/master/release-schema) 
* [x] wait for [Travis](https://travis-ci.org/camunda/camunda-modeler) to build the release
* [x] execute [integration test](https://github.com/camunda/camunda-modeler/blob/master/docs/.project/INTEGRATION_TEST.md) on [released artifacts](https://github.com/camunda/camunda-modeler/releases)
    * [x] Works on Linux
    * [x] Works on Mac
    * [ ] Works on Windows
* [ ] trigger QA for fuzzy testing
* [x] publish release on [Github Releases](https://github.com/camunda/camunda-modeler/releases)
* [x] trigger mirroring of release to https://camunda.org/release/camunda-modeler/ via [Jenkins](https://ci.cambpm.camunda.cloud/job/sideprojects/job/camunda-modeler-desktop-RELEASE/build?delay=0sec)
* [x] update download version of Camunda Modeler at [camunda.com](https://github.com/camunda/camunda.com-new/blob/live/data/releases.json)
* [x] spread the word
    * [x] send [release notice email](https://github.com/bpmn-io/internal-docs/blob/master/camunda-modeler/README.md#release-notice-email)
    * [ ] tweet
* [x] close [current milestone](https://github.com/camunda/camunda-modeler/milestones)

**Comment by pinussilvestrus** [comment]
Executed the integration tests under MacOS 10.14.5. No errors occurred.
