### ISSUE TITLE
Escalation boundary event prevents copy and paste

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1462]
__Describe the Bug__

An escalation event definition on a boundary event prevents the whole thing from pasting:

![capture Urhkmc_optimized](https://user-images.githubusercontent.com/58601/62852254-312dd580-bce9-11e9-90d5-eef855c19c59.gif)

__Steps to Reproduce__

* Open [sample diagram](https://github.com/camunda/camunda-modeler/files/3491451/copy-before.bpmn.txt)
* Select all
* Try copy + paste
* __See that paste is not permitted__
* Change escalation boundary to signal boundary
* __See that pasting works__

__Expected Behavior__

* [ ] Pasting works, even in the presence of escalation boundary events

__Environment__

 - OS: Arch Linux
 - Camunda Modeler Version: `v3.3.0-alpha.1`

**Comment by nikku** [comment]
This is a regression.

**Comment by barmac** [comment]
Will be fixed via https://github.com/bpmn-io/bpmn-js/pull/1169
