### ISSUE TITLE
camunda:failedJobRetryTimeCycle lost on replace

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1464]
__Describe the Bug__

Making boundary events non-interrupting should keep all configured properties including 
a configured `camunda:failedJobRetryTimeCycle`. The property is lost on replace though.

__Steps to Reproduce__

* Open [test diagram](https://github.com/camunda/camunda-modeler/files/3491511/copy-before.bpmn.txt)
* Replace escalation boundary event with non-interrupting version
* See that `camunda:failedJobRetryTimeCycle` is lost

__Expected Behavior__

* [ ] `camunda:failedJobRetryTimeCycle` on `EscalationEventDefinition` is kept on replace

__Environment__

 - OS: Any
 - Camunda Modeler Version: `v3.2.2`, `v3.3.0-alpha.1`

---

Depends on https://github.com/camunda/camunda-bpmn-moddle/issues/48

**Comment by barmac** [comment]
Updated with the current version, as it was already present in 3.2.2

**Comment by nikku** [comment]
Moving to backlog, as it is a known issue.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1468.
