### ISSUE TITLE
Paste requires mouse move in order to work

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1467]
__Describe the Bug__

Two-step copy and paste requires the mouse cursor to move. If I do not move it, the paste operation is rejected:

![capture D1WlTZ_optimized](https://user-images.githubusercontent.com/58601/62939822-6cf09a00-bdd2-11e9-8e21-2f79ca1d967c.gif)

__Steps to Reproduce__

* Copy any element
* `CTRL/CMD + V`
* Click (do not move mouse)
* __Paste is aborted without feedback for the user__

__Expected Behavior__

* [ ] Paste uses the current hover element (last known mouse position) as the default create target

__Environment__

 - OS: Any
 - Camunda Modeler Version: `v3.3.0-alpha.3`

**Comment by pinussilvestrus** [comment]
We will need to extract [the last `mousemove` target](https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/mouse/Mouse.js#L25) just before the first `create.move` is fired.

**Comment by pinussilvestrus** [comment]
Provided a test case and a small sketch for this: [diagram-js branch](https://github.com/bpmn-io/diagram-js/tree/1467-paste-requires-mousemove)

![Kapture 2019-08-13 at 15 46 36](https://user-images.githubusercontent.com/9433996/62946772-9f55c380-bde1-11e9-89f6-9e1ad1ecfeb8.gif)

Let's evaluate next week whether to do it this way.
