### ISSUE TITLE
npm run all error

### ISSUE THREAD

**Issue by AlexeyZabolockyi** [camunda/camunda-modeler#1472]
__Describe the Bug__

```
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alexey/.npm/_logs/2019-08-20T13_43_31_772Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! camunda-modeler-builder@0.0.0 client:build: `(cd client && npm run build)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the camunda-modeler-builder@0.0.0 client:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alexey/.npm/_logs/2019-08-20T13_43_31_806Z-debug.log
ERROR: "client:build" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! camunda-modeler-builder@0.0.0 build: `run-s client:build "build:distro -- {@}" "build:test-distro -- {@}" --`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the camunda-modeler-builder@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alexey/.npm/_logs/2019-08-20T13_43_31_870Z-debug.log
ERROR: "build --" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! camunda-modeler-builder@0.0.0 all: `run-s clean lint test "build -- {@}" --`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the camunda-modeler-builder@0.0.0 all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alexey/.npm/_logs/2019-08-20T13_43_31_920Z-debug.log
```

__Steps to Reproduce__

```bash
git clone https://github.com/camunda/camunda-modeler.git
cd camunda-modeler
git pull
npm install
npm run all
```

__Expected Behavior__

All scripts finished without any exceptions and modeler launched

__Environment__

 - OS: Ubuntu 18.04
 - Camunda Modeler Version: 3.2.3 develop branch
 - Npm: 6.10.3
 - Node: 12.8.1

**Comment by AlexeyZabolockyi** [comment]
Decision from https://github.com/camunda/camunda-modeler/issues/1087 does not help.

**Comment by nikku** [comment]
What exact steps do you undertake to reproduce the issue? Please provide us the commands (from download to run) that you feed into your CLI.

**Comment by AlexeyZabolockyi** [comment]
I execute next commands:
1. git clone https://github.com/camunda/camunda-modeler.git
2. git pull (to be sure that no one update is missing)
3. npm install
4. npm run all
If it will help you. i use VM VirtualBox 6.0.10 to work on Ubuntu 18.04. If it's a problem with my machine, like it was in previous task, Please. let me know how to solve it or how to configure machine to solve this problems, thank you

**Comment by barmac** [comment]
First, I tried this on a fresh install of Ubuntu 18.04.2 LTS in VirtualBox 5.2.20 r125813 (Qt5.6.3). The build finishes without any error.
The steps I followed were the following:
```bash
sudo apt install git
// install nvm https://github.com/nvm-sh/nvm#installation-and-update
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
// reopen terminal
nvm install 12
// the steps you provided
git clone https://github.com/camunda/camunda-modeler.git
cd camunda-modeler
git pull
npm install
npm run all
```

Then, I downloaded 6.0.10 r132072 (Qt5.6.3) and repeated the process. Still no errors.

I'd suggest you to try to clone the repo once more and make sure that you run the script from the repo's root directory. This does not seem to be a problem with Camunda Modeler.

**Comment by AlexeyZabolockyi** [comment]
what version of npm and node do you use?

**Comment by barmac** [comment]
`6.10.2` and `v12.9.0` respectively

**Comment by AlexeyZabolockyi** [comment]
package.json is on its place.
"build": "cross-env NODE_ENV=production webpack", - it's all that i have in it with build script.

**Comment by AlexeyZabolockyi** [comment]
it looks like one big joke. I've pulled. reexecute commands 'npm install' and 'npm run all'. and now i have another error : 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! camunda-modeler-builder@0.0.0 build:distro: `node tasks/distro.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the camunda-modeler-builder@0.0.0 build:distro script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alexey/.npm/_logs/2019-08-21T10_27_36_870Z-debug.log
ERROR: "build:distro --" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! camunda-modeler-builder@0.0.0 build: `run-s client:build "build:distro -- {@}" "build:test-distro -- {@}" --`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the camunda-modeler-builder@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alexey/.npm/_logs/2019-08-21T10_27_36_955Z-debug.log
ERROR: "build --" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! camunda-modeler-builder@0.0.0 all: `run-s clean lint test "build -- {@}" --`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the camunda-modeler-builder@0.0.0 all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alexey/.npm/_logs/2019-08-21T10_27_37_051Z-debug.log

**Comment by AlexeyZabolockyi** [comment]
[log.txt](https://github.com/camunda/camunda-modeler/files/3524877/log.txt)
add log file may be it will clarify situation for you.

**Comment by barmac** [comment]
Thanks for the log. It seems to be helpful.

According to [this bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=397763), the problem might come from lacking disk space. For my tests, I set a 20 GB limit on Ubuntu. Maybe there is just too little space to actually handle the whole build process. Please note that the `dist` folder with a built Linux version of Camunda Modeler takes 650 MB.

**Comment by AlexeyZabolockyi** [comment]
wow! its finally start to work! thank you very much. But i still have a few questions. First of all i reinstal my vm and choose VDI instead of VHD. could it matter? And the second  when i try to create new file i don't see anythink, file type menu is empty. why?

**Comment by AlexeyZabolockyi** [comment]
problem is faded away, thank you.
bye

**Comment by dubnemo** [comment]
What are the minimum Node.js and npm versions?

I tried installing Modeler on Raspbian Buster latest and I am getting deprecation messages for specific packages, and then PhantomJS not found.

/media/pi/Storage/camunda-modeler $ npm install

npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> phantomjs-prebuilt@2.1.16 install /media/pi/Storage/camunda-modeler/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Unexpected platform or architecture: linux/arm
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN karma-sinon-chai@1.3.4 requires a peer of sinon@>=2.1.0 <5 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-05T13_46_44_081Z-debug.log

df -Th
 11G  358M  9.6G   4% /media/pi/Storage
So this is not a disk space issue.

**Comment by barmac** [comment]
What commit did you clone? We have dropped phantomjs in fb7058b680b2c986acbe842060f8cde8a4cbb494

Also, the npm warning might be related to https://github.com/nodejs/help/issues/1877

I'd generally recommend latest LTS version of Node.js which is v12.13.0 now. We do not aim at supporting any specific Node.js version for the build tool.

**Comment by dubnemo** [comment]
@barmac 
It seems that I will not be able to update Node.js to v12.13.0.  All signs indicate the Raspberry Pi4 Raspbian Buster is an unsupported platform.  

$ sudo apt-get install nodejs npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (**10.21.0~**dfsg-1~deb10u1+rpi1).
npm is already the newest version (5.8.0+ds6-4+deb10u1).

git clone https://github.com/camunda/camunda-modeler.git -b v4.1.1 camunda-modeler
npm install

31513 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
31514 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
31515 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
31515 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
31515 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
31515 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: arm
31516 verbose stack Error: @sentry/cli@1.52.3 install: `node scripts/install.js`
31516 verbose stack Exit status 1
31516 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:283:16)
31516 verbose stack     at EventEmitter.emit (events.js:198:13)
31516 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
31516 verbose stack     at ChildProcess.emit (events.js:198:13)
31516 verbose stack     at maybeClose (internal/child_process.js:982:16)
31516 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
31517 verbose pkgid @sentry/cli@1.52.3
31518 verbose cwd /media/pi/Storage/camunda-modeler/client
31519 verbose Linux 4.19.118-v7l+
31520 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
31521 verbose node v10.21.0
31522 verbose npm  v5.8.0
31523 error code ELIFECYCLE
31524 error errno 1
31525 error @sentry/cli@1.52.3 install: `node scripts/install.js`
31525 error Exit status 1
31526 error Failed at the @sentry/cli@1.52.3 install script.
31526 error This is probably not a problem with npm. There is likely additional logging output above.
31527 verbose exit [ 1, true ]

**Comment by barmac** [comment]
According to [this tutorial], you can install Node v14 on Raspbian: https://thisdavej.com/beginners-guide-to-installing-node-js-on-a-raspberry-pi/#install-node

Anyway, what is your use case? What is the purpose of building Camunda Modeler on Raspberry Pi?

**Comment by dubnemo** [comment]
I see, a new apt repository entry.  That makes sense.  I will test that out tomorrow.

I am running a RPi4 with 4G.  I want to see how performant the computer is, and IMHO the Modeler is a good use case.    Soon Raspberry Pi 64bit OS will be available, which should be great with the 8G version of the RPi4.
