### ISSUE TITLE
Labels don't get saved when editor is still focused on the text

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#1473]
__Describe the Bug__

When direct editing is active, the currently edited text is not being flushed on diagram save:

![Aug-20-2019 17-06-17](https://user-images.githubusercontent.com/17595149/63359668-6bdce100-c36d-11e9-8061-0a635e57fa91.gif)

__Steps to Reproduce__

- enter the edit mode of any label (focus)
- save the diagram without deactivating the focus
- open the saved diagram

result: the label was not saved

__Expected Behavior__

* [ ] before actually saving the file complete direct editing so that the content of the label is synced into the XML

__Environment__

Camunda Modeler: v3.2.3
Operating System: OSX

**Comment by benhoffmann** [comment]
Closely related to that: labels should not be deleted when I hit Esc after typing

**Comment by nikku** [comment]
We'll tackle the original issue. 

We won't tackle the related behavior you mentioned:

> Closely related to that: labels should not be deleted when I hit Esc after typing

If you'd like to commit a change, press `ENTER`.

**Comment by benhoffmann** [comment]
good that the original issue will be fixed.

> If you'd like to commit a change, press ENTER.

This is quite an inconsistent user experience. I don't have to "commit" a change with ENTER anywhere else, e.g. when using the property panel or when editing stuff in DMN. Why would I have to commit when editing labels?

**Comment by nikku** [comment]
I absolutely understand the impact of this. Unfortunately we cannot easily work around that behavior, so it will be improved at a later point in time :wink:.

**Comment by pinussilvestrus** [comment]
What about listening for [`saveXML.done` to complete the direct editing](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/label-editing/LabelEditingProvider.js#L46)?

**Comment by oguzeroglu** [comment]
Should we consider calling setText of UpdateLabelHandler on keydown instead of focus-out?

**Comment by oguzeroglu** [comment]
@pinussilvestrus Good idea, however saveXML.start does not seem to be triggered when there's no change in the diagram, For example:

1) Save the diagram
2) Enable direct editing
3) Save the diagram again while direct editing

does not trigger saveXML.start on step 3.
