### ISSUE TITLE
Retrieving Plugins Fails When Diagram Can't Be Opened

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1479]
__Describe the Bug__

When opening a broken diagram there's an uncaught error in the console:

```javascript
AppParent.js:178 Uncaught (in promise) TypeError: this.getPlugins(...).getAll is not a function
    at Ci.hasPlugins (AppParent.js:178)
    at Ci.wi (AppParent.js:194)
```

__Steps to Reproduce__

1. Open [broken.bpmn](https://github.com/camunda/camunda-modeler/blob/master/docs/.project/broken.bpmn)

__Expected Behavior__

No error in console.

__Environment__

 - OS: Windows 10
 - Camunda Modeler Version: 3.3.0

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1482.
