### ISSUE TITLE
Do Not Show Preview If Create Is Not Allowed

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1481]
If the user leaves the canvas during create we still show a preview even though creating won't be allowed.

![foobar](https://user-images.githubusercontent.com/7633572/63578205-411ea280-c590-11e9-914c-ef0806cedcf9.gif)

**Comment by nikku** [comment]
Additional question: What would be the expected behavior here? There is a few routes we can go:

* If non-canvas drop target, keep last, good known canvas drop target
* If non-canvas drop target, cancel operation or display not allowed on root?
* If non-canvas drop target, remove drag preview?

**Comment by philippfromme** [comment]
> * If non-canvas drop target, keep last, good known canvas drop target

My favorite!

**Comment by nikku** [comment]
Moving this as a possible future enhancement into the backlog.

**Comment by nikku** [comment]
Fixed via https://github.com/bpmn-io/diagram-js/pull/408. 

Needs to be released and integrated.

**Comment by oguzeroglu** [comment]
Closed via Camunda modeler 3.4.0 release.
