### ISSUE TITLE
Rework the plugin system

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1485]
* [x] Rework UI extension to provide context.
* [x] Show Fills in a stable order.
* [x] Provide an API to log from an extension.
* [x] Provide an API to subscribe to events (`tab.open` etc.).
* [ ] Provide an API to access file system.
* [ ] Implement deployment tool as a 100% client extension. https://github.com/camunda/camunda-modeler/issues/1488

**Comment by nikku** [comment]
Can we close this? I guess we got this pretty much covered with other open / in progress issues.
