### ISSUE TITLE
Remove the ability to model collapsed sub-processes

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1486]
__Is your feature request related to a problem? Please describe.__

Collapsed sub-processes are not well supported across the Camunda tool stack (Cockpit, Optimize, ...). Generally, users should resort to call activities to break up their big processes. 

__Describe the solution you'd like__

In order to not cause users trouble when automating their processes we should disallow the usage of collapsed sub-processes. To support it we'll do the following:

* [x] Create and publish bpmn-js plug-in:
  * [x] Replace _Sub Process (expanded)_ and _Sub Process (collapsed)_ with _Sub Process_ and _Expand (not reversible)_
  * [x] Allow to turn tasks into collapsed Sub Process
  * [x] Disallow to collapse Sub Process
* [x] Disable collapsing of Sub-Processes in Camunda Modeler

__Describe alternatives you've considered__

* [x] We could simply discourage the usage of collapsed sub-processes via a lint rule (cf. https://github.com/camunda/bpmnlint-plugin-camunda/pull/1)

__Additional context__

![image](https://user-images.githubusercontent.com/58601/63760340-6c223280-c8bf-11e9-87b3-56f401183461.png)

Cf. [`sub-call.bpmn`](https://github.com/camunda/camunda-modeler/files/3545398/sub-call.bpmn.txt)

Related: https://app.camunda.com/jira/browse/SUPPORT-6256?focusedCommentId=118488&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-118488

**Comment by barmac** [comment]
Foundations in `diagram-js` for the plugin are already merged. Now we need a `bpmn-js` release in order to integrate the plugin with Camunda Modeler.
