### ISSUE TITLE
Empty item in the edit submenu when modeling BPMN diagram

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1487]
__Describe the Bug__

There is an empty menu item in the edit submenu when modeling BPMN diagram. When you click on it, Camunda Modeler reports an error (_no such action as `null`_).

<img width="904" alt="Screenshot 2019-08-27 at 15 59 22" src="https://user-images.githubusercontent.com/28307541/63777789-06946d00-c8e4-11e9-81df-c0070f48cc6f.png">

__Steps to Reproduce__

1. Open BPMN tab
2. Open edit submenu

__Expected Behavior__

There should be no such item in the menu.

__Environment__

 - OS: MacOS, Linux
 - Camunda Modeler Version: 3.3.1

**Comment by nikku** [comment]
Can reproduce this one on Linux, too.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1495.
