### ISSUE TITLE
unable to set retry interval

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#149]
In this process definition ([1](https://github.com/camunda/camunda-consulting/blob/master/showcases/twitter/src/main/resources/TwitterDemoProcess.bpmn)) it is not possible to set the retry interval for the service task 'Publish on twitter'. 

Steps to reproduce: Mark the service task as asyncBefore and enter `R3/PT10S` in the retry time cycle.
My observation: Any typed character in the Retry-box disappears after I entered it. 
When I save the diagram, the xml has these elements in the service task:
`cmd="properties-panel.update-businessobject-list" context="[object Object]"` and couldn't be deployed into the engine.

**Comment by romansmirnov** [comment]
Hi @ingorichtsmeier,

This is a duplicate of this issue https://github.com/bpmn-io/bpmn-js-properties-panel/issues/147

Cheers,
Roman
