### ISSUE TITLE
Show Fills in a stable order

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1492]
The Fills should be displayed in a stable order. Currently, we have the prioritized default groups and then the other groups are handled in a first come, first served manner. To allow the extension authors to precisely place their own fills, we should have a stable ordering rules here.

Currently existing groups:
- **general**
- **save**
- **editor**
- **export**
- color
- align
- distribute
- deploy

**bold** - prioritized

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1493.
