### ISSUE TITLE
Add ability to configure bpmn-js from client extension

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1499]
__Is your feature request related to a problem? Please describe.__

Add the ability to provide a bpmn-js extension via a client extension:

```javascript
export default class TestEditorEvents extends PureComponent {

  constructor(props) {

    super(props);

    const {
      subscribe
    } = props;

    subscribe('bpmn.modeler.configure', (event) => {

      const {
        tab,
        middlewares
      } = event;

      log('Creating editor for tab', tab);

      middlewares.push(addModule(BpmnModelerExtension));
    });
}
```

Cf. [`TestEditorEvents`](https://github.com/camunda/camunda-modeler/blob/develop/resources/plugins/test-editor-events/client/TestEditorEvents.js) for full example.

__Describe the solution you'd like__

* [ ] Implement `bpmn.modeler.configure` event that allows extensions to configure bpmn-js instances.

---

Child of #1496

**Comment by pinussilvestrus** [comment]
Closed via dff30e59d21155630cb7928e15cd3c9d700ddd64
