### ISSUE TITLE
Add ability to hook into created bpmn-js from client extension

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1500]
__Is your feature request related to a problem? Please describe.__

Add ability to hook into created bpmn-js instances from client extension.

```javascript
export default class TestEditorEvents extends PureComponent {

  constructor(props) {

    super(props);

    const {
      subscribe
    } = props;

    subscribe('bpmn.modeler.created', (event) => {

      const {
        tab,
        modeler,
      } = event;

      log('Modeler created for tab', tab);

      modeler.on('saveXML.start', (event) => {

        const {
          definitions
        } = event;

        log('Saving XML with definitions', definitions, tab);
      });

    });
}
```

Cf. [`TestEditorEvents`](https://github.com/camunda/camunda-modeler/blob/develop/resources/plugins/test-editor-events/client/TestEditorEvents.js) for full example.

__Describe the solution you'd like__

* [ ] Implement `bpmn.modeler.created` event that allows extensions to hook into bpmn-js after creation, i.e. to register for events

---

Child of https://github.com/camunda/camunda-modeler/issues/1496

**Comment by pinussilvestrus** [comment]
Closed via b12480ee534b629b9317ebf1147850cffebb619c
