### ISSUE TITLE
Remove exclusive property from property panel

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#1501]
Remove the `exclusive` property of elements using asynchronous continuation.

I continue to see customers toying around with it without knowing how much trouble it can cause them. Furthermore, customers who do know the effect of disabling it are most likely abusing the engine's job executor for work that is better offloaded to external task workers.

If removing is considered too harsh, we should at least warn customers that they are getting into multi-threading and optimistic locking territory.

**Comment by benhoffmann** [comment]
I would vote for adding a big warning instead of removing the property completely.

**Comment by nikku** [comment]
Linting / warning is a good way to approach this issue, cf. https://github.com/bpmn-io/bpmnlint/issues/34 / https://github.com/camunda/bpmnlint-plugin-camunda/issues/3.

**Comment by nikku** [comment]
We'll not remove the property but consider adding a validation rule for it. Linting is available as a plug-in today and will one day be available as a core capability of the tool.
