### ISSUE TITLE
Ids Not Unclaimed When Removing Elements

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1503]
__Describe the Bug__

Ids are not unclaimed when removing elements.

![foobar](https://user-images.githubusercontent.com/7633572/64706078-3f6e3d80-d4b1-11e9-9cf8-e6344a065598.gif)

__Steps to Reproduce__

1. Open [foo.bpmn.txt](https://github.com/camunda/camunda-modeler/files/3601263/foo.bpmn.txt)
2. Delete elements one at a time
3. Create new element and set ID to `foo`

> Deleting all elements at once doesn't reproduce the issue

__Expected Behavior__

`foo` should be available

__Environment__

 - Camunda Modeler Version: 3.3.4

---

Related to https://github.com/bpmn-io/bpmn-js/issues/608

**Comment by pinussilvestrus** [comment]
Seems like we [do not unclaim](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/behavior/UnclaimIdBehavior.js#L20) any id of a removed element's _children_. However, this seems to be a long-term issue, since I was able to reproduce it on Modeler version `2.2.4`.

**Comment by pinussilvestrus** [comment]
Is there any good reason why to not listen for `shape.delete` instead of `elements.delete`? This way we would also unclaim the children's id.

**Comment by nikku** [comment]
Closed, cf. https://github.com/bpmn-io/bpmn-js/issues/608#issuecomment-564895334
