### ISSUE TITLE
Copying Extension Elements with Unknown Type Fails

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1507]
__Describe the Bug__

Copying extension elements with an unknown namespace (e.g. Signavio) fails. Copies cannot be created since we don't know the Signavio model.

__Steps to Reproduce__

1. Open [copy-signavio-extension-elements.bpmn.txt](https://github.com/camunda/camunda-modeler/files/3642411/copy-signavio-extension-elements.bpmn.txt)
2. Change user task to plain task

__Expected Behavior__

* no error
* extension elements are not copied

__Environment__

 - Camunda Modeler Version: ^3.3.0

---

Support: https://app.camunda.com/jira/browse/SUPPORT-6386

**Comment by pinussilvestrus** [comment]
Will be fixed with upcoming patch release, cf. https://github.com/bpmn-io/bpmn-js/pull/1201

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1513#pullrequestreview-293041737
