### ISSUE TITLE
Move labels with connections on relayout

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#151]
We should move the label with a connection if the connection gets relayouted.

This way we make sure the label "does not get lost".
 
![label](https://cloud.githubusercontent.com/assets/58601/13222523/8b415240-d980-11e5-857a-50c0d6a5a1e5.gif)

**Comment by gimbel** [comment]
This is related to: https://github.com/bpmn-io/bpmn-js/issues/331
