### ISSUE TITLE
I Can Update My DMN Diagram to DMN 1.3 Namespace

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1510]
When opening a DMN diagram I want to be able to upgrade its namespace to DMN 1.3.

#### Context

DMN 1.3 is out and is being picked up by other tool vendors. It is supported by our DMN engine since 7.12 and backported to supported older enterprise versions of the engine.

#### Our Migration Strategy

* Future versions of dmn-js we will only support DMN 1.3 for editing / viewing
* Upon opening a DMN 1.1 file in the Camunda Modeler, users will be able to migrate the diagram to DMN 1.3 so that it can be edited as DMN 1.3
* Diagrams saved after the migration will be DMN 1.3

#### Tasks

* [x] DMN 1.3 is implemented in dmn-js (https://github.com/bpmn-io/dmn-js/issues/409)
* [x]  DMN 1.1 -> 1.3 migration support is implemented in the Camunda Modeler

---

Depends on https://github.com/bpmn-io/dmn-js/issues/409

Related to [CAM-10810](https://app.camunda.com/jira/browse/CAM-10810).

**Comment by nikku** [comment]
I guess we can go ahead and finalize this one now :bike:

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1688
