### ISSUE TITLE
I can define a task listener for event `update`

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda-modeler#1517]
Camunda BPM 7.12 will have a feature to define a task listener for all kinds of updates to a task: https://app.camunda.com/jira/browse/CAM-10254

It should be possible to define a task listener for the `update` event, so that the following XML is generated:

```
<bpmn:userTask id="myTask">
  <bpmn:extensionElements>
    <camunda:taskListener class="my.java.Class" event="update" />
  </bpmn:extensionElements>
</bpmn:userTask>
```

This listener should have the same configuration options like a `create` listener.

**Comment by pinussilvestrus** [comment]
Waiting for [`bpmn-js-properties-panel`](https://github.com/bpmn-io/bpmn-js-properties-panel/commit/775fae0d41cfaf518948b7a5ab8806af034ba1e0) to be released.
