### ISSUE TITLE
non-interrupting boundary event is not being stopped till the main process is running

### ISSUE THREAD

**Issue by siyer94** [camunda/camunda-modeler#1523]
hi,

I have added a non-interrupting conditional boundary event on script task based on some condition, but it is not being stopped till the main process is running.
The task which is called on the event is continously being executed till the main process is ended.

__Describe the Bug__

__Steps to Reproduce__

1. do this
2. do that

__Expected Behavior__

__Environment__

 - OS: [e.g. MacOS 10.2, Windows 10]
 - Camunda Modeler Version: [e.g. 2.0.0]

**Comment by siyer94** [comment]
OS : ubuntu
Camunda modeler version : 3.1.2

**Comment by philippfromme** [comment]
As I [already said](https://github.com/camunda/camunda-modeler/issues/1524) the right place for questions regarding the Camunda BPM engine is the [Camunda BPM forum](https://forum.camunda.org/).
