### ISSUE TITLE
org.camunda.bpm.engine.OptimisticLockingException: ENGINE-03005 Execution of 'DELETE VariableInstanceEntity failed

### ISSUE THREAD

**Issue by siyer94** [camunda/camunda-modeler#1524]
in my workflow i m running parallel multi instance execution. When the parallel instances completes at the same time, im getting this error. I have added async before and after at the end events. This resolved the issue for some time but again i got the same issue.

__Describe the Bug__

__Steps to Reproduce__

1. do this
2. do that

__Expected Behavior__

__Environment__

 - OS: [e.g. MacOS 10.2, Windows 10]
 - Camunda Modeler Version: [e.g. 2.0.0]

**Comment by siyer94** [comment]
Environment : 
os : Ubuntu
camunda modeler version: 3.1.2

**Comment by philippfromme** [comment]
Please head over to the [Camunda BPM forum](https://forum.camunda.org/) for any questions regarding the Camunda BPM engine. Please make sure you're in the right place before opening issues etc.
