### ISSUE TITLE
Gateway added to next element in process graph, not to the selected task

### ISSUE THREAD

**Issue by rob2universe** [camunda/camunda-modeler#1528]
__Describe the Bug__
When adding a gateway to a task, it looks as if it is added to the next element in process graph, not to the selected task.

__Steps to Reproduce__

1. create a new BPMN diagram with three sequentially connected tasks (A,B,C)
2. use fly-out menu of first task A to add a gateway connected to task A
    __it looks the gateway is connected to task B instead of A__

__Expected Behavior__

Connection alignment for gateways should be consistent with alignment for other elements.

![AddGatewaytoA](https://user-images.githubusercontent.com/1978908/66537576-805e7e00-eb53-11e9-8b57-509038033e8b.GIF)
![gatewayAddedtoB](https://user-images.githubusercontent.com/1978908/66537577-83596e80-eb53-11e9-8545-d161656373d3.GIF)
__Environment__

Camunda Modeler version 3.3.5
Windows 10

**Comment by pinussilvestrus** [comment]
When you move the created Gateway, you will discover, that it is added to the selected task. What is kind of broken her is the connection alignment behavior, which should work as for all other elements.

![Kapture 2019-10-10 at 8 53 35](https://user-images.githubusercontent.com/9433996/66545667-8183b100-eb3b-11e9-89bd-fa9316b703ba.gif)

**Comment by rob2universe** [comment]
You are right. Then the issue is obviously less significant. I update the ticket description accordingly. Thannks!

**Comment by philippfromme** [comment]
The gateway is added to the right task, the connection might be partially obscured by another element. That's not considered a bug. I'll close this issue.
