### ISSUE TITLE
Release v3.4

### ISSUE THREAD

**Issue by oguzeroglu** [camunda/camunda-modeler#1532]
* [x] put up code freeze appointment in calendar (include `modeling`, `qa`, `sre`, and `ilias.kourtoudis`) 
* [x] make sure dependencies are released (`rm -rf node_modules && npm i && npm run all` works)
    * `diagram-js` @oguzeroglu 
    * `dmn-js` @barmac 
    * `bpmn-js` @oguzeroglu
* [x] close all issues which are solved by dependency updates
* [x] verify `develop` is up to date with `master`: `git checkout master && git pull && git checkout develop && git merge master`
* [x] smoke test to verify all diagrams can be created
* [x] update CHANGELOG
* [x] semantic release (`npm run release`), cf. [release schema](https://github.com/bpmn-io/internal-docs/tree/master/release-schema) 
* [x] merge to master: `git checkout master && git merge develop`
* [x] wait for [Travis](https://travis-ci.org/camunda/camunda-modeler) to build the release
* [x] execute [integration test](https://github.com/camunda/camunda-modeler/blob/master/docs/.project/INTEGRATION_TEST.md) on [released artifacts](https://github.com/camunda/camunda-modeler/releases)
    * [x] Works on Linux
    * [x] Works on Mac @oguzeroglu 
    * [x] Works on Windows
* [x] trigger QA for fuzzy testing
* [x] publish release on [Github Releases](https://github.com/camunda/camunda-modeler/releases)
* [x] write blog post on [blog.camunda.org](https://github.com/camunda/blog.camunda.org), Cf. #1533  
* [x] trigger mirroring of release to https://camunda.org/release/camunda-modeler/ via [Jenkins](https://ci.cambpm.camunda.cloud/job/sideprojects/job/camunda-modeler-desktop-RELEASE/build?delay=0sec)
* [x] update download version of Camunda Modeler at [camunda.com](https://github.com/camunda/camunda.com-new/blob/live/data/releases.json)
* [x] spread the word
    * [x] send [release notice email](https://github.com/bpmn-io/internal-docs/blob/master/camunda-modeler/README.md#release-notice-email)
    * [x] tweet
* [x] close [current milestone](https://github.com/camunda/camunda-modeler/milestones)

**Comment by nikku** [comment]
Please use the official [release checklist](https://github.com/camunda/camunda-modeler/blob/develop/docs/.project/RELEASE_CHECKLIST.md)
