### ISSUE TITLE
Horizontal scrolling for DMN tables is missing

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1537]
__Describe the Bug__

Horizontal scrolling for DMN tables is not working

__Steps to Reproduce__

// when 
I create a number of input/output columns that does not fit onto my screen

// then
I cannot scroll to the left or the right side of my dmn table

// expected behavior
a scroll bar and the possibility to use SHIFT + Mouse Wheel for horizontal scrolling

// workaround
you can tab through the table cells from left to right and back ;)

__Environment__

WIN 10
Modeler V 3.4.0

**Comment by oguzeroglu** [comment]
Closed via #1539
