### ISSUE TITLE
Be able to edit timeout event on task listeners

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1540]
__Is your feature request related to a problem? Please describe.__

Starting with Camunda BPM Runtime 7.12.0-alpha4, time-triggered task listeners can be used.

An example looks like this:

```xml
...
<bpmn:userTask id="myTask">
  <bpmn:extensionElements>
    <camunda:taskListener delegateExpression="${setBusinessKeyListener}" event="timeout" id="timeout-friendly" >
      <bpmn:timerEventDefinition>
        <bpmn:timeDuration xsi:type="bpmn:tFormalExpression">PT1H</bpmn:timeDuration>
      </bpmn:timerEventDefinition>
    </camunda:taskListener>
  </bpmn:extensionElements>
</bpmn:userTask>
...
```

#### Expected solution

1. Value `timeout` allowed for `event` attribute of `camunda:taskListener`
1. Element `timerEventDefinition` now allowed as a child of `camunda:taskListener`, but only if the `event` of the `camunda:taskListener` is set to `timeout`
2. New attribute `id` for `camunda:taskListener`, only mandatory if `event` of `camunda:taskListener` is set to `timeout`
* Existing property panel controls for TimerBoundaryEvents can be used here as well for the timer event definition, if the `timeout` value is chosen as event type of the task listener.

__Additional context__

Should be shipped with Camunda Modeler until 30th of November, as it is supported in the upcoming Camunda Platform 7.12 release.

Original opened issue: https://github.com/camunda/camunda-bpmn-moddle/issues/50.

**Comment by pinussilvestrus** [comment]
> Element timerEventDefinition now allowed as a child of camunda:taskListener, but only if the event of the camunda:taskListener is set to timeout

Do we need an extra validation on the `camunda-bpmn-moddle` side, or do we just restrict it on UI side (properties panel)? Don't know whether a similar case on this kind of validation already exists on somep place.

**Comment by nikku** [comment]
Let's restrict the UI side for now. Reasoning: 

* The engine validates anyway
* Validation is super complex on the moddle side for this one

**Comment by pinussilvestrus** [comment]
> Existing property panel controls for TimerBoundaryEvents can be used here as well for the timer event definition, if the timeout value is chosen as event type of the task listener.

I'll try to re-use the current [TimerEventDefinition controls](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/bpmn/parts/implementation/TimerEventDefinition.js), by doing a little bit of refactoring.

**Comment by pinussilvestrus** [comment]
Waiting for upstream changes to be released, cf. https://github.com/bpmn-io/bpmn-js-properties-panel/pull/321
