### ISSUE TITLE
Ask user for privacy preferences

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1543]
__Is your feature request related to a problem? Please describe.__

As part of our automatic update check (#1541) we are going to send data to an update server to check, whether a new version of the app is available. We need to get the users consent, whether we are allowed to do that or not.

We take this as an opportunity to ask for three kinds of consent:

* Consent for update checks
* Consent for automatic crash reports
* Consent for anonymous analytics data

__Describe the solution you'd like__

* [x] If not asked before, ask the user about the privacy preferences:
    - whether to send crash reports
    - whether to send anonymous analytics data
    - whether to automatically check for updates
* [x] Store that information in the user configuration on her local disk

__Additional context__

Linked to [Prodpad idea](https://app.prodpad.com/ideas/207/canvas).

--- 

Child of #1541

**Comment by oguzeroglu** [comment]
- Should function only if `--server-interaction` feature flag is set.
- If this flag is not set the popup should not be visible, also Help > Privacy Preferences should not exist.
- If this flag is set, initially a popup must appear when the app is started with no Cancel button and no Exit icon. All of the preferences should be set to default by default. There should be only one Save button.
- Once the user has made a preference, this popup should no longer be visible when the app starts.
- Users can change their preferences by going Help >  Privacy Preferences. In this case, an additional Cancel button must be existent inside the popup.
- Preferences should not be updated if the user clicks on Cancel, they must be updated if the user clicks on Save. Saved Preferences should be persistent, should not disappear once the app is closed.

**Comment by oguzeroglu** [comment]
After having a meeting with Volker, we decided that it's better to change Crash Reporting to Error reporting, as Crash indicates a fatal error leads to the app getting closed but we want to capture minor exceptions as well.
