### ISSUE TITLE
As a user I can update my privacy preferences

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1544]
__Is your feature request related to a problem? Please describe.__

Related to https://github.com/camunda/camunda-modeler/issues/1543 I can update my privacy preferences via an entry in the menu.

__Describe the solution you'd like__

* [x] A menu entry exists that opens the [privacy consent screen](https://github.com/camunda/camunda-modeler/issues/1543) with prior input
* [x] Updating the screen changes my privacy preferences

---

Child of https://github.com/camunda/camunda-modeler/issues/1541

**Comment by oguzeroglu** [comment]
Closed via #1597 1597
