### ISSUE TITLE
Check for Modeler updates

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1545]
__Is your feature request related to a problem? Please describe.__

We would like to improve the adoption of new modeler releases by providing users with an update notification. 

__Describe the solution you'd like__

* [ ] Given user consent (https://github.com/camunda/camunda-modeler/issues/1543) an update check is performed every time the modeler is started
* [ ] If an update is available, guide users to the download page or allow them to ignore the update
* [ ] Only ask once for a particular update version (i.e. if she got notified for v3.5.0, don't ask until a new version is released)
* [ ] The update check sends information about the current modeler version as well as used plug-ins to determine, if updates are possible
* [ ] Temporarily unreachable update server does not result in a user facing error
* [ ] Automatic update checks may be disabled via feature toggle
* [ ] The URL of the update server may be configured via flags

__Additional Considerations__

* Is an update check on start sufficient or should we check once per day?

---

Child of https://github.com/camunda/camunda-modeler/issues/1541

**Comment by oguzeroglu** [comment]
We've decided:

We want to show a popup (modal) if server sends an update response (a newer version exists). We can consider adding a "Don't show this again" selection inside the modal for a better UX.

The primary goal of this popup is that the user clicks on the download URL.
The secondary goal is that the user is informed about what actually changed between their version and the newest version.

We'll implement couple of prototypes to decide what works best for us and for the user.

**Comment by oguzeroglu** [comment]
To answer the question:

> Additional Considerations

> Is an update check on start sufficient or should we check once per day?

I'd say the best solution would be:

When the app starts, Update checker module reads the latest checked date from the configurations. If such configuration does not exist or if it was older than a day ago, it performs a check.

**Comment by nikku** [comment]
Sounds reasonable to me.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1618
