### ISSUE TITLE
An update server to query for Modeler updates exists

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1546]
* [x] Update server technology is chosen, decision whether to roll our own _or_ use something pre-built is made
* [x] Update server is available online on a wellknown, secure (HTTPS) endpoint
* [x] Update server logs the following information: 
    * OS version
    * Modeler version
    * Installed plug-ins (names)
* [x] Update server responds with new version of the app as well as link to download page, if it is available => Not returning new version right now, operating in a dry run mode instead.

--- 

Child of https://github.com/camunda/camunda-modeler/issues/1541

**Comment by nikku** [comment]
We decided to not return a new version with the server right now. Instead it is operating in a dry run mode and only logs results.

**Comment by oguzeroglu** [comment]
The server's here: https://github.com/camunda/camunda-modeler-update-server

**Comment by oguzeroglu** [comment]
@nikku from Volker's perspective everything looks fine now. I guess we can start the code review process.

**Comment by nikku** [comment]
I'll review this one tomorrow.

**Comment by oguzeroglu** [comment]
@pinussilvestrus Reviewed the server, had some feedbacks. I fixed those feedbacks today so closing this issue.
