### ISSUE TITLE
Exported SVG image with incorrect marker id reference generation

### ISSUE THREAD

**Issue by bitarch** [camunda/camunda-modeler#1548]
Hi,

I've just noticed that an exported BPMN diagram as SVG image has marker id references quoted in urls.

```
<defs>
 <marker id="sequenceflow-end-white-black-7a9sifb55yb677cdgf247re6g" ...>
  ...
 </marker>
</defs>
```

```
<g class="djs-visual">
 <path d="m  1160,392L1160,444 " style="fill: none; stroke-width: 2px; stroke: black; stroke-linejoin: round; marker-end: url('#sequenceflow-end-white-black-7a9sifb55yb677cdgf247re6g');"/>
</g>
```

__Expected__

```
<g class="djs-visual">
 <path d="m  1160,392L1160,444 " style="fill: none; stroke-width: 2px; stroke: black; stroke-linejoin: round; marker-end: url(#sequenceflow-end-white-black-7a9sifb55yb677cdgf247re6g);"/>
</g>
```

__Environment__

- OS: Windows 10 Enterprise
- Camunda Modeler Version: 3.4.1

Could you please have a look at it?

Thank you.

**Comment by nikku** [comment]
How is that a problem?

**Comment by bitarch** [comment]
Hi Nico,

Tools that render SVG to PDF (i.e. prawn-svg, Microsoft Print to PDF) are not finding the marker refid resulting in markers not rendered.

See also the W3C recommendation at https://www.w3.org/TR/SVG11/painting.html#MarkerElement.

**Comment by nikku** [comment]
Please guide me to the place that mandates that marker IDs must not be put in ticks.

I've tried a number of freely available converter tools and found only one that had the issue you described. I'm wondering if it is a tool limitation _or_ an error on our side.

**Comment by nikku** [comment]
Were you able to find additional details regarding the issue?
