### ISSUE TITLE
Allow DMN editor to be extended

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1550]
__Is your feature request related to a problem? Please describe.__

We already offer a number of powerful extension points to hook into our BPMN editor. Given the fact that DMN is here to stay we should consider adding the same hooks for our DMN editor.

_Note that the difference between DMN and BPMN is that DMN is a multi-editor editor, while BPMN is a single editor editor (if that makes sense :stuck_out_tongue_winking_eye:)._

__Describe the solution you'd like__

* [ ] DMN editor can be extended via plug-in points similar to the BPMN editor

__Describe alternatives you've considered__

Keep things as is.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1672
