### ISSUE TITLE
Delete messages

### ISSUE THREAD

**Issue by dennisfabri** [camunda/camunda-modeler#1551]
You can create new Messages with the modeler but I haven't found a possibility to delete messages that are not longer needed with in the graphical view.

Deleting lines like the following works, but does not guarantee that the Message is not used anywhere else in the model:
<bpmn:message id="Message_1pj78vk" name="Message_11cheio" />

I would like to have an easy and save way to clean up models from unused messages.

**Comment by dennisfabri** [comment]
@falko: Note from the developer training

**Comment by nikku** [comment]
I believe this is a duplicate of https://github.com/camunda/camunda-modeler/issues/136, could you confirm it?

**Comment by dennisfabri** [comment]
confirmed
