### ISSUE TITLE
Privacy Statement for Camunda modeler

### ISSUE THREAD

**Issue by oguzeroglu** [camunda/camunda-modeler#1559]
__Is your feature request related to a problem? Please describe.__

We should have a privacy statement hosted somewhere so that the users could read it / approve it. We should explain to them why do we want to send requests to our backend, and how they might benefit from it.

__Describe the solution you'd like__

* [ ] Write a Privacy Statement and host it somewhere that is also readable through Camunda Modeler.
* [ ] We understand the upgrade path for the Privacy Statement (how do we change it in the future)

--- 

Child of #1541

See also [privacy statement input](https://docs.google.com/document/d/1qEdenZfufZSHynytlKlbkFFhzokz66KP7ZgXGQs3a2Q/edit).

**Comment by nikku** [comment]
Privacy statement will be hosted on camunda.com. We should link to that statement once we receive it.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1597

**Comment by barmac** [comment]
Or maybe not?

**Comment by nikku** [comment]
Needs integration of real privacy statement.

**Comment by oguzeroglu** [comment]
I'll update the privacy statement URL when it's ready. Since this is behind the feature flag, it's not harmful to keep the old URL for now.

**Comment by oguzeroglu** [comment]
Volker said that the URL would stay the same but the web content would be updated later so I'm closing the issue for now.
