### ISSUE TITLE
Show current file name and path somewhere

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-modeler#156]
When you have a file open you cannot see the current path anywhere (e.g. status bar, title bar, some info dialog, ...). 

Sometimes you want to know where the current file is stored on the file system. It should be possible to see/check this.

**Comment by nikku** [comment]
We are showing that as part of the tab (mouseover should show the file path). That is a standard behavior for Editors (Netbeans, Sublime Text, ...). Where else should we display that information?

**Comment by berndruecker** [comment]
Ah ok - I actually didn't recognize it there. Sorry. I personally would prefer something copy & pastable (to be able to navigate there quickly) - but that is much less urgent - so we can also close this issue.
