### ISSUE TITLE
Web  Browser

### ISSUE THREAD

**Issue by mariohmol** [camunda/camunda-modeler#1561]
Hi there!

Is it possible to run this i a browser instead of a electron? Is feaseable to separate the frontend code to run withou electron?

bests

**Comment by pinussilvestrus** [comment]
The [`Client`](https://github.com/camunda/camunda-modeler/tree/develop/client) part of this application is built on top of [bpmn.io](https://bpmn.io) and could run easily in the browser. It should offer everything to create a web application out of it if someone wants to do it.

**Comment by nikku** [comment]
@pinussilvestrus Thanks for clarifying. Closing this issue.

**Comment by nikku** [comment]
Note that we also host a dedicated example that looks quite similar to the Camunda Modeler: https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel

**Comment by mariohmol** [comment]
awesome!! so with this It will have all the features of the desktop ?

I did this repo to be a wraper for angular  https://github.com/mariohmol/ng-bpmn

So I should use this repo instead of the https://github.com/bpmn-io/bpmn-js ?

thanks!

**Comment by nikku** [comment]
It's your choice what to do and what not to do. Get your head around our tools and mix and match them as you like. Good luck :four_leaf_clover: :crossed_fingers: :heart:.

**Comment by mariohmol** [comment]
I see.. was more asking for a guide as you guys are the expert here =)

But thanks... great project.. thank you!

**Comment by pinussilvestrus** [comment]
Don't hesitate to ask _specific_ questions, if you need help. 👍
