### ISSUE TITLE
Release v3.4.2

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1565]
__What is inside?__

https://github.com/camunda/camunda-modeler/compare/v3.4.1...master

__Checklist__

* [ ] make sure dependencies are released (`rm -rf node_modules && npm i && npm run all` works)
    * `bpmn-js`, `dmn-js`, `cmmn-js`, `*-properties-panel`, `*-moddle`, ...
* [ ] close all issues which are solved by dependency updates
* [ ] smoke test to verify all diagrams can be created
* [ ] update CHANGELOG
* [ ] semantic release (`npm run release`), cf. [release schema](https://github.com/bpmn-io/internal-docs/tree/master/release-schema)
* [ ] wait for [Travis](https://travis-ci.org/camunda/camunda-modeler) to build the release
* [ ] The following things got fixed / need testing: https://github.com/camunda/camunda-modeler/issues/1328, https://github.com/bpmn-io/bpmn-js/pull/1227, https://github.com/bpmn-io/bpmn-js-properties-panel/issues/315)
* [ ] execute integration test, verifying fixed things are actually fixed
* [ ] [optional] trigger QA for fuzzy testing
* [ ] publish release on [Github Releases](https://github.com/camunda/camunda-modeler/releases)
* [ ] trigger mirroring of release to https://camunda.org/release/camunda-modeler/ via [Jenkins](https://ci.cambpm.camunda.cloud/job/sideprojects/job/camunda-modeler-desktop-RELEASE/build?delay=0sec)
* [ ] update download version of Camunda Modeler at [camunda.com](https://github.com/camunda/camunda.com-new/blob/live/data/releases.json)
* [ ] close [current milestone](https://github.com/camunda/camunda-modeler/milestones)

**Comment by barmac** [comment]
We'll release 3.5.0 instead.
