### ISSUE TITLE
Mac OSX v3.4.1 can not be started 

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-modeler#1572]
__Describe the Bug__

The release can not be run on OSX (10.15.1). I get an OSX warning stating that it cannot be opened because Apple cannot scan it for malware.

<img width="435" alt="osx-camunda-modeler" src="https://user-images.githubusercontent.com/814032/68151378-e0252a80-ff41-11e9-9b57-f4e53b87d168.png">

It doesn't matter if the install is done manually or via brew cask

__Steps to Reproduce__

1. use a mac osx with latest OS
2. download 3.4.1 dmg
3. start

__Expected Behavior__

normal start

__Environment__

 - OS: MacOs 10.15.1
 - Camunda Modeler Version: 3.4.1

__Workaround__

You cannot bypass the modal dialog shown above. But you can go to system settings/security and then force the start of the modeller (the following dialog allows starting anyway).
However this requires some knowledge of the OSX security behavior and a lot of trust that the binaries are not corrupted ... so for the OSX dev community, this shoud be fixed somehow, please.

---

Child of https://github.com/camunda/camunda-modeler/issues/1584

**Comment by nikku** [comment]
Popped up in an internal training today to. Some questions:

* Did you recently update your MacOS version?
* Can you reproduce it on Camunda Modeler `< 3.4`, too?

**Comment by jangalinski** [comment]
Yes, I did the latest update this weekend. The security setting "appstore or trusted developers" was required before, but it seems they got this one step further. Hurray for security.
Good news: once you bypassed the dialog, you can start the modeler again without being asked again ...

Versions <3.4 ... will give it a try.  Currently getting the dmg releases from github takes hours. Stay tuned

**Comment by nikku** [comment]
> But you can go to system settings/security and then force the start of the modeller (the following dialog allows starting anyway).
However this requires some knowledge of the OSX security behavior and a lot of trust that the binaries are not corrupted ... so for the OSX dev community, this shoud be fixed somehow, please.

To summarize the impact of this: It is not really possible to open the app on MacOS 10.15.1 for everyday normal users anymore?

**Comment by jangalinski** [comment]
Maybe you (camunda) should have a look at the certified developer registration programm: https://support.apple.com/de-de/HT202491

> Diese Nachrichten bedeuten nicht notwendigerweise, dass mit der App etwas nicht stimmt. Beispielsweise wurden einige App geschrieben, bevor die Entwickler-ID-Registrierung eingeführt wurde. Wenn Ihnen eine Warnmeldung angezeigt wird, bedeutet dies, dass die App nicht vom Entwickler signiert wurde, sodass macOS nicht überprüfen kann, ob die App seit ihrer Veröffentlichung geändert oder beschädigt wurde.

Although I hate it when I cannot control OSS on my machine without asking for permission ...

**Comment by jangalinski** [comment]
> To summarize the impact of this: It is not really possible to open the app on MacOS 10.15.1 for everyday normal users anymore?

If you check the link above: it is well documented and not too hard to find for "normal" users ... but you do not get any hint in the concrete situation. You have to know (and remember)about the security settings ...

**Comment by jangalinski** [comment]
> Versions <3.4 ... will give it a try. Currently getting the dmg releases from github takes hours. Stay tuned

Still downloading ... but reading the ht202491 docs ... I would guess that it is not dependent on the modeler version but how the latest OSX deals with unregistered developers apps ...

**Comment by nikku** [comment]
Thanks for providing the additional details. We'll look into this.

**Comment by nikku** [comment]
Seems like we need to integrate notarization into our build pipeline. [This comment](https://github.com/electron-userland/electron-builder/issues/3870#issuecomment-495087499) shows how it's supposed to work.

**Comment by nikku** [comment]
Also related: https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

**Comment by jangalinski** [comment]
Hurray!

**Comment by nikku** [comment]
:wink: :clap:
