### ISSUE TITLE
Modal Inaccessible on Smaller Screens

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1575]
![modal-overflow](https://user-images.githubusercontent.com/7633572/68295088-e2969a00-0091-11ea-9cdf-9ddd18725a35.gif)

__Describe the Bug__

Due to the fixed position of modals and the inability to scroll within them they might be inaccessible on smaller screens.

__Environment__

 - Camunda Modeler Version: 3.3.5

**Comment by nikku** [comment]
Will likely be improved via https://github.com/camunda/camunda-modeler/issues/1558.

**Comment by aravindhrs** [comment]
same issue persists in latest camunda modeler release version 3.6.0 also

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1686
