### ISSUE TITLE
unrecognized element <import> [ warning ]

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#1576]
__Describe the Bug__

```
[/home/falko/git/bpmn-miwg-demos/2020-06-omg-technical-meeting-boston/discussion/parent-process.bpmn] unparsable content <import> detected
	line: 4
	column: 2
	nested error: unrecognized element <import> [ warning ]
```

__Steps to Reproduce__

1. Open a BPMN model with an import element, e.g. https://github.com/bpmn-miwg/bpmn-miwg-demos/blob/master/2020-06-omg-technical-meeting-boston/discussion/parent-process.bpmn
2. See log

__Expected Behavior__

At least no warning should appear because it is a valid BPMN element.

__Environment__

 - OS: Ubuntu 18.04.3 LTS
 - Camunda Modeler Version: 3.1.2

**Comment by falko** [comment]
This issue was discovered during the preparation of the 2020 BPMN MIWG demo.

**Comment by philippfromme** [comment]
The `import` element is the only one missing the prefix. Adding the prefix fixes the issue.

**Comment by falko** [comment]
Oops. Thank you for the hint. It looks like I shouldn't be handcrafting BPMN XML in the middle of the night ;-)
