### ISSUE TITLE
Notarize and re-publish Camunda Modeler

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1587]
__Is your feature request related to a problem? Please describe.__

On MacOS Catalina, any app's version from 3.1.1 can't be run without right-click open.

__Describe the solution you'd like__

Notarize and re-publish some/all of the broken versions.

__Describe alternatives you've considered__

Leave it as it is and support MacOS Catalina from 3.5.0 on.

**Comment by nikku** [comment]
I'd say: Leave things as is.

**Comment by nikku** [comment]
We'll act on this once we get the respective user feedback.
