### ISSUE TITLE
BPMN Group is not being colored

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1598]
__Describe the Bug__

BPMN groups ignore the color that is assigned to them:

![image](https://user-images.githubusercontent.com/58601/69525657-e3bc3800-0f68-11ea-8bc9-7bddc762366f.png)

__Steps to Reproduce__

* Open [test diagram](https://github.com/camunda/camunda-modeler/files/3885569/test.bpmn.txt)
* Select all elements
* Color elements (any color)
* __Group keeps black color__

__Expected Behavior__

* [ ] Group adapts border color, as specified.

__Environment__

 - OS: Any
 - Camunda Modeler Version: v3.4.1, v3.5 (also Zeebe Modeler v0.8.0)

**Comment by pinussilvestrus** [comment]
We simply not setting the stroke color in [`BpmnRenderer`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/draw/BpmnRenderer.js#L1590)

Should be easy to fix by `getStrokeColor(element, defaultStrokeColor)`

**Comment by nikku** [comment]
That was indeed it: 

![image](https://user-images.githubusercontent.com/58601/69546879-d9b02e80-0f94-11ea-854d-4a92500c5e07.png)


Fix incoming via https://github.com/bpmn-io/bpmn-js/pull/1246.

**Comment by pinussilvestrus** [comment]
Closed via b9b5bdc176e62f885474433ac0f9e8b32d9707c4
