### ISSUE TITLE
Hover feedback not cleaned up when connecting to participant

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1599]
__Describe the Bug__

When I connect a message flow to a participant with lanes I can see that the target element drop feedback (green background) is not being cleaned up:

![capture ojIdvl_optimized](https://user-images.githubusercontent.com/58601/69526634-ee77cc80-0f6a-11ea-8341-b606152d748b.gif)

__Steps to Reproduce__

1. Open [test diagram](https://github.com/camunda/camunda-modeler/files/3885649/test.bpmn.txt)
1. Connect upper participant to lower participant with lanes
1. __See that drop feedback stays.__ (Has to be cleaned up via re-connect)

__Expected Behavior__

* [ ] Drop feedback is cleaned up on create end

__Environment__

 - OS: Any
 - Camunda Modeler Version: v3.5.0-dev

Works in Camunda Modeler v3.4.0.

**Comment by nikku** [comment]
This seems to be a general issue with any participant containing lanes:

![capture zGLUtQ_optimized](https://user-images.githubusercontent.com/58601/69527332-5a0e6980-0f6c-11ea-9d4e-4084b5fd505f.gif)

**Comment by barmac** [comment]
This seems to be a problem within `FixHoverBehavior` where the hover target is changed to a Participant, but the preview marker is still removed from the Lane.

**Comment by nikku** [comment]
Yea.

I guess the reconnect refactoring removed a hack / quirky behavior of leaking `hover` into the context. Without that hack we must re-compute hover on every change. [This PR](https://github.com/bpmn-io/bpmn-js/pull/new/correct-fix-hover) sketches a solution. You'd need to validate if it goes into the right direction :wink:.

**Comment by barmac** [comment]
Oh, thanks!

**Comment by pinussilvestrus** [comment]
Closed via b9b5bdc176e62f885474433ac0f9e8b32d9707c4
