### ISSUE TITLE
DRD element connection docking cannot be updated

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1601]
__Describe the Bug__

After I've connected two DRD elements I cannot update the docking of connecting lines. This makes the feel super buggy: 

![capture rS78zz_optimized](https://user-images.githubusercontent.com/58601/69528809-444e7380-0f6f-11ea-959c-4e779796a710.gif)

__Steps to Reproduce__

1. Open [test diagram](https://github.com/camunda/camunda-modeler/files/3885872/test.dmn.txt)
2. Connect input or knowledge source with decision
3. Try to update connection docking
4. __See that connection docking always jumps back__

__Expected Behavior__

* I can update the connection docking as I am used to (works in Camunda Modeler v3.4.1)

__Environment__

 - OS: Any
 - Camunda Modeler Version: v3.5.0-dev

This is a regression from v3.4.1.

**Comment by philippfromme** [comment]
Oh snap, I think I introduced that by not reconnecting if source and target haven't changed.

**Comment by nikku** [comment]
Yes, this seems indeed like it affects BPMN, too: 

![capture m5NXL0_optimized](https://user-images.githubusercontent.com/58601/69530433-4e25a600-0f72-11ea-9e26-86dbfd115a63.gif)

**Comment by philippfromme** [comment]
Yes, in that case, we should revert the change.

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/62a50b18ab2132c5e1aaba1bb817eb0102dceda4
