### ISSUE TITLE
DRD connection preview does not reflect actual result

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1602]
__Describe the Bug__

As a user I'd expect that the connect preview equals the final result after I've commited the re-connect operation. This is not what is happening in `v3.5.0-dev` though. We seem to show the correct previews but create / reconnect a different type: 

![capture 1OeyPl_optimized](https://user-images.githubusercontent.com/58601/69529438-9348d880-0f70-11ea-809a-974cab7b205b.gif)

__Steps to Reproduce__

1. Create input source -> decision connection
2. Reconnect connection to knowledge source (or any other different element)
3. See that preview shows connection type change
4. __Drop yields original connection type__

__Expected Behavior__

* Preview matches actual created connection.

__Environment__

 - OS: Any
 - Camunda Modeler Version: 3.5.0-dev

This seems to work more reliably in Camunda Modeler v3.4.1.

**Comment by philippfromme** [comment]
Hint: Connection is not replaced on reconnect. I'll fix this.

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/62a50b18ab2132c5e1aaba1bb817eb0102dceda4
