### ISSUE TITLE
DRD append does not work anymore

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1604]
__Describe the Bug__

Append from context pad does not work anymore, it worked in Camunda Modeler v3.4.1:

![capture eRFlsF_optimized](https://user-images.githubusercontent.com/58601/69533976-33a2fb00-0f79-11ea-8561-4a07419574aa.gif)

__Steps to Reproduce__

1. Model any element
2. Try to append from context pad
3. __Element is created but connection is not__

__Expected Behavior__

Append creates element _and_ connection.

__Environment__

 - OS: Any
 - Camunda Modeler Version: 3.5.0-dev

This worked in Camunda Modeler v3.4.1.

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/62a50b18ab2132c5e1aaba1bb817eb0102dceda4
