### ISSUE TITLE
Selections with connections cannot be moved anymore

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1605]
__Describe the Bug__

The editor disallows moving elements _and_ their connections. This worked in Camunda Modeler v3.4.1:

![capture JHLNG2_optimized](https://user-images.githubusercontent.com/58601/69534437-16baf780-0f7a-11ea-890f-67e4719c2ea2.gif)

__Steps to Reproduce__

1. Open [test diagram](https://github.com/camunda/camunda-modeler/files/3886218/test.dmn.txt)
2. Try to move any combination of (source, target, connecting connection)
3. __Move is rejected__

__Expected Behavior__

* Connections can be moved with their source / target

__Environment__

 - OS: Any
 - Camunda Modeler Version: v3.5.0-dev

This is a regression from v3.4.1.

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/62a50b18ab2132c5e1aaba1bb817eb0102dceda4
