### ISSUE TITLE
Reconnecting DRD connections results in original=[Object] elements serialized in XML

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1606]
__Describe the Bug__

When reconnecting DRD elements invalid XML (an unknown `original` property) is exported:

```xml
    <extensionElements>
      <biodi:bounds x="258" y="241" width="180" height="80" />
      <biodi:edge source="Decision_0lytqu5">
        <biodi:waypoints x="398" y="160" original="[object Object]" />
        <biodi:waypoints x="338" y="241" original="[object Object]" />
      </biodi:edge>
    </extensionElements>
```

__Steps to Reproduce__

1. Open [test diagram](https://github.com/camunda/camunda-modeler/files/3886281/test_2.dmn.txt)
2. Reconnect from B -> C
3. See that `original=[object Object]"` is serialized in XML

__Expected Behavior__

Editing the diagram _always_ exports valid XML.

__Environment__

 - OS: Any
 - Camunda Modeler Version: v3.5.0-dev

This is a regression / not an issue in Camunda Modeler v3.4.1.

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/62a50b18ab2132c5e1aaba1bb817eb0102dceda4
