### ISSUE TITLE
Camunda RUN: Support Camunda Spring Boot starter based setups

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1610]
__Is your feature request related to a problem? Please describe.__

Camunda Spring Boot starter based dev flows result in slightly different URLs for REST API endpoints and app context path. Right now in our run prototype we blindly assume that users use the Tomcat distribution. That results in 404 when following the "open instance link".

The different path(s) for Spring Boot Starter / Tomcat distributions are shown below:

| Type | REST endpoint | Apps Root |
| :--- | :--- | :--- |
|  Tomcat Distribution | `http://localhost:8080/engine-rest` | `http://localhost:8080/camunda/app(/cockpit)` |
|  Spring Boot Starter | `http://localhost:8080/rest` | `http://localhost:8080/app(/cockpit)` |

__Describe the solution you'd like__

We do not blindly assume we're targeting the Tomcat distribution when linking into the apps. If the user uses a localhost URL, we should test for both /engine-rest and /rest endpoints and if we detect one of them use that as the default value of the endpoint input field. 

Since we promote Spring Boot more, we should test first /rest to make this scenario faster.

This base url pattern should be re-used for the link to Cockpit: if it is /rest then use /app/cockpit, but if it is /engine-rest then use /camunda/app/cockpit.

In case the customer uses a different configuration for the app or rest endpoints, then we don't support this case for now. We might consider adding it later once we offer multiple endpoint configurations.

Since the endpoint configuration can only be changed in the deploy dialog, the "Start process instance with new configuration" menu entry should always open the deploy dialog (step 1 of 2) and not the run dialog (step 2 of 2).

__Describe alternatives you've considered__

* Make the apps root configurable and only link to the webapps, if configured.

__Additional context__

* Both REST API (with the default URL documented above) _and_ the webapps are optional for the Spring Boot Starter based getting started experiences.
* Users can freely configure the context root of REST API and webapps using the Spring Boot Starter
* A new executable version of Camunda (REST + Engine + Webapps) is in the works that can be configured by the user to a certain extend (cf. [CAM-10062](https://jira.camunda.com/browse/CAM-10062)).

---

Related to https://github.com/camunda/camunda-modeler/issues/1552

**Comment by ingorichtsmeier** [comment]
The default behavior is confusing for our default java developer training approach as we use spring boot here. 

I vote for using the base url that I've configured for deployment before. And fix this quickly.

Thank you, Ingo
