### ISSUE TITLE
Connection layout for loops breaks on paste

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1611]
__Describe the Bug__

In certain situations pasting breaks the connection layout for loops. This results in expensive re-layouting being necessary on the users side: 

![capture 6XcoOg_optimized](https://user-images.githubusercontent.com/58601/69731355-0ba6c980-112a-11ea-96a1-38b10e5121ad.gif)

__Steps to Reproduce__

1. Open [test diagram](https://github.com/camunda/camunda-modeler/files/3897214/test.bpmn.txt)
2. Copy everything
3. Paste
4. __See that pasting sometimes breaks the layout__

__Expected Behavior__

* Pasting does never trigger a re-layout under the hood.

__Environment__

 - OS: Any
 - Camunda Modeler Version: v3.4.1, v3.5.0

**Comment by pinussilvestrus** [comment]
Was able to reproduce this in older Camunda Modeler versions as well

* 3.3.0
* 3.0.1
* 2.0.4

**Comment by nikku** [comment]
This may be fixed with bpmn-js@master, as I've recently fixed https://github.com/bpmn-io/bpmn-js/commit/d769e6ddb0cb2dc8befb2e7b31682925089ba8f1.

**Comment by nikku** [comment]
You could investigate this.

**Comment by pinussilvestrus** [comment]
Thanks for the update! I'll check it.

**Comment by pinussilvestrus** [comment]
![Kapture 2019-12-10 at 15 58 28](https://user-images.githubusercontent.com/9433996/70540676-f4be9900-1b65-11ea-8778-8d10000aa9a1.gif)

Unfortunately, it's not fixed ... Already tried to find out where the re-layouting comes from, no clue so far.

**Comment by pinussilvestrus** [comment]
After debugging the error I found out that the `waypoints` got broken in the [`CroppingConnectionDocking`](https://github.com/bpmn-io/diagram-js/blob/develop/lib/layout/CroppingConnectionDocking.js#L35)

Before: `connection.waypoints`

```js
[
 { x: 459, y: 85 },
 { x: 459, y: 105 },
 { x: 369, y: 105 },
 { x: 369, y: 45 },
 { x: 409, y: 45 }
]
```

After: `croppedWaypoints`

```js
[
 { original: { x: 459, y: 85 }, x: 459, y: 85 },
 { x: 459, y: 105 },
 { x: 369, y: 105 },
 { x: 366, y: 45 },
 { original: { x: 409, y: 45 }, x: 459, y: 85 }
]
```

I'll check whether we can do something against it.

**Comment by pinussilvestrus** [comment]
We found out that our `path-intersection` algorithm only returns _one_ intersection point in some specific cases, even the target waypoint is _exactly_ on the shape path. That's why we accidentally crop the _target_ and _source_ waypoint to the same point.

**Comment by nikku** [comment]
So this is an instance of path intersection being broken. May be related to https://github.com/bpmn-io/path-intersection/issues/6 then.

In this case I propose that we park this issue for now (and do not workaround the bug in our tools). We could check in the future whether we can contribute to path-intersection becoming an even better intersection detector.

**Comment by pinussilvestrus** [comment]
I decided together with @philippfromme that we're going to prevent cropping on pasting (cf. [`BpmnUpdater`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/BpmnUpdater.js#L52) as a valid solution for now, since it's unlikely that it will break anything / we have to crop pasted connections.

Additionally, I'll add a failing test case on `path-intersection` lib / bug ticket so that we're aware of it.
