### ISSUE TITLE
Wrong snap lines are shown on paste

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1612]
__Describe the Bug__

When multi-element pasting wrong/confusing snap lines are shown to the user:

![capture nLAPKq_optimized](https://user-images.githubusercontent.com/58601/69731753-b8814680-112a-11ea-83c7-ed56f8e1c7c9.gif)

__Steps to Reproduce__

1. Open [test diagram](https://github.com/camunda/camunda-modeler/files/3897236/test.bpmn.txt)
2. Copy all elements
3. Start two-step pasting
4. See snap lines being shown relative to coordinate origin _?_ under certain circumstances

__Expected Behavior__

Snap lines are not shown at all _or_ show next to the diagram.

__Environment__

 - OS: Any
 - Camunda Modeler Version: v3.4.1, v3.5.0

**Comment by philippfromme** [comment]
Oh no. 😢

**Comment by nikku** [comment]
I thought we fixed this one but apparently we did not.

**Comment by oguzeroglu** [comment]
By having a first look, the problem seems to be that we make a calculation error when setting snap origins for connections inside BpmnCreateMoveSnapping.

In the buggy example file:

An origin point set for the connection -> (-428, -221)
An origin point set for the shape mid point -> (20, -10)

**Comment by oguzeroglu** [comment]
I think the solution is to do the same thing that CreateMoveSnapping in diagram-js does, which is to substract the event coordinates from the actual coordinates only if we are moving the shape but not creating it. The solution should be applied to [here](https://github.com/bpmn-io/bpmn-js/blob/477217c891892b88d2bb656ebca2011303ea5126/lib/features/snapping/BpmnCreateMoveSnapping.js#L78).
