### ISSUE TITLE
Open Replace Menu after create shortcut is broken

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1613]
__Describe the Bug__

Pressing the `CTRL / CMD` shortcut allows power users to open the new elements replace menu right after element creation. This seems to be broken since the introduction of multi-element create:

![capture TxkccF_optimized](https://user-images.githubusercontent.com/58601/69733657-fb90e900-112d-11ea-8f23-4eb7d37301ca.gif)

__Steps to Reproduce__

1. Open [test diagram](https://github.com/camunda/camunda-modeler/files/3897236/test.bpmn.txt)
2. Create element from the palette by pressing the `CTRL/CMD` modifier _or_ copy and paste elements pressing `CTRL/CMD` modifier
3. See that the replace menu opens in an odd location

__Expected Behavior__

* Replace menu does not open when multi-element creating (what should be the target element?)
* Replace menu opens in the correct location after creation when creating a single element

__Environment__

 - OS: Any
 - Camunda Modeler Version: v3.4.1, v3.5.0

**Comment by pinussilvestrus** [comment]
Was able to reproduce it while _pasting_ but via _palette creation_. However, I'll have a look.

![image](https://user-images.githubusercontent.com/9433996/70523087-8d432200-1b42-11ea-9698-a2eaff2f937d.png)

**Comment by pinussilvestrus** [comment]
@oguzeroglu @barmac @philippfromme is anybody able to reproduce the first case?

> Create element from the palette by pressing the CTRL/CMD

**Comment by barmac** [comment]
I cannot reproduce it for creation from palette. For Sub Process it activates the Start Event.

**Comment by oguzeroglu** [comment]
I can reproduce it with palette creation on a clean master branch:

![Kapture 2019-12-10 at 14 40 07](https://user-images.githubusercontent.com/15003836/70534294-09496400-1b5b-11ea-99c7-36a645e5b7b1.gif)

**Comment by pinussilvestrus** [comment]
What's broken there? The position of the replace menu?

**Comment by oguzeroglu** [comment]
Yes, this is the original position (does not overlap with the intermediate event):

<img width="653" alt="Screenshot 2019-12-10 at 14 41 59" src="https://user-images.githubusercontent.com/15003836/70534393-49104b80-1b5b-11ea-974c-28991d6d513e.png">

Not sure if this is the mentioned bug though.

**Comment by pinussilvestrus** [comment]
![Uploading Kapture 2019-12-10 at 14.46.23.gif…]()

**Comment by pinussilvestrus** [comment]
The issue that it's overlapping the element is also available in previous versions (e.g. `v3.3`).

![Kapture 2019-12-10 at 14 46 23](https://user-images.githubusercontent.com/9433996/70534753-fd11d680-1b5b-11ea-853f-4904f53e56f2.gif)

I think it's a general problem with the layouting. This issue was more about the fact the replace menu is rendered in an unusable manner in the upper left corner.
