### ISSUE TITLE
Deployment Error If No Open Diagram

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1614]
![deployment-bug](https://user-images.githubusercontent.com/7633572/69736839-9213d900-1133-11ea-980f-affd001b48c7.gif)

__Steps to Reproduce__

1. Open Camunda Modeler
2. Open Deployment

__Expected Behavior__

The deployment button shouldn't be present when there is no open tab.

__Environment__

 - OS: Windows 10
 - Camunda Modeler Version: 3.5.0

**Comment by pinussilvestrus** [comment]
Closed via #1615
