### ISSUE TITLE
File -> New File opens two tabs at once

### ISSUE THREAD

**Issue by benjschneider** [camunda/camunda-modeler#1620]
__Describe the Bug__

If a tab is already open and I choose to add another diagram via `File -> New File`, the editor opens two tabs at once. Expected behaviour would be just one new tab.

__Steps to Reproduce__

1. Have a tab open in Modeler
2. Select `File -> New File`and choose any diagram type
3. Two new tabs appear

__Expected Behavior__

Only one new tab opens.

__Environment__

- OS: MacOS 10.14.6
- Camunda Modeler Version: 3.5.0.4749

**Comment by nikku** [comment]
Thanks for your report.

I cannot reproduce this on Linux so it looks like this may be a MacOS specific issue.

**Comment by nikku** [comment]
@barmac Can you have a look?

**Comment by barmac** [comment]
I cannot reproduce it on MacOS, sorry.

**Comment by pinussilvestrus** [comment]
@benjschneider can you provide any more details which might help us to reproduce your problem? Or did you find out yourself what went wrong?

**Comment by philippfromme** [comment]
Cannot reproduce on Windows either.

**Comment by barmac** [comment]
I discussed this issue with @benjschneider today and he told me that he couldn't reproduce it afterwards. I am closing this.
