### ISSUE TITLE
Properties panel is empty for all DMN connections

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1621]
<img width="988" alt="Screenshot 2019-12-02 at 14 21 07" src="https://user-images.githubusercontent.com/28307541/69963080-ba268200-150f-11ea-93c8-91604c7aa084.png">

__Describe the Bug__

I can't view or change the connections' properties in the DMN table.

__Steps to Reproduce__

1. Create a connection in a DMN tab
2. Select connection

__Expected Behavior__

At least the ID is visible.

__Environment__

- OS: MacOS 10.14
- Camunda Modeler Version: `3.4.1`, `3.5.0`

**Comment by nikku** [comment]
Is this a regression? Did it work in `v3.4.x`?

**Comment by barmac** [comment]
Same in `3.4.1`.

**Comment by nikku** [comment]
Thanks.

**Comment by nikku** [comment]
In some places this is intentional behavior. In DMN 1.1 a lot of connections do not contain IDs. This changes with DMN 1.2 / 1.3.

**Comment by barmac** [comment]
> I believe this is intentional behavior.
> 
> In DMN 1.1 a lot of connections do not contain IDs. Actually they do not contain anything _editable_. This changes with DMN 1.2 / 1.3.

Right, the requirements don't have ID in the XML too.

**Comment by barmac** [comment]
Fixed via https://github.com/camunda/camunda-modeler/pull/1688
