### ISSUE TITLE
Illegal IDs may be entered via properties panel

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1623]
__Describe the Bug__

Starting with `v3.2.0` we enforce that XML IDs generated by the application are valid QNames. as https://github.com/camunda/camunda-modeler/issues/1622 indicates users are still able to input now illegal IDs, i.e. `${FOO}`. Saving the diagram and re-opening it in the modeler fails the import.

__Steps to Reproduce__

1. open process
2. using our properties panel controls change any ID to `${FOO}`
3. save diagram
4. re-open diagram
5. __see that import blows up__

__Expected Behavior__

* Valid IDs are enforced in all property panel controls that allow users to edit IDs
* Illegal IDs may not be saved by the user

__Environment__

- OS: Any
- Camunda Modeler Version: v3.2.0, ..., v3.5.0

----

__Tasks__

* [ ] Fixed in properties panels
* [ ] Released fixes
* [ ] Integrated in Camunda Modeler

**Comment by oguzeroglu** [comment]
> Valid IDs are enforced in all places where we allow users to edit IDs

Does this concern the XML edit as well @nikku ?

**Comment by nikku** [comment]
You mean the XML editor? No. If people enter invalid IDs into the XML view the problem will be caught on import and properly indicated.

Adding validation on the XML view would be another related feature request.

**Comment by oguzeroglu** [comment]
For reference: The problem seems to be [here](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/67f93aab8b54823fa12134b3e1ce2563108e49bd/lib/Utils.js#L203) as after this operation ${FOO} becomes FOO so it passes the QNames regex test.

**Comment by nikku** [comment]
Yes. This was intentional in the past but is not desired anymore.

**Comment by nikku** [comment]
Needs release of fixes in all libraries and integration into Camunda Modeler.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/f906e142f77c616f60435bf6b7e0a9abaedc9b05.
