### ISSUE TITLE
It should be possible to configure userData directory via flag

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1625]
__Is your feature request related to a problem? Please describe.__

Currently, we use the default `userData` directory for each operating system as our [search-paths](https://github.com/camunda/camunda-modeler/tree/develop/docs/search-paths). This is not giving us the flexibility to offer custom directories, e.g. to use the app in integration testing with plugins. With the option to edit the `userData` path it would be possible to start Camunda Modeler instances without depending on the user's configuration and with a cleared setup.

__Describe the solution you'd like__

It should be possible to configure the `userData` path via flag, e.g. `--user-path='any/foo/path'`

__Describe alternatives you've considered__

/

__Additional context__

* [`electron#setPath`](https://github.com/electron/electron/blob/master/docs/api/app.md#appsetpathname-path)

**Comment by nikku** [comment]
Assuming this is an easy pick, let's build this so we can start to use it.

**Comment by oguzeroglu** [comment]
Closed via #1626
