### ISSUE TITLE
Unclear error message when importing unsupported DMN table

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda-modeler#163]
Import this DMN table that has no input:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/DMN/20151101/dmn11.xsd" id="definitions" name="definitions" namespace="http://camunda.org/schema/1.0/dmn">
  <decision id="decision" name="">
    <decisionTable id="decisionTable">
      <output id="output1" label="Result" name="result" typeRef="string" />
      <rule id="row-624115199-1">
        <outputEntry id="LiteralExpression_090256m">        <text></text>
</outputEntry>
      </rule>
    </decisionTable>
  </decision>
</definitions>
```

Having no inputs is valid DMN XML but unsupported by the modeler as far as I know. The error message is

![screenshot](https://cloud.githubusercontent.com/assets/586648/13315040/b6bc396a-dba8-11e5-85cf-3c5437d34966.png)

Should probably say explicitly that this is not supported instead of a cryptic error.

**Comment by nikku** [comment]
What is not supported about this diagram? Old DMN version?

**Comment by nikku** [comment]
Aaah, did not read your comment on the inputs. I agree dmn-js should be forgiving about that and support tables without inputs.

**Comment by nikku** [comment]
Needs fix via bpmn-io/dmn-js#38.

**Comment by ThorbenLindhauer** [comment]
Either that or a better error. From what I've heard, it was a deliberate decision to not support no-input models.

**Comment by nikku** [comment]
Either way, needs discussion in [dmn-js](https://github.com/bpmn-io/dmn-js).

**Comment by nikku** [comment]
Fixed with recent version of the Camunda Modeler.

We now support decision tables without inputs.
