### ISSUE TITLE
IntermediateThrowEvent instead of BoundaryEvent 

### ISSUE THREAD

**Issue by burjandedes** [camunda/camunda-modeler#1631]
__Describe the Bug__

Hello,

When I place a Boundary Event to a Task, the Camunda Modeler puts an IntermediateThrowEvent.
In the previous Camunda Modeler versions (e.g., 3.2.3, 3.3.1, 3.3.4), we didn't have this error. (Please see the pictures below).

![image](https://user-images.githubusercontent.com/1625558/70706277-e5f6f400-1cd5-11ea-8ab4-8d580ab427cf.png)

![image](https://user-images.githubusercontent.com/1625558/70706305-f0b18900-1cd5-11ea-8ae3-a8f14ebeb278.png)

__Steps to Reproduce__

1. Add a task to the canvas
2. Place a boundary event to the task

__Expected Behavior__

I think it should place a Boundary Event instead of an Intermediate Throw Event, just like in the previous versions, because with this anomaly, the process crashes. (Please see the pictures below).

![image](https://user-images.githubusercontent.com/1625558/70706774-eb087300-1cd6-11ea-9d3d-ee18716f7b1f.png)

![image](https://user-images.githubusercontent.com/1625558/70706783-f0fe5400-1cd6-11ea-856f-289bc0307d87.png)

__Environment__

- OS: MacOS 10.15.1, Windows 10
- Camunda Modeler Version: 3.4.1, 3.5.0

**Comment by nikku** [comment]
I could reproduce the behavior in a sense that a boundary event created on a task has an _ID_ of the form `IntermediateThrowEvent_{....}`. 

If you look into the BPMN 2.0 XML you'll see, however, that the element is an actual _boundary event_:

```xml
  <bpmn:process id="Process_0ue1lm0" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1" />
    <bpmn:task id="Task_16qu7zi">
      <bpmn:outgoing>SequenceFlow_1nsuwxx</bpmn:outgoing>
    </bpmn:task>
    <bpmn:boundaryEvent id="IntermediateThrowEvent_08k0r20" attachedToRef="Task_16qu7zi" />
    <bpmn:task id="Task_01ge13y">
      <bpmn:incoming>SequenceFlow_1nsuwxx</bpmn:incoming>
    </bpmn:task>
    <bpmn:sequenceFlow id="SequenceFlow_1nsuwxx" sourceRef="Task_16qu7zi" targetRef="Task_01ge13y" />
    <bpmn:boundaryEvent id="IntermediateThrowEvent_1br4sbq" attachedToRef="Task_01ge13y" />
  </bpmn:process>
```

**Comment by nikku** [comment]
I agree that this is confusing. We will have a look.

**Comment by burjandedes** [comment]
Thank you very much for your answer. I had an error in my BPMN model, and I thought that this was the root cause of it, but as turned out, something else caused the problem.
