### ISSUE TITLE
Invoice Example: Association between DataStoreReference and UserTask disappears on save

### ISSUE THREAD

**Issue by mboskamp** [camunda/camunda-modeler#1635]
__Association between DataStoreReference and UserTask disappears__

In the invoice example of the BPM platform project, there is a BPMN model containing a DataStoreReference that is associated with a UserTask. (It is not possible to model this association via the modeler GUI btw) The association is removed when saving the model and can only be replaced manually with a DataInputAssociation.

The invoice example will use the DataInputAssociation in the future, but I still think this should not happen with models using the simple Association.

Unfortunately, since the environment to reproduce this issue is very instable (i.e. saving or switching to XML view already triggers the issue) and the simple Association can not be added with the modeler GUI, I can not provide a minimal example. The issue is easy to reproduce with the invoice example model, though.

__Steps to Reproduce__

1. Open the model ([from the platform repo](https://github.com/camunda/camunda-bpm-platform/blob/30d65cecd05de89b9ad40084d0f689cc3398e7ba/examples/invoice/src/main/resources/invoice.v1.bpmn))
2. change something
3. save the model
4. the association has disappeared

__Expected Behavior__

* The Association does not disappear when changes are saved

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 3.5.0

**Comment by nikku** [comment]
Minimal test case: [test.bpmn.txt](https://github.com/camunda/camunda-modeler/files/3968053/test.bpmn.txt)

**Comment by nikku** [comment]
The problem / underlying bug is that we do not allow associations in that place anymore. That in term leads to the association being removed.

**Comment by nikku** [comment]
I imagine this diagram is a couple of years old?

**Comment by nikku** [comment]
Do you guys mind changing it?

**Comment by mboskamp** [comment]
The current state is two years old. I already changed it to use a DataInputAssociation instead.
