### ISSUE TITLE
Message referenced via Receive Task not copied across between diagrams

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1637]
__Reproduce__

1. Create a Receive Task and add a message
2. Copy element to a new diagram

__Observed Behavior__

* The Message definition is not copied to other diagram

__Expected Behavior__

* [x] Message definition gets copied to other diagram

__Environment__

Camunda Modeler `v3.5`
OS: Any

---

Related to https://github.com/camunda/camunda-modeler/issues/1049

**Comment by pinussilvestrus** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js/pull/1272
