### ISSUE TITLE
Message/Signal/Escalation/etc. objects are referenced by two or more diagrams at the same time after copy-paste

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1639]
__Describe the Bug__

When I copy and paste a Message Event which references a Message to another diagram, I can change the Message definition for both diagrams at the same time.

__Steps to Reproduce__

1. Create a Message Event with a Message
2. Copy and paste the event to another diagram
3. Change name of the Message
4. Notice that it's changed accordingly in the second diagram.

__Expected Behavior__

New JS object should be created.

__Environment__

- OS: any
- Camunda Modeler Version: `develop`

**Comment by pinussilvestrus** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js/pull/1271
