### ISSUE TITLE
Release Camunda Modeler 0.5

### ISSUE THREAD

**Issue by gimbel** [camunda/camunda-modeler#164]
* [x] make sure dependencies are released (`rm -rf node_modules && npm i && grunt` works)
* [x] integration test running app via [`INTEGRATION_TEST.md`](https://github.com/camunda/camunda-modeler/blob/next/docs/INTEGRATION_TEST.md)
* [x] semantic release (`grunt release {minor|major|patch}`)
* [x] wait for CI infrastructure to build the release
* [x] integration test [released artifacts](https://camunda.org/release/camunda-modeler/) once built
* [x] write blog post
* [ ] spread the word

**Comment by nikku** [comment]
@pedesen  Please checkout and merge camunda/blog.camunda.org#9.
