### ISSUE TITLE
Replace deprecated gconf with gsettings/dconf

### ISSUE THREAD

**Issue by simonsilvalauinger** [camunda/camunda-modeler#1647]
__Is your feature request related to a problem? Please describe.__
Since gconf is deprecated with GNOME 3 in 2011, the Camunda Modeler should use the successor configuration system gsettings instead. Modern linux distribution i.e. arch, don't have gconf in their repository anymore.

__Describe the solution you'd like__

Replacing gconf with gsettings/dconf.

__Describe alternatives you've considered__

Removing gconf and use a custom settings file.

**Comment by nikku** [comment]
Please use our existing issue templates and provide the relevant context to your bug report.

Otherwise we cannot help you or address your issue.

**Comment by simonsilvalauinger** [comment]
@nikku Sorry, I changed it.

**Comment by nikku** [comment]
Where should `gconf` be removed?

**Comment by simonsilvalauinger** [comment]
I found out that it is just an old electron dependency, which is still installed by the aur package. I thought the modeler uses it to store its settings. So it should be no problem for other distributions. I'm reporting this at the aur package. I'm sorry for bothering, issue can be closed.
