### ISSUE TITLE
Create more generic IDs for new elements

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1654]
__Is your feature request related to a problem? Please describe.__

There are couple of reasons why our specific generated IDs confuse users: Intermediate events may become boundary events, service tasks (`ServiceTask_xxx`) may become user tasks. 

The IDs remain the same, causing confusion for our users. Just one case is described [here](https://github.com/camunda/camunda-modeler/issues/384).

__Describe the solution you'd like__

Rather than providing overspecific IDs such as `IntermediateCatchEvent_1`, provide IDs that are more generic, i.e, `Event_1`. This allows users to still recognize their semantics (this is an event rather than a gateway).

* Provide appropriate groupings based on the replace operations we allow

__Describe alternatives you've considered__

Ditch semantic IDs all together and generate generic IDs of the form `{GENERIC_PREFIX}_{RANDOM_VALUE}`.

**Comment by slizenko** [comment]
Yeah! Useful feature for us.
We are to rename manually to make XML more readable -
SequenceFlow_199ldc1 -> flow45
etc. etc.

**Comment by barmac** [comment]
Related to https://github.com/camunda/camunda-modeler/issues/1631
