### ISSUE TITLE
Allow multiple Camunda Modeler windows to be opened at the same time

### ISSUE THREAD

**Issue by TNSaturday** [camunda/camunda-modeler#1663]
Subject. As of now, I'm not aware of any way to open multiple **windows** (not to be confused with tabs)  of camunda modeler. Please, add such possibility.

**Comment by oguzeroglu** [comment]
Have you tried setting single-instance flag to false when opening the app? It should work.

**Comment by TNSaturday** [comment]
> Have you tried setting single-instance flag to false when opening the app?
Can you point me to a place, where this is done? I've got no settings in any of the menus of the editor.

**Comment by oguzeroglu** [comment]
Please refer to here: https://github.com/camunda/camunda-modeler/tree/master/docs/flags
