### ISSUE TITLE
Update DRD editing features to same level like BPMN

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1669]
__What should we do?__

* [ ] Pull in released `dmn-js@7.3` that ships with latest bpmn.io editing features (snapping, grid-snapping, alignment and distribution)
* [ ] Add alignment and distribution buttons similar to bpmn-js to allow users to organize their diagrams

__Why should we do it?__

Potential easy pick to improve DRD editing in the tool significantly.

**Comment by pinussilvestrus** [comment]
Related to https://github.com/camunda/camunda-modeler/issues/481
