### ISSUE TITLE
Focus of arrow keys changes unintuitivelly

### ISSUE THREAD

**Issue by sebwarnke** [camunda/camunda-modeler#1673]
__Describe the Bug__

When traversing through a list of element (e.g.) input parameters in properties panel by using arrow down key and reaching the end of the list the focus of the key press action changes to somewhere else. In the video below the properties panel itself is scrolled next and after that the selected symbol on the canvas is moved.

Same applies for arrow up key as well.
 
![Kapture 2020-01-28 at 9 07 55](https://user-images.githubusercontent.com/26740468/73246199-4c64a280-41ae-11ea-9f52-29d35f2e0f18.gif)

__Expected Behavior__
The arrow keys just keep their focus.

__Environment__

- OS: MacOS Catalina
- Camunda Modeler Version: 3.6.0

**Comment by pinussilvestrus** [comment]
I was able to reproduce this bug also in older versions (`v3.3`), so it's not a regression from the latest release.

**Comment by barmac** [comment]
We don't have such component in the _new_ properties panel, so this is fixed.
