### ISSUE TITLE
Empty OUTPUT cell in DMN can be confused with "-"

### ISSUE THREAD

**Issue by antonisku** [camunda/camunda-modeler#1677]
When editing a DMN table in Camunda Modeler, empty cells are marked with a hypen / minus sign. When an actual minus sign is entered in a cell, it becomes visually indistinguishable from an empty cell.

<img width="1039" alt="Screenshot 2020-01-30 at 18 27 30" src="https://user-images.githubusercontent.com/26555365/73474407-bc318380-438e-11ea-8e9a-a2ac13d45240.png">

XML for the same is:
<img width="589" alt="Screenshot 2020-01-30 at 18 32 35" src="https://user-images.githubusercontent.com/26555365/73474832-67dad380-438f-11ea-9a09-76101642f0bd.png">

On execution, the Camunda DMN engine will fail not being able to handle ${-} expression in the DMN input or output. 

---

As a possible solution:
- Change appearance of an empty cell in the Camunda Modeler to visually distinguish it from a cell with a minus sign
- Add validation in Camunda Modeler to validate if entered value can be executed by the engine
- Add validation in Camunda engine on deployment of a DMN model with invalid expression (admittedly out of scope of this repo)

**Comment by pinussilvestrus** [comment]
Thanks for reporting! We're currently re-evaluating the DMN modeling experience, which will also include the UX of decision tables. 

> Change appearance of an empty cell in the Camunda Modeler to visually distinguish it from a cell with a minus sign

Can you think about a solution how such a distinction could look like?

> * Add validation in Camunda Modeler to validate if entered value can be executed by the engine
> * Add validation in Camunda engine on deployment of a DMN model with invalid expression (admittedly out of scope of this repo)

That could be something for [`dmn-lint` ](https://github.com/bpmn-io/dmnlint) @barmac 

Your help is very appreciated!

**Comment by barmac** [comment]
<img width="975" alt="Screenshot 2020-02-05 at 10 38 58" src="https://user-images.githubusercontent.com/28307541/73829746-c4ad1280-4803-11ea-9d97-402835c1ff55.png">

How about this?

**Comment by barmac** [comment]
We could also simply leave the cells empty, as both Excel and Google Sheets do.

**Comment by nikku** [comment]
From the DMN standard perspective, what is the implication of `-` vs. empty string? Is there a relevant difference? If not I propose that e close this issue.

**Comment by antonisku** [comment]
Hi @nikku , I am not sure if I understand how this relates to the DMN standard - in my opinion this could be just a UX improvement to minimise human errors

But let me know if I am missing something

**Comment by nikku** [comment]
Thanks for the ping back. I've re-read your issue description and figured that you are explicitly talking about _outputs_ here.

In input cells, `-` has special semantics (always match). In output cells that semantic does not exist. In fact, as you mention, explicitly entering `-` won't ever evaluate.

My proposal is: Remove the `-` as a placeholder from the output cells. Outputs should always be specified.

**Comment by ingorichtsmeier** [comment]
Hi, a quote from the DMN specification: 
> If the input entry is ‘-’ (meaning irrelevant), every value of the input expression satisfies the input entry and that particular input is irrelevant in the specified rule. 

Found on page 68 of DMN 1.1 RTF v3 clean.pdf

Hope this helps, Ingo

**Comment by nikku** [comment]
With `v3.7` of the app we will ship an updated version of the decision table editor. This version won't show the `-` placeholder on outputs, thus preventing the confusion.

If you accidentally enter `-` it is your fault. Starting with `v3.7` that issue will clearly be visible in the decision table :wink:. Thanks for your input everyone!

---

![image](https://user-images.githubusercontent.com/58601/74451068-56a9c080-4e7f-11ea-9a52-b5b1e59c299b.png)
