### ISSUE TITLE
Expression language icon not shown for odd (gray background) rules

### ISSUE THREAD

**Issue by jesusherencia** [camunda/camunda-modeler#1678]
I've tested Camunda Modeler 3.5 and 3.6. I've found three issues:

__Describe the Bug__

- Expression language:
Normally when using another "expression language" different from the default one, a blue icon is shown, but for rows (odd ones) with a background color (gray) this icon is not shown.

__Environment__

- Windows 10
- Camunda Modeler Version: 3.5, 3.6

Related to https://github.com/bpmn-io/dmn-js/issues/647

**Comment by pinussilvestrus** [comment]
Hi @jesusherencia , thanks for reporting! It would be great if you could open one issue for one bug report at a time, and also use our [issue template](https://github.com/camunda/camunda-modeler/issues/new?labels=bug&template=BUG_REPORT.md) for that purpose.

**Comment by nikku** [comment]
Also, please attach a screenshot of the bug (_?_) you are reporting. This helps us to establish the relevant context.

**Comment by michaldytko** [comment]
I have created a separate issue based on the 3rd point (mouse scroll) 
-> https://github.com/camunda/camunda-modeler/issues/1687

**Comment by nikku** [comment]
@barmac Could you double check to which extend you can reproduce this issue?

**Comment by barmac** [comment]
> @barmac Could you double check to which extend you can reproduce this issue?

> Expression language:
Normally when using another "expression language" different from the default one, a blue icon is shown, but for rows (odd ones) with a background color (gray) this icon is not shown.

v3.5.0

> Vertical scroll bar not shown:
When a decision table has many rows and its height exceeds the window height the vertical scrollbar is not shown.

> Mouse scroll button not working (version 3.6):
The same problem with exceeding height but in 3.6 the mouse scroll button doesn't work.

v3.6.0

**Comment by nikku** [comment]
I've removed the scrolling bits from the description, as this is covered via https://github.com/camunda/camunda-modeler/issues/1687.

We'll look into the scrolling.

**Comment by nikku** [comment]
Closing this issue. Not sure to which extend it is still applicable in 2023.

**Comment by barmac** [comment]
In C8, we support only a single expression language. Thus, it is not possible to reproduce the issue in C8 diagrams without plugins.
