### ISSUE TITLE
DMN XML not correctly updated when changing IDs of Tables

### ISSUE THREAD

**Issue by michaldytko** [camunda/camunda-modeler#1679]
__Describe the Bug__

When changing IDs of Tables in a DMN, the relations get lost on the diagram but remain in the XML.

__Steps to Reproduce__

![SUPPORT-7040 (2)](https://user-images.githubusercontent.com/53857504/73840197-eca67100-4817-11ea-9bdb-3eb9a6d03bf8.gif)

__Expected Behavior__

When changing the IDs of an element, all relations get updated correctly.

__Environment__

- Camunda Modeler Version: all versions 
---

Related to [SUPPORT-7040](https://jira.camunda.com/browse/SUPPORT-7040)

```

**Comment by michaldytko** [comment]
This popped up in support. I linked relevant support case in issue description

**Comment by nikku** [comment]
@barmac Is there a chance that we can backport this to `dmn-js@7.x`?

**Comment by barmac** [comment]
> @barmac Is there a chance that we can backport this to `dmn-js@7.x`?

We can do that.
