### ISSUE TITLE
Application specific documentation is overridden by Modeler

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1682]
__Describe the Bug__

I have an application that serializes documentation entries with a custom `textFormat`:

```xml
    ...
    <bpmn:documentation textFormat="text/x-my-comments">AD
SAD
SAD
ASD</bpmn:documentation>
    ....
```

 This is being displayed in the Camunda Modeler and, on change, serialized again without the `textFormat` attribute.

What I would expect instead is that the Modeler only shows documentation that is well known to her, i.e. documentation entries with an empty `textFormat` attribute.

__Steps to Reproduce__

1. Open [test diagram](https://github.com/camunda/camunda-modeler/files/4169590/diagram_1.bpmn.txt)
1. inspect process documentation, see that it is shown
1. edit documentation
1. __see that documentation attribute `textFormat` is gone__

__Expected Behavior__

Two options, from my point of view:

1. We only read and display documentation entries without a `textFormat` or with `textFormat=text/plain`. Documentation entries with a `textFormat` are ignored.
2. The documentation attribute `textFormat` is not dropped on change

__Environment__

- OS: Any
- Camunda Modeler Version: v3.6.0

---

Originally reported via https://github.com/camunda/camunda-modeler-plugins/issues/20

Depends on https://github.com/bpmn-io/bpmn-js-properties-panel/pull/465

**Comment by barmac** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/465

**Comment by tiesebarrell** [comment]
Great to see this is getting picked up. Question: would it make sense for the Modeler to export its own documentation element with a custom format as well?

**Comment by nikku** [comment]
Well... the properties panel simply shows the first plain text element. How much sense does it make to mark that plain text documentation element with a non-plain text text format?

**Comment by tiesebarrell** [comment]
You have a good point there. I was just thinking about the "play nice with others", but this doesn't interfere with any other tools, come to think of it. It will only "participate" in editing the first documentation element with no special format, so that's still playing nice :)

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2246
