### ISSUE TITLE
Variables are disappeared while copying Signal Throwing Event

### ISSUE THREAD

**Issue by r-n-aliev** [camunda/camunda-modeler#1684]
__Description__

When it's necessary to **duplicate** Signal Throwing element with "copy-paste", the Variables list of the new Signal becomes empty

__Steps to Reproduce__

1. Open [test diagram](https://github.com/camunda/camunda-modeler/files/4172364/diagram_1.bpmn.txt) (create **Signal Throwing element**, with a few variables (key-value) in its tab **"Variables"**)
2. `Ctrl-C` it, and paste it to another place by `Ctrl-V`
3. Open its tab "Variables"
4. Variables list is now **empty**

__Expected Behavior__

All attributes of duplicated element are equal and Variables list is the same (by count and values)

__Environment__

- OS: Windows 7, Windows 10, macOS 10.13.6
- Camunda Modeler Version: 2.2.4, 3.4.1

---

Screenshot: 

![image](https://user-images.githubusercontent.com/58601/74055520-74d77280-49e0-11ea-9a11-56414e08221f.png)

**Comment by barmac** [comment]
I can reproduce this.

**Comment by barmac** [comment]
Will be fixed via https://github.com/camunda/camunda-bpmn-moddle/pull/54

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/1690.
