### ISSUE TITLE
Vertical scroll in DMN Table is not working

### ISSUE THREAD

**Issue by michaldytko** [camunda/camunda-modeler#1687]
__Describe the Bug__

Having a DMN Table bigger than window size it is not possible to scroll down to the lower rows.

__Steps to Reproduce__

[ScrollBug.dmn.zip](https://github.com/camunda/camunda-modeler/files/4180818/ScrollBug.dmn.zip)

1. The ScrollBug.dmn has 30 rows.
2. Try to scroll down to the last one.

__Expected Behavior__

It is possible to scroll down with the mouse to the lower rows.

__Environment__

- Camunda Modeler Version: 3.6

---

Related to [SUPPORT-7076](https://jira.camunda.com/browse/SUPPORT-7076)

**Comment by michaldytko** [comment]
This popped up in support. I linked relevant support case in issue description

**Comment by barmac** [comment]
Related to https://github.com/camunda/camunda-modeler/commit/168e605cef3b4e8c17d6cc41faeb1d76e88a7b9e

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1695.
