### ISSUE TITLE
Add build version / nightly build to distro

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#169]
* Generate proper versions for nightlies
* Allow to add build versions / nightly flag to distro build

**Comment by vladimirskatusenoks** [comment]
There is a [bug](https://github.com/gruntjs/grunt/issues/920) in the latest Grunt that relates to parsing options.

So e.g. this:
```grunt --nightly --build=12345 --app-version=0.6.8 distro:darwin```
does not set `build` option

Please, have a look on [`this comment`](https://github.com/gruntjs/grunt/issues/920#issuecomment-25484832).
