### ISSUE TITLE
[DMN] Overriding handler for `element.updateProperties`

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1697]
__Describe the Bug__

On [a branch with `dmn-js@8.0.0-alpha.1`](https://github.com/camunda/camunda-modeler/tree/dmn-1-3-experiments), I am not able to switch from DRD view to Decision Table or Literal Expression. It seems that we reuse the Command Stack object in Modeler. I could not reproduce it on bare `dmn-js`.

```
[/Users/maciej/workspace/bpmn-io/dmn-js/packages/dmn-js/test/spec/diagram.dmn] overriding handler for command <element.updateProperties>
    at o._setHandler (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:501:10)
    at _setHandler (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:268:7)
    at register (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:286:7)
    at file:///Users/maciej/workspace/bpmn-io/camunda-modeler/dist/mac/Camunda%20Modeler.app/Contents/Resources/app.asar/public/6.6.js:8:528369
    at iterator (webpack:///node_modules/min-dash/dist/index.esm.js:166:19)
    at file:///Users/maciej/workspace/bpmn-io/camunda-modeler/dist/mac/Camunda%20Modeler.app/Contents/Resources/app.asar/public/6.6.js:8:528349
    at file:///Users/maciej/workspace/bpmn-io/camunda-modeler/dist/mac/Camunda%20Modeler.app/Contents/Resources/app.asar/public/6.6.js:8:528393
    at file:///Users/maciej/workspace/bpmn-io/camunda-modeler/dist/mac/Camunda%20Modeler.app/Contents/Resources/app.asar/public/2.2.js:1:45959
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:366:33)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:351:23) [ error ]
```

__Steps to Reproduce__

1. `git checkout dmn-1-3-experiments`
2. Open DMN diagram
3. Try to switch view to Decision Table or Literal Expression

When doing (3) via Drill Down, there will be only an error in the log and nothing else. Switching via tab links crashes the tab.

__Expected Behavior__

It should work.

__Environment__

- OS: MacOS 10.15.2
- Camunda Modeler Version: [this branch](https://github.com/camunda/camunda-modeler/tree/dmn-1-3-experiments)

**Comment by nikku** [comment]
Please investigate this one further. Both editors are instantiated separaterly via `didi` and ment to be entirely independent. So any re-use is essentially a bug.

**Comment by barmac** [comment]
OK, I get it. It's a problem within `dmn-js-properties-panel`: we [register a handler](https://github.com/bpmn-io/dmn-js-properties-panel/blob/70bc931c4a570dd5e1ede42dd275ce19b38485af/lib/adapter/decision-table/DecisionTableAdapter.js#L38) which is excessive since the inconsistency has been removed.

**Comment by nikku** [comment]
Haha. So the workaround for the inconsistency broke our our neck here :see_no_evil:.

**Comment by barmac** [comment]
Exactly. I will fix that.

**Comment by barmac** [comment]
Fixed and published on [dmn-js-properties-panel](https://www.npmjs.com/package/dmn-js-properties-panel/v/0.4.0-alpha.0) as alpha.

**Comment by barmac** [comment]
Fixed via https://github.com/camunda/camunda-modeler/pull/1688
