### ISSUE TITLE
Update Modeler documentation to include DMN 1.3

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1698]
__What should we do?__

[docs.camunda.org](https://docs.camunda.org/manual/latest/) should feature DMN 1.3 where it currently features 1.1. Update strategy to be aligned with platform team.

Pages that need to be updated: 
https://docs.camunda.org/manual/latest/installation/camunda-modeler/
https://docs.camunda.org/manual/latest/modeler/
https://docs.camunda.org/manual/latest/modeler/dmn/

__Why should we do it?__

Users should be able to learn about DMN 1.3 support.

**Comment by barmac** [comment]
Ready for Camunda Modeler 4.0 release.

https://github.com/camunda/camunda-docs-manual/pull/477

**Comment by nikku** [comment]
Moving back to backlog, as we're not merging things right now.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-docs-manual/pull/477
