### ISSUE TITLE
I cannot set to the id to a former value after morphing a task

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda-modeler#170]
**Steps to reproduce:**
1) model a task
2) enter an id, e.g. "My_special_task"
3) morph the task to a service task for example (the id of the element changed)
4) try to enter again "My_special_task" as id

**Problem:**
A validation error with the message "Element must have an unique id" is shown.

**Expected behavior:**
After morphing a task, I can enter the previous id and no validation error is shown.

**Comment by nikku** [comment]
Duplicate of #97?

**Comment by gimbel** [comment]
Looks like a duplicate to me.

Shall we include that in the next camunda modeler milestone (03)?

**Comment by romansmirnov** [comment]
Yes, it is a duplicate of #97. I have not seen the other issue.
