### ISSUE TITLE
When modeler crashes, log can expand to overtake the application

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1701]
__Describe the Bug__

In case of a critical bug in the modeler, the error messages in the log make it grow so in effect the whole application is unusable.

<img width="1904" alt="Screenshot 2020-02-25 at 16 04 55" src="https://user-images.githubusercontent.com/28307541/75260124-67e0be80-57e9-11ea-8a74-a9b42c074d24.png">

__Steps to Reproduce__

1. Discover and activate a critical bug which causes `unhandled error in event listener` (easier to say than do, I know, but this can be simulated via a plugin or a known issue).
2. Notice that the log grows and hides the application controls.

__Expected Behavior__

Log should have a maximum height so that even in the case of failure you can close the tab and save your work easily.

__Environment__

- OS: MacOS 10.15.3
- Camunda Modeler Version: 3.7.0

**Comment by nikku** [comment]
For whoever picks up the issue: Could you show a path how to trigger the critical error?

**Comment by barmac** [comment]
> For whoever picks up the issue: Could you show a path how to trigger the critical error?

Currently, you can do that via https://github.com/camunda/camunda-modeler/issues/1703

However, I am not able to reproduce it although I tried a couple of times :/

**Comment by nikku** [comment]
Let's close the issue if we cannot reproduce it.

**Comment by nikku** [comment]
Regarding the critical error: If you can attach concrete steps to reproduce, I could check it out to better understand the impact.

**Comment by nikku** [comment]
When triggering https://github.com/camunda/camunda-modeler/issues/1703 I get two log entries and the log scrolls nicely, as intended:

**Comment by barmac** [comment]
Same here. I can't find a reliable way to reproduce it.
