### ISSUE TITLE
Space tool can crash diagram when used on lanes

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1703]
__Describe the Bug__

A space tool used on a lane can crash a diagram.

![space-tool](https://user-images.githubusercontent.com/28307541/75261572-8c3d9a80-57eb-11ea-8832-72287758e549.gif)

__Steps to Reproduce__

1. Create a multi-lane participant
2. Try to resize a lane with hover effect on a lower lane but with cursor over the middle one, so that it covers the middle one (cf. screencast)
3. Now this happens - diagram is unusable.

__Expected Behavior__

No crash, no effect.

__Environment__

- OS: MacOS 10.15.3
- Camunda Modeler Version: 3.7.0

Couldn't reproduce it in 3.6.0

**Comment by nikku** [comment]
I can reproduce the issue.

**Comment by barmac** [comment]
Fixed via https://github.com/bpmn-io/bpmn-js/pull/1291

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1730
