### ISSUE TITLE
Make image exporting dialog based instead of using a dropdown menu

### ISSUE THREAD

**Issue by ricardomatias** [camunda/camunda-modeler#171]
We want to refactor the way we export images to a common saving pattern seen in several editors. We'll do this as soon as electron adds the necessary infrastructure. More details in this [electron issue](https://github.com/atom/electron/issues/4634).

**Comment by philippfromme** [comment]
Using the Electron menu will always show the PNG option. There should be only one entry.

![foobar](https://user-images.githubusercontent.com/7633572/40467306-b5c21cc6-5f29-11e8-93d4-b2a4b26d9405.gif)
