### ISSUE TITLE
Change decision table default expression languages to map Camunda 7.13

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1710]
__What should we do?__

Update the default decision table expression languages so that they map [to Camunda 7.13 defaults](https://docs.camunda.org/manual/latest/update/minor/712-to-713/#new-default-expression-languages). FEEL is now essentially the default expression language, everywhere.

__Why should we do it?__

We are a tool that aligns with the engine.

**Comment by barmac** [comment]
Fixed via https://github.com/camunda/camunda-modeler/pull/1688
