### ISSUE TITLE
Nightly builds are failing

### ISSUE THREAD

**Issue by oguzeroglu** [camunda/camunda-modeler#1714]
Nightly builds are failing with this error:

> ⨯ Exit code: 1. Command failed: /root/.cache/electron-builder/winCodeSign/winCodeSign-2.5.0/linux/osslsigncode -in /project/dist/win-unpacked/Zeebe Modeler.exe -out /project/dist/win-unpacked/Zeebe Modeler-signed-sha1.exe -t http://timestamp.digicert.com -pkcs12 /tmp/t-dn32O9/1.p12 -h sha1 -n Zeebe Modeler -i https://github.com/zeebe-io/zeebe-modeler -pass 75ea1c5bf2170b304514854628a0f4fe1d5db7cb7861a0a5752721aebad32bb6 (sha256 hash) /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /root/.cache/electron-builder/winCodeSign/winCodeSign-2.5.0/linux/osslsigncode

It's possible that the OS version used in Travis machines changed so we need to update our SSL related packages accordingly.

---

Cf. [broken CI build](https://travis-ci.org/camunda/camunda-modeler/jobs/658288381).

**Comment by nikku** [comment]
The build is happening inside a docker container. So the other thing that could have changed is the docker image. I'm investigating.

**Comment by nikku** [comment]
The problem may be this one: https://github.com/electron-userland/electron-builder/releases/tag/v22.4.0

**Comment by nikku** [comment]
Issue tracked down [and fixed](https://travis-ci.org/camunda/camunda-modeler/jobs/658606472), we are back :package:!

**Comment by nikku** [comment]
Fixed via https://github.com/camunda/camunda-modeler/commit/98b7e3add90d0aba2db006f063b9a0e84b2cea59.

Ported to Zeebe Modeler via https://github.com/zeebe-io/zeebe-modeler/commit/6247d71a76d5e978ba014dbe3841c91b33b3e3cc.
