### ISSUE TITLE
Add lane below/above breaks layout

### ISSUE THREAD

**Issue by frayel** [camunda/camunda-modeler#1715]
__Describe the Bug__

When i choose the option "add lane above" or "add lane below" in a diagram with multiplex lane, the layout get broken.
I tried an old version "3.1.0" and this don't happen.

![layout](https://user-images.githubusercontent.com/3854341/75988376-3befc800-5ed0-11ea-9806-4b1b9b3f0f35.JPG)

__Steps to Reproduce__

1. Create a new diagram
2. Add three lanes
3. Create a flow
4. On the second lane, click "add lane below

![image](https://user-images.githubusercontent.com/3854341/75988357-31cdc980-5ed0-11ea-9e8b-cf2398c015d7.png)

__Expected Behavior__

The links should stay connected as below:
![image](https://user-images.githubusercontent.com/3854341/75988435-575ad300-5ed0-11ea-95db-a24558cb16d0.png)

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 3.7.0 Windows 64 bit

**Comment by nikku** [comment]
I can reproduce this issue:

![capture 9lpgXA_optimized](https://user-images.githubusercontent.com/58601/75989381-74ed6400-5ef3-11ea-95f7-6be24b5bba97.gif)

Test diagram: [`space-test.bpmn`](https://github.com/camunda/camunda-modeler/files/4293335/space-test.bpmn.txt).

**Comment by nikku** [comment]
Will be fixed with next release.

**Comment by nikku** [comment]
Can this one be closed?

**Comment by barmac** [comment]
👍
