### ISSUE TITLE
Update check once per day

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1718]
__Is your feature request related to a problem? Please describe.__

Right now, we [update check on application start only](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/update-checks/UpdateChecks.js#L79).

Most developer machines do not shut down nowadays, thus it is quite common for apps to stay open for long. With our current check, the users won't receive the update notification unless they forcefully shutdown the app (or reboot the machine).

__Describe the solution you'd like__

Update check daily.

__Describe alternatives you've considered__

Keep things as is.

__Additional context__

This is related to Volker, expecting an update check, when he did not receive one.

**Comment by oguzeroglu** [comment]
Closed by #1722.
