### ISSUE TITLE
CORS Issue on deploy

### ISSUE THREAD

**Issue by pixie79** [camunda/camunda-modeler#1723]
When trying to deploy a model using a token I get an error back saying invalid credentials. If I use the same token to deploy the same model from an older version of the Modeler to the same server then it deploys ok.
I have checked the network tab and the POST is being rejected due to a CORS issue.

Can you tell me what has changed in this regard between versions or what i need to change in our engine settings to allow me to deploy BPMN’s from the latest modeler.

Thanks :)

**Comment by nikku** [comment]
You'd need to enable CORS in the engines REST API.

The related change in the modeler that is effected by it was shipped with Camunda Modeler v3.5. We'll discuss this internally, as it is quite a limitation in the App, too. 

Maybe there is ways how we can work around this issue.

**Comment by barmac** [comment]
I tried to reproduce the issue using an AWS EC2 instance with:
* Camunda BPM 7.12 (TomCat distro) downloaded from https://camunda.com/download/, and
* Camunda BPM 7.13-alpha.2 (Camunda Run distro) downloaded from https://downloads.camunda.cloud/release/camunda-bpm/run/7.13/,

both with enabled HTTP Basic authentication and explicitly disabled CORS for the Camunda Run distro. For both distros, I was able to deploy and run instance directly from Camunda Modeler 3.7.1. I did not setup token authentication as it is not a built-in feature.

Can you please share the exact steps you took when you had the issue?

**Comment by nikku** [comment]
Closing this as it does not seem a general issue but rather an issue with a specific setup.

**Comment by ceefour** [comment]
@barmac See/vote CORS issue (and PR) here: https://jira.camunda.com/browse/CAM-11840

For Camunda Modeler & CORS see https://github.com/camunda/camunda-docs-manual/pull/549

**Comment by barmac** [comment]
Thanks for the update!
