### ISSUE TITLE
New radio buttons are not responsive

### ISSUE THREAD

**Issue by oguzeroglu** [camunda/camunda-modeler#1724]
__Describe the Bug__

As we saw in @philippfromme's laptop, the new radio buttons are not responsive for every screen resolution.

__Steps to Reproduce__

1) Open the deployment tool dialog in Philipp's computer.
2) Look at the screen 👁 

__Expected Behavior__

The radio buttons are responsive.

__Environment__

- OS: Any
- Camunda Modeler - Dev branch

**Comment by oguzeroglu** [comment]
Update: It turns out that Philipp has 1.5 zoom ratio configured in his machine which causes this behavior. Volker says we should not invest time on this until further notice.

**Comment by ingorichtsmeier** [comment]
1.5 zoom is common during trainings on low level projectors.

As this is my daily business, please find a way that I use the deployment from the modeler here.

**Comment by nikku** [comment]
I'd suggest that we spend a few more minutes to understand if this is a zoom ratio related issue or an issue how we've implemented the custom radio buttons.

@oguzeroglu Please verify with @philippfromme whether he sees the same issue with custom radios, i.e. provided by bootstrap. If not, adapt the styling techniques used in Bootstrap (with our custom style flavor baked in, of course).

**Comment by nikku** [comment]
> As this is my daily business, please find a way that I use the deployment from the modeler here.

@ingorichtsmeier The issue is a cosmetic one that won't impact your trainings.

**Comment by oguzeroglu** [comment]
It fails if px unit is used instead of rem unit. For instance in W3Schools website. In the official Bootstrap website they are implemented with rem unit. Our designs specify exact amount of px values.

**Comment by ingorichtsmeier** [comment]
OK, thank you for the clarification. 
Without screenshot it was difficult to judge.

**Comment by nikku** [comment]
Thanks for the clarification @oguzeroglu. I assume rewriting with `rem` is a lot of work we'll understandably not invest right now.
