### ISSUE TITLE
Add 'Values' to custom form fields

### ISSUE THREAD

**Issue by Ganondolf** [camunda/camunda-modeler#1727]
Currently, you can only insert camunda:value elements from the modeler as children of camunda:formField elements if the type is 'enum'. While this, in general, makes sense, I have custom types with values and I would like to be able to insert them from the modeler. A prime example would be checklists, for things I need to remind my users to do during a certain task.

Without this feature, I'm forced to either edit the xml directly or put values as properties, for example with an underscore as a prefix to distinguish them from actual properties during parsing. This is not ideal.

**Comment by nikku** [comment]
Please use the existing feature request template, provide links to relevant camunda documentation and show the produced XML.

Otherwise we cannot help you.
