### ISSUE TITLE
Remove toolkit watermarks from all editors

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1731]
__What should we do?__

Starting with `Camunda Modeler v4.0.0-alpha.1` we do not show the toolkit watermarks on all editors.

__Why should we do it?__

Alignment with other products in the Camunda stack.

__FAQ__

> Are we allowed to do it, despite the bpmn.io license telling otherwise?

Yes, as we are code owners of the bpmn.io toolkits.

**Comment by oguzeroglu** [comment]
Closed by #1733.
