### ISSUE TITLE
Less confusing process and participant ids

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#1738]
__Is your feature request related to a problem? Please describe__

For beginners it is confusing that the process id is handled in different fields depending if you modeled a process with a pool or without.

If you model a process without a pool, you have a Id and a Name to fill:
![grafik](https://user-images.githubusercontent.com/7870843/77325599-e2cdc400-6d18-11ea-8d55-d1bd6681f7ce.png)

If you model a process inside a pool, you have to fill a Process Id and a Process Name:
![grafik](https://user-images.githubusercontent.com/7870843/77325753-1c9eca80-6d19-11ea-9283-b4823553870a.png)

__Describe the solution you'd like__

Rename the labels: 

* Process Id and Process Name for the first picture.
* Participant Id, Participant Name, Process Id and Process Name for the second picture.

__Describe alternatives you've considered__

Keep it as it is.

__Additional context__

This will help beginners in trainings a lot, as it is confusing that the same process needs different fields if there is pool or not. The behaviour of the engine and the Cockpit is easier to understand.

---

Depends on https://github.com/bpmn-io/bpmn-js-properties-panel/issues/327

**Comment by volkergersabeck** [comment]
we will consider to improve this in context of property panel changes within the RPA initiative. Description of a possible solution will be added later.

**Comment by nikku** [comment]
Improved via https://github.com/bpmn-io/bpmn-js-properties-panel/issues/327.
