### ISSUE TITLE
ENGINE-09005 Could not parse BPMN process. Errors: 

### ISSUE THREAD

**Issue by kaleban86** [camunda/camunda-modeler#1744]
I just started learning camunda and trying to deploy diagram, I get this error please tell me how to fix it?

`ENGINE-09005 Could not parse BPMN process. Errors: 
* src-resolve: Cannot resolve the name 'extension' to a(n) 'element declaration' component. | resource diagram_1.bpmn | line 15 | column 70 * src-resolve: Cannot resolve the name 'rootElement' to a(n) 'element declaration' component. | resource diagram_1.bpmn | line 16 | column 72 * src-resolve: Cannot resolve the name 'bpmndi:BPMNDiagram' to a(n) 'element declaration' component. | resource diagram_1.bpmn | line 17 | column 79 * src-resolve: Cannot resolve the name 'relationship' to a(n) 'element declaration' component. | resource diagram_1.bpmn | line 18 | column 73 * cvc-complex-type.2.4.a: Invalid content was found starting with element 'bpmn:process'. One of '{"http://www.omg.org/spec/BPMN/20100524/MODEL":import}' is expected. | resource diagram_1.bpmn | line 3 | column 58 [ deploy-error ]`

**Comment by nikku** [comment]
Your diagram does not pass the BPMN validation by the engine.

As it looks like you're trying to report a bug. Please use the bug report template, provide all requested information and a diagram that allows us to reproduce the issue.

Thanks!

**Comment by nikolai-gnap** [comment]
this is the problem. why  I can't save a diagram using camunda modeler by following the link http://localhost:8080/engine-rest. I use Camunda Community standalone, I also deployed spring boot starter and I use intellij idea. When I save the same diagram to the project folder, it works.

**Comment by nikku** [comment]
Please provide _exact_ steps to reproduce the issue, including the diagram you started with.

**Comment by Namjoofar** [comment]
I have the same problem:

org.camunda.bpm.engine.ParseException: ENGINE-09005 Could not parse BPMN process. Errors: 
* src-resolve: Cannot resolve the name 'extension' to a(n) 'element declaration' component. | resource myproces/joint_account.bpmn | line 15 | column 70
* src-resolve: Cannot resolve the name 'rootElement' to a(n) 'element declaration' component. | resource myproces/joint_account.bpmn | line 16 | column 72
* src-resolve: Cannot resolve the name 'bpmndi:BPMNDiagram' to a(n) 'element declaration' component. | resource myproces/joint_account.bpmn | line 17 | column 79
* src-resolve: Cannot resolve the name 'relationship' to a(n) 'element declaration' component. | resource myproces/joint_account.bpmn | line 18 | column 73
* cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.omg.org/spec/BPMN/20100524/MODEL":process}'. One of '{"http://www.omg.org/spec/BPMN/20100524/MODEL":import}' is expected. | resource myproces/joint_account.bpmn | line 3 | column 100

**Comment by nikku** [comment]
@Namjoofar My [prior hints apply](https://github.com/camunda/camunda-modeler/issues/1744#issuecomment-605678239).

In addition, please do not [necrobump](https://www.urbandictionary.com/define.php?term=necrobump) old issues. Instead create a new one, providing _all_ necessary information, and link the old one for reference.
