### ISSUE TITLE
strings not trimmed in properties panel

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#175]
I would expect that strings are trimmed in the properties panel after saving the diagram

**Comment by nikku** [comment]
This should be a good behavior for most properties (maybe except for "documentation")?

**Comment by nikku** [comment]
Would fix https://github.com/camunda/camunda-modeler/issues/720, too.

**Comment by nikku** [comment]
We decided to not go for this but apply better validation instead (cf. #720).
