### ISSUE TITLE
Nightly versions are not updated in the Download Center

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1751]
__Describe the Bug__

When visiting the nightly build page in the [download center](https://downloads.camunda.cloud/release/camunda-modeler/nightly/), you see that the versions not got updated since 18th of March.

![image](https://user-images.githubusercontent.com/9433996/78132465-14334780-741d-11ea-8154-f224a934ba4d.png)

When downloading the version, you also see the wrong version number:

![image](https://user-images.githubusercontent.com/9433996/78132727-8c017200-741d-11ea-8de4-27a3b5533858.png)

The nightly jobs run through properly on Travis (cf. [build#669321397](https://travis-ci.org/github/camunda/camunda-modeler/builds/669321397)) and are updated in the [S3 bucket](https://camunda-modeler-nightly.s3.eu-central-1.amazonaws.com/)

__Steps to Reproduce__

1. Go to [the download center](https://downloads.camunda.cloud/release/camunda-modeler/nightly/)
2. See the wrong creation date

__Expected Behavior__

The nightly versions should be updated in the download center correctly.

__Additional Context__

* [Nightly Jenkins job](https://ci.cambpm.camunda.cloud/job/sideprojects/job/camunda-modeler-desktop-nightly/)

**Comment by nikku** [comment]
Works again, cf. [build](https://ci.cambpm.camunda.cloud/job/sideprojects/job/camunda-modeler-desktop-nightly/488/).
