### ISSUE TITLE
Paste diagram contents to open

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#176]
* Instead of opening a diagram from disk simply paste it inside the Camunda Modeler to create a new diagram tab with the given diagram contents.

This makes working with diagrams during testing AWESOME.

**Comment by vkatushenok** [comment]
Steps to achieve same behaviour:
- Copy diagram XML text
- Create new tab
- Switch to XML view (at the bottom of the tab)
- Replace content
- Switch back to Diagram view

Closing, as would, potentially, introduce more questions on copying invalid text, triggering elements paste from clipboard etc.
