### ISSUE TITLE
Tooltip implementation does not match the designs

### ISSUE THREAD

**Issue by oguzeroglu** [camunda/camunda-modeler#1761]
__Describe the Bug__

Tooltip implementation does not match the designs. See the image:

![](https://user-images.githubusercontent.com/938244/78546471-c2643600-77fd-11ea-8fa9-17d14b4edd18.png)

Related to: https://github.com/zeebe-io/zeebe-modeler/pull/194

__Steps to Reproduce__

1. Open Deployment Tool
2. Type some invalid URL
3. Hover to the warning icon

__Expected Behavior__

Tooltip implementation matches the designs.

__Environment__

- OS: N/A
- Camunda Modeler Version: N/A

**Comment by andreasgeier** [comment]
@andreasgeier

**Comment by barmac** [comment]
I guess I need this for my PR :D

**Comment by oguzeroglu** [comment]
Tip: We should probably play with .invalid-tooltip before and after pseudo elements inside _forms.less.

**Comment by barmac** [comment]
Thanks Oguz. I appreciate your tip :)

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1765
