### ISSUE TITLE
Association is gone after going to literal expression view

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1763]
__Describe the Bug__

Association is removed from the definitions after I go to literal expression view and then back to DRD.

![association-gone-3-7-1](https://user-images.githubusercontent.com/28307541/78560194-f9dedc80-7815-11ea-93f1-b3ee32f249e8.gif)

__Steps to Reproduce__

1. Create an empty decision
2. Create a text annotation linked to that decision
3. Go to literal expression view
4. Go back to DRD
5. now this happens

__Expected Behavior__

Association stays.

__Environment__

- OS: MacOS 10.15.3
- Camunda Modeler Version: both 3.7.1 and 4.0.0-alpha.1

__Additional Context__

It seems that the association is completely removed from the definitions while the DI information stays. See XML files below:

* 4.0.0-alpha.1: [alpha.dmn.txt](https://github.com/camunda/camunda-modeler/files/4438454/alpha.dmn.txt)
* 3.7.1 [stable.dmn.txt](https://github.com/camunda/camunda-modeler/files/4438455/stable.dmn.txt)

**Comment by pinussilvestrus** [comment]
This seems to be related to https://github.com/camunda/camunda-modeler/issues/1702

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/dmn-js/pull/519.
