### ISSUE TITLE
Investigate nightly build failures

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1766]
__What should we do?__

The [nightly build is currently failing](https://travis-ci.org/github/camunda/camunda-modeler/jobs/671726246) at MacOS notarization. We should investigate why:

```
Building camunda-modeler distro
---
  version: 4.0.0-nightly.20200406
  platforms: [mac]
  publish: true
---
electron-builder -c.forceCodeSigning=false --mac --publish=always -c.publish.provider=s3 -c.publish.bucket=camunda-modeler-nightly -c.artifactName=${name}-nightly-${os}-${arch}.${ext} -c.dmg.artifactName=${name}-nightly-${os}.${ext} -c.nsis.artifactName=${name}-nightly-${os}-setup.${ext} -c.nsisWeb.artifactName=${name}-nightly-${os}-web-setup.${ext}
  • electron-builder  version=22.3.2 os=18.7.0
  • loaded configuration  file=/Users/travis/build/camunda/camunda-modeler/electron-builder.json
  • packaging       platform=darwin arch=x64 electron=7.1.14 appOutDir=dist/mac
  • signing         file=dist/mac/Camunda Modeler.app identityName=Developer ID Application: Camunda Services GmbH (3JVGD57JQZ) identityHash=C16B85229F36AECB73E26C8D38BF465596DC0843 provisioningProfile=none
  • notarizing app from path: /Users/travis/build/camunda/camunda-modeler/dist/mac/Camunda Modeler.app
  ⨯ Failed to upload app to Apple's notarization servers
...
```

__Why should we do it?__

Nightlies (as well as stable releases) should be notarized.

**Comment by nikku** [comment]
Magically fixed by @barmac. Would be interested in how.

**Comment by barmac** [comment]
So I read the log carefully and found [this](https://travis-ci.org/github/camunda/camunda-modeler/jobs/671726246#L1024):
> [2020-04-06 17:46:10 GMT] <main> ERROR: You must first sign the relevant contracts online. (1048)

The next step was to go to Apple Developer dashboard and sign the contract online. With that done, the builds started to work again.
