### ISSUE TITLE
Add Split View with Viewer and Editor

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1767]
Instead of having a single view at a time, a split view allows for both a view of the DRD and the DRG element that is being edited at all times. The DRD view on the left can be used to navigate between DRG elements. The DRD itself can also be edited.

Interaction:

Split View open ➡️ Click DRG element in DRD view on the left ➡️ Open DRG element in view on the right

Split View open ➡️ Click _Edit DRD_ ➡️ Single View with DRD opens

Single View with DRD open ➡️ Click DRG element overlay ➡️ Open Split View

Prototype: https://dmn-prototypes.netlify.com/navigation-editing/

![foo](https://user-images.githubusercontent.com/7633572/78641658-db2e2380-78b1-11ea-87ba-850582a627ad.jpg)

Details:

* [x] collapsing:
  * [x] have a collapse / expand button for the DRD preview instead of (or in addition to) resize line
  * [x] "edit DRD" button always visible (also when preview is collapsed)
* [x] DRD preview:
  * [x] DRD preview at 50% scaling and with same grey background color as property panel
  * [x] add decision type icons (in grey) to DRD preview (table vs lit. expr.)
  * [x] highlighting of selected decision in DRD preview does not work correctly for all decision tables when I open them from the DRD editor
* [x] no property panel in decision table view
* [x] remove ID from decision table
* [x] hover effects:
  * [x] hover effect in DRD to show clickable elements
  * [x] remove dashed line on hover & select in DRD preview
  * [x] connectors and non-selectable nodes in the DRD preview should not have any hover effect
* [x] colors:
  * [x] selected decision table should have background fill color (light blue) in DRD preview
  * [x] selected elements in DRD editor or cells in decision tables have blue outline => highlight color in DRD preview should be the same blue instead of green
* [x] when opening a decision from DRD editor, the DRD preview should center this element / make sure the element is visible
  (but when using the DRD preview to navigate, we should not re-center to the selected element. This way, people can quickly navigate between two decisions using the DRD preview)

__Describe alternatives you've considered__

Using [diagram-js-minimap](https://github.com/bpmn-io/diagram-js-minimap) to improve navigation.

Possible follow-up issues:

* https://github.com/camunda/camunda-modeler/issues/1810

**Comment by philippfromme** [comment]
After implementing the split view and taking it for a test drive here are a few things that concern me:

* distinction between read-only DRD on the left and editor on the right is not clear
* transition between split view and editing DRD is weird, position of the diagram changes etc.
* DRD on the left means I cannot maximize table anymore

**Comment by nikku** [comment]
Some proposals how to circumvent the issue

* make the navigation panel optional, i.e. easily toggle-able via keyboard shortcut (and not-so-much space-taking UI control)

**Comment by philippfromme** [comment]
One alternative could be a modified version of the minimap that doesn't allow panning and zooming but clicking elements to open them.

The downside of using something similar to the minimap would be that the names of the elements wouldn't be readable and therefore navigation would be harder.

**Comment by philippfromme** [comment]
After further iteration this is the version we're going to build:

Overview open:

<img width="959" alt="dmn-navigation-open" src="https://user-images.githubusercontent.com/7633572/82019789-20e7c400-9688-11ea-9e93-b2451847da04.png">

Overview closed:

![dmn-navigation-closed](https://user-images.githubusercontent.com/7633572/82019830-30670d00-9688-11ea-857e-7524a0b134a2.png)

**Comment by barmac** [comment]
🎉
