### ISSUE TITLE
Where can I find some mor infos about this?

### ISSUE THREAD

**Issue by cGiesen** [camunda/camunda-modeler#1770]
I test it in my enviroment and didn't see a usefull result?!

https://github.com/camunda/camunda-modeler/blob/c2626b39ad22fc97387c7813ab95528d5c8e1d85/resources/element-templates/xss.json#L21

**Comment by nikku** [comment]
What is your request about in terms of our clearly defined issue templates? 

![image](https://user-images.githubusercontent.com/58601/79043657-b6fb7b00-7c00-11ea-9afc-20a9ffe4501f.png)
