### ISSUE TITLE
Export image on save

### ISSUE THREAD

**Issue by danielwinkels** [camunda/camunda-modeler#1771]
An image of the process should be exported automatically when the model is saved.

I need to create / document BPMN-Models that can be viewed by anybody without the Camund Modeler, but the image and the model have to be in sync.

**Comment by nikku** [comment]
Please use our existing issue template or we cannot help you.

**Comment by pinussilvestrus** [comment]
I'll close this issue since it has a lack of proper form. @danielwinkels feel free to re-open if you have further information to share.
