### ISSUE TITLE
Missing whitespaces in Input Expression help text

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#1772]
__Describe the Bug__

![image](https://user-images.githubusercontent.com/2777965/79231243-11e1dc00-7e66-11ea-95aa-e2eda65cfd79.png)

__Steps to Reproduce__

1. click in the Input Label field
2. read the help text below the Input Expression field 

__Expected Behavior__
Help text for contains whitespaces

__Environment__

- OS: [Linux Mint]
- Camunda Modeler Version: [4.0.0-nightly 20200413 ]

**Comment by pinussilvestrus** [comment]
Thanks for reporting! That might be resolved (or removed completely) when we update the column headers this quarter, cf. https://github.com/bpmn-io/dmn-js/issues/490
