### ISSUE TITLE
Start Process Instance Modal does not have correct label

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1777]
__Describe the Bug__

When opening the start instance modal via the option "Start process instance with new configuration", the label of the second modal step is wrong

![Kapture 2020-04-22 at 9 10 28](https://user-images.githubusercontent.com/9433996/79951549-30089700-8479-11ea-8d65-b5c429c94932.gif)

This is only reproducible when executing the procedure via the "Start process instance with new configuration" toolbar option.

__Steps to Reproduce__

1. open a diagram
2. execute  "Start process instance with new configuration" in toolbar under the run instance action
3. Go through the first deployment step
4. Note the wrong label of the second modal step

__Expected Behavior__

This modal should be displayed:

![image](https://user-images.githubusercontent.com/9433996/79951922-deacd780-8479-11ea-9861-edd9c3c63bad.png)

__Environment__

- OS: macOS 10.15
- Camunda Modeler Version: 4.0.0-alpha.1

**Comment by prithviraj-maurya** [comment]
I would like to work on this if approved as part of #hacktoberfest

**Comment by pinussilvestrus** [comment]
Feel free to open a Pull Request.

**Comment by sujata13** [comment]
@pinussilvestrus Can I work on this issue?
