### ISSUE TITLE
Clarify plugin files location

### ISSUE THREAD

**Issue by Acipenser** [camunda/camunda-modeler#1786]
__What should we do?__

Rewrite the [Camunda Modeler Plugins Documentation](https://github.com/camunda/camunda-modeler/blob/develop/docs/plugins/README.md#plugging-into-the-camunda-modeler) to make it clear that the plugin files have to be in their own folder inside the /plugins directory.

__Why should we do it?__

> The Camunda Modeler is only able to find plugins put directly into the plugins directory. plugins/*/my-plugin cannot be found.

 Those sentences can be misunderstood in a way that the plugin files (index.js,...) have to lie directly in the root folder.

**Comment by nikku** [comment]
Could you propose a change to our docs that is easier to understand and less miss-leading from your point of view?
