### ISSUE TITLE
Reconsider the design of the "Start process instance" dialogue

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#1790]
__What should we do?__

During process development I changed my process engine runtime. Either switching from Tomcat server to Spring boot or changed the port of my Spring boot application.

When I want to start a new process instance from the modeler in the new environment, I get a dialogue that shows the name of the last deployment on top of the new server endpoint configuration:

![grafik](https://user-images.githubusercontent.com/7870843/80701326-82802e00-8adf-11ea-9156-389cf80244d1.png)

The red marked details should be removed.

__Why should we do it?__

The details of the deployment are confusing. I have deployed my process recently. I only want to start a new instance of it.

Have I pushed the wrong button (deploy process model)?

Starting a process instance, I don't need the deployment details.

The selection in the drop down menu is called "Start process instance with new configuration".

**Comment by nikku** [comment]
Could you double check if your feedback still applies with version `v4.0`? We re-worked the start instance and deploy features and tried to ensure that the user does not need to provide details already entered.

**Comment by ingorichtsmeier** [comment]
Hi @nikku ,
It's sligtly better now as it is less confusing. 

But the most common usecase for starting another process instance is to change only the business key. (At least for me as a process automation developer) 

Maybe you should add another menu action (start process with changed business key) inbetween the existing ones?

**Comment by nikku** [comment]
Thanks for your feedback. 

I'll update the issue and we'll see what we can do.

**Comment by volkergersabeck** [comment]
@ingorichtsmeier is this still a relevant issue in the current Modeler? Otherwise, we would close the ticket without any fix.

**Comment by ingorichtsmeier** [comment]
Hi @volkergersabeck,

developer experience can still be improved.

Usually you don't change the REST-endpoit during the process development, after the initial setup.

As a developer you want to start process instances with certain variables or another business key.

Variables are missing at all and the business key is hidden on the second page.

Please improve it further.

Thank you, Ingo

**Comment by volkergersabeck** [comment]
Thanks for the clarification. Yes, the variables are still missing for starting process instances. We have this on the roadmap, but still a few other topics with higher prio first. 
Since this ticket was about the deployment name, I'm closing it.
