### ISSUE TITLE
Update icon on Electron Apps

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1791]
__What should we do?__

Update app icon on https://www.electronjs.org/apps

It can be done here: https://github.com/electron/apps/tree/master/apps/camunda-modeler

__Why should we do it?__

The app icon will be changed.

Requires https://github.com/camunda/camunda-modeler/issues/1779

**Comment by oguzeroglu** [comment]
https://github.com/electron/apps/pull/1415

**Comment by pinussilvestrus** [comment]
Works: https://www.electronjs.org/apps/camunda-modeler
