### ISSUE TITLE
Tabs reopen, even if they were closed with last Modeler quit

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#1795]
__Describe the Bug__

Even if I close certain Modeler tabs before I quit the Modeler, sometimes they show up again with the next start.

__Steps to Reproduce__

Close a tab and then the modeler without much time in between.
Reopen the modeler.

![May-06-2020 09-35-16](https://user-images.githubusercontent.com/17595149/81148955-8dbed800-8f7d-11ea-8bbc-ecc773c93915.gif)

__Expected Behavior__

Tabs that were closed should not reappear when the Modeler is opened again.
__Environment__

- OS: MacOS 10.15.4
- Camunda Modeler Version: 3.7.3

I know that a workaround is to wait for some time between closing the tabs and closing the modeler, but that can be pretty long (depending on how many tabs and how large the models (?)). Plus, this is not a good solution.

----

Depends on https://github.com/camunda/camunda-modeler/issues/1370.

**Comment by philippfromme** [comment]
Related to https://github.com/camunda/camunda-modeler/issues/1370.

The solution is to force updating the workspace before quitting the application.
