### ISSUE TITLE
Sequence flow condition removed after morphing source or target (Task / Gateway)

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#180]
__Describe the Problem__

When changing the source or target of a sequence flow that has a condition configured it seems like re-connecting the sequence flow does not retain the condition.

![image](https://user-images.githubusercontent.com/58601/62854135-b7004f80-bcee-11e9-848d-6ca71f85eb65.png)

**Steps to Reproduce**

* [open test diagram](https://github.com/camunda/camunda-modeler/files/3491551/conditional.bpmn.txt)
* Change target to intermediate message throw event _or_ change source to inclusive gateway
* See that condition on sequence flow `A` is lost

__Environment__

Camunda Modeler Version: `<= v3.3.0-alpha.1`

**Comment by nikku** [comment]
Adding a condition to the sequence flow should not be allowed (makes no sense from the BPMN perspective).

**Comment by nikku** [comment]
We have got #131 in the backlog with is not related, right?

**Comment by mschoe** [comment]
I choosed apoor example. Let's take this one:
Exclusive Gateway --> Sequence Flow --> Event
-- Add condition to sequence flow
-- change event type

--> sequence flow condition is lost

**Comment by mschoe** [comment]
my example was weak. Let's assume following scenario:
Exclusive Gateway --> Sequence Flow --> Event
- The outgoing sequence flows after the gateway need a condition to decide which path to take
-- Add condition to sequence flow
-- change event type

--> Booom, the sequence flow lost the condition

This is not related to #131 as this bug is not caused by morphing to default flow.

**Comment by nikku** [comment]
Still an issue with `v3.3.0-alpha.1`.

**Comment by nikku** [comment]
I've updated the description to provide more clarity.

**Comment by pinussilvestrus** [comment]
Seems like this will be fixed by the next release, cf. https://github.com/bpmn-io/bpmn-js/commit/b290078600ae4e45e7c72bd37919732e3f8fcbea

![Kapture 2019-10-10 at 9 10 18](https://user-images.githubusercontent.com/9433996/66546668-ce688700-eb3d-11e9-8b99-9add809f7711.gif)

**Comment by pinussilvestrus** [comment]
Can someone re-check this, so we can add the 'fixed upstream' label? @barmac @philippfromme @oguzeroglu?

**Comment by barmac** [comment]
I'll have a look at this today.

**Comment by oguzeroglu** [comment]
@pinussilvestrus I checked this also, this is fixed with the commit you mentioned.
