### ISSUE TITLE
Application prevents machine from shut down / restart

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1803]
__Describe the Bug__

When trying to shut down or restart on a macOS machine, the Camunda Modeler application prevents from doing it by hanging up.

<img width="494" alt="Bildschirmfoto 2020-05-18 um 10 27 39" src="https://user-images.githubusercontent.com/9433996/82191418-c9995c00-98f2-11ea-9e87-1e68b3ad59f6.png">

The current workaround is to manually close the application afterward.

__Steps to Reproduce__

1. Open Camunda Modeler, no files have to be open
2. Try to shut down or restart OS from the application menu
3. See that Camunda Modeler is not terminating

__Expected Behavior__

The application should terminate and the shutdown/restart should be going on.

__Environment__

- OS: macOS 10.15.4 / 11.2.3 (https://github.com/camunda/camunda-modeler/issues/2230)
- Camunda Modeler Version: 4.0.0-alpha.3, but also older versions (tested on 3.7, 3.3, 3.0)

__Additional Resources__

I attached the logs from the Modeler application after the quit was initiated

```sh
2020-05-18T08:26:48.935Z  INFO app:main asking client to allow quit
2020-05-18T08:26:48.938Z  INFO app:main quit allowed
2020-05-18T08:26:48.938Z  INFO app:main initating close of main window
2020-05-18T08:26:48.938Z  INFO app:main main window closed
2020-05-18T08:26:48.939Z  INFO app:mac-os Keeping app in the dock
```

See how the app is not terminating mode afterward, cf. [`window-all-closed` handler](https://github.com/camunda/camunda-modeler/blob/develop/app/lib/platform/mac-os/index.js#L79)

**Comment by pinussilvestrus** [comment]
Seems like the `app:quit` event got not fired on newer macOS version, but not sure why

**Comment by barmac** [comment]
What I noticed is, that on the first try to shut down the machine only the modeler window is closed. Then I need to try to shut down for the second time to actually quit the app and let the system continue (CM 3.7.1, MacOS 10.15.4).

**Comment by nikku** [comment]
The app does a roundtrip via the UI to ask the user if quit is allowed.

Maybe that blocks the app quit on MacOS, if the main window is closed? In that case, accessing the main window won't be possible and we should not do the roundtrip alltogether.

**Comment by barmac** [comment]
Log:
```
2020-05-18T09:18:44.345Z  INFO app:main initating close of main window
2020-05-18T09:18:44.345Z  INFO app:main asking client to allow quit
2020-05-18T09:18:44.359Z  INFO app:main quit allowed
2020-05-18T09:18:44.359Z  INFO app:main initating close of main window
2020-05-18T09:18:44.359Z  INFO app:main main window closed
2020-05-18T09:18:44.359Z  INFO app:mac-os Keeping app in the dock
```

**Comment by pinussilvestrus** [comment]
> Maybe that blocks the app quit on MacOS, if the main window is closed?

Maybe that's a thing here. But I can remember that worked before my latest macOS updates

**Comment by nikku** [comment]
A solution strategy could be how atom and/or VSCode handle this. 

There surely is some nifty electron magic involved to make this work on MacOS.

**Comment by nikku** [comment]
Example: Atom appears to listen to the `before-quit` event and unload all windows forcefully, cf. [`atom-application.js`](https://github.com/atom/atom/blob/master/src/main-process/atom-application.js#L713)

**Comment by nikku** [comment]
Example: VSCode handles it in a fairly similar fashion. `before-quit` sets a `_quitRequested` flag that is being considered in `window-all-closed`, cf. [`lifecycleMainService.ts`](https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/platform/lifecycle/electron-main/lifecycleMainService.ts#L220).
