### ISSUE TITLE
Send PING to E.T.

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1805]
__What should we do?__

If usage analytics is enabled, send a _hourly|daily_ :grey_question: ping to [E.T.](https://github.com/camunda/et), our telemetry back-end. 

Communication with E.T. happens as documented on the [E.T. documentation page](https://github.com/camunda/et).

As of now, there exists a preview of the public endpoint to push PING request to to, cf. https://github.com/camunda/et/issues/32.

__Why should we do it?__

Get insights into basic app usage metrics.

----

Depends on https://github.com/camunda/et/issues/32.

**Comment by nikku** [comment]
We are ready to go to implement this behind a feature toggle.

**Comment by volkergersabeck** [comment]
We could submit, if users have existing element templates
