### ISSUE TITLE
Selection outline on root element doesn't fit after change in properties panel

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#181]
Reproduce:
- create new diagram
- change process id in the properties panel
- click/hover over the start element

--> selection outline is four times bigger

- add a pool
- change process id
- click in the upper left corner of the pool

--> selection outline is very small

**Comment by nikku** [comment]
Related to bpmn-io/diagram-js#149?

**Comment by pedesen** [comment]
Fixed with https://github.com/bpmn-io/diagram-js/commit/90ca56f883dfa9b72feee782afbdcf5422899387
