### ISSUE TITLE
DMN DRD Diagram: Associations sometimes are removed for no apparent reason

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1814]
__Describe the Bug__

Associations sometimes are removed for no apparent reason.

![dmn-association-bug](https://user-images.githubusercontent.com/7633572/83105336-c18fa800-a0ba-11ea-9db4-8f03be7af6ca.gif)

__Steps to Reproduce__

1. Add a text annotation to a decision
2. Add a decision logic (decision table or literal expression)
3. Open the decision
4. Navigate back to the DRD

__Expected Behavior__

Association is not removed.

__Environment__

- Camunda Modeler Version: v4.0.0

**Comment by pinussilvestrus** [comment]
Probably related to https://github.com/camunda/camunda-modeler/issues/1763

**Comment by philippfromme** [comment]
@pinussilvestrus Duplicate you mean? 🤣 Alright, closing.
