### ISSUE TITLE
Shortcuts fire multiple times per key stroke when window is reopened

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1816]
__Describe the Bug__

When I close the window (but not the application) and open it again, shortcuts for opening new tabs and closing the current are fired multiple times per one key stroke. As a result, I get two or more tabs per one `Cmd+T`.

__Steps to Reproduce__

1. Open Camunda Modeler on MacOS
2. Close the window and open it again
3. now this happens

__Expected Behavior__

Shortcuts should fire once per key stroke.

__Environment__

- OS: MacOS 10.15.4
- Camunda Modeler Version: 3.7.1, 4.0.0

**Comment by barmac** [comment]
We initiate menu each time a new window is opened: https://github.com/camunda/camunda-modeler/blob/develop/app/lib/index.js#L344 Thus, there are multiple listeners for menu actions.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1826.
