### ISSUE TITLE
[DMN] Association is not created when dragged from the context pad

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1817]
__Describe the Bug__

When I create a text annotation by dragging it from the context pad, no association is created.

![association](https://user-images.githubusercontent.com/28307541/83113192-9495c200-a0c7-11ea-8834-5a80ecbd04e1.gif)

__Steps to Reproduce__

1. Select a decision
2. Drag a text annotation from the context pad
3. now this happens

__Expected Behavior__

An association should be created.

__Environment__

- OS: MacOS 10.15.4
- Camunda Modeler Version: 4.0.0

I was not able to reproduce it in 3.7.1

**Comment by philippfromme** [comment]
Related to https://github.com/camunda/camunda-modeler/issues/1702

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/dmn-js/pull/519.
