### ISSUE TITLE
Tests fail but build succeeds

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1820]
__Describe the Bug__

Tests failed but codecov succeeded so Travis CI thought that job is successful.

https://travis-ci.org/github/camunda/camunda-modeler/jobs/694279584

__Steps to Reproduce__

See linked job above.

__Expected Behavior__

Job fails.

__Environment__

- OS: Travis CI / Linux
- Camunda Modeler Version: 4.0.0

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/30e0852a3b975bfaab88d136a16c93c95045d927
