### ISSUE TITLE
Fix source maps not working in Camunda Modeler crash reports

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1831]
__What should we do?__

* [x] Investigate why source maps in the client bundle are not working in our crash reports. (See [this comment](https://github.com/camunda/camunda-modeler/issues/1831#issuecomment-648676209).)
* [ ] Fix the situation

__Why should we do it?__

Source maps allow us to reliably reproduce issues recorded.

**Comment by oguzeroglu** [comment]
We should also not upload `*Spec.js` files, as they are now present within the uploaded artifacts in Sentry.

**Comment by oguzeroglu** [comment]
We should also not set an array of plugins as a tag. It turns out that Sentry does not allow non-primivite values as tags:
<img width="886" alt="Screenshot 2020-06-22 at 17 53 39" src="https://user-images.githubusercontent.com/15003836/85308344-67171b00-b4b1-11ea-9fa1-01f43e6ee740.png">

**Comment by oguzeroglu** [comment]
We should also consider disabling this feature for nightlies, as we're uploading nightly sourcemaps to Sentry every night.

**Comment by oguzeroglu** [comment]
The problem seems to be path mismatch: Since we distribute the code to the clients, each error has a different path from uploaded sourcemap paths. We need to normalize the path before we send them to Sentry. I'm investigating the best practises for that.
