### ISSUE TITLE
Diagram Can Be Revealed in File Explorer

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1834]
## __Is your feature request related to a problem? Please describe.__

There is no easy way to get to a diagram file that is open in the Camunda Modeler. The only way to figure out where that file is on your hard drive is the tooltip that pops up on hovering the tab.

![image](https://user-images.githubusercontent.com/7633572/84503282-39b0bd00-acba-11ea-9f74-a5f4460f960a.png)

## __Describe the solution you'd like__

Adding an option to reveal the diagram in the file explorer when opening the context menu would be helpful.

### Current context menu:

![image](https://user-images.githubusercontent.com/7633572/84503422-7381c380-acba-11ea-850b-bd4e19a512da.png)

### _Reveal in file explorer_ option in Visual Studio Code:

![image](https://user-images.githubusercontent.com/7633572/84503075-ceff8180-acb9-11ea-9b29-660cd44c2757.png)

**Comment by chrysillala** [comment]
Hi, I would like to work on this issue. Could you please assign to me? Thanks
