### ISSUE TITLE
Support bpmn-js@7 in bpmn-js Extensions

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1837]
__What should we do?__

Update dev and peer dependencies and ensure extensions work with bpmn-js@7:

* [x] [bpmn-js-cli](https://github.com/bpmn-io/bpmn-js-cli) @philippfromme @maxtru
* [x] [bpmn-js-collapse-subprocess](https://github.com/bpmn-io/bpmn-js-collapse-subprocess) @barmac 
* [x] [bpmn-js-disable-collapsed-subprocess](https://github.com/bpmn-io/bpmn-js-disable-collapsed-subprocess) @barmac 
* [x] [bpmn-js-executable-fix](https://github.com/bpmn-io/bpmn-js-executable-fix) @MaxTru 
* [x] [bpmn-js-properties-panel](https://github.com/bpmn-io/bpmn-js-properties-panel) @oguzeroglu 
* [x] [bpmn-js-signavio-compat](https://github.com/bpmn-io/bpmn-js-signavio-compat) @barmac 

It might make sense to create issues in the respective repositories.

**Comment by linus-amg** [comment]
Out of curiosity, will you just add 7 to the list, or already plan ahead and add 8 and such? Or will this always be a topic to do after releasing a major?

**Comment by philippfromme** [comment]
We do not add versions that have been released yet because we can not be sure whether they will be compatible without changes. Of course we should always update peer dependencies as quickly as possible after a major release.

**Comment by barmac** [comment]
I think that until we know what breaking changes are introduced in `bpmn-js@8`, we cannot guarantee that the package will work with that major version.

**Comment by linus-amg** [comment]
> We do not add versions that have been released yet because we can not be sure whether they will be compatible without changes. Of course we should always update peer dependencies as quickly as possible after a major release.

Oh well yeah, that obviously makes a lot of sense 🥟 thanks for the fast reply!

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/67805010d74fbb37ead7410edef89802295b3d15
