### ISSUE TITLE
Keyboard shortcuts and menu entries for undo don't work in decision table

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1843]
__Describe the Bug__

When I create input/output column or new rule, I cannot undo the action via menu or keyboard shortcuts.

The toolbar button still works, though.

__Steps to Reproduce__

1. Create new input in decision table
2. Press Cmd/Strg + Z or click menu entry for Undo
3. now this happens

__Expected Behavior__

Shorcut should work.

__Environment__

- OS: MacOS 10.15.4
- Camunda Modeler Version: 3.7.1, 4.0.0, develop

**Comment by MaxTru** [comment]
Bug can be reproduced with same behaviour on OS: Arch Linux (Modeler 4.0.0)

**Comment by MaxTru** [comment]
Seems to be related to this Chromium bug: https://github.com/electron/electron/issues/3682

The fix we used [here](https://github.com/camunda/camunda-modeler/commit/434f46248c72d5fb842ecdf42436ebaed6569bf2) seems to solve the issue. Will investigate a bit further before creating the PR.
