### ISSUE TITLE
Make changing an element template a two-step action (unlink & choose new template)

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#1852]
__Is your feature request related to a problem? Please describe.__

Currently when working with element templates on service tasks, the Modeler User can switch freely between element templates using a dropdown. As soon as a template is selected, the values it specifies are directly applied to the respective fields.

This leads to the problem that other values, which the Modeler User has already set, are overwritten (potentially without the user noticing)

__Describe the solution you'd like__

This is a first solution-light to the problem. The goal of this solution is to make the application of an element template (and its value) a conscious decision for the user. _Specification is yet to be clarified_

_Option A_
- [ ] As soon as a template was applied (by clicking on one element template from the dropdown), the dropdown is disabled
- [ ] In order to re-enable the drop-down, the currently applied template needs to be "unlinked" by clicking a respective button. Unlinking would include a potential deletion of the specified parameters of that template so to not clutter the parameters (to be confirmed)

_Option B_
- [ ] When selecting a new template, a confirmation dialog stating the consequences (overwrite of existing values) requiring an "Okay" by the user

_Option C_
- [ ] we offer two things: either we keep all properties or we remove all properties (maybe except the element ID) regardless whether they were set by the template
- [ ] When switching from one template to another, removing all properties seems to be a good default
- [ ] When unlinking a template, then both options seems valid and we might offer them to the user

__Future solution__

Forward looking, the user shall retrieve more information about the impact of applying an element template by e.g., showing a dialog window which states all consequences of the application of that template (e.g., which fields are overwritten)

__Additional context__

Other issue relating to improvement of element template application: #1355

**Comment by andreasgeier** [comment]
We have to answer two questions:
- what happens when applying an element template?
- what happens when removing/changing an element template?

In my opinion, solution A would not solve the problem. Data will still be overwritten. The only little benefit I see is that the 2-step action may help the user to understand that after removing a template its data remains (seeing some artifacts in the general tab afterwards).

I would like to suggest that we answer the two questions mentioned above by defining an automatism or by providing options to the user. A two-step solution would then not be necessary.

Option B may be the most simple solution but it would also not require a two-step-action.

**Comment by volkergersabeck** [comment]
> Unlinking would include a potential deletion of the specified parameters of that template so to not clutter the parameters

this would require a major change in how element templates work today and might not be feasible for the first iteration.

> When selecting a new template, a confirmation dialog stating the consequences (overwrite of existing values) requiring an "Okay" by the user

This would happen every time a user selects from the worker catalog, and would lead to a situation where less technical people would be faced with technical details that they cannot understand. Therefore, I'm not sure if option B would be a good way to go. I could imagine option B as an alternative in case the user wants to see this, but not the default.

**Comment by volkergersabeck** [comment]
Alternative:
- we offer two things: either we keep all properties or we remove all properties (maybe except the element ID) regardless whether they were set by the template

When switching from one template to another, removing all properties seems to be a good default
When unlinking a template, then both options seems valid and we might offer them to the user

to be defined: how does this relate to initially applying an element template and what happens to properties that already existed before.

**Comment by MaxTru** [comment]
Will be closed by #1889
