### ISSUE TITLE
When Overview is too large, cell header popup is not positioned correctly

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1869]
__Describe the Bug__

When the DMN Overview got extended to a certain width, the table cell header popup is not positioned correctly.

![Kapture 2020-07-10 at 11 43 24](https://user-images.githubusercontent.com/9433996/87141058-bd060400-c2a2-11ea-8749-e8a10db75ee7.gif)

__Steps to Reproduce__

1. Increase Overview width
2. Start Editing Table Header Cell via double click
3. See the position is not correct (too wide to the left)

__Expected Behavior__

The popup opens on the correct position

__Environment__

- OS: MacOS 10.15.5
- Camunda Modeler Version: 4.1.0

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/30dc20a0a0b46d3444dacd419a15fb42427270f4.
