### ISSUE TITLE
Palette not usable on smaller screens

### ISSUE THREAD

**Issue by dumblob** [camunda/camunda-modeler#187]
Managers and analysts, the target group of camunda-modeler often use 14" or sometimes even smaller screens on their notebooks and the tool panel on the left side is not fully available (the last three icons at the bottom are fully hidden).

I have 15" notebook, but it still doesn't show the last two icons, because the panel is too long. Maybe, some of the icons there are redundant (e.g. the end event icon).

Also, the modeler doesn't respect DPI settings, so fonts are extremely tiny on higher-DPI screens (such screens are nowadays getting widespread).

**Comment by vladimirskatusenoks** [comment]
Thank you for reporting this.
Sounds like a valid issue and we will look into it.

**Comment by nikku** [comment]
Closed via responsive palette: bpmn-io/bpmn-js#502.
