### ISSUE TITLE
Improve logging behavior in hot functions

### ISSUE THREAD

**Issue by oguzeroglu** [camunda/camunda-modeler#1870]
__Is your feature request related to a problem? Please describe.__

We should consider improving the logging behavior in hot functions. See the GIF:

![to-many-logs](https://user-images.githubusercontent.com/15003836/87153125-3c053780-c2b7-11ea-8d85-512c8d67d5f9.gif)

In this GIF, we're logging UI resize event. `console.log` is expensive and should be avoided inside hot functions. It also creates a lot of noise in logs.

__Describe the solution you'd like__

Filter repetitive logs in the logger mechanism.

__Describe alternatives you've considered__

Turn of certain logs in production builds.

**Comment by pinussilvestrus** [comment]
Just for completion: we currently [every single action](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/App.js#L1570) even in production.

**Comment by philippfromme** [comment]
Related to https://github.com/camunda/camunda-modeler/issues/1369
