### ISSUE TITLE
File menue still shows "DMN Table" option

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#1871]
__Describe the Bug__

`File` menue still shows 'New file' => 'DMN Table' option.

__Steps to Reproduce__

![Screenshot_20200710_142606](https://user-images.githubusercontent.com/42800119/87154946-61477500-c2ba-11ea-8089-e515ac626e0e.png)

1.Click on File
2.Hover on New File

__Expected Behavior__

Option `DMN Table` shall not be present anymore.

__Environment__

- OS: Arch Linux - Manjaro
- Camunda Modeler Version: 4.1

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1873
