### ISSUE TITLE
Association is gone when going in decision table view

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#1874]
__Describe the Bug__

The association to annotation in DMN diagrams is lost, when the association was replaced and the decision table view is opened.

__Steps to Reproduce__

1. Add annotation to decision table
2. Move the annotation link, but keep it connected to the same decision table
3. Open decision table view using green icon
4. => Association will get lost

![AssociationLost](https://user-images.githubusercontent.com/42800119/87155572-707af280-c2bb-11ea-8ff9-695fc1696a97.gif)

__Expected Behavior__

* Association shall not be affected by opening the decision table view

__Environment__

- OS: Arch Linux - Manjaro
- Camunda Modeler Version: 4.1

**Comment by philippfromme** [comment]
I think this was supposed to be fixed: https://github.com/camunda/camunda-modeler/issues/1702

**Comment by philippfromme** [comment]
I can't reproduce this using v4.1.0.

**Comment by pinussilvestrus** [comment]
I can only reproduce this when creating _the first_ annotation. After this, I can't reproduce it anymore.

**Comment by philippfromme** [comment]
That's interesting!

**Comment by nikku** [comment]
Fixed upstream (again) via https://github.com/bpmn-io/dmn-js/pull/620.
