### ISSUE TITLE
coordinate mismatch between bpml and image

### ISSUE THREAD

**Issue by fabianhu** [camunda/camunda-modeler#1875]
__Describe the Bug__

The coordinate system of a exported image does not seem to have a clear relation to the coordinates used in the bpmn XML file.
See image attached.
Background: 
I am in the process of making a automated html imagemap + generated html page to make a portable view of the modeled processes.
This is a pythonic workaround, as at the moment the models can only be viewed in the modeler.
I find this especially important, if the tool should be used to document processes in other systems.

![diagram2](https://user-images.githubusercontent.com/5732935/87203279-8c55b700-c302-11ea-876e-7bf92e9f2d87.png)

__Steps to Reproduce__

1. export image
2. save diagram as bpmn file
3. compare image coordinates and xml coordinates -> there is a odd relation and a offset as well. 

__Expected Behavior__

xml coordinates should match image coordinates
or the relation should be documented.

Workaround (updated): 
image coordinates * 3 = xml coordinates.
Offset = take image size and center it over the min and max item coordinates of all xml drawable items (excluding text items)
This is quite a usable approach.

__Environment__

- OS: Win, Linux 
- Camunda Modeler Version: camunda-modeler-4.0.0-linux-x64 + Windows and nightly on Linux.

**Comment by philippfromme** [comment]
Images are exported with a [default zoom scale of 3](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/util/generateImage.js#L19) unless they're too large.

**Comment by pinussilvestrus** [comment]
@fabianhu any new input regarding this?

**Comment by fabianhu** [comment]
Hi, I am about to publish the python tool. - cleaning up some ugly hacks in the code.
For the formula I updated the description above with the workaround I used.
Suggestion for the coordinates would be indeed to have 1:1 pixel coordinates in the xml. 
Even a fixed factor of 3 is ok, but I kind of dislike the offset, which has to be calculated over all element coordinates first.

**Comment by nikku** [comment]
From what I've cross-read you were able to work around our behavior? 

If that is the case, I'm inclined to close this issue, as we do not plan on changing the existing export behavior any time soon.

**Comment by fabianhu** [comment]
For me the issue is solved for now, thanks. I just see, that I can close this myself -> doing so.
My boundary calculation now even includes the arrows.
If someone points me near the relevant locations in the code, I could try to fix the coordinates in the image export or in the xml export without breaking any compatibility.

**Comment by nikku** [comment]
[This is the place](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/BaseViewer.js#L448). However, as you can see we cut off / normalize intentionally.
