### ISSUE TITLE
Allow to apply (link), unlink or remove an element template

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#1889]
__Is your feature request related to a problem? Please describe.__

Currently when working with element templates on service tasks, the Modeler User can switch freely between element templates using a dropdown. As soon as a template is selected, the values it specifies are directly applied to the respective fields.

This leads to the problem that other values, which the Modeler User has already set, are overwritten (potentially without the user noticing). In general the behaviour is not transparent to the user.

__Describe the solution you'd like__
See [Design Decisions](https://docs.google.com/presentation/d/1groCM-o4nUjtg5T-tVMCNy7YEHUaLy34yr53aYbZ_e4/edit?usp=sharing)

- [x] From the element template search modal (), the user can "apply" an element template . This applies the properties and links the template technically. This then triggers displaying the simplified property panel. Ruleset:
  - [ ] Delete the current element properties which are not set in the template
  - [x] Add and set the properties which are not set in the element but set in the template
  - [ ] Add and set the properties from the template which are set in the element but equal the default values of the old template
  - [ ] Keep the current element properties which are set in the element and differ from the default value in the old template
- [x] From the simplified property panel, the user can "unlink" the template. This does not remove any data but only removes the technical link and therefore enables the non-simplified view again.
- [x] From the simplified property panel, the user can "remove" the template. This removes all data from the element and unlinks the template.

__Alternatives__
See [Design Decisions](https://docs.google.com/presentation/d/1groCM-o4nUjtg5T-tVMCNy7YEHUaLy34yr53aYbZ_e4/edit?usp=sharing)

Affects https://github.com/camunda/camunda-modeler/issues/1894

**Comment by philippfromme** [comment]
> * Delete the current element properties which are not set in the template

@MaxTru This is not how applying an element template currently works. No properties will be removed when applying a template. They might be overridden. Do we want to change this behavior?

**Comment by MaxTru** [comment]
> > * Delete the current element properties which are not set in the template
> 
> @MaxTru This is not how applying an element template currently works. No properties will be removed when applying a template. They might be overridden. Do we want to change this behavior?

The idea behind this is to make sure that an element template user will get not in a confusing state, where he/she cannot see properties, which are actually set [excluding the special case of properties, which were deliberately set to `hidden` in the element template config]. So therefore yes, let's change this behaviour.

Let's discuss if this is a challenge currently (I don't see this is a must-have for the MVP solution)
