### ISSUE TITLE
Direct Editing Not Completed on Drill Down

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1892]
__Describe the Bug__

When navigating through drill down active direct editing is not completed.

![DRD label editing](https://user-images.githubusercontent.com/7633572/88150850-34705780-cc02-11ea-839e-5130988efe10.gif)

There is a fix for this issue: https://github.com/camunda/camunda-modeler/tree/develop/client/src/app/tabs/bpmn/modeler/features/complete-direct-editing

This fix also must be applied to drilling down.

__Steps to Reproduce__

1. Start direct editing
2. Drill down
3. Go back to DRD
4. Direct editing still active

__Expected Behavior__

Drilling down completes direct editing.

__Environment__

- Camunda Modeler Version: 4.1.0

**Comment by barmac** [comment]
Related to https://github.com/bpmn-io/dmn-js/issues/547

**Comment by MaxTru** [comment]
Fixed upstream https://github.com/bpmn-io/dmn-js/pull/548
