### ISSUE TITLE
Property tab is simplified for RPA / Element Template use-case

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#1894]
__Is your feature request related to a problem? Please describe.__

The design of the property panel general tab does currently not optimally support the user need to reduce complexity when using element templates (spec. for RPA). Also, the "unlink" and "remove" (https://github.com/camunda/camunda-modeler/issues/1889) template logic can not be applied.

__Describe the solution you'd like__

See https://app.zeplin.io/project/5e149dc7ef8eaa51b52af327?seid=5f0dc356713f249d468ca42b
See https://docs.google.com/presentation/d/1groCM-o4nUjtg5T-tVMCNy7YEHUaLy34yr53aYbZ_e4/edit

[Update 10.09.: the ID and name field will not moved to the header]

__Describe alternatives you've considered__

See https://docs.google.com/presentation/d/1groCM-o4nUjtg5T-tVMCNy7YEHUaLy34yr53aYbZ_e4/edit

__Additional context__

Child of https://github.com/bpmn-io/internal-docs/issues/121
Affects https://github.com/camunda/camunda-modeler/issues/1891
Affects https://github.com/camunda/camunda-modeler/issues/1889
Related on https://github.com/bpmn-io/bpmn-js-properties-panel/issues/349

**Comment by pinussilvestrus** [comment]
Latest design proposals after the third round of user testing: https://miro.com/app/board/o9J_kplMaDU=/?moveToWidget=3074457349123831620&cot=13

**Comment by pinussilvestrus** [comment]
@philippfromme raised the issue of having a base properties panel instead of making changes to all properties panel. He proposed to do some Slack Time on it this week.

**Comment by pinussilvestrus** [comment]
Regarding the [current state of the design](https://app.zeplin.io/project/5e149dc7ef8eaa51b52af327?seid=5f0dc356713f249d468ca42b), I discovered the following points we could start with for the simplified properties panel.

* Changed Properties Panel Header (Id & Name)
* Button to select from catalog
* Own Template Tab
* Removed General Section, section according to Design (Name, description, topic / bot name, last modified)
* Unlink / Remove
* (Input / Output Variables), is pending to decision for new I/O UI
* Custom Fields (as it is today (?))

**Comment by MaxTru** [comment]
> Regarding the [current state of the design](https://app.zeplin.io/project/5e149dc7ef8eaa51b52af327?seid=5f0dc356713f249d468ca42b), I discovered the following points we could start with for the simplified properties panel. Note that the designs are still WIP.
> 
> * Changed Properties Panel Header (Id & Name)
> * Button to select from catalog
> * Own Template Tab
> * Removed General Section, section according to Design (Name, description, topic / bot name, last modified)
> * Unlink / Remove
> * (Input / Output Variables), is pending to decision for new I/O UI
> * Custom Fields (as it is today (?))
> 
> Let's discuss this in a meeting.

Discussed with @philippfromme and @pinussilvestrus on 05.08.. Take-aways:
* Button to select from catalog: will overwrite the element template dropdown in Camunda Modeler project. Keep naming simple and generic "Select element template" (or similar)
* `Topic` will be displayed as one of the other custom fields (not as part of the meta info) for now
* New Input/Output variable UI component will be rolled-out for regular tab + simplified prop. panel view
* Fields are either hidden / editable / non-editable based on what is defined in the template
* Custom fields are left as of today

**Comment by pinussilvestrus** [comment]
> @philippfromme raised the issue of having a base properties panel instead of making changes to all properties panel. He proposed to do some Slack Time on it this week.

@camunda/modeling-dev 

As a result of this, we decided to not refactor the properties panel beforehand. Those refactoring would take a lot of time and we should plan it accordingly. We're not blocked with this when making the changes for the simplified properties panel.

**Comment by pinussilvestrus** [comment]
@philippfromme will start on this issue by creating the general infrastructure on displaying the new Element Template Tab. It's needed to start implementing #1891 and #1889. The content of the tab can be found here: https://app.zeplin.io/project/5e149dc7ef8eaa51b52af327?seid=5f0dc356713f249d468ca42b, but will deal with this in a second step.

**Comment by pinussilvestrus** [comment]
Part of the improved element template view is also the grouping of input and output parameters by the new collapse component (https://github.com/bpmn-io/bpmn-js-properties-panel/issues/349). Is this also part of this issue, or do we need another issue here?

Just want to make sure we keep on track with this until our feature freeze in two weeks.

**Comment by MaxTru** [comment]
I would say yes.

But I suggest to sync end of this week (when Philipp is back) including all involved engineers to make sure we have everything covered. I will put something in the calendar.

**Comment by pinussilvestrus** [comment]
Good idea 👍

**Comment by pinussilvestrus** [comment]
Also cf. [to this comment](https://github.com/camunda/camunda-modeler/pull/1934/files#r484875769) regarding how `outputParameter` are bind from an element template.

**Comment by MaxTru** [comment]
Today we decided: we will not move the Name/ID to the header (for now)

**Comment by MaxTru** [comment]
> Part of the improved element template view is also the grouping of input and output parameters by the new collapse component ([bpmn-io/bpmn-js-properties-panel#349](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/349)). Is this also part of this issue, or do we need another issue here?
> 
> Just want to make sure we keep on track with this until our feature freeze in two weeks.

This is now handled here: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/358
