### ISSUE TITLE
Dragging of DMN rows is incorrectly previewed

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#1898]
__Describe the Bug__

The dragging of rows in dmn tables works but is incorrectly formatted during the dragging process

__Steps to Reproduce__

Create two or more decision rows
Drag them by using the "drag" icon

![](https://user-images.githubusercontent.com/42800119/88554040-48fb8800-d026-11ea-8414-4850c4f72368.gif)

__Expected Behavior__

Visual during dragging is the same as the end result

__Environment__

Please complete the following information:

Browser: n/a
Modeler: 4.1.1
OS: Arch Linux (Manjaro)
Library version: as used in 4.1.1 modeler

Must be fixed via https://github.com/bpmn-io/dmn-js/issues/550

**Comment by barmac** [comment]
Fixed via https://github.com/camunda/camunda-modeler/pull/1899 together with upstream https://github.com/bpmn-io/dmn-js/pull/557
