### ISSUE TITLE
Undo for DMN decision name direct editing doesnt work on first attempt

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#1912]
__Describe the Bug__

Undo is not working when using direct edit to adjust a DMN decision name. After having performed multiple actions it works

__Steps to Reproduce__

1. Open a new DMN DRD
2. Edit the Decision name
3. Try to undo
![labelEditingBug](https://user-images.githubusercontent.com/42800119/89800170-ad423f80-db2e-11ea-8b7d-59cd6f0b021e.gif)

__Expected Behavior__

Undo works

__Environment__

- OS: Arch Manjaro Linux
- Camunda Modeler Version: 4.1.1

__Additional context__
This belong to a series of undo bugs
* https://github.com/camunda/camunda-modeler/issues/1912
* https://github.com/camunda/camunda-modeler/issues/1921
* https://github.com/camunda/camunda-modeler/issues/1922
* https://github.com/camunda/camunda-modeler/issues/1923

**Comment by MaxTru** [comment]
This bug only occurs after initial creation of a DMN DRD (and when then changing the name of the decision).

Problem seems to be that the `commandStack` tries to undo an `elements.alignToRight` command rather than the updateLabel.

**Comment by oguzeroglu** [comment]
The problem seems to be that, when we edit the label for the first the, the latest command executed becomes `elements.alignToOrigin` rather than `element.updateLabel`.

**Comment by oguzeroglu** [comment]
It turns out that what triggers the `elements.move` command is align-to-origin module. https://github.com/bpmn-io/align-to-origin/blob/34931362346878ea9eec9b248b646c6ba714adf2/lib/align-to-origin.js#L117

**Comment by oguzeroglu** [comment]
One solution would be to register elements position to align-to-origin module on viewer creation so that we can have an early return here: https://github.com/bpmn-io/align-to-origin/blob/34931362346878ea9eec9b248b646c6ba714adf2/lib/align-to-origin.js#L94 since no delta would be computed.

**Comment by oguzeroglu** [comment]
Closed via #1935
