### ISSUE TITLE
DRD: undo of deleting a decision element doesn't work

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#1921]
__Describe the Bug__

When deleting a decision in the DRD view, undo doesn't work.

__Steps to Reproduce__

1. Delete a decision in DRD view
2. Click on undo or ctrl+z
![undoBug](https://user-images.githubusercontent.com/42800119/91411734-0a393780-e849-11ea-91a0-61ef1f3a9f01.gif)

__Expected Behavior__

Deletion is undone

__Environment__

- OS: Arch Linux Manjaro
- Camunda Modeler 4.2.0

__Additional context__
This belong to a series of undo bugs
* https://github.com/camunda/camunda-modeler/issues/1912
* https://github.com/camunda/camunda-modeler/issues/1921
* https://github.com/camunda/camunda-modeler/issues/1922
* https://github.com/camunda/camunda-modeler/issues/1923

**Comment by oguzeroglu** [comment]
Closed via #1938
