### ISSUE TITLE
DMN decision table: undo using keyboard shortcut for custom values doesn't work

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#1922]
__Describe the Bug__

When removing a custom value for of a String input clause, the undo operation using the keyboard shortcut doesn't work. (Button works)

__Steps to Reproduce__

1. Open decision table with string input clause with at least one value in a row
2. Delete a value _using the modal menu_
3. Try to undo using keyboard shortcut
![undoBug2](https://user-images.githubusercontent.com/42800119/91455285-2f966780-e882-11ea-9032-41a0e72e336f.gif)

__Expected Behavior__

Undo via keyboard shortcut works

__Environment__

- OS: Arch Linux Manjaro
- Camunda Modeler Version: 4.2.0

__Additional context__
This belong to a series of undo bugs
* https://github.com/camunda/camunda-modeler/issues/1912
* https://github.com/camunda/camunda-modeler/issues/1921
* https://github.com/camunda/camunda-modeler/issues/1922
* https://github.com/camunda/camunda-modeler/issues/1923

**Comment by oguzeroglu** [comment]
Fixed via https://github.com/camunda/camunda-modeler/commit/f2c0ad3badf3c798c002488494c31ff088caf8cb
