### ISSUE TITLE
DMN decision table undo not working when in freshly opened .dmn

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#1923]
__Describe the Bug__

The undo operation using the keyboard shortcut in the DMN decision table view doesn't work or shows wrong behaviours (see below) when working a just opened .dmn. After having had some interactions with the .dmn, this behaviour disappears.

__Steps to Reproduce__

**Aspect A**
1. Open a dmn
2. Go into decision table
3. Remove an input clause entry
4. Undo using keyboard shortcut
=> instead of undoing, a `-` string is inserted
![undoBug3](https://user-images.githubusercontent.com/42800119/91456102-2a85e800-e883-11ea-8533-e8592b31b1e5.gif)

**Aspect B**
1. Open a dmn
2. Go into decision table
3. Add decision rule / dmn table row
4. Try to undo the insertion of new row using keyboard shortcut
=> Nothing happens
![undoBug4](https://user-images.githubusercontent.com/42800119/91456168-3e314e80-e883-11ea-904e-23c5134a4b8b.gif)

__Expected Behavior__

Undo works

__Environment__

- OS: Arch Linux Manjaro
- Camunda Modeler Version: 4.2.0

__Additional context__
This belong to a series of undo bugs
* https://github.com/camunda/camunda-modeler/issues/1912
* https://github.com/camunda/camunda-modeler/issues/1921
* https://github.com/camunda/camunda-modeler/issues/1922
* https://github.com/camunda/camunda-modeler/issues/1923

**Comment by oguzeroglu** [comment]
Closed via #1942
