### ISSUE TITLE
Update Electron version

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1926]
__What should we do?__

Update to supported version of Electron.

* [ ] use [context isolation](https://www.electronjs.org/docs/tutorial/context-isolation) for better security

__Why should we do it?__

[End of support for Electron 7.x](https://www.electronjs.org/blog/electron-10-0#end-of-support-for-7xy)
[End of support for Electron 9.x](https://www.electronjs.org/blog/electron-12-0#end-of-support-for-9xy)

**Comment by adi-mohan** [comment]
Hello! May I work on this issue?

**Comment by barmac** [comment]
Feel free to start. Please make sure to follow our [contributing guidlines](https://github.com/camunda/camunda-modeler/blob/develop/.github/CONTRIBUTING.md).

**Comment by adi-mohan** [comment]
Hi! The latest version of Electron is 10.x.x 
Would you still prefer to go with 9.x.x ?

**Comment by adi-mohan** [comment]
@barmac CI is passing successfully. Please review my changes. Thanks!

**Comment by barmac** [comment]
Electron 11 [has just been released](https://www.electronjs.org/releases/stable#11.0.0) which means that Electron 9 is one major before end of support.

**Comment by barmac** [comment]
Electron 12 [has just been released](https://www.electronjs.org/blog/electron-12-0) which means that Electron 10 is one major before end of support.
