### ISSUE TITLE
Application Crashes on Launch when config.json is not a valid JSON

### ISSUE THREAD

**Issue by ss-nmoroz** [camunda/camunda-modeler#1927]
__Describe the Bug__

When launching a modeler, a popup window appears with a title: A JavaScript error occurred in the main process. 
<img width="422" alt="camunda-modeler-error" src="https://user-images.githubusercontent.com/62558758/91903151-6ec21f80-ecab-11ea-82e8-c52636a2ef76.PNG">

Clicking OK closes the popup,  then either the main application window opens but none of the ribbon menu items are functional, or application main window does not open at all.

__Steps to Reproduce__

1. Download Camunda modeler v.4.2.0 (WIN x64) from https://camunda.com/download/modeler/
2. Unzip Contents
3. Launch Camunda Modeler.exe

__Expected Behavior__

1. Application Windows opens and all menu items are functional.

__Environment__

- OS: Windows 10 x64
- Camunda Modeler Version: 4.2.0, 4.1.1

**Comment by barmac** [comment]
Can you please paste here application log? It should be located in `C:\Users\<username>\AppData\Roaming\camunda-modeler\logs`.

**Comment by ss-nmoroz** [comment]
Sure.
[log.log](https://github.com/camunda/camunda-modeler/files/5161069/log.log)

**Comment by ss-nmoroz** [comment]
One strange thing I've noticed is that config.json that is referenced in the error window is empty. Is that normal?

**Comment by barmac** [comment]
No, it should be a valid JSON or it should not exist. I was able to reproduce the issue and can confirm that this is a bug in the application. What you can do now is to remove the `config.json` file. After that, Camunda Modeler should work correctly.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1928

**Comment by ss-nmoroz** [comment]
@barmac  Thank you! I have removed the file and now this works as expected.
