### ISSUE TITLE
Validate the element template type <-> binding combination

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#1939]
__Is your feature request related to a problem? Please describe.__

Element template types (`Boolean`, `String`, `Hidden`, ...) can not be used for all bindings. Some combinations of types and bindings lead to errors (see https://github.com/camunda/camunda-modeler/issues/1933).

It would be helpful for the users to validate the `type` <-> `binding` combination and throw a more meaningful error.

__Describe the solution you'd like__

If a user configured a non-valid `type` <-> `binding` combination, a meaningful error shall be thrown (e.g., `Boolean` is not valid for `camunda:InputParameter` please use one of the following: <`String`, ...>)

__Describe alternatives you've considered__

Mid-term it would be even better to do a json schema validation.

__Additional context__

Related to #1933 
Related to https://github.com/bpmn-io/element-templates-json-schema/issues/2
Related to https://github.com/bpmn-io/element-templates-json-schema/issues/9
[Docs](https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates)

**Comment by MaxTru** [comment]
Better implementation of this feature would be to do an entire json schema validation.

**Comment by pinussilvestrus** [comment]
This will be fixed by https://github.com/bpmn-io/bpmn-js-properties-panel/issues/386, when we integrate the new JSON Schema

**Comment by pinussilvestrus** [comment]
Also related to #2159

**Comment by pinussilvestrus** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/455
