### ISSUE TITLE
Resizing text annotations in DRD is not safed

### ISSUE THREAD

**Issue by andreas-liebelt** [camunda/camunda-modeler#1941]
__Describe the Bug__

When I add text annotations at decisions or input data in an DRD diagram and resize them, they are displayed with the default size when I restart camunda modeler.

__Steps to Reproduce__

1. Create e.g. Decision in DRD
2. Append TextAnnotation
3. Enter Text
4. Resize TextAnnotation
5. Restart camunda modeler
6. TextAnnotation has default size again

__Expected Behavior__

Changed size of TextAnnotaiton should be safed and shown after application restart.

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.0.0, 4.1.0, 4.2.0

**Comment by pinussilvestrus** [comment]
Thanks for reporting! I was able to reproduce it on macOS

![Kapture 2020-09-21 at 09 17 13](https://user-images.githubusercontent.com/9433996/93740686-4616b100-fbeb-11ea-9bb8-f64e3a99bb93.gif)

Note that, additionally to the bug you reported, the connection layout is broken.

**Comment by pinussilvestrus** [comment]
This error starts occurring with version v4.0.0.

**Comment by pinussilvestrus** [comment]
Closed via 23c40fd465a7b35af0fa608474c3638bee4c9755
