### ISSUE TITLE
XMLNS from DMN

### ISSUE THREAD

**Issue by SvenMetzler** [camunda/camunda-modeler#1944]
__Describe the Bug__

Before camunda modeler version  4.x (e.g. 3.6.0) the xmlns from dmns in the header was:
"http://www.omg.org/spec/DMN/20151101/dmn.xsd"
Here I saw the definition of the given xml.

Now the path is:
"https://www.omg.org/spec/DMN/20191111/MODEL/"
Which displays http 404 error.

In my opinion, i think it would be better to use something like:
"https://www.omg.org/spec/DMN/20191111/DMNDI13.xsd"

Is my opinion right or did I miss something important in the internal logic ?

__Steps to Reproduce__

1. Download the camunda-modeler version 3.6.0
2. Create a dmn
3. download the camunda-modeler version 4.x
4. open the dmn which you created
5. See the xmlns path before and after
6. If you want see the const in "camunda-modeler-4.2.0\client\node_modules\@bpmn-io\dmn-migrate\dist\index.esm.js"
`const DMN11URI = '"http://www.omg.org/spec/DMN/20151101/dmn.xsd"';`
`const DMN12URI = '"http://www.omg.org/spec/DMN/20180521/MODEL/"';`
`const DMN13URI = '"https://www.omg.org/spec/DMN/20191111/MODEL/"';`

__Expected Behavior__

I would like to have a valid xsd definition

__Environment__

- OS: [Windows 10]
- Camunda Modeler Version: [e.g. 3.6.0 -> 4.x]

**Comment by philippfromme** [comment]
The namespace URI does _not_ have to exist. It's the correct one. For more information and examples see https://www.omg.org/spec/DMN/About-DMN/.
