### ISSUE TITLE
Template Not Visible If Types Do Not Match Exactly

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#1947]
__Describe the Bug__

If the type of the selected element doesn't match one of the types specified in an element template's `appliesTo` field it won't show up in the catalog modal. Therefore, element templates with types like `bpmn:Activity` won't show up.

__Steps to Reproduce__

1. Add this element template:

```json
[
  {
    "name": "Foo",
    "id": "foo",
    "appliesTo": [
      "bpmn:Activity"
    ],
    "properties": []
  }
]
```
2. Select an activity
3. Open the catalog
4. Element template won't show up

__Expected Behavior__

The element template shows up.

__Environment__

- Camunda Modeler Version: Nightly (2020-09-30)

**Comment by pinussilvestrus** [comment]
Very good finding 👏
