### ISSUE TITLE
Adding github action for greeting and issue labeller

### ISSUE THREAD

**Issue by bislara** [camunda/camunda-modeler#1959]
__What should we do?__

Add issue labeller action to add relevant labels to the issues once created. 
Add GitHub action to greet a first-time contributor for an issue or a PR.

__Why should we do it?__
Adding labelled would help to understand whats the issue is about. 
Adding greeting action will encourage the first time contributors to contribute more and more

**Comment by nikku** [comment]
Just to better understand your request...

> Add issue labeller action to add relevant labels to the issues once created.

What labels are usually missing when people create an issue?

> Adding greeting action will encourage the first time contributors to contribute more and more

How does that help you as a first time contributor? What is a good example that inspired you / picked you up?

**Comment by bislara** [comment]
> What labels are usually missing when people create an issue?

Labels will be generated based on the content which is written in the issue description. like if its enhancement type, then labeller will add enhancement label, similarly for bug and other. 
We can mention the keywords on which a particular label will be added. ie, if the labeller finds that particular keyword in the description, then it will add the corresponding label mentioned by us. 

> How does that help you as a first-time contributor? What is a good example that inspired you / picked you up?

The message present in the greeting action (like congrats 🎉 on creating your first PR, etc) can cheer someone that his/her contribution is being acknowledged. Also, I am quite new to open source world, and contributing to wonderful projects like this, will definitely give me a boost to contribute more and more to open source.

**Comment by nikku** [comment]
(1) Relevant labels (bug, feature request, ...) are already added if you follow our _new issue_ path. (2) The welcome message would be a nice to have but has to be done right.

Closing this issue, as we won't act on (1). (2) sounds like a potential improvement and I'd be happy to hear your suggestions on what a welcoming message sounds like. If GitHub actions will be the way how to implement such thing is another question.
