### ISSUE TITLE
Enable shift+click for multi select

### ISSUE THREAD

**Issue by andreasgeier** [camunda/camunda-modeler#1964]
__Is your feature request related to a problem? Please describe.__

To quickly select several elements within a diagram, I would like to use shift+click as a common way and very known from many other tools.

Besides the reason to enable this as expected behavior, there is currently no way to select multiple elements that are not exactly side by side (to be catched by the lasso tool).

__Describe the solution you'd like__

Enable shift+click to select multiple elements in (bpmn, dmn) diagrams.

Related to https://github.com/bpmn-io/diagram-js/issues/471

**Comment by ingorichtsmeier** [comment]
This is available with ctrl+click (on windows 10, in BPMN diagrams).

**Comment by nikku** [comment]
`CTRL + click` is there for historical reasons (coming from Windows UX where `SHIFT+click` is usually range selection).

I propose supporting both, CTRL _or_ SHIFT + click to multi-select. draw.io does a similar thing and there is no reason not to do it.

**Comment by dlavrenuek** [comment]
I have added a PR in [diagram-js](https://github.com/bpmn-io/diagram-js) that implements this functionality: [PR](https://github.com/bpmn-io/diagram-js/pull/493). I guess for it to land in the modeler a new version of `diagram-js` needs to be released and updated in the `package.json` here.
It would also make sense to include the new version of `diagram-js` in https://github.com/bpmn-io/bpmn-js.

**Comment by dlavrenuek** [comment]
If I read the code correctly the `camunda-modeler` includes the `diagram-js` package but the modeler canvas is loaded from the `bpmn-js` library: 
- https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/bpmn/modeler/BpmnModeler.js#L11
- https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/index.js#L11

So the correct approach would be:
1. release a new version of `diagram-js`
2. include the new version in `bpmn-js`
3. release a new version in `bpmn-js`
4. include the new version in `camunda-modeler`

I can take on creating PRs for 2 and 4 if this would speed up the integration

**Comment by pinussilvestrus** [comment]
Thanks, @dlavrenuek for tackling this! You're right that making changes in diagram-js and integrating them into the Modeler takes a couple of releases. We usually do those with a Camunda Modeler release, and marking related Modeler issues with `fixes upstream` beforehand. Sometimes we do library releases earlier when needed (e.g. in case of bug fixes).

Let's focus on merging your PR and then we can see when we're going to release those changes.

**Comment by pinussilvestrus** [comment]
Fixed upstream via https://github.com/bpmn-io/diagram-js/pull/493
