### ISSUE TITLE
Intuitive handling of updated/changed/deleted element templates is implemented

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#1969]
> **This is an epic issue which may be broken down into multiple tasks, if needed**

__What should we do?__

This issue continues #1889.

It is based on the [Design Decisions](https://docs.google.com/presentation/d/1groCM-o4nUjtg5T-tVMCNy7YEHUaLy34yr53aYbZ_e4/edit?usp=sharing).

Depends on https://github.com/camunda/cloud-connect-modeler-plugin/issues/25

In order to let the user work with versioned element templates, we need to allow him to:
- [x] Show some version information regarding element templates
- [x] In the "apply" logic, include some version information (so that you can have an old version of a template applied, even if there is a new one)
- [x] Offer some "Update" button to start a migration to a new template version (if available)
- [x] Let the user "migrate" from an old version to a new version (see Design Decisions](https://docs.google.com/presentation/d/1groCM-o4nUjtg5T-tVMCNy7YEHUaLy34yr53aYbZ_e4/edit?usp=sharing). for explanation)
  - [x] Add and set the properties from the template which are set in the element but equal the default values of the old template
  - [x] Keep the current element properties which are set in the element and differ from the default value in the old template

(*note that these tasks might change based on kickoff / clarification of this issue*)

__Why should we do it?__

The user shall be able to work with versioned element templates.

**Comment by philippfromme** [comment]
Follow Up Activities:

* Update Element Templates Samples to Include Templates with Versions (https://github.com/camunda/camunda-modeler/issues/2033)
* Update Element Templates Documentation to Feature Versions (https://github.com/camunda/camunda-modeler/issues/2034)
* Update Release Checklist to Include Integration Tests for Cloud Connect Plugin (https://github.com/camunda/camunda-modeler/issues/2035)

**Comment by barmac** [comment]
> Follow Up Activities:
> 
> * Update Element Templates Samples to Include Templates with Versions (#2033)
> * Update Element Templates Documentation to Feature Versions (#2034)
> * Update Release Checklist to Include Integration Tests for Cloud Connect Plugin (#2035)

All of these are done so I'm closing this issue.
