### ISSUE TITLE
Diagram deployment via the modeler is tracked in ET

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1970]
__Is your feature request related to a problem? Please describe.__

We want to send events to ET every time the user deploys a diagram. This allows us to track the general usage of the deployment tool. In the future, we also want to gather further information about the deployed diagrams, e.g. the number of available process variables (cf. #1971). It helps us to understand what kind of diagrams our users are deploying to Camunda BPM from the Modeler.

__Describe the solution you'd like__

- [x] Before starting the implementation, make sure to align with E.T. team, process is described here: https://confluence.camunda.com/display/camBPM/ET+-+Easy+Telemetry
- [x] Create [event handler](https://github.com/camunda/camunda-modeler/tree/develop/client/src/plugins/usage-statistics/event-handlers) [according to definition](https://github.com/camunda/camunda-modeler/issues/1970#issuecomment-712166861)
- [x] Update [Telemetry docs](https://github.com/camunda/camunda-modeler/blob/develop/docs/telemetry/README.md) afterwards

__Describe alternatives you've considered__

/

__Additional context__

[Telemetry docs](https://github.com/camunda/camunda-modeler/blob/develop/docs/telemetry/README.md)

**Comment by pinussilvestrus** [comment]
**Example Deployment configuration**

````json
{
  "endpoint": {
    "url": "http://localhost:8080/engine-rest",
    "authType": "basic",
    "rememberCredentials": false,
    "id": "1pcrg8r"
  },
  "deployment": {
    "name": "diagram_1",
    "tenantId": "foo"
  }
}
````

++ BPMN / DMN XML File

**Example Engine Response**

```json
{
  "id": "513d299e-0d36-11eb-82d2-b2bc80b7051a",
  "deployedProcessDefinitions": {
    "Process_1mh744l:1:51442e80-0d36-11eb-82d2-b2bc80b7051a": {
      "id": "Process_1mh744l:1:51442e80-0d36-11eb-82d2-b2bc80b7051a",
      "key": "Process_1mh744l",
      "category": "http://bpmn.io/schema/bpmn",
      "description": null,
      "name": null,
      "version": 1,
      "resource": "diagram_1.bpmn",
      "deploymentId": "513d299e-0d36-11eb-82d2-b2bc80b7051a",
      "diagram": null,
      "suspended": false,
      "tenantId": "foo",
      "versionTag": null,
      "historyTimeToLive": null,
      "startableInTasklist": true
    }
  },
  "deployedProcessDefinition": {
    "id": "Process_1mh744l:1:51442e80-0d36-11eb-82d2-b2bc80b7051a",
    "key": "Process_1mh744l",
    "category": "http://bpmn.io/schema/bpmn",
    "description": null,
    "name": null,
    "version": 1,
    "resource": "diagram_1.bpmn",
    "deploymentId": "513d299e-0d36-11eb-82d2-b2bc80b7051a",
    "diagram": null,
    "suspended": false,
    "tenantId": "foo",
    "versionTag": null,
    "historyTimeToLive": null,
    "startableInTasklist": true
  }
}
```

**Comment by pinussilvestrus** [comment]
Example event to e.t.

```json
{
  "installation": "[THE_EDITOR_ID]",
  "product": {
    "name": "Camunda Modeler",
    "version": "[MODELER_VERISON]",
    "edition": "community",
    "internals": {
      "event": "deployment",
      "diagram-type": "bpmn",
      "outcome": "success",
      "diagram-metrics": {
         "process-variables-count": 10
     }
    }
  }
}
```

**Comment by pinussilvestrus** [comment]
Optionally we could add another field `isRun` to indicate a deployment triggered via the Run Instance tool.

**Comment by nikku** [comment]
> Optionally we could add another field isRun to indicate a deployment triggered via the Run Instance tool.

Alternatively: Simply track runs, too.

**Comment by pinussilvestrus** [comment]
Internal discussion:

> Volker pointed me to a valid topic yesterday in regards of the upcoming E.T. events. We should align our property names. E.g. in https://github.com/camunda/camunda-modeler/tree/develop/docs/telemetry#diagram-opened-event we already use different styles (camelCase, e.g. elementTemplateCount and not-camel-case, e.g. diagram-type). I think we can’t align existing events, since they are already out there. But we should definitely do it with the next events (deployment and co.).
I’d argue to use camelCase for all properties, since it’s already common in our code base, also the Optimize team seems to do the same.

Since camelCase is the preferred version, we should go for it as a consistent naming style. I'd also propose to make attributes explicit to make analysis clearer, therefore the event could look like

```json
{
  "installation": "[THE_EDITOR_ID]",
  "product": {
    "name": "Camunda Modeler",
    "version": "[MODELER_VERISON]",
    "edition": "community",
    "internals": {
      "event": "deployment",
      "deployment": {
         "diagramType": "bpmn",
         "outcome": "success",   
         "diagramMetrics": {
           "processVariablesCount": 10
         }  
       }
    }
  }
}
```

**Comment by pinussilvestrus** [comment]
**Decisions after meeting with @volkergersabeck and @MaxTru** (Goal shall be to make the events more aligned and keep the structure generic for future events)

* We will always use `camelCase` inside our events, therefore we will update the [diagram-open event](https://github.com/camunda/camunda-modeler/blob/develop/docs/telemetry/README.md#diagram-opened-event). It's okay that there are already events on E.T. with the other style
* We will keep generic attributes like `diagramType` and `diagramMetrics` inside the "root" (.internals), and cluster event related attributes, so e.g.

```json
"internals": {
      "event": "deployment",
      "diagramType": "bpmn",
      "deployment": {
        "outcome": "DIAGRAM_PARSE_ERROR",
        "isRun": true
      },
      "diagramMetrics": {
         "processVariablesCount": 0
      }
}
```
* We will align the "outcome" attribute to only have the values "success", "failure" (and "warning" in the future)
* We will store the error code in a dedicated attribute "error", the code should be enough for now, we could extend this in the future
* We will see whether it's easy to add the processVariableCount to the diagram opened event as well, if yes, we will go for it
