### ISSUE TITLE
No correct schema for camunda extension BPMN elements

### ISSUE THREAD

**Issue by kurtinaitis** [camunda/camunda-modeler#1972]
__Describe the Bug__

Saved BPMN file with camunda extension elements contains a camunda namespace declaration which does not have XSD schema. Or at least its schema is not provided in supporting libraries (camunda-engine.jar?).
`xmlns:camunda="http://camunda.org/schema/1.0/bpmn"`

__Steps to Reproduce__

1. Open Modeler.
2. Create a new BPMN diagram.
3. Select start event and enter '30' into field "History Time ToLive"
4. Save the diagram and open it with IntelliJ IDEA.
5. The file has attributes in schema, which is IDE is unable to find:
```
xmlns:camunda="http://camunda.org/schema/1.0/bpmn"
```

__Expected Behavior__

IDE is able to find the XML schema and support editing of such file by providing navigation, documentation and suggestions for attributes and elements in camunda extension schema.

__Environment__

- OS: linux mint 19.1
- Camunda Modeler Version: 4.2.0
- IntelliJ IDEA: 2020.2.3

**Comment by kurtinaitis** [comment]
I was able to find XSD files with other schema containing some of the used attibutes (activiti-bpmn-extensions-5.10.xsd):
```
targetNamespace="http://activiti.org/bpmn"
xmlns:tns="http://activiti.org/bpmn"
```
It is though other schema (http://activiti.org/bpmn). Should it be used by modeler instead of `http://camunda.org/schema/1.0/bpmn`?

**Comment by nikku** [comment]
You may find all extension elements that Camunda supports [here](https://docs.camunda.org/manual/7.14/reference/bpmn20/custom-extensions/). However, I believe we do not maintain a XSD file that would help you with the XML editor completion. 

Our general suggestion is to use the modeling tools provided for editing the XML. XSD validation will only get you so far, anyway.

**Comment by nikku** [comment]
Please turn to the [Camunda forum](https://forum.camunda.org/) to raise this feature request.

I'm closing this issue as it is a won't fix on our side. The Camunda Platform would need to provide that XSD and if it did we'd happily include it into the exported XML.

**Comment by kurtinaitis** [comment]
But maybe you should use `http://activiti.org/bpmn` instead of `http://camunda.org/schema/1.0/bpmn` in saved XMLs? Could you please check?
