### ISSUE TITLE
'mv' command not found when running npm run build on Windows 

### ISSUE THREAD

**Issue by processbionics** [camunda/camunda-modeler#1976]
__Describe the Bug__

When running "npm run build", the build process stops with an error "mv command not found"

__Steps to Reproduce__

1. clone the modeler repository: git clone https://github.com/camunda/camunda-modeler.git 
2. Change to the camunda-modeler folder
3. Run "npm run build"
4. The build fails with an error : mv command not found

__Expected Behavior__

npm build should end with 
Verifying <win> distributables

 - camunda-modeler-4.3.0-win-ia32.zip
     > verifying contents
     > ok
 - camunda-modeler-4.3.0-win-x64.zip
     > verifying contents
     > ok

SUCCESS

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.3.0

Workaround: create a file in the Windows\system32 folder called "mv.cmd", add the following line to the mv.cmd file: move %1 %2 %3

**Comment by philippfromme** [comment]
What command line are you using?

**Comment by Adithya-adi-Menon** [comment]
Can u assign this task to me

**Comment by nikku** [comment]
> Can u assign this task to me

We do not even know what the exact problem is. What do you plan to do?

**Comment by Adithya-adi-Menon** [comment]
The mv  error is fixed . Shall I give a pull request

**Comment by Adithya-adi-Menon** [comment]
Solved it needed to change the postbuild script form 'mv' to 'move' in windows .

**Comment by Adithya-adi-Menon** [comment]
I have  give given a pull request kindly review it

**Comment by nikku** [comment]
Let's not add fixes for windows CLI. Instead, please use a Posix shell, i.e. via WSL, git bash or whatever is embedded in your IDE. That will help you in other places as you use and develop our tools, too.
