### ISSUE TITLE
"Freeze Top Row" when editing a BPMN

### ISSUE THREAD

**Issue by lfbarreira** [camunda/camunda-modeler#1983]
Hi,

I'm a daily user of the modeler and I was wondering if the option to have a "Freeze Top Row" wouldn't make sense. Currently when editing a big table, we "get lost" due to the fact that we do not know on which column we are editing.

Is there already such feature? Is it on the pipeline?

Thank you.
BR.

**Comment by nikku** [comment]
First of all, thanks for your feature request. Second, could you please use our existing template when creating the request? That helps us to gather all the relevant information from you and process your request further.

I assume you ask for sticky decision table headers? https://github.com/bpmn-io/dmn-js/issues/269

**Comment by lfbarreira** [comment]
Thank you for the quick feedback and sorry for not using the template, I'll use it next time ;) 

About the sticky table headers it is exactly what I meant.

Thanks,
