### ISSUE TITLE
Allow backspace for element removal

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1989]
__Is your feature request related to a problem? Please describe.__

This is the one, simple available shortcut on MacOS, cf. https://github.com/bpmn-io/diagram-js/issues/475.

__Describe the solution you'd like__

Do it, mirror https://github.com/bpmn-io/diagram-js/issues/475.

__Describe alternatives you've considered__

Keep things as is.

__Additional context__

We should aim to mirror our core modeling experience (https://github.com/bpmn-io/diagram-js/issues/475) where possible, this is why this feature exists. Additional work (i.e. native menu shortcuts) may need to be carried out to bring this into the App.

**Comment by nikku** [comment]
We need to double check on MacOS if that is needed, if so the right place to fix things is [here](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/getEditMenu.js#L198).

**Comment by pinussilvestrus** [comment]
This could be tough since electron currently don't support multiple accelerators for the same menu entry: https://github.com/electron/electron/issues/5256

**Comment by pinussilvestrus** [comment]
Alternative: setting one entry to invisible

```js
menuEntries.push({
      label: 'Remove Selected',
      accelerator: 'Delete',
      enabled: removeSelected,
      action: 'removeSelection',
      role: inputActive && 'delete'
});

menuEntries.push({
      visible: false,
      accelerator: 'Backspace',
      enabled: removeSelected,
      action: 'removeSelection',
      role: inputActive && 'delete'
});
```

**Comment by nikku** [comment]
I imagine the solution would be https://github.com/electron/electron/issues/5256#issuecomment-213559148.

So probably something along those lines:

* Make the most standard shortcut (i.e. `DELETE` on MacOS and `Backspace` on other systems) the menu shortcut
* Make the other shortcut available via the browser view (listen to it and react accordingly)

**Comment by pinussilvestrus** [comment]
> Make the most standard shortcut (i.e. DELETE on MacOS and Backspace on other systems) the menu shortcut

isn't it the other way around? Backspace on MacOS and Delete on other systems?

**Comment by nikku** [comment]
> isn't it the other way around? Backspace on MacOS and Delete on other systems?

On my German keyboard it is `Entf` to delete, `<-` usually does nothing. Not sure if that clarifies things.

**Comment by nikku** [comment]
Updated my previous comment accordingly.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/268160485ecbc819911197625d921985799ca17b
