### ISSUE TITLE
Deployment tool sometimes throws TypeError: Cannot read property 'endpoint' of undefined

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1991]
__Describe the Bug__

Sentry Issue: [CAMUNDA-MODELER-6S](https://sentry.io/organizations/camunda-modeling/issues/1783612995/?referrer=github_integration)

```
TypeError: Cannot read property 'endpoint' of undefined
  at Object.removeCredentials (./src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js:232:25)
```

__Steps to Reproduce__

This has to be investigated. I suspect that it might happen for specific saved configuration.

__Expected Behavior__

No errors.

__Environment__

See linked sentry issue.

**Comment by pinussilvestrus** [comment]
I was able to reproduce it with the following steps

1. Create new diagram (no deployment config saved so far)
2. Open deploy dialog
3. Immediately close it
4. Error pops up in Console

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/46d99c200ada4935f1ef907cace6bda26a400305
