### ISSUE TITLE
Custom property-panel does not work in 4.3 any more

### ISSUE THREAD

**Issue by hrzwkstim01** [camunda/camunda-modeler#1992]
__Describe the Bug__

Plugins, which add custom tabs or groups to the properties panel is no longer possible.
The getTabs method of plugins is no longer called in version 4.3. 

I created an example repo for a plugin, the getTabs method of which is called in version 4.1.1, but not in 4.3.
I have not tested if it works in 4.2.

__Steps to Reproduce__

1. Get this example repo: https://github.com/hrzwkstim01/camunda-modeler-4.3-property-panel-test (extended from 'camunda-modeler-plugin-example')
2. Use generated plugin in modeler v4.1.1. There you can see a console.log
3. Use generated plugin in modeler v4.3. There you can not see a console.log

__Expected Behavior__

The console.log should also be visible in the latest version of the modeler.

__Environment__

- OS: [Windows 10]
- Camunda Modeler Version: [4.3]

---

Depends on https://github.com/camunda/camunda-modeler/issues/2133

**Comment by pinussilvestrus** [comment]
We changed the interface of the CamundaPropertiesProvider, cf. https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/CHANGELOG.md#breaking-changes-1

Make sure you adjust it when you extend it: https://github.com/hrzwkstim01/camunda-modeler-4.3-property-panel-test/blob/main/client/bpmn-js-extension/ExampleExtensionService.js#L3

We did similar here in the Modeler itself: https://github.com/camunda/camunda-modeler/commit/538682ab07faa3d50d691b3dd74b64d973bae551

**Comment by pinussilvestrus** [comment]
That should do the trick. Feel free to re-open if that's not the case.

**Comment by hrzwkstim01** [comment]
@pinussilvestrus 
Thanks for you answer. 
I already recognized that the interface changed, so I used the same constructor which is used by the modeler.
Take a look at https://github.com/hrzwkstim01/camunda-modeler-4.3-property-panel-test/blob/main/client/bpmn-js-extension/ExampleExtensionService.js

Still it does not seem to work

**Comment by pinussilvestrus** [comment]
Seems to be also an issue with other existing plugins, e.g. https://github.com/camunda/camunda-modeler-process-io-specification-plugin

**Comment by pinussilvestrus** [comment]
Thanks for reporting anyway!

**Comment by pinussilvestrus** [comment]
This seems to be a problem with multiple properties provider: https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/element-templates-modal/modeler/index.js#L20

We will have a look.

**Comment by hrzwkstim01** [comment]
@pinussilvestrus @nikku 
Some updates on this topic?

**Comment by nikku** [comment]
We will restore the ability to customize properties panels in the future. We cannot give you a concrete estimate yet.

Could you elaborate _how_ you use the extension? Do you experiment with the API? Do you have an extension deployed, i.e. in production right now?

**Comment by hrzwkstim01** [comment]
Currently, we are developing a custom property panel to the tabs for our needs.
We plan to get productive this month and to extend more tabs/groups in future. 
 
As this extension is not supported any more, we are currently working with version 4.1.1, which prevents us to stay up-to-date with you guys and getting required features, for instance auto complete for expressions.
Additionally, working with an old version of the modeler, will lead to an extensive effort of integration once this feature gets live again.

**Comment by iskn90** [comment]
We faced the same issue, using v4.1.1 at the moment but it may reqire more work in future, is there a progress on the issue? Kind regards.

**Comment by nikku** [comment]
@iskn90 Could you elaborate on your setup and usage of the API, too? It helps us to better understand the impact of this issue for you.

**Comment by pinussilvestrus** [comment]
Hi @hrzwkstim01,

we pushed a fix recently (https://github.com/camunda/camunda-modeler/pull/2145) to make it possible to create multiple properties providers. That should make all those plugins working again with the next nightly + release.

However, from now on we suggest using the new `propertiesPanel.registerProvider` API instead of simply overriding the `propertiesProvider` module. You can see [this example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension) for some guidance. 

Feel free to reach-out if you have further questions 👍
