### ISSUE TITLE
Add fallback for displaying date in catalog

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#1995]
__Is your feature request related to a problem? Please describe.__

The Cawemo team is going to remove the `updated` property from the metadata property of templates. This will break the catalog unless we change the current implementation.

__Describe the solution you'd like__

My suggestion is to fall back to the `created` property if there is no `updated` property so we always display a date.

__Describe alternatives you've considered__

Always use the `created` property to display dates.

__Additional context__

Current implementation: https://github.com/camunda/camunda-modeler/blob/v4.3.0/client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.js#L417

**Comment by pinussilvestrus** [comment]
Closed via d796cd6d4e54b412aeeff73178a4ef301a243dc8 (correct me if I am wrong)
