### ISSUE TITLE
I can run the App on ARM based Macs

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1996]
__Is your feature request related to a problem? Please describe.__

Apple is going to release new ARM-based Mac books this fall. To my knowledge we do not ship ARM-based binaries for the Camunda Modeler yet.

__Describe the solution you'd like__

Be able to run the modeler on ARM as well as intel based architectures.

__Describe alternatives you've considered__

Ignore ARM as _too brand new_.

__Additional context__

This may be blocked by https://github.com/electron-userland/electron-builder/issues/5095, as electron builder does not build Mac binaries for ARM yet.

**Comment by nikku** [comment]
First Mac hardware with ARM `M1` based CPUs to be available in the next weeks.

**Comment by SiegfredRodriguez** [comment]
Anything on native Apple Silicon support?

**Comment by NuiceT** [comment]
When building from source, it generates a dmg for Apple Silicon. Works great.

**Comment by thoene** [comment]
> When building from source, it generates a dmg for Apple Silicon. Works great.

Hi Leon, could you please provide me the dmg you created for Apple Silicon?

**Comment by huksley** [comment]
@nikku Would be great if official releases support Apple Silion and does not require Rosetta.

**Comment by barmac** [comment]
Perhaps we could tackle this together with electron-forge trial.
