### ISSUE TITLE
Simplify appending expanded sub-processes

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2004]
__Is your feature request related to a problem? Please describe.__

When building a BPMN diagram, sometimes during the design phase I'd like to append an expanded sub-process directly from the current element. I'd even argue that, in the automation context, this is the more prominent action than appending a collapsed sub-process.

Right now though, this interaction is poorly supported. I.e. it takes an incredible amount of effort to get this done, even on an empty canvas:

![capture QwPa8Y_optimized](https://user-images.githubusercontent.com/58601/98352930-f0715900-201e-11eb-9172-6494d816ff53.gif)

__Describe the solution you'd like__

It should be easy to append an expanded sub-process right from the currently selected flow element.

* Update the append menu to allow appending an expanded sub-process _or_
* Update the replace menu to allow replacing a task to an expanded sub-process

__Describe alternatives you've considered__

As mentioned above, there is a few options.

__Additional context__

This is related to https://github.com/camunda/camunda-modeler/issues/1244, i.e. the fact that replacing a task  with a sub-process (after it has been placed) results in unnecessary noise on the diagram. :arrow_right: It may be better to support appending the sub-process right away.

**Comment by philippfromme** [comment]
I've investigated this issue and there is one major roadblock making this a bit more effort to implement. The `Modeling#appendShape` API doesn't support multiple elements at the moment the way the `Create` feature does. Thus, appending a subprocess with a start event isn't as easy as adding the respective context pad entry.

**Comment by nikku** [comment]
Will be solved via [create/append anything](https://github.com/bpmn-io/bpmn-js/issues/1627):

![capture qpon4Z_optimized](https://user-images.githubusercontent.com/58601/168652212-b11fae4e-e138-4537-90fc-ecdee629cf23.gif)

**Comment by nikku** [comment]
Fully supported with create/append anything in bpmn-js@13+:

![capture byijla_optimized](https://github.com/camunda/camunda-modeler/assets/58601/3593bd8e-bf69-43f0-89b9-e505ede70e88)
