### ISSUE TITLE
Update element template documentation to feature JSON schema

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2008]
__What should we do?__

Update documentation in various places to add a `$schema` property that hooks up the newly created [JSON schema](https://github.com/camunda/element-templates-json-schema):

* https://docs.camunda.org/manual/7.14/modeler/element-templates/
* https://github.com/camunda/camunda-modeler/tree/develop/docs/element-templates

__Why should we do it?__

The schema property allows editors to provide editor assistance.

**Comment by pinussilvestrus** [comment]
> https://docs.camunda.org/manual/7.14/modeler/element-templates/

Will we still do that or is this closed by #2102 ?

**Comment by MaxTru** [comment]
IMO this can be closed since https://docs.camunda.org/manual/7.14/modeler/element-templates/ refers to the updated documentation.

**Comment by pinussilvestrus** [comment]
👍
