### ISSUE TITLE
Create a menu option for "Check for updates"

### ISSUE THREAD

**Issue by Camunda-ChrisAllen** [camunda/camunda-modeler#2010]
__Is your feature request related to a problem? Please describe.__

A user might or might not have the privacy option for auto-checks to happen in the background.  But they might want to check manually without having to go to camunda.com

__Describe the solution you'd like__

A "Check for Updates" action available directly under the Help menu that would trigger the check immediately.

__Describe alternatives you've considered__

Perhaps under "File" instead??

__Additional context__

(thanks)

**Comment by pinussilvestrus** [comment]
Is it okay from a data privacy perspective to send the update-check request via manual step, although the privacy option is not set in the preferences? It's still a network request to a third-party-provider.

![image](https://user-images.githubusercontent.com/9433996/105148508-c0583300-5b02-11eb-8828-d9e319cee37c.png)

**Comment by nikku** [comment]
I believe so, as it is done given your one time consent :arrow_right: you called it.

**Comment by pinussilvestrus** [comment]
How it looks like in other Apps for macOS

VS Code

![image](https://user-images.githubusercontent.com/9433996/105179141-3a031780-5b29-11eb-8051-e1951d7fa202.png)

Zoom

![image](https://user-images.githubusercontent.com/9433996/105179368-8e0dfc00-5b29-11eb-8ead-aeecb8cce0c8.png)

IntelliJ

![image](https://user-images.githubusercontent.com/9433996/105179426-a251f900-5b29-11eb-95ea-b7efb1ed311d.png)

----

on Windows it's likely inside the "Help" menu.

**Comment by nikku** [comment]
`Help` menu it is, on Windows and Linux, indeed!
