### ISSUE TITLE
Input/output tab disappears when using element template

### ISSUE THREAD

**Issue by szerie** [camunda/camunda-modeler#2011]
__Describe the Bug__

Input/output parameters tab disappears in Camunda Modeler 4.4.0 after applying element template even if entriesVisible _all is set to true.

__Steps to Reproduce__

1. Create element template, for example:
```
[
    {
      "name": "Test task",
      "id": "TestTask",
      "appliesTo": [
        "bpmn:ServiceTask"
      ],
      "properties": [
        {
          "type": "Hidden",
          "value": "test",
          "binding": {
            "type": "camunda:inputParameter",
            "name": "TestInputParameter"
          }
        }           
      ],
      "entriesVisible": {
        "_all": true
      }
    }
]
```

2. Apply newly created template on service task.
3. Input/output parameters tab disappears.

The expected behavior is that if element template contains entriesVisible _all set to true then Input/output tab is visible after applying template to task. It is working correctly on version 4.2.0 but not on 4.4.0.

Result on Camunda Modeler 4.2.0:
![CamundaModeler42](https://user-images.githubusercontent.com/57395064/98903604-411e0180-24b8-11eb-8080-fd4dc83cd673.PNG)

Result on Camunda Modeler 4.4.0:
![CamundaModeler44](https://user-images.githubusercontent.com/57395064/98903606-41b69800-24b8-11eb-98ec-f0bf5137d340.PNG)

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.4.0

**Comment by nikku** [comment]
I can reproduce your issue.

**Comment by philippfromme** [comment]
Closing this as it is the same issue as https://github.com/camunda/camunda-modeler/issues/2018.
