### ISSUE TITLE
Improve the display and visibility of a configured element template

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2014]
__Is your feature request related to a problem? Please describe.__

Whether or not an element template is selected is currently indicated in the template tab:

<img src="https://user-images.githubusercontent.com/58601/98947755-e4413c00-24f5-11eb-875b-5a92680f76d5.png" width=40%>

This works, as long as the `Template` tab is the only tab but breaks as soon as more than one tab are shown. This is the case with the `entriesVisible` property that we restored in `v4.4.0` of the app (cf. https://github.com/camunda/camunda-modeler/issues/2011). It can also be the case if plug-ins provide additional tabs.

__Describe the solution you'd like__

My expectation is that the fact that an element template is selected is something general enough to be featured in the properties panel header, along with the ability to unlink (or remove) the template:

<img src="https://user-images.githubusercontent.com/58601/98948439-b90b1c80-24f6-11eb-849b-ef5c9f994787.png" width=40%> <img src="https://user-images.githubusercontent.com/58601/98949268-c543a980-24f7-11eb-8c7e-fdddf1075b4e.png" width=40%>

I see a number of benefits in this approach:

* We can drop the `Template` tab again and bring back the `General` tab and `General` section for elements with element templates applied. This way users have a consistent UX with and without templates applied
* We support the existing `entriesVisible` behavior out of the box, no hacks needed

__Describe alternatives you've considered__

Keep things as is.

__Additional context__

None.

----

Related to https://github.com/camunda/camunda-modeler/issues/2011

**Comment by pinussilvestrus** [comment]
Just for my understanding: would information like the template description (in the screenshot named "foo"), metadata regarding last modified, and the Template Input / Output Parameters groups also go inside the General Tab?

![image](https://user-images.githubusercontent.com/9433996/98972321-8ff88500-2512-11eb-82b1-79569cf98155.png)

**Comment by nikku** [comment]
Good point regarding the description in the RPA case. I looked at it from the non-RPA perspective where I saw an entirely different UI (see screenshots above). 

I guess it would makes sense to update [our example templates](https://github.com/camunda/camunda-modeler/tree/develop/resources/element-templates) to add RPA / catalog item specific ones that feature the newly created elements. Could you provide me with an RPA template example that is the basis for your screenshots?

At least the template description should have a high priority. So yea, I guess I'd put it on top of the existing items in the general tab, i.e. into a dedicated `template` section (or similar).

**Comment by pinussilvestrus** [comment]
I used this example template, coming from Cawemo (I removed some unrelated ids for referencing in Cawemo):

<details>
<summary>Collapse to see full JSON</summary>
```js
{
  "appliesTo": [
    "bpmn:ServiceTask"
  ],
  "description": "foo",
  "id": "ExampleTemplate",
  "metadata": {
    "created": 1601556562335,
    "tags": [
      "Niklas' Templates"
    ],
    "updated": 1604937555882
  },
  "name": "New RPA template",
  "properties": [
    {
      "binding": {
        "name": "name",
        "type": "property"
      },
      "type": "Hidden",
      "value": "MyBot"
    },
    {
      "binding": {
        "name": "bot",
        "type": "camunda:property"
      },
      "editable": false,
      "label": "UiPath Package Name",
      "type": "String",
      "value": "foo"
    },
    {
      "binding": {
        "name": "foo",
        "type": "camunda:inputParameter"
      },
      "description": "<Description of the IN argument, e.g. expected format of the value>",
      "label": "foo",
      "value": "${foo}"
    },
    {
      "binding": {
        "source": "${bar}",
        "type": "camunda:outputParameter"
      },
      "description": "<Description of the OUT argument, e.g. format of the returned value>",
      "label": "bar",
      "value": "bar"
    },
    {
      "binding": {
        "name": "camunda:type",
        "type": "property"
      },
      "type": "Hidden",
      "value": "external"
    },
    {
      "binding": {
        "name": "camunda:topic",
        "type": "property"
      },
      "type": "Hidden",
      "value": "uipath"
    },
    {
      "binding": {
        "name": "camunda:asyncAfter",
        "type": "property"
      },
      "type": "Hidden",
      "value": "true"
    }
  ]
}
```
</details>

**Comment by andreasgeier** [comment]
The reasons why we decided to have a template tab were:
* from UX perspective: the general tab is already cluttered (general, details, async, docu ...) and the (possible) complex RPA templates would just add to that and might even be overseen or mainly out of the viewport
* from tech perspective: it was decided to not allow access to other tabs/properties for RPA templates (@MaxTru @philippfromme can provide context) so an extra tab is a clean cut

**Comment by nikku** [comment]
This is being taken care of some day, maybe, as we roll out a new properties panel.
