### ISSUE TITLE
Literal Expression Styles Broken

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2019]
__Describe the Bug__

A literal expression might overflow its container.

![image](https://user-images.githubusercontent.com/7633572/99083485-ea065280-25c5-11eb-98d5-ba4c175ceb03.png)

__Environment__

- Camunda Modeler Version: v4.4.0

**Comment by MaxTru** [comment]
Closed with https://github.com/camunda/camunda-modeler/pull/2041
