### ISSUE TITLE
Pool collapsing leads to undesired behavior

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2022]
__Is your feature request related to a problem? Please describe.__

It's defined by the BPMN 2.0 specification that a pools content got erased once collapsing it. That leads to surprises to our users (cf. https://github.com/camunda/camunda-modeler/issues/712).

As a quick fix for the undesired behavior that a pool's content got lost after collapsing it, we should prevent the user to execute this action first hand (cf. https://github.com/camunda/camunda-modeler/issues/712#issuecomment-662419940, https://github.com/camunda/camunda-modeler/issues/712#issuecomment-732733559).

__Describe the solution you'd like__

Remove the action when the pool has content.

![image](https://user-images.githubusercontent.com/9433996/100104139-193e7e80-2e66-11eb-9b70-0d39481d9d7f.png)

We did a similar approach with sub-processes (cf. https://github.com/camunda/camunda-modeler/issues/1486).

__Describe alternatives you've considered__

Instead of simply preventing it, we could make the action hidden / inactive and add a hint regarding the rationale. This would make the changes and its rationale more explicit. If we decide on this, we should align the pattern for sub-processes as well.

Another alternative: make action clearer, cf. https://github.com/camunda/camunda-modeler/issues/2022#issuecomment-735725203

__Additional context__

Related to https://github.com/camunda/camunda-modeler/issues/712
Related to https://github.com/camunda/camunda-modeler/issues/1486
Related to https://github.com/bpmn-io/bpmn-js-disable-collapsed-subprocess

**Comment by pinussilvestrus** [comment]
Aspect to consider: How is _content_ defined? Is a Pool with two empty lanes also _empty_ or is the existence of the lanes itself defined as _content_?

![image](https://user-images.githubusercontent.com/9433996/100214726-83136280-2f10-11eb-8314-6866bec6641b.png)

**Comment by pinussilvestrus** [comment]
Codesandbox containing several options: https://codesandbox.io/s/pool-collapsing-wkc21?file=/src/index.js

**Comment by ingorichtsmeier** [comment]
When we do a BPMN training, it belongs to the exercises to model collapsed pools.

You should not be too restrictive with this feature.

I personally would like to see the original issue solved: https://github.com/camunda/camunda-modeler/issues/509#issuecomment-349950871

**Comment by pinussilvestrus** [comment]
**Kick off 30-11-2020 (Summary)**

Participants: @azeghers, @andreasgeier, @barmac, @pinussilvestrus 

## 1 - Discussed [available variants](https://wkc21.csb.app/)
* A - Removing the action completely

![image](https://user-images.githubusercontent.com/9433996/100603261-1d0a4f00-3305-11eb-9bbf-521b1a72c802.png)

* B - Disabling the action with clearer label + title tooltip

![Kapture 2020-11-30 at 12 12 36](https://user-images.githubusercontent.com/9433996/100603507-7bcfc880-3305-11eb-8406-39ea37b44f0d.gif)

* C - Disabling the action with clearer label + popup tooltip

![Kapture 2020-11-30 at 12 13 27](https://user-images.githubusercontent.com/9433996/100603510-7e322280-3305-11eb-8009-244ed8c92703.gif)

* D - Disabling the action with an even clearer label (two lines)

![image](https://user-images.githubusercontent.com/9433996/100603528-87bb8a80-3305-11eb-8f84-a9c249b57eff.png)

* E - Allowing the action, but change the label to what it is from specification --> _Not_ a collapsed pool, but _replacing_ it with an empty/black box pool which will remove the contents

![image](https://user-images.githubusercontent.com/9433996/100603573-973ad380-3305-11eb-8e08-8d823a7fde49.png)

### ---> Generally, the audience appreciated option _E_ the most 
... because currently, the toolkit is making wrong indications
* There is no _collapsed pool_ from the BPMN perspective (cf. BPMN 2.0 specification page 24)

![image](https://user-images.githubusercontent.com/9433996/100603726-cf421680-3305-11eb-9f68-6f56a6dc5759.png)

* Indeed the action is replacing it to a pool without referenced process
* Why not making it explicit? "Black box" or "empty"
--> [No surprises](https://github.com/bpmn-io/design-principles#no-surprises)
--> [Empower the user](https://github.com/bpmn-io/design-principles#empower-the-user)
* Maybe it has historic reasons due to similarities to other container elements

## 2 - Plugin or Core feature

* Depending on the solution we will end up with
* Generally the term is BPMN specific, so we should fix it inside bpmn-js directly
* If we go for disabled action: maybe offering a migration path to re-allow it (cf. https://github.com/bpmn-io/bpmn-js-collapse-subprocess)

## 3 - Align with sub process behavior

* Currently, we have a mix of option A (remove action) and E (allow but clear indication) for sub processes

![image](https://user-images.githubusercontent.com/9433996/100602931-cf8de200-3304-11eb-9d38-c3a22358b8e5.png)

![image](https://user-images.githubusercontent.com/9433996/100603007-e16f8500-3304-11eb-8790-45decc932a8d.png)

* Aligning with the pool collapsing makes a lot of sense but could be hard because the sub process behavior is a conflict in itself
* Depends on the solution

--------

## Action Items

* [ ] Create two new variants out of (B|C|D) and E and consult the rest of the team.

**Comment by pinussilvestrus** [comment]
### Wrap up usability tests

Prototype: https://github.com/pinussilvestrus/pool-collapse-test
Notes: https://github.com/pinussilvestrus/pool-collapse-test/blob/master/docs/summary.md

Findings
* Disabling the collapse action when the pool has content is not an option --> destructive
* Users wanted to model on instead of being blocked and removing the elements manually
* The hint "removes content" in the label was really appreciated
  * Alternative was mentioned: "removes content, irreversible"
* "Black Box" was appreciated, it follows the standard
* "Empty Pool (removes content)" was the favorite in the tests, alternatives were mentioned
  * "Empty Black Box (removes content)"
  * "Collapsed Pool (removes content)" (for historic reasons)
* When pool has _no contents_ the users expected the hint "removes content" to not appear
* All users would expect to keep the message flows when the pool got replaces with empty, cf. https://github.com/camunda/camunda-modeler/issues/1651
* All users would still see saving the contents for later re-expanding, cf. https://github.com/camunda/camunda-modeler/issues/712, but admit there is no easy solution
* All users admit that the option with a better, declarative label would be a really good improvement to prevent surprises

----------------

Proposal to solve this issue

* [ ] Change label of action to "Empty Pool (removes content)" when pool has content
  * [ ] Alternative: "Black Box (removes content)"
* [ ] Change label of action to "Empty Pool" when pool has no content
   * [ ] Alternative: "Black Box"
* [ ] Consider fixing https://github.com/camunda/camunda-modeler/issues/1651 to fix the situation even better

**Comment by pinussilvestrus** [comment]
@camunda/modeling-dev  Regarding the message flows topic, I created a solution sketch on how to handle this problem: https://github.com/bpmn-io/bpmn-js/compare/develop...keep-message-flows

Still, it has problems due to moving pool boundaries, which might be able to fix if we add the replaced connections in another place (cf. https://github.com/bpmn-io/bpmn-js/issues/1265)

![Kapture 2020-12-07 at 10 02 57](https://user-images.githubusercontent.com/9433996/101330849-67df1600-3873-11eb-84cd-a90433d69299.gif)

**Comment by ingorichtsmeier** [comment]
This looks promising...

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2040.
