### ISSUE TITLE
Boundary Cancel Event

### ISSUE THREAD

**Issue by richerzhagen1978** [camunda/camunda-modeler#2026]
__Describe the Bug__

Currently it is possible to attach a boundary cancalation event to any activity, but the spec does not allow that. On Page 263 the spec says: "The catch Cancel Intermediate Event MUST only be attached to the boundary of a **Transaction SubProcess** and, thus, MAY NOT be used in normal flow."

__Expected Behavior__

The Cancel event should not be available anywhere but in the scope of a transaction sub process.

**Comment by MaxTru** [comment]
Dear @richerzhagen1978 ,

thanks a lot for spotting, confirming and reporting this issue!

I can reproduce this and also understand the spec on page 263 that way. Moving the issue to backlog. This might be a "good first issue"

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2057
