### ISSUE TITLE
exporterVersion is set to "3.0.0-dev" initially

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2030]
__Describe the Bug__

When creating a new diagram, the exporterVersion attribute of the `bpmn:definitions ` element is set to `3.0.0-dev` in the dev. The filed is then correctly updated once there was a change done and saved.
IMO the display of the version `3.0.0-dev` is not a consistent behavior, it should directly be the correct version (ie. the version of the Modeler being used).

Still I recognize this is a minor issue.

__Steps to Reproduce__

1. Create a new BPMN diagram
2. View the XML

__Expected Behavior__

exporterVersion is set to the version of the Camunda Modeler (e.g., `4.4.0` )

__Environment__

- OS: Mac and Arch Linux
- Camunda Modeler Version: 4.4.0

**Comment by marstamm** [comment]
Was already fixed with https://github.com/camunda/camunda-modeler/pull/2123, see the discussion linked above: https://github.com/camunda/camunda-modeler/pull/2123/files#r586246227
