### ISSUE TITLE
Update Element Templates Samples to Include Templates with Versions

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2033]
__What should we do?__

Add a couple of examples of element templates with versions.

Example:

```json
[
  {
    "id": "foo",
    "version": 1,
    "appliesTo": [ "bpmn:Task" ],
    "properties": []
  },
  {
    "id": "foo",
    "version": 2,
    "appliesTo": [ "bpmn:Task" ],
    "properties": []
  }
]
```

---

Related to https://github.com/camunda/camunda-modeler/pull/2025.

Child of #1969.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2043
