### ISSUE TITLE
Update Element Templates Documentation to Feature Versions

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2034]
__What should we do?__

Document element template versions and the rules by which element templates are updated to a new version.

----

Related to https://github.com/camunda/camunda-modeler/pull/2025
Child of https://github.com/camunda/camunda-modeler/issues/1969

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2044
