### ISSUE TITLE
Update Release Checklist to Include Integration Tests for Cloud Connect Plugin

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2035]
__What should we do?__

We generally do not test Camunda Modeler releases against plugins but since we own the Cloud Connect Plugin which must be guaranteed to work we should update the release checklist to include integration tests for this combination.

----

Child of https://github.com/camunda/camunda-modeler/issues/1969

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2045
