### ISSUE TITLE
Disable CMMN using feature toggle per default

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2036]
__What should we do?__

Disable CMMN Diagrams per default in the Camunda Modeler via feature-toggle. It shall still be possible to enable it using the feature-toggle.

__Why should we do it?__

We don't promote the usage anymore.

**Comment by ingorichtsmeier** [comment]
Hi @MaxTru, from my understanding it is still supported and maintained. (at least for our enterprise customers)

But there will no further improvements happen.

Disabling CMMN at all may cause exisiting projects that they could not upgrade the modeler any more.

**Comment by nikku** [comment]
@ingorichtsmeier Thanks for your feedback. We'll deal with these cases on a case-by-case basis.

CMMN won't be gone, it will still be available behind a feature toggle and you can enable it again.

**Comment by MaxTru** [comment]
Hi @ingorichtsmeier ,

thanks. I clarified the issue text to make clearer that it will still be possible to use DMN, the feature-toggle which would enable/disable CMMN diagrams in the Modeler would just be set to `false` per default. I also added the rationale to make clear that we do this so to not "promote" it.

Feel free to reach out in case of questions.

Thanks

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2037.

**Comment by ingorichtsmeier** [comment]
I think there is a need to explain the use of this feature toggle as some users still want to use CMMN: https://forum.camunda.org/t/how-to-access-cmmn-in-the-modeler/25127

**Comment by nikku** [comment]
Thanks for your feedback, we will have a look.
