### ISSUE TITLE
Two or more pools that have equal Process Id (Process Def Key) should throw a error

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#2047]
If you how two or more pools that have equal `Process Id`'s should throw a error similar to show multiple `id` fields that are equal will throw an error.

---

__Describe the Bug__

If you how two or more pools that have equal `Process Id`'s should throw a error similar to show multiple `id` fields that are equal will throw an error.

__Steps to Reproduce__

1. Add two pools
2. set the process Ids of each pool to be the same

__Expected Behavior__

There should be a error shown

__Environment__

latest of camunda modeler 4.5

**Comment by StephenOTT** [comment]
The lack of error would likely provide unexpected results with moddle-bpmn as the `elementsById` property is a K/V of ID/Object.  The `Process Id` is one of those "unique" property keys.

**Comment by nikku** [comment]
Could you use our existing issue template and establish the relevant context? Maybe share a screenshot of which part of the app you refer to? Maybe share an example diagram?

We cannot act upon this issue otherwise.

**Comment by StephenOTT** [comment]
@nikku  updated..

**Comment by Skaiir** [comment]
This bug no longer exists as of 5.0.0. Feel free to re-open if I'm missing something. 

![electron_JRZam1pUbc](https://user-images.githubusercontent.com/17801113/168589685-3bb96374-32ac-4ace-aa74-b92e3a267175.gif)
