### ISSUE TITLE
Use Ctrl+Cmd+F as full screen shortcut on MacOS

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2050]
__Is your feature request related to a problem? Please describe.__

I tried today to go full screen using a common shortcut `Ctrl+Cmd+F` (e.g. in Google Chrome, Finder, MS Edge). Unfortunately, it doesn't work in Camunda Modeler. As a side note, `F11` doesn't help either but it might be related to my machine.

__Describe the solution you'd like__

Use Ctrl+Cmd+F as full screen shortcut on MacOS

__Describe alternatives you've considered__

Leave it as it is.

__Additional context__

Nay.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2069
