### ISSUE TITLE
DMN - Annotation flow disappears after renaming decision in table editor

### ISSUE THREAD

**Issue by azeghers** [camunda/camunda-modeler#2052]
__Describe the Bug__

https://user-images.githubusercontent.com/42282939/103775573-83823b80-502e-11eb-982d-09da31707966.mp4

Here are the logs after saving and reopening the diagram:

![image](https://user-images.githubusercontent.com/42282939/103775727-c3e1b980-502e-11eb-9c36-d41078085065.png)

__Steps to Reproduce__

-Create Decision
-Name it
-Add Annotation
-Morph into Decision Table
-Rename inside of Decision Table mode
-Go back to DRD
-See that the Annotation is unlinked

__Expected Behavior__

The annotation stays linked to the decision element

__Environment__

- OS: Ubuntu 20.04
- Camunda Modeler Version: v4.5.0-rc.0

---

Related to https://github.com/camunda/camunda-modeler/issues/1874

**Comment by barmac** [comment]
Related to https://github.com/camunda/camunda-modeler/issues/1814 and https://github.com/camunda/camunda-modeler/issues/1763

I can also reproduce that in 4.4.0

**Comment by pinussilvestrus** [comment]
Related to https://github.com/camunda/camunda-modeler/issues/1874.

**Comment by philippfromme** [comment]
This was fixed before (https://github.com/bpmn-io/dmn-js/issues/397) but still seems to be broken.

**Comment by nikku** [comment]
Fixed upstream (again) via https://github.com/bpmn-io/dmn-js/pull/620.
