### ISSUE TITLE
"Add row" button within DMN Decision Table is clickable in limited area

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2054]
__Describe the Bug__

I can click the "Add row" button only in some limited area of the last row. It works correctly on the demo site, though.

https://user-images.githubusercontent.com/28307541/103993298-ada23d80-5195-11eb-8530-9b7513f62dfd.mov

__Steps to Reproduce__

1. Open a DMN Decision Table
2. Try to click the plus button
3. now this happens

__Expected Behavior__

It should be clickable within the entire row.

__Environment__

- OS: MacOS 10.15.7
- Camunda Modeler Version: 4.5.0-rc.0

**Comment by philippfromme** [comment]
Cannot reproduce on Windows 10 using 4.5.0-rc.0. bpmn.io demo is also working for me.

**Comment by barmac** [comment]
I cannot reproduce it anymore. It might have been my Mac's quirk.

**Comment by philippfromme** [comment]
🚀
