### ISSUE TITLE
Download link for windows is broken

### ISSUE THREAD

**Issue by ahus1** [camunda/camunda-modeler#206]
When opening the website https://camunda.org/dmn/tool/ with firefox from windows, the big download button leads to 

https://camunda.org/release/camunda-modeler/0.5.1/camunda-modeler-win32-ia32.zip

But this link is broken (404). 

https://camunda.org/release/camunda-modeler/0.5.1/camunda-modeler-0.5.1-win32-ia32.zip

**Comment by nikku** [comment]
Thanks for the hint. Should be fixed, soon.
