### ISSUE TITLE
Provide an easy way to edit a rule's id in the decision table view

### ISSUE THREAD

**Issue by jtvilm** [camunda/camunda-modeler#2066]
__Is your feature request related to a problem? Please describe.__

The modeler auto-generates rule ids with prefix "DecisionRule_" and a hash suffix as their individual values, such as "DecisionRule_09xkbzp".

As a user or tester, it is pretty hard, however, to remember what specific conditions rule "DecisionRule_09xkbzp" is associated with. This is particularly the case when debugging and monitoring matched rules via log messages during runtime of the DMN engine in a Spring Boot application, for example.

Unfortunately, renaming a rule's id in the modeler to alleviate rule recognition is really cumbersome. It requires the user to switch to the XML view and edit their id as part of the XML rule tag. In case of a large decision table with many rules one can lose overview in the many XML tags easily.

I therefore suggest an easier way to edit an individual rule's id in the decision table view to be able to give it a semantically more meaningful value. 

__Describe the solution you'd like__

My proposed solution is similar to editing the details of input and output rule elements. One can modify their attributes, such as expression, input variable, or type, via a "floating panel" by double-clicking on the label in the column header.

Similarly, one could modify a rule's id by double-clicking on the row number displayed in the first column in the decision table. A small "floating panel" would allow editing the corresponding rule id.

__Describe alternatives you've considered__

None.

__Additional context__

None.

**Comment by nikku** [comment]
Thanks for opening this issue.

From what I understand your issue is "make it easier to trace/debug rule evaluation using a Camunda Spring Boot application logs". Is that correct? 

Could you share details on how you debug evaluation? What are these log messages you refer to and how do these get easier to understand by hand crafting rule IDs?
