### ISSUE TITLE
Disallow Window-Reload via Menu (will discard all non-saved changes)

### ISSUE THREAD

**Issue by ahus1** [camunda/camunda-modeler#207]
__Problem:__ User can reload via menu (`window -> reload`)
__Solution:__ Remove reload functionality from window menu.

__Details__:

When doing a reload, I experienced the following: 

   * with a newly created DMN file (not saved yet), the full table is gone
   * with a file loaded from disk and editit, the contents are reset to the data saved in the file

This comes to me (as a user) as a surprise. Behaviour I would expect:

  * a warning when there are unsaved changes with the chance to save them

**Comment by nikku** [comment]
Are you referring to the [Camunda Modeler](https://camunda.org/bpmn/tool)? How are you _reloading_ and why?

**Comment by ahus1** [comment]
Yes, I am referring to camunda modeler. There is a menu Item "Window" -> "Reload", hotkey CTRL-R. 

I was evaluating the Camunda Modeler and I was trying out what this menu item would do. In the future I think I would use this menu item when a file has been changed in disk (outside camunda modeler).

**Comment by nikku** [comment]
Thanks for the hint. This menu item is for debugging purposes and should not be visible to the user.
