### ISSUE TITLE
As a user, I'd like to know when an update check triggered by me fails

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2086]
__Is your feature request related to a problem? Please describe.__

When I trigger update check and there are network problems or the update server responds with anything but 200, it fails silently and the user can only notice it via console. 

__Describe the solution you'd like__

Show a notification on such problems.

__Describe alternatives you've considered__

Leave it as it is.

**Comment by nikku** [comment]
As a user I'd expect that background update checks do not disturb be, cf. https://github.com/camunda/camunda-modeler/pull/2216#issuecomment-821085673. So my expectation is exactly the opposite of what you expect :wink:.

**Comment by barmac** [comment]
I totally agree with you. Not sure why I did not specify it in the issue that I meant only the checks triggered by the user.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2216
