### ISSUE TITLE
Quick "New Tab" should offer more file types 

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2093]
__Is your feature request related to a problem? Please describe.__

The Modeler offers an easy way to quickly create new tabs.

![Kapture 2021-02-09 at 11 59 45](https://user-images.githubusercontent.com/9433996/107354336-5104ac00-6ace-11eb-8abe-4e3c770f431a.gif)

However, with introducing more and more file types (Zeebe BPMN Diagrams, Forms), this becomes less intuitive, since it will be hard to decide, which tab type _is the default_.

__Describe the solution you'd like__

It should be possible to create other tabs via the "+" button.

![image](https://user-images.githubusercontent.com/9433996/107354608-a771ea80-6ace-11eb-8866-ffa406b869c4.png)

I can also imagine this could be configurable.

__Describe alternatives you've considered__

Keep things as they are.

__Additional context__

Related to https://github.com/bpmn-io/internal-docs/issues/216

**Comment by nikku** [comment]
My personal opinion is to not invest time into this, short term.

Mid term, I can see a number of options:

* Keep `+` simple, in open tab user chooses diagram type
* Keep `+` simple, later on user chooses diagram type naturally, i.e. when she starts to implement

A simple alternative is also:

* Remove `+` alltogether.

The main use-case for the modeler is Camunda BPMN modeling. That will remain the case for the next releases.

**Comment by falko** [comment]
How about creating the same diagram type as the one currently open. This would have prevented #2283 and I also found myself multiple times clicking the + button while working on DMN and then getting a BPMN model as a surprise.

**Comment by andreasgeier** [comment]
As a quick fix, and also to mitigate #2283, the plus could open the welcome page where the different types can be chosen.

**Comment by nikku** [comment]
Closing this in favor of https://github.com/camunda/camunda-modeler/issues/2293. 

We'll remove the `+` button at least temporarily, as it causes trouble.
