### ISSUE TITLE
Deleting with backspace is not possible if a literal expression was reopened

### ISSUE THREAD

**Issue by jhbmach** [camunda/camunda-modeler#2095]
__Describe the Bug__

I want to open and edit a DMN file that already contains a Literal Expression task. After choosing the task in the DRD and click at the end of the expression line (or any other point in it) and than pressing backspace, the last char will not removed and an exception is printed in the log. If I press any other key, like delete or letters, the expression can be edited and even backspace will work after pressing any other key.

The exception from the log:
```
removeSelection is not a registered action
    at Th (webpack:///node_modules/dmn-js-literal-expression/lib/features/editor-actions/EditorActions.js:126:9)
    at e.value (webpack:///node_modules/dmn-js-literal-expression/lib/features/editor-actions/EditorActions.js:48:14)
    at trigger (webpack:///src/app/tabs/dmn/DmnEditor.js:669:7)
    at triggerAction (webpack:///src/app/tabs/MultiSheetTab.js:258:18)
    at triggerAction (webpack:///src/app/tabs/EditorTab.js:36:33)
    at triggerAction (webpack:///src/app/App.js:1709:15)
    at fn (webpack:///src/app/App.js:2232:19)
    at file:///D:/Programme/camunda-modeler-4.6.0-win-x64/resources/app.asar/public/bundle.js:65:109443
    at file:///D:/Programme/camunda-modeler-4.6.0-win-x64/resources/app.asar/public/bundle.js:65:109519
    at file:///D:/Programme/camunda-modeler-4.6.0-win-x64/resources/app.asar/public/bundle.js:65:122809 [ error ]
```

__Steps to Reproduce__

1. Get a DMN file with at least one LiteralExpression
2. (Re-)open the DMN file. Select the LiteralExpression, so that you can edit the actual expression.
3. When clicking in or at the end of the expression line and trying to delete parts of it with the backspace key, an exception appears in the log and no char is deleted.

__Expected Behavior__

Backspace should not lead to excpetions and it should delete the char before the cursor.

__Environment__

- OS: [Windows 10, Ubuntu 18]
- Camunda Modeler Version: [reproduced in 4.4 and 4.6]

![image](https://user-images.githubusercontent.com/78860984/107528743-766ee400-6bba-11eb-96c3-32fe9217a70d.png)

----

Related to [SENTRY issues](https://sentry.io/organizations/camunda-modeling/issues/?groupStatsPeriod=auto&project=5223041&query=removeSelection&statsPeriod=14d).

**Comment by MaxTru** [comment]
Thanks for reporting. I was able to reproduce it on Arch Linux with Camunda Modeler 4.4.0+. With 4.3.0 it works.

We will look into this

**Comment by MaxTru** [comment]
Workaround: type a space first, and then try to delete

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2394.
