### ISSUE TITLE
Trace non-existing plug-ins when reporting errors as `none` 

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2096]
__Describe the Problem__

When tracking errors via sentry we currently do log the installed plug-ins with an inconsistent datatype. If plug-ins exist we join them via `,`, if non exist we do not provide the field at all.

This confuses our error tracker and prevents us from filtering errors _without_ plug-ins installed:

![image](https://user-images.githubusercontent.com/58601/107537339-0e70cb80-6bc3-11eb-939e-c6b35102eaa4.png)

__What should we do?__

Always log plug-ins, if non are installed use a special field, i.e. `none`.

__Why should we do it?__

This allows us to filter our error logger for problems that originate in unmodified editor instances.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/2097

**Comment by nikku** [comment]
:clap:
