### ISSUE TITLE
Clarify file extension for form files

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2108]
__What should we do?__

Similar to `bpmn` and `dmn` elements, forms should have a clear file extension, for example `form`.

__Why should we do it?__

This would allow our users to open it directly in the Camunda Modeler, via dblclick in the file system.

__Alternatives__

Do nothing and recognize forms as `.json` files.

**Comment by nikku** [comment]
#### Proposal

We use `.form` as a file extension. It is used virtually nowhere else and should thereby be a safe pick (cf. [extension](https://www.file-extensions.org/form-file-extension) [registries](https://fileinfo.com/extension/form)).

**Comment by philippfromme** [comment]
+1 for using `.form`. My only concern was that another major tool is already using this extension. Let's grab it while it's up for grabs! 👋
