### ISSUE TITLE
Element Template Validation Error Messages don't refer to actual template

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2111]
__Describe the Bug__

Most of the error messages produced by the https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js produce their errors without refering to which element template they refer to.

__Steps to Reproduce__

Example for `invalid property type`

1. Setup broken template:
```JSON
[
  {
    "$schema": "https://unpkg.com/@camunda/element-templates-json-schema@0.2.0/resources/schema.json",
    "name": "Default Rendering2",
    "id": "com.camunda.example.DefaultRendering2",
    "appliesTo": [
      "bpmn:ServiceTask"
    ],
    "properties": [
      {
        "label": "Input Parameter",
        "binding": {
          "type": "camunda:inputParameter",
          "name": "processVar",
          "asdf": "aasdasdasdf"
        }
      },
      {
        "label": "Output Parameter",
        "type": "I dont exist",
        "binding": {
          "type": "camunda:outputParameter",
          "source": "outputParam"
        }
      }
    ]
  }
]
```
2. Start Modeler and create new BPMN
3. Error message is logged: `[diagram_1.bpmn] invalid property type <I dont exist>; must be any of { String, Text, Boolean, Hidden, Dropdown }`

Note that the error message is not very helpful if you have many element template present since you will not know which element template is affected.

__Expected Behavior__

All element template validation errors refer to the affected template in a consistent way (e.g., by referring to `id` and `name`)

__Environment__

- OS: Arch Linux
- Camunda Modeler Version: 4.6

**Comment by pinussilvestrus** [comment]
Closed via 2e1ecc1bec2a78d9e910a018cfc146e74d400469

![image](https://user-images.githubusercontent.com/9433996/111439892-17931200-8706-11eb-8412-0a457cdc7d48.png)
