### ISSUE TITLE
Migrate to C-based zeebe-node

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2114]
__What should we do?__

* Update `zeebe-node` dependency to the latest
* Include `electron-rebuild` as a post-install step
* Verify that a release-like build works with build-on-demand

__Why should we do it?__

We want to be ready for future Zeebe releases.

Child of https://github.com/bpmn-io/internal-docs/issues/216

**Comment by nikku** [comment]
`npm run all` should still work, too.

**Comment by barmac** [comment]
That's right. This should work both locally and on CI.

**Comment by MaxTru** [comment]
As discussed in the weekly. Since this increases library size and also install time significantly. Before doing this, we should at least quickly evaluate to update electron as a possible alternative solution.
