### ISSUE TITLE
When you save a Zeebe diagram with unknown extension, it opens as a Camunda diagram

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2130]
__Describe the Bug__

When you save a Zeebe diagram with unknown extension, it opens as a Camunda diagram.

__Steps to Reproduce__

1. Create a Zeebe diagram.
2. Save file as `diagram.foo`.
3. Close the diagram and reopen it.

__Expected Behavior__

It should open as Diagram (Zeebe).

__Environment__

- OS: MacOS
- Camunda Modeler Version: `develop`

**Comment by barmac** [comment]
Problem occurs [here](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/TabsProvider.js#L444), because in the providers map the `bpmn` (Camunda) provider precedes `cloud-bpmn` (Zeebe) provider.

**Comment by pinussilvestrus** [comment]
So, taking the `cloud-bpmn` before the `bpmn` provider should do the trick, right?

**Comment by barmac** [comment]
I think so.
