### ISSUE TITLE
Implement multi-file deployment

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2131]
__What should we do?__

Implement multi-file deployment

* [x] user can choose multiple files
* [x] files are opened via a system dialog
* [x] files are deployed to Camunda Platform
* [x] it looks as on [the design](https://miro.com/app/board/o9J_lSZSPc0=/)
* [x] clicking the button allows to add files to the existing list

__Why should we do it?__

This is not only required for the forms to work, but also useful for complex process diagrams.

Related to https://github.com/camunda/camunda-modeler/issues/2100

**Comment by andreasgeier** [comment]
In the issue description, an important acceptance criterion is missing: all files (incl. the bpmn file from which the deploy button was called) must be within the same deployment in order to ensure that referenced Camunda Forms are recognized and working.

**Comment by andreasgeier** [comment]
To describe acceptance criteria 1 und 2 more precise: a user must be able to call the system dialog multiple times to add sources from different locations. During these steps, the already selected sources must remain in the list of selected sources.
