### ISSUE TITLE
Add BPMN Diagram (Zeebe) button for the Empty Tab

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2132]
__What should we do?__

Add BPMN Diagram (Zeebe) button for the Empty Tab.

__Why should we do it?__

We want to support the Zeebe tab in all places.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/4e5fd1056ecf1ebdfd0bda2c1486b1336cca80e1
