### ISSUE TITLE
Change labels for the new file menu and the deployment plugins

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2136]
__What should we do?__

Change labels:

* [x] "new file" menu:
  * [x] Create BPMN Diagram (Camunda Engine)
  * [x] Create BPMN Diagram (Zeebe Engine)
  * [x] Create DMN Diagram (Camunda DMN Engine)
  * [x] _Create Form (Camunda Forms)_ (to be implemented yet)
* [x] tab name:
  * [x] Diagram (Camunda Engine)
  * [x] Diagram (Zeebe Engine)
* [x] deployment tools:
  * [x] Camunda Platform
  * [x] Camunda Cloud

__Why should we do it?__

We want to use accurate and clear naming.

**Comment by pinussilvestrus** [comment]
Will we also update it here? 

![image](https://user-images.githubusercontent.com/9433996/109952510-32658f80-7cdf-11eb-8c03-19a33d752189.png)

**Comment by barmac** [comment]
I think so.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2134
