### ISSUE TITLE
Modeler displays "Template not found" after publishing new template version in Cawemo

### ISSUE THREAD

**Issue by meyerdan** [camunda/camunda-modeler#2139]
__Describe the Bug__

After publishing a new version of my template in Cawemo, and restarting the modeler, when selecting a service task to which the previous version was applied, the modeler displays a "Template not found" error instead of allowing me to apply the template.

__Steps to Reproduce__

1. Crate template in Cawemo and publish it
2. Restart Camunda Modeler
3. Model process with service task and apply template to service task
4. In Cawemo, create new version of template and publish
5. Restart Camunda Modeler
6. Open process and select service task.
7. Instead of allowing me to apply the new template version, the modeler shows "template not found"

![image](https://user-images.githubusercontent.com/488063/110099218-5a1d2c00-7da1-11eb-8d3b-c3cb43225620.png)

__Expected Behavior__

Expected behaviour would be that the modeler allows me to update the template.

__Environment__

- MacOS
- Camunda Modeler Version: v4.6.0
- Link to template in cawemo that I used: https://cawemo.com/templates/29e2ed80-1ea7-47cd-ac3b-5bd645932299--delete-customer-data

**Comment by MaxTru** [comment]
Is solved by updating to Cloud Connect 3.0.0.

(We should add a compatability / features matrix in the docs)

**Comment by meyerdan** [comment]
We can close this.

Resolution: [cloud connect plugin](https://docs.camunda.org/cawemo/latest/technical-guide/integrations/modeler/) was not up to date

**Comment by meyerdan** [comment]
> (We should add a compatability / features matrix in the docs)

Or distribute this directly with the Camunda Modeler ;)

**Comment by philippfromme** [comment]
Okay, so the issue occurred because once you publish a new template only the new one will be synced. Older versions of the template will not be synced which is the expected behavior for version <3.x. 👍
