### ISSUE TITLE
Update cloud deployment target names

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2141]
> _Copied from the original issue https://github.com/zeebe-io/zeebe-modeler/issues/292_.

__Is your feature request related to a problem? Please describe.__

The names of the endpoint targets in the Zeebe deployment dialog are outdated.

![Screen Shot 2021-03-05 at 15 39 30](https://user-images.githubusercontent.com/938244/110130238-15a58680-7dc9-11eb-9323-6bd72d8d0809.png)

__Describe the solution you'd like__

According to @felix-mueller we should call it "Camunda Cloud Self-Managed" and "Camunda Cloud SaaS". Please update.

__Describe alternatives you've considered__

Keep it as is.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2148.
