### ISSUE TITLE
Wrong order of "Create BPMN Diagram (Zeebe)" and "Create BPMN Diagram (Camunda Engine)"

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2158]
__Describe the Bug__

In the current nightly (16.03.2021), the order of the "Create ..." options is as follows: 
![image](https://user-images.githubusercontent.com/42800119/111340689-28497680-8679-11eb-8a18-5b07d6718269.png)

However, `Camunda Engine` shall be the most prominent option on top.

__Steps to Reproduce__

1. Use Camunda Modeler Nightly as of 16.03.2021 
2. Click on "create diagram"
3. Wrong order appears

__Expected Behavior__

The expected order is:
```
Create BPMN Diagram (Camuda Engine)
Create BPMN Diagram (Zeebe)
Create DMN Diagram ....
Create Form ...
```

__Environment__

- OS: Manjaro Linux
- Camunda Modeler Version: nightly as of
- Found in the context of https://github.com/camunda/camunda-docs-manual/pull/889

**Comment by pinussilvestrus** [comment]
We could revert the changes of the reordering (a2cf40675f44e86583362de709cf885782c5a33c) and introduce a priority mechanism to ensure more specialized providers are adopted earlier.

```js
const DEFAULT_PRIORITY = '1000';

const HIGHER_PRIORITY = '1001';

this.providers = {
  ...
  'cloud-bpmn': {
    priority: HIGHER_PRIORITY
  },
  bpmn: {
    priority: DEFAULT_PRIORITY
  },
  ...
}

// _getFileProvider(file)


// no providers specified for the extension; return the first that can open the file
const provider = findProviderForFile(sortByPriority(this.providers), file);
```

**Comment by barmac** [comment]
Sounds good.

**Comment by nikku** [comment]
Priorities are the way to go. You could consider to give menu items a `priority` key, so more advanced use-cases are possible (ordering differently, depending on a use-case). Electron offers [some helpers](https://www.electronjs.org/docs/api/menu-item), that we could consider to adopt.

**Comment by pinussilvestrus** [comment]
> Priorities are the way to go. You could consider to give menu items a `priority` key, so more advanced use-cases are possible (ordering differently, depending on a use-case). Electron offers [some helpers](https://www.electronjs.org/docs/api/menu-item), that we could consider to adopt.

That sounds pretty interesting. Can you refer to how Electron could support us? The only properties that might help would be `before` and `after`, as far as I can see.

**Comment by nikku** [comment]
Not exactly supporting us. I'm just suggesting at this point. If we consider menu entries, their facilities could be an inspiration.

I.e. label existing entries (BPMN) and ensure that Cloud BPMN is always, no matter what rendered _after_ the element.

**Comment by joshdaniel87** [comment]
1b1a0e88ff2b05e49787c7ff1078247e4d83b67e

**Comment by barmac** [comment]
> 1b1a0e88ff2b05e49787c7ff1078247e4d83b67e

Excuse me?
