### ISSUE TITLE
Validate Element Templates using JSON Schema

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2159]
__Is your feature request related to a problem? Please describe.__

Currently, element templates are manually validated.
However, we now have a JSON Schema in place, which allows for easy and powerful validation.

__Describe the solution you'd like__

The goal of this request is to get rid of the manual validation we currently do and instead use JSON Schema validation using https://github.com/camunda/element-templates-json-schema

__Describe alternatives you've considered__

n/a

__Additional context__

Context: https://github.com/camunda/camunda-modeler/issues/2083

**Comment by pinussilvestrus** [comment]
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/386

**Comment by pinussilvestrus** [comment]
Together with @MaxTru we decided to check out this topic in a time-boxed manner at the end of this quarter, e.g. by replacing the Properties panel Validator with the JSON schema.

**Comment by pinussilvestrus** [comment]
**Checking possible inconsistencies of the [JSON Schema](https://github.com/camunda/element-templates-json-schema) with the current Validator implementation**

_WIP_

* https://github.com/camunda/element-templates-json-schema/issues/24
* https://github.com/camunda/element-templates-json-schema/issues/25

**Comment by pinussilvestrus** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/455
