### ISSUE TITLE
Create new deployment with all files by enabling enable-duplicate-filtering 

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2160]
__Is your feature request related to a problem? Please describe.__

Currently, when using `Start Instance Tool` a deployment is taking place. If an existing deployment exists, this might even create a new deployment. However, not all files being part of the deployment will be part of the deployment. This can break features like forms. 
In order to avoid this behavior, the `duplicate-filtering` shall be enabled in this situation:

`A flag indicating whether the process engine should perform duplicate checking for the deployment or not. This allows you to check if a deployment with the same name and the same resouces already exists and if true, not create a new deployment but instead return the existing deployment. The default value is false.` [source](https://docs.camunda.org/manual/7.14/reference/rest/deployment/post-deployment/#request-body)

__Describe the solution you'd like__

* Set `enable-duplicate-filtering` to `true` when deploying
* Don't set `deploy-only-changed`

__Describe alternatives you've considered__

n/a

__Additional context__

Discussed [here](https://confluence.camunda.com/display/camBPM/Camunda+Forms+Q1+2021%3A+cross-team+alignment+workspace)

**Comment by MaxTru** [comment]
I will evaluate the different cases we have and give a summary so to validate what is put in the issue, prior to doing the actual change

**Comment by nikku** [comment]
This is exactly what we do already, right? I mean we have `deploy-changed-only` enabled which enables duplicate filtering (cf. [docs](https://docs.camunda.org/manual/7.14/reference/rest/deployment/post-deployment/#request-body)).

Or am I missing anything here.

**Comment by nikku** [comment]
Enabling duplicate filtering _and_ disabling `deploy-changed-only` would yield a different behavior, however that is not what's specified in this issue.

**Comment by MaxTru** [comment]
See https://github.com/camunda/camunda-modeler/pull/2137#issuecomment-801714355

**Comment by MaxTru** [comment]
Will be handled as part of this PR: https://github.com/camunda/camunda-modeler/pull/2137
