### ISSUE TITLE
Save shortcut does not work in the Forms view

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2163]
__Describe the Bug__

When I press Cmd+S on a dirty form tab, nothing happens.

__Steps to Reproduce__

1. Create a form
2. Press Cmd+S
3. now this happens

__Expected Behavior__

File should be saved.

__Environment__

- OS: MacOS
- Camunda Modeler Version: `develop`

**Comment by pinussilvestrus** [comment]
Will this be fixed by #2150 as well or do we have to handle it separately?

**Comment by barmac** [comment]
I guess it should, otherwise one could argue that the integration is not done yet.
