### ISSUE TITLE
Variable names in the overview are shortened to a single character

### ISSUE THREAD

**Issue by andreasgeier** [camunda/camunda-modeler#2166]
__Describe the Bug__

If the mapping information in the variable overview contains a certain amount of text, it strongly truncates the variable names to only one visible character (screenshot by Robert Emsbach).

![image](https://user-images.githubusercontent.com/938244/111746304-24db0880-888e-11eb-88a0-71cbae0e5ecb.png)

__Steps to Reproduce__

see screenshot

__Expected Behavior__

In case of truncation, the variable text area must consider a min width of 50% to avoid such a scenario as in the screenshot above.

**Comment by barmac** [comment]
This will need to be fixed within the properties panel.
