### ISSUE TITLE
Help with the rendering MIWG models

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#2170]
__What should we do?__

Each year Camunda takes part is the Model Interchange Working Group presentation where members of the OMG all hang out and prove that tools which claim to the BPMN 2.0 compliment are in fact compliment. This involves being able to render the same model in the same way for each tools. We need help ensuring that the model correctly renders in Camunda's modeler and a long or short term fix in place if things don't look as they should

__Why should we do it?__

It's important that Camunda is seen to be part of the greater BPMN tooling community and by actively demonstrating the capabilities we can showcase our tooling while also learning about how we compare to other tools.  

__Resources__

* BPMN diagram: [`process-collaboration.bpmn`](https://github.com/camunda/camunda-modeler/files/6189347/process-collaboration.bpmn.txt)

**Comment by MaxTru** [comment]
This is what we should / could support for June 2021: https://drive.google.com/drive/u/0/folders/1LkaWLul2NxcXbRkeF_Nm7xkFUhwNBusi 

* DMN works
* BPMN so far does not work

The BPMN, we would - per design - not like to support. (also see [this discussion](https://forum.bpmn.io/t/process-elements-outside-of-a-pool/5934/3))

But what we potentially could do, is to provide an "compatability plugin"

**Comment by nikku** [comment]
Is the diagram public? If so, could we attach it to this issue as a test case?

**Comment by NPDeehan** [comment]
The diagram is not pubic - but I've added it to the Google Drive link that Max left in his comment. So we can use it internally.

**Comment by nikku** [comment]
Thanks for the info. Any chance to get hold on the most simple version of that diagram, available for public viewing?

**Comment by falko** [comment]
There is no problem if the model is in a public GitHub repo, e.g. as a test case or as part of this issue discussion. After the demo, it will become a test case of the BPMN MIWG Test Suite.

The particular style of modeling stems from Bruce Silver's BPMN books and might therefore be commonly used by his readers and training participants especially in North America.

**Comment by nikku** [comment]
Thanks for the clarification. I've attached it to the BPMN diagram being discussed.

**Comment by falko** [comment]
The i18n extension that has been specified by the BPMN MIWG is also a part of this year's test: https://github.com/bpmn-miwg/bpmn-i18n

Just this week I had another customer asking for it. Is there any way we can think of supporting that, e.g. in a modeler plugin?

**Comment by nikku** [comment]
Not supported out of the box, but may be possible to support via a plug-in, yes.

**Comment by falko** [comment]
A new issue has been discovered during today's demo dry run: https://github.com/camunda/camunda-modeler/issues/2214

**Comment by falko** [comment]
This year's MIWG demo will again use the BPMN in Color Specification: https://github.com/bpmn-miwg/bpmn-in-color
Is there any way we can think of supporting that, e.g. in a modeler plugin?

**Comment by barmac** [comment]
BPMN in Color will be supported via https://github.com/bpmn-io/bpmn-js/pull/1453

**Comment by davidgs** [comment]
I have a "minimum viable product' plugin for doing Model I18N that works, but ... it would be *much* better if we included the `<1i8n:translations>` extension in the underlying `moddle` out of the box.

**Comment by nikku** [comment]
At the moment we don't plan to support the `bpmn:i18n` extension out of the box. It is a classic _vendor_ extension.

I'm not sure what keeps you from using it at this stage?

**Comment by davidgs** [comment]
I believe it's a BPMN standard extension now, not a vendor extension. What so far keeps me from using it is that it simply doesn't work to add it as an extension later.

**Comment by falko** [comment]
Does this have to do with the use of xml:lang especially in the root node?

**Comment by davidgs** [comment]
Yes. That's what this is about.

**Comment by MaxTru** [comment]
> I believe it's a BPMN standard extension now, not a vendor extension. What so far keeps me from using it is that it simply doesn't work to add it as an extension later.

If it is not broken, could you please create an issue for that? That is something we should fix then.

I assume you are referring to [registerBpmnJSModdleExtension](https://github.com/camunda/camunda-modeler-plugin-helpers#how-to-use)?

**Comment by nikku** [comment]
What we can do is to look into the `i18n` topic in a time-boxed manner ourselves. 

Until then, please provide clearly reproducible bug reports for us that allow us to understand your context. What usually does not work is jumping onto potential solutions without us (the core modeling team) understanding the underlying issue.
