### ISSUE TITLE
Update Camunda Getting Started mentioning forms

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2172]
__What should we do?__

Update our getting started guides to mention form support in the Camunda Modeler.

__Why should we do it?__

Advertise the feature so people discover it going down the getting started guide route.

----

Child of https://github.com/camunda/camunda-modeler/issues/2135

**Comment by MaxTru** [comment]
Work in progress, see https://github.com/camunda/camunda-docs-manual/tree/CAM-13307

Next steps:
* Align with cross-team group (in particular Platform team to ensure proper backlinks) on Wednesday (24.03.)
* Add screenshots as soon as Camunda Nightly is available

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-docs-manual/pull/877
