### ISSUE TITLE
Improve the accessibility of form field `key`

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2178]
__What should we do?__

A design review surfaced that we may improve upon the form field `key` naming and/or documentation with the goal to make what it does easier to understand for users of the form builder. 

As a follow up we should get a clear picture, how we support our users:

* What is the user journey for getting started with Camunda Forms?
* How shall users understand the `key` property and it's implications?
* Potentially rename the field / add a description to make it easier accessible?
* Potentially add links to existing the documentation?

As an alternative, we may decide to do nothing, as we'll look into overall properties panel improvements in Q2 anyway.

__Why should we do it?__

Other than _label_, _description_ and other fields in the form builder properties panel the meaning and impact of the `key` entry is not self-explainatory.

**Comment by MaxTru** [comment]
**Result from quick workshop with @volkergersabeck, @nikku and @MaxTru on 29.03.2021**
Label shall be `Key`
Description shall be `Maps to a process variable`

Find all discussion points here: https://miro.com/app/board/o9J_lMvTFaU=/

**Comment by nikku** [comment]
Addressed via https://github.com/bpmn-io/form-js/pull/38.
