### ISSUE TITLE
Update manual integration tests

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2180]
__What should we do?__

With the coming release (#2157), we add a couple of "testworthy" features to the application. Therefore, the [integration tests](https://github.com/camunda/camunda-modeler/blob/develop/docs/.project/INTEGRATION_TEST.md) would need an update. That (could) include:
* Adding tests for Forms
* Removing CMMN (?)
* ...

__Why should we do it?__

Cleanup.

**Comment by MaxTru** [comment]
Closed by https://github.com/camunda/camunda-modeler/pull/2186
