### ISSUE TITLE
Boundary Event: EventDef Reference lost when changing type interruppting/non-interrupting

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2185]
__Describe the Bug__

When changing the type a boundary event, the reference within the EventDefinition is lost, even in case where the old and the new type both support the same EventDefinitions. Example: `Interrupting Message Boundary Event` and `Non-interrupting Message Boundary Event`

__Steps to Reproduce__

![MessageRefLost](https://user-images.githubusercontent.com/42800119/113616291-30337f80-9655-11eb-9af2-36bd24797ec3.gif)

1. Create non-interrupting Message Boundary Event
2. Add a message
3. Change type to interrupting Message Boundary Event
4. => Reference to the message is not copied over to the new/morphed element type

(The same applies to other References, such as `Signal` or `Error`)

__Expected Behavior__

If both - the new and the old type - support the same Event Definition Reference, the reference should be kept when morphing.

__Environment__

- OS: Any
- Camunda Modeler Version: 4.6.0
- Raised here: https://jira.camunda.com/browse/SUPPORT-10350

**Comment by nikku** [comment]
@philippfromme Please mark as fixed upstream if this bug is fixed via https://github.com/bpmn-io/bpmn-js/commit/c3e0d6d16477bc2e9e37109a9ff1254b6695c7cc.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2246
