### ISSUE TITLE
Form field can be dropped on the palette which causes an error

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2198]
__Describe the Bug__

https://user-images.githubusercontent.com/28307541/114030147-89302d00-987a-11eb-877d-619da9eec9f3.mov

__Steps to Reproduce__

1. Create an element
2. Drag it to the palette
3. now this happens

__Expected Behavior__

Palette should not be a drop target for fields.

__Environment__

- OS: MacOS
- Camunda Modeler Version: 4.7-rc.0

**Comment by philippfromme** [comment]
I can reproduce this. 👍🏻

**Comment by MaxTru** [comment]
Fixed via https://github.com/camunda/camunda-modeler/pull/2205
