### ISSUE TITLE
Min/max length can be set to negative values

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2199]
__Describe the Bug__

![image](https://user-images.githubusercontent.com/28307541/114030670-eaf09700-987a-11eb-9ff9-b6333535aac8.png)

__Steps to Reproduce__

1. Create an input
2. Play with min/max length
3. now this happens

__Expected Behavior__

`minlength` should be non-negative; `maxlength` should be positive.

__Environment__

- OS: MacOS
- Camunda Modeler Version: 4.7-rc.0

**Comment by philippfromme** [comment]
Thanks for reporting. Can easily be fixed before the release.

**Comment by pinussilvestrus** [comment]
Fixed upstream via https://github.com/bpmn-io/form-js/issues/48

**Comment by MaxTru** [comment]
Fixed via https://github.com/camunda/camunda-modeler/pull/2205
