### ISSUE TITLE
Label Box is annoying

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-modeler#220]
The Label "Boundary" is sometimes too big (in this case the text was without line breaks when I got the model. After adding line breakd the label box keeps being bit and is in the way of selecting other things properly)

![2016-03-17_08-05-46](https://cloud.githubusercontent.com/assets/1217596/13838818/33c7bd98-ec17-11e5-9f80-2425302d813b.png)

**Comment by nikku** [comment]
Related to and addressed by https://github.com/bpmn-io/bpmn-js/issues/549
