### ISSUE TITLE
Opening Form Results in Error Logged in Console

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2201]
__Steps to Reproduce__

1. Open existing `.form` file
2. Open console
3. Error logged in console

![image](https://user-images.githubusercontent.com/7633572/114154280-838d2280-9920-11eb-8839-21329b248a11.png)

The error is logged because the check whether the file is a BPMN file tries to parse the JSON as XML.

__Expected Behavior__

The check whether the file is a BPMN file returns `false` without an error logged.

__Environment__

- Camunda Modeler Version: 4.7.0-rc.0

**Comment by pinussilvestrus** [comment]
Can you share an example file? For me opening existing `.form` files work as expected.

![Kapture 2021-04-09 at 10 56 08](https://user-images.githubusercontent.com/9433996/114155831-3742e200-9922-11eb-97e4-9a636ba76787.gif)

**Comment by nikku** [comment]
This error seems to occur in conjunction with the Camunda Cloud Connect plug-in. From the stack trace it looks like the plug-in tries to retrieve the relation ID but fails opening forms.

**Comment by philippfromme** [comment]
@nikku You're right. I was to quick to assume it is caused by the check whether it is a BPMN diagram. I will adjust the description and create and issue in the cloud connect plugin's repository.

**Comment by philippfromme** [comment]
Closed in favour of https://github.com/camunda/cloud-connect-modeler-plugin/issues/38.
