### ISSUE TITLE
No error information when save is impossible

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-modeler#221]
Scneario:

- Open a BPMN Model from a browser link
- Change it
- Hit Strg-S or File->Save

Then you have no error message or feedback, but the market in the tab shows the file as unsaved. 

I have to manually say File -> Save File As... in order to get it saved correctly.

Improved behavior:
Srtg-S/File->Save gets an error message a la "File cannot be saved, please save it somehwere else" and open the Save As dialog

**Comment by ricardomatias** [comment]
I cannot open a BPMN model from a browser link. Is this a Windows feature ? Tried in both Linux and Mac.
