### ISSUE TITLE
The engine version shall be logged via E.T. after each deployment

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2219]
> **This is an epic issue which may be broken down into multiple tasks, if needed**

__What should we do?__

We would like to better understand to which engine a given diagram is deployed.

In particular, we would like to update the deployment event logging to E.T. as following:
Property Name | Property Definition | Data Type | Sample Values
-- | -- | -- | --
diagramType | type of diagram that was deployed | String | bpmn, dmn
diagramMetrics | *various* | JSON |  *various*
outcome | result of the deployment | String | success, failure
error | type of error (if outcome is failure) | String | DIAGRAM_PARSE_ERROR
context | where was the deployment triggered from | String | deploymentTool
**new:** engine | which engine was deployed to | String | camunda, zeebe
**new:** engineVersion | which engine version was deployed to | String | 7.15.0

In particular we need to:

- [x] Validate and finalize the `Property Name` (`engine` and `engineVersion`)
- [x] Validate with Engine teams which APIs to use to fetch the endpoint version
- [ ] Update the [Telemetry documentation](https://github.com/camunda/camunda-modeler/tree/develop/docs/telemetry)

__Why should we do it?__
This will help to better understand what engine versions is deployed to and hence optimize the Modeler experience to it.

__Context__
[Telemetry documentation](https://github.com/camunda/camunda-modeler/tree/develop/docs/telemetry)

**Comment by MaxTru** [comment]
To clarify: how would this fit to the existing metric
```
{
  "engineProfile": {
    "executionPlatform": "Camunda Cloud"
  }
}
```

**Comment by MaxTru** [comment]
To validate. 

I propose to embed this as following:
```
  "deployment": {
    "outcome": "success",
    "engine": "camunda",
    "engineVersion": "7.15.0"
  }
```

**Comment by MaxTru** [comment]
I validated with @ThorbenLindhauer : we should use the [version](https://docs.camunda.org/manual/latest/reference/rest/version/) API to retrieve the version information. (It does not require any special rights for the caller)

**Comment by MaxTru** [comment]
I talked with @menski : we can use the [`topologyRequest` API](https://docs.camunda.io/docs/reference/grpc#output-topologyresponse) to retrieve the broker version. However [Zeebe-node does not exposte the brokerVersion at the moment](https://github.com/camunda-community-hub/zeebe-client-node-js/blob/953a93894406d6e55cdfcc1e6289599644f77831/src/lib/interfaces-grpc.ts#L164). We can follow-up with a PR or get in touch with Josh.

**Comment by MaxTru** [comment]
I played around with zeebe-node-js and found that we can use [`gatewayVersion`](https://github.com/camunda-community-hub/zeebe-client-node-js/blob/master/proto/zeebe.proto#L255) which is included in a topologyResponse:
```js
await zbc.topology()
```

```json
    {
      brokers: [
        { partitions: [Array], nodeId: 0, host: '172.18.0.3', port: 26501 }
      ],
      clusterSize: 1,
      partitionsCount: 1,
      replicationFactor: 1,
      gatewayVersion: '0.26.1'
    }

```

**Comment by MaxTru** [comment]
Decided as described above with @volkergersabeck and @andreasgeier

**Comment by nikku** [comment]
For your consideration: We're naming these things `executionPlatform` and `executionPlatformVersion` in other places in the Camunda Modeler. Cf. https://github.com/camunda/modeler-moddle/blob/main/resources/modeler.json#L16.

**Comment by MaxTru** [comment]
> For your consideration: We're naming these things `executionPlatform` and `executionPlatformVersion` in other places in the Camunda Modeler. Cf. https://github.com/camunda/modeler-moddle/blob/main/resources/modeler.json#L16.

This is a good point.

`executionPlatform` refers to the platform set in the XML.
`engine` we propose to put as property of `deployment` so to make clear, that this is an outcome of the deployment. However, now that you say it I think we could simply name it `executionPlatform` and `executionPlatformVersion`. This would make the naming consistent. Still these would be properties of `deployment` so it would still be clear that this is not the same as the `executionPlatform` based on the XML.

@volkergersabeck wdyt?
