### ISSUE TITLE
support grouping/hiding of input columns and rows for better overview in DMN table

### ISSUE THREAD

**Issue by grexe** [camunda/camunda-modeler#2222]
__Describe the solution you'd like__

If you work with a complex set of business rules, you may end up with a lot of rules (rows) and columns (inputs) in your DMN table.
Grouping or hiding related input columns and rule rows could help a lot to clean up / trim the table and get a better overview of the rules and aspects you actually need to work with.

E.g., a price calculation may involve data from customers, products, and orders. If you work on rules that affect only order attributes, you might want to hide the other areas.
The same goes for rows, where you might want to collapse or hide rules you are not interested in.

Of course, a rules table should not involve too many different aspects and not get too wide/complex, but in many situations, you need the information together in one place to make a business decision.

__Describe alternatives you've considered__

There is none, except for splitting up the table or manually resizing columns,-)

__Additional context__

Table column grouping is a common advanced feature in the business domain (think Excel), so it would fit naturally, as advanced users already understand and use the concept.

**Comment by nikku** [comment]
Could you attach a small screen capture to showcase how that works in Excel? This will allow us to easier associate something with your feature request if we decide to pick up this issue.

**Comment by nikku** [comment]
Closing this as won't fix / missing information.
