### ISSUE TITLE
Update Camunda Forms engine profile description to include Camunda Cloud

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2233]
__What should we do?__

Update Camunda Forms engine profile description to include Camunda Cloud.

__Why should we do it?__

Currently, the description mentions Camunda Platform and the Tasklist only:

> This form is supposed to be used with <em>Camunda Platform</em>. The properties panel provides the related implementation features. This form can be attached to a BPMN diagram deployment and is rendered in a connected Camunda Tasklist.

With the upcoming release, the Camunda Cloud tab will also allow to use Camunda Forms within User Task. So it's not only about the Tasklist.

**Comment by andreasgeier** [comment]
If forms can be used in both stacks now, we also need to consider how to determine the deployment target. For the first time, the relation between engine profile and product stack is not 1:1.

**Comment by MaxTru** [comment]
> If forms can be used in both stacks now, we also need to consider how to determine the deployment target. For the first time, the relation between engine profile and product stack is not 1:1.

Just to summarize and document the discussion from slack: deploy tool is not shown in form tabs. Hence this is not relevant.
