### ISSUE TITLE
Include `deployment.targetType` field when deploying to Camunda Platform in telemetry

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2238]
__Is your feature request related to a problem? Please describe.__

When deploying a diagram, we send a `deploy` event to E.T.

When deploying to `Camunda Cloud` this event includes the following data:
```
deployment.targetType: camundaCloud <or> selfHosted
```

When deploying to `Camunda Platform` the `deployment.targetType` field is not included.

__Describe the solution you'd like__

To allow for better reporting in Kibana, the `deployment.targetType` should also be included for `Camunda Platform` (but would then always have the value `selfHosted`.

__Describe alternatives you've considered__

Accept inconsistent event structure when deploying to Camunda Cloud or Platform.

__Additional context__

Was realized working on #2219

**Comment by srijit2002** [comment]
@pinussilvestrus I want to work on this issue. Can you please assign it to me and list the files I need to work on?

**Comment by nikku** [comment]
Provided by the [Cloud deployer](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js#L395) but not the [platform deployer](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js#L180).
