### ISSUE TITLE
Implement improved properties panel resize bar

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2239]
__What should we do?__

Alongside building our new properties panel (cf. https://github.com/bpmn-io/internal-docs/issues/256) we want to improve the resize behavior of the existing Properties Container.

![screencast](https://user-images.githubusercontent.com/9433996/116811937-477a6580-ab4c-11eb-9141-5f143bcfaa69.gif)

__Why should we do it?__

Have a resize behavior that fits better into the new visual IDE story.

Cf. concept: https://github.com/camunda/camunda-modeler-design/issues/6

**Comment by pinussilvestrus** [comment]
We de-prioritize this task, because we believe the current resize bar is a good starting point.

**Comment by andreasgeier** [comment]
I believe this can be closed as done.

**Comment by pinussilvestrus** [comment]
Yes, thanks! Closed via https://github.com/camunda/camunda-modeler/pull/2642
