### ISSUE TITLE
t.getVersion is not a function when starting an instance on Camunda Platform

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2249]
__Describe the Bug__

Error visible on the screenshot appears when I start an instance with attached DMN on Camunda Platform. It is logged only to the console:

![image](https://user-images.githubusercontent.com/28307541/117646063-9eef8580-b18b-11eb-90f6-fc2e34bfbf80.png)

I suspect it's due to recent Usage Statistics changes.

__Steps to Reproduce__

1. Create a BPMN diagram
2. Deploy with a DMN as an attachment
3. Start instance

__Expected Behavior__

No errors in the console.

__Environment__

- OS: MacOS
- Camunda Modeler Version:  4.8.0-rc.0
- Installed plug-ins: None

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2254
