### ISSUE TITLE
Keep selected Properties Panel Tab when switching element

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-modeler#225]
Currently the Prperty Panel is always reseted to the first tab when clicking on a different diagram element. It should keep the tab is applicable to the element type selected.

Example: I want to check formKey for all User Tasks on a BPMN Model. I select the "Form" tab and after that I can select every User Task. Currently this is annoying as always the Tab "General" is selected (and mouse way is long)

**Comment by polenz** [comment]
Implemented with the following commits:

bpmn-js-properties-panel:
https://github.com/bpmn-io/bpmn-js-properties-panel/commit/f3e2e16046e5ec82b7250cc10a8b18f5de144111

cmmn-js-properties-panel:
https://github.com/bpmn-io/cmmn-js-properties-panel/commit/666974a9e146198635208a577c3da41e9ec414d6
