### ISSUE TITLE
DMN: Set focus to the new row

### ISSUE THREAD

**Issue by michaldytko** [camunda/camunda-modeler#2259]
__Is your feature request related to a problem? Please describe.__

Right-click on any row and click "Add Rule Above/Below", the focus should be set on the new rule.

__Describe the solution you'd like__

If I use the "Add Rule Above/Below" functionality, the focus should be set on the new row, hence it should be filled in.

__Describe alternatives you've considered__

no alternatives

This is a follow-up of #928, it only concerned the last row. Now the functionality should be the same for all rows.
[SUPPORT-6122](https://app.camunda.com/jira/browse/SUPPORT-6122)

**Comment by andreasgeier** [comment]
This request makes sense to me. We are aiming for the same behavior in the new property panel. 

The principle: If a new entry is created, it gets the focus. So a user can immediately start to type.

**Comment by volkergersabeck** [comment]
I would combine this topic with a proper visual indicator for which cell / row has the focus. Otherwise some users might not easily see where we put the focus. But in general, I agree that this would be good to have.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2316
