### ISSUE TITLE
Manual "check for update" should not use staged rollout endpoint

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2263]
__Is your feature request related to a problem? Please describe.__

User reported the following behavior as bug:
* A new camunda modeler solution is released
* User retrieves the update notififaction, but clicks it away
* User decides to view the update again, clicks "check for update"
* Because of the staged rollout strategy we use in the update server, the user retrieves the message "modeler is up to date"
* When clicking multiple times the "check for update" server, the modeler eventually gets the notification

__Describe the solution you'd like__

I propose:
* Implement a parameter or seperate endpoint in the update server which bypasses the staged rollout strategy
* Use this adjusted endpoint/additional parameter when manually checking for update

__Describe alternatives you've considered__

Keep as is

__Additional context__

Reported by Rob via slack

**Comment by andreasgeier** [comment]
I second this request. From the user's perspective (and common sense), the message "up to date" is just wrong when a new version is available.

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2395
