### ISSUE TITLE
DateTime returned by Tasks Rest API not rfc3339 compliant

### ISSUE THREAD

**Issue by Xnyle** [camunda/camunda-modeler#2266]
Using the SpringBoot Example App with Rest client enabled, queries to the task endpoint return times like this

 2021-05-10T14:36:44.418+0200

this is not  rfc3339 compliant, it should look like this

 2021-05-12T12:34:34.720+00:00

This is creating problems with clients generated via openapi generator as i now have to "hack" the generated ApiClient to accept that non standard format for task queries.

**Comment by pinussilvestrus** [comment]
Are you sure your problem belongs to the Camunda Modeler? Or rather https://github.com/camunda/camunda-bpm-platform?

**Comment by Xnyle** [comment]
Yeah sorry, belongs to platform, could you move it?

**Comment by pinussilvestrus** [comment]
I believe `camunda-bpm-platform` is using [a different issue tracker](https://app.camunda.com/jira). So I'd recommend you to open it over there.
