### ISSUE TITLE
Call Activity - Process Id field doesn't support expression and it should

### ISSUE THREAD

**Issue by danshapir** [camunda/camunda-modeler#2267]
For Camunda Cloud, when you create a new Call Activity, the process Id field should support expressions but it shows an error (Not a valid QName) instead.

__Steps to Reproduce__

1. Create a new call activity
2. Enter `=` in the `processId` field
3. _An error will be shown complaining about the invalid id_

__Expected Behavior__

It should work, that's a [documented feature](https://docs.camunda.io/docs/0.25/product-manuals/zeebe/bpmn-workflows/call-activities/call-activities/#defining-the-called-workflow).

> Usually, the processId is defined as a static value (e.g. shipping-process) but it can also be defined as expression (e.g. = "shipping-" + tenantId). The expression is evaluated on activating the call activity and must result in a string.

__Environment__

- OS: Mac OS
- Camunda Modeler Version: Latest

**Comment by pinussilvestrus** [comment]
Thanks for reporting!

For reference, we had a similar issue in the old Zeebe Modeler project: https://github.com/zeebe-io/zeebe-modeler/issues/290.

**Comment by danshapir** [comment]
Is there any update on this issue? Or a workaround until it's fixed?

**Comment by danshapir** [comment]
@pinussilvestrus ? Any updates? Or workaround? We are literally stuck and can't reach production due to this issue.

**Comment by nikku** [comment]
@danshapir As a workaround you could go to the XML view and change the process ID there.

![capture 7fdKQU_optimized](https://user-images.githubusercontent.com/58601/122345116-c59d9a80-cf47-11eb-9ec9-402d94e79542.gif)

As it is a documented feature we should fix it.

**Comment by pinussilvestrus** [comment]
Is this upstream fixed? (cf. https://github.com/camunda/camunda-bpmn-js/pull/28)

**Comment by nikku** [comment]
Yes it is. :)

**Comment by nikku** [comment]
And closed via https://github.com/camunda/camunda-modeler/commit/72a435c3d9ab76b5d7c591863c3b068a80b6e6c2#diff-1846122c2c83a486a3693f7966aa522c34cf489f674185c4da0d9221683fd81f.
