### ISSUE TITLE
Windows Newline Characters Lost on Paste

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2280]
__Describe the Bug__

Pasting copied text containing Windows newline characters (`\r\n`) results in those characters being lost. This affects both editing labels in the diagram and the properties panel. Both are using the API to paste the text (`document.execCommand('insertText', false, 'foo')`).

![YiYfMJ831R](https://user-images.githubusercontent.com/7633572/118964263-9ce5ad80-b967-11eb-997c-d286bad04d70.gif)

__Steps to Reproduce__

1. Copy this text

```
Line 1

Line 3
```

2. Paste text to edit label or into properties panel
3. Empty line is lost due to Windows newline characters being lost

__Expected Behavior__

Newline characters are preserved regardless of operating system.

__Environment__

- OS: Window 10
- Camunda Modeler Version: 4.8.1

Jira Issue: https://jira.camunda.com/browse/SUPPORT-10754

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2315
