### ISSUE TITLE
Simplify the sequence/message flow icon

### ISSUE THREAD

**Issue by eriknyk** [camunda/camunda-modeler#2282]
__What should we do?__

Simplify the connect icon from 

<img width="44" alt="connect-tool-screenshot" src="https://user-images.githubusercontent.com/205721/119166610-73d72280-ba24-11eb-9ef8-f7ff2f755c57.png">

to 

<img width="44" alt="single arrow" src="https://user-images.githubusercontent.com/205721/119167195-2f985200-ba25-11eb-860e-4b2848c27f5b.png">

__Why should we do it?__

Improve the icons accessibility :arrow_down:.

---

# What
Please, change the sequence/message flow icon

From:

<img width="44" alt="connect-tool-screenshot" src="https://user-images.githubusercontent.com/205721/119166610-73d72280-ba24-11eb-9ef8-f7ff2f755c57.png">

By the single version of both sequence line + arrow, like 

<img width="44" alt="single arrow" src="https://user-images.githubusercontent.com/205721/119167195-2f985200-ba25-11eb-860e-4b2848c27f5b.png">

and 

<img width="44" alt="Screen Shot 2021-05-21 at 11 08 57" src="https://user-images.githubusercontent.com/205721/119167213-33c46f80-ba25-11eb-9ef7-8bb4173799d3.png">

I think that by default can be the first image, and change it on demand later (with a context menu similar when you switch from task types ) to dotted arrow.

# Why?

There are some people (like me) that have a weird eye condition where with icons like that, 

![image](https://user-images.githubusercontent.com/205721/119166610-73d72280-ba24-11eb-9ef8-f7ff2f755c57.png)

It causes that the brain thinks that the image is not focused and it tries to focus but since the image is ok and will not change the brain tries to focus all time causing a fatal tiredness and even headache. 

I'm pretty sure that I'm not the only one with this problem since the doctor told me that is a normal issue for some people with certain age.

Best Regards, and congrats for all you awesome work.

**Comment by nikku** [comment]
Thanks for opening this issue.

What the icon should transport is _make a connection_. We want to avoid that users think only a single connection type is possible. We also want to avoid to show more than one entry in the context pad and in the palette. 

Do you have a suggestion how we could improve the icon with regards to your issue while continuing to transport that message?

**Comment by nikku** [comment]
Would be interesting to get your feedback on :arrow_up: @eriknyk.

**Comment by eriknyk** [comment]
Thanks for you answer @nikku, I was thinking a way try minimize the eye effect, and something like this can help.

![copy](https://user-images.githubusercontent.com/205721/120578670-c8e34300-c3eb-11eb-8567-562b4bf7bb95.png)

I didn't tried other colors, but yeah it minimize the effect, not at 100% but at least a 75% what is acceptable helpful.

**Comment by andreasgeier** [comment]
This symbol does not only represent (a standard) connection but also message flow, conditional flow, and default flow. It is a symbol that represents an entire group like most of our other symbols in the palette and context pad do (gateway, task, end event, etc.).

So my argument would be that one representative symbol is enough. In this case, I would choose the standard connection:
![symbol](https://user-images.githubusercontent.com/205721/119167195-2f985200-ba25-11eb-860e-4b2848c27f5b.png)

**Comment by nikku** [comment]
Your rationale @andreasgeier makes absolute sense.

I've updated the issue description accordingly. We'll give the simplified connection symbol (sequence flow style) only a try.

**Comment by eriknyk** [comment]
@nikku just checking in on this one to see if there is any update.

Regards.

**Comment by nikku** [comment]
We did not pick it up yet.

**Comment by barmac** [comment]
This is now `fixed upstream`.
