### ISSUE TITLE
Don't report element template validation "errors" to sentry

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2287]
__Describe the Bug__

Currently element template validation errors (e.g., `template(id: <abc>, name: <abc>): missing binding for property "0"` are logged and treated as errors. Hence they are also logged to sentry. See for example: 
[ex1](https://sentry.io/organizations/camunda-modeling/issues/2386508793/?project=5223041&query=is%3Aunresolved+template&statsPeriod=14d)
[ex2](https://sentry.io/organizations/camunda-modeling/issues/2336443227/?project=5223041&query=is%3Aunresolved+template&statsPeriod=14d)

__Steps to Reproduce__

1. Have usage statistics enabled
2. Set up an element template with an invalid property binding
3. See how an error is logged in the Camunda Modeler
4. See how the error appears in sentry

__Expected Behavior__

These validation *"errors"* should not be logged to sentry. 

__Environment__

- Camunda Modeler Version: 4.7 | 4.8
- Execution Platform: Camunda Platform
- Installed plug-ins: none

**Comment by pinussilvestrus** [comment]
Looking at the way we log [template validation errors](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js#L127) we could easily filter out these by checking a to-be-captured error starts with "template".

It would look something like that: https://github.com/camunda/camunda-modeler/pull/2302

Maybe even better would be a more stable identicator. But this could be a good starting point.

**Comment by pinussilvestrus** [comment]
Better approach: simply [handle template errors as warnings inside the BpmnEditor](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/bpmn/BpmnEditor.js#L251) ==> bubble up as warnings in the chain.

Cf. https://github.com/camunda/camunda-modeler/pull/2302#discussion_r648116355 (cc @nikku)

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2302
