### ISSUE TITLE
More clarity for elements with Listeners, forms, extensions etc.

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#229]
When selecting an element it would be very useful to see a summary of what has been implemented on the element. E.g. when clicking on a user task - it would be nice to immediately know how many task listeners ares present without having to click on the listeners tab. 

Perhaps a summary on the General tab could relay more information about what is implemented in the other tabs.

This is related to the famous [property-info-plugin](https://github.com/umb/camunda-modeler-property-info-plugin) that shows quite nicely what is configured on the diagram.

**Comment by Skaiir** [comment]
With the new properties panel, this comes by default as we have ditched tabs :)

![image](https://user-images.githubusercontent.com/17801113/165518325-c19ed59a-a80b-4e78-8fdf-23c193b6ecae.png)
