### ISSUE TITLE
Register Camunda Modeler as Default Editor for .form Files

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2292]
The Camunda Modeler isn't being registered as the default editor for `.form` files, yet: https://github.com/camunda/camunda-modeler/blob/v4.8.1/resources/platform/win32/support/fileassoc.reg

We should add it to get rid of this:

![image](https://user-images.githubusercontent.com/7633572/120182262-76006480-c20e-11eb-92a7-566e7cbd7714.png)

**Comment by nikku** [comment]
We simply forgot about this one. Good spot!

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2311.
