### ISSUE TITLE
Fallback Editor Not Opened in Case a Form Cannot Be Opened

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2294]
__Describe the Bug__

When opening a `.form` file that cannot successfully be opened (e.g. because it contains unknown form fields) the fallback editor (JSON editor) isn't opened. The tab is empty and therefore useless.

![7odbP39F8y](https://user-images.githubusercontent.com/7633572/120336262-76722b80-c2f2-11eb-97a8-7ce3a055f939.gif)

__Steps to Reproduce__

1. Open [form_1.form.txt](https://github.com/camunda/camunda-modeler/files/6576758/form_1.form.txt) with Camunda Modeler v4.8
2. An error message is displayed but the fallback editor isn't opened

__Expected Behavior__

The fallback editor is opened

__Environment__

- Camunda Modeler Version: 4.8

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2305
