### ISSUE TITLE
A Camunda Cloud user can model a Send Task

### ISSUE THREAD

**Issue by menski** [camunda/camunda-modeler#2297]
__Is your feature request related to a problem? Please describe.__

As a Camunda Cloud user I can model a process definition with a send task. The send task will behave like a service task, and the main purpose is to support the modelling of send task.

__Describe the solution you'd like__

A send task can be modeled and supports all service task properties, i.e. type, retries, input/output mappings and task headers

__Additional context__

```
<bpmn:sendTask id="Task" name="Task">
  <bpmn:extensionElements>
    <zeebe:taskDefinition type="task-type" retries="123" />
    <zeebe:ioMapping>
      <zeebe:input source="= processVariable" target="inputVariable" />
      <zeebe:output source="= localVariable" target="outputVariable" />
    </zeebe:ioMapping>
    <zeebe:taskHeaders>
      <zeebe:header key="firstTaskHeader" value="first task header value" />
      <zeebe:header key="secondTaskHeader" value="second task header value" />
    </zeebe:taskHeaders>
  </bpmn:extensionElements>
  <bpmn:incoming>IncomingFlow</bpmn:incoming>
  <bpmn:outgoing>OutgoingFlow</bpmn:outgoing>
</bpmn:sendTask>
```

**Comment by barmac** [comment]
Done upstream via https://github.com/camunda/camunda-bpmn-js/pull/27

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2315
