### ISSUE TITLE
Improve saving dialog

### ISSUE THREAD

**Issue by toco-cam** [camunda/camunda-modeler#2300]
__Is your feature request related to a problem? Please describe.__

When closing Modeler with a not saved model, the dialog displays the buttons in a not standardized way (compared to e.g. word) and the focus is on cancel. 
![image](https://user-images.githubusercontent.com/71005504/121025638-aa8f9580-c7a5-11eb-9cc8-94ec9ce34b35.png)

Due to this behavior, it happend to me several times, that I lost my model without saving.

__Describe the solution you'd like__

Implement default behavior like e.g. Word with the focus on save.
![image](https://user-images.githubusercontent.com/71005504/121026050-107c1d00-c7a6-11eb-8875-eab54fdcfff8.png)

**Comment by nikku** [comment]
Confirmed by @toco-cam that this is annoying for windows users.
