### ISSUE TITLE
Cannot open multiple processes if flag "disable-cmmn" is set to false

### ISSUE THREAD

**Issue by hizr** [camunda/camunda-modeler#2301]
__Describe the Bug__

If the flag "disable-cmmn" is set to false its only possible to open a single process file on startup

__Steps to Reproduce__

1. open a process (could be BPMN or CMMN)
2. while the modeler is open, open a new process by double clicking or out of an IDE **(not with the opening dialog)**
3. now the modeler screen flashes but the does not open the file

__Expected Behavior__

Like in older versions it should open a new tab with the file, when opening a process file.

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.8.1

**Comment by pinussilvestrus** [comment]
Thanks for sharing! This might be related to https://github.com/camunda/camunda-modeler/issues/2268, what will be fixed in the next release.

Can you maybe try out [the current nightly](https://downloads.camunda.cloud/release/camunda-modeler/nightly/) and tell us if your issue still exists?

**Comment by hizr** [comment]
works the the current nighlty build! Thanks for your fast response!
