### ISSUE TITLE
Show version number in status bar with basic "what's new" communication

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2303]
Let's display version number with basic "what's new" communication on the status bar.

__Requirements__

* [x] Version number is displayed
* [x] Unread marker is displayed
  * [x] Marker disappears once the overlay has been clicked
* [x] When version number is clicked, an overlay opens
  * [x] overlay includes "what's new" text
  * [x] overlay includes "learn more" links
  * [x] overlay is displayed correctly
* [x] Help menu includes a link which opens the overlay
* [x] Telemetry is updated
  * [x] We track opening of the overlay
  * [x] We track opening the links in the "Learn more" section
  * [x] [Documentation](https://github.com/camunda/camunda-modeler/blob/develop/docs/telemetry/README.md) is updated
  * [x] Tracking concept is updated
* [x] Release checklist is updated

__Additional context__

Design: https://github.com/camunda/camunda-modeler-design/issues/2

**Comment by barmac** [comment]
Proposal for the tracked data: https://github.com/camunda/camunda-modeler/commit/e1dd2287c33d65d6a51b9b7f0cb049f741e0cc46
@volkergersabeck

**Comment by MaxTru** [comment]
For 
> Telemetry is updated

=> Could we please give the *Shared Services* team just a quick heads-up? I don't want them to be surprised when this new event type pops up in dev or prod :-) Thanks

**Comment by barmac** [comment]
> For
> 
> > Telemetry is updated
> 
> => Could we please give the _Shared Services_ team just a quick heads-up? I don't want them to be surprised when this new event type pops up in dev or prod :-) Thanks

Thanks for the suggestion. I've already reached out to the Shared Services Team and as soon as we decide on what exactly we want to collect, I will send them the detailed information as they requested.

**Comment by volkergersabeck** [comment]
regarding tracking: could we have two separate events "versionInfoOpened" and maybe "versionInfoClicked"? Then we don't need the type attribute and it's easier when evaluating.

for the clicked url: do we need the full url or would e.g. the link label be sufficient / more understandable?

**Comment by barmac** [comment]
> regarding tracking: could we have two separate events "versionInfoOpened" and maybe "versionInfoClicked"? Then we don't need the type attribute and it's easier when evaluating.

Sure. Thanks for the suggestion.

> for the clicked url: do we need the full url or would e.g. the link label be sufficient / more understandable?

If we start to use labels, it may be more difficult to implement tracking the links within the update notice. Let's say we take this sentence from the 4.7 release blog post:

> To find out more about the form editor and how to use forms for your Camunda BPMN or custom application, please take a look at the [documentation](https://docs.camunda.org/manual/latest/modeler/forms/).

Should we then add a label to the link or have a third type of event?

**Comment by barmac** [comment]
Second version: https://github.com/camunda/camunda-modeler/blob/2303-update-usage-statistics/docs/telemetry/README.md#version-info-events

**Comment by barmac** [comment]
After a second thought, the labels might be enough for now if we assume we track only learn more section. Then, it can look like this: https://github.com/camunda/camunda-modeler/blob/b14fcbe253955dfb6174c58f06d35c357dee50df/docs/telemetry/README.md#version-info-events

**Comment by MaxTru** [comment]
> After a second thought, the labels might be enough for now if we assume we track only learn more section. Then, it can look like this: https://github.com/camunda/camunda-modeler/blob/b14fcbe253955dfb6174c58f06d35c357dee50df/docs/telemetry/README.md#version-info-events

I think this is, from a tracking perspective, the best solution since it will allow easy analysis of the events in Kibana. So the proposal is good from my perspective. @volkergersabeck ?

**Comment by barmac** [comment]
Based on discussion with @volkergersabeck, I prepared this version: https://github.com/camunda/camunda-modeler/blob/8785c1ef98a567322696452f162da48962168a84/docs/telemetry/README.md#version-info-events

**Comment by barmac** [comment]
> https://github.com/camunda/camunda-modeler/blob/8785c1ef98a567322696452f162da48962168a84/docs/telemetry/README.md#version-info-events

We will continue based on this proposal.

**Comment by nikku** [comment]
Can this one be closed with the final bits merged?

**Comment by barmac** [comment]
Correct.
