### ISSUE TITLE
As a user I want to set a static value in a read-only text field

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-modeler#2304]
__Is your feature request related to a problem? Please describe.__

Often I want to provide additional context to the user about a task.

__Describe the solution you'd like__

Be able to set a static value (instead of a key that maps to a process variable) on a read-only text field. 

__Describe alternatives you've considered__

My current workaround is using input mappings to set the value of the key to some static value.
This means the static definition is defined in the process, while it should probably belong in the form.

__Additional context__

- It might be interesting to allow FEEL expressions directly instead of defining a key.
- I'd expect a static value to be rendered directly in the modeller, also when this is a FEEL expression like `= "foo"`

----

Mentioned [here](https://camunda.slack.com/archives/C034N0E5YCX/p1651054827674279?thread_ts=1650414431.837809&cid=C034N0E5YCX).

**Comment by pinussilvestrus** [comment]
To which execution platform are you referring? Camunda Cloud or Platform?

**Comment by korthout** [comment]
Ah I wasn't sure there was a difference for forms, but I specifically need this for Camunda Cloud :)

**Comment by pinussilvestrus** [comment]
You're probably right, that seems to be not related to a specific platform 👍

**Comment by nikku** [comment]
Also mentioned in [this conversation](https://camunda.slack.com/archives/C034N0E5YCX/p1651054827674279?thread_ts=1650414431.837809&cid=C034N0E5YCX).

**Comment by pinussilvestrus** [comment]
This will be doable once we integrate https://github.com/bpmn-io/form-js/issues/436 (via `form-js@0.10`). I'm setting this as fixed upstream; feel free to disagree.
