### ISSUE TITLE
Improve status bar

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2318]
__What should we do?__

Implement missing pieces of the status bar story.

Activities:

* [x] move deploy button to the status bar
  * [x] status bar button opens the modal
  * [x] status bar button is placed correctly
* [x] move run button to the status bar
  * [x] status bar button opens the modal
  * [x] status bar button is placed correctly
* [x] reduce buttons number on the toolbar

Design: https://github.com/camunda/camunda-modeler-design/issues/1

Already done:

* [x] engine profile (already done)
* [x] xml button
* [x] log button

__Why should we do it?__

It's part of [the status bar vision](https://github.com/camunda/camunda-modeler-design/blob/main/visual-ide/STATUS_BAR.md) and a step towards the Visual IDE goal.

**Comment by andreasgeier** [comment]
I've updated the [design issue](camunda/camunda-modeler-design#1) and added the todo of delivering the new icons.

**Comment by nikku** [comment]
Question raised: Do we ship with the multi-option start or without? 

My proposal would be: Cleanup the existing behavior. If we allow  _start (with same configuration)_, allow repetitive _deploy (with same configuration)_, too. 

Why would I personally keep the _start (with same configuration)_? Because it encourages quick iteration during development / understanding the engine in a playful manner.

**Comment by andreasgeier** [comment]
@barmac Let's have a chat about the multi-option, I need a better understanding what is the current state. On top, I'll have a talk with Volker about further reducing the toolbar and will keep you posted. This would be just removals, not moves or changes.

**Comment by barmac** [comment]
Multi-option alignment rough result:

![image](https://user-images.githubusercontent.com/28307541/122936413-6db0ca80-d371-11eb-83d1-a250fad359aa.png)

It's not pixel-perfect, I know.

For the Camunda Cloud tab, the overlay will still open but it will contain only the "Start Instance" option.

**Comment by andreasgeier** [comment]
@barmac regarding the toolbar reduction please have a look at https://github.com/camunda/camunda-modeler-design/issues/1 and let's sync.

**Comment by philippfromme** [comment]
Is it intentional that almost all buttons are gone when the _Welcome_ tab is open? 

![image](https://user-images.githubusercontent.com/7633572/123591698-9e1ebb80-d7ec-11eb-8174-12fb367f879d.png)
