### ISSUE TITLE
Support zeebe 1.1 clusters by bumping zeebe-node

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2319]
> :construction: This issue is WIP :construction:

__Is your feature request related to a problem? Please describe.__

**[Context](https://docs.google.com/document/d/1FvTVcSFLactlF0Mw1npq19O-iir4QHzNpzIj4Fzk9S0/edit#)**
At the moment the Camunda Cloud infrastructure is creating a DNS entry in the format ${UUID}.zeebe.camunda.io for every Zeebe cluster. This is the unique address the cluster is available at for the user to connect to.
* This limits the amount of clusters we can address to 3.500
* This requires users to wait for DNS propagation

Solution approach by the cloud team: use a single DNS address per region and provide cluster UUID using the `:authority` pseudo header.

**What this means for us**

(As of now) the assumption is that [zeebe-node-js](https://www.npmjs.com/package/zeebe-node) will be released in a new version which supports zeebe 1.0 and zeebe 1.1.

Based on that assumption, we would need to update to that latest version and ensure everything still works as expected.

__Describe alternatives you've considered__

~~Integrate two versions of [zeebe-node-js](https://www.npmjs.com/package/zeebe-node)~~ (We can not do that)

__Additional context__

RfC: https://docs.google.com/document/d/1FvTVcSFLactlF0Mw1npq19O-iir4QHzNpzIj4Fzk9S0/edit#

**Comment by MaxTru** [comment]
cc @barmac

**Comment by nikku** [comment]
Did we receive an update from upstream regarding when and if that thing is going to be delivered? Asking as the release manager for the upcoming release.

**Comment by barmac** [comment]
@jwulf is working on a new version of `zeebe-node` which should support Zeebe 1.1 without any API changes. We will get a status update on Monday.

**Comment by barmac** [comment]
Since zeebe-node@1.4.0 is out, we can test that.

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2343
