### ISSUE TITLE
Compatibility with Set Execution Platform and Version Is Indicated through Linting

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2323]
The Camunda Modeler is aware of execution platforms and indicates compatibility of a form with the selected execution platform through linting.

### General

* [x] https://github.com/camunda/camunda-modeler/issues/2324
* [x] https://github.com/camunda/camunda-modeler/issues/2325
* [x] https://github.com/camunda/camunda-modeler/issues/2326
* [x] https://github.com/camunda/camunda-modeler/issues/2327

### Forms

* [x] https://github.com/camunda/camunda-modeler/issues/2330
* [x] https://github.com/camunda/camunda-modeler/issues/2328
* [x] https://github.com/camunda/camunda-modeler/issues/2329

---

See also [strategy document](https://docs.google.com/document/d/1Zt4rm5IDwfVsUtdMAOEwlRmpEqdli22Y_7iFqyKG3g4/edit).

---

### Concept and design

- [Platform + version selection](https://github.com/camunda/camunda-modeler-design/issues/26)
- [Data view for linting results in form editor](https://github.com/camunda/camunda-modeler-design/issues/25)

**Comment by philippfromme** [comment]
### Kickoff (2nd July 2020)

Participants: 👨🏻 Maciej, 👨🏻 Max, 👨🏻 Niklas, 👨🏻 Volker

Miro Board: https://miro.com/app/board/o9J_l9eF1cI=/

#### Decisions

* the following execution platforms will be available: Camunda Platform 7.15, Camunda Cloud 1.0 and 1.1
* users should be able to select the respective form field when clicking on a linting error
* user tests regarding setting the execution platform will be conducted in the context of splitting properties into design and implementation (c.f. https://github.com/camunda/camunda-modeler-design/issues/8)

#### Actions

* we will consider user tests once we have a better idea of what the features could look like

**Comment by philippfromme** [comment]
### User Test with Curran (13.07.2021)

* positive feedback in general
* Question: Are the errors the way they are displayed (cf. [Zeplin](https://app.zeplin.io/project/5e149dc7ef8eaa51b52af327/screen/60d2fa323e729249ca083ba3)) the right abstraction layer? Will users understand them? The idea of displaying linting errors in the diagram/form later would make them easier to understand and to correlate
* Why not show early indication of whether choosing an execution platform would lead to compatibility issues?

#### Sketch

![image](https://user-images.githubusercontent.com/7633572/125467230-dbd9d77f-8000-446a-b347-3dc3516980ca.png)

**Comment by nikku** [comment]
Shipped.
