### ISSUE TITLE
No name of element "Association" on diagram

### ISSUE THREAD

**Issue by michel777777** [camunda/camunda-modeler#2331]
__Describe the Bug__

No name of element "Association" on diagram
![example_no_name_on_diagram](https://user-images.githubusercontent.com/86347050/123257740-da9f9e00-d4f2-11eb-84af-6ccff7e65aeb.png)

__Steps to Reproduce__

1. I put a name for a DataInputAssociation in the Properties Panel
2. I don't see the name of that DataInputAssociation on the diagram
3. The same for  th elements DataOutputAssociation, 

__Expected Behavior__

I expect, that the name appears on the diagramm all the Associations element

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.8.1
- Execution Platform: Camunda Platform
- Installed plug-ins: none

**Comment by pinussilvestrus** [comment]
Thanks for reporting! Can you verify whether this worked in older versions of the Modeler for you?

**Comment by pinussilvestrus** [comment]
@michel777777 is this the same issue as for #2333 or do they differ in one aspect?

**Comment by michel777777** [comment]
If you give me a link to an "older version"

**Comment by michel777777** [comment]
To https://github.com/camunda/camunda-modeler/issues/2331#issuecomment-868278626 not the same. 

https://github.com/camunda/camunda-modeler/issues/2331#issuecomment-868278626 deals with import
here is the name in modeler (without error) crated and after reopening gets error.

**Comment by pinussilvestrus** [comment]
It also seems like the `name` property is missing for associations in [bpmn-moddle](https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/json/bpmn.json#L2190).

We're open to contributions to improve the situation.

**Comment by ingorichtsmeier** [comment]
Hi @michel777777,

you can find older versions here: https://downloads.camunda.cloud/release/camunda-modeler/

**Comment by michel777777** [comment]
Tested 3.00 5.50 4.00 - the same

**Comment by michel777777** [comment]
Tested 3.00 , 3.50  and 4.00 - the same issue

**Comment by michel777777** [comment]
https://github.com/camunda/camunda-modeler/issues/2333 says. The modeler
allows giving a name without any error messaging. Only

**Comment by pinussilvestrus** [comment]
Related to https://github.com/camunda/camunda-modeler/issues/2333

**Comment by Skaiir** [comment]
As names are not supported for associations as per discussed in https://github.com/camunda/camunda-modeler/issues/2333 , we'll close this issue. 

Feel free to re-open if we get further feedback on this, but a solution for this would most likely require an extension and wouldn't be a quick property addition in the properties panel.
