### ISSUE TITLE
Send notification if nightly build fails

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2336]
__What should we do?__

Setup a notification when nightly build fails.

__Why should we do it?__

We may miss the error if there are no notifications. As long as we don't know about the problem, we are not inclined to fix it.

**Comment by nikku** [comment]
Could trial a Github :arrow_right: slack integration, i.e. https://github.com/marketplace/actions/slack-webhook-for-github-actions.

**Comment by barmac** [comment]
Alternatively, we could just send an email: https://github.com/dawidd6/action-send-mail

**Comment by nikku** [comment]
We already have `Sentry -> Slack` integration in place. As slack is really our communication hub (outside of GitHub) nowadays we should have that information in our team channel, visible for all.

**Comment by barmac** [comment]
Let's try out the Slack route. Maybe we can make some other use of the app later.
