### ISSUE TITLE
Allow editing process (inside participant) documentation via properties panel

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#235]
### Use Case

* Add documentation to process (via the properties panel)
* Changed the process diagram into a collaboration diagram
* Select newly created participant
* __Process documentation is not editable anymore__

### Solution Approaches

* Show both process _and_ participant documentation in properties panel
* Show _only_ process documentation in properties panel
* Move documentation from process to participant during morph?

**Comment by gimbel** [comment]
I would prefer the first approach: Show both process and participant documentation in properties panel

**Comment by nikku** [comment]
Closed via bpmn-io/bpmn-js-properties-panel#193 and available in next release.
