### ISSUE TITLE
Can model unsupported `bpmn:SendTask` in Camunda Cloud diagrams

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2354]
__Describe the Bug__

Send tasks are [not supported by Camunda Cloud yet](https://docs.camunda.io/docs/reference/bpmn-processes/bpmn-coverage). Regardless we already allow users to edit them:

![image](https://user-images.githubusercontent.com/58601/124723290-2e56b200-df0b-11eb-9566-52c29f3415b8.png)

__Steps to Reproduce__

1. Open [test diagram]([sendtask.bpmn.txt](https://github.com/camunda/camunda-modeler/files/6775440/sendtask.bpmn.txt))
2. Deploy diagram to Cloud 1.1
3. See cloud report back error

__Expected Behavior__

I cannot model a send task yet, if it is not supported by the cloud.

Starting with execution platform profiles we may revise that strategy, i.e. allow to model everything but lint.

__Environment__

- OS: Linux
- Camunda Modeler Version: v4.9.0-rc.4
- Execution Platform: Camunda Cloud 1.1
- Installed plug-ins: None

**Comment by barmac** [comment]
But... https://github.com/camunda/camunda-modeler/issues/2297

**Comment by nikku** [comment]
I know :thinking:. Clarifying this right now.

**Comment by nikku** [comment]
I did apparently test against the wrong cloud version. Should work in Cloud 1.1.
