### ISSUE TITLE
 Deleting the value of the "key"  leaves Text field completely inaccessible

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#2358]
__Describe the Bug__

After adding a text field in form and deleting the value of the "key"  leaves Text field completely inaccessible

__Steps to Reproduce__

1. Open a new Form.
2. Add a text field and button .
3. Click on the text filed and remove the value of the "key".
4. We could see the inside the text field "[object Object]" is displayed.
5. Click on the button and try to come back to the text field we could not access it anymore.
6. The delete option is also not visible.

__Expected Behavior__

The value in the"key" field should not be allowed to be removed.

__Environment__

- OS: Windows 10
- Camunda Modeler Version:4.9.0
- Execution Platform: Form(camunda platfomr or camunda cloud)
- Installed plug-ins: [...]

![from_console_err](https://user-images.githubusercontent.com/85225325/124939809-b8854000-e009-11eb-9060-a0cb7042e89f.jpg)

https://user-images.githubusercontent.com/85225325/124939861-c2a73e80-e009-11eb-8da0-ae5ac8c05467.mp4

---

Depends on https://github.com/bpmn-io/form-js/issues/58.

**Comment by nikku** [comment]
It is fairly trivial to break the form with invalid keys. Once broken it cannot be fixed anymore. Related to https://github.com/bpmn-io/form-js/issues/58.

**Comment by philippfromme** [comment]
How would we roll out a potential fix? The current Camunda Modeler v4.9 release doesn't feature the latest form-js version so in order to ship the fix with a potential v4.9.1 we'd have to backport it to form-js v0.1.x.

**Comment by nikku** [comment]
I'd be fine simply fixing it in form-js for now. So whenever we release and integrate that one (soon) we have it fixed.

There is no need to fix it with `v4.9.1`. Technically it is not a regression, too (has been around since v4.8.0).
