### ISSUE TITLE
Cannot use the letter/key "e", "s", "h", "l" when typing in DMN table

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#236]
Using Mac app. 0.5.1

OS: 10.11.4

![screen shot 2016-03-23 at 12 30 14 pm](https://cloud.githubusercontent.com/assets/1994838/13992577/02137e8c-f0f3-11e5-9341-63c1b1bec7fd.png)

**Comment by nikku** [comment]
Should be fixed in the [latest nightly](https://camunda.org/release/camunda-modeler/nightly/) and part of the next Camunda Modeler release (0.6.0).

**Comment by nikku** [comment]
Fixed via camunda/camunda-modeler#192
