### ISSUE TITLE
Forms are not XML/HTML encoded

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-modeler#2365]
__Describe the Bug__

Forms that define xml tags in the label, description, etc are not xml/html encoded.

__Steps to Reproduce__

1. create a new form
2. add a text field
3. write in the description: `Hello, <world>!`
4. go to json view
5. copy json
6. paste into a Camunda Cloud user task
7. go to xml view
8. see that it breaks the xml

__Expected Behavior__

Values defined in the form editor should be xml/html encoded.

For example, `Hello, <world>!` should be encoded to `Hello, &lt;world&gt;!` (I think)

__Environment__

- OS: macOS 11.4 / any
- Camunda Modeler Version: 4.8.1 (4.8.1.8069)
- Execution Platform: Camunda Cloud (but probably also on Camunda Platform)

**Comment by nikku** [comment]
I can reproduce the issue.

**Comment by nikku** [comment]
Congratulations by the way. You surfaced a [low-level XML serialization bug](https://github.com/zeebe-io/zeebe-bpmn-moddle/pull/12). We don't have many of these around, anymore :1st_place_medal:

**Comment by nikku** [comment]
Actually just a `zeebe-bpmn-moddle` [meta-model bug :crying_cat_face:](https://github.com/zeebe-io/zeebe-bpmn-moddle/commit/764d635e69dd8b4f00d871299aa223b42e33e31c).

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2369
