### ISSUE TITLE
TimerEventDefinitions types are not validated when changing element type

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2368]
__Describe the Bug__

(Cloud BPMN Tab)
TimerEventDefinitions types are not validated when changing element type.
Because of this, one can create invalid TimerEventDefinitions.

__Steps to Reproduce__

1. Create a new Cloud Diagram
2. Create a **non-interrupting TimerBoundaryEvent**
3. Set Timer Type `cycle`
4. Define a cycle time
5. Change type of element to **interrupting TimerBoundaryEvent**
6. ==> Notice that the TimeCycle is still set in the XML, even though it is not allowed for **interrupting TimerBoundaryEvent**

__Expected Behavior__

When changing the element type of Events having `Timer Event Definitions`, validate and potentially remove unsupported `Timer Event Definition Types`.

__Environment__

- OS: Arch Linux
- Camunda Modeler Version: 4.8
- Execution Platform: Camunda Cloud
- Installed plug-ins: n/a

**Comment by barmac** [comment]
I am looking into this.

**Comment by barmac** [comment]
This will be fixed via https://github.com/camunda/camunda-bpmn-js-behaviors/pull/15

**Comment by philippfromme** [comment]
Closed by https://github.com/camunda/camunda-modeler/pull/3248.
