### ISSUE TITLE
Form Editor Shown Twice

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2371]
__Describe the Bug__

![kkjtnr5GLE](https://user-images.githubusercontent.com/7633572/125924054-bdb8cb52-3cb6-4ef1-9516-e2dafad6eb52.gif)

__Steps to Reproduce__

1. Create a new form
2. Add a `Button` form field
3. Switch to the JSON editor
4. Change the type to `""`
5. Switch to the form editor
6. Error is shown
7. Change the type back to `"button"`
8. Change the label to `"Submit"`
9. Switch to the form editor
10. Form editor is shown twice

__Expected Behavior__

Form editor is only shown once.

__Environment__

- Camunda Modeler Version: 4.9.0

**Comment by nikku** [comment]
I love that feature. Finally the split screen is there!

**Comment by philippfromme** [comment]
I cannot reproduce this issue anymore after integrating form-js 0.2.x (cf. https://github.com/camunda/camunda-modeler/tree/form-js-0.2). So this issue will be fixed once we merge this.

**Comment by nikku** [comment]
Fixed upstream then, great :muscle:.
