### ISSUE TITLE
New properties panel for Cloud: properties panel looses state in some situations

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2374]
__Describe the Bug__

In some cases, the new camunda cloud properties panel does not show the currently selected element. This bug was not present when using the old properties panel.

Related to https://github.com/bpmn-io/bpmn-properties-panel/issues/6

__Steps to Reproduce__

![CollabError](https://user-images.githubusercontent.com/42800119/126161645-50517e91-9f71-4add-a7b3-2d6b76a4c2ed.gif)

1. Create an empty cloud diagram
2. Drag a participant to the canvas
3. ==> Note the collaboration is shown in the properties panel but the participant is selected

__Expected Behavior__

The new properties panel remembers the currently selected element and also the sections which are open in all situations.

__Environment__

- OS: Manjaro Linux
- Camunda Modeler Version: https://github.com/camunda/camunda-modeler/commit/40832417aeaed32067244a047a37813e3e4bb629
- Execution Platform: Camunda Cloud
- Installed plug-ins: n/a

**Comment by pinussilvestrus** [comment]
Case 1 is related to https://github.com/bpmn-io/bpmn-properties-panel/issues/6

**Comment by pinussilvestrus** [comment]
The properties panel is losing its state because we currently re-render it with any [`attachTo`](https://github.com/bpmn-io/bpmn-properties-panel/blob/main/src/render/BpmnPropertiesPanelRenderer.js#L59), therefore with any mount of the editor. 

To fix this problem we would need to prevent re-rendering or persist the state.

**Comment by MaxTru** [comment]
Similar issue, but maybe also relevant to consider: https://github.com/bpmn-io/properties-panel/issues/63 (here the state is persisted, even though it shouldn't -> so the other way around)

**Comment by MaxTru** [comment]
Case 2 fixed upstream via https://github.com/bpmn-io/bpmn-properties-panel/pull/40

**Comment by pinussilvestrus** [comment]
I updated the description to indicate the missing bits (collaboration creation).

**Comment by MaxTru** [comment]
Since the collaboration creation bug is not critical, I will de-milestone this for 4.10.0
