### ISSUE TITLE
Allow to deploy a diagram to a different Camunda Cloud region

### ISSUE THREAD

**Issue by menski** [camunda/camunda-modeler#2375]
__Is your feature request related to a problem? Please describe.__

With Camunda Cloud 1.1 we added a region to the URL of a Zeebe cluster to be able to route traffic to different regions. You can read a bit about it in the docs https://docs.camunda.io/docs/guides/update-guide/100-to-110#zeebe-java-client.

At the moment for all >= 1.0 clusters in Camunda Cloud only a single default region exists. But in the future we might add more, i.e. we plan to offer a new North America region in the near future.

The user has to be able to specify the region in some way to be able to deploy the diagram to a different region.

A workaround exists by using the Camunda Cloud Self Managed Oauth configuration in the deploy dialog.

__Describe the solution you'd like__

* [ ] Instead of using the `Cluster ID`, identify the cluster via the `Cluster URL`.
* [ ] Migrate existing configurations (that provided the `Cluster ID` only) to use `bru-2` (cf. https://github.com/camunda/camunda-modeler/issues/2375#issuecomment-889830410) as a region.
* [ ] Upon save or deploy persist the `Cluster URL` in the deployment profile

---

__Context and Prior Discussion__

@menski At the moment we offer three configuration fields in the deploy dialog, `Cluster ID`, `Client ID` and `Client Secret`.

![2021-07-19-14:52:20](https://user-images.githubusercontent.com/516296/126162502-f13cfe5a-0329-49b3-b76d-4972f8d79fdc.png)

I see two options but maybe there is another better one:
1. We add a fourth field `Region` to allow the user to specify the region
2. We replace the `Cluster ID` field by `Cluster URL` to allow users to enter the full URL including the region

In my opinion I would prefer option 2 as it is simpler for the user if we enable them to copy the whole address the same way they can copy the client id/secret. In Option 1 they have to copy to information which are always related and will never change separately.

**Comment by MaxTru** [comment]
Just to explore options: 
* would it also be an option to retrieve the region via the cluster id in the background so that the fields of the dialog would not have to be changed?

**Comment by menski** [comment]
We don't have any information which cluster id belongs to which region at the moment. So no it's not possible right now.

**Comment by MaxTru** [comment]
ok, thanks

**Comment by nikku** [comment]
Regarding the options:

* What is the best practice established by the Cloud team? Supported and documented in the Cloud console?
* Will using the URL circumvent caching issues with newly created clusters?

**Comment by nikku** [comment]
@menski This is not actionable for us, yet, cf. https://github.com/camunda/camunda-modeler/issues/2375#issuecomment-882720354.

**Comment by menski** [comment]
> What is the best practice established by the Cloud team? Supported and documented in the Cloud console?

Write now the java client and node-js client offer to specify the region as an extra parameter. But this was just added to stay backwards compatible, and there are justified concerns if this is a good UX, i.e., what is the point for the user to copy to values which are highly coupled.

> Will using the URL circumvent caching issues with newly created clusters?

I'm not sure which chaching you are referring too? There was the issue of negative DNS propagation issues before. But the change which is requiring this feature, actually removed the root cause of this DNS propagation problem.

**Comment by nikku** [comment]
> But the change which is requiring this feature, actually removed the root cause of this DNS propagation problem.

So we are safe to use URL, too. Thanks.

**Comment by nikku** [comment]
Follow up question:

Region is going to be a mandatory field? Or does it remain optional once introduced?

**Comment by nikku** [comment]
From what I can read in the documentation you use `ZeebeAPI` (or _audience_). I did not try out yet how the cloud presents the information (do you still feature _clusterID_ or do you provide the clusterURL_ to users. 

My two cents therefore are: Switch from cluster ID to _ClusterURL_ in the future, but only if

* that is done in the cloud console, too
* we can introduce that in a backwards compatible manner (i.e. we pick up the currently configured cluster IDs and generate cluster URLs from these, for all cloud >= 1.0 versions).

**Comment by menski** [comment]
> that is done in the cloud console, too

Right now the user is seeing the following modal when creating a secret
![2021-07-30-13:23:22](https://user-images.githubusercontent.com/516296/127646440-771d84c7-b37f-4dc6-a171-64b6c5e9e8b1.png)

Which we can easily extend to feature the Cluster URL additionally, which then matches the input fields of the modeler
![2021-07-30-13:25:04](https://user-images.githubusercontent.com/516296/127646517-26298d57-e666-42eb-9a5c-dabc546253a4.png)

If we decide to go for this in the modeler then I would make sure that the console will present the cluster URL prominent to the user, and also that the Java and Nodejs client can work with it.

> we can introduce that in a backwards compatible manner (i.e. we pick up the currently configured cluster IDs and generate cluster URLs from these, for all cloud >= 1.0 versions)

All saved credentials can only refer to the current defaut `bru-2` region, therefore I think it is save to generate the URL out of the saved cluster id on migration.

**Comment by nikku** [comment]
Perfect. Given your confirmation I believe we should settle down on that option: Rename `Cluster ID` to `Cluster URL` + auto-migrate existing deployment configs.

**Comment by nikku** [comment]
I've updated the issue accordingly.

**Comment by MaxTru** [comment]
What is the timeline for this? 

@menski , would it be okay if we plan this for Q4 or do you expect that the new region will come sooner than that?

cc. @volkergersabeck

**Comment by menski** [comment]
We will roll out the changes required in Cloud https://github.com/camunda/camunda-modeler/issues/2375#issuecomment-889830410 probably this week, see https://github.com/camunda-cloud/console/pull/2382

As far as I know the new region is already setup, I can double check with Felix if we will promote it soon

**Comment by MaxTru** [comment]
Marked for 4.10 release

**Comment by MaxTru** [comment]
Aligned with @menski :

When validating the URL, we can assume that the format must match
`<someId>.<airport>-<number>.zeebe.camunda.io:443`

* Potentially `https://<someId>.<airport>-<number>.zeebe.camunda.io:443` is also okay, but this shall be tested with `zeebe-node`

**Comment by menski** [comment]
The changes https://github.com/camunda-cloud/console/pull/2382 are live in console in production and can be used for testing.

**Comment by pinussilvestrus** [comment]
When viewing the client connection details, I can't see the cluster URL

![image](https://user-images.githubusercontent.com/9433996/132697489-85b2e5bc-f235-40ed-a4e9-a63e255f172b.png)

It's only visible after creating a new client

![image](https://user-images.githubusercontent.com/9433996/132697356-906ba490-b4bf-44c6-8af1-56d77554a8f0.png)

Is this intended? /cc @menski

**Comment by menski** [comment]
No let me create an issue in console to get that fixed
