### ISSUE TITLE
Update element templates docs to indicate Platform

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2382]
__What should we do?__

[Element templates](https://github.com/camunda/camunda-modeler/tree/develop/docs/element-templates) are a Camunda Platform only feature. Since we now have Camunda Cloud diagram also editable in the Camunda Modeler, we should make clear that this feature is for Camunda Platform BPMN diagrams only.

* [ ] Add a note on top to indicate Camunda Platform only support.

__Why should we do it?__

Minimize confusion, cf. https://forum.camunda.org/t/element-templates-with-camunda-cloud/29028/2

**Comment by nikku** [comment]
I believe this is best  done along with a general documentation overhaul. From the looks of it the screenshots would need to be updated to the new UI, too.

**Comment by pinussilvestrus** [comment]
This can be closed since we now as we updated the docs to clarify the execution platforms: https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/defining-templates/
