### ISSUE TITLE
Pressing `Delete` in Literal Expression Editor Leads to Error

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2386]
__Describe the Bug__

Pressing `Delete` in the literal expression editor eeads to an error since the respective editor action doesn't seem to be implemented in that editor.

![DmqHvJZjtk](https://user-images.githubusercontent.com/7633572/127978060-160eb158-a9a2-4cf5-bc02-31775edfa9f4.gif)

__Steps to Reproduce__

1. Open literal expression
2. Press `Delete`
3. Log opens with error

__Expected Behavior__

No error.

__Environment__

- Camunda Modeler Version: v4.9.0

---

Sentry Issue: https://sentry.io/organizations/camunda-modeling/issues/2404601390

**Comment by pinussilvestrus** [comment]
Is this related to https://github.com/camunda/camunda-modeler/issues/2095?

**Comment by philippfromme** [comment]
Oh, yeah, it's a duplicate. Closing this in favor of #2095.
