### ISSUE TITLE
Copy version info, installed plugins, OS

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#2388]
As a user, it would encourage me to provide feedback more often if I could easily copy the version info, installed plugins, O, etc. out of the tool. Especially the version number of nightly builds and the list of installed plugins takes a lot of time to manually type into a bug report and is likely not as precise as it could be when exported by the tool.

Bonus would be some more direct integration of feedback in the UI like in Cawemo.

**Comment by pinussilvestrus** [comment]
Thanks for reporting! Do you have already an idea / sketch in mind how to get this information in the UI? Via menu option? Shortcut? Something else?

**Comment by falko** [comment]
Intuitively have been searching for some kind of about screen in the help menu to copy from and I tried clicking on the version number displayed in the bottom right corner and tried to copy from that pop-up. A link inside that pop-up would also work. But really anything goes. I'm happy to also click a button or menu entry that prints all the info you'd like for a bug report to the log and copy it from there if that's easier to implement. Another option could be a file on disk or something printed to stdout but that might be harder to find for the average user.

**Comment by pinussilvestrus** [comment]
I think there is definitely something we can do to improve the way of providing such details. I will move this one to backlog 👍

**Comment by barmac** [comment]
This is how a feedback form looks in VS Code:

![image](https://user-images.githubusercontent.com/28307541/128836160-410e1ec9-3935-4b80-bc59-965c6ff7e31b.png)

**Comment by nikku** [comment]
If I understand you correctly Falko improving our existing report a bug feature, to include that information would work? 

![capture SRdV6Z_optimized](https://user-images.githubusercontent.com/58601/129549987-a946b9b0-c646-4fa8-858c-0b8f56d9cb2f.gif)

**Comment by ingorichtsmeier** [comment]
Hi @nikku,

nice idea for a shortcut, but sometimes you need information on other places than a bug report for the modeler.

From my perspective, it would not work.

**Comment by nikku** [comment]
> but sometimes you need information on other places than a bug report for the modeler.

Where exactly do you need that information and what specific information would you need?

Adding a `Copy ABC info` to the help menu would be an alternative in these cases. In that cases, we'd still need to settle down on the information you need.

**Comment by ingorichtsmeier** [comment]
> Where exactly do you need that information

Customer emails, Jira tickets, forum posts, slack messages, ...

> what specific information would you need?

Version, Build number, Operating System, Installed plugins (Name and version). Should be the infos that you request on a bug report.

**Comment by nikku** [comment]
Thanks for your feedback everyone. I think we have enought information to act on this one.

**Comment by andreasgeier** [comment]
Since @MaxTru will work on this during the Sommer Wrap week, we discussed and agreed on a solution. This will not only allow users to copy the system information to the clipboard but will also introduce the feedback button to the status bar and brings the feedback and copy feature together.

<br>

![Screen Shot 2021-08-18 at 17 13 30](https://user-images.githubusercontent.com/938244/129925366-454afcda-23ca-4391-8b21-817a9b54db2d.png)

<br>

Please note:
- The second feedback option (email) is in discussion and not yet decided
- The status bar icon can be found here: https://github.com/camunda/camunda-modeler-design/blob/main/icons/feedback.svg
- The existing help menu entry "Report Issue" opens that overlay instead of directly jumping to GitHub
