### ISSUE TITLE
Editor actions keyboard bindings involve even devTools

### ISSUE THREAD

**Issue by Ichigo85** [camunda/camunda-modeler#2389]
__Describe the Bug__

While inspecting Camunda Modeler to debug something in token simulation, just typing the T key in the devTool area (console) activate/deactivate Token simulation, making impossible to debug. This happens for (I think) every keybinding related to the canvas palette, too.

__Steps to Reproduce__

1. Open devTools
2. Set focus on them
3. Just press 'S' or 'T'

__Expected Behavior__

Keybindings should work only inside the 'canvas' scope, I think.

__Environment__

- OS:  Windows 10
- Camunda Modeler Version: 4.9.0
- Installed plug-ins: [Token simulation]

**Comment by pinussilvestrus** [comment]
In which scenarios would you need to open the dev tools?

**Comment by Ichigo85** [comment]
> In which scenarios would you need to open the dev tools?

I am developing different plugins and I use dev tools to debug them.

**Comment by pinussilvestrus** [comment]
I see, I can think that this might a bit frustrating. Let's see how we can improve the situation.

Moving it to backlog.

**Comment by barmac** [comment]
I found out that within the dev tools we can only trigger shortcuts registered in the menu. We could handle the single letter (or all) shortcuts only via the keyboard event listeners instead. For that, we should pass `registerAccelerator=false` when we create menu items. Cf. https://www.electronjs.org/docs/api/menu-item

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2396

**Comment by nikku** [comment]
Created a follow up based on your comment: https://github.com/camunda/camunda-modeler/issues/3096
