### ISSUE TITLE
Make existing intermediate events attachable

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#239]
It would be nice to being able to attach existing intermediate events to tasks and subprocesses and morph them to boundary events right away. I now this requires a change of the actual element type, but users know that feature from other modeling tools.

---

Upstream issue: https://github.com/bpmn-io/bpmn-js/issues/478

**Comment by nikku** [comment]
Which other modeling tools allow this?

**Comment by nikku** [comment]
And based on that: What is the use case, i.e. when would you like to change an intermediate event to a boundary event?

**Comment by benhoffmann** [comment]
I know that know such behaviour from Signavio and ARIS (not sure about ARIS, though) and during my last BPMN training some attendees asked about that as well. For BPMN beginners, this might be the expected behaviour, because those intermediate elements look the same and are both accessible from the same pallette element.

One possible use case: reorganize a model and convert events which followed an event-based gateway to boundary events without loosing the sequence flow and attributes.

Another one: drag an element from the context menu, remove the sequence flow and try to make a boundary event out of it (this happened when we told the attendees to "forget" about the pallette in the beginning of the training to help them select the right elements and model syntactically correct)

**Comment by nikku** [comment]
Thanks for the clarification. 

> For BPMN beginners, this might be the expected behaviour, because those intermediate elements look the same and are both accessible from the same pallette element.

We should implement it just because of that.

**Comment by nikku** [comment]
Needs fix via https://github.com/bpmn-io/bpmn-js/issues/478.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1404.
