### ISSUE TITLE
Compensation: Compensation Sub-Process appears in list of activities to be compensated

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda-modeler#2397]
__Describe the Bug__

When modeling a compensation, the throwing compensation event allows to only compensate one activity. This can be chosen from a dropdown in the properties panel.

A compensation can be modelled as a sub-process.

The sub-process should not appear in the list of activities to be compensated (as it is the compensation activity), but it does.

__Steps to Reproduce__

1. Create a simple process with one activity that has a compensation boundary event and a compensation end event
2. Add a compensation task to the compensation boundary event
3. When configuring the end event, you can select the activity with the compensation boundary event to be compensated exclusively
4. Change the type of the compensation task (the one that is compensating), to a sub-process
5. Now, when configuring the end event, you can select the activity as before PLUS the compensation sub-process
![capture 7DSsz7_optimized](https://user-images.githubusercontent.com/81753891/129912405-d3f52110-f9ac-4794-869c-603e6f286d82.gif)

__Expected Behavior__

In step 5, the content of the dropdown should not have changed as no more activities that can be compensated were inserted

__Environment__

- OS: MacOS 11.5.2
- Camunda Modeler Version: 4.9.0
- Execution Platform: Camunda Platform
- Installed plug-ins: token-simulation, rename-technical-ids, bpmn-linter, property-info, tooltip, transaction-boundaries, could-connect

**Comment by MaxTru** [comment]
I can re-produce this. Thanks for reporting! 

Moving it to the backlog. Additionally, we will ensure this bug is not re-introduced in the new properties panel (see https://github.com/bpmn-io/bpmn-properties-panel/issues/2) (Thanks @barmac for linking)

**Comment by pinussilvestrus** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-properties-panel/commit/02fffa5066e007e7c4cf048cffee9ea5a8b87658. Will be released when we integrate the new properties panel for platform properties.
