### ISSUE TITLE
Show snap lines across pools and subprocesses

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#240]
Currently no snap lines are shown when I try to align elements from different pools unless I attach a message flow to them. It would be useful to have snap lines by default.

**Comment by nikku** [comment]
That would mean having thousands of snap lines and points across huge diagrams. Any idea how to circumvent / optimize this?

I.e. try to edit [this diagram here](http://demo.bpmn.io/s/application-processing) and imagine all elements snapping.

**Comment by benhoffmann** [comment]
Good point. Maybe only show snap lines to elements within the current view?

**Comment by berndruecker** [comment]
I would actually expect not to have too many snap lines in reality, as you typically snap across pools (resulting in some kind of "grid"). But it is a possibility. Only take the ones in the current view sounds like a pragmatic solution :-)

**Comment by falko** [comment]
+1
See also #652 and #653

**Comment by nikku** [comment]
The latest version of the app supports grid snapping.

That should get you covered, without cross-participant snap lines I guess.
