### ISSUE TITLE
Switching between XML and Diagram needs better info message

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#241]
Switching back to the Diagram tab after making XML changes results in a message letting the user know that editing history is going to be lost and so you'll no longer be able to undo actions.
The message options are a little confusing:
![tabswitch](https://cloud.githubusercontent.com/assets/10612634/14013593/a3653374-f1ad-11e5-8e0e-6c7d71d0155a.PNG)

After getting the opinion of no less than 2 other consultants i would like to suggest renaming the info message:

"Switching tabs after XML changes will remove the diagram's undo history
Would you like to proceed?" 

and the buttons as follows:

Cancel
Yes - lose undo history
Yes - lose xml changes

**Comment by nikku** [comment]
Different solution (proposed by customers):

* Remove the dialog all together and replace it with a warning, shown on the diagram view "Import from XML cleared undo history". 

* Another solution:

* Remove dialog without replacement

Either way is less annoying for users that switch between BPMN and XML regularily; these people generally know what they are doing anyway. The everyday normal guy users (that do not even know undo exists) do not care about history anyway.

**Comment by ricardomatias** [comment]
We've got a solution for this.

Check #346 for more information.
