### ISSUE TITLE
Select all is not working in forms properties panel

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2411]
__Describe the Bug__

Executing Cmd+A inside a text input in the forms properties panel does not do anything.

<img height="500" src="https://user-images.githubusercontent.com/9433996/132651853-d61b2c58-af70-49ec-8228-21758263e46e.gif" />

__Steps to Reproduce__

1. Create a new form field
2. Select "field label"
3. Press Cmd + A 
4. See that the content of the input is not selected

__Expected Behavior__

The content of the input is selected completely.

__Environment__

- OS: macOS 11.5
- Camunda Modeler Version: 4.10.0-rc.0

This is not a regression from the latest release, but already discoverable in Camunda Modeler 4.9.0.

**Comment by philippfromme** [comment]
Cannot reproduce on Windows ™️ 

![XsYARR1oqj](https://user-images.githubusercontent.com/7633572/132655291-20645f82-7f51-4120-81c2-b0a2dc261cd6.gif)

**Comment by MaxTru** [comment]
Good catch!
Cannot reproduce on Linux (Arch) either

**Comment by pinussilvestrus** [comment]
@barmac @andreasgeier @volkergersabeck @smbea can you reproduce this on your machine? Maybe it's just a personal setup thing...

**Comment by smbea** [comment]
I am on Mac and have the same issue - can't select the input with Cmd + A

**Comment by andreasgeier** [comment]
I can reproduce it on Mac 11.5.1 and Modeler 4.9.0

**Comment by nikku** [comment]
It is related to editing roles being required for `CMD+XXX` to work on MacOS. Apparently these are not properly integrated yet.

**Comment by philippfromme** [comment]
Closed by https://github.com/camunda/camunda-modeler/pull/2665.
