### ISSUE TITLE
Cover Features in Integration Tests

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2412]
__What should we do?__

The following new features are not covered in the [integration tests](https://github.com/camunda/camunda-modeler/blob/master/docs/.project/INTEGRATION_TEST.md):

* new form editor features (new form fields)
* execution platform
* linting

__Why should we do it?__

We need to ensure that these essential features are working in every release.

**Comment by nikku** [comment]
Let us schedule this for v4.11. Contract: We close this issue either by expanding our integration tests or because we do not act.

**Comment by philippfromme** [comment]
Yes, my idea was to add integration test to https://github.com/camunda/camunda-modeler/blob/master/docs/.project/INTEGRATION_TEST.md for the next release.
