### ISSUE TITLE
'Include additional files' default folder when deploying from Modeler 

### ISSUE THREAD

**Issue by superbeagle** [camunda/camunda-modeler#2418]
__Is your feature request related to a problem? Please describe.__
In deploying processes from Modeler the 'Include additional files' button opens an arbitrary folder, not the process diagram folder. 

In deploying processes from Modeler the 'Include additional files' button opens an arbitrary folder, not the process diagram folder. As a result I kept deploying the wrong form since I assumed it was the form in the same folder as the process diagram, not an arbitrary folder containing a file with the same name - 'form_1.form' 

__Describe the solution you'd like__

I would like Modeler to open the folder of the process diagram. It would be similar to the behavior when you attempt to open another file in Modeler - it open the folder of the currently displayed diagram

__Describe alternatives you've considered__

__Additional context__

Add any other context or screenshots about the feature request here. For example, provide the execution platform you're operating on (Camunda Platform, Camunda Cloud, ...).

**Comment by nikku** [comment]
> I would like Modeler to open the folder of the process diagram. It would be similar to the behavior when you attempt to open another file in Modeler - it open the folder of the currently displayed diagram

As a default action we open the folder a user last opened  from or saved to. I can reproduce the "add additional files" behavior deviates from that (opens some random folder). 

To confirm your assessment: Would you be fine with the existing behavior, if it worked consistently? Or would you deviate from it  to open the folder containing the to-be-deployed diagram.

**Comment by nikku** [comment]
Marking this one as a bug, as it does not confirm to our expected standard behavior.

**Comment by superbeagle** [comment]
I think it would be more intuitive if it opened the folder of the to be deployed diagram. In all likelihood it will be the same folder as other files, including forms. It would be consistent with the behavior when opening other files in Modeler.

**Comment by Skaiir** [comment]
@superbeagle The issue no longer seems to exist on the latest version of the modeler. Can you still replicate? If not I'll close it. :)
