### ISSUE TITLE
[Cloud] I can model a message throw event and message end event

### ISSUE THREAD

**Issue by saig0** [camunda/camunda-modeler#2420]
__Is your feature request related to a problem? Please describe.__

**Camunda Cloud** will support message throw events (intermediate message throw event & message end event) in version `1.2.0`. In this version, the message events are handled like service/send tasks and have the same properties (i.e. job type, job retries, custom task headers, input & output variable mappings).

As a user, I want to model a process with message throw events. 

__Describe the solution you'd like__

I can model intermediate message throw events & message end events in my process.
I can set the same properties on the event as for service/send tasks.

__Breakdown__

- [x] Enable replace to Message Throw Event camunda/camunda-bpmn-js
- [x] Enable replace to Message End Event camunda/camunda-bpmn-js
- [x] [Overwrite the Message Section in bpmn-io/bpmn-properties-panel for Camunda Cloud for Message Throw and Message End Events](https://github.com/bpmn-io/bpmn-properties-panel/pull/114#pullrequestreview-758410701)
- [x] [Make Message Throw Event and Message End Event "serviceTaskLike" in zeebe-io/zeebe-bpmn-moddle](https://github.com/zeebe-io/zeebe-bpmn-moddle/pull/15)
  - [x] Ensure that only messageThrowEvents and messageEndEvents (e.g., events with messageEventDefinition), are valid by using extension behaviour to manage these
- [x] [Update properties panel for Message Throw Event and Message End Event in bpmn-io/bpmn-properties-panel](https://github.com/bpmn-io/bpmn-properties-panel/pull/116)
   - [x] Release updated version of zeebe-bpmn-moodle
- [x] [Add serviceTaskLike properties section for Message Throw Event and Message End Event in camunda/camunda-bpmn-js (**in the old properties panel**)](https://github.com/camunda/camunda-bpmn-js/pull/55)
  - [x] Ensure that not all "endEvents" and "throwEvents" get this, (context: see [here](https://github.com/camunda/camunda-bpmn-js/pull/27/commits/bd80cee614553ac3cd522846c4044d3cf80c958e#diff-0ed88c55309981cacf670f359e045d099a198f98f14b33d00c88a5daf69d1b18R47), [here](https://github.com/camunda/camunda-bpmn-js/pull/27/commits/bd80cee614553ac3cd522846c4044d3cf80c958e#diff-8294c84621c1bb029491aa223b1acc3661b882ccec92ae1c2a3f2e11741533d6R16) and [here](https://github.com/camunda/camunda-bpmn-js/pull/27/commits/bd80cee614553ac3cd522846c4044d3cf80c958e#diff-7b23f796d75c74b001659762706cd0c2d132d0c95676f18612e31c234b923ad6R105), and maybe more)
- [x] Update and integrate bpmn-properties-panel and camunda-bpmn-js into camunda-modeler
  - [x] Release updated version of bpmn-properties-panel
  - [x] [Release updated version of camunda-bpmn-js](https://github.com/camunda/camunda-bpmn-js/issues/51)
  - [x] Integrate updated versions into camunda-modeler
 
__Describe alternatives you've considered__

None.

__Additional context__

Related Zeebe issues: camunda-cloud/zeebe#7763 and camunda-cloud/zeebe#7796.

**Comment by MaxTru** [comment]
@saig0 just to ensure:

* This means we would **not** allow to model the bpmn-specific `messageRef` (e.g., like so:
```
<bpmn:intermediateThrowEvent id="Event_05h4m4x">
    <bpmn:messageEventDefinition id="MessageEventDefinition_1xbxlse" messageRef="Message_0acxwhg" />
</bpmn:intermediateThrowEvent>
<bpmn:message id="Message_0acxwhg" name="Message_0sfsina">
  <bpmn:extensionElements>
    <zeebe:subscription correlationKey="abc" />
  </bpmn:extensionElements>
</bpmn:message>
```)

Could you please confirm? Thanks

**Comment by saig0** [comment]
> Could you please confirm?

Yes, confirmed :heavy_check_mark: 

A message throw event doesn't need to reference a message. It could but at the moment, Zeebe will ignore it. To avoid confusion for the user, we could not allow setting a message.

**Comment by smbea** [comment]
Currently, in `zeebe-bpmn-moddle` it's only possible to add the "serviceTaskLike" like properties to any endEvent/intermediateThrowEvent (regardless if they are message events) or to any messageDefinitions (regardless if they belong to any end or intermediate throw events).

To implement this, it will require an extension behaviour to manage these properties.
