### ISSUE TITLE
External labels cannot be deleted (clearing the text)

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#243]
Users assume that deleting an external label unsets the name of an element (cf. [forum](https://forum.bpmn.io/t/sequence-flow-text-cannot-be-deleted-with-latest-bpmn-js/591/2)).

Gets adressed via bpmn-io/bpmn-js#503

**Comment by philippfromme** [comment]
Copy and paste tests are skipped due to bugs that need a bigger refactoring.

**Comment by nikku** [comment]
What is our plan regarding copy and paste now? My guess is you should create issues for the things that we still need to refactor to complete this ticket. Or is it _broken_ in a sense that it is still somewhat usable and no change is required?

**Comment by nikku** [comment]
I've [added a few comments](https://github.com/bpmn-io/bpmn-js/commit/702c45b25f6ba787a38f31bc140dafb33fd2da3c#comments) on the implementation. For bigger issues such as this one it probably makes sense to file a PR (for better discussion support).
