### ISSUE TITLE
As a user I want to be able start a process instance with variables.

### ISSUE THREAD

**Issue by aivinog1** [camunda/camunda-modeler#2437]
__Is your feature request related to a problem? Please describe.__

I create it from the discussion: https://forum.camunda.org/t/how-can-i-start-a-process-instance-with-process-instance-variables-via-camunda-modeler/30176. Right now there is no way to start a process instance with variables.

__Describe the solution you'd like__

In the start process instance modal I want to see some sort of table, that I can fill up with variables.

**Concretization based on comments below**

**First increment / quick-fix**

* [x] Offer a basic textArea, allowing the user to input JSON data to specify processVariables (see [comment](https://github.com/camunda/camunda-modeler/issues/2437#issuecomment-924708148))
  * [x] #2693
  * [x] #2678

**More sophisticated solution**

* [ ] Develop UI sketch letting the user input various variables with different types based on some input fields (see [comment](https://github.com/camunda/camunda-modeler/issues/2437#issuecomment-924072215))
* [ ] Implement the solution based on UI solution
  * [ ] Camunda Cloud (see https://docs.camunda.io/docs/reference/grpc#createprocessinstance-rpc)
  * [ ] Camunda Platform (see https://docs.camunda.org/manual/7.15/reference/rest/process-definition/post-start-process-instance/#request-body)

__Describe alternatives you've considered__

I can't see any alternatives here. Probably design a separate modal for it.

__Additional context__

I want to see it on the Camunda Platform diagram, but I think that this would be useful on Camunda Cloud diagrams too.

**Comment by MaxTru** [comment]
Interesting requirement, thanks for reporting @aivinog1 .

processVariables might have different types, and based on the type, the value to be provided can be less or more complex from my understanding. For example:
* Type could be `Object`
* In this case one would need to provide some serialized `Value` as string and additionally some `valueInfo` as JSON with `objectTypeName` and `serializationDataFormat`

(See [docs](https://docs.camunda.org/manual/7.15/reference/rest/process-definition/post-start-process-instance/)).

What solution would you propose here? I could image a very basic solution (e.g., just allow primitive types, then use a table as input), or something more complex (like an additional dialog or modal) when all types shall be supported.

**Comment by ingorichtsmeier** [comment]
As a first step I would like to get a text area where I can type the same content for `variables` as I use in the plain rest api (with Postman or curl or...) : https://docs.camunda.org/manual/7.15/reference/rest/process-definition/post-start-process-instance/#request-body.

Something like:
```
{
    "aVariable" : {
        "value" : "aStringValue",
        "type": "String"
    },
    "anotherVariable" : {
      "value" : true,
      "type": "Boolean"
    }
  }
```

**Comment by MaxTru** [comment]
I edited the issue to give solution approaches in two steps: a first pragmatic quick-fix, then potentially a UI-guided input-based solution

**Comment by aivinog1** [comment]
Hey @MaxTru, I think that I can try to contribute a developer-friendly approach if this is not occupied already :)

**Comment by MaxTru** [comment]
> Hey @MaxTru, I think that I can try to contribute a developer-friendly approach if this is not occupied already :)

Sure, that would be great :-)

**Comment by MaxTru** [comment]
> As a first step I would like to get a text area where I can type the same content for `variables` as I use in the plain rest api (with Postman or curl or...) : https://docs.camunda.org/manual/7.15/reference/rest/process-definition/post-start-process-instance/#request-body.
> 
> Something like:
> 
> ```
> {
>     "aVariable" : {
>         "value" : "aStringValue",
>         "type": "String"
>     },
>     "anotherVariable" : {
>       "value" : true,
>       "type": "Boolean"
>     }
>   }
> ```
> 
> This is the developer friendly way. The user friendly way would be a lot more complicated, I think.

This was implemented via https://github.com/camunda/camunda-modeler/pull/2443 and was merged to develop.

Open: camunda cloud solution

**Comment by MaxTru** [comment]
Also reference here: https://docs.camunda.io/docs/components/modeler/cloud-modeler/start-instance/ for how Cloud Modeler does it

**Comment by MaxTru** [comment]
We have the basic solution running for Cloud and Platform. Hence I am closing this issue. We can create another one, if the current solution does not work UX-wise (based on feedback).
