### ISSUE TITLE
The copy of a subprocess is not identical with the original

### ISSUE THREAD

**Issue by CatalinaMoisuc** [camunda/camunda-modeler#2438]
__Describe the Bug__

When copy-pasting a sub-process, the type of the start event is lost.

__Steps to Reproduce__

[11700-example.bpmn.zip](https://github.com/camunda/camunda-modeler/files/7208405/11700-example.bpmn.zip)

1. Open the attached BPMN in Camunda Modeler 4.10.0 (actually in any version after 4.7.0)
2. Copy the given sub-process, then paste it in the same diagram
3. Please observe how the `Error Start Event` becomes a simple `Start Event` in the copy of the original sub-process

__Expected Behavior__

The copy and the original sub-process should be identical.

__Environment__

- OS: [MacOS 11.4]
- Camunda Modeler Version: [>4.7]
- Execution Platform: [Camunda Platform]
- Installed plug-ins: [not relevant for this bug]

---

Depends on https://github.com/bpmn-io/bpmn-js/issues/1696
Referenced via [SUPPORT-11700](https://jira.camunda.com/browse/SUPPORT-11700)

**Comment by MaxTru** [comment]
Thanks for reporting, I can re-produce it. We will take a look

**Comment by barmac** [comment]
Intersting finding: The replacement does not occur if I drop the event subprocess on a sequence flow.


https://user-images.githubusercontent.com/28307541/137483820-8aebf79c-a005-4d73-881f-90c94658cb6a.mov

**Comment by barmac** [comment]
Prototypical solution: https://github.com/bpmn-io/bpmn-js/tree/properly-replace-elements-on-create

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/3065.
