### ISSUE TITLE
Make tab navigation easier when working with many tabs & long tab names

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2440]
__Is your feature request related to a problem? Please describe.__

Reported via https://jira.camunda.com/browse/SUPPORT-7415.

When working with many open tabs and long tab filenames, it becomes hard to navigate / maintain overview.

__Describe the solution you'd like__

Two solution options are seen:

1. Trim tab description of too many tabs are open and tab names are too long.
2. Offer dropDown (in case not all tabs can be shown?) to allow quicker tab navigation
  * See sketch
![image](https://user-images.githubusercontent.com/42800119/134634184-c67c1d1e-a4a8-4ffe-aac4-2479f77a54d9.png)

__Describe alternatives you've considered__

:arrow_up: 

__Additional context__

https://jira.camunda.com/browse/SUPPORT-7415

**Comment by andreasgeier** [comment]
In the new Modeler UI architecture, these topics are already considered. They are currently in design development.

A tab action area with access to all opened editors (see "tab context menu"): https://github.com/camunda/camunda-modeler-design/issues/36
A redesigned tab area with tabs that shrink: https://github.com/camunda/camunda-modeler-design/issues/37

**Comment by andreasgeier** [comment]
Both mentioned design tasks are now defined and ready to review and kickoff.

The feedback from here has been considered: Tabs now have equal widths and a max-width. And a list of opened editors is provided as a dropdown.

![Screen Shot 2021-10-01 at 17 09 33](https://user-images.githubusercontent.com/938244/135644008-4fb3459c-818b-4618-8a6a-6b98241bf21f.png)

![Screen Shot 2021-10-01 at 17 09 49](https://user-images.githubusercontent.com/938244/135644059-738ed3e2-d5a0-4719-9425-78d174388794.png)

**Comment by nikku** [comment]
Feedback @nikku (2021-12-06) regarding the new tab design: I find it odd that we now truncate tabs in all cases, also when there is sufficient space available (cf. screenshot below).

My expectation would be that truncation is not required in the happy path, i.e. with concisely named diagrams. We do already truncate with newly created diagrams, which looks odd: 

![image](https://user-images.githubusercontent.com/58601/144844183-411f6d3d-523e-4163-beaa-6de5f68d6981.png)


For reference, browsers, i.e. Chrome, if taken as a reference, _do not truncate_ per default (which is what I'd expect): 

![image](https://user-images.githubusercontent.com/58601/144844064-e3e51c16-9156-43a0-a9f8-32a4f1a19b63.png)

**Comment by MaxTru** [comment]
> Feedback @nikku (2021-12-06) regarding the new tab design: I find it odd that we now truncate tabs in all cases, also when there is sufficient space available (cf. screenshot below).
> 
> My expectation would be that truncation is not required in the happy path, i.e. with concisely named diagrams. We do already truncate with newly created diagrams, which looks odd:
> 
> ![image](https://user-images.githubusercontent.com/58601/144844183-411f6d3d-523e-4163-beaa-6de5f68d6981.png)
> 
> For reference, browsers, i.e. Chrome, if taken as a reference, _do not truncate_ per default (which is what I'd expect):
> 
> ![image](https://user-images.githubusercontent.com/58601/144844064-e3e51c16-9156-43a0-a9f8-32a4f1a19b63.png)

I agree.

Otherwise the customer who reported the feedback of this issue might likely feel that we actually deprecated quality rathen than increased quality with 5.0.0. cc @andreasgeier @pinussilvestrus

**Comment by pinussilvestrus** [comment]
> For reference, browsers, i.e. Chrome, if taken as a reference, do not truncate per default (which is what I'd expect):

Chrome also truncates per default as tabs reach a certain max-width. The max-width is just higher as in the new tab design. 

![image](https://user-images.githubusercontent.com/9433996/144849322-0d4042b8-2e43-43b5-8357-d6480c56a6d0.png)

**Comment by pinussilvestrus** [comment]
What I could imagine is to set our initial tab-width also higher so that the `default` tab names (diagram_1.bpmn) don't get truncated.

**Comment by nikku** [comment]
Exactly, I guess we got to find a good place in the middle. My personal favorite would be: Decrease the font size by 1 or 2 pixels, slightly increase the default width.

**Comment by andreasgeier** [comment]
@pinussilvestrus 

> What I could imagine is to set our initial tab-width also higher so that the `default` tab names (diagram_1.bpmn) don't get truncated.

That's a good idea! We can increase the initial width while keeping the other behaviors. Let's do it and change max-width from 160 to 220px. 

![Screen Shot 2021-12-06 at 14 52 26](https://user-images.githubusercontent.com/938244/144857917-cfa883fc-a5ce-41b9-9485-87110db74d17.png)

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2709
