### ISSUE TITLE
Upgrade our issue templates to use GitHub issue forms

### ISSUE THREAD

**Issue by Hard-Coder05** [camunda/camunda-modeler#2451]
__Is your feature request related to a problem? Please describe.__

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

__Describe the solution you'd like__

Camunda Modeler currently uses the older issue template format. Your task is to create GitHub issue forms for this repository. We can use Camunda Modeler's issue templates as a reference for this PR.

**Comment by Hard-Coder05** [comment]
I would like to work on this issue!

**Comment by Sri-vishnu-r1431** [comment]
I would like to work on this issue Kindly assign it to me under Hacktoberfest '21

**Comment by MaxTru** [comment]
Thanks for highlighting this. We will evaluate this feature for all of our [repos](https://github.com/camunda) and decide what do to. Closing this for now
