### ISSUE TITLE
Redesign the tab bar and the tab container (incl. '+' button and 'CTRL + T' improvement)

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2461]
> **This is an epic issue that may be broken down into multiple tasks if needed**

__What should we do?__

As part of our one Visual IDE improvements, we will improve the existing tab bar, tab container plus the way how to add new tabs.

![image](https://user-images.githubusercontent.com/9433996/135997114-30a0ba0e-9b61-4298-9207-efefc9ce0155.png)

That includes
- [x] #2562
- [x] #2563
- [x] #2556

* <del>add new shortcuts for respective actions (e.g. via [adding `accelerators` to tabs provider](https://github.com/camunda/camunda-modeler/commit/15f0cc882c090fbf46fb7e4a49e4ef25b874a5ed#diff-a8ee53f63c47900983b24616f87f9b04023e1b48be19fd3ee726d0138276b811), cf. [this discussion](https://github.com/camunda/camunda-modeler-design/issues/58) )</del> ==> Postponed
* <del>add new welcome tab behavior</del> ==> Postponed

__Why should we do it?__

The flat design fits into our visual IDE theme, provides a more user-friendly way of working with tabs, and makes the removal of the toolbar possible (via the new plus button).

Cf. https://github.com/camunda/camunda-modeler-design/issues/36
Cf. https://github.com/camunda/camunda-modeler-design/issues/37
Cf. https://github.com/camunda/camunda-modeler-design/issues/43

**Comment by pinussilvestrus** [comment]
> add new tab button

To be clarified whether this is part of this epic, or part of the toolbar replacement efforts.

**Comment by pinussilvestrus** [comment]
### Kickoff summary

Find here the link to the Miro board: https://miro.com/app/board/o9J_lh4pDM0=/

![image](https://user-images.githubusercontent.com/9433996/143039675-06cd8af7-dba6-4526-b73f-6f95aa92e336.png)

![image](https://user-images.githubusercontent.com/9433996/143039720-63c384ec-268c-4d91-b4fb-1e273e0a5afd.png)

**Comment by pinussilvestrus** [comment]
Since current unclarities, investigating better alternatives (command palette), and limited design resources, we decided to postpone the introduction of new shortcuts for creating new tabs + a new welcome tab / empty tab behavior.

**Comment by nikku** [comment]
Closed with https://github.com/camunda/camunda-modeler/pull/2616 being merged.
