### ISSUE TITLE
Compatibility of BPMN with Set Execution Platform and Version Is Indicated through Linting

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2464]
Basic linting infrastructure is in place. In the next step, the execution platform version can be set for Platform and Cloud BPMN diagrams. Compatibility is then indicated through the new linting view (_Modeling Guidance_).

### Sub Tasks

* [x] https://github.com/camunda/camunda-modeler/issues/2465
* [x] https://github.com/camunda/camunda-modeler/issues/2466
* [x] Form linting features `major.minor` only in error text / grammar (_not supported **in**_) corrected https://github.com/camunda/camunda-modeler/pull/2622
* [x] #2617
* [x] Spike: Cloud validation rules are a re-usable library
* [x] #2625

---

Pulled out the following tasks as (potential) follow-up activities:

* Spike: Validate `formRef`, introduced in Camunda 7.16 (https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/3)
* #2564
* #2623

---

See also [strategy document](https://docs.google.com/document/d/1Zt4rm5IDwfVsUtdMAOEwlRmpEqdli22Y_7iFqyKG3g4/edit#heading=h.6e7wd2v3vvn1).

**Comment by philippfromme** [comment]
@nikku Work in progress on https://github.com/camunda/camunda-modeler/tree/2464-bpmn-execution-platform-linting.

**Comment by nikku** [comment]
Scheduled a kick-off for next week. 

Development snapshot available on the branch.

**Comment by nikku** [comment]
Updated the issue in accordance to our kick-off findings.
