### ISSUE TITLE
Upgrade issue templates to use GitHub issue forms

### ISSUE THREAD

**Issue by Obnoxious-coder** [camunda/camunda-modeler#2468]
Upgrade currently available Issues Template with recently released Github issue forms

**Comment by pinussilvestrus** [comment]
Quoting a similar issue in one of our libraries (https://github.com/bpmn-io/form-js/issues/183)

> Thanks for highlighting this. We will evaluate this feature for all of our [repos](https://github.com/bpmn-io) and decide what do to. 

I think we would first need to clarify this internally, whether it makes sense for us at all. Closing it for now though.
