### ISSUE TITLE
Cannot deploy BPMN with Form Binding `latest`

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#2484]
__Describe the Bug__
When I want to deploy a camunda form with the form binding `latest`, the deployment fails with the following error:

```
ENGINE-09005 Could not parse BPMN process. Errors: 
* Invalid element definition: value for formRefBinding attribute has to be one of [deployment, latest, version] but was null | resource diagram.bpmn | line 8 | column 92 [ deploy-error ]
```
![recording (27)](https://user-images.githubusercontent.com/21984219/136962033-fd3b6be5-24d0-464a-bc58-52b58752443b.gif)

__Steps to Reproduce__

1. create a Platform BPMN diagram
2. add a User Task
3. configure a Camunda Form ref with binding `latest`
4. Try to deploy it
5. The error occurs

__Expected Behavior__

I can deploy the diagram.

__Hints__

When the Binding is set to `latest`, the xml attribute `camunda:formRefBinding` is removed. The platform expects it to be `camunda:formRefBinding="latest"`. In fact `camunda:formRefBinding` is required in all cases (https://github.com/camunda/camunda-modeler/issues/2484#issuecomment-941998160).

__Environment__
 * Version: 4.11.0
 * Operating System: Linux x86_64 amd64
 * Plugins: Cloud Connect
 * Execution Platform: BPMN - Camunda Platform (7.16)

**Comment by ingorichtsmeier** [comment]
As the binding=latest is assumed if the tag is missing in the XML for call activities (`camunda:calledElementRef`), shouldn't it be the same with `camunda:formRefBinding`?

And therefore fixed in the engine parser?
