### ISSUE TITLE
Status bar design finishing & migration to new UI Architecture

### ISSUE THREAD

**Issue by smbea** [camunda/camunda-modeler#2488]
> This is an epic issue that may be broken down into multiple tasks if needed

__What should we do?__

As part of our one Visual IDE improvements, we will resign the status bar and certain UI aspects.

Depends on (*):
- [x] https://github.com/camunda/camunda-modeler/issues/2458
- [x] https://github.com/camunda/camunda-modeler/issues/2539

__To Do__:

__Status bar__:
- [x] #2550 *
- [x] [Cloud connect] https://github.com/camunda/cloud-connect-modeler-plugin/issues/68 *
 - [x] camunda/camunda-modeler/pull/2559

 __Overlays__:
- [x] https://github.com/camunda/camunda-modeler/pull/2576 *
- [x] #2489

__Why should we do it?__

That's part of our one Visual IDE efforts.

**Comment by nikku** [comment]
Cf. also https://camunda.slack.com/archives/GP70M0J6M/p1637682262023100. I believe it makes sense to extract all basic formatting concerns into a re-usable stylesheet.

**Comment by barmac** [comment]
@smbea are we releasing the plugin soon? Camunda Modeler 5.0.0-alpha.0 is publicly available now.
