### ISSUE TITLE
Form Type Selection Is Misleading

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#2496]
__Describe the Bug__

The current form type selection on a user task is wrong.

![grafik](https://user-images.githubusercontent.com/7870843/137194109-b82464a9-1058-4212-8704-11c45b7942af.png)

The option `<none>` can contain form fields for generated forms.

The option `Embedded or External Task Form` shows the Formkey, which can be filled with a Formkey for a Camunda Form as well: https://docs.camunda.org/manual/7.16/user-guide/task-forms/#form-key

The option `Camunda Forms` opens the reference to a deployed form. Camunda Forms can be used by Formkey as well.

__Steps to Reproduce__

1. Create a new BPMN Process for Camunda Platform
2. Add a User task
3. Open the Form tab
4. Select an option from the dropdown

__Expected Behavior__

The names on the options should fit to the field that the developer has to fill after the selection.

If I select none, nothing else can be added.
I would like to select `Formkey` to fill a camunda Form Formkey.
I would like to select `Deployed form` to fill the reference to the deployed form.
I would like to select `Generated Form` to fill the form fields.

For a new user it seems that Camunda Forms always need a deployment.

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.11
- Execution Platform: don't care, But my preference is Spring-Boot, 7.16
- Installed plug-ins: 
![grafik](https://user-images.githubusercontent.com/7870843/137195204-76a4a356-c63a-4410-a882-4394248a886c.png)

---

Related to [CAM-14004](https://jira.camunda.com/browse/CAM-14004)

**Comment by ingorichtsmeier** [comment]
@nikku, I agree that on the long run Camunda Forms with `formRef` are better than using the `formKey`.

But right now the overall user experice is not good enough to prefer the `formRef` over the `formKey`.

I've collected my first impression in a JIRA-Ticket as well: https://jira.camunda.com/browse/CAM-14004

Another feature is missing to use `formRef` with binding latest easily: I cannot deploy my form after a change directly from the modeler. I will file another feature request for this.

**Comment by nikku** [comment]
You're talking about https://github.com/camunda/camunda-modeler/issues/2484 regarding the `latest` deployment binding, right? We've fixed that bug and will ship a patch release that corrects it.

**Comment by nikku** [comment]
Also: _Camunda Forms_ shall be featured first in the dropdown.

Also: Documentation shall be updated to reflect usages.

**Comment by nikku** [comment]
We plan to investigate this topic in Q1 along with general improvements to the Forms user journey.

**Comment by smbea** [comment]
It appears that since https://github.com/camunda/camunda-modeler/issues/2484 was fixed, the `formKey` vs `formRef` discussion is no longe an issue.

Currently working on a sketch solution to address the form type selection. So far, this is what I've come up with, with Andi's input - [see Miro board here](https://miro.com/app/board/uXjVOQb5RLM=/?invite_link_id=657175926579). I may reach out to you (@nikku @ingorichtsmeier) to further discuss this proposal as a possible solution.

**Comment by nikku** [comment]
I like the direction. :+1: from my side.

**Comment by smbea** [comment]
After talking with Andi, Nico and Ingo, this is ready for implementation

**Comment by barmac** [comment]
This one is in fact `fixed upstream` as long as we don't release and update `bpmn-js-properties-panel`.
