### ISSUE TITLE
Be Able to Deploy Forms Stand-Alone

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#2498]
__Is your feature request related to a problem? Please describe.__

As a developer I want to test my form. In the user task I use reference binding latest for my form. 

After some change in the modeler I want to check the form in the task list. To get the form deployed, I either have to use a different tool like curl, postman or Camunda Cockpit (EE) or deploy the process diagram and include the form in the deployment.

__Describe the solution you'd like__

The Camunda Form can be deployed directly from the modeler. Same as to deploy process diagrams or decision diagrams.

__Describe alternatives you've considered__

Deploying with another tool, but this is poor developer experience.

__Additional context__

See https://jira.camunda.com/browse/CAM-14004.

**Comment by smbea** [comment]
This will only be possible for Platform forms, at the moment. To my knowledge, Cloud isn't prepared to deploy forms - it doesn't allow so in the web modeler
