### ISSUE TITLE
Exported PNG/JPEG does not show "Default Flow" marker correctly

### ISSUE THREAD

**Issue by usuppa** [camunda/camunda-modeler#250]
Hey guys,

I just noticed, that if you create a "Default Flow" in your process model and export the model as PNG or JPEG the "Default Flow" marker gets lost. You can only find a black and a grey pixel near the Sequence Flow. 

As an example I marked the sequence flow to task 3 as "default":

![diagram_1](https://cloud.githubusercontent.com/assets/17964661/14534060/db5cff12-0267-11e6-97b7-649dad286c06.png)

Version 0.6.0 on Windows 7 64Bit

Cheers, Uli.

---

See also [SUPPORT-2631](https://app.camunda.com/jira/browse/SUPPORT-2631).

**Comment by vladimirskatusenoks** [comment]
Hi, thanks for reporting this.

Just verified - does not work properly on all platforms.

N.B. `SVG` export works correctly.

**Comment by StephenOTT** [comment]
Any expected fix on this?  in backlog, so assume it is low priority, but just check in 😄

**Comment by nikku** [comment]
Yea, low priority right now. Needs fix in [canvg-browser](https://github.com/bpmn-io/canvg-browser).

**Comment by nikku** [comment]
Could be worth checking if that stuff is fixed in upstream canvg (cf. https://github.com/camunda/camunda-modeler/issues/423).

**Comment by ricardomatias** [comment]
I've checked the original canvg repo and there was nothing added that fixes this.

**Comment by nikku** [comment]
Needs fix in bpmn-js SVG generation (see attached commit).
