### ISSUE TITLE
'exporter' and 'exporterVersion' XML attributes are misleading

### ISSUE THREAD

**Issue by vkatushenok** [camunda/camunda-modeler#251]
On existing diagrams, that have been created with other tools/old modeler/eclipse plugin, the attributes are not updated and are misleading.

E.g. 
```
<?xml version="1.0" encoding="UTF-8"?> 
<bpmn2:definitions ... exporter="camunda modeler" exporterVersion="2.7.0" ...
...
```

**Comment by nikku** [comment]
Should we tackle this for the next release?

**Comment by vkatushenok** [comment]
Think so - should be quick to implement, as well.
