### ISSUE TITLE
Integrate new properties panel for platform, but hide behind feature flag until 7.17 release

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2517]
Copied from https://github.com/camunda/camunda-modeler/issues/2577:

**Is your feature request related to a problem? Please describe.**
 
With the M51 milestone, the new properties panel for Platform (for Cloud, it is integrated already) is planned to be ready. We plan to

* Integrate it into the Camunda Modeler
* But hide it behind a feature flag (so old propPanel remains the default)

WHY?:

* Using the new properties panel is a major change from User perspective
* We want to use a bit more time to get feedback, and also use the feature flag to encourage users to give feedback and to allow more users to give feedback
 
**Describe the solution you'd like**
 
* [ ]  Integrate new properties panel for Camunda Platform
* [ ]  Add feature flag (e.g., `new-properties-panel`)
* [ ]  Only show new properties panel, if feature flag was set
 
**Describe alternatives you've considered**

Only integrate once we have the new properties panel user tested and released in 1.0. Downsides of this solution:

* When we don't integrate, we miss out to learn about technical challenges we might face
* When users can't toggle it on via feature flag, we probably miss feedback from a large group of users

**Additional context**

The new properties panel (c.f. bpmn-io/properties-panel) will be released soon. The team ambition is to integrate it into the Camunda Modeler soon as well, so to get rid of legacy. 

However, from a consulting and devRel perspective, we need to hold it back a little bit longer, so to give time for updates of docs / trainings / slides / and more. In particular from their perspective, we would like to have this timeline: 

1. Do an internal release in Q4 with new PropPanel
2. Do a public pre-release in early '22 (e.g., Jan)
3. Release then in April with 7.17

In order to make this possible, we plan to release the new properties panel ASAP, but hide it behind a feature flag. That feature flag would then be removed with the 7.17. release.

**Comment by barmac** [comment]
We can re-use the way we add the new properties panel to Camunda Cloud BPMN, but use the flag to decide whether the modules should be replaced. What needs to be figured out yet is how we handle the stylesheets. Perhaps we can just leave the old styles in the app as they use a different namespace.

**Comment by barmac** [comment]
This is not planned anymore. We will integrate the new properties panel without a feature flag, but not for 4.12 release.
