### ISSUE TITLE
I can deploy a DMN to Camunda Cloud

### ISSUE THREAD

**Issue by saig0** [camunda/camunda-modeler#2526]
__Is your feature request related to a problem? Please describe.__

In Camunda Cloud `1.4.0`, we will support evaluating DMN decisions in Zeebe. As a user, I want to deploy a DMN to Camunda Cloud in the same ways as for processes.

Currently, I can deploy a DMN only to Camunda Platform.

* [x] I can deploy DMN to Cloud the same way as BPMN
* [x] I can deploy DMN even if the file does not have `.dmn` extension
* [x] When I deploy DMN to Cloud, correct notification is displayed

__Describe the solution you'd like__

I want to deploy a DMN to Camunda Cloud in the same way as for processes.

__Describe alternatives you've considered__

None.

**Comment by barmac** [comment]
DMN deployment is already available in Zeebe 1.4.0-alpha1. We should check if `zeebe-node` supports it too.

**Comment by saig0** [comment]
> We should check if zeebe-node supports it too.

The existing clients should be able to deploy DMN resources, just like BPMNs. We didn't change the deployment API yet.
