### ISSUE TITLE
I can set assignment details on a user task

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-modeler#2535]
__Is your feature request related to a problem? Please describe.__

In Camunda Cloud `1.3` we will introduce support for a new extension element for user tasks: assignment definition. See https://github.com/camunda-cloud/zeebe/milestone/69

__Describe the solution you'd like__

I want to be able to define the `assignee` and/or the `candidateGroups` attributes of the assignment definition of a user task from the camunda-modeler.

**Breakdown of activities**

- [x] https://github.com/zeebe-io/zeebe-bpmn-moddle/pull/18
- [x] [Implement new fields in properties-panel](https://github.com/bpmn-io/bpmn-properties-panel/pull/192)
- [x] #2580
- [x] [Add behavior to ensure that no empty `assignmentDefinitions` remain in the XML (after both inputs were set to ``)](https://github.com/camunda/camunda-bpmn-js/pull/72)

__Describe alternatives you've considered__

None

__Additional context__

- a user task can have 0 or 1 assignment defininitions (i.e. denoted as `zeebe:assignmentDefinition` inside the `bpmn:extensionElements` of a `bpmn:userTask`)
- an assignment definition specifies an assignee and/or candidate groups (i.e. denoted as `candidateGroups`)
- an assignee is defined as a string containing a static values (e.g. `x`), or a Zeebe-formatted FEEL expression (i.e. prefixed by `= `) where the expression should evaluate to a string
- candidate groups are defined as a string containing a comma-separated list of values (e.g. `x,y,z`), or a Zeebe-formatted FEEL expression (i.e. prefixed by `= `) where the expression should evaluate to a list of strings.

<details>
  <summary>Examples</summary>

```xml
<!-- A user task can have an assignee, specified as static value -->
<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
   <zeebe:assignmentDefinition assignee="frodo" />
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
 
<!-- A user task can have an assignee, specified as expression -->
<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
   <zeebe:assignmentDefinition assignee="= ring.bearer" />
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
 
<!-- A user task can have candidateGroups, specified as comma-separated list of values -->
<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
   <zeebe:assignmentDefinition candidateGroups="elves, men, dwarfs, hobbits" />
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
 
<!-- A user task can have candidateGroups, specified as expression -->
<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
   <!--
     expression produces bracket formatted list which differs from static value
     example expression evaluates to: ["elves", "men", "dwarfs", "hobbits"]
   -->
  <zeebe:assignmentDefinition candidateGroups="= distinct values(fellowship.belongsTo)"/>
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
 
<!-- A user task can have an assignee and candidateGroups simultaneously -->
<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
  <zeebe:assignmentDefinition
      assignee="= ring.bearer" 
      candidateGroups="elves, men, dwarfs, hobbits" />
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
```

</details>

**Comment by MaxTru** [comment]
Reopening because of missing clean-up behavior
