### ISSUE TITLE
Upgrade to latest Electron

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2538]
__What should we do?__

Update to latest Electron, cf. https://github.com/camunda/camunda-modeler/pull/2561 et all.

Changed `userData` behavior requires investigation: https://github.com/camunda/camunda-modeler/pull/2533#issuecomment-956286853.

__Why should we do it?__

 Be up to date with latest development snapshot.

----

Closes https://github.com/camunda/camunda-modeler/issues/2774

**Comment by nikku** [comment]
We need to be mindful regarding an [issue with the user path](https://github.com/camunda/camunda-modeler/pull/2533#issuecomment-956286853) when persuing this.

**Comment by MaxTru** [comment]
To consider: directly bump to 16.x

**Comment by nikku** [comment]
Renamed the issue. We shall update to the latest one available, of course.

**Comment by MaxTru** [comment]
We need to update also to improve compatability. See https://github.com/camunda/camunda-modeler/issues/2774

**Comment by marstamm** [comment]
closed via https://github.com/camunda/camunda-modeler/pull/2797
