### ISSUE TITLE
Connection to Identity Service?

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#254]
Is there any ability to connect to the Identity Service so that Assignees, groups, etc are more of a autocomplete experience?

**Comment by nikku** [comment]
Nope, there is not such connection.

**Comment by nikku** [comment]
Seems like a good feature for a repository / web-based modeling solution.

**Comment by StephenOTT** [comment]
@nikku for organizations that have large number of groups, sub-groups, employees, etc, the ability to quick lookup rather than manual input is usually favourable.  But can also have this added as another website/webpage for lookups of the proper variable.
