### ISSUE TITLE
Improve Camunda Forms User Journey

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2541]
_This is a tracking issue to collect potential improvements in Camunda Forms land._

__Larger Issues__

* https://github.com/camunda/camunda-modeler/issues/2498
* Improve form type selection, ensure Camunda Forms is promoted (cf. https://github.com/camunda/camunda-modeler/issues/2496)
* https://github.com/bpmn-io/form-js/issues/190 (cf. https://github.com/bpmn-io/form-js/pull/210)
* https://github.com/bpmn-io/form-js/issues/209 (cf. https://github.com/bpmn-io/form-js/pull/210)

__Smaller Fixes__

* https://github.com/camunda/camunda-modeler/issues/2603 (cf. https://github.com/bpmn-io/form-js/pull/211)
* https://github.com/bpmn-io/form-js/issues/169 (cf. https://github.com/bpmn-io/form-js/pull/177)
* https://github.com/bpmn-io/form-js/issues/199
* https://github.com/bpmn-io/form-js/issues/219

__Misc__

* https://github.com/camunda/camunda-modeler/issues/2540 (cf. https://github.com/camunda/camunda-modeler/pull/2683)
* https://github.com/bpmn-io/form-js/issues/216

**Comment by nikku** [comment]
CC @MaxTru

**Comment by superbeagle** [comment]
Hi, here are my suggestions for features, if not already noted or slated:
Date and Date Time Picker field
Form Layout (columns, rows, groupings ie. containers)
Tabs
Modals
Table builder
Script snippets

**Comment by superbeagle** [comment]
A way to extend the framework to create custom components or clone and tweak out of the box elements

**Comment by MaxTru** [comment]
cc @ingorichtsmeier 
Hi Ingo,
this is our current perspective of key issues required for improvement of form-js. Please feel free to comment.
Thanks

**Comment by ingorichtsmeier** [comment]
Hi @MaxTru,

looks good for the next round.

I recently stumbled over one missing feature: Text areas. I have filed an extra issue in forms-js to track it: https://github.com/bpmn-io/form-js/issues/194.

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2817
