### ISSUE TITLE
Issue template URL for Release issues does not work anymore / is too long

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2549]
__Describe the Bug__

Issue template URL for Release issues does not work anymore / is too long

__Steps to Reproduce__

1. Open https://github.com/camunda/camunda-modeler/blob/develop/docs/.project/RELEASE.md
2. Click `Draft a Release` link
3. => link does not open cause URL is too long

__Expected Behavior__

I can quickly draft a new release via URL

We need to check:
* Is there a way to make it work?
* If not, maybe we just have to do manual copy&paste when creating release issues

__Environment__

Any

**Comment by nikku** [comment]
If we would like to keep the checklist as verbose as it is, let us get rid of the links (or simplify them, i.e. indicate that the log has to be manually pasted).

There is no way to workaround this issue other than shortening our checklist.

**Comment by nikku** [comment]
We could even simplify the release issue creation one day: Whenever the old issue is closed, a new one is automatically created (similar to our weekly notes).
