### ISSUE TITLE
Delete shortcut is not set in the menu on Mac OS

### ISSUE THREAD

**Issue by vkatushenok** [camunda/camunda-modeler#255]
<img width="1680" alt="screen shot 2016-04-22 at 14 58 55" src="https://cloud.githubusercontent.com/assets/2331533/14742101/c7f952a2-089a-11e6-9113-1a2f73dce543.png">

**Comment by vkatushenok** [comment]
Raised related [issue](https://github.com/electron/electron/issues/5419) in Electron repository.

**Comment by benhoffmann** [comment]
I spend some minutes trying to remove selected elements today until I found the menu item and the corresponding shortcut. However, this is not very intuitive as the default shortcuts to remove things on a Mac are either fn+Backspace (which corresponds to Del on a windows machine) or cmd+Backspace (which is the standard action in Finder and many other apps).

Plus, ctrl+D is really hard to type with one hand.

Could you think about reassigning the shortcut?

**Comment by nikku** [comment]
This is an issue with the underlying infrastructure we are not going to fix.

`fn+Backspace` is the combination we are bringing back as soon as we can.

**Comment by vkatushenok** [comment]
The fix has been merged in the Electron and should be available in current latest release (v1.2.4).
Worth looking into it again.

**Comment by nikku** [comment]
@vkatushenok Wanna look into this again?

**Comment by vkatushenok** [comment]
@nikku Sure 🎩
