### ISSUE TITLE
Migrate deployment+start instance modals to overlays

### ISSUE THREAD

**Issue by smbea** [camunda/camunda-modeler#2552]
See [prototype](https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v14/)

__What should we do?__
- Migrate the existing deployment modal to an overlay
- Explore layout design for start instance
  - Maintain 2 step approach, re-using deploy overlay
- Migrate the start instance modal to an overlay

__Why should we do it?__
It's part of our new UI architecture, related to the Visual IDE efforts.

---
Child of #2489

**Comment by smbea** [comment]
Here are some developments of the UI migration for Platform.

@andreasgeier developed the prototype for the **Deploy** button:
![1-deploy](https://user-images.githubusercontent.com/25825387/141476859-414db45d-e5f9-4ed8-b6ca-8dc3e9d1be28.png)

The **Start Instance** also uses this overlay, as well as a second one (hence why this is being tackled at the same time). Since this didn't have a dedicated design, this a suggestion of how this could look like:

<div>
<img src="https://user-images.githubusercontent.com/25825387/141476858-040d87db-43f6-4bd9-ad69-1f222b4c9a0f.png"/>
<img src="https://user-images.githubusercontent.com/25825387/141476852-28896627-8a67-4b84-937b-d9e5008593b8.png"/>
</div>

The whitespace in the second screenshot is to assure the overlay size remains the same when "Next" is clicked.

__Things to consider:__
1. It would probably be useful to have a button to go back to the 1st screen - at the moment you can only do so by closing and opening the modal again
2. Having Step x out of 2" in the overlay title doesn't make much sense to me

However these things weren't addressed in the modal either so it might be out of the "migrate from modal to overlay" scope

**Comment by pinussilvestrus** [comment]
Does this flatten design also work with the radio button in the Cloud deployment? The radio buttons with the longer labels might take some more space.

![image](https://user-images.githubusercontent.com/9433996/141480572-a3363d5f-2452-4472-b5b4-f952decfff26.png)

**Comment by smbea** [comment]
> Does this flatten design also work with the radio button in the Cloud deployment? The radio buttons with the longer labels might take some more space.
> 
> ![image](https://user-images.githubusercontent.com/9433996/141480572-a3363d5f-2452-4472-b5b4-f952decfff26.png)

No, that's why I mentioned _for Platform_. We are tackling one at a time because of that reason. The radio buttons will need to be adjusted to work with the overlay. I don't have a suggestion I can share for that one yet

**Comment by pinussilvestrus** [comment]
> @pinussilvestrus No, that's why I mentioned for Platform.

Oh sorry, I missed that one 😅

**Comment by ingorichtsmeier** [comment]
The design looks nice.

But, from a developers point of view, it didn't make sense to add addtional files when I want to start a new process instance.

Or is there some magic working in the background that I didn't see?

It would be more useful to provide variables for starting a process instance. I think there is an open issue with a pull request to work on it: https://github.com/camunda/camunda-modeler/pull/2443

**Comment by MaxTru** [comment]
> The design looks nice.
> 
> But, from a developers point of view, it didn't make sense to add addtional files when I want to start a new process instance.
> 
> Or is there some magic working in the background that I didn't see?
> 
> It would be more useful to provide variables for starting a process instance. I think there is an open issue with a pull request to work on it: #2443

There are two cases how the startInstance modal would start:
1) there was a prior deployment
* I this case the "additional files" button should not appear
2) there was no prior deployment
* In this case two steps are needed
  1. deploy (with additional files)
  2. start instance

@smbea I think you were only showing case 2, and also the screenshots you shared miss the descriptions we used to have?
![image](https://user-images.githubusercontent.com/42800119/141486943-8d5367cb-a22a-4280-9ecd-649d649f4bc3.png)

**Comment by pinussilvestrus** [comment]
I don't think that we should keep possible usability improvements outside of this issue. As I understand, this is about migrating the current modals, and ensure we keep the existing behavior 1:1.

**Comment by smbea** [comment]
I updated my comment to be easier to look at the whole design in one spot. It believe now it reflects all the states and includes the missing description.

I also decided to make the 2nd step of the start instance process is true size (instead of having whitespace and making it the same height of the previous overlay) because the 1st overlay doesn't have fixed height - it depends on how many files are added.

**Comment by andreasgeier** [comment]
> I think that we should keep possible usability improvements outside of this issue. As I understand, this is about migrating the current modals, and ensure we keep the existing behavior 1:1.

I would like to avoid a two-step-approach in an overlay (weird behavior for an overlay) but show these options in one step. And since we would need to implement such a wizard into an overlay (and throw it away in the next iteration), would it be reasonable to consider this right now?

**Comment by smbea** [comment]
The start instance component fully relies on the deploy component for this and doesn't handle any of the responsibility for this deploy request. With the way we have this structured I think it would require some effort in refactoring this, which I'm not sure should be dealt with in this issue of UI migration. 

But let me ping more people for their opinion @pinussilvestrus @barmac @nikku @MaxTru

**Comment by andreasgeier** [comment]
@smbea I saw in your demo today that you already implemented the two-step approach. I agree that we can progress with this as long as we don't discover any additional problems in the review.

I'm working on a solution draft (next iteration?), but to give you an early insight, and to foster feedback from others as well, here is a rough idea sketch (no guarantee that this will be the final structure):

<img width="1476" alt="Screen Shot 2021-11-16 at 11 25 47" src="https://user-images.githubusercontent.com/938244/141968251-3fef8f0c-e69d-4b2e-a4fa-a3d128cc25e8.png">

_Both features in one overlay, the deployment part can be toggled. In error case, the configuration part would be expanded and errors are shown._

This would give us two advantages:
- avoid two-step approach, have everything directly available, simplified user flow
- we get rid of the two options (start + start with new config) since both are always available

I still need to check how this works for cloud but I don't expect blockers. Let me know if you have feedback.

**Comment by smbea** [comment]
@andreasgeier I did because it was a natural step in a direct translation form modal to overlay - this component reuses the deploy component so it was changed automatically with the deploy one.

In the sense of making progress I agree we should keep as is for now. But I like your concept and the fact that it eliminates the dropdown. Maybe I can open an issue to address this after the basic translations to overlays are done. This way we can fully complete a 1st increment and move on to enhancements.

**Comment by MaxTru** [comment]
I agree with the general sentiment in this conversation. I like the idea and concept to get away from the 2-step approach. But this PR should focus on the Overlay migration.

@andreasgeier, maybe you want to create an issue to "Migrate away from 2-step approach" to bundle the conversations and to ensure we don't forget about this?

**Comment by andreasgeier** [comment]
> @andreasgeier, maybe you want to create an issue to "Migrate away from 2-step approach" to bundle the conversations and to ensure we don't forget about this?

@MaxTru I already did: see [design issue #55](https://github.com/camunda/camunda-modeler-design/issues/55)

**Comment by smbea** [comment]
**Proposal for cloud:** it's a direct translation with the exceptions of :
1. the "Remember Credentials" which was replaced with a toggle switch
2. the target radio buttons were transposed from horizontal to vertical


<div>
<img  width="300" src="https://user-images.githubusercontent.com/25825387/142648179-da2ca972-27b3-43e2-bf44-301af863e661.png"/>

<img  width="300" src="https://user-images.githubusercontent.com/25825387/142648158-c80ba645-99a7-41af-a9f7-dc2b242f3393.png"/>
</div>
<br/>
The start instance for this doesn't have a specific overlay, it's done with the deploy config.
