### ISSUE TITLE
Implement new `Create new` menu

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2556]
__What should we do?__

Implement the [newly designed create new menu](https://github.com/camunda/camunda-modeler-design/issues/50) and remove the existing menu bar in the toolbar:

![image](https://user-images.githubusercontent.com/58601/141168149-9f34f72f-e99a-4551-9f84-894c90538296.png)

__Tasks__

* [ ] Add pluggable tab actions
* [ ] Newly introduced `+` button opens create popup
* [ ] Create popup is populated based on available editors
* [ ] Clicking either option closes the popup and creates the respective diagram type + opens it
* [ ] Keep the existing context menu on right-click (maybe adding a new separator to indicate cloud vs. platform)

Out of scope: Show keyboard shortcuts along with create options (https://github.com/camunda/camunda-modeler/issues/2555).

__Why should we do it?__

Contribute to the editor redesign.

---

Cf. [design issue](https://github.com/camunda/camunda-modeler-design/issues/50).

**Comment by pinussilvestrus** [comment]
With this we add a _grouping_ to our new file entries

![image](https://user-images.githubusercontent.com/9433996/143841421-0245b4f1-f287-4b4b-b475-c68ec489458c.png)


I believe we should align this with other parts where we rely on the [`TabsProvider`](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/TabsProvider.js#L136) entries

**Application menu**

![image](https://user-images.githubusercontent.com/9433996/143841722-dde9e82a-4096-4800-b383-537a13ece4a0.png)

**Context menu**

![image](https://user-images.githubusercontent.com/9433996/143841754-eaaeced3-e521-45c0-b1ab-7c4e17772266.png)

**Comment by nikku** [comment]
Agreed. If possible we shall group by target platform consistently, in all cases. For me that means adding a separator between platform and cloud diagrams. I don't see a better way to support this given the [native capabilities](https://www.electronjs.org/docs/latest/api/menu-item#menuitemsublabel) we have available.

**Comment by pinussilvestrus** [comment]
> Agreed. If possible we shall group by target platform consistently, in all cases. For me that means changing the grouping and adding a separator between platform and cloud diagrams. I don't see a better way to support this given the [native capabilities](https://www.electronjs.org/docs/latest/api/menu-item#menuitemsublabel) we have available.

I added a sketch of how we could achieve that as a core feature: https://github.com/camunda/camunda-modeler/pull/2609
