### ISSUE TITLE
Provide initial CMMN modeling

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#256]
Beside bpmn and dmn the Camunda Modelers allows cmmn modeling

**Comment by StephenOTT** [comment]
Wasn't this planned for Q2 2016 (I believe i saw in blog post) ?

**Comment by vkatushenok** [comment]
We are not sure when it will be released, but yes, it is in our roadmap.

**Comment by nikku** [comment]
:cake:

**Comment by gimbel** [comment]
Done: https://blog.camunda.org/post/2016/05/camunda-modeler-cmmn-modeling/
