### ISSUE TITLE
Unchecked checkbox not mapped to process variable

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#2560]
__Describe the Bug__

An unchecked checkbox does not create the mapped variable

__Steps to Reproduce__

**Scenario a**: I create my form in the modeler form-builder.
```
{
  "schemaVersion": 2,
  "components": [
    {
      "label": "Checkbox",
      "type": "checkbox",
      "id": "Field_1l6w7am",
      "key": "chk_variable"
    }
  ],
  "type": "default",
  "id": "Form_1mnbkj6"
}
```
// when 
I complete a task with an unchecked checkbox 
// then
the mapped process variable `chk_variable` will **not** be created.

**Scenario b**: I create my form as html file
```
    <input type="checkbox"
      id="resolve-chk"
      cam-variable-name="chk_variable"
      cam-variable-type="Boolean"
 />
```
// when 
I complete a task with an unchecked checkbox 
// then
the mapped process variable `chk_variable` will be created and the value is false.

**Scenario c**: I create the checkbox in the properties panel forms tab. 
```
<camunda:formData>
  <camunda:formField id="chk_variable" label="Checkbox" type="boolean" defaultValue="false" />
</camunda:formData>
```
// when
I complete a task with unchecked checkbox 
// then
the mapped process variable `chk_variable` will be created and the value is false.

__Expected Behavior__

The variable will always be mapped. I assume that in scenario a the checkbox value is null. So using a defaultValue field like in the properties panel forms tab could already solve the problem

__Environment__
- Camunda Modeler Version: [4.11.1]

----

Depends on https://github.com/bpmn-io/form-js/issues/190

**Comment by nikku** [comment]
Thanks for opening this issue. 

It looks like we already track this upstream (https://github.com/bpmn-io/form-js/issues/190), could you verify it?

**Comment by mschoe** [comment]
Hey @nikku, it seems to be the same issue.

**Comment by barmac** [comment]
It looks like this issue has already been fixed in https://github.com/bpmn-io/form-js/issues/190, and has been fixed for over a year in the app 🤡
