### ISSUE TITLE
Make multi-element color picker available via the app menu

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2568]
__What should we do?__

* [ ] Support color picker actions via the app menu (`Edit > Color`)

As a potential improvement, investigate if [adding a color icon](https://github.com/camunda/camunda-modeler-design/issues/52#issuecomment-973005198) is possible and an improvement

---

Proposed menu addition:

```
App menu > Edit > Color 
                        > White
                        > Blue
                        > Orange
                        > Green
                        > Red
                        > Purple
```

__Why should we do it?__

Support tool bar removal and general UI unification (https://github.com/camunda/camunda-modeler-design/issues/52).

**Comment by smbea** [comment]
@nikku @andreasgeier 
After exploring the possibility of having colored icons to make the process easier, I concluded this is easily achieved. But now with svgs, we have to add a PNG or JPG icon in each of the colors. Do we want to move forward with this?

Here is an example of placeholder icons:
![image](https://user-images.githubusercontent.com/25825387/143862207-4abad53e-ac27-4a4a-989c-1b8de984df34.png)

**Comment by nikku** [comment]
> Do we want to move forward with this?

What is your take on it? I could deliver a base SVG and/or you role your own.

**Comment by smbea** [comment]
I think it's easy enough and makes a significant impact to the user. So I would go with yes. I can add the icons if we just want to do a filled colorful circle

**Comment by nikku** [comment]
:+1: Let's do it then!

**Comment by andreasgeier** [comment]
Okay for me. Please ensure that it looks as expected in all 3 supported OS.
