### ISSUE TITLE
Remove toolbar all together

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2569]
__What should we do?__

Remove the toolbar completely and the the existing toolbar fills (align, distribute, color helpers).

__Why should we do it?__

Support [UX re-design](https://github.com/camunda/camunda-modeler-design/issues/32).

---

Depends on https://github.com/camunda/camunda-modeler/issues/2568.

**Comment by Josef-Reichardt** [comment]
Are the alignment functions also removed?  
![grafik](https://user-images.githubusercontent.com/1203740/180221936-6013ef04-5afa-437b-8fef-3160a72203ad.png)

Is there a way to use them in the modeler >= 5.x?

**Comment by nikku** [comment]
They are available via the menu.

Modeler v5.1 also makes them available as context pad actions (cf. [blog post](https://camunda.com/blog/2022/07/camunda-desktop-modeler-5-1-released/)).
