### ISSUE TITLE
Replace the form JSON configuration text field with a text area

### ISSUE THREAD

**Issue by CatalinaMoisuc** [camunda/camunda-modeler#2579]
__Is your feature request related to a problem? Please describe.__

As a Camunda Modeler User, I should be able to easily browse the JSON content of the form linked to a User Task in the Properties Panel of my Cloud processes.

Currently, I can't reference the form (in the same way I can for the Platform processes) and I have to copy-paste the form's JSON content and paste it in the Properties Panel in a text field.

The only way I can check if the correct form is linked is to look through the JSON content I linked and this is quite hard to achieve today since the whole JSON content is in a text field and the amount of characters I can actually visualize at a time is very limited. (see screenshot attached below)

__Describe the solution you'd like__

I would like to be able to better see the Form JSON configuration for a User Task in a Cloud Process.

I would like if the Form JSON configuration would be displayed in a text area that displays at least 4 lines (rather than a simple text field) so I can easily browse through the linked form JSON content.

__Describe alternatives you've considered__

I would like to be able to reference a form and deploy both the form and the process in the Zeebe Engine and the correct form to be picked up during execution (same as I currently can for the Camunda Platform processes).
But I think this requires higher implementation efforts than the solution I described above.

__Additional context__

**Execution Platform**: Camunda Cloud
**Camunda Modeler version**: 4.11.1
![Screenshot 2021-11-22 at 15 28 35](https://user-images.githubusercontent.com/25924333/142886068-fa3bd48e-2669-4f9b-b1ef-bcff9cb1b86e.png)

cc @MaxTru @MoAtCamunda @felix-mueller

**Comment by MaxTru** [comment]
I picked this up as it is a one liner (assuming I didn't miss anything)

**Comment by nikku** [comment]
As a little bit of background, please note that making it a text area does not fit the overall issue: The fact that deploying something _along with_ the BPMN diagram does not exist as a feature as of yet, though it is required for forms (and other things) to work properly.

Personally I'd rather invest in getting that fixed, linking back to the original (embedded) diagram, ...

Embedding a form via any field, however big is, on purpose and without a doubt, a big hack.

**Comment by ingorichtsmeier** [comment]
Hi, after looking at the BPMN XML, it seems to me that the packaging of the form into the BPMN diagram is just caused by a missing concept of deployment in Zeebe.

Under the hood, the user tasks references the formKey:
```
    <bpmn:userTask id="enterMessageTask" name="Enter Message">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="humanTask" />
        <zeebe:formDefinition formKey="camunda-forms:bpmn:userTaskForm_15j79nd" />
      </bpmn:extensionElements>
    </bpmn:userTask>
```

And the form itself is referenced as an extension of the process:

```
  <bpmn:process id="send-email" name="Send Email" isExecutable="true">
    <bpmn:extensionElements>
      <zeebe:userTaskForm id="userTaskForm_15j79nd">{"components"...}</zeebe:userTaskForm>
    </bpmn:extensionElements>
```

I have no good idea how to solve this issue, but the current workflow (copy the JSON into the BPMN) is confusing and error prone for the developer.

**Comment by felix-mueller** [comment]
Thanks @nikku and @ingorichtsmeier for the input. I agree with you that copying the json config is only a temporary solution.
