### ISSUE TITLE
Form file name not displayed 

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#2581]
__Describe the Bug__

When saving a freshly created form file the new file name is not displayed in the tab bar. Instead of that the initial file name `form_1.form`  is displayed.
Furthermore the tooltip shows `unsaved` when I hover over the tab header. 

__Steps to Reproduce__

1. create a new form file
2. save it and change the file name 
3. observe the displayed file name in the tab header
4. hover over the tab header

__Expected Behavior__

correct file name will be displayed

__Environment__

- OS:  linux mint 20.2
- Camunda Modeler Version: 4.11.1-new-properties-panel edition

**Comment by barmac** [comment]
I cannot reproduce it on MacOS. @nikku @MaxTru can you check on Linux?

**Comment by nikku** [comment]
I cannot reproduce it either on `v4.11.1`.

**Comment by mschoe** [comment]
I'm using the 4.11.1-new-properties-panel edition, don't know if this makes any difference towards v4.11.1
and this it how it looks like:

https://user-images.githubusercontent.com/2777965/143024222-9998dcd7-3829-4058-92d8-9944833bf52d.mp4

**Comment by MaxTru** [comment]
@pinussilvestrus maybe this is something which was caused by recent tabBar infrastructure changes?

**Comment by barmac** [comment]
I can reproduce it in the 4.11.1-new-properties-panel edition. Thanks @mschoe for update.

**Comment by pinussilvestrus** [comment]
> @pinussilvestrus maybe this is something which was caused by recent tabBar infrastructure changes?

which changes? the tab bar is not touched so far (on `develop`).

**Comment by barmac** [comment]
I can reproduce it in a `nightly` build as well.

**Comment by pinussilvestrus** [comment]
Seems like it does not use the [defined getter](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/TabsProvider.js#L518) when accessing `tab.title` for form files (after the save operation).

**Comment by MaxTru** [comment]
With the latest nightly (having linting also for BPMN), this bug also occurs with BPMN diagrams.
