### ISSUE TITLE
Removing space from participant breaks diagram

### ISSUE THREAD

**Issue by ricardomatias** [camunda/camunda-modeler#259]
When removing space to the left (inside a Participant), if no element is caught in the selection, the participant doesn't take into account the children and the participant can be made smaller then them.

![foo](https://user-images.githubusercontent.com/58601/33851006-f633d082-deb5-11e7-8fb7-e25eca53a91e.gif)

**Comment by ricardomatias** [comment]
Related to bpmn-io/bpmn-js#259

**Comment by nikku** [comment]
We appreciate a PR to improve things.
