### ISSUE TITLE
Radio Button value field loses selection after a second

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#2603]
__Describe the Bug__

When creating a radio button after selecting the value field to enter in something after about a second the field loses selection and you can no longer add anything to it without re-selecting it. 

__Steps to Reproduce__

1. Create a new camunda form
2. drag the radio button onto the cancase
3. enter a value to the label field. 
4. enter a value to the value feild
5. Notice that after a second it stops accepting input. 

__Expected Behavior__

I should be able to enter data without the field losing focus

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.11.1

https://user-images.githubusercontent.com/10612634/144260236-d73ed0d6-20f4-429f-8430-e610cb9bb985.mp4

- Execution Platform: NA
- Installed plug-ins: (lots)

**Comment by nikku** [comment]
Thanks for reporting. I can reproduce the issue. 

We plan to look into form related improvements in the next quarter and I've added this one onto the list of potential candidates.

**Comment by NPDeehan** [comment]
Thanks Nico!

**Comment by philippfromme** [comment]
This bug was introduced by https://github.com/bpmn-io/form-js/commit/e66585c24828f318bb2f6bd28fb6b1913423940f#diff-78090eb9f4e5b857920283996e0d8d9af3e7b83471930850f5f79aa817c5574a.

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2771
