### ISSUE TITLE
Improve Notifications

### ISSUE THREAD

**Issue by smbea** [camunda/camunda-modeler#2607]
> this is an epic issue that might be broken down into specific tasks

__What should we do?__

Redesign notifications of deploy + start instance to match new UI - https://github.com/camunda/camunda-modeler-design/issues/38

Also consider https://github.com/camunda/camunda-modeler/issues/1827

__To Do:__
* update UI of notifications
   * placement + animation
* expand deploy notification description to include `deployment ID`
    * (maybe) link to cockpit (deployment section) or link to run

- update cloud-connect-plugin notifications to match new UI - https://github.com/camunda/cloud-connect-modeler-plugin/pull/72
  - add error notifications for invalid credentials and cawemo connection
  - match text and letter cases to new UI

__Why should we do it?__

That's part of our one Visual IDE efforts.

**Comment by smbea** [comment]
> Related: #1827
> 
> Just found this randomly in our inbox 🙂

Whoops! Will mark as duplicate and close. @nikku's wishes from 2020 are coming true

**Comment by nikku** [comment]
So happy about this :gift:
