### ISSUE TITLE
Destroy diagram when closing tab

### ISSUE THREAD

**Issue by ricardomatias** [camunda/camunda-modeler#261]
Without destroying it, global event listeners will not be removed.

**Comment by nikku** [comment]
Is this a quick fix? If that is the case we should address this soon.

**Comment by vkatushenok** [comment]
@ricardomatias Need to implement `destroy` method on XML editor as well. See [CodeMirror doc](http://codemirror.net/doc/manual.html#swapDoc) for reference.

**Comment by nikku** [comment]
Plus, needs to actively unbind [this](https://github.com/camunda/camunda-modeler/blob/b6a05a29ddebb0e3b3b881c2019edb89f5b8b9b8/client/lib/app/tabs/multi-editor-tab.js#L280). Otherwise the editor gets never cleaned up.
