### ISSUE TITLE
Lint rules for Camunda Cloud 1.0, 1.1, 1.2, and 1.3 exist

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2617]
Rules for Camunda Cloud versions are defined and implemented based on

* docs (cf. [1.0](https://docs.camunda.io/docs/1.0/reference/bpmn-processes/bpmn-coverage/#), [1.1](https://docs.camunda.io/docs/1.1/reference/bpmn-processes/bpmn-coverage/), [1.2](https://docs.camunda.io/docs/reference/bpmn-processes/bpmn-coverage/), [1.3](https://stage.docs.camunda.io/docs/reference/bpmn-processes/bpmn-coverage/))
* Zeebe test diagrams (cf. https://github.com/camunda-cloud/zeebe/tree/develop/bpmn-model/src/test/resources/io/camunda/zeebe/model/bpmn)

Rules are implemented as bpmnlint plugin: https://github.com/camunda/bpmnlint-plugin-camunda-compat

**Comment by nikku** [comment]
Exists, and integrated via https://github.com/camunda/camunda-modeler/pull/2610/commits/8633666276635e116988e44fcabcaeb059da1bdc.

**Comment by nikku** [comment]
Provided as a re-usable building block (https://github.com/camunda/bpmnlint-plugin-camunda-compat).
