### ISSUE TITLE
Add ability to document Version number of Process in Process General Tab

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#262]
Would be great if there was a way to mark the version of the process in the General tab next to ID and Name.

**Comment by vkatushenok** [comment]
Hi, what version do you mean exactly?

**Comment by StephenOTT** [comment]
When working on a Process, you go through many iterations.  This often ends with Process123_v1.bpmn, Process123_v2.bpmn, etc.

Increased on putting this information into the Process ID and/or the Name field, a specific Version field would be very useful.

But probably a more expanded question is, do you see a extension for the modeller being built for direct git commits on Save of a process/bpmn to a Git Repo; similar to how JBOSS RH BPM functions?  (Not to say that the JBOSS RH BPM model is correct, just using it as a example).

If there was GIt support the versions field would not really be required, and you could control versions through tags and regular VC of the XML making up the BPMN file.

**Comment by vkatushenok** [comment]
I was not able to find anything that relates to process version in BPMN 2.0 specification, at this moment.
Please, feel free to point out, how process versioning could be achieved in relation to spec.

At current point, similar functionality could be implemented using [this example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension).

Regarding Git related extension - we do not have any plans to do that. 

As always - pool requests welcome 😉.

**Comment by StephenOTT** [comment]
@vkatushenok Was not thinking it was part of the BPMN spec.  Agree it probably fits best as a properties panel extension.

**Comment by menski** [comment]
There is already a "Version Tag" property in the latest nightly. As this is a feature the next Camunda BPM version will support (https://app.camunda.com/jira/browse/CAM-5528). Maybe you can also use this property.

**Comment by nikku** [comment]
Sounds like a valid solution. Gonna close this issue for now.

**Comment by StephenOTT** [comment]
Yes that looks to be perfect! 
Thanks!
