### ISSUE TITLE
Selected item is not highlighted in forms

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#2620]
__Describe the Bug__

In the forms after we make a selection in the execution platform the radio button selection and the highlighting are in different items.

__Steps to Reproduce__

1. Select the Camunda BPMN platform in the forms for execution.
2. We could see that the selection and highlight appear in the same item as selected.
3. Try to change the selection to Camunda cloud.
4. We could see that the selection is on camunda cloud and the blue highlight is still in the platform.

__Expected Behavior__

Selected item should be highlighted as well.

__Environment__

- OS: [Windows 11]
- Camunda Modeler Version: [4.12]

https://user-images.githubusercontent.com/85225325/145243285-25d6a4a5-a0a1-4355-9bba-26ac484a6418.mp4

**Comment by philippfromme** [comment]
Fixed via https://github.com/camunda/camunda-modeler/pull/2573.

**Comment by nikku** [comment]
How is this fixed via https://github.com/camunda/camunda-modeler/pull/2573?

**Comment by philippfromme** [comment]
There is only one input in the new engine profile overlay so there is no case of the _wrong_ input being focused.

**Comment by nikku** [comment]
:+1: Thanks for clarifying.
