### ISSUE TITLE
File Conflicts when using Google Drive

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#263]
<s>When you save multiple versions of the same Process using the File Names such as Process123_v1.bpmn and Process123_v2.bpmn, but the Process ID are the same in the xml/files, a conflict is created and the user cannot open both of the BPMN files at the same time.
You have to change the Process ID field.

Why is the Process ID field used as the UID between open files rather than the file name?</s>

see below

**Comment by nikku** [comment]
Based on your description we cannot reproduce your bug report.

Could you please provide 

* your platform
* the Camunda Modeler
* detailed steps to reproduce

**Comment by StephenOTT** [comment]
Mac, 10.11.4

Camunda: Version 0.6.0 (1458750623)


Did some further testing, and I see this is a problem with Google Drive rather than Camunda directly.

Seems that Google Drive and Camunda do not get along 😄 

Get the following error often when opening BPMN files in google drive:
![screen shot 2016-05-02 at 10 45 17 am](https://cloud.githubusercontent.com/assets/1994838/14957384/1a7cd62e-1053-11e6-9350-00aed7107748.png)

Does not happen every time, but it is often.

Open a BPMN file on Google Drive.  Save.  Close.  Reopen.
Repeat if it does not happen the first time.

**Comment by nikku** [comment]
Google drive seems to constantly update the last edit flag of the files. There is nothing we can do about it, unless we do an actual hashsum check on the file contents.
