### ISSUE TITLE
Add support for tables inside a notation

### ISSUE THREAD

**Issue by Rednas83** [camunda/camunda-modeler#2634]
__Is your feature request related to a problem? Please describe.__

Not able to add tables inside a notation

__Describe the solution you'd like__

An additional/modified component like 'TextAnnotation'. In which you have the option to create columns and rows and where you can easily navigate cells with mouse click or arrow buttons.

Something like:
![image](https://user-images.githubusercontent.com/25219229/145973429-ca40ee4f-61f9-4e6c-bd53-230d4dffed24.png)

__Describe alternatives you've considered__

Using 'TextAnnotation' for defining tables with manually doing the alignment
![image](https://user-images.githubusercontent.com/25219229/145970823-d683d19e-db0a-42e5-b2f8-3cf128510fbe.png)

**Comment by nikku** [comment]
@Rednas83 Thanks for opening this issue. 

I'm afraid that this is outside the scope of the core capabilities offered by the app: Annotations are plain text, not structured text.

Maybe there exists a way to hook up the functionality as a [bpmn-js extension](https://github.com/bpmn-io/bpmn-js)?

You'd need to provide both editing and view capabilities to support such special annotations.

**Comment by Rednas83** [comment]
Is camunda also supporting js extensions?
I am currently stuck to camunda because bpmn-js is not supporting Nuxt/SSR yet😢

**Comment by nikku** [comment]
How does Camunda support Nuxt/SSR and bpmn-js not?

**Comment by Rednas83** [comment]
I am just using Camunda as a temporary solution until Nuxt/SSR is supported. But to answer my question. Does camunda support js extensions?

**Comment by nikku** [comment]
> I am just using Camunda as a temporary solution until Nuxt/SSR is supported. 

Who shall support Nuxt/SSR? Do you work on a contribution? I'm asking because I have it nowhere on my radar.

To your point, the Camunda Modeler [can be extended via plug-ins](https://github.com/camunda/camunda-modeler-plugin-example).

**Comment by Rednas83** [comment]
Thanks, perhaps I will look into it if I find the time.

The 'feature request' for adding nuxt support should be on the backlog
https://github.com/bpmn-io/vue-bpmn/issues/11
