### ISSUE TITLE
Menu save options behave inconsistently for Camunda Forms

### ISSUE THREAD

**Issue by hkupitz** [camunda/camunda-modeler#2635]
__Describe the Bug__

While it's possible to use the "Save File", "Save File as.." and "Save All Files" options in the "File" menu both for BPMN as well as DMN diagrams whenever, this doesn't seem to be the case for Camunda Forms.

Normally, switching to a different tab in the Modeler doesn't gray out those options:

![normal](https://user-images.githubusercontent.com/27265759/146008711-41227288-6752-4c0e-9c14-325ff52ada75.gif)

When doing this for a Camunda Form though, all save options are grayed out:

![forms](https://user-images.githubusercontent.com/27265759/146008845-e0349244-bde3-45a0-9fcc-c3fe2b168761.gif)

__Steps to Reproduce__

1. Create a BPMN/DMN diagram in the Modeler.
2. Create a Form & add an element such as a text field.
3. Switch to the BPMN/DMN tab.
4. Switch back to the Form tab.
5. Open the "File" menu.

__Expected Behavior__

Save options should behave consistently (not being grayed out), no matter for which diagram type.

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.11.1

**Comment by MaxTru** [comment]
Thanks for reporting, I can reproduce this. We will take a look.

**Comment by MaxTru** [comment]
`handleChanged` is not called when one switches from another tab to the form tab:
https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/form/FormEditor.js#L229
