### ISSUE TITLE
Support deploy diagram to alternative Camunda Cloud SaaS environments

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-modeler#2636]
__Is your feature request related to a problem? Please describe.__

I want to be able to deploy my diagram directly to a test cluster on a non-production environment. Specifically, I don't run my tests in production because the special-made generation is unavailable on production. I can easily create a new generation of my branch of Zeebe using the Jenkins QA pipeline. However, deploying a model to my custom cluster is cumbersome because the modeler does not support connecting to the other Camunda Cloud environments.

__Describe the solution you'd like__

Please additionally accept as cluster url the following:
- `<uuid>.<region>.zeebe.ultrawombat.com:443` (integration)
- `<uuid>.<region>.zeebe.dev.ultrawombat.com:443` (dev)

__Describe alternatives you've considered__

For now, I'll use `zbctl` to deploy my models.

__Additional context__

Related to https://github.com/camunda/camunda-modeler/issues/2375

**Comment by MaxTru** [comment]
Makes sense.

I would assume that we can relax the URL schema in general. So have something like
* `<uuid>.<region>.zeebe.<someHost>.<someTopLevelDomain>:443`

Or are there any restrictions we should adhere to?

**Comment by korthout** [comment]
>Are these restrictions valid?

I believe so, yes (as long as `someHost` can contain dots).

> Do the map to some Zeebe conventions (if so, do we have them documented?)

Not that I'm aware of. Such a convention would not be owned by the Zeebe team, but by SRE, Console or Cloud. In any case, I'm not aware of this having documentation.

>Do they help?

I think so. Users can use the Self-Managed connection configuration to connect to their own clusters, but any cluster we manage for users should be available through the SaaS connection configuration IMO. 

Note that I don't think it needs to be complex validation that highlights stuff like: You've forgotten to add the region.
Instead, I think simple validation that rejects unknown urls sounds good enough to me.

**Comment by barmac** [comment]
@korthout can you verify this works on [a nightly build](https://camunda.org/release/camunda-modeler/nightly/)? 

I believe this is still broken because even though I can provide a custom URL, the app still tries to authenticate with the production URL of Camunda Cloud SaaS. @andreasgeier you had this problem, didn't you?

**Comment by korthout** [comment]
It still seems to disallow using ultrawombat:

cluster-url: `15eb52aa-552b-47cd-a589-56d817bb84f5.bru-3.zeebe.ultrawombat.com:443`

<img width="792" alt="Screen Shot 2022-01-28 at 12 23 58" src="https://user-images.githubusercontent.com/3511026/151538784-4ce2108a-f953-4c95-b688-a111514a27ac.png">

**Comment by MaxTru** [comment]
I will take a look - moving to ready

**Comment by MaxTru** [comment]
The approach I took for this fix was wrong.

The deploy dialog currently has 2 modes:
1. Camunda Cloud SaaS
2. Camunda Cloud Self-Managed

* When using (1) `SaaS`, we assume the audience and oauth URL (actually the zeebe-node-client...).
* When using (2) `Self-Managed`, the user is to provide audience and oauth URL.

If you want to deploy to ultrawombat, this is basically a custom self-managed environment, and is possible via (2).

Does this work for you @korthout?

I would basically then revert the commit and close this issue.

However there are follow-ups:
We need to invest into the Deploy dialog (documentation, make it easier to configure audience / perhaps automate audience field, ...). This is handled in this issue: https://github.com/camunda/camunda-modeler/issues/2707

**Comment by korthout** [comment]
🤯 This works. I completely hadn't thought about this, but it makes total sense.

Thanks, please revert the changes and I'll close this issue 🙇
