### ISSUE TITLE
Make save action not lose the currently active editing state of an element

### ISSUE THREAD

**Issue by hkupitz** [camunda/camunda-modeler#2637]
__Is your feature request related to a problem? Please describe.__

Whenever a save action is triggered, be it from the "File" menu, via Ctrl+S or through a plugin, elements that were just being edited lose their editing state. 

![editingstate](https://user-images.githubusercontent.com/27265759/146014627-2c0b26e7-174f-4a6e-82ff-db9fb7cc692d.gif)

This isn't a problem on its own, however makes the use of certain plugins like the [Autosave Plugin](https://github.com/pinussilvestrus/camunda-modeler-autosave-plugin) impractical. I noticed this behavior when having set up the plugin with a rather short saving interval, triggering the save action every few seconds, 

This has caused quite some confusion for me, thinking I was accidentally hitting certain hotkey combinations, until I figured out the actual cause.

__Describe the solution you'd like__

I am not sure if the intention of having the save action stop all editing is to provide the user with some kind of visual feedback. However if it's desired to keep the current behavior for saving manually, it could be an option to allow plugins to trigger the save action while keeping the focus/editing active.

**Comment by pinussilvestrus** [comment]
I think we proactively added this behavior to cancel the editing on saving in the past (cf. https://github.com/camunda/camunda-modeler/issues/1473). This ensures direct editing is completed and changes are persisted on the file.

**Comment by nikku** [comment]
As you're mentioning the unwanted interaction between Auto-Safe and this feature, what if auto-safe would consider the direct editing state and wait for completion, before automatically saving.

**Comment by pinussilvestrus** [comment]
I'm closing this one in favor of https://github.com/pinussilvestrus/camunda-modeler-autosave-plugin/issues/74, because it's the duty of the plugin contributors (which is me 🐵)  to fix that issue.
