### ISSUE TITLE
In order to close a tab, I have to click/focus it first

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2639]
__Describe the Bug__

In order to close a tab, I have to click/focus it first

__Steps to Reproduce__

1. Have two tabs open
2. Click on the second tab
3. Try to close the first tab without clicking on it / opening it first

__Expected Behavior__

I can close the tab without clicking it first. 

Why? Otherwise I need to always do 2 clicks

__Environment__

Camunda Modeler Nightly 15.12.2021

**Comment by MaxTru** [comment]
For context: this is personal feedback from myself playing around with the new tabs area. The "2 clicks" feel annoying to me.

**Comment by andreasgeier** [comment]
In the first increment of the tab bar redesign, we considered scalability and responsiveness, but not to the edge of perfection. By default, an inactive tab doesn't show the close icon, because otherwise, with many tabs opened and very small tab widths, it would become hard/impossible to switch a tab (see screenshot below).

In another iteration, we could improve this with a style switch based on the width of the tabs (like Chrome does, for instance). This would be an enhancement of the tab bar.

![Screen Shot 2021-12-14 at 11 52 26](https://user-images.githubusercontent.com/938244/146196476-709700d3-f6d0-4c43-a487-277b109f5a6a.png)

**Comment by nikku** [comment]
My gut feeling is that we'll get such feedback more often. Personally I'd assume our modeling UX shall be similar to existing DEV tools out there; if being able to close a tab without focusing it is a thing (and it is) we shall support it, too.

But I also do understand that we may have a fundamental conflict here with regards what our "behavioral reference" shall be: A developer tool with a certain behavior, or a browser with a different behavior. I see us moving to "browser" being our reference here lately.

Cf. also https://github.com/camunda/camunda-modeler/pull/2631#issuecomment-993424269.

**Comment by MaxTru** [comment]
Let's do the following:
* For 5.0.0 stable we should not degenerate quality
* Doing 2 clicks instead of 1 for an action that for sure is quite heavily used is a degeneration
* Hence: let's tackle the improvement @andreasgeier mentioned. If we cannot tackle it, we will just always show the `x` in some pragmatic way and accept that is overlaps if there are too many tabs open

Moving this to ready

**Comment by pinussilvestrus** [comment]
So the aimed solution is:
* Show the close handle on every tab
* If the tab width reaches a certain value (we currently use [45px for the `tab--small` selector](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/primitives/TabLinks.js#L36)), only display it at the active tab

That's how Chrome behaves. Is that correct?

**Comment by pinussilvestrus** [comment]
45px might be too less

![image](https://user-images.githubusercontent.com/9433996/147923491-62e3795f-7081-4a39-9f25-e705c5e53777.png)

**Comment by andreasgeier** [comment]
The threshold should be increased so that a reasonable part of the file name is visible. I would try 90px. On a 1200px wide display, this would still allow opening 10 tabs with a visible close button.

**Comment by pinussilvestrus** [comment]
I introduced two modes now in relation to the tab width:

a) threshold = 90px ==> only active tab has the close handle
b) threshold = 45px ==> file name got hidden, only icons are visible (that's the is-state)

![Kapture 2022-01-03 at 14 54 26](https://user-images.githubusercontent.com/9433996/147938791-cd2170c1-e1eb-4c00-8eef-4339849e7fb2.gif)

I like that solution, wdyt @andreasgeier @MaxTru?

**Comment by andreasgeier** [comment]
Okay for me.

**Comment by MaxTru** [comment]
+1 I like
