### ISSUE TITLE
Annotations attached to DataStore do not remain attached when moving datastore

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#264]
Version 0.6.0 (1458750623) OS X 10.11.4

Have the following text scenario BPMN:
![screen shot 2016-05-01 at 3 02 05 pm](https://cloud.githubusercontent.com/assets/1994838/14943699/e6eceaf6-0fad-11e6-9c1a-dd1a66bb4fca.png)

If you create the process in the modeller without saving and closing the app it does not see to happen.  But if you create, save, close the app and reopen, then move the datastore the following happens:

Original:
![screen shot 2016-05-01 at 3 02 17 pm](https://cloud.githubusercontent.com/assets/1994838/14943702/04d0b412-0fae-11e6-9a4d-0d84679059eb.png)

When you move the datastore around (click drag, and release click):
![screen shot 2016-05-01 at 3 02 24 pm](https://cloud.githubusercontent.com/assets/1994838/14943705/245cbba0-0fae-11e6-9f95-5431e20c42a1.png)
![screen shot 2016-05-01 at 3 02 29 pm](https://cloud.githubusercontent.com/assets/1994838/14943707/27365eda-0fae-11e6-9269-3933768c8e1a.png)
![screen shot 2016-05-01 at 3 02 32 pm](https://cloud.githubusercontent.com/assets/1994838/14943708/2ab67f04-0fae-11e6-94fc-b53da86a84eb.png)
![screen shot 2016-05-01 at 3 02 37 pm](https://cloud.githubusercontent.com/assets/1994838/14943709/2e7030cc-0fae-11e6-95ed-6b5e1d4fed48.png)
![screen shot 2016-05-01 at 3 02 42 pm](https://cloud.githubusercontent.com/assets/1994838/14943710/31d780d0-0fae-11e6-84be-0f8435d61876.png)
![screen shot 2016-05-01 at 3 02 47 pm](https://cloud.githubusercontent.com/assets/1994838/14943712/34799026-0fae-11e6-9a18-30516165518d.png)

The annotation arrows are selectable and moveable, and can be reattached to the datastore.  But if you continue to move the datastore around the arrows eventually reattach as other detach, as you can see in the images above.

**Comment by vkatushenok** [comment]
Thank you for reporting this.

This is known problem and we will look in to this at some point.

**Comment by StephenOTT** [comment]
@vkatushenok thanks. Is there any breaking effects when the annotations visibly disconnect?  Are they actually disconnecting?

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/issues/479
