### ISSUE TITLE
Support Element Templates for Camunda Cloud BPMN diagrams

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2640]
> **This is an epic issue that may be broken down into multiple tasks if needed**

__Is your feature request related to a problem? Please describe.__

Support Element Templates for Camunda Cloud BPMN diagrams following the same concept as exists for Camunda Platform BPMN diagrams. (c.f. [element template docs](https://github.com/camunda/camunda-modeler/tree/develop/docs/element-templates))

__Describe the solution you'd like__

* Use the same concept as we have (c.f. [docs](https://github.com/camunda/camunda-modeler/tree/develop/docs/element-templates))
* In the first step, support
  * `zeebe:taskDefinition` (`String`, `Dropdown` or `Hidden` binding + support for constraints)
  * `zeebe:taskHeader` (`String`, `Dropdown` or `Hidden` binding + support for constraints)
  * `zeebe:input`(`String`, `Dropdown` or `Hidden` binding + support for constraints)
  * `zeebe:output` (`String`, `Dropdown` or `Hidden` binding + support for constraints)
* Consider an overall flag for an element template to indicate for which execution platform they are valid
* To consider / cherry-on-top: `optional` attribute => https://github.com/bpmn-io/bpmn-js-properties-panel/issues/501#issuecomment-1013090577

__Breakdown__

- [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/540
- [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/559
- [x] https://github.com/camunda/camunda-modeler/issues/2673
- [x] Learn from first user story and make element templates a platform agnostic feature (C7 vs. C8)
  - [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/561
  - [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/562
- [x] #2731
- [x] #2723
- [x] #2786
- [x] Consider (bpmn.io) blog post for `cloud-element-templates` => cf. [`bpmn-io/internal-docs#403` (comment)](https://github.com/bpmn-io/internal-docs/issues/403#issuecomment-1057771316)

__Describe alternatives you've considered__

* Re-build a new concept => does not make sense. Element templates concept as-is works fine.
* ...

__Additional context__

Also see archived zeebe-modeler issue https://github.com/zeebe-io/zeebe-modeler/issues/119
Related to https://github.com/camunda/product-hub/issues/2
[Element templates docs](https://github.com/camunda/camunda-modeler/tree/develop/docs/element-templates)

There does not exist a dedicated BPMN extension element reference for Zeebe. The [examples should be used](https://docs.camunda.io/docs/components/modeler/bpmn/service-tasks/service-tasks/#xml-representation) as a reference.

**Comment by pinussilvestrus** [comment]
Another thing that might be important for the Connectors story after a chat with @nikku and @pihme (maybe not in the first iteration) 
* Inputs and outputs are also relevant
* Inputs and outputs support dynamic binding ("=expression") or static values ("1") => that might conclude in another type "Expression" if we decide to provide additional editor tooling around it

In general, the existing templates concept fits well with what we need for the Connectors story, although there are unclarified things regarding the connection of a template and a connector implementation (top-down vs. bottom-up). Either way, we can start with the way element templates are currently working.

**Comment by pinussilvestrus** [comment]
Let's close this one as all implementation tasks are done. To consider: https://github.com/bpmn-io/internal-docs/issues/403#issuecomment-1057771316
