### ISSUE TITLE
Support completion condition for multi-instance

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-modeler#2641]
__Is your feature request related to a problem? Please describe.__

Zeebe will gain support for completion condition for multi-instance with https://github.com/camunda-cloud/zeebe/pull/8321. Users should be able to model this expression in the modeler, instead of having to change the XML directly.

__Describe the solution you'd like__

I want to be able to set the completion condition expression for multi-instance elements from the modeler's properties panel.

In the properties panel, under `Multi-Instance`, a new input field could be added that:
- when some text is entered, it creates the `<completionCondition>` element inside the `<multiInstanceLoopCharacteristics>` element if the `completionCondition` element does not yet exist, **and always**  updates the content of the element with the provided text
- when the text is removed, it removes the `<completionCondition>` element from the `<multiInstanceLoopCharacteristics>` element.

__Describe alternatives you've considered__

None

__Additional context__

In the xml, a multi-instance element has a `<multiInstanceLoopCharacteristics>` child element. This `multiInstanceLoopCharacteristics` element should have a child element `<completionCondition>` which itself contains the expression as content. See [BPMN/2.0.2](https://www.omg.org/spec/BPMN/2.0.2/PDF) pages 192, 198, 432 and 433.

Zeebe expects the completion condition to be a FEEL-expression that evaluates to a boolean value.
Zeebe expects FEEL-expression to be prefixed by `=`.

See: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/530

**Comment by korthout** [comment]
@barmac Thanks for the fix. I see that this is connected to the 5.0.0-alpha release. Will that be the next generally available modeler version? Or will there be a stable release that will contain this feature?

**Comment by korthout** [comment]
@barmac I'm asking because of https://github.com/camunda-cloud/camunda-cloud-documentation/pull/509#pullrequestreview-843413303. We want to publish the documentation once this feature is supported by the modeler. Is the alpha release a real release, or just something to try out stuff?

**Comment by barmac** [comment]
Let's sync via DM.
