### ISSUE TITLE
Error notification hides log panel (and actual error message)

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2643]
__Describe the Bug__

When I import a broken diagram I did previously get details from the log immediately. With the new placement of notifications major parts of the log contents are hidden. I have to close the notification (not that simple) before accessing it:

![capture bZ2m5R_optimized](https://user-images.githubusercontent.com/58601/146672472-17f84a68-2061-4679-aabf-748d4ec30ae4.gif)

__Steps to Reproduce__

* Open a broken diagram, i.e. [error-test.bpmn.txt](https://github.com/camunda/camunda-modeler/files/7740664/error-test.bpmn.txt)
* See notification hiding log

__Expected Behavior__

After an error occurs I get straight forward access on the error.

__Environment__

- OS: Any
- Camunda Modeler Version: `dev`
- Execution Platform: Any
- Installed plug-ins: None

**Comment by nikku** [comment]
I do believe this is a UX regression we shall fix.

**Comment by nikku** [comment]
@smbea Can you have a look at this one? Maybe you can think of a simple solution.

**Comment by andreasgeier** [comment]
No matter where a toast notification is placed, there is never a solution that works 100% in all scenarios. It is the nature of a toast that content will be overlapped.

I can imagine these options:
- do nothing - message can be closed anytime with the X
- do not open the log by default but bring back the "See log view" link in the message which would cause the message to close and the log to open

What we shouldn't do: change the position of the notification.

**Comment by nikku** [comment]
I think this option you suggested could be worth exploring: 

> do not open the log by default but bring back the "See log view" link in the message which would cause the message to close and the log to open.

**Comment by smbea** [comment]
I agree. There isn't much we can do here and changing the position of the notification doesn't make sense.
I also like the "see log" link option. But we should keep in mind that opening the log from the notification may require some effort - not just a simple link.
