### ISSUE TITLE
Provide Ability to Copy DMN Rule Rows

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#265]
Seems you can only copy DMN cells but not the entire row.  Need the ability to copy and paste the entire row.  

Users often have large number of rules that are similar but with minor differences.  Being able to copy and paste the entire row is a HIGE timesaver.

**Comment by vkatushenok** [comment]
There is an existing [issue](https://github.com/bpmn-io/dmn-js/issues/30) for that in `dmn-js`.

**Comment by ricardomatias** [comment]
Implemented with https://github.com/bpmn-io/dmn-js/issues/30.

Will be available in the next release.
