### ISSUE TITLE
Display symbol name and ID as tooltip on element hover

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#266]
Some of the Throw and Catch symbols can be easily confused, especially in more complex diagrams.  Would be great if there was a quick way to hover over symbols to have a text tooltip indicating which symbol is being used.

**Comment by nikku** [comment]
Gets addressed by bpmn-io/bpmn-js#530.

**Comment by MaxTru** [comment]
The PropPanel introduced with Camunda Modeler 5.0.0-alpha.0 shows the element type prominently on top. I would assume, that this would adress the UX problem of "easy confusion of elements". Please feel free to re-open if you disagree
![Screenshot_20220204_201902](https://user-images.githubusercontent.com/42800119/152589893-e8b323ce-835f-4e22-9b71-1f3f409b9a6d.png)
