### ISSUE TITLE
Don't use two tones of grey for the section actions

### ISSUE THREAD

**Issue by andreasgeier** [camunda/camunda-modeler#2664]
__What should we do?__

The expand/collapse arrows in the new properties panel change their color, depending on whether the section is marked as edited or not.

![Screen Shot 2022-01-11 at 14 55 33](https://user-images.githubusercontent.com/938244/148955633-ffc12b9b-a904-40c0-8971-d6217a3c6831.png)

This is repetitive information. 
Moreover, we learned from user feedback, that the greyed-out arrows may perceived as disabled.

Solution: Use the same dark grey for all section arrows.

![Screen Shot 2022-01-11 at 14 58 25](https://user-images.githubusercontent.com/938244/148956141-0d17f41d-ab8c-4bad-b37a-d45b459c28bc.png)

Same for the create (plus) button: use the same dark grey to avoid the association with being disabled.

![Screen Shot 2022-01-11 at 15 17 53](https://user-images.githubusercontent.com/938244/148959441-32e0cd0b-bc69-42c9-9b68-836f5359d9b9.png)

__Why should we do it?__

See above.

**Comment by MaxTru** [comment]
Closed via https://github.com/bpmn-io/properties-panel/pull/130
