### ISSUE TITLE
Select multiple BPMN symbols via CMD+Click on Mac

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#267]
Often need to move multiple symbols on the bpmn canvas but have to slowly move stuff around with the lasso which can be difficult to use in tight / complex diagrams.

Would be great if we could Shift+Click or cmd+click each of the symbols we wish to move and they would be grouped together.  Typical multi-select stuff. :)

**Comment by ricardomatias** [comment]
This is already possible with 'Cmd/Ctrl+Click'.

What platform and modeler version are you using?

**Comment by StephenOTT** [comment]
@ricardomatias  Ahh interesting... okay so did more testing and on Mac it is Alt/Option + Click. Not CMD+click. Would say that is bug cause of none standard usage for multi-select on mac.

Running: OSX 10.11.4.
Version 0.6.0 (1458750623)
