### ISSUE TITLE
Custom element colors

### ISSUE THREAD

**Issue by Praweisschen** [camunda/camunda-modeler#2676]
I use Camunda Modeler mainly for visualising processes (in my day to day work and my thesis). For that use of color can be beneficial to differienciate between certain levels/views. At the moment there is only 5 colors I can use. In some cases, I want them to fit my document design though.

__Describe the solution you'd like__
Therefore I would like the option to add custom colors to the selection. Adding colors by hexcode or RGB-values in an option-pane that are then visible when you select the paintbrush - that would be ideal.
As every element consists of two colors (frame + text, background color), every "custom color" should really consist of color1 and color2.

**Comment by nikku** [comment]
There exists the [color picker extension](https://github.com/camunda-community-hub/camunda-modeler-plugin-color-picker) to choose from arbirary colors.

However, considering the core we rather not allow arbitrary shades of colors. I personally believe that having multitudes of colors, all things considered, won't benefit our users at large.

If you want to share additional inspirations (i.e. what a better color selection could look like) that feedback is appreciated.

I'm closing this issue though as I don't see us being able to implement the configuration capability you're asking for any time soon.
