### ISSUE TITLE
Remove Selected needs a keyboard shortcut

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#268]
There is no default keyboard shortcut for Edit -> Remove Selected

This makes deleting fairly slow and burdensome :)

Need a default keyboard shortcut for Remove Selected

**Comment by ricardomatias** [comment]
You should be able to do it with the 'Delete' key.

What platform and modeler version are you using?

**Comment by nikku** [comment]
Duplicate of #255 if you are using Mac.

**Comment by StephenOTT** [comment]
Blah was searching for "Remove selected" :)
