### ISSUE TITLE
Rearrange the process property panel

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#2680]
__Is your feature request related to a problem? Please describe.__

From the developers perspective, the sections of the process should be rearraged according their relevance.

__Describe the solution you'd like__

in the moment, the property panel for a process on Platform looks like:
![grafik](https://user-images.githubusercontent.com/7870843/149758113-35faea34-63b3-4862-adfd-c12d0fb7e10c.png)

Sorting by relevance it should look like:
* General
* Documentation
* History cleanup
* Tasklist
* Candidate starter
* External task
* Job execution
* Execution listeners
* Extension properties

__A clear and concise description of any alternative solutions or features you've considered.__

At least bring the two tasklist sections together: Candidate starter and Tasklist.

Add any other context or screenshots about the feature request here. For example, provide the execution platform you're operating on (Camunda Platform, Camunda Cloud, ...)

## Camunda Modeler system information
 * Version: 4.13.0-nightly.20220116
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform

**Comment by andreasgeier** [comment]
@ingorichtsmeier Thank you very much for your proposal.

Documented in [this spreadsheet](https://docs.google.com/spreadsheets/d/1jw1TkK7YS0PMPQouDpdKHzfnb0wBNvMAfKI-jJI8LCI/edit#gid=0).

![Screen Shot 2022-01-31 at 14 16 39](https://user-images.githubusercontent.com/938244/151800121-b4a0dbc7-043f-4eaf-8bb4-2069ebfe1096.png)
