### ISSUE TITLE
Cannot open a diagram if executionPlatformVersion is unknown

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2682]
__Describe the Bug__

When I try to open [this diagram](https://github.com/camunda/camunda-modeler/files/7881867/diagram_1.bpmn.txt) which is a valid BPMN but with `modeler:executionPlatformVersion="7.14.0`, Modeler displays a dialog and refuses to display the diagram.

```xml
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" id="Definitions_1snrxfq" targetNamespace="http://bpmn.io/schema/bpmn" xmlns:modeler="http://camunda.org/schema/modeler/1.0" modeler:executionPlatform="Camunda Platform" modeler:executionPlatformVersion="7.14.0">
```

![image](https://user-images.githubusercontent.com/28307541/149770838-813a19b8-4547-4898-8a3c-f0f6d85f6841.png)

__Steps to Reproduce__

1. Download the nightly
2. Try to open [the diagram](https://github.com/camunda/camunda-modeler/files/7881867/diagram_1.bpmn.txt)
3. now this happens

__Expected Behavior__

Modeler should never refuse to open valid BPMN 2.0 diagrams. It could warn the user about unsupported execution platform instead.

__Environment__

- OS: MacOS
- Camunda Modeler Version: nightly as of 17.01.2022
- Execution Platform: Camunda Platform 7.14.0
- Installed plug-ins: none

__Additional context__

* [Slack conversation on this](https://camunda.slack.com/archives/CKGH9LR40/p1642423445002800?thread_ts=1642079115.015000&cid=CKGH9LR40)

**Comment by MaxTru** [comment]
The rationale behind this is:
* The Modeler can deal with diagrams which dont have an exectionPlatformVersion set
* If the Modeler reads an unknown exectuinPlatformVersion, it will not open the file. Consider the cases:
  * `foobar` => does not make sense. Also why would a user set it? Hence rejection is okay
  * `7.22` => may not be supported by the current modeler version. Hence rejction is okay
  * `7.14` => some old version. Note that setting to 7.14.0 in the first place must have been a manual activity. Hence rejection is okay

**Comment by MaxTru** [comment]
After conversation with Maciej I am reopening this. This is valid feedback and the decision we made (see previous comment) may be revised. We will just leave this open to have a issue to collect feedback on this. We will not take any action soon.

**Comment by nikku** [comment]
I do believe a simple thing we could do is the following:

* accept all versions of Camunda Platform; only allow to set recent versions

**Comment by nikku** [comment]
Would be interesting to figure out what leads a user to enter an unsupported (because too old) execution platform version in the first place.

**Comment by MaxTru** [comment]
Thanks for the feedback Ingo.

I suggest we invest into the solution proposal by @nikku 
> accept all well known versions of Camunda Platform; only allow to set recent versions

+ Addition to be clear: linting will only kick in for known versions (obviously)

**Comment by MaxTru** [comment]
Will not be able to do it this iteration

**Comment by barmac** [comment]
Hi @schreuder71,

In the XML, find `bpmn:definitions` (it should be the top-most element), and modify it as in the diff below:

```diff
- <bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" id="Definitions_0rih9zo" targetNamespace="http://bpmn.io/schema/bpmn" xmlns:modeler="http://camunda.org/schema/modeler/1.0" exporter="Camunda Modeler" exporterVersion="5.0.0" modeler:executionPlatform="Camunda Platform" modeler:executionPlatformVersion="7.14.0">
+ <bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" id="Definitions_0rih9zo" targetNamespace="http://bpmn.io/schema/bpmn" xmlns:modeler="http://camunda.org/schema/modeler/1.0" exporter="Camunda Modeler" exporterVersion="5.0.0" modeler:executionPlatform="Camunda Platform" modeler:executionPlatformVersion="7.15.0">
```

Specifically, it's this part:

```diff
- modeler:executionPlatformVersion="7.14.0">
+ modeler:executionPlatformVersion="7.15.0">
```

**Comment by schreuder71** [comment]
Excellent. Thank you that worked.

**Comment by nikku** [comment]
This is coming up [more often then expected](https://camunda-modeling.sentry.io/issues/?alert_rule_id=1077807&alert_timestamp=1686045571259&alert_type=email&environment=production&project=5223041&query=is%3Aunresolved+execution+platform&referrer=issue-list&sort=user&statsPeriod=14d). We've seen around ~150 users being affected in the last 14 days, likely due to the following scenario:

* User creates diagram with a newer modeler version
* Colleague tries to open diagram with an older modeler version
* We throw with an error

A resolution could be, as suggested, to handle this issue more gracefully: 

* Be optimistic about future engine version support (still open, assume latest known version, indicate miss-match)
* Be optimistic about past version support (still open, assume no version being set)

**Comment by nikku** [comment]
Again this affected roughly 200 users in the last 14 days.

I propose that we re-consider this. The least thing we could do is to cater towards users using outdated Camunda Modelers and give them a hint to try an update Desktop Modeler version.

**Comment by nikku** [comment]
Roughly 240 users affected in the last 14 days.
