### ISSUE TITLE
Modeler marks multiinstance subprocess as not supported

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#2686]
__Describe the Bug__

Modeler complains about a multiinstance Embedded subprocess for Camunda Cloud. But the element is supported regarding the docs. 

__Steps to Reproduce__

Open this process model: 
[order-process.zip](https://github.com/camunda/camunda-modeler/files/7888545/order-process.zip)

You get an error in the console like 
![grafik](https://user-images.githubusercontent.com/7870843/149927485-25ac67c8-d746-451f-98fb-3d02c1a5a0cf.png)

The error didn't disappear if you cange to later versions of Camunda Cloud.

__Expected Behavior__

The process opens successfully without any error. Cloud docs say, that the element is supported in version 1.1: https://docs.camunda.io/docs/1.1/reference/bpmn-processes/multi-instance/multi-instance/

__Environment__

## Camunda Modeler system information
 * Version: 4.13.0-nightly.20220116
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Cloud

**Comment by MaxTru** [comment]
Thanks for reporting!

I can reproduce and confirm. Moving to backlog and marking for spring cleaning

**Comment by MaxTru** [comment]
Fixed upstream via https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/6

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2817
