### ISSUE TITLE
Building error on Mac Os

### ISSUE THREAD

**Issue by PythonicArt** [camunda/camunda-modeler#2691]
I am building the modeler according to the readme file. After checkout v1.1.0 and npm run all, I got the flowing error message.

```
stderr:
   'npm ERR! peer dep missing: sinon@>=2.1.0 <5, required by karma-sinon-chai@1.3.4\n' }
```

I have tied to solve this problem by changing the version of ‘sinon’ to 2.1.0 in devDependencies of the package.json. When I run ‘npm install’, i got these warning:

```
npm WARN notsup Unsupported engine for karma@0.13.22: wanted: {"node":"0.10 || 0.12 || 4 || 5"} (current: {"node":"10.24.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: karma@0.13.22
npm WARN notsup Unsupported engine for stringify@3.2.1: wanted: {"node":"<=0.10.26"} (current: {"node":"10.24.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: stringify@3.2.1
npm WARN karma-sinon-chai@1.3.4 requires a peer of sinon@>=2.1.0 <5 but none is installed. You must install peer dependencies yourself.
```

It can build successfully but when I run the app,  I got these runtime errors:

```
Uncaught Exception:

Error: Cannot find module ‘concat-map’

at Module._resolveFilename (module.js:438:15)

at Function.Module._resolveFilename (/Users/michaeltang/nn/camunda-modeler/distro/Camunda Modeler-darwin-x64/Camunda Modeler.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)

at Function.Module._load (module.js:386:25)

at Module.require (module.js:466:17)

at require (internal/module.js:20:19)

at Object. (/Users/michaeltang/nn/camunda-modeler/distro/Camunda Modeler-darwin-x64/Camunda Modeler.app/Contents/Resources/app.asar/node_modules/brace-expansion/index.js:1:96)

at Module._compile (module.js:541:32)

at Object.Module._extensions…js (module.js:550:10)

I have no idea to figure out a resolution for it for now
```.

__Environment__

- OS: Mac OS Monterey 12.1, Apple M1.
-Node 10.24.1
-npm 6.14.12

**Comment by PythonicArt** [comment]
> 

![image](https://user-images.githubusercontent.com/19612522/150158762-73fcdbb8-5f8c-4196-bb71-61060e282ac5.png)
I am not sure if I misunderstood the guide to building the app. If I use the current one rather than the v1.1.0?

**Comment by MaxTru** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/19612522/150158762-73fcdbb8-5f8c-4196-bb71-61060e282ac5.png) I am not sure if I misunderstood the guide to building the app. If I use the current one rather than the v1.1.0?

That is just an example, but 1.1.0 is from 2016. Currently we are on 4.12.0.

But I will take this as an action (obviously this is confusing), and will adjust the guide.

Can you please try to run

```
git checkout master
``` 

instead?

**Comment by PythonicArt** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/19612522/150158762-73fcdbb8-5f8c-4196-bb71-61060e282ac5.png) I am not sure if I misunderstood the guide to building the app. If I use the current one rather than the v1.1.0?
> 
> That is just an example, but 1.1.0 is from 2016. Currently we are on 4.12.0.
> 
> But I will take this as an action (obviously this is confusing), and will adjust the guide.
> 
> Can you please try to run
> 
> ```
> git checkout master
> ```
> 
> instead?

It works and thanks for your reply!
