### ISSUE TITLE
Improve UX of Deployment to Camunda Cloud

### ISSUE THREAD

**Issue by andreasgeier** [camunda/camunda-modeler#2707]
__Is your feature request related to a problem? Please describe.__

As a Desktop Modeler user, I am familiar with how to deploy diagrams to a local Camunda platform. But I failed to deploy to Camunda Cloud. I struggled with:

- I wasn't sure if `Contact point` would accept a web address, the placeholder displays an IP
- I wasn't sure if the URL should contain the port since the port is mentioned in the text file that I downloaded after the client creation but not in the client information dialog on the cluster page. (for contact point, the port is needed)
- I had absolutely no idea what `Audience` means. This term is mentioned nowhere. (it's the cluster URL aka contact point but without the port)
- It's annoying that the credentials are stored only when I successfully deploy a diagram although I toggled `Remember credentials`. During my attempts to deploy I had to enter the data over and over again (5 inputs!). 
- The [documentation](https://docs.camunda.io/docs/guides/getting-started/deploy-your-process-and-start-process-instance/) is outdated and didn't help at all.

__Describe the solution you'd like__

- For `Contact point`, consider a description that makes clear that it accepts a local IP as well as a web address.
- For `Contact point`, make clear that the port is a required information.
- On the client page on Console, add the port to the `Cluster URL`.
- On the client page on Console, add a field for `Audience`.
- The text file that I can download after client creation (with the client secret) should contain the same information as the client information dialog on Console.
- Store the credentials immediately when I toggle `Remember credentials`
- Bring the documentation up to date.

__Describe alternatives you've considered__

n/a

__Additional context__

See the differences between text file, client modal, and Desktop Modeler deploy dialog.

![Screen Shot 2022-01-25 at 17 48 04](https://user-images.githubusercontent.com/938244/151021336-215aefd9-fd27-4077-bc7b-00132ad7c08b.png)

**Comment by barmac** [comment]
Regarding the `audience`, I found it in the docs: https://docs.camunda.io/docs/self-managed/zeebe-deployment/security/client-authorization/#java-1

**Comment by MaxTru** [comment]
To consider: if audience is always `URL - port`, we could just programmatically derive it...

**Comment by barmac** [comment]
Related to https://github.com/camunda/camunda-modeler/issues/2636

**Comment by smbea** [comment]
Scope decided on alignment meeting:

* find out if audience is always cluster URL minus port
    * if so then we can omit field
    * if not give field description/hint
* contact point:
   * remove default text, add placeholder
   * change label to "Cluster endpoint"
   * add validation for port
* remember credentials
   * make it always available (for self managed too)
   * save onSubmit and onClose
* invalid credentials/connection
   * extract error message to not belong to a single field
   * block deploy
* decided not to change documentation for now

**Comment by nikku** [comment]
@smbea @andreasgeier regarding https://github.com/camunda/camunda-modeler/issues/2862 I assume this is aligned with our general direction of travel? I am personally not a fan of this (rather love _to do_ an bear the consequences of my actions), but I've seen the same pattern in the web modeler, too.

As long a we're consistent, we're fine.

**Comment by barmac** [comment]
For more context, check out the design prepared by @nazlikaya based on which we stopped to disable deploy button: https://confluence.camunda.com/pages/viewpage.action?spaceKey=PD&title=Input+Fields+Validation

**Comment by nikku** [comment]
@barmac I'm confused. The links explicitly do not state submit being disallowed. What we're doing now is disallowing submit (cf. https://github.com/camunda/camunda-modeler/issues/2862).

**Comment by barmac** [comment]
Quite contrary - in the design we allowed to click submit again, that's why I said "**stopped** to disable deploy button". Sorry for poor communication.

To make it clear: [The design I linked](https://confluence.camunda.com/pages/viewpage.action?spaceKey=PD&title=Input+Fields+Validation) is for when we changed the submit button to be always enabled unless the form is being submitted. Before, it used to be disabled when there were validation errors.

**Comment by MaxTru** [comment]
@nikku @barmac Thanks for raising.

We should adhere to the guidelinehere.

@smbea @christian-konrad I propose to adjust https://github.com/camunda/camunda-modeler/issues/2862 as following:
* Keep the task to:
> Extract general error message to not belong to a single field - currently, it is always applied to 'Cluster URL' field, regardless of which field is incorrect

* Descope:
> Disable the "Deploy" button if there are validation/connection errors

**Comment by barmac** [comment]
Generally, there are some good points on the web why we should not disable buttons unless there is a good reason for this. For example, check out this article: https://www.smashingmagazine.com/2021/08/frustrating-design-patterns-disabled-buttons/

**Comment by nikku** [comment]
Thanks for support @barmac :medal_military:.

Backing up my intuition with resources :truck:.

**Comment by smbea** [comment]
I have adjusted #2862 accordingly
