### ISSUE TITLE
Selection / focus outline in properties panel looks broken

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2721]
__Describe the Bug__

Interacting with the mouse on the properties panel `+ CREATE` button looks broken:

![capture 1nTUfI_optimized](https://user-images.githubusercontent.com/58601/151796194-9fd9d66c-1ccd-4d6c-9252-3963d5484d2a.gif)

__Steps to Reproduce__

1. Open properties panel
2. mouse down or keyboard select `+ CREATE` button
3. See outline

__Expected Behavior__

Outline is consistently right around the element (preferred) or with a rectangular shape.

__Environment__

- OS: Linux
- Camunda Modeler Version: v5.0.0-alpha.1
- Execution Platform: Any

**Comment by pinussilvestrus** [comment]
Related: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/503

**Comment by nikku** [comment]
Feel free to close, if duplicate :).

**Comment by pinussilvestrus** [comment]
Alright 👍  I added the spring cleaning to the upstream issue 🧹
