### ISSUE TITLE
Closing All Tabs Sometimes Leads to Empty Tab Not Being Displayed

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2734]
__Describe the Bug__

Closing all tabs _sometimes_ leads to an unexpected UI state where the empty tab isn't displayed. Instead the properties panel container is displayed but empty. Unfortunately this only happens sometimes.

<img width="960" alt="Camunda_Modeler_1AuDZI13kU" src="https://user-images.githubusercontent.com/7633572/153006477-89671086-f539-46e6-a33c-af8dbab9dfdf.png">

__Steps to Reproduce__

1. Open a couple of tabs
2. Close all tabs
3. Unexpected UI state

__Expected Behavior__

Empty tab is displayed.

__Environment__

- Camunda Modeler Version: 5.0.0-alpha.0
- Camunda Modeler Version: 5.0.0-alpha.1

**Comment by philippfromme** [comment]
Sometimes closing a tab doesn't display the remaining tab, too.

I had two tabs open, closed one of them without saving and got this:

<img width="960" alt="Camunda_Modeler_qvr5UZJuts" src="https://user-images.githubusercontent.com/7633572/153183577-20db37f1-253b-4249-9fcd-4dff2a033a3a.png">

**Comment by MaxTru** [comment]
Maybe related to https://github.com/camunda/camunda-modeler/issues/2732

**Comment by barmac** [comment]
The only way I was able to (consistently) reproduce it is via https://github.com/camunda/camunda-modeler/issues/2732. Check out the screencast:

https://user-images.githubusercontent.com/28307541/153574185-365782b5-b681-419c-9c02-3b6f42bee66c.mov
