### ISSUE TITLE
Missing properties panel icon for ad-hoc subprocess

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2749]
__Describe the Bug__

There's no icon for both expanded and collapsed ad-hoc subprocess:

<img width="1520" alt="image" src="https://user-images.githubusercontent.com/28307541/153576848-67e5d662-aa97-47cf-9517-da3b16168e0e.png">

__Steps to Reproduce__

1. Create ad-hoc subprocess
2. now this happens

__Expected Behavior__

There should be an icon. A subprocess icon should be sufficient.

__Environment__

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.0.0-alpha.0 and 1
- Execution Platform: Camunda Platform
- Installed plug-ins: [...]

**Comment by barmac** [comment]
@andreasgeier I think you might be interested in this.

**Comment by MaxTru** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/583
