### ISSUE TITLE
Undo after Collapsed Subprocess ID change breaks the modeler

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#2750]
__Describe the Bug__
The Modeler blows up if I try to remove a collapsed subprocess with `undo` after I changed the ID
![Recording 2022-02-11 at 11 55 14](https://user-images.githubusercontent.com/21984219/153579631-33558258-67bd-4b0e-9cab-d6ff9926e082.gif)

__Steps to Reproduce__

1. model a collapsed subprocess
2. drill into it
3. change the ID
4. Spam undo
5. An error occurs

__Expected Behavior__
No error is shown and the shape is deleted

__Environment__

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.0.0-alpha.1
- Execution Platform: Camunda Platform
- Installed plug-ins: [...]

**Comment by barmac** [comment]
I am able to reproduce this.

Uploading Screen Recording 2022-02-11 at 11.05.26.mov…

**Comment by barmac** [comment]
If I undo only once, it only breaks the drilldown:


https://user-images.githubusercontent.com/28307541/153584448-2573b509-503d-4e93-a3fa-27d7d0357cd4.mov

**Comment by marstamm** [comment]
Root cause: Undo breaks the link `id` <-> `id_plane`

![image](https://user-images.githubusercontent.com/21984219/153586137-8f906fe2-35b9-4199-9f89-357052454358.png)
(`data-element-id` should always be the plane Element for layer graphics)

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2817
