### ISSUE TITLE
Group inside collapsed subprocess breaks the Modeler

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2751]
__Describe the Bug__

When I try to place a group inside of a collapsed subprocess, it breaks the Modeler. It breaks the whole application and I have to restart to make it work again as the errors are constantly thrown even after I change the tab.

The same applies to a situation when I try to collapse a subprocess with a group inside added in the XML.

<img width="1520" alt="image" src="https://user-images.githubusercontent.com/28307541/153581132-32a06278-567a-4f63-803a-a22813a53922.png">

__Steps to Reproduce__

1. Create a collapsed subprocess and drill down
2. Place a group on the diagram
3. now this happens

__Expected Behavior__

No error is thrown. A group is an artifact and I should be able to place them in a subprocess.

__Environment__

- OS: MacOS
- Camunda Modeler Version: 5.0.0-alpha.1
- Execution Platform: Camunda Platform
- Installed plug-ins: [...]

**Comment by MaxTru** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js/pull/1599

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2817
