### ISSUE TITLE
`.bpmn` files of similar names break eachother on saving

### ISSUE THREAD

**Issue by Skaiir** [camunda/camunda-modeler#2753]
__Describe the Bug__

When opening different files with names starting with `{name}.bpmn`, the modeler seems to conflate them in some way. This leads to the two tabs influencing each-other after having saved them both at least once.

This triggers the `file has been changed externally` warning occasionally when clicking around the tabs.
The models also just starts reverting every change you make on save once two files have been saved once.

![Two files of the same name](https://user-images.githubusercontent.com/17801113/153606652-306260b6-f2f4-4a24-aa2c-1bf0e9a5fe4f.gif)

I'll admit this is a niche case but it is new to `5.x` and could not be replicated on `4.7` and `4.12`

I believe this is not an issue for DMN because we do not accept files of the format `{name}.dmn.{suffix}`, but feel free to correct me here.

__Steps to Reproduce__

1. Open modeler 5
2. Create any bpmn diagram
2. Save it
3. Clone the file and add a suffix to the clone (example, test.bpmn -> test.bpmn.wow)
4. Open both files
5. File A
	- Change file
	- Save file
	- Change file
	- Save file -> works as expected
6. File B, repeat above sequence, works as expected
7. File A, repeat above sequence, broken

__Expected Behavior__

Both file should either be considered entirely different, or entirely the same (and open in the same tab). There shouldn't be any side effects of the sort.

__Environment__

- OS: Win10x64
- Camunda Modeler Version: 5.0.0-alpha.1
- Execution Platform: bpmn cloud, platform, 
- Installed plug-ins: [...]

**Comment by marstamm** [comment]
Closing as we assume it is fixed with https://github.com/camunda/camunda-modeler/pull/2755 . We can always reopen if it reappears
