### ISSUE TITLE
Combination Generator?

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#276]
Anyone have thoughts on a built in or extension that is a combination generator for Rule Rows?

Example: Two inputs may be Zone and Day of Week.  Zone is values 1 to 10 and Day of Week is Mon, tue, wed, thur, fri, sat, and sun.

The outputs are different for each combination of Zone and day of week, and each zone has each day of week.

So...

Zone 1, Mon
Zone 1, Tue,
...
Zone 1, Sun,
Zone 2, Mon,
Zone 2, Tue,
etc.

Obviously we can speed the development of this with the build in Excel and then import into Modeler, but has any planning been done on long term usage?  Is the idea for large tables they would be developed in Excel and then copied over?  Any ideas for a Generator that you state the combination pattern and let it generate the rule rows?

**Comment by nikku** [comment]
This is nothing we are going to support in the near future.

**Comment by nikku** [comment]
If I would implement this I'd rather create a small tool that prepares tables with the given combinations _outside the scope of the Modeler_ (i.e. generates the boilerplate). The user may then fill in the gaps _using the Modeler_.

**Comment by StephenOTT** [comment]
@nikku i was on the same line of thinking.  Excel/Spreadsheets seems to be the best/most flexible option.
