### ISSUE TITLE
Zeebe Deploy Plugin crashes when open and then creating new tab

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2762]
__Describe the Bug__

Zeebe Deploy Plugin crashes when open and then switching tabs
```
[plugin:ZeebePlugin] Cannot read property 'getBoundingClientRect' of null
```

__Steps to Reproduce__

1. Create Cloud Diagram
2. Save Cloud Diagram
3. Click on "deploy"
4. Leave "deploy" dialog open
5. Click on new => Platform diagram
6. => Error `Zeebe Deploy Plugin crashes when open and then switching tabs`
![Peek 2022-02-16 09-24](https://user-images.githubusercontent.com/42800119/154224672-490b8d84-525b-4f8d-936c-a799ebec5071.gif)

__Expected Behavior__

In this case, the deploy dialog should be closed (compare to how this works when creating a new file via the `+` button)

__Environment__

- OS: Linux
- Camunda Modeler Version: 5.0.0-alpha.1

**Comment by smbea** [comment]
This happens for **start instance and deploy** in **platform and cloud** diagrams.
