### ISSUE TITLE
Register additional modules plugins `bpmn.modeler.additionalModules` and moddle extensions in C8

### ISSUE THREAD

**Issue by Skaiir** [camunda/camunda-modeler#2766]
__Is your feature request related to a problem? Please describe.__

Currently we do not pick up `bpmn.modeler.additionalModules` registered plugins in the C8 bpmn diagram editor, hence making plugins impossible to use there. We want to replicate the functionality here, this key should from now on be used to register plugins which aren't specific to c7 or c8. 

Edit: as part of this we should also pick up `bpmn.modeler.moddlextension`

__Describe the solution you'd like__

The c8 functionality for this should match that of c7.

__Describe alternatives you've considered__

We've considered to split up c7 and c8 registration keys, which we will do in a further issue to allow targeting of specific bpmn versions, however this would break existing plugin registration which isn't ideal. Hence we'll keep this functionality for compatibility reasons.

**Comment by pinussilvestrus** [comment]
I guess this will resolve this issue as well: https://github.com/camunda/camunda-modeler/issues/2284

We should inform in the other issue once it's fixed, I think some people will be excited 🙂

**Comment by Skaiir** [comment]
Thanks for linking this :D
