### ISSUE TITLE
Add a `disable-form` flag

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2767]
__Is your feature request related to a problem? Please describe.__

You an disable CMMN, and DMN, but not Forms in the Camunda modeler.

__Describe the solution you'd like__

Have a flag `disable-form`, just as we have `disable-dmn`. Add it to our existing flags infrastructure:  https://github.com/camunda/camunda-modeler/tree/develop/docs/flags

__Describe alternatives you've considered__

n/a

__Additional context__

n/a

**Comment by nikku** [comment]
Makes sense. Any specific use-case where you would like to disable forms?

**Comment by nikku** [comment]
Makes sense. Thanks.

**Comment by Skaiir** [comment]
@MaxTru There is already this exact flag in the app dating back 6 months though, am I missing something or can this be closed?

![image](https://user-images.githubusercontent.com/17801113/162155579-fcfeb8bf-177a-48c6-9586-aa7c1f55c1e5.png)

![image](https://user-images.githubusercontent.com/17801113/162155654-bb89b17c-3f46-4a3b-a402-2855e5e0fb15.png)

**Comment by MaxTru** [comment]
Good catch. Then the bug is that https://docs.camunda.io/docs/components/modeler/desktop-modeler/flags/#available-flags is outdated :-)

Can you please follow up in the camunda-cloud-docs?

**Comment by Skaiir** [comment]
@MaxTru There are a few which aren't in the docs, should we put them all in there?

```js
export const DISABLE_CMMN = 'disable-cmmn';
export const DISABLE_DMN = 'disable-dmn';
export const DISABLE_PLATFORM = 'disable-platform';
export const DISABLE_ZEEBE = 'disable-zeebe';
export const DISABLE_ADJUST_ORIGIN = 'disable-adjust-origin';
export const DISABLE_PLUGINS = 'disable-plugins';
export const DISABLE_REMOTE_INTERACTION = 'disable-remote-interaction';
export const DISPLAY_VERSION = 'display-version';

export const DISABLE_FORM = 'disable-form';
export const RELAUNCH = 'relaunch';
export const UPDATE_SERVER_URL = 'update-server-url';
export const FORCE_UPDATE_CHECKS = 'force-update-checks';
export const SENTRY_DSN = 'sentry-dsn';
export const ET_ENDPOINT = 'et-endpoint';
```

`usr-data-dir` and `single-instance` exist but are only tested locally, not through util.

**Comment by Skaiir** [comment]
I've split them by which are referenced

**Comment by MaxTru** [comment]
Let's only add `DISABLE_FORM` since the others are more for the core developers IMO.

**Comment by Skaiir** [comment]
Yeah makes sense 👍

**Comment by ingorichtsmeier** [comment]
DISABLE_PLUGINS is important for enduser as well. If they have outdated plugins installed from somewhere else...

**Comment by MaxTru** [comment]
> DISABLE_PLUGINS is important for enduser as well. If they have outdated plugins installed from somewhere else...

True, thanks for checking :-) Let's do that

**Comment by MaxTru** [comment]
> DISABLE_PLUGINS is important for enduser as well. If they have outdated plugins installed from somewhere else...

But we have that documented already in the docs :-)

**Comment by MaxTru** [comment]
See https://docs.camunda.io/docs/components/modeler/desktop-modeler/flags/#available-flags
