### ISSUE TITLE
CI builds are broken on Windows

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2779]
__Describe the Bug__

Starting yesterday, all CI builds start to break on Windows, especially our nightly: https://github.com/camunda/camunda-modeler/runs/5324718004?check_suite_focus=true

```sh
Error output:
node-pre-gyp ERR! install response status 404 Not Found on https://node-precompiled-binaries.grpc.io/grpc/v1.24.10/electron-v12.1-win32-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.24.10 and electron@12.1.2 (electron-v12.1 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://node-precompiled-binaries.grpc.io/grpc/v1.24.10/electron-v12.1-win[32](https://github.com/camunda/camunda-modeler/runs/5324718004?check_suite_focus=true#step:5:32)-x64-unknown.tar.gz 
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! code ELIFECYCLE
npm ERR! errno 1
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
```

__Steps to Reproduce__

1. Open [builds](https://github.com/camunda/camunda-modeler/actions)
2. See that all builds are failing on Windows while installing the dependencies, beginning yesterday ~10AM

__Expected Behavior__

Builds should run green.

__Environment__

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by marstamm** [comment]
This might be a wild guess, but I had similar errors (c++ compiler missing) when [windows build tools](https://www.npmjs.com/package/windows-build-tools) were missing with react development. Do we know how the CI windows is configured?

**Comment by pinussilvestrus** [comment]
At least it works on other platforms: https://github.com/camunda/camunda-modeler/runs/5330533353?check_suite_focus=true

**Comment by pinussilvestrus** [comment]
Can one of our Windows users maybe verify whether it works locally? By doing a fresh install

```sh
npm ci
```

@philippfromme @Skaiir

**Comment by pinussilvestrus** [comment]
> ```shell
>  find VS could not find a version of Visual Studio 2017 or newer to use
> ```

Trying this one out: https://github.com/camunda/camunda-modeler/actions/runs/1897581013

**Comment by marstamm** [comment]
Might be related to latest virtual environment update https://github.com/actions/virtual-environments/commit/b410b609eb2117007c3ba135b49fa41211d9f8d1

It also fails on [other Windows versions](https://github.com/camunda/camunda-modeler/commit/5a96658e6dd1a486c91630c4bdaf5128d0fad7c4) that got an [update](https://github.com/actions/virtual-environments/commit/af602c66f746f21e1a9537261c69442f89ace12e) recently (Visual C++ 14.31 is the common change here).

**Comment by marstamm** [comment]
I just saw that the Jobs failed on Windows-2022, when `windows-latest` was windows-2019 before. Checking with explicit `windows-2019`: https://github.com/camunda/camunda-modeler/actions/runs/1897615012

**Comment by marstamm** [comment]
Works on windows 2019: https://github.com/camunda/camunda-modeler/runs/5330823564?check_suite_focus=true

What are the next steps? I guess we pin the windows version for now?

**Comment by Skaiir** [comment]
Ah guess I figure I was too late with that one, `git ci` works locally though 🤡, not that this is useful info anymore.

**Comment by pinussilvestrus** [comment]
> I guess we pin the windows version for now?

+1 for this one. We do already the same with MacOS.

On the longer runner, we should really investigate an Electron upgrade (https://github.com/camunda/camunda-modeler/issues/2538), and get rid of the C++ based grpc dependency (https://github.com/camunda-community-hub/zeebe-client-node-js/blob/master/CHANGELOG.md#breaking-changes).

**Comment by marstamm** [comment]
Found the issue that changes the target `windows-latest` version:

https://github.com/actions/virtual-environments/issues/4856

> This change will be rolled out over a period of several weeks beginning on January, 17. We plan to complete the migration by March, 6.
