### ISSUE TITLE
Rearrange the dropdowns of the Service task implementation 

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#2787]
See here: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/597

cross posting for visibility.

Found in

## Camunda Modeler system information
 * Version: 5.0.0-alpha.1
 * Operating System: Windows 10 amd64
 * Plugins: Cloud Connect, bpmn-js Token Simulation, BPMN Linter, Transaction Boundaries, Camunda Property Infos, Tooltip Plugin
 * Execution Platform: BPMN - Camunda Platform

**Comment by smbea** [comment]
Duplicate of https://github.com/bpmn-io/bpmn-js-properties-panel/issues/597
