### ISSUE TITLE
Allow user to set custom value for "version indicator" in status bar via flag

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2790]
__Is your feature request related to a problem? Please describe.__

When creating screenshots for documentation, I want to display a certain stable version, even though I am still working on an alpha version. Also cf https://github.com/camunda-cloud/camunda-cloud-documentation/pull/651

__Describe the solution you'd like__

Provide a flag that can be used to set a custom version

__Describe alternatives you've considered__

n/a

__Additional context__

n/a

**Comment by pinussilvestrus** [comment]
Related to https://github.com/bpmn-io/internal-docs/issues/444.
