### ISSUE TITLE
Error doesn't appear in the log

### ISSUE THREAD

**Issue by andreasgeier** [camunda/camunda-modeler#2793]
__Describe the Bug__

If start instance failed but the user did not click on the "show error in log" link, the error does not appear on the log at all.

(I assume the same behavior for deployment errors)

__Steps to Reproduce__

1. Create a start instance failure
2. Do not (!) click on the error message link, wait until message is closed or close it via X
3. Open log view from status bar
4. No error is shown

Screen recording:
https://user-images.githubusercontent.com/938244/156136839-0dfcced7-cf27-4635-8939-33adbdeaa017.mov

__Expected Behavior__

Write errors into the log independent from the interaction with the error notification.

__Environment__

 * Version: 5.0.0-nightly.20220217
 * Operating System: Mac OS 12.2.1 
 * Plugins: Cloud Connect
 * Execution Platform: BPMN - Camunda Platform

**Comment by smbea** [comment]
This was discussed with https://github.com/camunda/camunda-modeler/issues/2643.
Basically, the reason for this is that the notification hid the log message. Do you suggest that the log not open by default but still have the message when the user opens it?

**Comment by smbea** [comment]
Makes sense.

**Basically:** add log entry but don't toggle log view
