### ISSUE TITLE
Tab title of a form is not updated after saving a form

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-modeler#2796]
__Describe the Bug__

After saving a form in the desktop modeler, the tab title of this form is not updated. It still shows the old, pre-generated name (form-X.form)

See here:
![Bildschirmfoto 2022-03-02 um 10 37 08](https://user-images.githubusercontent.com/56470362/156336263-a2c3ed2f-48c6-4dd0-8ec7-211c42f18059.png)

__Steps to Reproduce__

1. Create a new form
2. Select a platform so form can be saved
3. Save it under a custom name
4. The form is saved under the custom name, but the tab still shows the old name

__Expected Behavior__

The tab should show the new name immediately

__Environment__

- OS: MacOS Monterey
- Camunda Modeler Version: 4.12.0
- Execution Platform: Not relevant (Both)
- Installed plug-ins: None

**Comment by smbea** [comment]
Thanks for the report @christian-konrad.
I believe this was fixed with #2581 and included from v5.0.0-alpha.0 onwards.

**Comment by nikku** [comment]
You could try out [using a nightly](https://downloads.camunda.cloud/release/camunda-modeler/nightly/) to see if you can still reproduce it.

**Comment by MaxTru** [comment]
This was fixed (probably as @smbea pointed following https://github.com/camunda/camunda-modeler/issues/2581). Closing
