### ISSUE TITLE
Modeler is slow when importing diagrams with high nesting

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#2803]
__Describe the Bug__

When opening a large diagram with Camunda Modeler 5.0.0-alpha.1, importing and interaction is very slow

![Recording 2022-03-04 at 13 45 31](https://user-images.githubusercontent.com/21984219/156765939-f8ca7a6f-36b9-404d-a42c-3af9910532dc.gif)

Cf. https://jira.camunda.com/browse/SUPPORT-13125

__Steps to Reproduce__

1. Open the Diagram
2. Try to zoom in/out, drill down, ...
3. it is slow

__Expected Behavior__

A smooth modeling experience

__Environment__

- OS: -
- Camunda Modeler Version: 5.0.0-alpha.1
- Execution Platform: Camunda Platform

**Comment by marstamm** [comment]
# Problem Analysis

- Most of the import time is spent rendering
- The diagram is huge and creates >9k elements on the canvas.
- The Navigation is slow due to Matrix transformations on the viewport. All elements and layers are affected and have to be recalculated.

Original profile of load: 34s

![image](https://user-images.githubusercontent.com/21984219/156768420-8aa0777e-4f17-41d8-b5b7-539c8169b8a7.png)

# Possible solutions

## Usability after import

- The only reason navigation the diagram is slow at the moment is applying matrix transformation to the huge SVG. Most of the Contents are hidden, so rerendering would not be necessary.
- We can remove invisible layers from the DOM tree instead of just setting the visibility. This improves speed significantly.
> Note that this means that Canvas layers are not always represented in the DOM, searches not using internal API (e.g. using css selectors) might fail

![Recording 2022-03-04 at 13 58 24](https://user-images.githubusercontent.com/21984219/156767648-71c8f174-9e61-44e7-8296-9298c6205920.gif)

Proto in diagram-js: https://github.com/bpmn-io/diagram-js/commit/d45ea2e023ef99269c1c3af6ea0023af8f890abd
This also improved load times significantly as adding elements would not require DOM changes:
![image](https://user-images.githubusercontent.com/21984219/156768663-c8e16463-2071-4ce9-9328-5f192376ddbc.png)

## Import time

- to reduce loading time, we can consider removing rendering times during import.
- one approach is to only render contents on-demand when switching root elements.

> This requires significant changes in our Core rendering API to do it right.

Proto in diagram-js: https://github.com/bpmn-io/diagram-js/compare/improve-multi-root-performance
This improves load times further: 
![image](https://user-images.githubusercontent.com/21984219/156769996-6733a2e0-225b-404e-b1dc-e04960c3530a.png)

However, it increases time for switching root elements and hinders overall responsiveness:
![image](https://user-images.githubusercontent.com/21984219/156769679-5f5971a1-3043-48f6-bc17-f1325d62f2e8.png)

> The rendering in import is due to label layouting which is a limitation of the prototype. Both problems could be solved (e.g. prioritizing first layer to render and cache the rest in the background after basic interaction was achieved). However, this would be high effort and requires big changes to our core API

# Conclusion
If we decide to support diagrams of this size, we should prioritize modeling experience/responsiveness over initial load time. This is also much easier to achieve with the DOM optimizations detailed above and also help import time initially.

**Comment by marstamm** [comment]
Further thoughts on removing layers from DOM:

I think this can also be achieved with a plugin listening to `root.added` and `root.set` events. This way it does not have to be part of the diagram-js core

**Comment by marstamm** [comment]
We decided that this should be a root capability as every Tool would benefit from this improvement. We will not create a plugin for it

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2817
