### ISSUE TITLE
HTTPs with self signed certificate through ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by palex351** [camunda/camunda-modeler#2807]
__Describe the Bug__

In Camunda deployment with self signed certificate, modeler fails with: ERR_CERT_AUTHORITY_INVALID

__Steps to Reproduce__

1. Run Camunda in HTTPs with self signed certificate
2. Use modeler to upload diagram
3. And Modeler will fail to connect with server

__Expected Behavior__

Should be possible to have a way to accept self signed certificates or to upload the certificate into the modeler

__Environment__

## Camunda Modeler system information
 * Version: 4.12.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform

**Comment by palex351** [comment]
It seems related to #2404 . Anyway, it is possible to get around the issue by ignoring the certificate with parameter "--ignore-certificate-errors"

**Comment by ingorichtsmeier** [comment]
Hi @barmac, it could be useful if you develop processes in an environemnt with self signed certificates like Camunda Run production setup (https://docs.camunda.org/manual/7.16/user-guide/camunda-bpm-run/#choose-between-default-and-production-configuration). It enables SSL with this kind of certificate. 

Is "--ignore-certificate-errors" a command line parameter that I can apply at Modeler startup? (like --disable-plugins?)

**Comment by barmac** [comment]
Thanks @ingorichtsmeier for your insights.

> Is "--ignore-certificate-errors" a command line parameter that I can apply at Modeler startup? (like --disable-plugins?)

No, this is a flag which you can activate in your browser to allow untrusted certificates. Cf. https://superuser.com/questions/27268/how-do-i-disable-the-warning-chrome-gives-if-a-security-certificate-is-not-trust Note however that if we include such flag in the Modeler, you cannot tell whether the server is using the self-signed certificate or some other untrusted certificate.

**Comment by palex351** [comment]
"--ignore-certificate-errors" flag is not used by Modeler but it is passed into embedded browser "electron".

**Comment by ingorichtsmeier** [comment]
So, the Modeler could potentially use it, if it is set for electron via command line?

**Comment by barmac** [comment]
Potentially, but we'd need to implement this in the application. Still, I am rather sure that we would prefer a solution where you select the certificate to trust instead of ignoring all certificate errors at once.
