### ISSUE TITLE
Diagram deployment uses the same BrowserWindow of local nodejs Modeler application

### ISSUE THREAD

**Issue by palex351** [camunda/camunda-modeler#2811]
__Describe the Bug__

When uploading diagrams to a remote Camunda, it's used the same BrowserWindow of local nodejs application.
This will prevent the remote calls initiate cookies session due to cross-site policy.
The current implementation is systematically sending the same headers (Authorization) with every remote request. Even when the login has already been made at the time of the first request with a supposedly cookie session.

__Steps to Reproduce__

1. Run Camunda in application server with basic-auth and secure with 'Set-Cookie' Secure Flag
2. Run Camunda Modeler win DevTools and try to upload a diagram to the remote site.
3. DevTools will show that 'Set-Cookie' session will be blocked 

__Expected Behavior__

Remote Calls should be decoupled from the local nodejs execution so that cross-site policy can be avoided.

__Environment__

## Camunda Modeler system information
 * Version: 5.0.0-alpha.1
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform

**Comment by barmac** [comment]
Hi,

Thanks for opening the issue.

> The current implementation is systematically sending the same headers (Authorization) with every remote request. Even when the login has already been made at the time of the first request with a supposedly cookie session.

On my local Camunda instance, I don't see any session cookies being set when I deploy a diagram:

```
* Connected to localhost (::1) port 8080 (#0)
> POST /engine-rest/deployment/create HTTP/1.1
> Host: localhost:8080
> Accept-Encoding: deflate, gzip
> Connection: keep-alive
> accept: application/json
> authorization: Basic ZGVtbzpkZW1v
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 12_2_1) AppleWebKit/537.36 (KHTML, like Gecko) CamundaModeler/5.0.0-alpha.1 Chrome/89.0.4389.128 Electron/12.1.2 Safari/537.36
> Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryAnCAXrYw9gvLC9oE
> Sec-Fetch-Site: cross-site
> Sec-Fetch-Mode: cors
> Sec-Fetch-Dest: empty
> Accept-Language: en-US
> Content-Length: 8666
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Content-Length: 445
< Date: Tue, 22 Mar 2022 19:42:11 GMT
< Keep-Alive: timeout=60
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
```

This makes sense as we use the REST API to deploy the diagram which is per definition stateless. Please explain me if I get something wrong.

**Comment by palex351** [comment]
I'm using a production environment where the security level is more restricted where authentication can be mixed where it can be started with basic auth and later followed in cookie session based.
After some analysis, it appears that mix solution is not recommended due to some browsers may not support it.
You may close the issue.
