### ISSUE TITLE
Include plugin telemetry data into ping events

### ISSUE THREAD

**Issue by Skaiir** [camunda/camunda-modeler#2818]
__Is your feature request related to a problem? Please describe.__

Currently the only way we are able to gather information about plugin usage is by downloading data from the update server. This is different from our other sources 

__Describe the solution you'd like__

We would like instead to switch over this data to telemetry, most likely via the ping event

Documentation can be found here; https://docs.camunda.io/docs/components/modeler/desktop-modeler/telemetry/#ping-event

__Describe alternatives you've considered__

Keep relying on the update server data and fetch from it, but it is unreliable and generally we don't want to have tons of different sources for our data.

**Comment by smbea** [comment]
**Solution decided:**

Use existing "ping" event (`PingEventHandler`) to track plugin usage, by extending event structure:

```diff
  {
  "event": "ping",
+ "plugins": ['token-simulation', 'auto-save-plugin', ...]
  }
```

**Note:** since the plugin version is not available to the Modeler, we will use only the plugin names
