### ISSUE TITLE
Make improved modeling UI available in Modeler

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2820]
__What should we do?__

See [integrating library](https://github.com/bpmn-io/bpmn-js-connectors-extension).

- [ ] [C8 element template support](https://docs.camunda.io/docs/components/modeler/camunda-modeler/element-templates/camunda-modeler-element-templates/)
- [ ] Append elements from element templates during modeling
- [ ] Upgrade tasks to element templates from context pad
- [ ] Visually distinguish templated tasks from standard BPMN tasks
- [ ] Modern replace and append menu
- [ ] Support for documentation links and icons in element templates

__Why should we do it?__

Add feature parity with the web-modeler + general improvements to modeling with templates / modeling for execution.

**Comment by MaxTru** [comment]
Let's consider to have `Provide C8 built-in connectors with the desktop modeler` seperate.

Reason:

I belive to have this, we would need to do various things in advance.
* Have some `context` in DesktopModeler (e.g., via project context)
* In `context` store Camunda Cloud connection for a given diagram
* Set target cluster C8 SaaS or self-managed cluster for diagram `context`
* If target cluster is C8 SaaS 8.x, then retrieve templates (conntectors) and show them

**Comment by nikku** [comment]
Makes sense. Can you split up into two issues?

**Comment by MaxTru** [comment]
See https://github.com/camunda/camunda-modeler/issues/2840

**Comment by philippfromme** [comment]
@nikku We might want to close this issue.

**Comment by nikku** [comment]
Let's close. We have everything available with the next Modeler release.
