### ISSUE TITLE
Working with Templates: JavaScript error in user task when deactivating outputParameter

### ISSUE THREAD

**Issue by Xembalo** [camunda/camunda-modeler#2823]
__Describe the Bug__

When using a template for user tasks a predefined output Parameter disapears after disabling it for currend acitivity.

__Steps to Reproduce__

1. Create Template with content and save to file:
```
{
  "$schema": "https://unpkg.com/@camunda/element-templates-json-schema@0.4.0/resources/schema.json",
  "name": "User Task",
  "id": "aId",
  "description": "User Task with return variable",
  "appliesTo": [
    "bpmn:UserTask"
  ],
  "properties": [
    {
      "label": "Variable for return value:",
      "binding": {
        "type": "camunda:outputParameter",
        "source": "${returnValue}"
      }
    }
  ]
}
```
2. Create new bpmn file and add user task
3. Choose User Task Template
4. Deactivate "process variable assignment"
5. Whole section disappears and in "f12-console" is the following error
```
Helper.js:166 Uncaught TypeError: Cannot read property 'get' of undefined
    at e.exports.findOutputParameter (Helper.js:166)
    at Object.T (OutputParametersProps.js:114)
    at l.isOn (ToggleSwitchEntryFactory.js:88)
    at PropertiesPanel.js:782
    at _createBaseEach.js:24
    at e.exports (forEach.js:37)
    at U.updateShow (PropertiesPanel.js:776)
    at U.updateState (PropertiesPanel.js:759)
    at HTMLDivElement.n (PropertiesPanel.js:638)
    at HTMLDivElement.<anonymous> (index.esm.js:359)
e.exports.findOutputParameter @ Helper.js:166
T @ OutputParametersProps.js:114
l.isOn @ ToggleSwitchEntryFactory.js:88
(anonymous) @ PropertiesPanel.js:782
(anonymous) @ _createBaseEach.js:24
e.exports @ forEach.js:37
U.updateShow @ PropertiesPanel.js:776
U.updateState @ PropertiesPanel.js:759
n @ PropertiesPanel.js:638
(anonymous) @ index.esm.js:359
PropertiesPanel.js:838 Uncaught TypeError: Cannot read property 'oldValues' of undefined
    at U.applyChanges (PropertiesPanel.js:838)
    at HTMLDivElement.n (PropertiesPanel.js:637)
    at m (debounce.js:95)
    at E (debounce.js:144)
    at T (debounce.js:132)
```

__Expected Behavior__

I'm able to disable parameter or enable it again.

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.12.0
- Execution Platform: Camunda Platform
- Installed plug-ins: none

__Pictures__

Before:
![grafik](https://user-images.githubusercontent.com/21131605/159482042-0df85112-5a8e-4852-9088-7d3e1e512bf8.png)

After:
![grafik](https://user-images.githubusercontent.com/21131605/159482160-65b4e3fb-1ab0-44b1-8512-346d8ac4c770.png)

**Comment by pinussilvestrus** [comment]
I can reproduce this on version `v4.12.0`. However, I can't reproduce it in `v5.0.0-alpha.1`, so that will be fixed in the next stable release (April). Does this help you?

**Comment by Xembalo** [comment]
Ok,
