### ISSUE TITLE
Renaming C7/C8 – Welcome tab - Core Implementation

### ISSUE THREAD

**Issue by Skaiir** [camunda/camunda-modeler#2826]
__What should we do?__

We should implement the new welcome tab as per [this design issue](https://github.com/camunda/camunda-modeler-design/issues/71)

As part of this, the implementation should contain:

- [x] New column
- [x] Links to multiple pages
- [x] "New" badges
- [x] A new header which disappears when disabling either C7 or C8
- [x] Adjust tests

__Why should we do it?__

To improve visibility on C8 and hopefully drive adoption. 

Epic: https://github.com/bpmn-io/internal-docs/issues/490

**Comment by smbea** [comment]
The `bpmn-io-tasks` bot reopened this issue. Is there any reason for that 🤔?

**Comment by Skaiir** [comment]
Not that I can think of @smbea. Perhaps a miss-click or some solar particles at work here.
