### ISSUE TITLE
Renaming C7/C8 – Welcome tab - Replace Placeholder

### ISSUE THREAD

**Issue by Skaiir** [camunda/camunda-modeler#2827]
__What should we do?__

In the new column implemented in #2826, we should replace the placeholder and link to the blog post.

The post will accessible under 

https://camunda.com/blog/2022/04/camunda-platform-8-orchestrate-all-the-things?utm_source=modeler&utm_medium=referral

__Why should we do it?__

The placeholder only exists for the look of the main screen to be reviewable and look as close to the end product, for release it should be functional.

**Comment by christian-konrad** [comment]
The link is prepared; the post will be accessible at

https://camunda.com/blog/2022/04/camunda-platform-8-orchestrate-all-the-things?utm_source=modeler&utm_medium=referral

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2914
