### ISSUE TITLE
Platform 8 deploy dialog has `self-managed` as default

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2832]
__Describe the Bug__

Platform 8 deploy dialog has `self-managed` option as default

__Steps to Reproduce__

1. Have a new Camunda Modeler instance without a configuration
2. Create Platform 8 BPMN
3. Click deploy
4. now this happens
![Screenshot_20220323_202348](https://user-images.githubusercontent.com/42800119/159779828-958efa7b-ecb2-4fcb-8656-7b73fb0c9d9c.png)

__Expected Behavior__

The default / pre-selected option is `SaaS`

Reason: 
* Easier to use
* Should be promoted over self managed?

__Environment__

Camunda Modeler nightly as of 22.03.2022

**Comment by MaxTru** [comment]
Needs @christian-konrad 's assessment

**Comment by andreasgeier** [comment]
In case we change to SaaS as default, we should also switch the order of the radios and put SaaS as first item.

**Comment by christian-konrad** [comment]
Let's do this accordingly to SaaS promotion. I moved it into ready.
