### ISSUE TITLE
Provide C8 built-in connectors with the desktop modeler

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2840]
__What should we do?__

Retrieve and show C8 SaaS present Connectors (technically via element templates) and offer for modeling.

Probably in order to do this, we need to:
- [ ] Have some `context` in DesktopModeler (e.g., via project context)
- [ ] In `context` store Camunda Cloud connection for a given diagram
- [ ] Set target cluster C8 SaaS or self-managed cluster for diagram `context`
- [ ] If target cluster is C8 SaaS 8.x, then retrieve templates (conntectors) and show them

Precondition:
- [x] https://github.com/camunda/camunda-modeler/issues/2820

Dependency:
- [ ] Web Modeler to offer API for us to retrieve available connector element templates for given cluster (@CatalinaMoisuc )

__Why should we do it?__

To offer C8 SaaS Connectors in Desktop Modeler

**Comment by emailtowalter** [comment]
Is there a plan when the connector will be avail in desktop modeler? I also found the connector that published to the on-prem camunda engine ( stood up using docker compose) does not run. It just stay there. When the desktop modeler starts to support the connector, I assume the on-prem engine will just work? 

Thanks

**Comment by nikku** [comment]
@emailtowalter Connectors will only work out of the box when using Camunda SaaS.

At some point though you'll be able to spin up the connector run-times on C8 self-managed yourself (to accomplish the same thing).

**Comment by philippfromme** [comment]
Closed by https://github.com/camunda/camunda-modeler/pull/4409.
