### ISSUE TITLE
Improve paste from menu (element positioning)

### ISSUE THREAD

**Issue by gimbel** [camunda/camunda-modeler#285]
**Problem**
- content is pasted outside the view

![screencast1](https://cloud.githubusercontent.com/assets/3829733/15352570/1963b048-1ce5-11e6-9ba8-8e57738d32eb.gif)

**Solution**

Would be nicer if elements were always placed at the same position, in case paste is used via menu

Hint: Not critical, since I think not many people are using it that way

**Comment by nikku** [comment]
Superseded by https://github.com/camunda/camunda-modeler/issues/1421.
