### ISSUE TITLE
Improve UX of "Remember credentials" toggle in deployment

### ISSUE THREAD

**Issue by smbea** [camunda/camunda-modeler#2860]
__What should we do?__

Improve the UX of "Remember credentials" toggle in the deployment overlay for Cloud.

- [ ] Make 'Remember credentials' toggle always available (currently not available for self-managed target with no OATH)
- [ ] Save credentials onClose, regardless if the deployment succeed 

__Why should we do it?__

This is part of a bigger effort to improve the UX of the deployment journey (see #2707)

----

Child of #2707

**Comment by smbea** [comment]
I decided to save credentials only on close since they are only reset (to the saved ones)when opening the overlay again

**Comment by andreasgeier** [comment]
> I decided to save credentials only on close since they are only reset (to the saved ones)when opening the overlay again

If one adds/changes the credentials (toggle was already activated or has been activated) and then deploys, are the new credentials stored?

**Comment by smbea** [comment]
* If deploy successful -> it will always save
* If deploy connection cannot be established (wrong credentials or so) -> validation kicks-in so the deploy doesn't proceed and the overlay doesn't close. But if you close it later it saves.

I hope this makes sense, but I will add you as a reviewer for this PR and you can test the artifact.
