### ISSUE TITLE
Improve connection error messages in deployment overlay

### ISSUE THREAD

**Issue by smbea** [camunda/camunda-modeler#2862]
__What should we do?__

Extract general error message to not belong to a single field - currently, it is always applied to 'Cluster URL' field, regardless of which field is incorrect:

<img width="300" alt="Screenshot 2022-03-29 at 17 53 02" src="https://user-images.githubusercontent.com/25825387/160653400-c40ebe52-1490-4d84-8fbb-cdeffeee7a19.png">

Steps to reproduce:
1. Enter correct Cluster URL, Client secret, and wrong Client ID
2. See that error message is applied to Cluster URL field

__Why should we do it?__

This is part of a bigger effort to improve the UX of the deployment journey (see https://github.com/camunda/camunda-modeler/issues/2707)

----

Child of #2707

**Comment by smbea** [comment]
Sketch of extracting the error message:

<img width="297" alt="Screenshot 2022-03-29 at 17 50 18" src="https://user-images.githubusercontent.com/25825387/160652878-dd219e35-5517-4996-97a9-ababc5520af6.png">

**Comment by andreasgeier** [comment]
In my opinion, this is a question of the desired security level.

A: 
This is access to Saas data, so we do not communicate specific security information.
Conclusion: general summary message like `Credentials are not accepted`, not providing which field value is wrong

B:
We want to support the Modeler user as much as possible and treat her as a trusted user.
Conclusion: specific error messages per input like `Cluster URL not valid`, `Client ID not found`, `Client secret not accepted`

@christian-konrad pls provide input.

**Comment by smbea** [comment]
I believe we don't have the specific error. We just have a general "cluster unavailable" message, for this case.

These are the possible error outcomes:

```js
const errorReasons = {
   UNKNOWN: 'UNKNOWN',
  CONTACT_POINT_UNAVAILABLE: 'CONTACT_POINT_UNAVAILABLE',
  CLUSTER_UNAVAILABLE: 'CLUSTER_UNAVAILABLE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  OAUTH_URL: 'OAUTH_URL',
  UNSUPPORTED_ENGINE: 'UNSUPPORTED_ENGINE'
};

```

**Comment by andreasgeier** [comment]
If only option A is possible, the suggested position of the message below the form fields and above the submit button makes sense.

However, I would suggest to improve the message to mention both cases of possible failure:
`Credentials are not accepted or Zeebe cluster is not running.`

**Comment by smbea** [comment]
Straight out of the code:

```js
export const CONNECTION_ERROR_MESSAGES = {
  [ ERROR_REASONS.CONTACT_POINT_UNAVAILABLE ]: 'Should point to a running Zeebe cluster.',
  [ ERROR_REASONS.CLUSTER_UNAVAILABLE ]: 'Should point to a running Zeebe cluster.',
  [ ERROR_REASONS.UNAUTHORIZED ]: 'Credentials do not match with the server.',
  [ ERROR_REASONS.FORBIDDEN ]: 'This user is not permitted to deploy. Please use different credentials or get this user enabled to deploy.',
  [ ERROR_REASONS.OAUTH_URL ]: 'Should point to a running OAuth service.',
  [ ERROR_REASONS.UNKNOWN ]: 'Unknown error. Please check Zeebe cluster status.',
  [ ERROR_REASONS.UNSUPPORTED_ENGINE ]: 'Unsupported Zeebe version.'
};
```

**Comment by christian-konrad** [comment]
Is the "CLUSTER_UNAVAILABLE" one thrown after credentials have been validated? If so, we could be more precise here (but I con't know exactly HOW contact point and cluster unavailability are distinguished at all)
Otherwhise, this looks good and we can move on!

**Comment by smbea** [comment]
`CONTACT_POINT_UNAVAILABLE` and `CLUSTER_UNAVAILABLE` are roughly the same, but one is for the "contact point" for self-managed and the other is for "cluster URL" for SaaS. The connection is always validated with the credentials, so it's not possible to separate these further, I believe

**Comment by smbea** [comment]
It appears it isn't as simple as we thought. After some investigation on these messages, when and where they appear, here is what I discovered:

* **Wrong Client ID**:  Regardless of the rest of the credentials, this returns a `CLUSTER_UNAVAILABLE` error.
Which leads me to believe, the rest of the credentials are compared against this one.

<img width="301" alt="Screenshot 2022-03-31 at 14 43 32" src="https://user-images.githubusercontent.com/25825387/161057420-d637ab59-1ceb-419d-bb46-0cdba27f3005.png">


* **Wrong Cluster URL and correct Client ID**: only shows error after clicking deploy.
This is because we check the connection with Cluster ID, which is deduced from the Cluster URL **ONLY** right before submitting - see [here](https://github.com/camunda/camunda-modeler/blob/5bb898c4645a59073930593b2197922454c9dbea/client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js#L169). Meaning, (if changing from correct url to wrong url) it checks the connection with the stored correct value. And it returns a `UNKNOWN` error.

<img width="302" alt="Screenshot 2022-03-31 at 14 44 14" src="https://user-images.githubusercontent.com/25825387/161057539-82480211-eb85-4c0b-8aa5-87cdd8fde9b1.png">

* **Wrong Secret**:  Returns a `UNAUTHORIZED` error.
<img width="300" alt="Screenshot 2022-03-31 at 14 47 38" src="https://user-images.githubusercontent.com/25825387/161058112-7710c1ff-41dc-48d6-af7a-bbdf63d53afd.png">

So my conclusion here is that this issue should be used to clear up these messages, since I believe it's very confusing. And deduce the Cluster ID from the URL on input, in order to display the proper message. 

@christian-konrad @andreasgeier @MaxTru

**Comment by MaxTru** [comment]
> * mpared against this one.

Thanks for the analysis. I agree that we should clear up the messages to reflect the actual error.

Could you please sketch a proposal for this? I liked the style of the comment where you tried out the situations and then showed how the UI reacts.

**Comment by smbea** [comment]
Although we don't validate each field on its own, by testing and experimenting, I was able to figure out which messages are related to which fields. And that the other fields are only valid if the Client ID is valid. Based on what I commented above, I propose we change the messages (starting [here](https://github.com/camunda/camunda-modeler/blob/f46e7d1133542476aa1f7dea197a0845dcd8880b/app/lib/zeebe-api.js#L323)) to:

* `CONTACT_POINT_UNAVAILABLE: 'Should point to a running Zeebe cluster.'` **becomes** `INVALID_CLIENT_ID: ‘Please provide a valid Client ID.’`
     * highlight client ID field
     
* `UNAUTHORIZED: 'Credentials do not match with the server.'` **becomes** `INVALID_CREDENTIALS: 'Client secret does not match the  Client ID provided.'`
     * highlight client secret field (this field is compared against the client ID)

* `UNKNOWN: 'Unknown error. Please check Zeebe cluster status.'` **becomes**  `CONTACT_POINT_UNAVAILABLE: 'Should point to a running Zeebe cluster.'`
     * highlight contact point

As for when zeebe is down we should have the `UNKNOWN` error. We have #2876 to handle this use case

**Comment by christian-konrad** [comment]
Thanks Bea for investigating this further! Looking forward to seeing your proposal in action.
