### ISSUE TITLE
Adjust deployment field labels, hints and validation

### ISSUE THREAD

**Issue by smbea** [camunda/camunda-modeler#2863]
__What should we do?__

*  audience
    * [x] find out if it's always cluster URL minus port (ask Zeebe team)
       *  if so then we can omit field;  if not give field description/hint
* contact point
  * remove default text, add placeholder
  * change label to "Cluster endpoint"
  * add validation for valid url/ip address with port

__Why should we do it?__

This is part of a bigger effort to improve the UX of the deployment journey (see https://github.com/camunda/camunda-modeler/issues/2707)

----
Child of https://github.com/camunda/camunda-modeler/issues/2707

**Comment by smbea** [comment]
After reaching out to the zeebee team, I have learned that although the recommendation for `audience` is to be the base address of the resource being accessed (url minus the port), we cannot guarantee users will follow this in self-managed instances. Therefore -> **we will maintain the `audience` field, but let's consider what description or placeholder could be added**. (cc @christian-konrad )

**Comment by christian-konrad** [comment]
Thanks for investigating!

Is there any documentation on OAuth in Self-Managed Camunda 8?
Or should we expect Self-Managed Users that implemented their OAuth to understand what to do in the Modeler Client? Is it the responsibility of the one installing Self-Managed to teach their users on it?

We could maybe print in the validation string “Please enter the audience your token issuer provided to you” or similar, but I am a total OAuth newbie and not sure what’s right here

**Comment by smbea** [comment]
After discussing and consulting the zeebe teamm, we decided to add a description that points to it usually being the base address of the cluster (aka without the port)
