### ISSUE TITLE
Message End events as external tasks didn't work in the engine

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#2865]
__Describe the Bug__

Camunda Platform cannot work with message end events implemented as external tasks.

The modeler writes XML like:
```
    <bpmn:endEvent id="Event_1xh41u2" name="Payment completed" camunda:topic="paymentCompletion">
      <bpmn:incoming>Flow_0277qmu</bpmn:incoming>
      <bpmn:messageEventDefinition id="MessageEventDefinition_0cl2fmn" camunda:type="external" camunda:topic="" />
    </bpmn:endEvent>
```

It should look like here: https://docs.camunda.org/manual/7.16/reference/bpmn20/events/message-events/#message-end-event

```
      <bpmn:messageEventDefinition id="MessageEventDefinition_0cl2fmn" camunda:type="external" camunda:topic="paymentCompletion" />
```

__Steps to Reproduce__

1. create an new message end event. 
2. select the implementation External
3. Add a topic name paymentCompletion
4. deploy it to Camunda Platform Run
5. Implement an external task worker for this topic.
6. The task will never be picked up by the worker (as the topic is empty in the XML)

__Expected Behavior__

The task will be picked up by the worker. (the topic is filled at the messageEventDefinition)

__Environment__

Camunda Modeler system information
 * Version: 5.0.0-alpha.1
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform

__Additional comment__
I'm working on the new training for Camunda Platform, where this is part of an exercise. It would be nice if you can fix this with higher priority to get it in the 5.0.0 release. Thank you!

**Comment by ingorichtsmeier** [comment]
It's the same for a message intermediate throw event.

**Comment by pinussilvestrus** [comment]
Thanks for reporting! This is a bug in the properties panel, as we always [set the topic to the element](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/provider/camunda-platform/properties/ImplementationProps.js#L247). For message event, it has to be set in the definition.


> <bpmn:endEvent id="Event_1xh41u2" name="Payment completed" camunda:topic="paymentCompletion"> ... </bpmn:endEvent>

**Comment by pinussilvestrus** [comment]
We have to make sure that we always use `getServiceTaskLikeBusinessObject` for these props to be element agnostic.

**Comment by pinussilvestrus** [comment]
This was upstream fixed via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/634

Will be closed once we integrate the latest properties panel version (which will happen during release preparation).
