### ISSUE TITLE
Conditional event configuration miss camunda:variableName and camunda:variableEvents

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#2866]
__Describe the Bug__

For a conditional event, I can add configuration for `camunda:variableName` and `camunda:variableEvents`.

These settings are missing in the property panel: 
![grafik](https://user-images.githubusercontent.com/7870843/160556127-cd5da86e-87d4-4e62-b3ca-54935819f395.png)

The elements are documented here: https://docs.camunda.org/manual/7.16/reference/bpmn20/events/conditional-events/#condition 

__Steps to Reproduce__

1. Open a process model with a conditional event
2. Try to enter a variable name and variable events for this BPMN event.

__Expected Behavior__

I can add a the configurations in the property panel.

__Environment__

Camunda Modeler system information
 * Version: 5.0.0-alpha.1
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform

**Comment by MaxTru** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/651
