### ISSUE TITLE
Reopen last tab when there is no last tab shows console error

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2873]
__Describe the Bug__

Reopen last tab when there is no last tab shows console error

__Steps to Reproduce__

1. Have no last tab
2. Click "open last tab
3. now this happens =>
![Screenshot_20220330_172822](https://user-images.githubusercontent.com/42800119/160872656-1b43a65b-5c01-4fce-9a81-acea08ea7305.png)

__Expected Behavior__

Some nice indication that there is no last tab

__Environment__

Camunda Modeler 4.12.0

**Comment by pinussilvestrus** [comment]
Seems like that this bug came back after some time: https://github.com/camunda/camunda-modeler/issues/1173

**Comment by Skaiir** [comment]
This may not be a regression but rather a case we've not entirely considered with the disabling of this menu entry.
