### ISSUE TITLE
Change text from Camunda Cloud 8.0 to Camunda Platform 8.0 in forms error message

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#2880]
__Describe the Bug__

As a user when we select the Camunda 8.0 platform version for deploying forms we could still see "Camunda Cloud 8.0" in the error  message and it needs to changed to "Camunda Platform 8.0".

__Steps to Reproduce__

1. Create/Open forms 
2. Select version 8.0 for deploying the forms.
3. If there would be any linting errors we could still see "camunda cloud 8.0" in the error message.

__Expected Behavior__

Change the test from "Camunda cloud 8.0" to "camunda Platform 8.0"

__Environment__

- OS: [ Windows 10]
- Camunda Modeler Version: [5.0.0 Nightly ]
- Execution Platform:[, Camunda Cloud]

![form_error_change](https://user-images.githubusercontent.com/85225325/161264690-5e9144d4-310c-4bb3-b8f9-a27a9b23d8a8.JPG)

**Comment by MaxTru** [comment]
Ups: this is valid, but also, there should not even be an error in this case in the first place. I will create a seperate issue

**Comment by MaxTru** [comment]
Assigning to @philippfromme who is our linting master at the moment
