### ISSUE TITLE
The license book displays old version

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2896]
__Describe the Bug__

When the license book diff is sent, it contains old version, e.g. `Camunda Modeler v5.0.0-alpha.1 Third Party Summary` for Camunda Modeler 5.0.0.

__Steps to Reproduce__

Reproduced with each release.

__Expected Behavior__

It should contain the release for which the summary is generated.

__Environment__

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2969.
