### ISSUE TITLE
Replace old Operate process instances route URLs

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda-modeler#2902]
__What should we do?__

With the release of Camunda Platform 8 Operate replaced the routes `/instances` with `/processes` because now we have the two kinds of instances, processes, and decisions.
The Camunda Modeler should reflect these changes by changing the old routes [[1]](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js#L358=)[[2]](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js#L615=)
[Operate routes for reference](https://github.com/camunda-cloud/operate/blob/master/client/src/modules/routes.tsx#L27-L32=)

__Why should we do it?__

Because the old routes don't exist anymore (but we're redirecting the old routes to the new ones)

**Comment by smbea** [comment]
@vsgoulart Is this change live already?

**Comment by vsgoulart** [comment]
> @vsgoulart Is this change live already?

Yes, from our side it is. But we're redirecting old `/instances` routes to `/processes`

**Comment by nikku** [comment]
Let us please consider what switching to new URLs means for backwards compatibility with recent (but old) Camunda Cloud / operate versions.

Sticking to old URLs _for the moment_, for old clusters is a safe choice.

**Comment by smbea** [comment]
I tested changing this with an outdated cluster, and if we do change to `/processes`, then it leads nowhere. So should we maybe keep it as is? That is, the old url and re-direct it.

**Comment by vsgoulart** [comment]
@nikku That's true, but I guess it all depends on how many old clusters we still have.

I'll talk with Felix and ask if he has this data and what is his opinion this.

**Comment by vsgoulart** [comment]
> I tested changing this with an outdated cluster, and if we do change to `/processes`, then it leads nowhere. So should we consider keeping it as is? That is, the old url and re-direct it.

I'm talking with Felix, I'll post his feedback when he answers me so you can decide

**Comment by smbea** [comment]
@vsgoulart Do you have any update on this?

**Comment by vsgoulart** [comment]
Hi @smbea, sorry for the delay.
Felix was on vacation and I forgot to check this topic again so I asked Menski and Aleksander Dytko yesterday.
Their opinion is that it's ok to only have the redirect from Operate's side for now but they're still not sure when we should update the modeler.

I'll setup a reminder for before the next cloud release in 6 months and check if we can update the modeler by then.

I think for now we can close this issue. I'll reopen it when we decide it's a good moment for the update.

**Comment by vsgoulart** [comment]
Sorry for the unnecessary work from your side :grimacing:
