### ISSUE TITLE
When will a web version of the designer come out?

### ISSUE THREAD

**Issue by lanxingfu** [camunda/camunda-modeler#2906]
__Is your feature request related to a problem? Please describe.__

When will a web version of the designer come out?

__Describe the solution you'd like__

__Describe alternatives you've considered__

__Additional context__

Add any other context or screenshots about the feature request here. For example, provide the execution platform you're operating on (Camunda Platform, Camunda Cloud, ...).

**Comment by nikku** [comment]
You can give [camunda cloud](https://camunda.io) a try, it is the web version of our tool.
