### ISSUE TITLE
Scrolling variable type in Literal expression of DMN is not possible.

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#2908]
__Describe the Bug__

When we try to scroll down the variable type in the Literal expression it is not possible.

__Steps to Reproduce__

1. Create a new DMN.
2. Change the decision type to Literal expression.
3. When we try to choose the variable type it is not scrollable anymore and looks like it is cut-off from the window.

__Expected Behavior__

Make the variable type in Literal expression scrollable.

__Environment__

- OS: [ Windows 10]
- Camunda Modeler Version: [ 5.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]

<img width="956" alt="19a0d421185ebf45dd40fa9ccc514f27" src="https://user-images.githubusercontent.com/85225325/162422675-07443755-fb09-43cd-929b-b9e2cca20008.png">

**Comment by barmac** [comment]
The same happens in a really small window in the decision table view:
![image](https://user-images.githubusercontent.com/28307541/162465582-b5226744-0f62-424d-a7d4-20060fd6b8cf.png)

**Comment by barmac** [comment]
https://user-images.githubusercontent.com/28307541/162475630-fa831eac-0992-49a8-b0b2-c0964937624b.mov

I've got a working prototype of a fix.

**Comment by barmac** [comment]
I will provide a fix via https://github.com/bpmn-io/dmn-js/pull/695
