### ISSUE TITLE
form textfield: 'regularExpressionPattern' should be 'pattern'

### ISSUE THREAD

**Issue by rondie** [camunda/camunda-modeler#2919]
__Describe the Bug__

 'regularExpressionPattern' should be 'pattern' in form JSON, others descibe the same in https://forum.camunda.io/t/regular-expression-pattern-not-working/30215

__Steps to Reproduce__

Adding a 'Regular Expression Pattern' validation to a text field in a form will show up as 'regularExpressionPattern' in the resulting JSON data

__Expected Behavior__

'regularExpressionPattern' does not work, 'pattern' does, as per form schema (https://github.com/bpmn-io/form-js/blob/master/docs/FORM_SCHEMA.md?plain=1#L32)
changing it manually in the JSON data makes it work after deployment

__Environment__

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 4.11, 5.0.0
- Execution Platform: camunda platform 7.16.0
- Installed plug-ins: none

**Comment by MaxTru** [comment]
I can reproduce. Moving to ready

**Comment by MaxTru** [comment]
Fixed upstream via https://github.com/bpmn-io/form-js/pull/245

**Comment by Skaiir** [comment]
Closed via 15aed67091ddde9443726d53d927d4a26494f28f
