### ISSUE TITLE
Element template name and icon are not displayed in property panel header if template is versioned

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-modeler#2920]
__Describe the Bug__

The element template name and icon are not displayed in the property panel header if the template is versioned (has a version attribute).

__Steps to Reproduce__

1. Assign a template without a version attribute to a task of a C7 model
2. ▶️ The icon and title are shown
3. Add a version attribute to the template
4. Refresh the modeler
5. ▶️ The icon and title aren't displayed anymore

See screencast for reference:

https://user-images.githubusercontent.com/56470362/163670856-0cf5e999-2e76-4d42-9865-fa4a7c93795f.mov

__Expected Behavior__

The icon and name should be visible no matter if the template is versioned or not.

__Environment__

- Camunda Modeler Version: 5.0.0
- Execution Platform: C7.17
- Installed plug-ins: None

**Comment by pinussilvestrus** [comment]
Icons are not implemented yet for Camunda Platform 7, that's probably why it doesn't properly work. However, the name should be displayed indeed.

**Comment by pinussilvestrus** [comment]
I can reproduce it and move it to ready, as it is a bug in a recently added feature.

Something is broken in the [header provider](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/render/PanelHeaderProvider.js) for versioned templates.

**Comment by pinussilvestrus** [comment]
This will be fixed upstream via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/670

**Comment by Skaiir** [comment]
Closed via e77fc5da94aeb224de1f813b4c936558385be96f
