### ISSUE TITLE
Highlight in XML opage didn't match the text

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#2923]
__Describe the Bug__

When I try to highlight some text in the XML view of a process model, on some lanes the highlight didn't match the text.

__Steps to Reproduce__

1. model some elements
2. switch to the XML view
3. mark a line in the text with the mouse

__Expected Behavior__

The text is exactly marked.

But it isn't, as you can see in the screenshot:
![grafik](https://user-images.githubusercontent.com/7870843/164236897-437ea971-0741-4857-8658-ff1eae8d2a23.png)

It seems to depend on the line you want to mark with the mouse. On some lines it matches the text, on some it doesn't match.

__Environment__

Camunda Modeler system information
 * Version: 5.0.0
 * Operating System: Windows 10 amd64
 * Plugins: Cloud Connect, Migration, bpmn-js Token Simulation, BPMN Linter, Transaction Boundaries, Camunda Property Infos, Tooltip Plugin
 * Execution Platform: BPMN - Camunda Platform 7

**Comment by marstamm** [comment]
I can reproduce the issue. Some more details from my side:

- I can only achieve it on a fresh start of the modeler, when first opening the XML view
- When closing and opening it again, it is resolved
- Typing anything into the xml also fixes it

![Recording 2022-04-22 at 09 11 37](https://user-images.githubusercontent.com/21984219/164625447-4e2689bc-f15d-4bd2-9a7f-ae154498c24d.gif)

**Tested on environment**
 * Version: 5.0.0
 * Operating System: Linux x86_64 amd64
 * Plugins: none
 * Execution Platform: BPMN - Camunda Cloud
