### ISSUE TITLE
Discussion: Should i/o variable alphabetical sorting behavior be kept? 

### ISSUE THREAD

**Issue by Skaiir** [camunda/camunda-modeler#2932]
__Context of feature discussion:__

Follow a [community post](https://forum.camunda.io/t/disable-auto-sorting-of-output-variables-in-camunda-modeler-5-0/37034), i/o variable sorting in the properties panel has come back to being controversial. This was also subject of discussion back when it was first implemented and as a fail-safe, a configuration option was already provided in the code, which makes actual toggling of this behavior rather easy.

However this topic cannot be progressed currently as there is no clear consensus on what the right way to do this is.

Options currently are:

- keep as-is (no effort)
- de-activate the behavior if we somehow figure out this is an overwhelming preference of our users (very low effort)
- introduce configuration options for this (medium effort)

This issue serves as a feedback aggregation platform and may be converted into a feature request if we decide to take action on it.

__Feedback gathered:__

- the referenced post: https://forum.camunda.io/t/disable-auto-sorting-of-output-variables-in-camunda-modeler-5-0/37034
- [internal discussion thread](https://camunda.slack.com/archives/GP70M0J6M/p1650460457216909) summary of points
	- variable ordering from some developer's perspective feels more intuitive semantic than alphabetical
	- however in large sets of inputs and outputs, alphabetical is the only version which really scales
	- we lack data on what the general user preference is for this
	- manual / custom sort should be considered as a potential enhancement rather than a default, this is further supported by Ingo in this thread

**Comment by ingorichtsmeier** [comment]
My two cents on this topic:

Variables are the heart of of process automation as they transport information from one task to the following.

If you have only a few of them, it's easy for everybody to get an overview.

But alphabetical ordering is only one aspect to get an overview in a large amount of names. Sometimes it's more suitable to sort historically. Sometimes you sort by an appendix. Sometimes you have to agree as team on the ordering.

The best way is to allow manual ordering afterwards (which is not possible in the moment).

**Comment by nikku** [comment]
Closing this issue. 

The fact that we had alphabetic ordering in the first place was a misstake. 

C8 already sorts in insertion order, C7 may follow some day (cf. https://github.com/camunda/camunda-modeler/issues/3978).
