### ISSUE TITLE
Support binding `retries` on `zeebe:taskDefinition` through element template

### ISSUE THREAD

**Issue by B-hamza** [camunda/camunda-modeler#2936]
_This is a child of https://github.com/camunda/product-hub/issues/1382._

__Is your feature request related to a problem? Please describe.__

When trying to create services tasks templates we only can bind the type via `zeebe:taskDefinition:type` but we can't bind retries elements.

__Describe the solution you'd like__

Add new binding: `zeebe:taskDefinition` which accepts `property` as the name of the templated property. This can be `type` or `retries` but ready for new properties.

* [x] Implement in JSON schema
* [x] Implement in bpmn-js-element-templates
* [x] Remove obsolete `zeebe:taskDefinition:retries` from JSON schema as never implemented
* [ ] [Document new property](https://github.com/camunda/camunda-docs/pull/2864)

__Describe alternatives you've considered__

We unlink after selecting templates to be able to set retries.

----

Also mentioned via [slack](https://camunda.slack.com/archives/CKGH9LR40/p1677510188850949).

**Comment by nikku** [comment]
Thanks for reporting. Missing feature, moving to backlog for the time being.

**Comment by ajeans** [comment]
Hello @nikku 

That is a blocker for us to adopt element templates, can you provide a code pointer to implement that?

**Comment by nikku** [comment]
@ajeans Could you elaborate how this is a blocker for you? 

For additional context the engine [uses default retries of `3`](https://docs.camunda.io/docs/components/modeler/bpmn/service-tasks/#task-definition).

**Comment by ajeans** [comment]
@nikku oh right, if it is not configurable but falls back to the default value of 3, then this is not a blocker. 

You are absolutely right.

I would still be interested in providing support for it, as we might want to add more retries for some tasks.

**Comment by nikku** [comment]
@ajeans Given that you started implementing this via https://github.com/camunda/element-templates-json-schema/pull/90, do you plan to follow up with the behavior part in [our properties panel](https://github.com/bpmn-io/bpmn-js-properties-panel). Again implementation is likely a 1:1 copy of `zeebe:taskDefinition:type`.

**Comment by ajeans** [comment]
@nikku thanks for the quick feedback

Yes I plan to look into this this week.

**Comment by nikku** [comment]
Stalled draft PR that we can use to resurrect the properties panel parts: https://github.com/bpmn-io/bpmn-js-properties-panel/pull/880.

**Comment by nikku** [comment]
Moving to `ready` as this is desired in connectors, too.

**Comment by barmac** [comment]
I've sketched a solution together with @philippfromme, and added task list to the first comment in the issue.

**Comment by sbuettner** [comment]
@barmac will this be part of 8.4-alpha1?

**Comment by barmac** [comment]
It's pretty close to be released. When https://github.com/bpmn-io/bpmn-js-element-templates/pull/29 gets merged, I will release the templates. If we manage to do that today, support for `zeebe:taskDefinition` binding will be available in the upcoming Desktop Modeler release.

**Comment by barmac** [comment]
This is now `fixed upstream` via `bpmn-js-element-templates@1.7.0` release.

**Comment by chillleader** [comment]
@barmac I tried to use the new binding today with 5.17.0 but it doesn't work, I get a warning:
```
template(id: <io.camunda.connectors.HttpJson.v2>, name: <REST Outbound Connector>): invalid property.binding type "zeebe:taskDefinition:retries"; must be any of { property, zeebe:taskDefinition:type, zeebe:input, zeebe:output, zeebe:property, zeebe:taskHeader, bpmn:Message#property, bpmn:Message#zeebe:subscription#property } [ warning ]
```

and the template is unavailable. Was this already released?
