### ISSUE TITLE
recovery my BPMN Diagram

### ISSUE THREAD

**Issue by Larky92** [camunda/camunda-modeler#2937]
_hello,

Please somebody help me to recover all my work in this file. the file has a set of diagrams but on BPMN, not all of them are displayed because I couldn't make the save after
[fichier error.zip](https://github.com/camunda/camunda-modeler/files/8599543/fichier.error.zip)
[fichier en Erreur.bpmn.txt](https://github.com/camunda/camunda-modeler/files/8599536/fichier.en.Erreur.bpmn.txt)
[fichier en Erreur.bpmn.txt](https://github.com/camunda/camunda-modeler/files/8599535/fichier.en.Erreur.bpmn.txt)

**Comment by nikku** [comment]
Please use our existing issue template (bug report in your case) to provide all relevant details.

What did you do in which sequence? What did not work? Did you try to copy + paste?

Do you have a working diagram version?

**Comment by nikku** [comment]
Hope you were able to recover your file. We'll not be able to help you without further details.
