### ISSUE TITLE
Cant deploy diagram using camunda modeler 5.0 when ldap authentication is enabled

### ISSUE THREAD

**Issue by RedOne-Guerad** [camunda/camunda-modeler#2944]
I am using camunda run 7.17 with ldap authentication, I can connect to the web application, but when I try to deploy a diagram using modeler 5.0, i get an error must point to a running camunda platform  REST API , however when i disable ldap authentication on camunda run 7 the deployment success.

Using Postman with LDAP enabled on camunda run 7 the deployment success .
The issue only occurs when using Modeler 5.0.

**Comment by nikku** [comment]
Please use our existing issue templates.

Please provide additional information / screenshots (with secrets redacted) so this becomes actionable for us.

**Comment by pinussilvestrus** [comment]
I'm closing this now as we don't have the necessary details to work on it. Feel free to re-open using our issue templates.
