### ISSUE TITLE
Missing elements Data Store /  Data Object

### ISSUE THREAD

**Issue by michel777777** [camunda/camunda-modeler#2954]
__Describe the Bug__

Missing elements Data Store /  Data Object

__Steps to Reproduce__

I open a new diagram 

__Expected Behavior__

Elements Data Store /  Data Object are visible.

__Environment__

## Camunda Modeler system information
 * Version: 5.0.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform 8
 * 
![missing_elements](https://user-images.githubusercontent.com/86347050/167797047-0bd295f0-d99d-48c8-a2b1-f78a59682a9e.png)

**Comment by barmac** [comment]
Data storage and data item elements are not supported yet in Camunda Platform 8. Check out [the BPMN Coverage page](https://docs.camunda.io/docs/components/modeler/bpmn/bpmn-coverage/#data) for supported elements.
