### ISSUE TITLE
Creating file from empty bpmn creates C7 diagram

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2957]
__Describe the Bug__

Creating file from empty bpmn creates C7 diagram

__Steps to Reproduce__

1. Have an empty file
2. Name the file empty.bpmn
3. Open file
4. Now this happens:
![image](https://user-images.githubusercontent.com/42800119/168104918-ccf25ee2-4409-462c-9723-f1b714ae888d.png)
==> C7 diagram is created

__Expected Behavior__

==> C8 diagram is created

__Environment__

Camunda Modeler 5.0.0

**Comment by smbea** [comment]
Can reproduce, moving to backlog.

**Comment by barmac** [comment]
Bot forgot to add `needs review` label 🤡

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/3243
