### ISSUE TITLE
Add resize handler for bottom panel

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2959]
__What should we do?__

Design issue: https://github.com/camunda/camunda-modeler-design/issues/105

* [ ] make [properties panel](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/PropertiesContainer.js) resize handler a reusable component
* [ ] add resize handler to the bottom panel

__Why should we do it?__

We defined the resize handler as a general concern and shall use it where applicable.

Depends on https://github.com/camunda/camunda-modeler-design/issues/90

**Comment by smbea** [comment]
I believed this was achieved with https://github.com/camunda/camunda-modeler/pull/3509
