### ISSUE TITLE
Navigating via linting panel references does no clear label editing focus

### ISSUE THREAD

**Issue by Skaiir** [camunda/camunda-modeler#2961]
__Describe the Bug__

Navigation via the linting panel does not clear an activity's label editing box, as shown below. This leads to some cases where the context pad is obfuscated.

![editLabelStateStuck](https://user-images.githubusercontent.com/17801113/168553202-623bb7d7-3d72-4039-b7de-8afc69ee8acb.gif)

__Steps to Reproduce__

1. Create a C8 diagram
2. Create two blank tasks
3. Open the linting panel (should have two errors)
4. Double click on one of the blank tasks to enter label edit mode
5. Navigate between the two, the text input window does not close as we do

__Expected Behavior__

This navigation should happen exactly like how clicking manually would, and clear this editing state. 

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 5.0.0

**Comment by nikku** [comment]
This shall be fixed at the core (not a big deal, but a general canvas interaction issue):

Whenever selection changes and direct editing is active; then direct editing shall completed.

**Comment by Skaiir** [comment]
Closed via bc8b74870d230e0a8298b335ba00ff733388dc2d
