### ISSUE TITLE
Wrong linting error for Business Rule Task in Zeebe 1.2

### ISSUE THREAD

**Issue by andreasgeier** [camunda/camunda-modeler#2962]
__Describe the Bug__

A wrong message appears when creating a Business Rule Task and lint against Zeebe 1.2 (other versions to be checked, works as expected in 8.0).

__Steps to Reproduce__

See [recording in this comment](https://github.com/camunda/web-modeler/pull/1097#issuecomment-1123780247)

1. Create new BPMN diagram
2. Set execution platform to Zeebe 1.2
3. Add Task, morph to Business Rule Task
4. See error message

Expected message: `A <Business Rule Task> must have a defined <Implementation>`
Actual message: `A <Business Rule Task> must have a <Task definition type>`

__Expected Behavior__

See above

__Environments__

All

**Comment by barmac** [comment]
Zeebe 1.2 is not supported anymore.
