### ISSUE TITLE
Update telemetry documentation for next release

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2964]
__What should we do?__

Update telemetry documentation for next release with tracking of flags via ping event. 

See https://docs.camunda.io/docs/components/modeler/desktop-modeler/telemetry/

__Why should we do it?__

To keep https://docs.camunda.io/docs/components/modeler/desktop-modeler/telemetry/ up to date. Follow-up of https://github.com/camunda/camunda-modeler/issues/2901

**Comment by smbea** [comment]
Done with https://github.com/camunda/camunda-platform-docs/pull/1018
