### ISSUE TITLE
Remove drag preview from resizable containers

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2968]
### Describe the bug

There is a little annoying "globe" image when resizing certain containers (e.g. the properties panel).

![Kapture 2022-05-16 at 16 05 03](https://user-images.githubusercontent.com/9433996/168769114-7541b0f1-2653-4cd3-8713-00f900f15fbd.gif)

This comes from our [`dragger` utility](https://github.com/camunda/camunda-modeler/blob/develop/client/src/util/dom/dragger.js#L48), as we try to remove the dragging preview completely. 

Context: https://github.com/camunda/camunda-modeler/pull/2967#issuecomment-1128594443

### Steps to reproduce

1. Open new BPMN tab
2. Resize a container (e.g. properties panel)
3. The the "globe" icon appearappears

### Expected behavior

The drag preview should be disabled completely.

### Environment

- OS: macOS 11.6.5
- Camunda Modeler Version: 5.0.0
- Execution Platform: all
- Installed plug-ins: none

**Comment by philippfromme** [comment]
Fixed by https://github.com/camunda/camunda-modeler/pull/3509. We're not using drag events anymore.
