### ISSUE TITLE
Make empty file dialog buttons intuitive across all supported OS

### ISSUE THREAD

**Issue by Skaiir** [camunda/camunda-modeler#2970]
### Problem you would like to solve

Currently when importing an empty .bpmn file, a menu pops up on windows looking like this:

![image](https://user-images.githubusercontent.com/17801113/168854410-8223c555-3c9b-4f5d-8438-71a23f06b4e8.png)

On windows, this is off as the cancel button is nearly always rightmost aside from a few exceptions, usually a special action.

### Proposed solution

Swap the buttons on Windows. Knowing how mac re-arranges these buttons I don't believe we need to make any changes there. I also believe the order is expected on Linux. 

To confirm: 
- [x] Windows is wrong @Skaiir 
- [ ] Mac is ?
- [ ] Linux is ?

### Alternatives considered

n/a

### Additional context

Very similar fix to https://github.com/camunda/camunda-modeler/issues/2300

**Comment by barmac** [comment]
MacOS:
![image](https://user-images.githubusercontent.com/28307541/168979471-944d52df-38bf-44c2-847d-a96b4721d6eb.png)

I'd like "Create" to be the primary action (with blue background) if possible.

**Comment by Skaiir** [comment]
@barmac Is the blue background a selection state or does it just highlight one of the buttons? Like if you tab through, will the buttons show as blue?

**Comment by barmac** [comment]
I can't tab through and the hover background is a darker grey.

**Comment by barmac** [comment]
I believe we need to pass `defaultId` to make it work: https://github.com/electron/electron/pull/21642
