### ISSUE TITLE
Modeler 5.0 doesn't show multi-line fields for scripts anymore

### ISSUE THREAD

**Issue by michaelarnauts** [camunda/camunda-modeler#2982]
### Describe the bug

The rework of the property panels in 5.0 doesn't support multi-line property fields anymore. This is needed when writing a script to be executed by a script worker (on Camunda Platform 8), or when working with JSON values.

### Steps to reproduce

1. Add a script task.
2. Give it type `script` so it can be picked up by https://github.com/camunda-community-hub/zeebe-script-worker for example.
3. Add a header `language` = `javascript`.
4. Add a header `script` and try to add a script there. There is only room for one line.

![image](https://user-images.githubusercontent.com/1193779/171422555-c6d553c4-2d92-4fa9-b5ac-69865a38b959.png)

![image](https://user-images.githubusercontent.com/1193779/171422635-378d7558-b814-4586-a990-b8ca328a8d47.png)

### Expected behavior

It should be possible to expand the input field so it can contain multi-line values. This is how it worked in Modeler 4.x and earlier.

### Environment

- OS: Ubuntu 22.04
- Camunda Modeler Version: 5.0
- Execution Platform: N/A (happens with Camunda Platform 7 and 8 BPMN files)
- Installed plug-ins: N/A

**Comment by pinussilvestrus** [comment]
Thanks for your request!

> The rework of the property panels in 5.0 doesn't support multi-line property fields anymore

The properties panel still supports multi line fields, for example Camunda Forms configuration

<img width="628" alt="image" src="https://user-images.githubusercontent.com/9433996/171569244-8a054d06-ea91-40e7-91de-fa4b41ca40c6.png">

Headers are one-line inputs, that was already the case in Camunda Modeler 4.x

<img width="342" alt="image" src="https://user-images.githubusercontent.com/9433996/171568862-dff5dac8-13db-4677-bcb8-57bb1aceb412.png">

I think this is intended, as [the docs](https://docs.camunda.io/docs/components/modeler/bpmn/service-tasks/#task-headers) don't describe the option for multi-line values. 

If you think this would be a valuable addition, let's make this one a _feature request_ and discuss it 👍 

/cc
@christian-konrad

**Comment by christian-konrad** [comment]
@michaelarnauts What is your use case of adding a script to the header?

**Comment by michaelarnauts** [comment]
It seems to be the way how it's implemented in https://github.com/camunda-community-hub/zeebe-script-worker

Also, there is no other field available in models for Camunda 8.

**Comment by irlaer** [comment]
I have the same problem with editing names of elements
![изображение](https://user-images.githubusercontent.com/48518512/172849526-7fb04216-d7b3-459b-8b46-9c7182dfdeb8.png)

**Comment by nikku** [comment]
I think this is something we want to have (again), some day. Moving to backlog.

**Comment by nikku** [comment]
CC @christian-konrad

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js-properties-panel/issues/705.

**Comment by michaelarnauts** [comment]
> Fixed upstream via [bpmn-io/bpmn-js-properties-panel#705](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/705).

Only for name field, not for the headers or field injections.

**Comment by nikku** [comment]
Thanks @michaelarnauts.

Removed `fixed upstream`. Would be a good candidate to now clean this up end-to-end. We have all foundations in place.

**Comment by jarekdanielak** [comment]
Fixed upstream with https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1065

Released in [v5.18.1](https://github.com/bpmn-io/bpmn-js-properties-panel/releases/tag/v5.18.1)
