### ISSUE TITLE
Error editing properties of Field Injections for Task/Execution Listeners

### ISSUE THREAD

**Issue by irlaer** [camunda/camunda-modeler#2989]
### Describe the bug

I get an error when I try to edit properties of Field Injections. It occurs only for Task/Execution Listeners and work well with Field Injections for Service Task.

### Steps to reproduce

1. Add any kind of Task Listener
2. Add new item to Field Injections and try to input its name.
3. Error happens with small delay and appears in the log at the bottom and some functions of Modeler don't work until application restart.
![Task and Execution Listeners FiledInjections Error](https://user-images.githubusercontent.com/48518512/172846378-6fe36153-8018-4c24-89bf-9648c2e12678.png)

### Expected behavior

No unexpected errors

### Environment

- OS: Windows 10
- Camunda Modeler Version: 5
- Execution Platform: Camunda Platform 7
- Installed plug-ins: None

**Comment by Skaiir** [comment]
The issue as far as I can tell:

We have a few behaviors that respond to updateModdleProperties, like Niklas mentioned above. The event is called without and element defined, which causes the behaviors to throw. The behaviors themselves are not an issue, the element should be populated in this case.

I've traced back the undefined element to the properties panel core. There seems to be in issue with nested propagation of props in the ListGroup component, although investigations into formFieldConstraints (which are structured the same) show that this can work, so this may not be specifically a ListGroup issue but rather an implementation problem.

**Comment by Skaiir** [comment]
Closed via e77fc5da94aeb224de1f813b4c936558385be96f
