### ISSUE TITLE
Modeler 5 properties panel's keyboard input problem

### ISSUE THREAD

**Issue by irlaer** [camunda/camunda-modeler#2990]
### Describe the bug

When I type something (usually scripts in script task) in some unpredictable moment the last typed symbol does not appear and the cursor jumps to the end of text.
![Modeler5_input_bug](https://user-images.githubusercontent.com/48518512/173012005-efafec91-11fd-49c8-bf70-8e8918c7be05.gif)

### Steps to reproduce

1. Create script task with inline script
2. Start to type script content. It is better to see the bug when type symbols in the middle of text.
3. In a few seconds one or more symbol will be missed.

### Expected behavior

The cursor must not jump

### Environment

- OS: MacOS and Windows 10
- Camunda Modeler Version: 5
- Execution Platform: Camunda Platform 7
- Installed plug-ins: None

**Comment by nikku** [comment]
@marstamm @philippfromme this is something we already addressed ("debounced input loosing text")?

**Comment by marstamm** [comment]
Yes, this looks exactly like what was happening in https://github.com/bpmn-io/properties-panel/issues/146

So it should be fixed with the next release

**Comment by Skaiir** [comment]
Closed via e77fc5da94aeb224de1f813b4c936558385be96f
