### ISSUE TITLE
Collapse sub process does not move sequence flow descriptions

### ISSUE THREAD

**Issue by rweisleder** [camunda/camunda-modeler#2993]
### Describe the bug

When collapsing a sub process, sequence flow descriptions are not moved to the sub process diagram.

### Steps to reproduce

1. Create a new BPMN diagram for Camunda Platform 7
2. Create a simple process with start event, activity of type "Sub process (expanded)", and end event
3. Inside the sub process, create a simple process with start event, activity, and end event
4. Add a name for a sequence flow inside the sub process

The process looks like this now:
![image](https://user-images.githubusercontent.com/1654369/174297692-ef70dfe5-6182-48f7-9c71-726438f5c886.png)

5. Change the activity type from "Sub process (expanded)" to "Sub process (collapsed)"

After step 5, the name of the sequence flow remains in the diagram of the main process. The main process looks like this now:
![image](https://user-images.githubusercontent.com/1654369/174297806-35ef8fd9-2609-4020-a8e7-f792d5f5e1c0.png)

### Expected behavior

The name of the sequence flow should be moved to the diagram of the sub process.

## Camunda Modeler system information
 * Version: 5.0.0
 * Operating System: Windows 10 amd64
 * Plugins: BPMN Linter, bpmn-js Token Simulation, Transaction Boundaries
 * Execution Platform: BPMN - Camunda Platform 7

**Comment by marstamm** [comment]
Hi @rweisleder , thanks for opening this issue.

Seems like this was already addressed with https://github.com/bpmn-io/bpmn-js/issues/1617 in bpmn-js, but not yet released in the Modeler itself. This issue will be fixed with the next release

**Comment by Skaiir** [comment]
Closed via e77fc5da94aeb224de1f813b4c936558385be96f
