### ISSUE TITLE
Warn users about hidden sequence flows

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda-modeler#2994]
### Problem you would like to solve

When editing a model it could occur that some sequence flows are seemingly connected in one way:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/5787702/174800669-59afad1e-504c-4bc7-9dd4-fc251407d9ce.png">

But in reality the sequence flows behind the gateway:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/5787702/174799809-4198b3c8-6f4b-41b9-971e-586850f9f2e0.png">

In the first image it's very hard to see that the sequence flows doesn't target the gateway, but goes through it and targets the task. It would be great if we could improve this visually, or warn the user with linting that a flow is hidden.

### Proposed solution

Move sequence flows to the foreground of the process.

### Alternatives considered

Have linting detect when a sequence flow is hidden underneath some other element, giving users a warning when this is the case.

**Comment by nikku** [comment]
Thanks for your report. We'll investigate if moving sequence flows to the front is a quick win or if we need another way to indicate such flows.

**Comment by barmac** [comment]
> Thanks for your report. We'll investigate if moving sequence flows to the front is a quick win or if we need another way to indicate such flows.

So this could look like the diagram below, right?

![image](https://user-images.githubusercontent.com/28307541/175243477-f67695a8-d4ea-43f3-84a3-a692458921d9.png)

I think it's worth trying out. We already draw message flows on top.

**Comment by CatalinaMoisuc** [comment]
Moved to backlog, we could consider this as a warning in the future.

**Comment by barmac** [comment]
> Moved to backlog, we could consider this as a warning in the future.

Somehow it was still `ready`.

**Comment by barmac** [comment]
There will be no hidden sequence flow once https://github.com/bpmn-io/bpmn-js/pull/1717 is integrated.
