### ISSUE TITLE
Update check failure not properly handled

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2999]
### Describe the Problem

What I've found is that the update check does not work but that is due to the update server not handling feature branch builds gracefully (it simply returns `400 Bad Request`) and the modeler tries to parse that as `JSON` (not properly handling the `HTTP 400` error code):

![capture 1sK5kH_optimized](https://user-images.githubusercontent.com/58601/175013301-5e7d6098-7355-44c7-a4d5-2784c0a49eb0.gif)

### Expected Behavior

If the update check fails with a `HTTP 400` we do not attempt to parse the response, but indicate the error in a non cryptic fashion.

Bonus points: Ensure that our update server exposes machine readable errors that we can display to the user.

Additional bonus: Handle feature branch versions `v5.0.0-foo-bar` gracefully in the update server.

### Environment

* Camunda Modeler: v5.0.0-some-feature-branch
* OS: Linux (Arch)

----

_Originally posted by @nikku in https://github.com/camunda/camunda-modeler/pull/2998#issuecomment-1162970727_

**Comment by marstamm** [comment]
closed by https://github.com/camunda/camunda-modeler/pull/3265
