### ISSUE TITLE
XML editor scroll position lost after tab switch

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#300]
After switching to another tab when I switch back to my original tab scroll position is lost. This is counter-intuitive.

![xml-editor-scroll-position-lost](https://cloud.githubusercontent.com/assets/7633572/15466098/2f9044a2-20d8-11e6-9701-12c3f370dbd1.gif)

**Comment by ricardomatias** [comment]
Works as intended on my machine.
