### ISSUE TITLE
Template applies to CallActivity is not displaying in BPMN Camunda Platform 8.0

### ISSUE THREAD

**Issue by Cruiser79** [camunda/camunda-modeler#3000]
### Describe the bug

If i use the following template example from the sample.json and create a BPMN Camunda Plaform 7 document it will show me the template chooser, if i create a task and switch it to CallActivity. If i do the same with a BPMN Camunda Platform 8 document, no template chooser is displayed.
`
[
  {
    "$schema": "https://unpkg.com/@camunda/element-templates-json-schema/resources/schema.json",
    "name": "Caller All IO",
    "id": "com.camunda.example.CallerAllIO",
    "appliesTo": [
      "bpmn:CallActivity"
    ],
    "properties": [
      {
        "label": "Called Process",
        "type": "String",
        "editable": false,
        "value": "calledProcess",
        "binding": {
          "type": "property",
          "name": "calledElement"
        }
      },
      {
        "label": "Input all",
        "type": "Hidden",
        "binding": {
          "type": "camunda:in",
          "variables": "all"
        }
      },
      {
        "label": "Output all",
        "type": "Hidden",
        "binding": {
          "type": "camunda:out",
          "variables": "all"
        }
      }
    ]
  }
]
`

### Steps to reproduce

1. Create a sample.json with the sourcode above
2. Open Modeler 5.0.0
3. Create a BPM Camunda Platform 8.0 document
4. Create a task
5. Switch task type to CallActivity

### Expected behavior

The template chooser will be displayed

### Environment

- OS: Windows 10
- Camunda Modeler Version: 5.0.0
- Execution Platform: -
- Installed plug-ins: -

**Comment by smbea** [comment]
I was able to reproduce this issue, moving to backlog.

**Comment by smbea** [comment]
The problem doesn't seem to be the `appliesTo` type. For example, this template works: 

```json
{
  "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
  "name": "Caller All IO",
  "id": "com.camunda.example.CallerAllIO",
  "appliesTo": [ "bpmn:CallActivity" ],
  "properties": [ ]
}
```

The problem should be with the schema of the `properties`
