### ISSUE TITLE
Usage of Variables didn't contain a separator

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#3003]
### Describe the bug

When I have a process variable used in two different generated forms, the Variables section shows the name of the tasks without any separator:

![grafik](https://user-images.githubusercontent.com/7870843/175567443-8c379fbb-5b16-4b37-b342-5487c888615a.png)

### Steps to reproduce

1. label the start event
2. create a generated form on the start event.
3. add a single process variable
4. append a user task to the start event and enter a label.
5. create a generated from on the user task.
6. add the same process variable.
7. select the process
8. open the Variables section

### Expected behavior

The names of the tasks are somehow separated. With a comma, semicolon or anything else.

### Environment

Camunda Modeler system information
 * Version: 5.0.0
 * Operating System: Windows 10 amd64
 * Plugins: Cloud Connect, Migration, bpmn-js Token Simulation, BPMN Linter, Transaction Boundaries, Camunda Property Infos, Tooltip Plugin
 * Execution Platform: BPMN - Camunda Platform 7

**Comment by smbea** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/714

**Comment by Skaiir** [comment]
Closed via e77fc5da94aeb224de1f813b4c936558385be96f
