### ISSUE TITLE
As a user I can template Call Activities

### ISSUE THREAD

**Issue by Cruiser79** [camunda/camunda-modeler#3006]
### Describe the bug

In the examples for camunda 7 templates (https://github.com/camunda/camunda-modeler/blob/develop/resources/element-templates/samples.json) we can set the property for the called element of an CallActivity

```JSON
  {
    "$schema": "https://unpkg.com/@camunda/element-templates-json-schema/resources/schema.json",
    "name": "Caller",
    "id": "com.camunda.example.Caller",
    "appliesTo": [
      "bpmn:CallActivity"
    ],
    "properties": [
      {
        "label": "Called Process",
        "type": "String",
        "editable": false,
        "value": "calledProcess",
        "binding": {
          "type": "property",
          "name": "calledElement"
        }
      }
```

If i try the same with a camunda 8 template, the modeler sets the property as a property of the "root element" from the call activity

```JSON
  {
    "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
    "name": "call activity",
    "id": "my.callactivity",
    "appliesTo": [
      "bpmn:CallActivity"
    ],
    "properties": [
      {
        "label": "Called element",
        "type": "Hidden",
        "editable": false,
        "value": "recordSubEvent",
        "binding": {
          "type": "property",
          "name": "calledElement"
        }
      }
```
will get

```XML
    <bpmn:callActivity id="Activity_11cqzvi" zeebe:modelerTemplate="my.callactivity" calledElement="recordSubEvent">
      <bpmn:extensionElements>
        <zeebe:calledElement propagateAllChildVariables="false" />
```

what i want

```XML
    <bpmn:callActivity id="Activity_0osluzw" zeebe:modelerTemplate="my.callactivity">
      <bpmn:extensionElements>
        <zeebe:calledElement processId="recordSubEvent" propagateAllChildVariables="false" />
        <zeebe:ioMapping>
```

### Steps to reproduce

1. Use the template for https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json from above to create a template
2. Open modeler 5.0.0 and create a bpmn 8
3. Create a CallActivity and use the created template
4. Save the created BPMN

### Expected behavior

The created XML should have a zeebe:calledElement xml element with the processId.

### Environment

- OS: Windows 10
- Camunda Modeler Version: 5.0.0
- Execution Platform: -
- Installed plug-ins: -

### Additional context

Depends on https://github.com/bpmn-io/bpmn-js-element-templates/issues/28

**Comment by pinussilvestrus** [comment]
Unfortunately, templating call activities is not supported for Camunda 8 Templates at the moment. There is an issue in the upstream properties panel library that tracks the progress: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/704.

In related news: thanks for reporting this. It gives us an indication that this feature is needed (/cc @christian-konrad) 👍

**Comment by ingorichtsmeier** [comment]
Hi team, I've lately recommended call activities with templates for a smooth migration from Camunda 7 to Camunda 8. Right now, the customer uses an execution listener to initialize variables for the called process.

In the future, a preconfigured Call Activity would be the way to go. Could you please move it higher on the priorities?

**Comment by nikku** [comment]
Moving to `ready`.
