### ISSUE TITLE
Resize log panel works clumsy in XML tab

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#3017]
### Describe the bug

Resizing the log panel does not work sufficiently inside the XML tab.

![Kapture 2022-07-08 at 12 03 00](https://user-images.githubusercontent.com/9433996/177969235-413e01fd-5f07-48ff-a993-2fc91c0915fd.gif)

It's working better in the diagram view.

### Steps to reproduce

1. Open the log panel
2. Open the XML tab
3. Resize the log panel
4. Increasing the height does not work at all

### Expected behavior

Resizing the log panel should work sufficiently.

### Environment

- OS: MacOS 11.6.5 
- Camunda Modeler Version: 5.1.0-rc.1, 5.0.0, 3.3.0
- Execution Platform: /
- Installed plug-ins: Cloud Connect Plugin

### Additional context

Related to https://github.com/camunda/camunda-modeler-design/issues/90.

**Comment by pinussilvestrus** [comment]
Moving this to the backlog, as this issue persists for a time now and I think it has no priority at the moment.

**Comment by philippfromme** [comment]
Fixed by https://github.com/camunda/camunda-modeler/pull/3509.
