### ISSUE TITLE
Update release info for 5.1

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-modeler#3021]
### What should we do?

Update the [Release Info](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/version-info/ReleaseInfo.js) release info for 5.1 following our [guidelines](https://github.com/bpmn-io/internal-docs/tree/master/camunda-modeler#whats-new-communication)

### Why should we do it?

To provide users with info about the new release, and how to cope with changes.

**Comment by Skaiir** [comment]
Resolved through https://github.com/camunda/camunda-modeler/commit/51f3da5e15cbbea71de128e0b620fa5ad3c17ac7
