### ISSUE TITLE
Monkey patch 5.1 styles for the release, then resolve those. 

### ISSUE THREAD

**Issue by Skaiir** [camunda/camunda-modeler#3025]
### Describe the bug

We've encountered two release critical bugs late in the release, we'll fix this temporarily using css styling but the root cause needs to be investigated for both of those and the monkey patch reverted.

- [x] Apply monkey patch - https://github.com/camunda/camunda-modeler/pull/3026
- [x] Root cause and fix [CSS styling issue](https://github.com/bpmn-io/internal-docs/issues/590)
- [x] <del>Root cause and fix [sticky headers issue](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/726)</del> [Exclude for now](https://github.com/camunda/camunda-modeler/issues/3025#issuecomment-1197839192)
- [x] Integrate changes
- [x] Remove monkey patch

### Steps to reproduce

**[CSS issue](https://github.com/bpmn-io/internal-docs/issues/590):**
1. using camunda-modeler `5.1.0-rc.2`
2. open a bpmn diagram
3. create a task
4. look at the template section => button is not visible except on hover due to styles override

**[Sticky header issue](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/726):**
1. using camunda-modeler `5.1.0-rc.2`
2. open a bpmn diagram
3. mess around with the group headers => headers sometimes end up in an unexpected state

### Expected behavior

The template buttons should always be visible if the group is present.

The headers should only be sticky when they are at least partially above the top of the scrollarea.

### Environment

- Camunda Modeler Version: 5.1.0-rc.2

**Comment by pinussilvestrus** [comment]
Also related: https://github.com/camunda/camunda-modeler/issues/3030

**Comment by pinussilvestrus** [comment]
> Root cause and fix https://github.com/bpmn-io/bpmn-js-properties-panel/issues/726

Find some notes on this one: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/726#issuecomment-1197837962

**Comment by pinussilvestrus** [comment]
This is fixed upstream as it requires the integration of a new properties panel release.

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/3059.
