### ISSUE TITLE
Unable to operate after upgrade to 5.1.0 version

### ISSUE THREAD

**Issue by Siddharth0905** [camunda/camunda-modeler#3027]
### Describe the bug

<img width="1792" alt="Screenshot 2022-07-13 at 11 17 26 AM" src="https://user-images.githubusercontent.com/8971332/178660045-98b0dc1f-5d1c-46e8-8d92-133f19304707.png">

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Expected behavior

Old bpmn fils should work without any issue

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by nikku** [comment]
Please attach a diagram / concrete steps to you took so we're able to reproduce your case.
