### ISSUE TITLE
Conditional properties are not reliably rendered

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-modeler#3029]
### Describe the bug

Property conditions are not evaluated right when applying a template where the referenced dropdown value has no explicit default. Also, the value of a binding is not changed to the specified default value when using multiple but mutually exclusive properties with different default values (i.e. to simulate conditional default values). The latter is a behavior requested by a partner that implements a whole connector ecosystem.

### Steps to reproduce

1. Create a template with a dropdown with no default option specified (the first option will be rendered)
2. Create 2 dependent properties, but with same binding, and both depending on different dropdown option. The first is dependent on the first dropdown option. Both have different default values.
3. When applying the template, even if the first dropdown option is visually selected, the dependent property isn't shown
4. Switching the dropdown value does not change the default value of the field/binding
5. The field must be rendered invisible first (by invalidating all conditions), before the default value can change 

See the video and template (next comment)

https://user-images.githubusercontent.com/56470362/179018429-c526803e-4faa-4cc0-ac21-a4ebf8c54995.mov

### Expected behavior

- Either the dropdown renders no value if no default is set, or if the first value is rendered, all conditions to this must be evaluated.
- Default values of same bindings should change when conditions apply, as this is explicitly defined in the template (otherwhise, the template should prohibit multiple properties with same binding) 

### Environment

- Camunda Modeler Version: 5.1.0
- Execution Platform: C8
- Installed plug-ins: None

**Comment by christian-konrad** [comment]
```
  {
    "$schema": "https://unpkg.com/browse/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
    "name": "Same Binding Test",
    "id": "same-binding-test",    
    "appliesTo": [
      "bpmn:ServiceTask"
    ],
    "properties": [
      {
        "id": "default-changer",
        "label": "Change the default",
        "type": "Dropdown",
        "choices": [
          {
            "name": "Set it as 1",
            "value": "set-1"
          },
          {
            "name": "Set it as 2",
            "value": "set-2"
          },
          {
            "name": "Reset",
            "value": ""
          }
        ],
        "binding": {
          "type": "zeebe:taskHeader",
          "key": "ignore"
        }
      },
      {
        "label": "Test",
        "type": "String",
        "value": "1",      
        "binding": {
          "type": "zeebe:input",
          "name": "test"
        },
        "condition": {
          "property": "default-changer",
          "equals": "set-1"
        }
      },

      {
        "label": "Test",
        "type": "String",      
        "value": "2",
        "binding": {
          "type": "zeebe:input",
          "name": "test"
        },
        "condition": {
          "property": "default-changer",
          "equals": "set-2"
        }
      }
    ]
  }
]

**Comment by pinussilvestrus** [comment]
I believe it should work the same as for any other templated "Dropdown" property. When no `value` is given, it should display empty.

![image](https://user-images.githubusercontent.com/9433996/179175163-3a198ccb-4051-454a-a466-da709bc2ef2c.png)

```json
{
  "name": "Dropdown",
  "id": "Dropdown",
  "appliesTo": [  "bpmn:ServiceTask"  ],
  "properties": [
    {
      "label": "Task Priority",
      "type": "Dropdown",
      "choices": [
        { "name": "low", "value": "20" },
        { "name": "medium", "value": "50" },
        { "name": "height", "value": "100" }
      ],
      "binding": {
        "type": "property",
        "name": "camunda:priority"
      }
    }
  ]
}
````

**Comment by pinussilvestrus** [comment]
Moving this to backlog as it was not picked for the next iteration. Feel free to disagree.

**Comment by christian-konrad** [comment]
Hi, a forum user just ran into this issue, too:

https://forum.camunda.io/t/help-use-expression-in-element-templates/39039

The feature becomes more powerful if we fix this, so please put it into ready and pick it up on the next planning.

**Comment by nikku** [comment]
Also reported from the connectors side of things: https://github.com/camunda/web-modeler/issues/3075.

Moving back to ready and hoping to be able to pick this up.

**Comment by nikku** [comment]
Closed via [dependency bump](https://github.com/camunda/camunda-modeler/commit/8ecb65fffe00db81a2183180a9eef98923f5b471).

**Comment by nikku** [comment]
![capture m4q8B8_optimized](https://user-images.githubusercontent.com/58601/204773308-e7db5700-4cbe-4d47-bac9-6c1cb4fd218d.gif)

**Comment by igpetrov** [comment]
Hi @nikku, sorry for re-opening, just wanted to double-check if this is released (or is it even the same issue?) because this is an issue raised by one of external users.

I currently still see an issue on dev. Consider following element template and video attached.

```
{
  "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
  "name": "dynamic-values",
  "id": "2b9dc4da-6acc-478c-a774-ece1b04ff988",
  "appliesTo": [
    "bpmn:ServiceTask"
  ],
  "properties": [
    {
      "id": "default-changer",
      "label": "Change the default",
      "type": "Dropdown",
      "choices": [
        {
          "name": "Set it as 1",
          "value": "set-1"
        },
        {
          "name": "Set it as 2",
          "value": "set-2"
        },
        {
          "name": "Set it as 3",
          "value": "set-3"
        }
      ],
      "binding": {
        "type": "zeebe:input",
        "name": "ignore"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "Test",
      "type": "String",
      "value": "1",
      "binding": {
        "type": "zeebe:input",
        "name": "test"
      },
      "condition": {
        "property": "default-changer",
        "equals": "set-1"
      }
    },
    {
      "label": "Test",
      "type": "String",
      "value": "2",
      "binding": {
        "type": "zeebe:input",
        "name": "test"
      },
      "condition": {
        "property": "default-changer",
        "equals": "set-2"
      }
    },
    {
      "label": "Test",
      "type": "String",
      "value": "3",
      "binding": {
        "type": "zeebe:input",
        "name": "test"
      },
      "condition": {
        "property": "default-changer",
        "equals": "set-3"
      }
    }
  ]
}
```


https://user-images.githubusercontent.com/108870003/204857843-927b9ffe-d4e2-4f15-8478-0a7896ba42de.mov

**Comment by nikku** [comment]
Thanks for raising. I propose to (and will) move this to a separate issue.

**Comment by nikku** [comment]
Opened https://github.com/camunda/camunda-modeler/issues/3327 to track the bug you reported as a follow up.

**Comment by nikku** [comment]
FYI @igpetrov https://github.com/camunda/camunda-modeler/issues/3327#issuecomment-1333310967.
