### ISSUE TITLE
form field on the start event creates a business key as well

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#3050]
### Describe the bug

When I model a generated form on the start event, the first form field is also used as business key.

This should not happen, the business key has to be a separate entity.

### Steps to reproduce

1. Create a new BPMN Diagram for Camunda Platform 7
2. Select the start event
3. Open the property panel and enter the Form group
4. Select generated form
5. Add a form field with name firstname, label Firstname and type string 

### Expected behavior

The business key group should be untouched.

Instead the firstname becomes the business key as well: 
![grafik](https://user-images.githubusercontent.com/7870843/180768704-1642bf52-217a-496a-b393-efb9355a63f1.png)

```
    <bpmn:startEvent id="StartEvent_1" name="Immutable data test wanted">
      <bpmn:extensionElements>
        <camunda:formData businessKey="firstname">
          <camunda:formField id="firstname" label="Firstname" type="string" />
        </camunda:formData>
      </bpmn:extensionElements>
      <bpmn:outgoing>Flow_0vxpkwl</bpmn:outgoing>
    </bpmn:startEvent>
```
The attibute `businessKey` should not be there.
 

### Environment

Camunda Modeler system information
 * Version: 5.1.0
 * Operating System: Windows 10 amd64
 * Plugins: Cloud Connect, Migration, bpmn-js Token Simulation, BPMN Linter, Transaction Boundaries, Camunda Property Infos, Tooltip Plugin
 * Execution Platform: BPMN - Camunda Platform 7

**Comment by pinussilvestrus** [comment]
Seems like we have a dedicated modeling behavior for that: https://github.com/camunda/camunda-bpmn-js-behaviors/blob/master/lib/camunda-platform/UserTaskGeneratedFormsBehavior.js#L44

I don't have much context on that, but there seems to be a reason why we are doing that (updating the business key once the form field id changed). 

However, as we are doing it [_before the id update_](https://github.com/camunda/camunda-bpmn-js-behaviors/blob/master/lib/camunda-platform/UserTaskGeneratedFormsBehavior.js#L44), [there might be a bug](https://github.com/camunda/camunda-bpmn-js-behaviors/blob/master/lib/camunda-platform/UserTaskGeneratedFormsBehavior.js#L59) that it's also doing it when formField id and the business key is `undefined`.

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/3059
