### ISSUE TITLE
Element-Templates are not discovered in .camunda/element-templates directory

### ISSUE THREAD

**Issue by McAlm** [camunda/camunda-modeler#3055]
### Describe the bug

According to the docs [modeler-template configuration](https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/configuring-templates/) templates can be stored into a `.camunda/element-templates directory that resides, relative to the currently opened diagram, anywhere in the diagrams path hierarchy.`
This does not work (at least on my machine => see environment) for C8 templates. When putting the templates to the APP_DATA_DIRECTORY they are picked up by the Modeler.

### Steps to reproduce

Create a template as .json and store it into a folder .camunda/element-templates next to a bpmn file (Camunda 8). Open the modeler, the template is not being shown when an element is configured accordingly to the template.

### Expected behavior

Following the docs the template should appear in the template list of an selected element.

### Environment

MacBook Pro M1, macOs Monterey 12.5
Camunda Modeler 5.1

**Comment by pinussilvestrus** [comment]
Can you maybe share your C8 element template so we can try to reproduce your problem?

**Comment by McAlm** [comment]
[mailconnector.json.zip](https://github.com/camunda/camunda-modeler/files/9205755/mailconnector.json.zip)
This is how it works on my machine (using ${APP_DATA_DIR}
<img width="240" alt="doesNotWork" src="https://user-images.githubusercontent.com/2012154/181430179-25def34b-3a7a-46f3-9e27-7e8e7f104187.png">

And this is what does not work(.camunda folder next to the process.bpmn):
<img width="228" alt="works" src="https://user-images.githubusercontent.com/2012154/181430184-554da677-de4c-4c70-b276-13964df556cc.png">

**Comment by McAlm** [comment]
I have no idea why it yesterday did not work, but today the template is being picked up from the local .camunda folder...
I close this ticket for now, sorry for bothering you! ;-)

**Comment by pinussilvestrus** [comment]
Thanks for the follow up 👍
