### ISSUE TITLE
Update timer cycle definition to support cron expression

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-modeler#3061]
### What should we do?

Update timer cycle definition to support cron expressions.

Inspiration can be retrieved from the docs (once those are completed).
- https://github.com/camunda/camunda-platform-docs/issues/1117

### Why should we do it?

Camunda Platform 8.1 introduces the following
- https://github.com/camunda/zeebe/pull/9674

Note that we can define a CRON expression, but that the description specifies the ISO 8601 repeating intervals only:
<img width="801" alt="Screen Shot 2022-08-03 at 16 00 40" src="https://user-images.githubusercontent.com/3511026/182627404-450d8c7b-bd81-42d0-9086-1de5ac9f775f.png">

---

Related to https://github.com/camunda/product-hub/issues/300.

**Comment by pinussilvestrus** [comment]
Are there changes needed for the property itself, or are only documentation/description updates required?

**Comment by korthout** [comment]
@pinussilvestrus I don't think so. For the `Cycle` Type, the Value can simply be set to a cron expression (like in the example above).

**Comment by nikku** [comment]
Split up validation into separate topic: https://github.com/camunda/camunda-modeler/issues/3084. That one goes beyond duration but shall cover different mentions of times, durations and intervals, as well as CRON expressions across our app(s).

**Comment by barmac** [comment]
Do we want to update the description for C7 too? [As noted in the Zeebe issue](https://github.com/camunda/zeebe/issues/9673#issuecomment-1176055977), C7 also supports cron expression and it's documented: https://docs.camunda.org/manual/7.17/reference/bpmn20/events/timer-events/#time-cycle

**Comment by nikku** [comment]
Yes, let us do it!

**Comment by barmac** [comment]
Draft:

![image](https://user-images.githubusercontent.com/28307541/191281605-880aaff8-f178-4887-b845-c0cae0103199.png)

**Comment by barmac** [comment]
The example comes from the docs: https://docs.camunda.io/docs/next/components/modeler/bpmn/timer-events/#time-cycle

**Comment by barmac** [comment]
I confirmed that a timer with exactly this expression is successfully deployed to `zeebe@8.1.0-alpha5`. No additional flags are required.

**Comment by barmac** [comment]
OK, so I will proceed with the contents as on the screenshot.

**Comment by barmac** [comment]
This will be implemented via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/772
