### ISSUE TITLE
DRD image export is broken

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#3068]
### Describe the bug

With version 5.1.0, exporting a DRD to an image is broken.

![image](https://user-images.githubusercontent.com/9433996/183031476-cb902d94-5549-40bb-b7f2-1a1ea4375995.png)

### Steps to reproduce

1. Create new DMN file
2. Export as image (CTRL/CMD + Shift + E)
3. See error in the Log Panel

### Expected behavior

The image export of DRDs is working without errors.

### Environment

- OS: MacOS 11.6.5
- Camunda Modeler Version: 5.1.0, 5.2.0-rc.0
- Execution Platform: /
- Installed plug-ins: /

### Additional context

Note the last version the export is working for me is 5.1.0-rc.1. We updated dmn-js afterward: https://github.com/camunda/camunda-modeler/commit/9bbcec9ed62cf9f6846af45e52f1d1584132ab59

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/3074.
