### ISSUE TITLE
Remove Default Value `= source` of Variable Assignment Value from Newly Created Inputs and Outputs

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3073]
### Problem you would like to solve

We currently have the default value "source" in the input and output assignment value field that has been present for the user to avoid and empty assignment value.

### Proposed solution

Since we now have the Feel editor in place we could remove the "source" text as the default value from the input and output assignment field. Also we need to manually remove this default value each time  when we want to enter a new input/output assignment .

### Alternatives considered

The "source" text could also be a made as a placeholder text as an example to the users

### Additional context

https://user-images.githubusercontent.com/85225325/183061331-630dee29-a30e-45b2-8619-8c4235ae6cfb.mp4

**Comment by philippfromme** [comment]
This could also be a use case for linting.
