### ISSUE TITLE
Clarify Behavior When Switching between FEEL and Non-FEEL Property

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3075]
### Problem you would like to solve

1. Select a field where the FEEL expression is not mandatory
2. Fill in the field with any expression in the Feel 
3. Try to switch between normal text field and the Feel editor
4. Now in  the normal text field try to edit the expression
5. Switch back to feel editor 
6. We could see that the new line formatting is not maintained when we switch between normal text field and feel editor

### Proposed solution

We should clarify the behavior regarding formatting and preserving whitespace characters when switching between FEEL and non-FEEL properties. Right now, the behavior feels broken.

### Alternatives considered

* be explicit and remove line breaks when switching from FEEL to non-FEEL - single line means single line

### Additional context

https://user-images.githubusercontent.com/85225325/183065676-0d0b1cd2-6f62-4713-9dc1-ed184fd0a630.mp4

**Comment by nikku** [comment]
I reviewed this one again. Once you edit the (single line) text then the (FEEL) newline information is gone. It still works if you just (accidentally) toggled, toggling FEEL back on keeps the newlines:

![capture tWNBSj_optimized](https://github.com/user-attachments/assets/e4e41f2e-0223-469a-a3e2-b85537d39aea)


For this reason I regard this as an edge case, and will close this issue.
