### ISSUE TITLE
Unintuitive selection indicator in (Web) Modeler

### ISSUE THREAD

**Issue by hkupitz** [camunda/camunda-modeler#3081]
### Problem you would like to solve

Since Camunda Modeler version 5.1.0 the selection behavior on the canvas seems to have changed. I am not sure if this is a bug or a change that was made on purpose. This change also appears in the current version of Web Modeler.

Beforehand, when hovering over an element on the canvas, there used to be a transparent dashed line indicator around the element with the mouse cursor being set to default:

![Camunda Modeler 5.0.0](https://user-images.githubusercontent.com/27265759/183444967-bd3fd55f-2584-43d2-b9d5-429a5fac18c7.png)

Now there is no indicator at all anymore, with the mouse cursor changing to a dragging cursor, without the element itself even being selected:

![Web Modeler](https://user-images.githubusercontent.com/27265759/183445991-ba099764-651a-4126-923a-b9693826bc4b.png)

When the element is selected, a continuous line indicator around the element appears (instead of the dashed line one), with the cursor still being of the dragging type:

![Web Modeler](https://user-images.githubusercontent.com/27265759/183447085-e3447c1d-1589-4d48-a928-cc72f34ee88a.png)

Personally I find especially the lack of a hover indicator as well as the continuous line selection indicator a bit unintuitive. Without the hover indicator the dragging cursor feels a bit out of place.

### Proposed solution

As for the lack of a hover indicator: I think there definitely should be an indicator, preferably one with a dashed line.

![image](https://user-images.githubusercontent.com/27265759/183459847-969346ca-d580-4180-8027-10a5f7790026.png)

Personally I was fine with the default mouse cursor when hovering over an element, however this might simply be because I am very used to it. I know of tools that use a default cursor for this as well as tools that change the cursor to the cross-arrow one.

IMO the continuous line selection indicator might work, but maybe could be made more transparent to not look as visually blocking:

![Proposed selection indicator](https://user-images.githubusercontent.com/27265759/183457982-b59c07e5-8fb5-4af2-b1f7-5cdf111d2898.png)

### Additional context

Tested on _Camunda Modeler 5.1.0_ + _Web Modeler_ (current version)

**Comment by nikku** [comment]
Thanks for your feedback on this matter. We've indeed reworked hover / select feedback on the diagram canvas with the Camunda Modeler 5.1 / [bpmn-js@9.2](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#920).

However what you describe (missing hover feedback) is not a bug but a feature. Let me try to elaborate.

The original issue we solved was that there was no way for the user to figure out whether an element is hovered _or_ selected (https://github.com/bpmn-io/bpmn-js/issues/1616). Looking into how most other popular diagramming tools (Powerpoint, Google Slides, Miro, Inkscape) do it we found that they don't indicate hover with a dedicated outline. Hence we dropped the hover outline. Same applies to the dragging cursor; we simply adopted proven ways of working.
