### ISSUE TITLE
Support diverging inclusive gateway

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-modeler#3083]
### Problem you would like to solve

The diverging inclusive gateway (i.e. OR gateway) is added to Zeebe in https://github.com/camunda/zeebe/pull/9747 as an external contribution. Of course, all the Camunda Platform 8 need to be aligned and support the feature.

If the Modeler doesn't support modeling the inclusive gateway for Camunda Platform 8, then our customers cannot use this new feature.

### Proposed solution

Please support the diverging inclusive gateway for Camunda Platform 8. The behavior is specified in the PR.

At a minimum:
- a gateway can be configured to the **Inclusive Gateway** type
- **Conditions** can be configured for outgoing sequence flows of the inclusive gateway
- a **Default** outgoing sequence flow can be chosen for the inclusive sequence flow

Nice to have:
- validations are added for:
  - an outgoing sequence flow of an inclusive gateway doesn't have a condition **and** the inclusive gateway has more than 1 outgoing sequence flow
  - there are multiple sequence flows targeting the inclusive gateway

### Alternatives considered

- Customers can update the XML by hand
- Customers can use combinations of XOR and AND gateways to rebuild the OR gateway logic.

### Additional context

- https://github.com/camunda/product-hub/issues/214

PS: The `Camunda Cloud` label should probably be updated to `Camunda Platform 8`

----

__TODO__ 

* [x] add inclusive gateway to replacement options ([camunda-bpmn-js](https://github.com/camunda/camunda-bpmn-js))
  * https://github.com/camunda/camunda-bpmn-js/pull/162
* [x] show _Condition_ group in properties panel if sequence flow source is inclusive gateway ([bpmn-js-properties-panel](https://github.com/bpmn-io/bpmn-js-properties-panel))
  * https://github.com/bpmn-io/bpmn-js-properties-panel/pull/756
* [x] add lint rules ([bpmnlint-plugin-camunda-compat](https://github.com/camunda/bpmnlint-plugin-camunda-compat/))
  * [x] https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/44
  * [x] https://github.com/camunda/linting/pull/18 
    * [x] inclusive gateway only supported in 8.1
    * [x] inclusive gateway must not have more than one incoming sequence flow ("converging OR gateway not supported")
    * [x] if inclusive gateway has more than one outgoing sequence flow each must have condition (i.e. Conditions are required, unless the OR gateway is not diverging)
 * [x] integrate into Camunda Modeler
   * [x] release `bpmnlint-plugin-camunda-compat`
   * [x] release `@camunda/linting`
   * [x] release `bpmn-js-properties-panel`
   * [x] release `camunda-bpmn-js`

**Comment by nikku** [comment]
@korthout to reiterate on what you say:

* Forking OR gateway is supported, converging OR gateway is NOT supported

That means:

* We allow modeling of OR gateway (replace)
* We add dedicated lint rules:
    * OR gateway only supported in 8.1
    * OR gateway must not have more than one incoming sequence flow ("converging OR gateway not supported")

**Comment by korthout** [comment]
@nikku That sounds great.

Did you also consider a lint rule for:
- OR gateway with more than one outgoing sequence flow must have a Condition for each of these flows (i.e. Conditions are required, unless the OR gateway is not diverging)

**Comment by nikku** [comment]
@korthout Added as a rule.

**Comment by korthout** [comment]
Thanks @skayliu for bringing attention to this. 

The linting rules were actually the reason that camunda/zeebe#10310 was discovered. But I forgot to document it. Sorry about that.

**Comment by nikku** [comment]
>  may be the lint rule shold make some adjust

As you've identified, lets fix this in Zeebe, and not workaround in our lint rules.

**Comment by nikku** [comment]
@philippfromme please double-check but I believe with https://github.com/camunda/camunda-modeler/pull/3150 merged this can be closed?

**Comment by philippfromme** [comment]
@nikku Yes, we can finally close this issue. 🎉
