### ISSUE TITLE
Validate format of durations, intervals and times entered in the properties panel

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3084]
### What should we do?

Validate ISO date and duration as well as CRON expressions entered by the user using our lint infrastructure.

Thereby we capture two important aspects:

* Support for different notations (i.e. CRON introduced in 8.1 only)
* Format of message (would fail deployment if invalid)

### Why should we do it?

Help our users to prevent unnecessary errors as early as possible.

----

Related to https://github.com/camunda/camunda-modeler/issues/3061.

**Comment by nikku** [comment]
CC @christian-konrad

**Comment by barmac** [comment]
This will be implemented in bpmn-io/bpmn-js-properties-panel.

**Comment by barmac** [comment]
Fixed upstream in https://github.com/camunda/linting/pull/23

**Comment by barmac** [comment]
I showed @christian-konrad a prototype of the solution and we concluded that it needs a couple of improvements:

* Nonsense ISO8601 dates should be rejected (e.g. February 30th, 30:00:00 etc.).
* The cycle validation message should state it explicitly that cron is supported in 8.1 and newer only.

If you want to try out the prototype, check out:

 https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/timer-linting/camunda-modeler-timer-linting-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/timer-linting/camunda-modeler-timer-linting-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/timer-linting/camunda-modeler-timer-linting-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/timer-linting/camunda-modeler-timer-linting-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/timer-linting/camunda-modeler-timer-linting-win-x64.zip
