### ISSUE TITLE
Process ID Duplicated When Copying a Participant

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#3085]
### Describe the bug

When copying and pasting a participant after changing the _Process ID_ the `processRef` is re-used leading to a duplicated ID.

![Camunda_Modeler_ZTqQZ0sWFK](https://user-images.githubusercontent.com/7633572/183904712-56dbd2eb-c3c1-40a5-b3ab-c9a92bb46275.gif)

### Steps to reproduce

1. Create a participant
2. Change the _Process ID_
3. Copy participant
4. Paste participant
5. Process ID is duplicated

### Expected behavior

Process references are _not_ re-used.

### Environment

- Camunda Modeler Version: 5.2

**Comment by philippfromme** [comment]
This happens because we

1. Do not claim IDs assigned to model elements that aren't flow elements (`modeling.updateModdleProperties` doesn't take into account that property could be ID)
2. Copy IDs of model elements during copy and paste if they're not assigned

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js/issues/1708.
