### ISSUE TITLE
Release Camunda Modeler v5.3.0

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3098]
## What's inside?

_Code Freeze:_ 8th September 2022
_Release Date:_ 13th September 2022

[`v5.2.0...develop`](https://github.com/camunda/camunda-modeler/compare/v5.2.0...develop)

* Linting Annotations (cf. https://github.com/bpmn-io/internal-docs/issues/591)
* C8 Extension Properties (cf. https://github.com/bpmn-io/internal-docs/issues/627)
* Sticky headers (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/issues/726)
* Other Modeling Improvements (cf. https://github.com/bpmn-io/internal-docs/issues/607)

## Release Checklist

_To be done immediately after creating this issue._

* [x] put up code freeze appointment in calendar (include `modeling`, `qa`, `infra`, and `Team-Support`)
* [x] put up release appointment in calendar (include `modeling`, `DevRel` and Marketing [ `Christopher Rogers` ])
* [x] add Slack role to release manager (`@modeling-release-manager`)

_To be done before the code freeze._

* [x] inform QA about the release and its details so they can prepare for testing
* [x] Get in touch with the team (PM, UX and Engineering side), to clarify what topics will be included in the Release and their priority. Use this information to start preparing a concept for the *blog post* (see below) and *release info* (see below)
    * [x] (optional) if possible, already create feature branch to update [Release Info](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/version-info/ReleaseInfo.js) following our [guidelines](https://github.com/bpmn-io/internal-docs/tree/master/camunda-modeler#whats-new-communication) => cf. https://github.com/camunda/camunda-modeler/pull/3110

_To be done after code freeze to prepare and test the release._

* [x] make sure changes in upstream libraries are merged and released
    * `bpmn-js`, `dmn-js`, `*-properties-panel`, `*-moddle`, `camunda-bpmn-js`, `form-js`, `linting`, ...
* [x] make sure dependencies to upstream libraries are updated and can be installed (`rm -rf node_modules && npm i && npm run all` works)
* [x] close all issues which are solved by dependency updates
* [x] smoke test to verify all diagrams can be created
* [x] update [Release Info](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/version-info/ReleaseInfo.js)
    * [x] create a draft following [our guidelines](https://github.com/bpmn-io/internal-docs/tree/master/camunda-modeler#whats-new-communication) and based on priorities which were aligned with the team (PM, UX, and Engineering side)
   * [x] create PR to merge the draft into `develop`. Assign to PM, UX and Engineering for review => https://github.com/camunda/camunda-modeler/pull/3110
* [x] update [`CHANGELOG`](https://github.com/camunda/camunda-modeler/blob/develop/CHANGELOG.md) => https://github.com/camunda/camunda-modeler/pull/3121 
* [x] verify `develop` is up to date with `master`: `git checkout master && git pull && git checkout develop && git merge master`
* [x] merge to master: `git checkout master && git merge develop`
* [x] create release candidate (`npm run release`), cf. [release schema](https://github.com/bpmn-io/internal-docs/tree/master/release-schema); e.g `v1.0.0-rc.0`
    * [x] wait for [release build](https://github.com/camunda/camunda-modeler/actions/workflows/RELEASE.yml) to create the [artifacts](https://github.com/camunda/camunda-modeler/releases)
* [x] execute [integration test](https://github.com/camunda/camunda-modeler/blob/master/docs/.project/INTEGRATION_TEST.md) on [released artifacts](https://github.com/camunda/camunda-modeler/releases/tag/untagged-0a48aeb184699be75d5a)
    * [x] Works on Linux @marstamm 
    * [x] Works on Mac @pinussilvestrus 
    * [x] Works on Windows @philippfromme 
* [x] notify QA about the release so they can test it

_To be done to build the release after release testing completed._

* [x] create release (`npm run release`), cf. [release schema](https://github.com/bpmn-io/internal-docs/tree/master/release-schema)
    * [x] wait for [release build](https://github.com/camunda/camunda-modeler/actions/workflows/RELEASE.yml) to create the [artifacts](https://github.com/camunda/camunda-modeler/releases)

_To be done once the release is built._

* [x] publish release on [Github Releases](https://github.com/camunda/camunda-modeler/releases)
* [x] trigger mirroring of release to [Camunda Download Center](https://downloads.camunda.cloud/release/camunda-modeler/) via [Jenkins](https://ci.cambpm.camunda.cloud/job/sideprojects/job/camunda-modeler-desktop-RELEASE/build?delay=0sec) => https://ci.cambpm.camunda.cloud/job/sideprojects/job/camunda-modeler-desktop-RELEASE/71/
* [x] <del>write blog post for the [Camunda Blog](https://camunda.com/blog/)</del>
* [x] (if the Modeler UI appearance changed) update Camunda Modeler screenshots (and potentially text content) in the docs using [automation scripts](https://github.com/camunda/camunda-docs-modeler-screenshots)
  * https://github.com/camunda/camunda-docs-static/pull/289
  * https://github.com/camunda/camunda-docs-manual/pull/1291
  * https://github.com/camunda/camunda-platform-docs/pull/1244
* [x] send all information required to compile the [release notice email](https://github.com/bpmn-io/internal-docs/blob/master/camunda-modeler/README.md#release-notice-email) to the [`@product-release-presentation-dri` role](https://confluence.camunda.com/pages/viewpage.action?spaceKey=HAN&title=Release+Presentation+Process#ReleasePresentationProcess-OrganisingtheReleasePresentation)
  * => https://docs.google.com/document/d/19V-88plLbu3ZaVDxTWjhEJ_eUsQAWPo9tFrjcdcWxXU/edit 
* [x] request marketing to update the [downloads page](https://camunda.com/download/modeler/) via [request form](https://confluence.camunda.com/display/MAR/Change+request+to+Downloads+page) => https://app.asana.com/0/1149058359050441/1202961806243664
* [x] add new version to [update server releases](https://github.com/camunda/camunda-modeler-update-server/blob/master/releases.json) ==> https://github.com/camunda/camunda-modeler-update-server/pull/97

_To be done once release is publicly announced on release day._

* [x] publish release via update server (push to `live`)
* [x] close [current milestone](https://github.com/camunda/camunda-modeler/milestones)

**Comment by pinussilvestrus** [comment]
The release artifacts are building (cf. https://github.com/camunda/camunda-modeler/actions/runs/3014691473) ...

**Comment by pinussilvestrus** [comment]
### Issues during integration testing
* https://github.com/camunda/camunda-modeler/issues/3125 => not a regression
* https://github.com/camunda/camunda-modeler/pull/3124 ==> fix already delivered

**Comment by pinussilvestrus** [comment]
The final release artifacts are building (cf. https://github.com/camunda/camunda-modeler/actions/runs/3035452216)...

**Comment by pinussilvestrus** [comment]
All tasks are done, so let's call it a release! Download is already available: https://camunda.com/download/modeler/

Thanks all for helping 🎉

**Comment by marstamm** [comment]
> Created https://github.com/camunda/camunda-modeler/issues/3135.

Dang it, the description is not added  -.-
I'll check if I can find the problem
