### ISSUE TITLE
Generated task creates a business key field when adding one form field

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda-modeler#3102]
### Describe the bug

When creating a generated form for a user task and add one field, this field is created a business key field.

### Steps to reproduce

1. In a process model, create a user task.
2. Select generated form as implementation style
3. add a field and configure it properly
4. This field is now a business key field in the BPMN XML

### Expected behavior

When creating a form field in a generated form, every field is mapped to a process variable as long as I do not explicitely declare it as business key. In version 4.x, this was configurable with a dropdown.

### Environment

- OS: MacOS BigSur 11.6.8
- Camunda Modeler Version: 5.2.0
- Execution Platform: Camunda Platform Run 7.17.3
- Installed plug-ins: Token Simulation, Linter, Rename IDs, Transaction Boundaries, Property Infos, Tooltip

Hint: @mboskamp could reproduce the bug in the referenced ticket. If you doubt about plugins having side-effects, he should also provide information about his environment.

### Additional context

Please find the original bug report here: https://jira.camunda.com/browse/CAM-14816

I did not properly research before reporting, but the Platform 7 Engineering team found out.

Anyway, all required assets are also there.

**Comment by pinussilvestrus** [comment]
Mh, I thought we would have fixed that via https://github.com/camunda/camunda-modeler/issues/3050 in Camunda Modeler 5.2.0. I can also not reproduce that in this version when creating a form field

![image](https://user-images.githubusercontent.com/9433996/185638935-bec12144-ea9a-4db0-b1e8-e19204262ee0.png)

```xml
<bpmn:startEvent id="StartEvent_1">
  <bpmn:extensionElements>
    <camunda:formData>
      <camunda:formField id="aaaa" />
    </camunda:formData>
  </bpmn:extensionElements>
</bpmn:startEvent>
```

**Comment by pinussilvestrus** [comment]
The [support issue](https://jira.camunda.com/browse/CAM-14816) is not mentioning any Camunda Modeler version. Are you able to specify that?

**Comment by mboskamp** [comment]
I only reproduced the issue with 5.1.0. Did not try 5.2.0. @jonathanlukas maybe you could try if using 5.2.0 fixes the issue?

**Comment by jonathanlukas** [comment]
Hello @pinussilvestrus ,

I could not reproduce the bug any more using 5.2.0. I guess I used the old version before. Here is my test result:

```xml
   <bpmn:userTask id="Activity_1ayzm3z">
      <bpmn:extensionElements>
        <camunda:formData>
          <camunda:formField id="message" label="Message" type="string" />
        </camunda:formData>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_0wm4n5w</bpmn:incoming>
      <bpmn:outgoing>Flow_1kzxjso</bpmn:outgoing>
    </bpmn:userTask>
```

So I guess the ticket can be closed again.
