### ISSUE TITLE
Migrate to `npm@8`

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3106]
### What should we do?

As decided we migrate our code base, including this app [to `npm@8`](https://github.com/bpmn-io/internal-docs/issues/482).

### Why should we do it?

Ensure we have a smooth transition.

---

Requires https://github.com/bpmn-io/dmn-js-properties-panel/pull/46 to be merged, released, and integrated.

**Comment by barmac** [comment]
This escalated a bit because I need to release dmn-js-properties-panel which supports @bpmn-io/properties-panel@0.19.0. I tried to update dmn-js in the former project, but the tests start to fail 🤡 . Gotta figure this out.

**Comment by barmac** [comment]
The problem with dmn-js-properties-panel appears with dmn-js@12.2.0 and later.

**Comment by barmac** [comment]
I suspect that the tests broke with a fix for https://github.com/bpmn-io/dmn-js/issues/697, which was released as dmn-js@12.1.1

**Comment by barmac** [comment]
The fix was correct but our tests were not. See details in the linked PR.
