### ISSUE TITLE
A value that should be a FEEL expression is not handled correctly if the leading '=' is missing

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda-modeler#3111]
### Describe the bug

The problem occurs if a field is defined as mandatory feel expression but the value does not contain the leading '=':

```json
...
      {
        "label": "Result Variable",
        "description": "Name of variable to store the response data in.",
        "value": "response",
        "optional": true,
        "type": "String",
        "binding": {
          "type": "zeebe:output",
          "source": "= body"
        },
        "feel": "required"
      }
...
```

### Steps to reproduce

1. Create an element template according to the example above
2. apply it
3. the first letter of value will disappear, leaving everybody in confusion

### Expected behavior

If the value of a mandatory FEEL expression is missing the leading '=', it should automatically be added. 

This behaviour is not expected on optional FEEL expressions, as the '=' sign defines whether it is FEEL by default.

### Environment

- OS: MacOS BigSur 11.6.8
- Camunda Modeler Version: 5.2.0
- Execution Platform: Camunda 8
- Installed plug-ins: not relevant here

----

Depends on https://github.com/bpmn-io/properties-panel/issues/183.

**Comment by pinussilvestrus** [comment]
Thanks for reporting! I'm moving this to ready as it is a regression of one of the last releases. Feel feel to disagree and put it into backlog 👍 (/cc @marstamm @christian-konrad)

**Comment by nikku** [comment]
Let's leave this open. It is a valid user reported bug and will be closed as the upstream fix is incorporated.
