### ISSUE TITLE
Cannot Paste Sub-Process With Attacher

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#3125]
### Describe the bug

When pasting a sub-process with attacher, there's a rectangular area where pasting is not allowed for no apparent reason. 

![Camunda_Modeler_Mhulf3Lp2W](https://user-images.githubusercontent.com/7633572/189291796-6e85b6a6-e6d1-459a-aebc-91bc87cb1339.gif)

### Steps to reproduce

1. Create sub-process with attacher
2. Copy elements
3. Open a new tab
4. Activate paste
5. Paste is prevented in a rectangular area around the initial start event

### Expected behavior

Paste is not prevented.

### Environment

- Camunda Modeler Version: 5.3.0-rc.0, 5.2.0, 5.1.0, ...

**Comment by pinussilvestrus** [comment]
Can you maybe share your diagram? I can't reproduce it on my mac...

**Comment by philippfromme** [comment]
Diagram to reproduce:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:modeler="http://camunda.org/schema/modeler/1.0" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="Definitions_01p3jf9" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.3.0-rc.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.0.0" camunda:diagramRelationId="a0d0615c-3547-410d-a6d0-e0f5f7c190e8">
  <bpmn:process id="template-error-handling" name="Error Handling Example" isExecutable="true">
    <bpmn:subProcess id="Activity_1g84tgk" />
    <bpmn:boundaryEvent id="Event_1f7pviq" attachedToRef="Activity_1g84tgk" />
  </bpmn:process>
  <bpmn:error id="Error_0gyjhl0" name="ErrorInData" errorCode="ErrorInData" />
  <bpmn:error id="Error_0df5ic3" name="FailedToCreateRecord" errorCode="FailedToCreateRecord" />
  <bpmn:error id="Error_0u57r6m" name="ProblemProcessingData" errorCode="ProblemProcessingData" />
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="template-error-handling">
      <bpmndi:BPMNShape id="Activity_1g84tgk_di" bpmnElement="Activity_1g84tgk" isExpanded="true">
        <dc:Bounds x="160" y="80" width="350" height="200" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_084vzou_di" bpmnElement="Event_1f7pviq">
        <dc:Bounds x="492" y="262" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

**Comment by pinussilvestrus** [comment]
Thanks for the diagram! I was able to reproduce, also with older versions. Example: 5.0.0

![Kapture 2022-09-09 at 09 13 28](https://user-images.githubusercontent.com/9433996/189292908-19cbfe4d-e4ea-4d14-97b8-c381fe664285.gif)

**Comment by nikku** [comment]
Cannot reproduce anymore with Camunda Modeler v5.24.0:

![capture lyZthw_optimized](https://github.com/camunda/camunda-modeler/assets/58601/69b6eaca-78d4-43e1-a7c1-6046ee37d97d)
