### ISSUE TITLE
Integrate `@camunda/form-playground` into the Desktop Modeler

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#3126]
### What should we do?

Integrate the first version of [`@camunda/form-playground`](https://github.com/camunda/form-playground) into the Form Editor.

This includes

_Part 1_
* [x] Replace the existing form editor  
* [x] Add toggle to the status bar
* [x] Error Panel reduces Viewport Size instead of Overlapping
* [x] Persist toggle states across sessions (global layout)
* [x] Add keyboard shortcut to toggle between modes (`CTRL/CMD + P`, as we already have with BPMN/DMN Properties Panel and DMN Overview)

_Part 2_
* [x] #3247

_To consider as follow up_
* [ ] https://github.com/camunda/form-playground/issues/3
* [ ] Auto-collapse preview on minimal width (cf. https://github.com/bpmn-io/internal-docs/issues/617#issuecomment-1238428647)
* [ ] Persist input data across sessions (per file?)

### Why should we do it?

Integrate the new Forms Playground 🎉 
Child of https://github.com/bpmn-io/internal-docs/issues/527
Depends on https://github.com/bpmn-io/internal-docs/issues/617

**Comment by pinussilvestrus** [comment]
[fyi] After a chat with @christian-konrad and @marstamm we decided not to plan to finish this for the [5.4.0 Desktop Modeler release](https://github.com/camunda/camunda-modeler/issues/3135). Given the short time until the Code Freeze (approx. 1 working week for me) and the number of open tasks, we should not rush with this. 

@christian-konrad will inform PMM accordingly.

**Comment by pinussilvestrus** [comment]
> Persist toggle states across sessions

Is this something we want to persist globally in the `config.json`. Context: we do the same for any other UI component (properties panel, error panel, DMN overview, log)

![image](https://user-images.githubusercontent.com/9433996/192963091-77f71d73-d1f1-4cd2-b364-9ffcbab4387a.png)

My proposal would be, therefore, to keep it consistent and also keep the playground toggle states globally.

```json
{
  "layout": {
    "formEditor": {
      "form-preview": {
        "open": true
      },
      "form-input": {
        "open": true
      },
      "form-output": {
        "open": true
      }
    },
    "log": {
      "height": 130,
      "open": false
    },
    "panel": {
      "open": true,
      "tab": "linting"
    },
    "dmnOverview": {
      "open": true,
      "width": 350
    }
  }
}
```

/cc @christian-konrad

**Comment by nikku** [comment]
Yes! We want these UIs to persist across tabs. From the users point of view this is global (as long as applicable) layout state; I have not seen different behaviors (per tab layouts) in an app yet.

**Comment by pinussilvestrus** [comment]
> Add toggle to the status bar

Asking for some feedback: In the [Playground Demo](https://camunda-form-playground.netlify.app/), we placed the Design & Validate buttons in the center of the status bar. In the Desktop Modeler, I'm inclined to place them on the left side (status-bar__file ) because of the following reasons:
* It follows our current status bar UI architecture (left: file-related actions, right: app-related actions)
* VS Code also has no third (center) slot for those actions
* It fits other "mode" actions, e.g. JSON/XML

What do you think? /cc @Christian Konrad

![image](https://user-images.githubusercontent.com/9433996/193254927-b68092ad-ff87-4394-92f0-b736e139ac0d.png)

**Comment by nikku** [comment]
The problem I see with putting these things together is that design <-> validate are two clearly distinguishable modes, independent of other things we see in the UI. It does make sense to group them somehow (cf. @christian-konrad's [web modeler sketches](https://github.com/bpmn-io/internal-docs/issues/574))

**Comment by pinussilvestrus** [comment]
For comparison, that's how it would look like following the sketches, introducing a third status bar slot:

![image](https://user-images.githubusercontent.com/9433996/193264449-74c5fd4b-2b88-4416-bc91-46d40ed7cf20.png)

**Comment by nikku** [comment]
As suggested what about a dedicated "toggle switch": 

![image](https://user-images.githubusercontent.com/58601/193267352-8bd747ce-a00f-4945-b1eb-721265a369a2.png)

Then we can move that indicator anywhere.

**Comment by pinussilvestrus** [comment]
Sorry @nikku, apparently I had the [wrong sketches](https://docs.google.com/presentation/d/1OITvoqaRrYtfLoEBZT05Xy5aHFaIg--_bNhG6R5b1gA/edit#slide=id.g12d06793e71_0_0) in mind 😅 

This mode toggle looks pretty reasonable IMHO. @christian-konrad was there any reason why we moved away from that in Desktop Modeler sketches?

**Comment by pinussilvestrus** [comment]
More feedback coming [from slack ](https://camunda.slack.com/archives/GP70M0J6M/p1664535100529289).

![image](https://user-images.githubusercontent.com/9433996/193789627-7bb52f49-e596-4bfc-b0ff-85284b3ac9fc.png)

* @pinussilvestrus to double-check with @YanaSegal whether this direction fits our [Visual IDE architecture](https://miro.com/app/board/o9J_leTgMeo=/?moveToWidget=3074457351884237449&cot=14).  
* @nikku: If it is cheap let's add resizable panels. For users (cf. Web Modeler properties panel) not having things resizable "fit for purpose" is a big nuisance that I'd like to avoid.
* @nikku: Instead of going "full configurability" and "build things back" once we learned we can also build two clearly distinguishable modes and learn from there. We have these two options.
* @christian-konrad: It looks like the inner padding of icon and text is different from those of the error toggle-is it right or is it because the icons are larger (missing padding in the png itself)?

**Comment by pinussilvestrus** [comment]
> * @nikku: If it is cheap let's add resizable panels. For users (cf. Web Modeler properties panel) not having things resizable "fit for purpose" is a big nuisance that I'd like to avoid.

I can double-check this. It should be relatively easy to add this for the `@camunda/form-playground` panels™️. However, I remember we had some difficulties in the past when we wanted to make the error panel resizable (cf. https://github.com/camunda/camunda-modeler/pull/2967). 

These issues could probably re-appear once we make the playground data panels resizable.

**Comment by pinussilvestrus** [comment]
I created [an issue](https://github.com/camunda/form-playground/issues/3) for the resizable playground components + had a small look at this via https://github.com/camunda/form-playground/tree/3-resizable-container. I won't be able to follow up this week. 

It's possible but not trivial. Reason: Compared to the rather simple properties panel resizer in BPMN & DMN, we now have three more resize options. Given the things we already discovered during https://github.com/camunda/camunda-modeler/pull/2967, we need to handle the full resize story properly. 

![Unbenannt-2021-11-18-0826](https://user-images.githubusercontent.com/9433996/193841935-04a03672-4e79-4bb0-b798-5d583cc9a05f.png)

Otherwise, we will end up with bad UX I believe. Example: The input data container can't be resized anymore, as other bottom containers already use too much space. 

What I could imagine, is to introduce horizontal resizability as a good first step (properties panel, form preview).

**Comment by christian-konrad** [comment]
@pinussilvestrus I assume resizability of the preview and editor does not add value; I try to ask myself when do I want to resize them so the one is larger than the other? Thinking about the future, when we also have horizontal layouts (very likely flexboxes) and those may also wrap on smaller screens, then it may be hard to correlate the left to the right view in case the left shows wrapped components, while the other doesn't (depending on the wrap breakpoints).  @YanaSegal would you see value in independently resizable editor+preview?

I assume vertical resizability is more helpful, to resize the mock input/output panels. To do so, we need to decide if resizing does result in absolute or relative sizes, which is important when you collapse the error/log panels: should then both editor and form input panel resize, or one is sticky and the other resizes?

**Comment by pinussilvestrus** [comment]
Closed by accident, some things are still open (tracking, docs)
