### ISSUE TITLE
Error overlay does not open up the properties panel on single click

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3127]
### Describe the bug

When we try to click on the error overlay and open up the properties panel it is not possible  with a single click rather we need to click twice to achieve the output.

### Steps to reproduce

1. Create a BPMN diagram with Camunda Platform 8
2.  Create any two tasks that would produce lint error
3. Now try to traverse between the lint error overlay of the tasks we could see sometimes on a single click the properties panel is open and the respective error is highlighted while sometimes it needs a double click on the overlay.

https://user-images.githubusercontent.com/85225325/189343200-5ff09fd4-ccdd-4de0-aa1b-8d23d2d5b4a7.mp4

### Expected behavior

On clicking the error overlay once the properties panel should be open

### Environment

- OS: [ Windows 10]
- Camunda Modeler Version: [5.3.0]
- Execution Platform: [ Camunda Cloud]

**Comment by philippfromme** [comment]
I spent some time looking into this issue. I cannot reproduce it in https://github.com/philippfromme/linting-playground. The issue occurs only when clicking an overlay focuses a text input in the properties panel. The next click after that doesn't do anything for some reason. I'll need more time to look into this.
