### ISSUE TITLE
Cannot upgrade template from empty one to another one

### ISSUE THREAD

**Issue by CatalinaMoisuc** [camunda/camunda-modeler#3140]
### Describe the bug

When I apply an empty template to a task

And then change the empty template to match this template: https://github.com/francav/hey-duedate/blob/c8-connector/c8-connector/element-templates/template-connector.json and upgrade

Then I get an error and the template is not correctly applied and the icon is not visible:
![Screenshot 2022-09-15 at 17 19 44](https://user-images.githubusercontent.com/25924333/190445594-9eaa57a4-5f69-4d9a-91a0-edee03ef9349.png)

The issue was originally opened for the Web Modeler:
https://github.com/camunda/web-modeler/issues/2376

### Steps to reproduce

1. Create an empty template (see empty template in attachment)
2. Create a new BPMN file
3. Add a new task, apply the empty template to it (see empty template in attachment)
4. Replace the empty template with this one: https://github.com/francav/hey-duedate/blob/c8-connector/c8-connector/element-templates/template-connector.json (see non-empty template in attachment)
5. Go back to the BPMN file from 2.
6. Select the task and choose upgrade the template in the Properties Panel to apply the new non-empty template
7. The template is not upgraded correctly, the icon is missing and I also get this error in console:
```
unhandled error in event listener Error: unknown binding <property> for element <Activity_1xdyi2h>, this should never happen
    at QA (index.esm.js:17840:10)
    at NA (index.esm.js:17668:9)
    at index.esm.js:18711:41
    at Array.forEach (<anonymous>)
    at UA._applyConditions (index.esm.js:18711:21)
    at UA.<anonymous> (CommandInterceptor.js:43:15)
    at EventBus.js:519:13
    at o._invokeListener (EventBus.js:371:19)
    at o._invokeListeners (EventBus.js:352:24)
    at o.fire (EventBus.js:313:24)
    at i._fire (CommandStack.js:356:29)
    at i._internalExecute (CommandStack.js:425:10)
    at i.execute (CommandStack.js:153:8)
    at Ki.updateProperties (Modeling.js:98:22)
    at LA._updateZeebeModelerTemplate (index.esm.js:17978:14)
    at LA.preExecute (index.esm.js:17930:10)
    at i._internalExecute (CommandStack.js:401:15)
    at i.execute (CommandStack.js:153:8)
    at WA.applyTemplate (index.esm.js:19140:24)
    at up (index.esm.js:19708:27)
    at action (index.esm.js:20284:19)
    at p (index.esm.js:858:5)
    at Object.onClick [as clickfalse] (index.esm.js:892:25)
    at HTMLButtonElement.B (preact.module.js:1:4348)
    at HTMLButtonElement.i (helpers.js:85:17)
```

#### Attachment
[example-templates.zip](https://github.com/camunda/camunda-modeler/files/9577031/example-templates.zip)

### Expected behavior

The template can be upgraded correctly.

### Environment

- OS: not relevant
- Camunda Modeler Version: 5.3.0
- Execution Platform: not relevant
- Installed plug-ins: not relevant

**Comment by nikku** [comment]
The error says:

> `unknown binding <property>`

And indeed the template contains a binding `property` which is not supported in Camunda 8 element templates:

![image](https://user-images.githubusercontent.com/58601/190462978-e44876eb-1c5b-4c2d-bdcb-d623ca980f0e.png)

**Comment by nikku** [comment]
My assumption would be however that we do reject such templates in the first place (do not allow to choose them, as they fail validation on load). Need to investigate this.

**Comment by nikku** [comment]
Correction: We do support `property` (for name binding). I'm continuing to investigate.

**Comment by marstamm** [comment]
Everything works as expected in the handling of the property and we throw this error incorrectly. As a result, the modeler breaks because of the unhandled error.

**Root cause**

When a `property` binding does not have a default value and is not set, we don't change the XML and don't execute a command:

https://github.com/bpmn-io/bpmn-js-properties-panel/blob/9017ba5ec60df7341a88fd575f88bc058e7dbb2d/src/provider/cloud-element-templates/util/propertyUtil.js#L224-L233

However, we later use the commands array to check if the property was handled:

https://github.com/bpmn-io/bpmn-js-properties-panel/blob/9017ba5ec60df7341a88fd575f88bc058e7dbb2d/src/provider/cloud-element-templates/util/propertyUtil.js#L406-L416

As we don't guarantee to create commands while handling a property, we need a more explicit check before throwing the error.

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/763.
