### ISSUE TITLE
Be able to provide custom lint rules

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3145]
### Problem you would like to solve

With Camunda Modeler `<= 5.2` there exists the [camunda-modeler-linter-plugin](https://github.com/camunda/camunda-modeler-linter-plugin). It allowed me to validate my diagrams against the best practice lint rules established by [bpmnlint](https://github.com/bpmn-io/bpmnlint), but also to [provide custom rule sets](https://github.com/camunda/camunda-modeler-linter-plugin#overriding-provided-rules).

With `>= 5.3` of the app we ship with our own visual lint integration + error panel, because of that the old linter plug-in is [rendered obsolete](https://github.com/camunda/camunda-modeler-linter-plugin/issues/28). At the same time the use-case (recommended lint rules + plugability) remains.

### Proposed solution

* [x] Quick fix: Document deprecation
* [x] Deprecate [camunda-modeler-linter-plugin](https://github.com/camunda/camunda-modeler-linter-plugin) for Camunda Modeler `>= 5.3` (https://github.com/camunda/camunda-modeler-linter-plugin/issues/28, https://github.com/camunda/camunda-modeler-linter-plugin/issues/29)
* [x] Add ability to provide custom lint rules through Camunda Modeler plug-in
  * [x] https://github.com/camunda/linting/pull/20
  * [x] https://github.com/camunda/camunda-modeler/pull/3153
* [x] Extend error panel + canvas to show warnings, too (https://github.com/camunda/camunda-modeler/issues/3200)
* [x] Serialize disabled lint rules via with configuration (https://github.com/bpmn-io/bpmnlint/pull/90)
* [x] Update [custom linter rules plug-in](https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin) to Modeler 5.3+ (https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin/pull/24)
* [x] Document migration from [camunda-modeler-linter-plugin](https://github.com/camunda/camunda-modeler-linter-plugin) to using Camunda Modeler 5.3 with custom lint rules
* [x] #3269

### Follow-ups

* provide [recommended lint rules](https://github.com/bpmn-io/bpmnlint/tree/master/rules) as ready-to-use plugin (https://github.com/bpmn-io/internal-docs/issues/657)

### Additional context

See [board](https://miro.com/app/board/uXjVPW7Ui3A=/) for initial collection of ideas.

**Comment by philippfromme** [comment]
@nikku @camunda/modeling-dev I wasn't able to finish this topic before my holiday. Feel free to take over if necessary.

Remaining steps:

* deprecate old plugin (cf. https://github.com/camunda/camunda-modeler-linter-plugin/issues/29#issuecomment-1262764353)
* support lint warnings in Camunda Modeler
* document everyting

**Comment by philippfromme** [comment]
@nikku Since you added _Document usage of plug-ins to add custom lint rules_ where would you think is the appropriate place for this documentation? The Camunda docs?

**Comment by barmac** [comment]
I'd say the right place for this would be the Desktop Modeler documentation. It could be a separate section at https://docs.camunda.io/docs/components/modeler/desktop-modeler/plugins/ or even a new page in the "Additional configuration" part.

**Comment by nikku** [comment]
As @barmac suggested this should be featured on the [desktop modeler docs]([https://docs.camunda.io/docs/components/modeler/desktop-modeler](https://docs.camunda.io/docs/components/modeler/desktop-modeler/plugins/)).

**Comment by philippfromme** [comment]
Okay, will create a pull request. 🚀

**Comment by nikku** [comment]
I believe we can close this @philippfromme?

**Comment by philippfromme** [comment]
Yes, the documentation was finally merged! 👍🏻
