### ISSUE TITLE
Show version that enables the feature if not supported in currently selected version

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda-modeler#3148]
### Problem you would like to solve

When using properties that are not supported in the currently selected platform version (e.g. Camunda Platform 8.0), the only statements I get from error messages is that the field is not supported (by Camunda 8):

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/81753891/191701543-bebb1951-e02f-4618-90c7-057ba4685a2b.png">
### Proposed solution

I would like to see the version which makes the desired property available, if available. The error message should clearly state the minimum target that supports the feature:

```
[...] is only supported by Camunda Platform 8.1 or newer
```

In case we don't know yet when to support it, it should show:  
```
[...] is not supported by <Platform version>
```

This gives me as a user some insight on the evolution of the capabilities I have available to design and enhance my process.

Also, marking properties that are not available in the current version would help to sort out quickly what I can actually do.

### Alternatives considered

As an alternative, not available options could be filtered out.

Pro: Cleaner working environment

Con: No awareness of features in newer versions.

### Additional context

With regards to the evolution of Camunda 8, it would make sense to raise awareness of feature evolution and not leaving a user with a simple "Not supported" which is frustrating.

**Comment by marstamm** [comment]
Makes sense to have a clear message around "how to fix the error". In this case, it would be "upgrade to newer version". 

I will move this to the backlog. Thank you for reporting!

**Comment by nikku** [comment]
CC @christian-konrad We'll not immediately follow up on this.

**Comment by nikku** [comment]
Options for messaging to consider:

* Dedicated `Supported in Camunda Platform >= 8.1` appendix.
* `[...] is supported from Camunda Platform >= 8.1 only`

**Comment by christian-konrad** [comment]
Frameworks, IDEs etc. show things like

` is only available in iOS 13 or newer`

so what about

 `[...] is only supported by Camunda Platform 8.1 or newer`

**Comment by nikku** [comment]
Perfect. Let's take that one.

**Comment by nikku** [comment]
Moving to ready. If there is capacity, let's act on it soon, otherwise Wintersweep candidate.

**Comment by christian-konrad** [comment]
Based on discussions in https://github.com/bpmn-io/internal-docs/issues/644, we should differentiate between two situations/type of messages:

- A supported version is already released or known: `A <ElementType> is only supported by Camunda Platform 8.1 or newer`
- We don't know yet when to support it:  `A <ElementType> is not supported by <Platform version>`

@philippfromme

**Comment by philippfromme** [comment]
> Based on discussions in [bpmn-io/internal-docs#644](https://github.com/bpmn-io/internal-docs/issues/644), we should differentiate between two situations/type of messages:
> 
> * A supported version is already released or known: `A <ElementType> is only supported by Camunda Platform 8.1 or newer`
> * We don't know yet when to support it:  `A <ElementType> is not supported by <Platform version>`
> 
> @philippfromme

This is what I intend to implement. Either the user can choose a different execution platform version that will fix the error (_supported by Camunda X or newer_) or there is no execution platform version that would fix the error (_not supported by Camunda X).
