### ISSUE TITLE
Support `zeebe:candidateUsers` Property Supported by Camunda Platform 8.2

### ISSUE THREAD

**Issue by lzgabel** [camunda/camunda-modeler#3151]
### Problem you would like to solve

I want to be able to define the candidateUsers attributes of the assignment definition of a user task from the camunda-modeler.

### Proposed solution

None

### Alternatives considered

None

### Additional context

Related Zeebe PR: [10459](https://github.com/camunda/zeebe/pull/10459)
Related Modeler Issue: [2535](https://github.com/camunda/camunda-modeler/issues/2535)

* candidate users are defined as a string containing a comma-separated list of values (e.g. x,y,z), or a Zeebe-formatted FEEL expression (i.e. prefixed by = ) where the expression should evaluate to a list of strings.

##### Example

```xml
<!-- A user task can have an candidateUsers, specified as static value -->
<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
   <zeebe:assignmentDefinition candidateUsers="saruman,gandalf" />
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
 
<!-- A user task can have an candidateUsers, specified as expression -->
<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
  <!--
     expression produces bracket formatted list which differs from static value
     example expression evaluates to: ["saruman", "gandalf"]
   -->
   <zeebe:assignmentDefinition candidateUsers="= wizards" />
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
 
 
<!-- A user task can have an assignee, candidateGroups and candidateUsers simultaneously -->
<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
  <zeebe:assignmentDefinition
      assignee="= ring.bearer" 
      candidateUsers="saruman, gandalf"
      candidateGroups="elves, men, dwarfs, hobbits" />
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
```

Issue tracking
---
* [x] https://github.com/camunda/zeebe-bpmn-moddle/issues/37
* [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/774

**Comment by marstamm** [comment]
Hi @lzgabel ,

thank you for opening the issues and contributing code for it. The feature makes sense, as it is in the BPMN spec. 
However, as zeebe does not support his feature (yet), we will keep these changes the backlog until we know when the changes in Zeebe will be merged.

Thank you <3

**Comment by philippfromme** [comment]
This feature has just landed in the Camunda Modeler and will be released soon (cf. https://github.com/camunda/camunda-modeler/pull/3302).
