### ISSUE TITLE
Properties Panel for CMMN?

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#316]
with the 1.0 release of the modeler, is CMMN tabs supposed to have a Properties Panel?

**Comment by nikku** [comment]
Nope. We plan to add the properties panel with a later release.

**Comment by StephenOTT** [comment]
@nikku. Thanks. Was not sure of it was broken. :). Side question: are you supposed to be able to draw flow lines between symbols in the current release?  They are in the pic on the blog talking about the releases, but does not seem to be available in the UI.

**Comment by nikku** [comment]
Nope, you are not supposed to do that (yet). We will provide that as part of [CMMN full modeling support](https://github.com/bpmn-io/cmmn-js/milestones/C02%20-%20Full%20CMMN%20Modeling%20Support) plus its integration into the modeler.

**Comment by StephenOTT** [comment]
@nikku thats for the quick followup!
