### ISSUE TITLE
Interrupting timer start event should not have time cycle

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3181]
### Describe the bug

We currently allow to set time cycle on an interrupting timer start event within an event subprocess. This is incorrect and a deployment with such an event is rejected by Zeebe.

![image](https://user-images.githubusercontent.com/28307541/192967256-c00be46d-4aa9-4387-92e3-de45fbcb8839.png)

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Expected behavior

Interrupting timer start event should have only time date.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: C8
- Installed plug-ins: [...]

### Additional context

No need to change anything in C7.

----

Raised via [SUPPORT-14530](https://jira.camunda.com/browse/SUPPORT-14530)

**Comment by MaxTru** [comment]
Raised here: https://jira.camunda.com/browse/SUPPORT-14530

**Comment by barmac** [comment]
I am working on this.

**Comment by barmac** [comment]
This will be fixed via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/802

**Comment by philippfromme** [comment]
Closed by https://github.com/camunda/camunda-modeler/pull/3248.
