### ISSUE TITLE
Request: Left-Hand Shortcut key for activating Lasso

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#320]
The current shortcut for the lasso is `L`.  The problem with his is your have to take your hand off the mouse or move your left hand across the keyboard.  The other shortcuts (`S, C, E`) are all easy reach of Left hand.  But the `L` is too far.  The Hand tool is automatically activated with the mouse selection of whitespace, and the ability to quickly activate the lasso would be highly useful.

Suggestion: have a combination of keys such a `command+shift`, `Alt+shift` etc, or select another key on the left side of keyboard to represent Lasso.

**Comment by nikku** [comment]
You can `SHIFT+Drag` to draw the lasso, too. I think that would suite your use-case better.
