### ISSUE TITLE
Support Lint Warnings

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#3200]
As a follow-up to https://github.com/camunda/camunda-modeler/pull/3153 we need to support lint warnings in the Camunda Modeler. Right now all lint results show up as errors. The category is ignored.

In order to support warnings we need to:

* [x] show number of warnings in linting toggle
* [x] show warnings as such in the error panel
* [x] show warnings as such on the canvas
* [x] rename the "Errors" panel to "Problems" to support both Errors and Warnings

We might want to get a designer involved in regards to color and icon.

# Sketch

![Group 12](https://user-images.githubusercontent.com/7633572/193129960-9e369ea8-24fb-4505-9ed0-806b1d2670dc.png)

---

Related to https://github.com/camunda/camunda-modeler/pull/3153

**Comment by YanaSegal** [comment]
link to figma:
https://www.figma.com/file/3vfmNJXiOhVudCAK3DbV4p/Untitled?node-id=1%3A2

Designs:
![No Problem](https://user-images.githubusercontent.com/110401507/196991382-3cc713df-b5bf-4fe5-a205-904888e408e7.png)
![warnings](https://user-images.githubusercontent.com/110401507/196991386-7b612cfd-977d-4cff-9a05-aa2bcae14879.png)
![hover](https://user-images.githubusercontent.com/110401507/196991389-e6990ab6-9790-4894-a5c3-882dbf620da8.png)
![hover-1](https://user-images.githubusercontent.com/110401507/196991390-32ca1add-7466-4787-bb2c-0b28d353a424.png)

Notes:
- the 2 icons at the footer will be one single button
- the red and yellow colors and the warning icon are carbon elements
- we removed the error/warning next to each line in the problems panel. however, for accessibility, we need to add a tooltip to the respective symbols.

cc: @christian-konrad , @nithinssabu
