### ISSUE TITLE
FEEL help missing

### ISSUE THREAD

**Issue by toco-cam** [camunda/camunda-modeler#3201]
### Problem you would like to solve

Learn FEEL

### Proposed solution

Links from the modeler to docs

### Alternatives considered

Search directly in docs

**Comment by nikku** [comment]
The simplest thing we could do is to add the FEEL reference to the help menu. Is that correct? 

![capture NZBuse_optimized](https://user-images.githubusercontent.com/58601/193241822-22a0871d-548a-4151-87e4-8e7bbd65e3ac.gif)

**Comment by barmac** [comment]
+1, we could link this: https://docs.camunda.io/docs/components/modeler/feel/what-is-feel/

**Comment by nikku** [comment]
Moving to backlog and marked as `spring cleaning`. I believe at least the reference linked is an easy one to pick up.
