### ISSUE TITLE
Remember properties panel sections toggle state

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3213]
### Problem you would like to solve

As a user I'm regularily frustrated by the properties panel groups behavior: It does not remember the existing toggle state, thus making it impossible to perform maintenance tasks in an efficient manner. Whenever I switch to a different tab (or sometimes even element) the view is gone and I have to restore it with many button clicks: 

![capture YejKLO_optimized](https://user-images.githubusercontent.com/58601/193832030-c23ba5c3-f5d5-42b6-91d2-ddb8ddd52f92.gif)

### Proposed solution

Assuming that I as a user switch between contexts in order to _compare_ or _copy/paste_:

* [ ] Ensure that properties panel open state is persisted _across_ diagrams.
* [ ] View is restored on a best effort basis; if a section opened does not exist, open it
* [ ] Scroll position is restored on a best effort basis (i.e. open sections) 

### Alternatives considered

None.

### Additional context

We already treat other parts of the editor state such as properties panel width as global state; we plan to do the same for the form playground.

**Comment by pinussilvestrus** [comment]
This is related to: https://github.com/camunda/camunda-modeler/issues/2638

We had some investigations around this in a previous spring cleaning (cf. https://github.com/camunda/camunda-modeler/issues/2638#issuecomment-1015292428). I would love to see this picked up again 🙂

**Comment by nikku** [comment]
Actually a duplicate :slightly_frowning_face:. Closing again.

**Comment by nikku** [comment]
Updated https://github.com/camunda/camunda-modeler/issues/2638 so it continues to live long and prosper!
