### ISSUE TITLE
Holding the Enter key in diagram-js freezes the window

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3214]
### Describe the bug

When I add rows by pressing "Enter", and I keep it pressed, the window freezes for a bit and then adds all Rows at once

![Recording 2022-10-04 at 16 35 33](https://user-images.githubusercontent.com/21984219/193848101-445352bc-f0d3-4e83-a5a9-b7163dac96c4.gif)

### Steps to reproduce

1. Open a dmn-js decision table
2. Enter the last row
3. Hold Enter key
4. Release it after a while

### Expected behavior

The rows are added one-by-one as I hold the key.

### Environment

 * Version: 5.4.0-rc.1
 * Operating System: Linux x86_64 amd64 (Ubunru 20.04)
 * Plugins: <no plugins>
 * Execution Platform: DMN - Camunda Platform 8

### Additional context

I can reproduce it on https://demo.bpmn.io/dmn/new , but it only starts to lag after ~60 Rows were added, so this seems to be  performance related

Alternative to consider:

- Don't do anything, adding rows like this probably has limited use-cases
- Get a better laptop

**Comment by nikku** [comment]
> Get a better laptop

Go for it! :heart:

**Comment by nikku** [comment]
If you agree I'm inclined to close this issue. Seems like a super edge case. We could of course throttle the rate at which we listen to ENTER, but I've not seen this in any tool.

Is that the issue?

**Comment by marstamm** [comment]
Agreed, it is an edge case and throttling `Enter` would be weird
