### ISSUE TITLE
Suggestions and explanation text for FEEL expressions seems to be cut-off from the windows

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3216]
### Describe the bug

When we have a longer suggestion for the text entered in the Feel Expression field we could see that it is cut off from the windows.

### Steps to reproduce

1. Create a BPMN task/event 
2. Try to enter a text say "b" here in any of the field for FEEL expression
3. We could see that the suggestion for the text entered is so long and it gets cut off from the windows.

https://user-images.githubusercontent.com/85225325/194263817-b49a6c84-b764-4115-8468-a4fbced1e972.mp4

5. This issue also occurs as we move down the properties panel and even though the list of suggestions is not as long enough.

https://user-images.githubusercontent.com/85225325/194265945-6f9e423f-9f2a-42cd-9fa2-e6d32b58ddfa.mp4

### Expected behavior

If the suggestion is long or the field is at the end of the page the suggestion should be not cut off from the windows 

### Environment

- OS: [ Windows 10]
- Camunda Modeler Version: [5.4.0]
- Execution Platform: [ Camunda Cloud]

**Comment by barmac** [comment]
Thanks for creating the issue. I can reproduce it in 5.4.2

**Comment by marstamm** [comment]
While we also do not configure it correctly, it seems that the positioning for hints is broken in Codemirror: 
https://github.com/codemirror/dev/issues/991

**Comment by marstamm** [comment]
Moving to Backlog until we get a reply from CM
