### ISSUE TITLE
Naming difference in the form elements static option value 

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3220]
### Describe the bug

When you add a static option for the very first time for a form element we could see that the naming is used as "value" and when we delete and add it again it is named as "value1"

### Steps to reproduce

1. create/Add a form element say checklist
2. Click on the "create" button  static options in the properties panel
3. We could see that the naming of the created option is called "value"
4. Delete and re-create the static option 
5. we could see now the naming is value1 

https://user-images.githubusercontent.com/85225325/194304225-10eba532-7954-4d3a-aedf-506af6a5ba44.mp4

### Expected behavior

Align the naming between first time creation and the later ones

### Environment

- OS: [Windows 10]
- Camunda Modeler Version: [5.4.0]
- Execution Platform: [ Camunda Cloud]

**Comment by pinussilvestrus** [comment]
The [default value of the `checklist` field](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-viewer/src/render/components/form-fields/Checklist.js#L90) differs from the [default when creating new values](https://github.com/bpmn-io/form-js/blob/1e89b2d67898d6839ddf4312b561c1797c4d161e/packages/form-js-editor/src/features/properties-panel/entries/StaticValuesSourceEntry.js#L23).

Looks like a nice spring cleaning topic 🙂

**Comment by Alcadeus0** [comment]
Sure, will do!

**Comment by philippfromme** [comment]
Closed by https://github.com/camunda/camunda-modeler/pull/3248.
