### ISSUE TITLE
Can't deploy to C8 SaaS

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3223]
### Describe the bug

I can't deploy to C8 SaaS

![Recording 2022-10-07 at 13 46 26](https://user-images.githubusercontent.com/21984219/194545947-3e639b54-60ce-4b7b-9eab-935ecd2027c5.gif)

### Steps to reproduce

1. Create a C8 diagram
2. deploy it to saas
3. It fails 

### Expected behavior

I can deploy to SaaS

## Camunda Modeler system information
 * Version: 5.4.0-rc.1
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform 8

### Additional context

zeebe-node has breaking changes in a minor update:
![image](https://user-images.githubusercontent.com/21984219/194546067-c6d67317-ddac-4c47-b51f-85c1b9adbedf.png)

**Comment by nikku** [comment]
My appologies for blindly bumping zeebe-node. :see_no_evil: 

Let's revert to 8.0.x to fix this.

**Comment by marstamm** [comment]
I'll invest 30 minutes to see if we can use non-deprecated API. If this does not work, we can revert and re-release

**Comment by marstamm** [comment]
closed via https://github.com/camunda/camunda-modeler/pull/3224
