### ISSUE TITLE
Camunda 8 linting should allow Undefined Tasks

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda-modeler#3230]
### Problem you would like to solve

Once https://github.com/camunda/zeebe/issues/10562 has been merged Zeebe supports Undefined Tasks. Currently it is not possible to deploy a process with an Undefined Task in the modeler:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/5787702/195054722-b9d1910e-3381-465c-a560-a40d16f1be50.png">
The linting needs to be changed to allow these tasks.

### Proposed solution

* [ ] Create a dedicated Camunda 8.2 profile.
* [ ] Remove Undefined Tasks from the [unsupported element validation for Camunda 8.2](https://github.com/camunda/bpmnlint-plugin-camunda-compat/blob/main/rules/element-type/config.js#L120). 

### Alternatives considered

None

### Additional context

This change in Zeebe will be part of the next minor release (8.2.0)

**Comment by nikku** [comment]
That is a great contribution for our users! 

To be clarified: Naming (abstract vs. undefined) - https://github.com/camunda/zeebe/issues/10562#issuecomment-1274433564.

**Comment by nikku** [comment]
Agreed to call it `Undefined Task`: https://github.com/camunda/zeebe/issues/10562#issuecomment-1275683681

**Comment by nikku** [comment]
Landed in Zeebe (https://github.com/camunda/zeebe/issues/10562#event-7579410412). We're good to pick this up.

**Comment by marstamm** [comment]
After https://github.com/camunda/camunda-modeler/issues/3148, introducing this lint rule now would result in the error message "An <Undefined Task> is only supported by Camunda Platform 8.2 or newer", but no option to select this version.

I suggest we delay the implementation until we introduce 8.2 as a target execution platform.

/cc @christian-konrad @CatalinaMoisuc

**Comment by marstamm** [comment]
AFAIK, we did not included pre-release versions as selectable targets in the past and just went with 1️⃣

**Comment by felix-mueller** [comment]
> AFAIK, we did not included pre-release versions as selectable targets in the past and just went with 1️⃣

FYI @HanselIdes sth. we chatted about recently, maybe we need to consider for onboarding to change?

**Comment by HanselIdes** [comment]
After the next alpha release, we'll test an experiment where trial users get alpha clusters instead of stable clusters. I'll drive towards users adopting our monthly releases rather than waiting up to 6 months for the minor release, so 2️⃣ will be preferably around EOY

**Comment by christian-konrad** [comment]
Let's allow selection of alphas for linting as an accelerator. Two things:
- Per default, the latest stable is preselected
- The alphas are clearly labeled as alphas
    - There must be a way for users to educate themselves easily what the alpha means, and why there's no stable yet, and how they benefit from alphas
    - (One way to solve this could be to introduce a changelog tool in Modeler, like Beamer or Appcues Announcements, or just link to a page with additional info)
- With the new onboarding Modeler urls / process templates, we should be able to control the linting target (i.e. we want to showcase recent features from latest alpha, so it must be selected for this particular template)

I will create an epic for that (covering both Web+Desktop Modeler, with priority for Web).

@HanselIdes @CatalinaMoisuc

**Comment by christian-konrad** [comment]
@CatalinaMoisuc yes, exactly, to prevent us from building it twice

**Comment by marstamm** [comment]
@christian-konrad @CatalinaMoisuc

What impact does this decision have in the desktop modeler? We already added the 8.2/7.19 platform as selectable targets (cf. https://github.com/camunda/camunda-modeler/pull/3286)

**Comment by nikku** [comment]
We've already built this and I don't understand the need to unbuild it. What is blocking us to ship this?

**Comment by marstamm** [comment]
**Decision**
- We will keep 8.2 as target platform 
- as a potential follow-up, we can add an `alpha` tag to the selection
- Web modeler wants to introduce `latest` option, but this does not block us with our current approach

**Comment by marstamm** [comment]
Undefined task linting is included with 1d0c47f0ca98e69dbf4fe810c80fde0481022908 and alphas are tagged as such with https://github.com/camunda/camunda-modeler/issues/3301 .
