### ISSUE TITLE
Copy and paste a non-template activity with an default template results in loosing all properties

### ISSUE THREAD

**Issue by Xembalo** [camunda/camunda-modeler#3235]
### Describe the bug

I'm using Modeler with global templates in cawemo. e.g. for call activities. (template attached below). The template is marked as default for call activities. 

But of course there is always the exception to the rule. So I have removed the default template of a call activity via "unlink" and added data/properties.

If I now copy and paste the activity (Ctrl C + V), the modeler sets the default template again.

This is debatable, but the problem is that it also clears all relevant properties, even if they are included in the default template.

``` 
{
  "$schema": "https://unpkg.com/@camunda/element-templates-json-schema@0.10.0/resources/schema.json",
  "name": "Subprozess",
  "description": "Aufruf eines Subprozesses mit Weitergabe der Variablen und des BusinessKeys",
  "id": "20b5a934-dc51-4b24-911b-083998e84adf",
  "appliesTo": [
    "bpmn:CallActivity"
  ],
  "isDefault": true,
  "properties": [
    {
      "label": "Subprozess",
      "type": "String",
      "editable": true,
      "value": "",
      "binding": {
        "type": "property",
        "name": "calledElement"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "Input all",
      "type": "Hidden",
      "binding": {
        "type": "camunda:in",
        "variables": "all"
      }
    },
    {
      "type": "Hidden",
      "value": "${ execution.processBusinessKey }",
      "binding": {
        "type": "camunda:in:businessKey"
      }
    }
  ]
}
```

### Steps to reproduce

1. create template above and make modeler recognize it
2. create new bpmn and create a call activity and add sub process name

![grafik](https://user-images.githubusercontent.com/21131605/195370483-c391fee4-0c01-4430-844f-8a0b33ace1c8.png)

3. unlink activity, properties are still there

![grafik](https://user-images.githubusercontent.com/21131605/195370764-53068e41-27cb-4d4b-b968-f634fa7c9881.png)

4. copy & paste this activity, sub process name in the new activity has gone away

![grafik](https://user-images.githubusercontent.com/21131605/195370993-2a73bfce-53fe-44a0-95f2-853c2f80b3c2.png)

### Expected behavior

Configuration of an activity "survive" copy and paste ;-)

### Environment

- OS: Windows 10
- Camunda Modeler Version: 5.4.1 and 5.3
- Execution Platform: Camunda Platform
- Installed plug-ins: Cloud Connect

### Additional context

It is very annoying because we work a lot with standard external tasks and constantly lose the settings

----

Also tracked by SUPPORT-15859

**Comment by barmac** [comment]
I can reproduce it. Thanks for the report.

**Comment by Xembalo** [comment]
Any tips on where I should start looking for the bug or a possible solution? Is this a modeler issue or does it belong to bpmn-js? 

Since it is very annoying, I would possibly try my hand at a solution and submit a pull request. Best case. But the threshold of getting into the project may be too high for me.

**Comment by nikku** [comment]
@Xembalo Thanks for pinging us on this one again.

Copy and paste unfortunately _creates_ an element, hence our existing create logic triggers.

To move forward with this issue we'd need to be clear on the expected overall behavior:

* Given there is a `DEFAULT_TEMPLATE` applied to `ACTIVITY_X`
* If I apply a `OTHER_TEMPLATE` to `ACTIVITY_X`
* Then...
  * :a: The `DEFAULT_TEMPLATE` does not apply anymore
  * :b: The `DEFAULT_TEMPLATE` and `OTHER_TEMPLATE` both apply

I'm in favor of :a: as we generally (UI wise) cannot handle multiple templates being applied. It also is a more sane direction for users: The `DEFAULT_TEMPLATE` applies _unless_ another template is explicitly chosen.

**Comment by nikku** [comment]
Additionally we need to clarify:

* Given there is a `DEFAULT_TEMPLATE` applied to `ACTIVITY_X`
* I unapply it
* Then, once I copy the element...
  * :c: the default template is re-applied (and will in the process clear all not configured properties :arrow_right: this is the existing behavior)
  * :d: the default template remains unapplied (violates our existing create behavior)

**Comment by nikku** [comment]
Will be fixed as described in https://github.com/camunda/camunda-modeler/issues/3235#issuecomment-1424295244 with Camunda Modeler v5.9.0 (or in the next nightly).

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/3452.
