### ISSUE TITLE
Deleting a Message does not delete it from XML

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#324]
Steps:
Create a event that throws or catches aMessage in a process:
![screen shot 2016-06-04 at 8 33 07 pm](https://cloud.githubusercontent.com/assets/1994838/15802955/a25eff90-2a93-11e6-94ba-2084045ef699.png)

In the properties panel select the `+` box to create a new message:
![screen shot 2016-06-04 at 8 34 47 pm](https://cloud.githubusercontent.com/assets/1994838/15802958/d4df02e4-2a93-11e6-92ed-0d60ff50344b.png)

Now delete the message by selecting the `x` in the message name field, and select the blank options in the Message field.
![screen shot 2016-06-04 at 8 35 43 pm](https://cloud.githubusercontent.com/assets/1994838/15802959/ed677b8e-2a93-11e6-8d87-c16a5864a511.png)

If you go back to the Message field you will still see the message.  If you delete the element and recreate a new element and open the message field, the message is still in the message field.  If you look in the XML you see that the entire message is not deleted:
![screen shot 2016-06-04 at 8 36 59 pm](https://cloud.githubusercontent.com/assets/1994838/15802963/2193f662-2a94-11e6-8f42-c9f8e04aaab4.png)

**Comment by nikku** [comment]
You need to manually delete the message. The missing feature is an overview over all defined messages (on definition level).
