### ISSUE TITLE
Prompt to save your files before reload

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-modeler#3240]
### Problem you would like to solve

With the new reload action (https://github.com/camunda/camunda-modeler/issues/3089), it is easy for everyone to reload Modeler (to recover from errors or to reload element templates or other configs). Since the reload is easily accessible, people may do it once without saving their files before and will lose all their changes.

### Proposed solution

Prompt to save files before reload (same prompt as when to close Modeler)

### Alternatives considered

Introduce Ctrl+Shift+R instead and remove it from the option menu

**Comment by christian-konrad** [comment]
> If you could choose, which option would you prefer?

Asking to safe (before reloading) 

With the spread of connector templates for Self-Managed, I would say this should not be an expert feature, but accessible to more people

(I would even expect something less intrusive like "Reload element templates" but let's keep it out of scope for now due to complexity)

**Comment by barmac** [comment]
I can imagine we ask whether user wants to save files like we do before the exit.

**Comment by vignesh57** [comment]
Just came here to post this as a feature request but looks like it's already in backlog. 
My +1 to get this prompt added so we don't accidentally lose unsaved work.
