### ISSUE TITLE
Opening multiple BPMN files at once not working as expected

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#325]
On windows 10, 64bit.

When i select a number of BPMN files and open them with the modeler the first thing that happens is that a number of pop-ups appear sequentially,  telling me that a file has been changed and asked me to reload.

Once i get past that it has opened one of the files in multiple tabs and not opened others. Screen shots attached show the issue:

![files](https://cloud.githubusercontent.com/assets/10612634/15816793/fd664ec4-2bd4-11e6-8a33-92a2acd4461b.PNG)
![files2](https://cloud.githubusercontent.com/assets/10612634/15816808/12240b80-2bd5-11e6-8820-a63b163cc210.PNG)

**Comment by gimbel** [comment]
What would be the expected behaviour? 
- All files open as new tabs (if not open already)
- For all files already open, the user gets asked if he wants to reload

Something like that?

**Comment by ricardomatias** [comment]
Check #326
