### ISSUE TITLE
Closing all Tabs results in multiple "file changed" dialogs

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#326]
When using the "close all tabs" option the "file changed" popup appears for each tab - clicking cancel or reload has the same affect.

**Comment by gimbel** [comment]
What would be the expected behaviour?

**Comment by ricardomatias** [comment]
@gimbel, there should be no popup unless there are actually external file changes. What happens now is that the dialog is shown independently of whether the file changed or not.

**Comment by ricardomatias** [comment]
Closing this issue for now. I cannot find a way to reliably reproduce it. Feel free to reopen it if you find a way to reproduce it.
