### ISSUE TITLE
Syntax error with default value

### ISSUE THREAD

**Issue by Oleksiivanov** [camunda/camunda-modeler#3261]
### Describe the bug

When we have in a  template default value : 
`"value": "{}",
`
in desktop modeler we see next : 
<img width="411" alt="Screenshot 2022-10-27 at 19 20 01" src="https://user-images.githubusercontent.com/108869886/198344951-c66a3e33-42d5-4be6-afa9-b1a234623f4f.png">

### Steps to reproduce

1. add template to modeler : 

<details><summary>Click to open template code</summary>
 <p>
      {<br>
        "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",<br>
        "name": "TestDefaulValueTemplate",<br>
        "id": "5210ac12-fc32-4352-a311-67168c2d45d6",<br>
        "category": {<br>
          &nbsp&nbsp&nbsp&nbsp"id": "connectors",<br>
          &nbsp&nbsp&nbsp&nbsp"name": "Connectors"<br>
                    },<br>
        "appliesTo": [<br>
         &nbsp&nbsp&nbsp&nbsp "bpmn:Task"<br>
        ],<br>
        "elementType": {<br>
          &nbsp&nbsp&nbsp&nbsp"value": "bpmn:ServiceTask"<br>
        },<br>
        "properties": [<br>
          &nbsp&nbsp&nbsp&nbsp{<br>
            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"label": "Test",<br>
            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"type": "Text",<br>
            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"feel": "required",<br>
            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"value": "{}",<br>
            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"binding": {<br>
              &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"type": "zeebe:input",<br>
              &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"name": "message.properties"<br>
          &nbsp&nbsp&nbsp&nbsp  }<br>
         &nbsp&nbsp&nbsp }<br>
        ]<br>
      }<br>
</p>
</details>

2. launch the desktop modeler
3. create a new BPMN diagram
4. append a task
5. add`TestDefaulValueTemplate` template
6. and we see a syntax error in field
 - or see attached video
 

https://user-images.githubusercontent.com/108869886/198350005-f1dafdee-a2ec-42d7-b8e9-5aeda0060df7.mov

### Expected behavior

I expected that I would see in the desktop modeler value what was write in template : 

<img width="418" alt="Screenshot 2022-10-27 at 19 21 07" src="https://user-images.githubusercontent.com/108869886/198345212-9c05d0fd-4d7c-473a-8390-c3d1204c0950.png">

### Environment

- OS: [e.g. MacOS 10.2]
- Camunda Modeler Version: [e.g. 5.3.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by philippfromme** [comment]
@marstamm Do we remove the first character assuming it's the `=` sign?

**Comment by marstamm** [comment]
> Do we remove the first character assuming it's the = sign?

We did previously, but it was fixed in https://github.com/bpmn-io/properties-panel/issues/183 and shipped with Camunda Modeler 5.4.0.

@Oleksiivanov Which Modeler version are you using?
