### ISSUE TITLE
Morph menu should appear after dropping an element on the canvas

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#327]
When a new element is created I've found that the first thing that a user wants to do is to morph it into their required symbol. This is because the default symbols are actually ones that are rarely used when modeling. Like the undefined task or non-intermediate event. 

Feedback I've gotten has suggested that it gets a bit annoying having to click the morph button every time you create a new element, it tends to break up the flow of model creation. It might be a nice idea to consider opening the morph menu by default when an item is created.

**Comment by nikku** [comment]
Do we really want to do this?

**Comment by NPDeehan** [comment]
I think it's a pretty good addition to the user experience. We already have a very fluid method of modeling and i think this would really add to that.

**Comment by nikku** [comment]
Suggestion: Automatically open replace menu on drop with modifier key only (CTRL on Linux/Windows, ALT on Mac).
