### ISSUE TITLE
Consider Always Showing IDs in Problems Panel

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#3270]
The _Problems_ panel lists reports showing the `name` specified in the report and falls back to showing their ID.

In this example the warning shows the ID while the the errors show the name:

![image](https://user-images.githubusercontent.com/7633572/199474231-a16f40a6-f025-48ad-be43-ea8741a5ff74.png)

We should consider always showing the IDs for the following reasons:

* IDs are unique while names can be duplicated which would make it harder to distinct between reports
* Names tend to be longer than IDs, rarely can the entire name be shown
* Names might not actually help to identify problems quicker

---

Follow-up to https://github.com/camunda/camunda-modeler/pull/3257

**Comment by christian-konrad** [comment]
Summary of current arguments:

Pro Name (+ ID fallback):
* Names have a much higher chance to be set then the IDs
* Users write the names themselves, which makes them easier to recognize then automatically defined IDs
* Names are always visible on the canvas, IDs are not

Pro ID:
* IDs are unique while names can be duplicated which would make it harder to distinct between reports
    * Contra argument: Duplicate task names are in general discouraged since it reduces understandability of the diagram
* Names tend to be longer than IDs, rarely can the entire name be shown
    * Contra argument: Only the first n chars of the name are neccessary for the user to recognize the element
* Flow nodes are often named "yes" and "no", and are hard to distinguish in the problems panel
    * Contra argument: Flow nodes rarely produce problems, and if they do, you are midst modeling and can easily make the connection between the "yes"/"no" shown in the panel, and the only flows annotated in the canvas (the ones recently added)
* It may appear weird if you add a task, then you see the task id in the problems panel, then you rename the task, and then you see the name 

@YanaSegal @philippfromme

**Comment by nikku** [comment]
Let's close this as the discussion on this item was non-conclusive. If we receive further feedback we can re-open.
