### ISSUE TITLE
Changing the option source from input -> static values does not bring back the "default value" option in forms

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3274]
### Describe the bug

While we create forms and make use of a field that has option source say Radio and change the option source  from input value->static we could see that the default one "value" that comes by choosing static option is not displayed and we need to manually add the static value by clicking on the "+" button in the static option field

### Steps to reproduce

1. create a form with radio button
2. We could see a default "value" under the radio button
3. in the properties panel goto options source and change it from "static" -> "Input data"
4. we could see that the deafult value is not available since the option source is changed to input data
5. Changing back the source from input data->static does not bring the default vale back to the Radio button field. 

https://user-images.githubusercontent.com/85225325/199750570-a95844ea-8cd6-4174-80bf-523e07ce87e7.mp4

### Expected behavior

changing back to static option source must bring back the default value for the field

### Environment

- OS: [ Windows 10]
- Camunda Modeler Version: [5.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]

**Comment by philippfromme** [comment]
> Uploading d438bf4583567c3044c3efd89fc0ca41.mp4…

@GeethaParthasarathy it seems like the screencast didn't finish uploading in time. 😄

**Comment by GeethaParthasarathy** [comment]
https://user-images.githubusercontent.com/85225325/199750570-a95844ea-8cd6-4174-80bf-523e07ce87e7.mp4

 @philippfromme my bad I did not notice that . Hopefully it works now

**Comment by barmac** [comment]
I can reproduce it. Thanks for the report.

**Comment by pinussilvestrus** [comment]
Fixed upstream via https://github.com/bpmn-io/form-js/pull/514

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/41d2d9bed5c426d2a07dba4064ea668682160d18
