### ISSUE TITLE
Support BPMN Data Store and Data Object

### ISSUE THREAD

**Issue by CatalinaMoisuc** [camunda/camunda-modeler#3277]
### Problem you would like to solve

Related to the following epic:

* https://github.com/camunda/product-hub/issues/618.

Support for BPMN Data Store and Data Object is added to Zeebe in https://github.com/camunda/zeebe/issues/8230
All the products in the Camunda Platform 8 stack need to align and support the feature.

If the Modeler doesn't support modeling the BPMN Data Store and Data Object for Camunda Platform 8, then our customers cannot use this new feature.

### Proposed solution

Add support for BPMN Data Store and Data Object for Camunda Platform 8.

The user should also get proper feedback from linting depending on the execution platform version selected i.e. is it supported or not by version x.

### Alternatives considered

Customers could update the XML by hand

**Comment by nikku** [comment]
It will be supported in 8.2, but also got backported to 8.0 stable: https://github.com/camunda/zeebe/pull/10916.

I suggest we mark it as supported for 8.0+.

**Comment by marstamm** [comment]
integrated with 1d0c47f0ca98e69dbf4fe810c80fde0481022908
