### ISSUE TITLE
Be able to define default element templates (on User Task / Service Task)

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#328]
A developer can define element templates that activate per default based on an elements type (i.e. `bpmn:ServiceTask`).

* Template properties are applied on element creation
* Default templates do not activate for elements with a specified element template
* Default templates activate automatically and do not persists to `camunda:modelerTemplate`
* Template properties are editable in properties panel
* Template is shown but cannot be changed, if a default template is being active on an element

**Example**

A developer defines an element template for all `bpmn:UserTask`s. Whenever a citizen developer creates a user task (from palette or context pad) it gets initialized with a `camunda:property` `foo=bar`:

``` xml
<camunda:property name="foo" value="bar" />
```

The property is shown as a custom property in the properties panel together with user defined validation rules and hints.

---

Related to [SUPPORT-2383](https://app.camunda.com/jira/browse/SUPPORT-2383)

**Comment by gimbel** [comment]
did we also write docs for this feature?

**Comment by nikku** [comment]
Not yet, still needs to be done.

**Comment by mprokopenko-jc** [comment]
Hi guys. Do we have this ability in bpmn-js library ? I just want to predefine some camunda properties for Service task

**Comment by nikku** [comment]
What exactly would you like to do? What is your setup?

Element Templates are implemented as part of the [`bpmn-js-properties-panel`](https://travis-ci.org/bpmn-io/bpmn-js-properties-panel). The core library does not have that feature.

**Comment by mprokopenko** [comment]
Thank you for your response.
So I have the next setup:
1.Properties panel already added.
2. Camunda module added as well.

I have created custom Service Task with icon in the panel (please check the screen - http://prntscr.com/gwvjf3 , i will change svg shape on canvas as well). But this task is empty by default. So all i need is make some properties for Service Task be preset. Please check the screen to see what properties i mean - 
- http://prntscr.com/gwvlb9
- http://prntscr.com/gwvli9

**Comment by mprokopenko** [comment]
Hi guys. Did you have ability to check my problem?
