### ISSUE TITLE
FEEL field reports syntax error for path expression in a list

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3280]
### Describe the bug

When I type a path expression in a list (`[ test.x ]`) to a FEEL field, it reports a syntax error.

### Steps to reproduce

See above.

### Expected behavior

No syntax error should be reported.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

### Additional context

- Issue in nikku/lezer-feel: https://github.com/nikku/lezer-feel/issues/11
- Reported to Jira as https://jira.camunda.com/browse/SUPPORT-15070

Related to https://github.com/camunda/camunda-modeler/issues/3296.

**Comment by nikku** [comment]
Moving to backlog for the moment. Worth having a look at some point though; we've come across this from multiple angles.

**Comment by nikku** [comment]
Fixed through dependency update, testable in the latest [nightly](https://downloads.camunda.cloud/release/camunda-modeler/nightly/), via 8b92c59e2a376838d349acf693088371b9761ce9.
