### ISSUE TITLE
The source of the output is not editable when using element template

### ISSUE THREAD

**Issue by tkuy** [camunda/camunda-modeler#3281]
### Describe the bug

When trying to create a service task template with outputs, the output doesn't appear correctly. The target is editable instead of the source.

The element template:
```
{
  "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
  "name": "Example",
  "id": "Example",
  "description": "The output is not correct",
  "appliesTo": [
    "bpmn:ServiceTask"
  ],
  "groups": [
    {
      "id": "inputs",
      "label": "Inputs"
    },
    {
      "id": "outputs",
      "label": "Outputs"
    }
  ],
  "properties": [
    {
      "value": "example-v1",
      "binding": {
        "type": "zeebe:taskDefinition:type"
      },
      "editable": false
    },
    {
      "description": "Output value",
      "group": "outputs",
      "label": "myTarget",
      "value": "myTarget",
      "type": "String",
      "binding": {
        "type": "zeebe:output",
        "source": "=\"mySource\""
      },
      "constraints": {
        "notEmpty": true
      }
    }
  ]
}
```

When the element template is linked:
In the XML: `<zeebe:output source="=&#34;mySource&#34;" target="myTarget" />`

![Screenshot from 2022-11-08 11-32-13](https://user-images.githubusercontent.com/45755667/200546121-d6e15e98-a30e-44e0-8f24-f43dac9e09f5.png)

When the element template is unlinked:
In the XML: `<zeebe:output source="=&#34;mySource&#34;" target="myTarget" />`

![Screenshot from 2022-11-08 11-46-31](https://user-images.githubusercontent.com/45755667/200546249-2b303e43-9820-4b3e-9f95-8290f68a5b49.png)

### Steps to reproduce

1. Create a task using the element template
2. Check that the source is not editable 
3. Unlink the element template using the camunda modeler
4. Check that without the element template, the source is editable

### Expected behavior

The output source is editable when the element template is linked

### Environment

Environent: 
- OS: Ubuntu 20.04.3 LTS
- Camunda Modeler Version: 5.5.0
- Execution Platform: Camunda 8 Platform Self Managed
- Installed plug-ins: None

### Additional context

Summarized [here](https://github.com/camunda/camunda-modeler/issues/3281#issuecomment-1327123634).

**Comment by nikku** [comment]
Thanks for opening this issue!

Could you explain to me in brief why you'd expect the source to be editable? Element templates define a contract / hard-code bindings for a re-usable building block. In the binding it is expected that outputs are static (the building block always produces the same outputs, i.e. `invoiceNumber` for an invoice submission service), and that these outputs are to be mapped into the process `invoiceNumber -> savedInvoiceNumber`.

**Comment by tkuy** [comment]
Maybe, I shouldn't have talk about edition. When the element template is linked, the value is not correctly mapped in the UI. 
Instead of `myTarget`, I should have `="mySource"`
![200546121-d6e15e98-a30e-44e0-8f24-f43dac9e09f5](https://user-images.githubusercontent.com/45755667/201933962-edd70ff2-56a6-4062-b8ef-7704b115b11b.png)

**Comment by nikku** [comment]
> https://github.com/camunda/camunda-modeler/issues/3281#issuecomment-1315328484

Outputs map _from_ expressions (variables assigned within the service task, and or computed values, defined in the element template) _to_ output variables. Hence task users can specify the name of a variable a particular production from the service task will be written to.

I can only re-iterate: Why do you expect the source for output mappings to be editable? What is your (real world) use-case?

**Comment by tkuy** [comment]
I understand your point and it's working for most of our cases.

A simple real use case where we need to edit the source: 

![Screenshot from 2022-11-16 14-43-45](https://user-images.githubusercontent.com/45755667/202196665-48f87d29-bbcd-4e81-9550-575e2081fa37.png)


- A service task that creates a session `createdSession` and add it to the `applicant.sessions`
- The value sometimes need to be changed using feel expression before we add it to `applicant.sessions` and it depends on the workflow

We can have this kind of output in the service task:
1. `append(applicant.sessions, createdSession)) -> applicant.sessions`
2. `append(applicant.sessions, put(createdSession, "sessionName", "mySessionName")) -> applicant.sessions`
3. `append(applicant.sessions, put(createdSession, "anyOtherValue", "value")) -> applicant.sessions`
4. ...

We need to edit the source so we can change the feel expression. As you can see, the output is not always the same even for the same task. 

We don't want to add a step to compute a variable using an output that comes from the service task as it add complexity to our workflows such as:
![Screenshot from 2022-11-16 14-46-30](https://user-images.githubusercontent.com/45755667/202197165-0dd142c9-de5f-44bd-a505-f185046e3b27.png)


Thanks :)

**Comment by nikku** [comment]
Thanks for sharing your use-case.

What I'm seeing in https://github.com/camunda/camunda-modeler/issues/3281#issuecomment-1318564165 is `Create session` does the following:

* You create a session
* You attach (optional) additional meta-data to it
* You link the session into a given session list

----

Thinking about this a little differently, adding additional meta-data could be a feature of the create session service. It would have the (baked in) functionality to attach additional meta-data that is being passed as an input. Would that work?

The source of the output mapping is a static one in that case, again:

```
= append(sessions, (
    if additionalDetails != null 
    then
      put all(createdSession, additionalDetails)
    else
      createdSession
  ))
```

**Comment by nikku** [comment]
Moving to backlog.

The essential requested feature is to be able to not only assign an output variable, but rather incorporate the output into the process context (add to a list) using an expression.

**Comment by tkuy** [comment]
Thank you for your advice @nikku
This solution is good to me, it solves our problem!
I'm closing the issue.
