### ISSUE TITLE
I can model link events for Camunda Platform 8

### ISSUE THREAD

**Issue by lzgabel** [camunda/camunda-modeler#3282]
### Problem you would like to solve

Since Camunda Platform `8.2`, link events are supported. I want to model a process that contains a link throw event or a link catch event.

### Proposed solution

* I can choose 8.2. as an execution platform
* I can model link events in my process starting from Camunda Platform 8.2
* The Problem panel shows an error when an older execution platform is selected

### Alternatives considered

None.

### Additional context

Related Zeebe PR: 
* https://github.com/camunda/zeebe/pull/10770
* https://github.com/camunda/zeebe/pull/10635

----

_Tracked via https://github.com/camunda/product-hub/issues/248._

**Comment by nikku** [comment]
Thanks for the heads up. Awesome zeebe contribution :medal_sports:.

We'd need to create a 8.2 profile first (https://github.com/camunda/camunda-modeler/issues/3284), and take it from there.

**Comment by marstamm** [comment]
> let's not forget about the changes on the prop panel side

The Zeebe implementation uses the default "name" prop from the bpmn spec, which the zeebe property panel already supports. This Issue only needs changes in linting to be fully supported
