### ISSUE TITLE
Add Camunda 8.2 profile

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3284]
### What should we do?

The [first alpha](https://github.com/camunda/zeebe/releases) of Camunda 8.2 is out. As a user I want to be able to use it in the Modeler.

* [ ] Be able to select 8.2 as a diagram target (try out new features)
* [ ] Keep 8.1 (stable) as a default for now

### Why should we do it?

Make it possible for me as a user to use 8.2 features in my diagrams (https://github.com/camunda/camunda-modeler/issues/3282).

**Comment by marstamm** [comment]
I'll take this one as I need it to make progress with https://github.com/camunda/camunda-modeler/issues/3230 anyway
