### ISSUE TITLE
Changing a Task type clears Inbound and outbound Flow conditions

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#329]
Example: If you have a Exclusive Gateway that flows to a Service Task and you change that task to a User Task, the condition on the flow that points into the task is cleared/deleted.  Same with any flows coming out of the task.

This is very problematic as there is no warning, or message, and so you can have a lot of config in the condition of the flow and easily have it deleted without notice when making a modification to the task type.

**Comment by pedesen** [comment]
@nikku Is this still an issue? I can't reproduce this in the latest version (1.3.2) of the modeler.

If I change the task type in [this diagram](https://github.com/camunda/camunda-modeler/files/536076/condition-flow.bpmn.zip) the conditionExpression configuration of the sequence flow is retained.

**Comment by nikku** [comment]
Cannot reproduce it myself. 

@StephenOTT still an issue?

**Comment by StephenOTT** [comment]
@nikku this appears to be fixed!  Thank you!
