### ISSUE TITLE
Feel conditional expression shows "Invalid Syntax Error"

### ISSUE THREAD

**Issue by igpetrov** [camunda/camunda-modeler#3296]
### Problem you would like to solve

<img width="408" alt="Screenshot 2022-11-10 at 11 36 35" src="https://user-images.githubusercontent.com/108870003/201108425-d76ad5b5-40fa-4dcc-bbf4-ee04588fe92e.png">

Feel Conditional Expression shows "Invalid Syntax Error".

Reproducible in web and desktop modeler.

See diagram [github-pr-to-slack.bpmn.txt](https://github.com/camunda/camunda-modeler/files/9981230/github-pr-to-slack.bpmn.txt)

### Expected Behavior

Expression parses correctly.

### Alternatives considered

No alternatives.

### Additional context

This is required for the Inbound Connectors implementation ( https://github.com/camunda/product-hub/issues/174).

----

Depends on https://github.com/nikku/lezer-feel/issues/12.

**Comment by nikku** [comment]
As a workaround remove the `()` and the expression parses just fine.

**Comment by nikku** [comment]
Fixed with `lezer-feel@0.15.0`, to be incorporated via upstream releases.

**Comment by marstamm** [comment]
fixed through dependency update, testable in the latest [nightly](https://downloads.camunda.cloud/release/camunda-modeler/nightly/)
