### ISSUE TITLE
Select All command does not work when in text fields in Property Panel

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#330]
When you are in the property panel and you need to select all text in a field, the Select All command does not function/does not select all text.

**Comment by StephenOTT** [comment]
For mac, current work around is to use Shift+Command+Arrow Key direction that you want to select all from cursor.

**Comment by nikku** [comment]
There were a few Electron regressions. Please verify if this behavior got fixed with the latest Camunda Modeler release (`v1.2.2`).

**Comment by ricardomatias** [comment]
Fixed with new Electron version.
