### ISSUE TITLE
Implementation detail disappears when you delete the only character

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#3304]
### Describe the bug

If you start entering an implementation for a service task, the selected implementation disappears, if you delete the one and only character entered in the Java class or delegate expression.

### Steps to reproduce

1. model a service task in the canvas
2. open the implementation group and select delegate expression
3. enter `$`.
4. Delete the character by pressing Backspace

### Expected behavior

The empty delegate expression is kept open and the implementation is still selected.

### Environment

Camunda Modeler system information
 * Version: 5.5.0
 * Operating System: Windows 10 amd64
 * Plugins: Cloud Connect, bpmn-js Token Simulation, Migration, Transaction Boundaries, Camunda Property Infos, Tooltip Plugin
 * Execution Platform: BPMN - Camunda Platform 7

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/eeab284c812bf77c7b31b7ae49bcf59364ca18f6
