### ISSUE TITLE
Support BPMN Escalation Events for C8

### ISSUE THREAD

**Issue by CatalinaMoisuc** [camunda/camunda-modeler#3318]
### Problem you would like to solve

As a user implementing a process in Camunda 8 I want to model escalations, introduced into Zeebe via https://github.com/camunda/zeebe/issues/10682.

Support the standard BPMN fields, no extensions are added. It's basically identical to error events. Example of an escalation end event:

```xml
<bpmn:process>
  <bpmn:endEvent>
    <bpmn:escalationEventDefinition id="EscalationEventDefinition_1" escalationRef="Escalation_2" />
  </bpmn:endEvent>
</bpmn:process>
<bpmn:escalation id="Escalation_2" name="Escalation_2" escalationCode="code" />
```

### Proposed solution

* [x] Support standard BPMN escalation fields in properties panel
* [x] `bpmn:Escalation#escalationCode` can optionally be a `FEEL` expression https://github.com/bpmn-io/bpmn-js-properties-panel/pull/855
* [x] Allow escalation in 8.2 and validate escalation code https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/73
* [x] Provide properties panel support for escalation code linting
* [x] https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/79

### Alternatives considered

None.

### Additional context

Upstream implementation (engine wise) tracked via https://github.com/camunda/zeebe/issues/10682.

----

Also tracked via https://github.com/camunda/product-hub/issues/198.

**Comment by nikku** [comment]
We'd need clear documentation of escalation event support in zeebe before we can pick this up for implementation:

* Do they support the standard BPMN fields on escalation?
* Which of these can be dynamic (FEEL expressions)

Do you already have the details? If so, please attach them to this issue so it becomes actionable for us.

**Comment by lzgabel** [comment]
> Which fields can be dynamic (FEEL expressions)?

@nikku @CatalinaMoisuc https://github.com/camunda/zeebe/issues/10973#issuecomment-1316777130

**Comment by remcowesterhoud** [comment]
@nikku @CatalinaMoisuc 

> Do they support the standard BPMN fields on escalation / do they add extensions?
Yes, we support the standard BPMN fields. It's basically identical to error events.

Example of an end event:
```xml
  <bpmn:endEvent id="Event_188ciku">
    <bpmn:incoming>Flow_0hzdbf9</bpmn:incoming>
      <bpmn:escalationEventDefinition id="EscalationEventDefinition_0ljzqnu" escalationRef="Escalation_2t48e46" />
  </bpmn:endEvent>
</bpmn:process>
<bpmn:escalation id="Escalation_2t48e46" name="Escalation_2t48e46" escalationCode="code" />
```

> Which fields can be dynamic (FEEL expressions)?
The `escalationCode` of the `bpmn:escalation` can optionally be a FEEL expression

Does this answer your questions?

**Comment by nikku** [comment]
Thanks @remcowesterhoud :tada:. Answers all our questions. I'll update the issue accordingly.

**Comment by nikku** [comment]
Now ready to be picked up :muscle:

**Comment by barmac** [comment]
I am looking into this today.

**Comment by barmac** [comment]
> Catch events referencing an escalation with a FEEL expression are not allowed. It would be nice if the linting could catch this. Zeebe will reject the deployment if there is a catch event containing an `escalationCode` with an expression.

Generally, BPMN does not allow to have an intermediate catch event with escalation event definition. Did you mean anything else?

**Comment by remcowesterhoud** [comment]
> > Catch events referencing an escalation with a FEEL expression are not allowed. It would be nice if the linting could catch this. Zeebe will reject the deployment if there is a catch event containing an `escalationCode` with an expression.
> 
> Generally, BPMN does not allow to have an intermediate catch event with escalation event definition. Did you mean anything else?

I don't mean intermediate catch events. With catch event I'm referring to the escalation start event and the escalation boundary events. Here we have the possibility to define an escalation code. This escalation code can not be a FEEL expression.
FEEL expressions are only supported in the escalation intermediate throw event and the escalation end event.

**Comment by barmac** [comment]
Thanks for explanation. I've just tested this on the latest alpha and got the results as you explained. So we should disallow escalation code as expression in **start** and **boundary** events.
