### ISSUE TITLE
Support FEEL expressions in error throw events

### ISSUE THREAD

**Issue by CatalinaMoisuc** [camunda/camunda-modeler#3319]
### What should we do?

Allow users to [model dynamic `Error#errorCode`](https://github.com/camunda/product-hub/issues/698) in 8.2+ diagrams.

### Describe the Solution

* [x] [`Error#errorCode` can be an optional FEEL expression](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/836)
* [x] [We validate through linting that this feature is supported in 8.2+ only](https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/69)
* [x] [Integrated via `@camunda/linting`](https://github.com/camunda/linting/pull/40)

### Why should we do it?

Currently, if I want to throw different errors from my process, I need to explicitly model multiple error end events. When I have an errorCode available in a variable I need to use an exclusive gateway to decide which error end event I should go to. If I can use an expression in my error throw event I don't need to explicitly model all these options anymore. I can have a single throw event that can trigger multiple different catch events.

----

Also tracked via https://github.com/camunda/product-hub/issues/698.

**Comment by barmac** [comment]
Added https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/69 as the linting part.

**Comment by barmac** [comment]
The issue above will be followed by a PR in camunda/linting project.
