### ISSUE TITLE
syntaxError: expression expected in input variables (service task) with parenthesis

### ISSUE THREAD

**Issue by VDmdm** [camunda/camunda-modeler#3320]
### Describe the bug

I try to get variables from ((productAction.serviceOrderOperations[1]).serviceOrder.items[1]).service.id path, it's working in zeebe (without parenthesis it don't work, but it's another problem), but i get syntax error in modeler 5.5.1, also in comunda/linter.
Error text: "syntaxError: expression expected"

### Steps to reproduce

1. Create service task, in "Inputs" add variable with some local name, put expressions with parenthesis (not function) in variables assignment value
2. Get error "syntaxError: expression expected"
3. Try to deploy, deploy have success.

### Expected behavior

Don't get syntax error

### Environment

- OS: [MacOS 12.1]
- Camunda Modeler Version: [ 5.5.1 ]
- Execution Platform: [ Zeebe 1.3.0 ]

**Comment by nikku** [comment]
You are running into https://github.com/camunda/camunda-modeler/issues/3280, fixed with the next release!

**Comment by VDmdm** [comment]
@nikku I'm definitely lucky :) Thanks for anwer!

**Comment by nikku** [comment]
Fixed through dependency update, testable in the latest [nightly](https://downloads.camunda.cloud/release/camunda-modeler/nightly/), via 8b92c59e2a376838d349acf693088371b9761ce9.
