### ISSUE TITLE
Open all group elements by default

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#3325]
### Problem you would like to solve

I have to check a lot of processes for their implementations. The developer put many execution listeners of different types all over the processes.

To inspect every one, I need a lot of clicks: 
* Once the Execution Listener group is opened, I can see the single listeners, but not their details.
* I have to click on each expander of every listener to see the details. 
* Select another BPMN element
* Open all listener details again.

### Proposed solution

It would be great if the property panel would remember my selection for nested groups and elements.

Once I had opened them, I would like to have them open when I select the next BPMN element again.

### Alternatives considered

nothing

### Additional context

Perhaps I can attach an example process afterwards that you can feel my pain.

**Comment by nikku** [comment]
This has been reported multiple times already and we track it via https://github.com/camunda/camunda-modeler/issues/2638.

The solution you propose is pragmatic, what the user expects. The current situation is inconvenient to say the least. I can feel your pain.
