### ISSUE TITLE
check email field on demo template to be a valid email address

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#333]
Could you please improve the demo template for the email task to check the sender to be a vlalid email address with a pattern constraint? I'm curouius how it looks like and customes are asking for it.

**Comment by nikku** [comment]
Can get [arbitrarily complex](http://www.regular-expressions.info/email.html). Which regex would you like us to include?

**Comment by ingorichtsmeier** [comment]
The first one is OK. Is it possible to add the link of the document in the lable of the mail textbox? If not, it would be an improvement, too (maybe worth another issue).
