### ISSUE TITLE
"readonly" mode for file protection

### ISSUE THREAD

**Issue by leolux** [camunda/camunda-modeler#334]
I think it would be a nice feature to have some kind of mode switcher for activating/deactivating the "readonly" mode per file basis. This mode could help everyone to actively protect files against any unwanted changes within the XML / diagram. 

Unwanted changes on the wrong version of file happend to me view times already. I realised that it produces frustration at the moment of discovery every time :tired_face:.

**Comment by StephenOTT** [comment]
As current work around, could you just set Read only  / locked through the file system?

**Comment by nikku** [comment]
This is nothing we are going to implement any time soon.

Interesting questions we have to ask ourself:

* where to store the read-only information
* how to properly transport the "read-only" property to the user

As @StephenOTT there is workarounds for that. I suggest using a versioning control system under the hood to detect unwanted changes on the file basis.

**Comment by leolux** [comment]
Ok, that's fine. A version control system is the best solution in many aspects.

Regarding the question of how to represent the "read-only" property to the user I would think of a a transparent grayish-colored overlay for example, deactivating the contents of the panel or simply an lock-icon behind the filename.

**Comment by StephenOTT** [comment]
> As @StephenOTT there is workarounds for that.

@nikku something that would be great to add for when a file is read-only is a pop-up warning, and text in the app header or tab header that the file is Read-only and cannot be changed without saving new file.  There is the pop-up on save that says this file cannot be saved and must re-save, but something when you first open the file would be great as well.

**Comment by nikku** [comment]
@StephenOTT Sounds like a good addition. Feel free to provide a PR for that!
