### ISSUE TITLE
New replace menu search is closed when palette shortcuts kick in

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3342]
### Describe the bug

When I open the replace menu and start typing, it closes immediately if I type a letter to which a shortcut is applied, e.g. S for the space tool or L for lasso.

### Steps to reproduce

1. Open replace menu
2. Type "S"
3. now this happens

### Expected behavior

Shortcuts should not activate when input is focused.

### Environment

- OS: Mac
- Camunda Modeler Version: Current (upcoming 5.6.0)
- Execution Platform: Any
- Installed plug-ins: [...]

**Comment by philippfromme** [comment]
Might be due to the fact that the popup menu is now an asynchronously rendered Preact app?

**Comment by barmac** [comment]
There is a hotfix for this: https://github.com/camunda/camunda-modeler/pull/3343

Not closing the issue though.
