### ISSUE TITLE
Replace Menu Search only triggers on second character

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3347]
### Describe the bug

In Certain starting letters, the list of replace options is not filtered:

![Recording 2022-12-08 at 09 36 32](https://user-images.githubusercontent.com/21984219/206399113-c092804d-a7ad-4bd3-b785-e20643d32b21.gif)

### Steps to reproduce

1. open the replace menu on a task
2. Type "R" in the filter
3. Nothing happens

### Expected behavior

Entries without "R" (like Manual Task) are hidden

## Camunda Modeler system information
 * Version: 5.6.0-rc.0
 * Operating System: Linux x86_64 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform 8

**Comment by marstamm** [comment]
I can reproduce it back in bpmn-js. It seems like we filter for the entry ID instead of the label. I think this is a bit unexpected from the user perspektive

![Recording 2022-12-08 at 09 42 47](https://user-images.githubusercontent.com/21984219/206399757-fbe812b0-3c94-47e0-a61d-90be3d1f1ff1.gif)

**Comment by nikku** [comment]
:+1: Should not filter by ID (unsurprising results).
