### ISSUE TITLE
DMN styling is broken

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3348]
### Describe the bug

No palette border, broken hover effect etc.

![Screen Shot 2022-12-08 at 12 14 01](https://user-images.githubusercontent.com/28307541/206432950-622a6971-626a-46e0-837b-32dbbc6c72bc.png)

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Expected behavior

It should work.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by barmac** [comment]
This was broken in `f825a96173c6def1b0fb802fde0ad7910f2e781d`.

**Comment by nikku** [comment]
@smbea This breaking change completely slipped our attention. Could you add it to the changelog (diagram-js@11)?

**Comment by nikku** [comment]
Actually never mind my previosu comment:

![image](https://user-images.githubusercontent.com/58601/206437233-8d8c7943-0690-4c9f-abba-86a92b31f5a6.png)

It is all there, we just have to read the changelog (apparently renovate does not) :wink:

**Comment by barmac** [comment]
Fixed via https://github.com/camunda/camunda-modeler/commit/4a8a2de0eebc81a0118ffcb2c7ee5fdcf3994efe
