### ISSUE TITLE
Unable to collapse Expanded embedded sub-process?

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#335]
Currently you can convert a Sub-Process (collapsed) into a Expanded sub-process, but there does not seem to be a way to collapse.  Is this expected behaviour at this time?

Thanks!

**Comment by nikku** [comment]
Gonna be adressed with https://github.com/bpmn-io/bpmn-js/issues/510.

**Comment by nikku** [comment]
Fixed with next release.
