### ISSUE TITLE
Missing Extension properties on some elements in Camunda platform 8

### ISSUE THREAD

**Issue by david-d-le** [camunda/camunda-modeler#3365]
### Problem you would like to solve

There is missing Extension properties option on some elements (data store, data object, data input) in Camunda Platform 8.

![image](https://forum.camunda.io/uploads/default/original/3X/4/e/4ef64f24870d730bc0b9a078b5ad173152bd8ea0.png)

### Proposed solution

Add Extension properties option into Modeler for Platform 8. The generic extension element should be supported on all BPMN elements.

### Alternatives considered

None.

### Additional context

Forum thread for this feature request on: [https://forum.camunda.io/t/missing-extension-properties-on-some-elements-in-camunda-platform-8/41528](https://forum.camunda.io/t/missing-extension-properties-on-some-elements-in-camunda-platform-8/41528)

**Comment by philippfromme** [comment]
I have root-caused the issue. It requires a fix in `zeebe-bpmn-moddle`: https://github.com/camunda/zeebe-bpmn-moddle/issues/43
