### ISSUE TITLE
Cannot connect to C8 with custom SSL in some cases handled correctly by zbctl

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3366]
### Describe the bug

Cannot connect to C8 with custom SSL in some cases handled correctly by zbctl.

See linked support case: https://jira.camunda.com/browse/SUPPORT-13807

### Steps to reproduce

See linked support case.

### Expected behavior

Whenever I can connect with zbctl, I should be able to do that with Camunda Modeler.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

### Additional context

[SUPPORT-13807](https://jira.camunda.com/browse/SUPPORT-13807)

**Comment by nikku** [comment]
As I found out recent versions of `zeebe-node` completely break the communication with Zeebe. And if I say _completely_ I mean it (https://github.com/camunda-community-hub/zeebe-client-node-js/issues/290).

https://github.com/camunda-community-hub/zeebe-client-node-js/pull/291 is a fix that we'd need to apply locally or get incorporated into `zeebe-node`. Installing it locally you'll see that communication with Zeebe (unauthorized _and_ authorized) is fixed, when it was broken in `5.7.0` and earlier.

### Before fix applied

![screenshot pKgFKw](https://user-images.githubusercontent.com/58601/214661851-875522b1-f55e-4758-90ea-ebcbae768508.png)


### With https://github.com/camunda-community-hub/zeebe-client-node-js/pull/291 applied locally 

```
npm install -w app zeebe-node@github:camunda-community-hub/zeebe-client-node-js#pin-dependencies
```

![screenshot 6Ai6cL](https://user-images.githubusercontent.com/58601/214662115-b44a4540-4dc0-4fc2-9241-59c91e0434c5.png)

**Comment by nikku** [comment]
I'll need to follow up with this issue based on [our new test bed](https://github.com/camunda/zeebe-connection-test).

Maybe (hopefully) this becomes a configuration issue. https://github.com/camunda/camunda-modeler/issues/3366#issuecomment-1404108469 is outdated.

**Comment by nikku** [comment]
Closing this as won't fix. 

In the Camunda Modeler certificates used to validate a secured connection to Zeebe must be signing authority root certificates, not the server certificate itself (https://github.com/camunda/camunda-modeler/issues/3326#issuecomment-1405764329).

We are now eagerly validating the correctness of certificates (https://github.com/camunda/camunda-modeler/pull/3411) and improved our documentation on this matter (https://github.com/camunda/camunda-platform-docs/pull/1652), too.
