### ISSUE TITLE
Flag HTTL for C7 BPMN and DMN

### ISSUE THREAD

**Issue by toco-cam** [camunda/camunda-modeler#3369]
### Problem you would like to solve

- Many users do forget to set History Time To Live (HTTL), which frequently leads to problems and support cases in the long term as the database can't be cleaned up properly.
- Starting with Caumduna 7.19, deployments of models without HTTL defined will be rejected.

### Proposed solution

Flag HTTL on DMN and BPMN models as mandatory

### Alternatives considered

Yes, all stakeholders agreed that a forced HTTL flag is the way to go.

**Comment by nikku** [comment]
We should introduce a lint error for 7.19+ diagrams to support this.

**Comment by nikku** [comment]
CC @christian-konrad I guess this falls into our investment areas.

**Comment by christian-konrad** [comment]
@nikku yes, should be part of the next iteration(s)

**Comment by christian-konrad** [comment]
@toco-cam this will be delivered soon to Modeler
