### ISSUE TITLE
Cannot Run Camunda Modeler >=5.0.0 When Located in Folder Shared over Network

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#3370]
### Describe the bug

Running Camunda Modeler >=5.0.0 when located in a folder shared over the network results in a crash. Camunda Modeler versions <5.0.0 do not crash. In Camunda Modeler 5 Electron was updated from v12 to v17 (cf. https://github.com/camunda/camunda-modeler/pull/2797/commits/a0884ac240623932233722558e92522d21e0b535).

### Steps to reproduce

1. Locate Camunda Modeler >=5.0.0 in folder shared over network
2. Run Camunda Modeler
3. Camunda Modeler crashes

### Expected behavior

Camunda Modeler does not crash.

### Environment

- OS: Windows 10
- Camunda Modeler Version: >=5.0.0

### Additional context

Related to https://github.com/electron/electron/issues/27356
Related to https://bugs.chromium.org/p/chromium/issues/detail?id=103902#c27
Jira issue: https://jira.camunda.com/browse/SUPPORT-15522

**Comment by nikku** [comment]
As the [original issue states](https://bugs.chromium.org/p/chromium/issues/detail?id=103902#c27) this is a security feature and I want to trust the Chrome maintainers on this.

The user _may_ get around it (exposing themselves to security risks by [disabling the Chrome / Electron sandboxing](https://www.electronjs.org/docs/latest/tutorial/sandbox#disabling-chromiums-sandbox-testing-only).

Closing the issue as won't fix.

**Comment by philippfromme** [comment]
Makes sense, thanks for clarifying.
