### ISSUE TITLE
Entering a date in the past crashes the current DateTime form element

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3380]
### Describe the bug

When we try to enter a date in the past say 1800 and then we access the calendar the Datetime form element crashes as we cannot edit the date anymore

### Steps to reproduce

1. Create a form with datetime picker
2. In the datetime picker field enter a year in the past in the Form preview
3. Click on the calendar element and we could see that the calendar for the entered past year is displayed
4. Now try to make any changes to the calendar or by typing in the field
5. We could see that the current element has crashed and no changes are effective to it

https://user-images.githubusercontent.com/85225325/211035620-74e0272e-b568-41bc-a9b9-1b2b5fbbf240.mp4

### Expected behavior

Entering a date in the past should also be possible

### Environment

- OS: [Windows 10]
- Camunda Modeler Version: [5.7.0 rc-1]
- Execution Platform: [Camunda Cloud]

**Comment by Skaiir** [comment]
We've disabled dates prior to 1900 as a temporary fix. We will however figure out a proper fix for this in the future, and it's tracked [here](https://github.com/bpmn-io/form-js/issues/533). Nevertheless, this remains fixed upstream and we chose for now not to support dates pre-1900.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/41d2d9bed5c426d2a07dba4064ea668682160d18
