### ISSUE TITLE
Disabling and enabling the Datetime field persists the values only in the date field and not in time field

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3383]
### Describe the bug

When we enter Date and time values in the Datetime field and disable and enable the field again we could see that the date valuea is persisted and not the time

### Steps to reproduce

1. Create a new form
2. Add the date time element-> choose the subtype as Datetime
3. Now enter values into each field in the form preview
4. Disable the field
5. enable the field again
6. We could see that the value or the date is persisted and not the time

https://user-images.githubusercontent.com/85225325/211040787-15591929-c8e3-4d25-b0b0-bbb36a79d272.mp4

### Expected behavior

Align the behavior of the date and time fields while we disable and enable the field

### Environment

- OS: [Windows 10]
- Camunda Modeler Version: [5.7.0 rc-1]
- Execution Platform: [Camunda Cloud]

**Comment by Skaiir** [comment]
Fixed upstream via https://github.com/bpmn-io/form-js/pull/495

**Comment by nikku** [comment]
Disabling should consistently clear all fields.

This is restored via https://github.com/camunda/camunda-modeler/pull/3422

![capture AgGegd_optimized](https://user-images.githubusercontent.com/58601/216344851-f6d08dd8-83b5-4790-b23a-a9397b76a747.gif)
