### ISSUE TITLE
unclear behavior of increment function in the Number field 

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3384]
### Describe the bug

When we have a number field and a form input number provided to it say "5" when we try to apply the increment to it by entering a increment value to it say 10, the increment does not apply to the input value provided rather starts from 0 and increments by the number provided for increments. It is not clear how the increment should be applied to the input value,

### Steps to reproduce

1. Create a new form
2. Add a number form element
3. To the number field add a form input value as "5"
4. In the properties panel enter the increment value as "10"
5. Click on the up arrow in the preview of the number field we could see that the increment is not applied to the number inputted but starts from 0

https://user-images.githubusercontent.com/85225325/211042575-5385ef92-0d26-4318-9b12-971cfe429fa0.mp4

### Expected behavior

Unclear behavior of increment function in the Number field 

### Environment

- OS: [ Windows 10]
- Camunda Modeler Version: [5.7.0 rc-1]
- Execution Platform: [ Camunda Cloud]

**Comment by Skaiir** [comment]
This is expected behavior, the increment doesn't dictate the amount that the arrow increments by, but rather the increments which are valid for the field.

It seems here that the confusion is more one of language than anything else.

**Comment by Skaiir** [comment]
Ah, actually there's a bigger bug at play here, the validation for the increment doesn't work anymore. If the validation was there the behavior would be crystal clear. Will provide a fix shortly.

**Comment by Skaiir** [comment]
Fixed upstream via https://github.com/bpmn-io/form-js/commit/9b339dc275752b3f560199faf4159608b2d669b0

**Comment by nikku** [comment]
https://github.com/camunda/camunda-modeler/pull/3422 restores the validation to provide additional guidance to the user:

![capture LGVWaI_optimized](https://user-images.githubusercontent.com/58601/216344151-9a13d5ae-05fb-4531-a9cf-cc65228e5419.gif)
