### ISSUE TITLE
Validate `zeebe:candiateUsers` support

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3385]
### Problem you would like to solve

We shipped https://github.com/camunda/camunda-modeler/issues/3151 without the usual support through lint rules. As a result you cannot learn when it is supported in our tool stack.

### Proposed solution

Add validation rules to indicate this works in Camunda 8.2+.

### Alternatives considered

None.

### Additional context

Came up in a [recent conversation](https://camunda.slack.com/archives/GP70M0J6M/p1673021988031899).

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/2a92253696c5d55f0589771c9c6cb64345b8783f
