### ISSUE TITLE
As a User, I cannot use multi-instance on a task with a template applied

### ISSUE THREAD

**Issue by CatalinaMoisuc** [camunda/camunda-modeler#3396]
_This supports https://github.com/camunda/product-hub/issues/1851._

### Describe the bug

As a User, I cannot model in Camunda Modeler a task that has a template applied to it and is also multi instance.

### Steps to reproduce

1. model a task
2. apply any template to it
3. make it multi instance
4. see properties panel not displaying the section that I need to configure the multi instance i.e. `Input Collection`

See recording:

https://user-images.githubusercontent.com/25924333/212100132-9bc7e225-3b80-46f0-a7f0-70ef78fa8c0d.mov

### Expected behavior

When I apply a template to a task and then I make the task multi instance, the respective Properties Panel section should appear.

### Environment

- OS: any
- Camunda Modeler Version: 5.7
- Execution Platform: Camunda 8
- Installed plug-ins: irrelevant

----

Depends on https://github.com/bpmn-io/bpmn-js-properties-panel/issues/907

**Comment by nikku** [comment]
Also reported via https://github.com/camunda/connectors-bundle/issues/470 and https://github.com/bpmn-io/bpmn-js-properties-panel/issues/907.

**Comment by barmac** [comment]
Let's discuss it in the next iteration planning. Moving to _ready_. We can still move it to backlog.

**Comment by nikku** [comment]
FYI @christian-konrad. This is a medium sized issue and we did not prioritize it.

**Comment by barmac** [comment]
This will be fixed upstream via https://github.com/bpmn-io/bpmn-js-element-templates/pull/27
