### ISSUE TITLE
Illegal configuration on task does not validate

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3397]
### Describe the bug

As it looks like illegal configuration on `bpmn:Task` elements is not captured using the validation rules: 

![capture fg6YdT_optimized](https://user-images.githubusercontent.com/58601/212102286-ba2afa29-52cc-4c72-a00a-5fc75db97510.gif)

### Steps to reproduce

1. Open [test.bpmn](https://github.com/camunda/camunda-modeler/files/10402957/task-with-input-template-applied.bpmn.txt) in Camunda Modeler
2. See no indication of illegal `zeebe:taskDefinition:type` and `zeebe:input` bindings being present on the task

### Expected behavior

Either this is illegal and gets validated, too, or it is displayed in the properties panel.

### Environment

- OS: Any
- Camunda Modeler Version: v5.7.0
- Execution Platform: Camunda Cloud

### Additional context

None.

**Comment by philippfromme** [comment]
Interesting case. So far the lint rules only account for things that can be modeled through the UI. It is not validated that elements do _not_ have extension elements that aren't expected to exist (e.g. a plain task having a task definition). Shouldn't we prevent applying the element template in the fist place? You cannot repair the XML afterwards unless you use undo or edit the XML.

**Comment by nikku** [comment]
Yes we should fix the root cause instead -> (https://github.com/camunda/camunda-bpmn-js/issues/232). I just wanted to cross-check here if there may be different options.

**Comment by philippfromme** [comment]
I think verifying all buggy behavior of the properties panel etc. shouldn't be the responsibility of the linter. ➕ 1️⃣  for fixing #3398.

**Comment by philippfromme** [comment]
I'll close this issue. The actual bug is #3398.
