### ISSUE TITLE
Property panel shows list elements in alphabetical order

### ISSUE THREAD

**Issue by MarcusMue** [camunda/camunda-modeler#3400]
### Describe the bug

When adding list items in property panel the next time it opens it changed the order based on its content (alphabetically). It is very hard to edit items where order matters using the property panel. It doesn't respect the item order.

### Steps to reproduce

1. create a connector input item as list
2. add bbb, aaa, ccc as list values
3. close and reopen properties
4. now the order of the values does no longer reflect what you can see in then BPMN XML (or what was shown before in the property panel)

### Expected behavior

Use the same order of list values in modeler property panel as in XML.

### Environment

Windows 10, Camunda Modeler 5.7.0, Camunda 7

**Comment by nikku** [comment]
@MarcusMue Thanks for opening this issue.

It has been a longer standing UX impediment that we [fixed recently](https://github.com/camunda/camunda-modeler/blob/develop/CHANGELOG.md#key-changes-in-properties-panel). Please give the latest [nightly](https://downloads.camunda.cloud/release/camunda-modeler/nightly/) a try and report any issue that you can find.
