### ISSUE TITLE
Support Error Boundary events with errorCodeVariable and errorMessageVariable for Camunda Platform 8 

### ISSUE THREAD

**Issue by lzgabel** [camunda/camunda-modeler#3402]
### Problem you would like to solve

With https://github.com/camunda/zeebe/issues/11388, Zeebe now supports Error Boundary events with `errorCodeVariable` and `errorMessageVariable`.

Allow specifying specific variable names for the `errorCode` and `errorMessage` in the process model (BPMN). The specified variables will be created with as values the error code and error message provided along with the thrown error, respectively. For example, `errorCodeVariable: 'errCode'` would end up creating a process variable named `errCode` with as value the thrown error's error code. `errorMessageVariable` will allow specifying the variable that will contain the error message.

Currently, Error Boundary events with `errorCodeVariable` and `errorMessageVariable` are not supported in the Modeler for Camunda 8 BPMN diagrams.

### Proposed solution

The Modeler allows the creation of Error Boundary events with `errorCodeVariable` and `errorMessageVariable`.

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/24605947/213460249-4b744f3b-5e50-4a52-a75a-b73e81675e6a.png">

### Alternatives considered

/

### Additional context

Sample XML:

```xml
<bpmn:boundaryEvent attachedToRef="task" id="error-boundary-event" name="error-boundary-event">
      <bpmn:errorEventDefinition errorRef="error_c2c5e107-4c33-4b53-97e8-b09332230a2a" id="errorEventDefinition_11a12a8b-6496-4070-8379-543e1eac52e6">
        <bpmn:extensionElements>
          <zeebe:error errorCodeVariable="errorCode" errorMessageVariable="errorMessage"/>
        </bpmn:extensionElements>
      </bpmn:errorEventDefinition>
</bpmn:boundaryEvent>
<bpmn:error errorCode="ERROR" id="error_c2c5e107-4c33-4b53-97e8-b09332230a2a"/>
```

**Comment by nikku** [comment]
@lzgabel Could you elaborate how this relates to https://github.com/camunda/camunda-modeler/issues/3319? Feels like especially around "errorCode mapping" we're re-implementing the same thing in different ways.

**Comment by nikku** [comment]
Moving back to inbox to get some more insights on usage here.

**Comment by nikku** [comment]
As [clarified internally](https://camunda.slack.com/archives/CSQ2E3BT4/p1674145158818329?thread_ts=1674144892.889129&cid=CSQ2E3BT4) this merely allows a user to retrieve the (dynamically generated) error code and message with the purpose to store it in the context of the running scope, i.e. process. 

I suggested to re-think this and consider providing such variables via the local (boundary event ) scope instead and allow to map them via the existing output mapping feature, which is a powerful one and will become even more powerful in the future:

![image](https://user-images.githubusercontent.com/58601/213530563-d9ce7319-e320-45b1-a611-03672a2d6fb2.png)

**Comment by lzgabel** [comment]
Hi @korthout. Do you have other ideas? Because I can't see the internal communication news, I don't know whether you have reached an agreement internally.

**Comment by nikku** [comment]
@lzgabel We're going to share additional information with you on this issue. 

https://github.com/camunda/camunda-modeler/issues/3402#issuecomment-1397433971 is just a heads-up that we're currently discussing this. Would what I sketched solve your use-case, too? I'm aware that it would require a re-work of https://github.com/camunda/zeebe/pull/11388 in some sort.

**Comment by korthout** [comment]
@lzgabel This became an interesting internal discussion on how we want to expand functionalities. It is becoming clear that we want to use something other than extension elements in BPMN for this.

Instead, we believe the way forward is to use a similar approach as how you added the multi-instance properties to the [completion condition expression](https://docs.camunda.io/docs/next/components/modeler/bpmn/multi-instance/#completion-condition). The `errorCode` and `errorMessage` could then be available to the output mappings of the error catch event, like @nikku showcased above.

However, some discussion and user testing may be necessary to determine the naming of these properties. For now, we'll leave the feature camunda/zeebe#11388 as it is, but it will require some changes before the 8.2 release.

I'll open an issue in Zeebe for this. Would you be willing to contribute to this again @lzgabel? We see this as an essential step toward our vision for Zeebe.

**Comment by lzgabel** [comment]
> I'll open an issue in Zeebe for this. Would you be willing to contribute to this again?

@korthout Yes. Assign the task to me anytime, anywhere.
