### ISSUE TITLE
I as Zeebe user want to set backoff timeout between failed tasks

### ISSUE THREAD

**Issue by aivinog1** [camunda/camunda-modeler#3419]
### Problem you would like to solve

I want to set up backoffs for failed tasks but via BPMN XML, as described [here](https://github.com/camunda/zeebe/issues/11101). We need to support it in the Camunda Modeler because it is the primary editor for Zeebe's BPMN diagrams. We are ready to take it because [the BPMN API negotiated](https://github.com/camunda/zeebe/pull/11339#pullrequestreview-1241821331).

### Proposed solution

I see the flow as something like this:
- [x] https://github.com/camunda/zeebe-bpmn-moddle/issues/42
- [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/860
- [ ] https://github.com/camunda/zeebe/pull/11339
- [ ] and update the corresponding libraries and test it end to end

Feel free to correct me if you see that that could be improved :) 

### Alternatives considered

I can't see any decent alternatives for this task, I think that it should be implemented :) 
Editing BPMN XML in the text editor, maybe 🙈

### Additional context

This is for Camunda 8 a.k.a. Zeebe.

**Comment by nikku** [comment]
@aivinog1 Is this issue already defined (https://github.com/camunda/zeebe/issues/11101)? If not, let's consider it once it becomes actionable for us.

**Comment by nikku** [comment]
Closing this as the [engine PR](https://github.com/camunda/zeebe/pull/11339) is closed.
