### ISSUE TITLE
Moving around canvas (hand tool) when using Pools and Lanes is difficult

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#342]
When you are using Pools with lanes and you are zoomed in, you have to activate the hand tool manually rather than selecting white space to drag/move around the canvas.  This is not a problem when you are not using Pools and lanes, because selecting the canvas allows easy navigation.

Current workaround if you have to active and deactivate the hand tool, zoom out and select white space/canvas or use arrow keys on keyboard

Request: When selecting and dragging inside of a lane, this is the same as selecting the canvas and dragging.

**Comment by benhoffmann** [comment]
Hi Stephen, this issue relates to a former one of mine, feel free to join the discussion there as well. #238

**Comment by StephenOTT** [comment]
closed in favour of #238
