### ISSUE TITLE
Resizable Linting Panel

### ISSUE THREAD

**Issue by codygulley** [camunda/camunda-modeler#3420]
### Problem you would like to solve

For users with smaller screens and/or lower resolution screens, the bottom linting section takes up a good amount of screen real estate - especially when combined with other open bottom sections (e.g. Log). This is a problem because linting icons are only shown in the modeler when the linting bottom section is open. 

### Proposed solution

Add a resize handler to the Linting bottom section so that the height can be changed dynamically like that of the Log bottom section.

### Alternatives considered

There are no real other alternatives to solving this issue because the linting section must be open for lint icons to appear.  A workaround may be to create a plugin that does min-max height based on width, but that does not solve the root problem.

### Additional context

Currently using Camunda Modeler 5.7.0

**Comment by pinussilvestrus** [comment]
Related to https://github.com/camunda/camunda-modeler/issues/2959

**Comment by smbea** [comment]
I believed this was achieved with https://github.com/camunda/camunda-modeler/pull/3509
