### ISSUE TITLE
Modeler re-arranges `zeebe:input` values in XML on change

### ISSUE THREAD

**Issue by igpetrov** [camunda/camunda-modeler#3424]
### Describe the bug

Hi folks,

I found a weird behavior on camunda-modeler where it re-arranges `zeebe:input` values. It is only reproducible in camunda-modeler and not in SaaS.

The impact of that can be described as following.

Given **non-hidden** value `<zeebe:input target="xxx" />` staying in XML first in order and dependent **hidden** value `<zeebe:input source="=&#34;value-&#34;+xxx" target="yyy" />` staying second in XML.

When the first value (`xxx`) is edited, the `camunda-modeler` changes the order of two fields making `xxx` going second therefore breaking FEEL evaluation.

Delivering platform connectors heavily relies on consistent order during FEEL evaluation.

### Steps to reproduce

Please see video demonstration.

https://user-images.githubusercontent.com/108870003/216367453-2305c688-691f-4577-8171-e789d7ef2549.mp4

Given connector element template. Please see, that some fields are dependent on each other via context and FEEL evaluation. Also, please pay attention on the order.

```
{
  "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
  "name": "Bug Connector",
  "id": "io.camunda.connectors.SortOfBug.v1",
  "version": 1,
  "description": "This buggy template demonstrates a use-case when new values are appended to the end of BPMN XML",
  "icon": {
    "contents": "data:image/svg+xml;utf8,%3C%3Fxml version='1.0' encoding='utf-8'%3F%3E%3Csvg version='1.1' id='Extra_Large' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' viewBox='0 0 3261 1200' style='enable-background:new 0 0 3261 1200;' xml:space='preserve'%3E%3Cstyle type='text/css'%3E .st0%7Bfill:%23FA4616;%7D%0A%3C/style%3E%3Cg%3E%3Cpath class='st0' d='M0,0h1200v1200H0V0z M124.2,1075.8h951.6V124.2H124.2V1075.8z M604,309.5h124.2v363.6 c0,164.3-93.2,263.4-250.4,263.4c-154.3,0-245.4-97.2-245.4-263.4V309.5h124.2v363.6c0,91.2,38.1,146.2,124.2,146.2 c83.1,0,123.2-52.1,123.2-146.2V309.5z M964.6,309.5c0,44.1-32.1,74.1-76.1,74.1c-44.1,0-76.1-30-76.1-74.1 c0-45.1,32.1-76.1,76.1-76.1C932.5,233.4,964.6,264.4,964.6,309.5z M826.4,442.7h124.2v487.8H826.4V442.7z M1784,517.9 c0,133.2-88.1,212.4-223.4,212.4h-112.2v200.3h-124.2v-621h236.4C1697.8,309.5,1784,389.6,1784,517.9z M1657.8,517.9 c0-68.1-39.1-108.2-110.2-108.2h-99.2v221.4h99.2C1618.7,631.1,1657.8,591,1657.8,517.9z M2201.7,442.7h124.2v487.8h-124.2v-55.1 c-33.1,39.1-85.1,61.1-158.3,61.1c-132.2,0-225.4-104.2-225.4-249.4c0-144.2,91.2-250.4,225.4-250.4c71.1,0,125.2,25,158.3,67.1 V442.7z M2201.7,687.1c0-84.1-50.1-142.2-129.2-142.2c-79.1,0-128.2,55.1-128.2,142.2c0,81.1,44.1,140.2,128.2,140.2 C2148.6,827.4,2201.7,772.3,2201.7,687.1z M2629.4,824.4h49.1v106.2h-65.1c-118.2,0-169.3-56.1-169.3-171.3V547.9H2386V442.7h58.1 V309.5h124.2v133.2h109.2v105.2h-109.2v212.3C2568.3,803.3,2581.3,824.4,2629.4,824.4z M3214.3,647.1v283.5h-124.2V661.1 c0-74.1-38.1-122.2-111.2-122.2s-117.2,50.1-117.2,133.2v258.4h-124.2V279.5h124.2v213.4c31.1-37.1,80.1-57.1,147.2-57.1 C3124.2,435.7,3214.3,518.9,3214.3,647.1z M3200,279.5h21.7v4.2h-8.5v25.8h-4.8v-25.8h-8.5V279.5z M3261,279.5v30h-4.8v-22.8 l-9.7,22.8h-3.6l-9.7-22.8v22.8h-4.8v-30h6l10.3,23.4l10.3-23.4H3261z'/%3E%3C/g%3E%3C/svg%3E%0A"
  },
  "category": {
    "id": "connectors",
    "name": "Connectors"
  },
  "appliesTo": [
    "bpmn:Task"
  ],
  "elementType": {
    "value": "bpmn:ServiceTask"
  },
  "groups": [],
  "properties": [
    {
      "type": "Hidden",
      "value": "io.camunda:http-json:1",
      "binding": {
        "type": "zeebe:taskDefinition:type"
      }
    },
    {
      "label": "Endpoint path",
      "description": "Supposed to send to https://httpbin.org/anything/{Endpoint path}",
      "type": "String",
      "binding": {
        "type": "zeebe:input",
        "name": "endpointPath"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "Camunda Secret Header",
      "description": "Supposed to append X-Camunda-Header = {Camunda Secret Header}",
      "type": "String",
      "binding": {
        "type": "zeebe:input",
        "name": "camundaSecretHeader"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "URL for operation addQueueItem",
      "type": "Hidden",
      "value": "=\"https://httpbin.org/anything/\"+endpointPath",
      "binding": {
        "type": "zeebe:input",
        "name": "url"
      }
    },
    {
      "label": "Headers",
      "description": "I am secret header but will never be evaluated because I go before input value above",
      "type": "Hidden",
      "value": "={\"X-Camunda-Header\":camundaSecretHeader, \"Content-Type\":\"application/json\"}",
      "binding": {
        "type": "zeebe:input",
        "name": "headers"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "id": "methodGet",
      "label": "I am okay, since I am a constant",
      "type": "Hidden",
      "value": "get",
      "binding": {
        "type": "zeebe:input",
        "name": "method"
      }
    }
  ]
}
```

1. Create a new BPMN diagram with element template above. Save and see the order of `zeebe:input` fields:
```
<zeebe:ioMapping>
  <zeebe:input target="endpointPath" />
  <zeebe:input target="camundaSecretHeader" />
  <zeebe:input source="=&#34;https://httpbin.org/anything/&#34;+endpointPath" target="url" />
  <zeebe:input source="={&#34;X-Camunda-Header&#34;:camundaSecretHeader, &#34;Content-Type&#34;:&#34;application/json&#34;}" target="headers" />
   <zeebe:input source="get" target="method" />
</zeebe:ioMapping>
```

2. In the modeler, enter missing values `endpointPath` and `camundaSecretHeader`. Save and see the new order of fields changed:
```
<zeebe:ioMapping>
  <zeebe:input source="=&#34;https://httpbin.org/anything/&#34;+endpointPath" target="url" />
  <zeebe:input source="={&#34;X-Camunda-Header&#34;:camundaSecretHeader, &#34;Content-Type&#34;:&#34;application/json&#34;}" target="headers" />
  <zeebe:input source="get" target="method" />
  <zeebe:input source="echo" target="endpointPath" />
  <zeebe:input source="xxxxx" target="camundaSecretHeader" />
</zeebe:ioMapping>
```
3. `Deploy` diagram and `Start` instance.
4. Fields are serialized to JSON in the same order.
5. See related error message that some of the fields cannot be evaluated:
```
failed to evaluate expression '{url:"https://httpbin.org/anything/"+endpointPath,headers:{"X-Camunda-Header":camundaSecretHeader, "Content-Type":"application/json"},method:"get",endpointPath:"echo",camundaSecretHeader:"xxxxx"}': no variable found for name 'camundaSecretHeader'
```

### Expected behavior

I would expect that `zeebe:input` are serialized in the same order as defined in the element template

--- or ---

I can control the order of the fields manually, so that I can always put dependent fields after dependency when I would like to build one value atop of another

--- or ---

FEEL context evaluated in graph manner with dependency resolution rather than instructional list.

### Environment

- OS: MacOS X Pro 13.1 Ventura
- Camunda Modeler Version: latest 5.7.0, and bleeding edge (assembled from source)
- Execution Platform: Camunda Platform docker image in core variant ([this one](https://github.com/camunda/camunda-platform/blob/main/docker-compose-core.yaml)). _Note: SaaS is working fine._
- Bare modeler

### Additional context

We, the Connectors team, are building several out-of-the-box connectors that rely on already completed HTTP connector. We call them platform connectors. While input for different connectors might be different, by the end of the day we collapse all user input into a regular HTTP request and send it via HTTP connector.

The major chunk of aggregation lies on top of hidden fields with FEEL context evaluation. This bug prevents us from doing so.

**Comment by igpetrov** [comment]
cc: @bastiankoerber FYI

**Comment by nikku** [comment]
Thanks for reporting. A clear break of the existing contract indeed.

We fixed this earlier this month. Gotta investigate what broke it again :see_no_evil:.

**Comment by nikku** [comment]
Please ensure you use a recent nightly. The fixes are [yet to be released](https://github.com/camunda/camunda-modeler/blob/develop/CHANGELOG.md#key-changes-in-properties-panel).

**Comment by igpetrov** [comment]
Confirmed that nightly worked out
