### ISSUE TITLE
I can't create or open BPMN file

### ISSUE THREAD

**Issue by akassab1** [camunda/camunda-modeler#3429]
### Describe the bug

i installed and extracted camunda 5.7.0 win64 and tried to use it but it give me message
"
![oops](https://user-images.githubusercontent.com/124773152/217480707-4a5c4bbf-acef-4c66-8b52-efeb07662562.jpg)
oops, this shouldn't happen"

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Expected behavior

it should work

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by nikku** [comment]
Please share your full details (i.e. which platform you are using).
