### ISSUE TITLE
Association missing when element is appended via dragging

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3436]
### Describe the bug

Given I select a task, when I drag Data Store Reference from append anything, the association is missing. It works fine when I click the Data Store Reference though.

![capture MMfyhi_optimized](https://user-images.githubusercontent.com/58601/217796994-8b5503e1-7003-4502-946d-823b3992b84d.gif)

### Steps to reproduce

See description.

### Expected behavior

Association should be created regardless I click or drag shape.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.8.0-rc.0
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by nikku** [comment]
CC @smbea

**Comment by nikku** [comment]
@smbea https://github.com/camunda/camunda-modeler/issues/3436#issuecomment-1424140374 is missleading.

On context pad drag this just works, _if_ connect is allowed:

![capture bMrgdW_optimized](https://user-images.githubusercontent.com/58601/217822059-7006edd5-fffd-461b-9bf8-6d013a427644.gif)

In the case you mention it is _not_ allowed, as sequence flow connection across sub-process boundaries is not a thing:

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js/pull/1843.

**Comment by marstamm** [comment]
closed via https://github.com/camunda/camunda-modeler/pull/3501
