### ISSUE TITLE
Text annotation resizing glitches

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3438]
### Describe the bug

https://user-images.githubusercontent.com/28307541/217777679-09132e2c-05a9-45db-b720-efa30535a5b2.mov

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Expected behavior

The vertical part should resize according to the text size as it does when I change text (mostly).

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.8.0-rc.0
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by nikku** [comment]
Please verify if I understand correctly: If you shrink a text area horizontally using the resize handles _then_ you'd expect automatic vertical resizing to happen?

I honestly think this is an edge case. As a user I am in full control to resize in both directions at the same time. I get visual feedback as well and can use the diagonal resize handles to help me out.

**Comment by barmac** [comment]
Yes, or I shouldn't be able to resize so that text doesn't fit the annotation anymore -> see SubProcess case.

Feel free to close it if it's an edge case.

**Comment by nikku** [comment]
Let's close this and see if it pops up again in user feedback.
