### ISSUE TITLE
Create/append search should prefer items starting with typed text

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3439]
### Problem you would like to solve

I was surprised to discover that I have to scroll the menu to find End Event after typing "en", even though it's the only element which starts with "en". IMO it should be on top of the list.

https://user-images.githubusercontent.com/28307541/217778860-452750ee-f2df-4666-92c9-4d797b717779.mov

### Proposed solution

If an item starts with the searched text, it should appear on top.

### Alternatives considered

Leave it as is.

**Comment by nikku** [comment]
CC @smbea I found the same thing, trying to search for `ter` (Terminiate End Event).

**Comment by nikku** [comment]
Good question. Maybe it makes sense to look at this in a more holistic manner; consider group names, too, and consider display (with group headers or not)?

An (simple) alternative would be to only match from the start of a token; from what I understand this is what @barmac stumbled upon. `en` should match `End` rather than `went`.

One assumption I have (not tested) is that re-ordering elements in the search results will confuse me.

**Comment by nikku** [comment]
CC @YanaSegal. Maybe you have some general UX insights to share.

**Comment by smbea** [comment]
Me and @YanaSegal discussed this topic yesterday and ended up discussing how the search could work in a more general aspect.

* Search by "starts with" or "contains strict term". For example:
   * If you search for "en":
     * "end event" will match
     * "start event" would not match
   * If you search for "end": "error end event" will also match
* Search by group name too
* Keep groups during search and do not re-order entries. Instead, re-order groups by relevance of search results
   * Prioritization order would be: label > description > group
   
With this discussion, the capability of collapsing/expanding groups also came up. I created a separate issue for this: https://github.com/bpmn-io/diagram-js/issues/764

**Comment by nikku** [comment]
Depends on https://github.com/camunda/camunda-bpmn-js/pull/393 to be released and incorporated.

**Comment by nikku** [comment]
Unfortunately not fully addressed (yet):

![capture iDtIjs_optimized](https://github.com/user-attachments/assets/683a4ba0-6131-484a-8969-e17c4bc97bef)

(Fails with `Event` as a search term, expected to prioritize `Event-based Gateway` over other search results).

**Comment by nikku** [comment]
I looked into this again, via https://github.com/bpmn-io/diagram-js/pull/953. First I thought that it would be unexpected that we still _group_ search results (while the results are actually in a chaotic order). However https://github.com/camunda/camunda-modeler/issues/3439#issuecomment-1481069503 backed up that we want to:

* Still have items grouped
* Show most relevant group first

:arrow_right: This is what we do today, and will ship, cf. https://github.com/bpmn-io/diagram-js/pull/953.
