### ISSUE TITLE
Paste elements changes pool size

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#344]
When I copy elements from within a pool and try to paste them to another pool, the second pool's size is changed to the size of the first one.

Occurs both in Windows and Mac versions

![copyandpaste](https://cloud.githubusercontent.com/assets/17595149/16075086/a8fbfa3a-32ed-11e6-81c4-57c39b067096.gif)

**Comment by nikku** [comment]
Nice bug :balloon:.

**Comment by ricardomatias** [comment]
Related to bpmn-io/bpmn-js#178
