### ISSUE TITLE
Connect tool should activate with the selected element

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3441]
### Problem you would like to solve

It is annoying that I have to click previously selected shape when using shortcut.

https://user-images.githubusercontent.com/28307541/217780609-a45d64a8-5987-49cb-9a79-118997adea7c.mov

### Proposed solution

Given I selected an element, when I use the connect tool shorcut C, it should activate with the selected element as the source.

### Alternatives considered

Do nothing.

**Comment by nikku** [comment]
Thinking about it a little bit more I'm not sure if I like this suggestion. Let me elaborate:

The tools purpose (and name) is _global connect tool_. It should allow to connect quickly different elements from source to target. Testing what you suggest on a bigger diagram I'd need to manually de-select the currently selected element, which breaks my flow.

What we could do, of course, is to automatically de-select the current element to make that happen. However either way selecting the current element will have negative impact on the modeling flow _I think_.

**Comment by barmac** [comment]
Perhaps this could play nicely with binding `Escape` to deselect action. We don't have it right now though.

**Comment by nikku** [comment]
> Perhaps this could play nicely with binding Escape to deselect action. We don't have it right now though.

I think that would be too complicated. Rather I'd like to have dedicated shortcuts for it. Same goes for create vs. append. Similar, but also very different.

**Comment by barmac** [comment]
I checked how Miro and Excalidraw solve this. In both cases, shortcut deselects the current shape and activates global connection tool. Based on this, I think we can close the issue.
