### ISSUE TITLE
JPEG and PNG export glitches on message flow markers

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3442]
### Describe the bug

Message flow markers miss part. Notice it applies both to the start and the end.

![test2](https://user-images.githubusercontent.com/28307541/217784238-e9175383-7d33-423e-9d58-31a975e66d14.jpeg)

![test2](https://user-images.githubusercontent.com/28307541/217784244-6a288ffd-abec-480e-b12a-8b975d3be1c6.png)

### Steps to reproduce

1. Create a collaboration diagram with message flow
2. Export as PNG or JPEG
3. now this happens

### Expected behavior

No glitches

### Environment

- OS: MacOS
- Camunda Modeler Version: 5.8.0-rc.0
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by nikku** [comment]
Likely related to https://github.com/bpmn-io/bpmn-js/commit/eb4b54f7ffdb55e340aac291c33a5f4d66e246b3.
