### ISSUE TITLE
Add Cmd+Shift+[ and Cmd+Shift+] as tab switch shortcuts on MacOS

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3444]
### Problem you would like to solve

I am frustrated that I cannot use my favorite tab switch shortcut in the Modeler. The app should follow established patterns in order to embrace smooth UX.

### Proposed solution

Add `Cmd+Shift+[` and `Cmd+Shift+]` as tab switch shortcuts on MacOS.

### Alternatives considered

Do nothing and grow user's frustration.

### Additional context

Browsers implement both shortcuts: Ctrl+Tab and Cmd+Shift+[.

**Comment by barmac** [comment]
@nikku @philippfromme what are the common shortcuts on Linux and Windows?

**Comment by nikku** [comment]
> what are the common shortcuts on Linux and Windows?

`CTRL+TAB` / `CTRL+SHIFT+TAB`. These work just fine.

**Comment by nikku** [comment]
Seems like we need MacOS specific switching [here](https://github.com/camunda/camunda-modeler/blob/develop/app/lib/menu/menu-builder.js#L306).

**Comment by nikku** [comment]
There seems to be different shortcuts to accomplish the same thing [available on MacOS](https://superuser.com/questions/609821/hotkey-for-switching-between-tabs-window-panes-on-a-mac).

**Comment by codygulley** [comment]
The shortcuts of `Cmd+Tab` and `Cmd+SHIFT+TAB`  are MacOS level shortcuts and thus can't be used. 

We can provide different shortcuts per OS. Allowing us to maintain `Control+TAB` / `Control+SHIFT+TAB` for non-MacOS and implement something else for MacOS - maybe the suggested `Cmd+SHIFT+[` / `Cmd+SHIFT+]` would suffice? 

If we can get an agreement on the shortcuts to use then I am happy to open a PR!

**Comment by nikku** [comment]
@codygulley I've provided hints where the change needs to happen https://github.com/camunda/camunda-modeler/issues/3444#issuecomment-1423968357.

As you second @barmac's comment do you want to go ahead and contribute these shortcuts (MacOS only).
