### ISSUE TITLE
Text area in properties panel can shrink below line height

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3445]
### Describe the bug

Text area can shrink below line height which makes it unreadable.

### Steps to reproduce

https://user-images.githubusercontent.com/28307541/217788821-edb2623a-1a62-4072-96fd-e44c5bf3f3e4.mov

### Expected behavior

Minimum height should kick in.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.8.0-rc.0
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by Abhishek7Tech** [comment]
@barmac I would like to contribute. I will add min height property to text area.

**Comment by nikku** [comment]
@Abhishek7Tech We've already added one via https://github.com/bpmn-io/properties-panel/pull/214/files#diff-398d379cec6e774a099d60df565c9d947f4799b2c1bfab8825c3ba4fd0d900faR459.

We may simply add it to all text areas.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/e3e01f3d7b724a2009fc12fff23157030a5f42d0.

**Comment by marstamm** [comment]
closed via https://github.com/camunda/camunda-modeler/pull/3501
