### ISSUE TITLE
Use correct articles in form palette titles

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3448]
### Describe the bug

![image](https://user-images.githubusercontent.com/28307541/217792656-6d4c1b8b-e792-4ac3-9e4a-c3ef090962b4.png)

It should say "an image".

<img width="527" alt="image" src="https://user-images.githubusercontent.com/28307541/217793324-85ac024d-340c-49ad-8924-ece9feb6f0fc.png">

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Expected behavior

See description

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

### Additional context

FYI: @pinussilvestrus  @Skaiir

**Comment by pinussilvestrus** [comment]
Fixed upstream via https://github.com/bpmn-io/form-js/pull/545
