### ISSUE TITLE
Align on the lint error messages displayed based on the selected engine verison

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3451]
### Problem you would like to solve

Currently we could see two different types of error when we do not support elements in a particular engine version. So the below are the examples when we do not support elements in the selected engine version 8.1.

Error 1: Searchable selects are not supported by Camunda Platform 8.1
Error2: An <Escalation Intermediate Throw Event> is only supported by Camunda 8.2 or newer

https://user-images.githubusercontent.com/85225325/217846162-c0db8164-4acc-474d-9878-0974ad519ca4.mp4

Both the errors are resolved when we choose the engine version 8.2

### Proposed solution

Align on the lint error messages displayed on BPMN,Forms,DMN diagrams

### Alternatives considered

NA

**Comment by nikku** [comment]
CC @Skaiir @pinussilvestrus.

**Comment by nikku** [comment]
Bug fix for forms that superceedes this: https://github.com/camunda/camunda-modeler/issues/4646
