### ISSUE TITLE
"Check For Updates" menu option not hidden on MacOS when "disable-remote-interaction" flag is set

### ISSUE THREAD

**Issue by codygulley** [camunda/camunda-modeler#3457]
### Describe the bug

On MacOS, when the `disable-remote-interaction` flag is set to true, the Check for Updates menu item is still visible. 

![Screen Shot 2023-02-10 at 11 27 09 AM](https://user-images.githubusercontent.com/8097956/218168803-2dfd855d-e5de-4fe1-b8e0-91528b6969d3.png)

This is unlike in Windows where both the 'Check For Updates' and 'Privacy Preferences' are hidden under the Help menu when the flag is set to true.
 
![Screen Shot 2023-02-10 at 10 42 16 AM](https://user-images.githubusercontent.com/8097956/218168928-b8e6ce9a-db51-41db-8511-183561350f25.png)
(Notice 'Check for Updates' and 'Privacy Preferences' are missing when flag is set)

### Steps to reproduce

1. Create a `flags.json` file with content
```
{
  "disable-remote-interaction": true
}

```
2. add `flags.json` file to `resources` folder
3. Launch Camunda Modeler
4. From Menu bar select   'Camunda Modeler'

Notice that 'Check for Updates'  is still a visible option.

### Expected behavior

'Check for Updates' option should not be visible when `disable-remote-interaction` flag is set to true. 

### Environment

- OS: MacOS 12.6.1
- Camunda Modeler Version: 5.7.0
- Execution Platform: Camunda Platform
- Installed plug-ins:  []

### Additional context

Help menu code in [menu-builder.js](https://github.com/camunda/camunda-modeler/blob/6b5e71234746478e029125c86e7727242b4da9d0/app/lib/menu/menu-builder.js#L590)  checks for the `disable-remote-interaction` and hides them appropriately. 

There is no such check in the [mac-menu-builder.js](https://github.com/camunda/camunda-modeler/blob/58123a652018db7d73ce8274d98713eece3f6020/app/lib/menu/mac-os/mac-menu-builder.js#L33)

**Comment by nikku** [comment]
`disable-remote-interaction` does prevent interaction automatically initiated by the tool. It does not prevent manual update check by the user.

**Comment by codygulley** [comment]
Yes. Happy to make the change!

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/47ef3192bd79f938304fb749796ab281119d8978.
