### ISSUE TITLE
Add "cloud-bpmn" information to menuState object

### ISSUE THREAD

**Issue by gclaussn** [camunda/camunda-modeler#3458]
### Problem you would like to solve

When a plugin registers custom menu actions via `menu.js` in Camunda Modeler 5.x (https://docs.camunda.io/docs/components/modeler/desktop-modeler/plugins/#adding-menu-entries-to-the-modeler), the `menuState` object does not provide any information about the bpmn target type: Camunda Platform 7 (**bpmn**) or 8 (**cloud-bpmn**). Currently only the property `bpmn` with value `true` is provided by the `menuState` object.

To check this, add a log to the `enabled` function in a plugin's `menu.js` file and start the desktop modeler via command line:
```
enabled: function() {
  console.log(menuState);
  return menuState.bpmn;
}
```

The `menuState` has a lot of information including the tabs, which hold the target type information - e.g.:
```
tabs: [
  {
    file: [Object],
    id: '0op69ts',
    name: 'diagram_1.bpmn',
    title: '(new file)',
    type: 'cloud-bpmn'
  },
  {
    file: [Object],
    id: '1rcri3w',
    name: 'diagram_1.bpmn',
    title: '(new file)',
    type: 'bpmn'
  }
]
```
but there is also no information, which tab is currently active!

The information is needed for the BPMN Driven Testing community extension:
https://github.com/camunda-community-hub/bpmn-driven-testing

Since the extension does not support Camunda Platform 8, the Camunda Modeler plugin should also not be allowed to be enabled for BPMN models that are modeled for Camunda Platform 8.

### Proposed solution

In case of a BPMN model, the `menuState` object should provide an additional property called `bpmnType` with one of the following values depending on the target (Camunda Platform 7 or 8):
- `bpmn`
- `cloud-bpmn`

### Alternatives considered

The `menuState` object should provide the ID of the currently active tab, so that the already existing `tabs` property can be used to lookup the BPMN type.

### Additional context

Required for:
https://github.com/camunda-community-hub/bpmn-driven-testing/issues/114

The missing information is needed here:
https://github.com/camunda-community-hub/bpmn-driven-testing/blob/master/camunda-modeler-plugin/menu.js#L8

**Comment by nikku** [comment]
Thanks for opening this issue. I think it is reasonable to assume that you have access to the current tab (and its type) in the menu.

We already expose `tabs`. What is missing is `activeTab`:

![image](https://user-images.githubusercontent.com/58601/218726462-327e1989-19f8-4d9a-b5b9-8ff20f4b9e99.png)
