### ISSUE TITLE
I can configure errorMessageVariable for error events

### ISSUE THREAD

**Issue by deivarayanazhagappan** [camunda/camunda-modeler#347]
Use case:
Users can retrieve error message when the errorMessageVariable is set in the BPMN xml during deployment.

AT:
Adding errorMessageVariable to the errorEventDefinition for error start event that contains the error message, so that users can retrieve the reason for error.

Support case: https://app.camunda.com/jira/browse/SUPPORT-2313

Engine issue: https://app.camunda.com/jira/browse/CAM-5953

Documentation: https://stage.docs.camunda.org/manual/develop/reference/bpmn20/events/error-events/#error-start-event

**Comment by polenz** [comment]
It is implemented with bpmn-io/bpmn-js-properties-panel#191
