### ISSUE TITLE
Create a handle to close the properties panel

### ISSUE THREAD

**Issue by fml2** [camunda/camunda-modeler#3480]
### Problem you would like to solve

This all is about the modeler 5.8.0.

When the properties panel is in the closed state, there is a handle that appears when the mouse is moved on the right side of the window. When I click on the handle, the properties panel is displayed.

![grafik](https://user-images.githubusercontent.com/534392/221540327-49801998-549f-493d-a0a8-6864bfe4bf13.png)

However, if the panel is in the open state, there is no such handle. If I want to close the panel I can't do it by a click. Instead, I have to grab the left edge of the panel and move it to the right. This is inconvenient.

### Proposed solution

Create a handle (with an arrow pointing to the right) that would appear when the mouse is moved over the left panel edge. A click on the handle should close the panel.

### Alternatives considered

Dragging the left panel edge which is inconvenient.

**Comment by nikku** [comment]
Thanks for opening this issue. I actually stubled across this multiple times myself. Now we have something to act upon.

**Comment by nikku** [comment]
@oraliahdz Yes it is. Probably somewhere [here](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/PropertiesContainer.js#L171) we want to ensure that clicking the visual resize handle closes the properties panel. We can then go ahead and see if the additional visual handle is necessary.

**Comment by oraliahdz** [comment]
Hi @nikku should I flip the handle or do we need a new image to use when open?

![Screen Shot 2023-03-01 at 4 31 59 p m](https://user-images.githubusercontent.com/89615667/222281226-e1697d70-9655-491f-916e-7a0eaa87e79f.png)
![Screen Shot 2023-03-01 at 4 34 18 p m](https://user-images.githubusercontent.com/89615667/222281242-387ac09e-f2df-4f5f-878b-02c5f6337018.png)

**Comment by nikku** [comment]
@oraliahdz Let's try to use the existing outline instead as a handle:

I expect:

* I click the outline (which is not available when the properties panel is collapsed) => Properties panel closes
* I drag the outline (causing re-size) no collapse happens

**Comment by barmac** [comment]
This is already implemented.
