### ISSUE TITLE
Align colors with web modeler

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3481]
### What should we do?

Ensure that colors in desktop and web modeler are align.

* [ ] Simplify input colors #3540
* [ ] Align application blues
* [ ] Simplify on canvas colors

### Why should we do it?

Bring us closer to a uniform UI.

**Comment by nikku** [comment]
@YanaSegal Please link the overarching initiative to this issue.

You can find the colors we use in the tool [here](https://github.com/camunda/camunda-modeler/blob/develop/client/src/styles/_colors.less).

**Comment by YanaSegal** [comment]
You can find the color mapping for the blue shades here: 
https://www.figma.com/file/zgOi6eDZRprddwgMvjlFMi/color-migration?node-id=1%3A2

**Comment by nikku** [comment]
What are the semantic names we're going to reference these colors with? Is it going to be `--color-X-SOMENUMBER`? I'm asking because our previous scheme was different, and any change in color names is a potential breaking change for our sers.

**Comment by nikku** [comment]
I'd also suggest that an engineer trials these new colors beyond the modeler.

We'd need to ensure these actually work in different places where the old ones are being used.

Just one example is that the new "light color" really screams in your face when being used as a background for active inputs.

**Comment by nikku** [comment]
I personally feel that these colors overall scream into a users face, where the old ones were nicely muted (as I'd expect and know from most apps and websites I use).

**Comment by nikku** [comment]
To show some screens (just showcasing the basic change): 

![image](https://user-images.githubusercontent.com/58601/227128463-d2e13ef5-89b4-470d-a62f-0c09edbc1d46.png)

![image](https://user-images.githubusercontent.com/58601/227128575-e57ca29f-0938-417d-9bc2-3c46ff270b63.png)

![image](https://user-images.githubusercontent.com/58601/227129172-b34c49a7-a3a4-43d7-b6b7-9289a5dd320b.png)

**Comment by nikku** [comment]
We'll re-visit this once we decide to transition to Carbon UI. As of today, the Desktop Modeler uses a well defined color scheme, E2E, and is pleasent to use in the process.
