### ISSUE TITLE
Support conditional properties in Element Templates for Camunda 7

### ISSUE THREAD

**Issue by p-e-e-t-e-r** [camunda/camunda-modeler#3482]
### Problem you would like to solve

I was following the tutorial at [docs.camunda.io](https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/defining-templates/#defining-conditional-properties) since it seems to document both Camunda 8 and 7 versions.

I can always see the Username and Password fields in Modeler regardless of the selected Authentication Type.
C8 seems to work fine.

The reason I'm opening this ticket is that I think either the documentation is wrong (in case this is only available for C8) or there is a bug in Modeler.

### Proposed solution

Allow Camunda 7 element template to be used the same as Camunda 8. E.g. the Camunda 7 Template
```json
  {
    "name": "Test Task",
    "id": "com.camunda.example.TestTask",
    "appliesTo": [
      "bpmn:ServiceTask"
    ],
    "properties": [
    {
      "id": "authenticationType",
      "label": "Authentication Type",
      "type": "Dropdown",
      "choices": [
        {
          "name": "None",
          "value": "xx"
        },
        {
          "name": "Basic",
          "value": "basic"
        }
      ],
      "binding": {
        "type": "camunda:inputParameter",
        "name": "auth"
      }
    },
    {
      "label": "Username",
      "type": "String",
      "binding": {
        "type": "camunda:inputParameter",
        "name": "username"
      },
      "condition": {
        "property": "authenticationType",
        "equals": "basic"
      }
    },
    {
      "label": "Password",
      "type": "String",
      "binding": {
        "type": "camunda:inputParameter",
        "name": "pwd"
      },
      "condition": {
        "property": "authenticationType",
        "equals": "basic"
      }
    }
   ]
  }
```

Should have the same behavior as the Camunda 8 Template
```json
  {
    "$schema": "https://unpkg.com/browse/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
    "name": "Test Task",
    "id": "com.camunda.example.TestTask",
    "appliesTo": [
      "bpmn:ServiceTask"
    ],
    "properties": [
    {
      "id": "authenticationType",
      "label": "Authentication Type",
      "type": "Dropdown",
      "choices": [
        {
          "name": "None",
          "value": "xx"
        },
        {
          "name": "Basic",
          "value": "basic"
        }
      ],
      "binding": {
        "type": "zeebe:input",
        "name": "auth"
      }
    },
    {
      "label": "Username",
      "type": "String",
      "binding": {
        "type": "zeebe:input",
        "name": "username"
      },
      "condition": {
        "property": "authenticationType",
        "equals": "basic"
      }
    },
    {
      "label": "Password",
      "type": "String",
      "binding": {
        "type": "zeebe:input",
        "name": "pwd"
      },
      "condition": {
        "property": "authenticationType",
        "equals": "basic"
      }
    }
   ]
  }
```

### Alternatives considered
-

**Comment by codygulley** [comment]
I don't think this is a bug but rather a feature only available in Camunda 8. 
The docs you mentioned subtly states this:

> Camunda Platform 8 also supports these properties:
> 
> id: An identifier that can be used to reference the property in conditional properties.
> condition: A condition that determines when the property is active.

I think the word "also" here can be construed in this context as "both" rather than "only".

I would **LOVE** conditional to be supported in Camunda 7 element templates though. (;

**Comment by marstamm** [comment]
Hi,

@codygulley is correct, this is a feature only available in Camunda 8. I will convert this ticket to a feature request and move into the backlog.

It could be made clearer in the subsection "defining-conditional-properties" that this is not supported in Camunda 7. Pull requests with improvements are always welcome 😄 
Cf. docs repo: https://github.com/camunda/camunda-platform-docs/blob/main/versioned_docs/version-8.1/components/modeler/desktop-modeler/element-templates/defining-templates.md

**Comment by nikku** [comment]
Will be closed via https://github.com/camunda/camunda-platform-docs/pull/1795.
