### ISSUE TITLE
Support Due and Follow-Up Date Properties in Camunda 8 User Tasks

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda-modeler#3484]
### Problem you would like to solve

Currently, due and follow-up dates are a missing piece for user tasks in Camunda Platform 8. They will be supported with https://github.com/camunda/product-hub/issues/215.

### Proposed solution

The `dueDate` and `followUpDate` attributes are added through a new user task extension element called `taskSchedule`. The BPMN XML should look like the following example:

```xml
<userTask id="userTaskWithDates" name="userTaskWithDates">
    <extensionElements>
        <zeebe:taskSchedule dueDate="2023-02-24T14:29:00Z" followUpDate="=followUpDateVar"/>
    </extensionElements>
</userTask>
```

The `dueDate` and `followUpDate` attributes support static values and FEEL expressions. The expected output should be a valid ISO 8601 combined date and time representation (as with [time date timer events](https://docs.camunda.io/docs/next/components/modeler/bpmn/timer-events/#time-date)). For static values, it might be a good UX to validate the DateTime string in the modeler.

### Additional context

The Zeebe workflow engine will perform the following validations on the `dueDate` and `followUpDate` values:
* During BPMN resource deployment - if an expression is provided, assert that it is a valid FEEL expression.
* (ZPA stretch goal) During BPMN resource deployment - if a static value or static expression is provided, assert that a valid ISO 8601 DateTime string is provided.
* During user task activation - assert that a valid ISO 8601 DateTime string is provided.

The target release for this epic is Camunda Platform 8 `8.2.0`.

**Comment by marstamm** [comment]
Moving to ready to be picked up in the next planning as this has the target version 8.2

**Comment by philippfromme** [comment]
# Breakdown

* https://github.com/camunda/zeebe-bpmn-moddle/pull/45

**Comment by philippfromme** [comment]
@koevskinikola I assume, the linter should disallow using due and follow-up date before version 8.2?

**Comment by koevskinikola** [comment]
Hey @philippfromme, yes, user task due and follow-up dates will be supported from Zeebe `8.2.0` so we should disallow them in earlier versions.
