### ISSUE TITLE
Change sequence in Script Task Script section

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#3495]
### What should we do?

Change the sequence of the fields `FEEL expression` and `Result variable` in a Script task implemented as a FEEL expression.

They should be `Result variable` and then `FEEL expression`.

### Why should we do it?

I've modeled a process for Zeebe 8.0 where all tasks were implemented by Service Tasks just with an Output mapping. The task worker was a NOOP-worker and used only to complete the task.  

Here, the business logic in the modeler looks like this:

![grafik](https://user-images.githubusercontent.com/7870843/223089853-c8a9df19-d823-4fef-8f1e-ee6a75152c06.png)

It's common to most programming language to read the expression like `let a = b;` (or `Setze RVSATZAN = 0,093` in german).

As Zeebe 8.2 supports a FEEL, I want to switch my Service Tasks to Script tasks to get rid of my service task worker.

Now, using the section `Script`, the sequence of the fields are switched. First the expression, then the variable: 

![grafik](https://user-images.githubusercontent.com/7870843/223091020-e50f6b39-c52f-417f-b846-0b2d12304940.png)

This is confusing and lacks the readability. 

Keep it consistent with an output mapping.

**Comment by marstamm** [comment]
Hi @ingorichtsmeier , thank you for reporting. I agree, it is confusing and does not make sense. 

As this is an easy fix and will impact users with the 8.2 release, I'll move it to ready to be picked up in the next planning

**Comment by nikku** [comment]
Spot on find @ingorichtsmeier. Kudos!

**Comment by stephengarn** [comment]
Pardon my ignorance but where is this issue in the project folder? Every other issue is labeled except this one.

**Comment by nikku** [comment]
> Pardon my ignorance but where is this issue in the project folder?

Could you elaborate? What project folder to you refer to?

**Comment by stephengarn** [comment]
The screen shots which are referenced in the issue...where is the file that produces this view?

**Comment by ingorichtsmeier** [comment]
Hi @stephengarn, the repo with the process model is here: https://github.com/camunda-consulting/lohnsteuer-pap

The process model with the script tasks itself is on this branch: https://github.com/camunda-consulting/lohnsteuer-pap/blob/feel-script-tasks/src/main/resources/mpara-unterprozess.bpmn
