### ISSUE TITLE
Add a grid to our core modeling canvas

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3497]
### Problem you would like to solve

A grid provides the visual cue that snapping takes place on the diagram. It also helps users to distinguish canvas from contents.

### Proposed solution

Add a grid to the diagram modeling canvas (BPMN, DMN) if snapping happens.

* [x] Add to BPMN (https://github.com/camunda/camunda-bpmn-js/pull/266)
* [x] Add to DMN (https://github.com/camunda/camunda-dmn-js/pull/67)
* [x] Consumable for web-modeler, too (i.e. potentially integrated in [camunda-bpmn-js](https://github.com/camunda/camunda-bpmn-js) and friends)

### Alternatives considered

None.

### Additional context

Discussed in length in [this conversation](https://camunda.slack.com/archives/CKGH9LR40/p1677745515323909?thread_ts=1677743893.202279&cid=CKGH9LR40). @philippfromme previously sketched this in already.

**Comment by nikku** [comment]
@philippfromme Maybe you could dig up what the status of the existing grid proposal is. I think we can be pragmatic (ship it as an extension?) and include it in camunda-*-js.

Alternatively we ship it with the core of our toolkits and make it disableable behind a feature toggle.

**Comment by philippfromme** [comment]
It's currently shipped with bpmn-js but disabled by default (cf. https://github.com/bpmn-io/diagram-js/tree/develop/lib/features/grid-snapping/visuals). Since we usually don't ship features that aren't enabled by default, let's move it to a separate package and include it in camunda-bpmn-js.

**Comment by nikku** [comment]
Now available as a nicely supported external library: https://github.com/bpmn-io/diagram-js-grid.

**Comment by christian-konrad** [comment]
@nikku @philippfromme from what I see in bpmn.io, I would say don't hesitate and just add it to the products!

@YanaSegal even if we want to do it different later due to Carbon, I think we can just proceed and iterate.

**Comment by nikku** [comment]
This actually made it. :rocket:

**Comment by philippfromme** [comment]
> This actually made it. 🚀

Thanks to your contribution! ❤️
