### ISSUE TITLE
Copy and paste morphs event sub process to normal sub process

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#350]
When copying an event sub process and pasting it, it gets morphed to a normal sub process.

That's an awesome way to create error start events ;)

![copy-paste](https://cloud.githubusercontent.com/assets/17595149/16242415/91c0c33c-37f2-11e6-971c-2de4560117ea.gif)

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/issues/555 (fix available in nightly).

**Comment by benhoffmann** [comment]
It also morphs non-interrupting start events to interrupting ones. Was this fixed as well?
