### ISSUE TITLE
Uncaught exception when saving a model

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#351]
Try this on a Mac and you'll get the following message:

1. Create a new model
2. Hit the save file button
3. Click on Cancel

This also happens when cancelling other dialogues.

<img width="439" alt="uncaught-exception" src="https://cloud.githubusercontent.com/assets/17595149/16243500/da8f7f5e-37f7-11e6-9d2f-da93f9864d37.png">

**Comment by nikku** [comment]
Did you try out the latest nightly? Should be fixed there (via https://github.com/camunda/camunda-modeler/issues/337).
