### ISSUE TITLE
Ability to set the default execution version on new BPMNs via a flag in flags.json

### ISSUE THREAD

**Issue by codygulley** [camunda/camunda-modeler#3515]
### Problem you would like to solve

As an enterprise I have a specific version of the Camunda runtime installed e.g. 7.16.0 . I want the want the ability to default the execution version of BPMN diagrams to the version of the runtime I have deployed in my infrastructure via a flag in `flags.json` so that my end users won't create diagrams in a later version since new diagrams default to latest stable BPMN execution version. 

This is the screen I would like the ability to default via a flag.
<img width="429" alt="Screenshot 2023-03-20 at 3 45 34 PM" src="https://user-images.githubusercontent.com/8097956/226472721-d21de960-f878-4e5c-a23d-556249a66074.png">

### Proposed solution

Implement flags for the C7 and C8 engine platforms such that new diagrams will default to that execution version.

Note - I am only interested in C7 but the feature makes sense for both platforms. 

### Alternatives considered

Build a plugin somehow that would automatically default this...

### Additional context

 Two flags named like `default-c7-execution-engine-version` and `default-c8-execution-engine-version` ?

**Comment by nikku** [comment]
Makes loads of sense. Would you be interested in contributing that feature? If so I'd be happy to provide you with the necessary pointers.

**Comment by codygulley** [comment]
Hey @nikku !
I'd be happy to contribute if you could point me in the direction of where/how this needs to be implemented.  

I had a go at implementing this in the default engine profile; however, it still doesn't default to the supplied version I've supplied in flags.json.  Here is my attempt in my fork [branch commit](https://github.com/camunda/camunda-modeler/compare/develop...codygulley:camunda-modeler:feature/default-execution-version-flag) . 

I may be completely off on where/how to implement this so any direction helps!
Thanks!

**Comment by nikku** [comment]
@codygulley Your contribution looks promising. However flags are initialized late (during modeler initialization, not source loading), hence they cannot be retrieved eagerly. Do you mind creating a DRAFT PR from your feature branch so we can continue the discussion there?
