### ISSUE TITLE
Error when starting modeler-restapi

### ISSUE THREAD

**Issue by milmar02** [camunda/camunda-modeler#3518]
### Describe the bug

I have Camunda running in Kubernetes 1.21. When starting modeler-restapi the container fails to start with this output in the logs file:

/home/node/node_modules/toml/lib/parser.js:3833
      throw peg$buildException(null, peg$maxFailExpected, peg$maxFailPos);
      ^
[SyntaxError: Expected "#", "'", "[", "\"", "\n", "\r", [ \t], [A-Za-z0-9_\-] or end of input but "" found.] {
  expected: [
    { type: 'literal', value: '#', description: '"#"' },
    { type: 'literal', value: "'", description: `"'"` },
    { type: 'literal', value: '[', description: '"["' },
    { type: 'literal', value: '"', description: '"\\""' },
    { type: 'literal', value: '\n', description: '"\\n"' },
    { type: 'literal', value: '\r', description: '"\\r"' },
    { type: 'class', value: '[ \\t]', description: '[ \\t]' },
    {
      type: 'class',
      value: '[A-Za-z0-9_\\-]',
      description: '[A-Za-z0-9_\\-]'
    },
    { type: 'end', description: 'end of input' }
  ],
  found: '\x7F',
  offset: 0,
  line: 1,
  column: 1
}

Node.js v18.15.0

Environment variables are set according to the docker-compose.yaml:
https://github.com/camunda/camunda-platform/blob/main/docker-compose-web-modeler-beta.yaml

### Steps to reproduce

1. Deploy the container to kubernetes
2. wait till it starts
3. error occurs

### Expected behavior

modeler-restapi container starts as expected.

### Environment

- OS: Kubernetes 1.21
- Camunda Modeler Version: 0.8.0-beta
- Execution Platform: Camunda Platform self-managed
- Installed plug-ins: none

### Additional context

The error also occurs with other modeler versions.

**Comment by milmar02** [comment]
2 additions:
- I'm using Zeebe with a self-signed certificate
- Keycloak is connected to an external identity provider

**Comment by jfriedenstab** [comment]
Hi @milmar02,
Thank you for reporting this issue. Please note that this repository is actually used for the Camunda **Desktop** Modeler. For Web Modeler Self-Managed, please open a support issue in [Jira](https://jira.camunda.com) or ask your company's support contact to do so. We will then be happy to assist you.
