### ISSUE TITLE
Remove space make Sub-Process to small

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#352]
See screencast:

![animation](https://cloud.githubusercontent.com/assets/40038/16243997/2952e138-37fa-11e6-9e86-57b81e48ef43.gif)

(My screen capturing tool placed the mouse at the wrong position)

**Comment by philippfromme** [comment]
There are a few options here.

1. Prevent removing space entirely if layout would break
2. Only prevent removing space from subprocesses of which layout would break
3. Not preventing resize but instead adding an orange preview like the one that other shapes have that would visualize that the layout is going to break

What is the behaviour you would expect?

In general making the space tool smarter would also make it less predictable. Right now you can break the layout using the space tool in various ways like

![ezgif com-crop](https://cloud.githubusercontent.com/assets/7633572/16562101/89dd2eee-41fc-11e6-8846-2a1b19a670db.gif)

If we fix the issue regarding the layout of subprocesses being broken but don't fix other issues too the space tool will become more and more unpredictable. At the end it's a question of how smart we expect the user to be and how smart the user expects the space tool to be. Do we allow literally everything and expect the user to know what he's doing or do we prevent the user from breaking something from the beginning even he may know what he's doing.

**Comment by philippfromme** [comment]
We decided that we're definitely going to add a preview for resizing using the space tool since this feature should exist regardless of this ticket. I've created a ticket for this: https://github.com/bpmn-io/bpmn-js/issues/586

**Comment by nikku** [comment]
We won't do anything here any time soon. As part of the next Camunda Modeler release we improved the space-tool resize preview instead. This should give users a bit more assistance.

**Comment by falko** [comment]
That's fine with me, since any heuristic will never be perfect. The 
preview is already very helpful for such situations.

**Comment by nikku** [comment]
Closing this for now as we did substantial improvements on the preview.
