### ISSUE TITLE
Only provide variable suggestions in places where it is SAFE to do so

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3525]
### Problem you would like to solve

As a user I rely on variable suggestions to be correct; a tool providing assistance but being wrong leaves a bad feeling (cf. https://github.com/camunda/camunda-modeler/issues/3524).

### Proposed solution

Until we are able to define proper variable scoping (https://github.com/camunda/camunda-modeler/issues/3524) we limit (external) variable completion to fields that are backed by IO mappings (input/output).

### Alternatives considered

None.

### Additional context

Cf. https://github.com/camunda/camunda-modeler/issues/3524#issuecomment-1488395923 for implementation hints.

**Comment by nikku** [comment]
@ingorichtsmeier Not sure if I understand you correctly. Do you agree or disagree to the following statement:

> We should only provide suggestions where the suggestion is correct (i.e. because the variable has a high likelyhood to exist).
> 
> Conversely we should not suggest variables in places where we know they do not exist.

**Comment by ingorichtsmeier** [comment]
@nikku, 

I agree with these statements.

I was wondering about 

> Alternatives considered
> None.

An alternative (or better addition) to calculate the best suggestion is to provide insight to all variables and let the user influence the data. At least when it comes to variables given at process instance start or returned from a self-developed worker, this would be handy.

**Comment by nikku** [comment]
> An alternative (or better addition) to calculate the best suggestion is to provide insight to all variables and let the user influence the data. At least when it comes to variables given at process instance start or returned from a self-developed worker, this would be handy.

I 100% agree @ingorichtsmeier. We need to strike the balance between sensible completions (where the user provides us with hints) and NOT completing, where a completion would be wrong.

This is why @marstamm worked on the ability to inject "example data" into your process diagrams. That example data (i.e. output) represents data available in your process (i.e. available after you started the process using a start event.

The following screen capture shows what will be available in our modeler(s) soon: 

![capture YsomaM_optimized](https://user-images.githubusercontent.com/58601/228561302-f5c40246-c554-41cf-8ad7-a5d2adfc38ef.gif)

**Comment by ingorichtsmeier** [comment]
Cool stuff! Where do you store the example data? 

My guess is an extension tag in the XML.

Looking at the movie, I would propose to rename the field here. As it is technically an output of the none start event, the average user would see them as input data from the process instance start. 

Tasks inside the process diagram have output data. Here the name fits to the purpose.

**Comment by nikku** [comment]
CC @marstamm https://github.com/camunda/camunda-modeler/issues/3525#issuecomment-1489786416. Maybe you can elaborate further?

Indeed `task` does not work well for start events :see_no_evil:.

**Comment by marstamm** [comment]
I agree that the current naming can be confusing and really only fits the Task use-case. Maybe we can get it closer to what it actually does, add Variables to the current scope (or propagate them up to the nearest scoped parent if no mappings are present). I created https://github.com/camunda/camunda-modeler/issues/3530 to refine the wording,

> Where do you store the example data?

The example data is stored as a `zeebe:property` extension element in the XML
