### ISSUE TITLE
Morph deletes conditions on incoming Sequence Flows

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#353]
![2016-06-21-morph-deletes-conditions-of-incoming-sequence-flows](https://cloud.githubusercontent.com/assets/40038/16245244/37ab2032-3800-11e6-9360-92bbec473b0e.gif)

**Comment by nikku** [comment]
This got already fixed via https://github.com/camunda/camunda-modeler/issues/318. Somehow, it is not part of the nightly though.

**Comment by nikku** [comment]
Nightly simply did not build yet.

**Comment by nikku** [comment]
Closed via #318.
