### ISSUE TITLE
Form "Text" entry disappears when switching between modes 

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3533]
### Describe the bug

When I click the `=` sign to switch between markdown and templating, the element flickers in and out.

### Steps to reproduce

1. Create a new Diagram
2. Add a Text vie
3. In General > Text, switch to templating and back

![Recording 2023-03-30 at 15 37 18](https://user-images.githubusercontent.com/21984219/228854516-d64d3248-cb50-42ff-b346-5b56a46a4dea.gif)

### Expected behavior

The `=` sign is removed/added without visual disturbance, e.g. like the Image source entry 
![Recording 2023-03-30 at 15 41 26](https://user-images.githubusercontent.com/21984219/228855227-46448116-b99f-4432-86d1-29eee31d97a3.gif)

## Camunda Modeler system information
 * Version: 5.10.0-rc.0
 * Operating System: Linux x86_64 amd64
 * Plugins: <no plugins>
 * Execution Platform: Form - Camunda Platform 8

**Comment by smbea** [comment]
cc @pinussilvestrus @Skaiir

**Comment by marstamm** [comment]
Not sure if same problem: It also sets the cursor to the end when switching modes by keyboard:

![Recording 2023-03-30 at 15 46 49](https://user-images.githubusercontent.com/21984219/228856658-682ab020-434c-47ba-b2ad-c13678ac5997.gif)


Expected:

![Recording 2023-03-30 at 15 48 11](https://user-images.githubusercontent.com/21984219/228857068-a0bfdffc-9654-4daf-a5b9-b61a43ec2bca.gif)

**Comment by pinussilvestrus** [comment]
Thanks for letting us know. I assume it's not blocking the release? 

I added it to our team board to check.

**Comment by marstamm** [comment]
Yeah, this is a minor thing and not blocking 😄

**Comment by marstamm** [comment]
[q] Should this field be `feel` or `feelers templating`? Because it seems to behave like a default FEEL field right now, while [this PR](https://github.com/camunda/camunda-platform-docs/pull/1873) says it should be feelers.

![image](https://user-images.githubusercontent.com/21984219/228859485-1de869f0-1e0c-4cf1-9148-d37b1fcad379.png)

If it should support templating, than that would be blocking (and a separate issue). Also reproduceable on https://demo.bpmn.io/form

**Comment by marcosgvieira** [comment]
@marstamm I wasn't able to reproduce it anymore (I believe it was fixed as it's been a while), please if you still observe this behavior reopen this issue.
