### ISSUE TITLE
Rename field to configure job type from `Type` to `Job Type` 

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3534]
### What should we do?

Rename `Type` to `Job Type` in the properties panel Task definition section for service tasks:

![image](https://user-images.githubusercontent.com/58601/229077718-3087ead7-a63b-4f99-ba5d-5c3f4e02db4e.png)

This is an initial step to get users into the Zeebe mental model (we have tasks, but these are backed by jobs at run-time, executed through job workers).

### Why should we do it?

Better align modelers (talk about `task` and `type` and documentation `job` and `job type` all the way), cf. [this conversation](https://camunda.slack.com/archives/C026U8GBNSW/p1680086221893759).

**Comment by vishalsingh2972** [comment]
@nikku can you assign this to me, want to give this a try!

**Comment by nikku** [comment]
Happy to take your contribution in the form of a PR. We don't usually assign external contributors.

**Comment by nikku** [comment]
@barmac I believe we integrated/released this with the last release?

**Comment by barmac** [comment]
No, this change was merged after the RC was built, so it didn't make it to the code freeze: https://github.com/camunda/camunda-modeler/releases/tag/untagged-d7a57258826d3983a401
Note also that the change has not been released in the properties panel yet 🤦

**Comment by barmac** [comment]
I suggested to @philippfromme that it's a good opportunity to practice releasing libraries with @abdul99ahad :)
