### ISSUE TITLE
Track templates/connectors

### ISSUE THREAD

**Issue by smbea** [camunda/camunda-modeler#3539]
### What should we do?

We used to tracked the templates with ET but we don't track them now with Mixpanel.

We should consider tracking the applied template ids with `diagram.opened` and `diagram.deployed` events.

This also related to https://github.com/bpmn-io/bpmn-js-tracking/issues/19

### Why should we do it?

We want to understand the usage of element templates. See https://camunda.slack.com/archives/CKGH9LR40/p1680264740474189

**Comment by smbea** [comment]
Talking to @CatalinaMoisuc, this is related to https://github.com/bpmn-io/bpmn-js-tracking/issues/19 in the sense that we want to have the same tracking of this for both modelers. Since diagram opened/deployed isn't built in the core (it's done in each modeler), we can't handle its tracking with `bpmn-js-tracking`. 

We would need to figure out a way to handle these cases, perhaps an additional module on top of the tracking framework for these cases. We would also need to figure out also how to hook into these actions on both modelers.

**Comment by nikku** [comment]
> If we decide not to pursue this, we can just add the properties missing to deskop modeler events. Personally, this is what I would do for now until we want to invest some time into properly synchronising both modelers. Feel free to drop your thoughts (cc @nikku)

This is what I'd go for at the moment, too.
