### ISSUE TITLE
'cmmn-js-properties-panel' is not in the npm registry

### ISSUE THREAD

**Issue by mbateman** [camunda/camunda-modeler#354]
This might be temporary but I get the the following when doing npm install:

 Registry returned 404 for GET on https://registry.npmjs.org/cmmn-js-properties-panel

Removing the dependency from package.json and doing npm install https://github.com/bpmn-io/cmmn-js-properties-panel fixes this, but grunt distro is unhappy with this manually installed dependency:

'npm ERR! extraneous: cmmn-js-properties-panel@0.0.0 /Users/michael/camunda/projects/camunda-modeler/node_modules/cmmn-js-properties-panel\n'

**Comment by nikku** [comment]
Yes, this is temporary. See attached commit for (temporary fix).
