### ISSUE TITLE
Enable signal end event

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-modeler#3546]
### What should we do?

- Change the linter to allow Signal End Events in Camunda Platform `8.3 Alpha`.
- Add the ability to specify Input Mappings for Signal End Events
- Add the ability to specify the Signal Name as an expression (prefixed by `=`)

> **Note** that Signal End Events support input mappings in C8 to pass along variables with the broadcasted signal.

<img width="1006" alt="Screenshot 2023-04-04 at 15 18 18" src="https://user-images.githubusercontent.com/3511026/229804495-5ee98536-cbda-4d24-a783-6b72945c3dd2.png">

### Why should we do it?

Zeebe will support signal end events with `8.3.0-alpha1`:

- https://github.com/camunda/zeebe/pull/11927

**Comment by korthout** [comment]
I forgot to mention that the Signal Name can be defined statically or as an expression (prefixed by =). I've updated the issue description.

**Comment by nikku** [comment]
Thanks for this issue. We'll do our best to prioritize it.

**Comment by korthout** [comment]
@nikku I think this is resolved by:
- https://github.com/camunda/camunda-modeler/issues/3555

**Comment by nikku** [comment]
Indeed. Good catch. Closed via #3555
