### ISSUE TITLE
Cannot open DMNs where `typeRef` is missing

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3553]
### Describe the bug

Modeler fails to open this DMN:

```xml
<definitions xmlns="https://www.omg.org/spec/DMN/20191111/MODEL/" id="definitions" name="definitions" namespace="http://camunda.org/schema/1.0/dmn">
  <decision id="decision" name="decision">
    <decisionTable id="decisionTable">
      <input id="InputA">
        <inputExpression id="InputExpression1044165151">
          <text>pincode</text>
        </inputExpression>
      </input>
      <output id="OutputB" name="isNegativeArea"/>
      <rule id="excelRow2">
        <description>yes</description>
        <inputEntry id="A2">
          <text>515004</text>
        </inputEntry>
        <outputEntry id="B2">
          <text>"no"</text>
        </outputEntry>
      </rule>
    </decisionTable>
  </decision>
</definitions>
```

It crashes on `translate` trying to translate missing `typeRef`s. The attribute is optional though.

### Steps to reproduce

Try to open DMN file pasted above.

### Expected behavior

Should open the file.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

### Additional context

Discovered internally: https://camunda.slack.com/archives/CKGH9LR40/p1681250904177009

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js/CHANGELOG.md#1412.

**Comment by barmac** [comment]
Not really, the bug was fixed in literal expression but is still present on the decision table.

**Comment by barmac** [comment]
This will be fixed via https://github.com/bpmn-io/dmn-js/pull/750

**Comment by barmac** [comment]
Now it's fixed upstream.

**Comment by nikku** [comment]
:crossed_fingers:

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/3566
