### ISSUE TITLE
Support Signal Intermediate Throw and End Event in Camunda 8.3

### ISSUE THREAD

**Issue by skayliu** [camunda/camunda-modeler#3555]
### What should we do?

* https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/93
* https://github.com/camunda/linting/issues/52
* https://github.com/bpmn-io/bpmn-js-properties-panel/issues/909
 
#### Current support

![image](https://user-images.githubusercontent.com/7633572/234564847-892f3113-bbf1-469a-b118-fb7ef2ac8116.png)

### Why should we do it?

 Zeebe v8.3.0-alpha1 will support signal intermediate throw  and end events (cf. https://github.com/camunda/zeebe/pull/12206).

---

Related to https://github.com/camunda/product-hub/issues/657

**Comment by korthout** [comment]
We forgot to mention that the Signal Name can be defined statically or as an expression (prefixed by =). I've updated the issue description.

**Comment by philippfromme** [comment]
@korthout Is a signal reference required? Will a signal throw / end event without a signal reference be rejected by the engine?

**Comment by koevskinikola** [comment]
Hey @philippfromme, yes a signal reference is required. If a `SignalEventDefinition` doesn't reference a `Signal`, an error is thrown and the deployment is rejected.

**Comment by philippfromme** [comment]
> Hey @philippfromme, yes a signal reference is required. If a `SignalEventDefinition` doesn't reference a `Signal`, an error is thrown and the deployment is rejected.

Since signal start events are already supported, do they also require a signal reference? We don't show an error yet.

**Comment by skayliu** [comment]
> > Hey @philippfromme, yes a signal reference is required. If a `SignalEventDefinition` doesn't reference a `Signal`, an error is thrown and the deployment is rejected.
> 
> Since signal start events are already supported, do they also require a signal reference? We don't show an error yet.

@philippfromme,Yes, they also require a signal reference.

**Comment by nikku** [comment]
Fixed upstream via https://github.com/camunda/linting/pull/53, https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/93, andhttps://github.com/bpmn-io/bpmn-js-properties-panel/issues/909.
