### ISSUE TITLE
Process Variables schemas from out mappings are not merged

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3562]
### Describe the bug

When I have a Process Variable defined in a Mapping with multiple sources, only one is used.

### Steps to reproduce

1. Create a Process with 2 ServiceTasks
2. add an output mapping to each, writing the same variable but with different schemas
3. Try to get suggestions for the variable
4. Only 1 schema is used

![image](https://user-images.githubusercontent.com/21984219/233593503-a3b24b6d-35d4-48d6-a48f-2ea1e130adab.png)

### Expected behavior

The schema is merged, as we do with example data:

![image](https://user-images.githubusercontent.com/21984219/233593817-aee65e9b-56b1-4042-8f5f-718e5f8929d6.png)

## Camunda Modeler system information
 * Version: 5.10.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform 8

**Comment by nikku** [comment]
@marstamm Is this going to be addressed via https://github.com/bpmn-io/variable-resolver/pull/15? If so, let's mark this as `fixed upstream`.

**Comment by marstamm** [comment]
Yes, this will be addressed with the linked PR. I think we should move it to "in Progress" rather than "fixed upstream", as it is not merged yet?
