### ISSUE TITLE
Receive Task after Event-Based Gateway is not supported

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3569]
#### The rule should detect the following modeling patterns

Correct:

![diagram](https://user-images.githubusercontent.com/28307541/233603841-bdb2c0dd-4345-4c73-a502-12fbabd47ece.svg)
![diagram (2)](https://user-images.githubusercontent.com/28307541/233603962-51291f9e-35b3-4aeb-971e-7d0a49dca3a7.svg)

Incorrect:

![diagram (1)](https://user-images.githubusercontent.com/28307541/233603914-676a89c3-d86a-43f2-9648-f5c47bab1993.svg)

#### How does the rule improve the BPMN diagram?

Prevent deployment errors for <=C8.2.

#### Rule Details

* Name: 
* Default notification level: `error`

#### What alternatives did you consider? 

Do nothing.

---

Context: https://camunda.slack.com/archives/CKGH9LR40/p1682069620734539

**Comment by nikku** [comment]
Fixed upstream via https://github.com/camunda/linting/pull/54 and https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/82.
