### ISSUE TITLE
Cancel open file => popup with javascript error

### ISSUE THREAD

**Issue by Wadeck** [camunda/camunda-modeler#357]
Using a fresh Camunda Modeler 1.1.1, I click on "Open a Diagram" then I cancel the operation. There is a popup with an error that appeared. This is also the case if I cancel using the cross icon of the popup.
![javascript_error](https://cloud.githubusercontent.com/assets/2662497/16406453/aa88f06c-3d0e-11e6-8126-6805d4aea62f.png)
![open_file_cancel](https://cloud.githubusercontent.com/assets/2662497/16406452/aa882542-3d0e-11e6-9cc0-8f0866e49489.png)

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/337

**Comment by nikku** [comment]
To be fixed with next Camunda Modeler release. Fixed in the [nighty builds](https://camunda.org/release/camunda-modeler/nightly/) already.
