### ISSUE TITLE
Modeler does not read trusted intermediate certificates from Windows trust store

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3574]
### Describe the bug

As documented [the modeler requires the full certificate chain](https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/flags/#zeebe-ssl-certificate) in order to validate secured connections to Camunda 8 / Zeebe.

My setup is using an intermediate cert the following trust chain:

```
Custom ROOT Cert
Custom Intermediate Cert
Custom Server Cert (used to configure Zeebe)
```

Trying to use the "auto-discovery" features on Windows we found that it only ready root certificates, not intermediate certificates:

![image](https://user-images.githubusercontent.com/58601/235113007-55b8438d-1e7d-4ca1-be48-f7f44e6eb515.png)

As a result I need to put the intermediate certificate as a trusted root. That yields a prominent warning in the certificate manager. 

### Steps to reproduce

0. On Windows
1. Generate a three step certificate chain `ROOT -> INTERMEDIATE -> SERVER`
2. Put `ROOT` into root certificate store
3. Put `INTERMEDIATE` in intermediate certificate store
4. **Modeler does not validate `SERVER` certificate**

If I force put `INTERMEDIATE` into root certificate store, then modeler validates the connection.

### Expected behavior

We read both root and intermediate certificate stores on Windows.

### Environment

- OS: Windows 10
- Camunda Modeler Version: v5.10.0
- Execution Platform: Camunda Cloud
- Installed plug-ins: None

### Additional context

Reported via SUPPORT-15806.

**Comment by nikku** [comment]
Marked https://jira.camunda.com/browse/SUPPORT-15806 as depending on this issue.

**Comment by nikku** [comment]
To unblock users with this issue that cannot use the [proposed workaround](https://github.com/camunda/camunda-modeler/issues/3574#issuecomment-1537923670) we could make it possible to load certificates from the modeler root:

#### `{{MODELER_ROOT}}/resources/flags.json`

Loaded in accordance with [search path documentation](https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/flags/#configure-in-flagsjson).

```json
{
  "zeebe-ssl-certificate": "{{MODELER_ROOT}}/resources/certs.pem"
}
```

#### `{{MODELER_ROOT}}/resources/certs.pem`

Certificate file that is loaded in accordance with flags.

**Comment by barmac** [comment]
So potentially we could just add `certs.pem` to the files that we already detect automatically: flags.json, plugins, element templates. Flag could stay as is, but you would have a way to include the certs in a custom build.

**Comment by nikku** [comment]
Closing this issue as [serving full chain certificates on the remote end](https://github.com/camunda/camunda-modeler/issues/3574#issuecomment-1537923670) is an industry  practice and the recommended way to handle such scenario. 

We include this tip as a dedicated entry in our [troubleshooting guide](https://docs.camunda.io/docs/components/modeler/desktop-modeler/troubleshooting/#the-remote-endpoint-presents-an-untrusted-certificate).
