### ISSUE TITLE
Example Data docs links to `next` documentation

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3582]
### Describe the bug

The link is referencing unreleased version

### Steps to reproduce

1. Click the link ![image](https://user-images.githubusercontent.com/21984219/235615517-7931fcc4-a167-4e8a-b83f-10fd2c22bbcb.png)
2. It leads to https://docs.camunda.io/docs/next/components/modeler/data-handling/

### Expected behavior

It links to https://docs.camunda.io/docs/components/modeler/data-handling/

## Camunda Modeler system information
 * Version: 5.11.0-rc.0
 * Operating System: Linux x86_64 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform 8

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/50fba26bf06b89e33785445118b8c47d6fe407f7.
