### ISSUE TITLE
Saving New File Before Closing Camunda Modeler Doesn’t Keep It Open

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#3586]
### Describe the bug

https://user-images.githubusercontent.com/7633572/235845737-f0d435bf-2c56-47fd-a0a8-5ef2846a636e.mp4

### Steps to reproduce

1. Create a new file
2. Close the modeler
3. Confirm saving the file
4. Open the modeler
5. File is not open

### Expected behavior

File is open

### Environment

- OS: Windows 10
- Camunda Modeler Version: 5.11-rc.0

**Comment by nikku** [comment]
I can reproduce this issue.

**Comment by nikku** [comment]
> I think that close-all-tabs is not the correct action to take during shutdown - instead, we should do save-all-tabs and save the workspace after this is done. It should not matter whether the tabs are open or closed when closing the app.

I agree with that.
