### ISSUE TITLE
Unable to open process in Operate after deployment

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#3596]
### Describe the bug

Operate answers with 
```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
```
When I click on the link after deploying for the first time:

![grafik](https://user-images.githubusercontent.com/7870843/236781913-c63bb6e3-f3f2-46c5-ad4d-06523422b169.png)

### Steps to reproduce

1. create a new process model
2. make it executable
3. deploy it to a fresh SaaS cluster
4. Click on the link from the Popup.

### Expected behavior

Operate opens the deployed process instead of an error page.

The link provided from the modeler is:

```
https://bru-2.operate.camunda.io/7c1184c4-040c-4d11-af4e-ef08888fe6e6/instances/?process=PaymentProcess&version=all&active=true&incidents=true
```

It should be (no trailing `/` in path name part):

```
https://bru-2.operate.camunda.io/7c1184c4-040c-4d11-af4e-ef08888fe6e6/instances?process=PaymentProcess&version=1&active=true&incidents=true
```

### Environment

**Camunda Modeler system information**
 * Version: 5.10.0
 * Operating System: Windows 10 amd64
 * Plugins: Cloud Connect, bpmn-js Token Simulation, Migration, Transaction Boundaries, Camunda Property Infos, Tooltip Plugin
 * Execution Platform: BPMN - Camunda Platform 8

**Comment by barmac** [comment]
I can reproduce the issue. It looks like Operate does not accept trailing slash anymore, as when I remove the slash I see this page:

<img width="1792" alt="image" src="https://github.com/camunda/camunda-modeler/assets/28307541/5d4f20d2-7082-4a4c-9b35-1f67cd08eb02">

We could consider using `version` information which is returned by the gateway to deep link to exactly the deployed version. It's a separate feature though.

**Comment by nikku** [comment]
I'd rather suggest to file this as an Operate bug report.

It is breaking publicly available URIs. If old operates supported a URI without trailing `/` then we could also move our link to that scheme, of course.

**Comment by nikku** [comment]
I [reached out](https://camunda.slack.com/archives/C9B5270DA/p1683791676783079) just to make them aware and confirm your observations.

**Comment by barmac** [comment]
Generally, it feels quite unusual to me to use both trailing slash and query parameters in one URL.

**Comment by nikku** [comment]
Confirmed that new links are the ones to choose, and are backwards compatible. Let's remove the trailing slashes.

**Comment by barmac** [comment]
I created an issue for the exact version link: https://github.com/camunda/camunda-modeler/issues/3605
