### ISSUE TITLE
Cannot hit Ctrl-S in Properties Panel

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-modeler#360]
Saving via Keyboard shortcut works when drawing panel is selected, but not when I am editing properties in the panel

**Comment by philippfromme** [comment]
I cannot reproduce this bug (Windows 10, Camunda Modeler 1.1.1). Saving while in properties panel works perfectly fine here. Which version do you use?

**Comment by berndruecker** [comment]
Some Nightly. Strange. I will check again when it does occur exactly (and come back when I know)

**Comment by ricardomatias** [comment]
I could also not reproduce it on Linux. Closed for lack of reproducibility.
