### ISSUE TITLE
Disable form elements via FEEL expression

### ISSUE THREAD

**Issue by tobiasschaefer** [camunda/camunda-modeler#3600]
### Problem you would like to solve

Currently, various elements of a form (number fields, text fields, checkboxes, ...) can be disabled statically with a `disabled` checkbox. However, I need to disable an element dynamically, i.e. based on the value of a variable and would like to use a FEEL expression.

### Proposed solution

It would be similar to the conditional hide-if where it is already possible to configure a FEEL expression.

IMHO the UI would need a toggle to switch between the static checkbox and a FEEL expression. Technically, the FEEL expression would be sufficient because `=false` and `=true` would work, but from a usability point of view this would be a step back.

### Alternatives considered

A very hacky alternative:
I could duplicate each element and configure one to be disabled and one to be enabled and then use hide-if to conditionally hide one or the other. 

### Additional context

@jonathanlukas likes the idea and asked me to file a feature request: https://camunda-platform.slack.com/archives/C6WGNHV2A/p1683309976821459?thread_ts=1683289802.281679&cid=C6WGNHV2A

**Comment by nikku** [comment]
CC @pinussilvestrus @christian-konrad I guess this is on our roadmap?

**Comment by nikku** [comment]
Thanks for opening this issue. Moving to `backlog` for the time being.

**Comment by tobiasschaefer** [comment]
Thanks @pinussilvestrus , thanks @nikku 

If the `readonly` property supports FEEL it will perfectly cover my use case 👍

**Comment by pinussilvestrus** [comment]
`readonly` support with FEEL is fixed upstream: https://github.com/bpmn-io/form-js/issues/396. As we do not intend to support `disabled` via FEEL as well, let's move this to fixed upstream.
