### ISSUE TITLE
Lint `[0]` based collection access in FEEL

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3604]
### Problem you would like to solve

The fact that FEEL starts arrays at index `1` is unexpected for professional developers. We should assist our users that expect `[0]` to work.

### Proposed solution

* [ ] We lint FEEL and detect `[0]` access, and tell users this is not going to work

### Alternatives considered

None.

### Additional context

None.

**Comment by barmac** [comment]
This makes sense.

**Comment by nikku** [comment]
We already did this I believe @barmac?

**Comment by barmac** [comment]
Added to changelog via https://github.com/camunda/camunda-modeler/pull/4750
I also updated the milestone of this issue accordingly.
