### ISSUE TITLE
Be able to provide helpful hints in a contextual, non-intrusive manner using tooltips

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3611]
### Problem you would like to solve

As a user of the modeler I have issues navigating the properties panel and understanding individual items due to the lack or overload of information:

* **Too little information:** In some places, the properties panel showcases a very small amount of information. This leads to me not being able to understand how a certain feature works (https://github.com/camunda/camunda-modeler/issues/3588).
* **Too much information:** In some places we show large amounts of information, specifically in connectors or timer definitions (cf. additional context). Much of that is duplicate and tends to become irrelevant once you know. Such wall of text can distract users from quickly skipping through the properties panel to discover or re-identify relevant information.

### Proposed solution

Structure helpful hints in a manner that it is non-intrusive using tooltips:

* Tooltip shows structured information (code snippets, external links)
* Tooltip presence is indicated on the UI (on element/section hover/focus)
* Tooltip displays on demand (when user hovers/focuses a certain section)
* Tooltip can be focused to copy from, but also follow links presented in there
* Tooltips can be populated in different ways:
    * via `bpmn-js-properties-panel` and such
    * via element templates
  
### Alternatives considered

None.

### Additional context

Product hub epic: https://github.com/camunda/product-hub/issues/893

Current UI in connectors, meant to be _user friendly_; assistive documentation highlighted:

<img width="300" src="https://github.com/camunda/camunda-modeler/assets/58601/76887154-10ed-493b-a951-348385b49112" />

-----

Breakdown:
1st iteration:
- https://github.com/bpmn-io/properties-panel/issues/202
  - https://github.com/bpmn-io/properties-panel/pull/263
- https://github.com/bpmn-io/properties-panel/issues/261
- [x] Integrate tooltips in `bpmn-js-properties-panel`
    - [x] Identify places where we want to add tooltips: [comment 1](https://github.com/camunda/product-hub/issues/893#issuecomment-1639667813), [comment 2](https://github.com/camunda/product-hub/issues/893#issuecomment-1639701409), [comment 3](https://github.com/camunda/product-hub/issues/893#issuecomment-1640066118)
    - https://github.com/bpmn-io/bpmn-js-properties-panel/issues/945
    
2nd:
- [x] implement tooltips for element templates
    - https://github.com/camunda/element-templates-json-schema/issues/103
    - https://github.com/bpmn-io/bpmn-js-element-templates/issues/8
    
Follow ups and improvements:
- https://github.com/bpmn-io/properties-panel/issues/272
- https://github.com/camunda/camunda-modeler/issues/3756
- https://github.com/bpmn-io/properties-panel/issues/274
- https://github.com/bpmn-io/bpmn-js-properties-panel/pull/955
   - [x] Add short explanatory text to `bpmn-js-properties-panel` doccumentation tooltips
   - [x] Add missing tooltips: extension properties, script task, timer retries

**Comment by nikku** [comment]
A quick sketch on tooltip discovery:

![capture rpWSb7_optimized](https://github.com/camunda/camunda-modeler/assets/58601/97000343-2019-469a-b175-917c2cf940ee)

Another one on overall tooltip UI:

https://github.com/bpmn-io/properties-panel/issues/202

**Comment by nikku** [comment]
Context provided by @YanaSegal: We already have an existing tooltip component in web modeler. To be clarified if we want to use that one, move to a new one (Carbon).

Cf. existing component, used in Web Modeler:

![image](https://github.com/camunda/camunda-modeler/assets/58601/787b2cf3-ae3a-4693-be06-8c37ceab5e9e)

**Comment by Nitish-u** [comment]
Hello @nikku, Is this issue still open? I wanted to know about this issue can you please tell me, where it is occurring and what adjustments you want. Actually i'm new to opensource contribution, till now i've contributed to my personal repo only.

**Comment by nikku** [comment]
If you want to contribute @Nitish-u, please checkout [issues flagged accordingly](https://tasks.bpmn.io/board?c=%21Done%2C%21Inbox&s=label%3A%22good+first+issue%22+) as well as our [contributing guide](https://github.com/camunda/camunda-modeler/#contributing).

**Comment by smbea** [comment]
While https://github.com/bpmn-io/properties-panel/issues/202 is being reviewed, I will try to identify places where we might want to replace the description with a tooltip or add one.

This will also help me figure out if there is a need to allow tooltip population by context/tooltip provider [like we do for description](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/contextProvider/zeebe/DescriptionProvider.js) for now.

**Comment by smbea** [comment]
**[tooltips via context and tooltips for group headers]**

In order to provide tooltip content as context, we need to provide ids for the trigger element. If we combine this with supporting tooltips on group headers, then we need to provide some id. The group id sometimes coincides  with a field id (ex: documentation group and element documentation field; implementations group and field).

A way to avoid potential breaking changes by altering some of the ids so they don't match, is to use the `data-group-id` which adds the `group-` prefix. In a tooltip provider, this would look like:

```diff
- businessRuleImplementation: (element) => return <TOOLTIP_CONTENT>;

// for implementation field
+ businessRuleImplementation: (element) => return <TOOLTIP_CONTENT>; 
// for implementation group
+ `group-businessRuleImplementation`: (element) => return <TOOLTIP_CONTENT>; 
```
