### ISSUE TITLE
Support converging inclusive gateway

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda-modeler#3613]
### Problem you would like to solve

Support for the converging inclusive gateway (i.e. converging OR gateway) is added to Zeebe in https://github.com/camunda/zeebe/pull/12642 as an external contribution. Of course, all the Camunda Platform 8 need to be aligned and support the feature.

If the Modeler doesn't support modeling the converging inclusive gateway for Camunda Platform 8, then our customers cannot use this new feature.

### Proposed solution

Please support the converging inclusive gateway for Camunda Platform 8. The behavior is specified in the [related Zeebe issue](https://github.com/camunda/zeebe/issues/10031).

- Remove the validation that restricts the number of incoming sequence flows to an inclusive gateway to max 1.

### Alternatives considered

* Users can update the XML by hand
* Users can use combinations of XOR and AND gateways to rebuild the OR gateway logic.

### Additional context

* https://github.com/camunda/product-hub/issues/364
* https://github.com/camunda/zeebe/issues/10031

**Comment by nikku** [comment]
Moving to ready as this is now implemented in Zeebe.

**Comment by barmac** [comment]
This will be implemented upstream via https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/111

**Comment by barmac** [comment]
Fixed upstream via https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/111

**Comment by barmac** [comment]
As a consequence of the decision PHub epic, I am reopening this issue, moving to the backlog, and removing it from the 8.3 milestone.

**Comment by saig0** [comment]
**Update:** The feature is implemented in Camunda for version **8.6**. :rocket: 

@barmac please plan to support it in the Modeler for Camunda version 8.6.

**Comment by nikku** [comment]
Moved to `ready`.

**Comment by barmac** [comment]
Fixed upstream via https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/166
