### ISSUE TITLE
Custom Properties Panel preact  hook error

### ISSUE THREAD

**Issue by sungeng49** [camunda/camunda-modeler#3619]
### Describe the bug

I've created a custom Properties Provider plugin for the properties panel. However, when I use the TextFieldEntry from Preact in the properties panel, an error occurs. After checking, I found that the error was in the useState hook of Preact. Later, I also discovered that when I used useService in my own plugin project, it would cause errors during runtime. After investigation, it appears that any time I use a Preact hook in my plugin project, it results in a runtime error.

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Expected behavior

why

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by smbea** [comment]
It could be that there is more than one `Preact` instance inside a project, which is a common issue.

Please verify this (against a package-lock.json or similar lock file) and use tools to de-duplicate your dependency tree. You can also use the [forum](https://forum.bpmn.io/) to share your concrete issue and ask for help.

**Comment by smbea** [comment]
Since there hasn't been any more activity on this, I will close. Feel free to re-open if you have more information to share with us. You can also use the [bpmn-io forum](https://forum.bpmn.io/) to ask for help in using our tools.
