### ISSUE TITLE
Start Process sets Business Key as empty string rather than NULL

### ISSUE THREAD

**Issue by codygulley** [camunda/camunda-modeler#3623]
### Describe the bug

When utilizing the Camunda Modeler's Start Process Instance overlay if I don't provide a business key, it sets the business key to  empty string rather than NULL. 

<img width="339" alt="Screenshot 2023-05-19 at 1 20 37 AM" src="https://github.com/camunda/camunda-modeler/assets/8097956/92363d62-321d-4039-b270-9d0b7e524a3b">

<img width="407" alt="Screenshot 2023-05-19 at 1 05 31 AM" src="https://github.com/camunda/camunda-modeler/assets/8097956/3a8c4938-0e20-47a5-b5ce-ef030ec2bda7">

My Camunda process engine has a unique constraint on business key on start API calls (per process definition). Since the business key is technically being set to a value (to an empty string) this causes my process start API to fail.

### Steps to reproduce

1. Create a simple model in the Camunda Modeler
2. Attempt to start a process instance via the Modeler 
3. Check the network traffic  (or query the database for the process instance that was created) and inspect the business key - it will be "" not NULL.

### Expected behavior

When business key is not set in the start process instance overlay it should be sent as NULL not empty string. 

### Environment

- OS: MacOS 13.3.1
- Camunda Modeler Version: 5.9.0, 5.11.0
- Execution Platform: Camunda Platform

**Comment by barmac** [comment]
Thanks for reporting. I can reproduce the issue. We are also happy to accept external contributions. Feel free to create a PR; the null coercion would have to be implemented somewhere in https://github.com/camunda/camunda-modeler/tree/develop/client/src/plugins/camunda-plugin/start-instance-tool
