### ISSUE TITLE
Camunda Modeler Crash

### ISSUE THREAD

**Issue by Wasace** [camunda/camunda-modeler#3624]
### Describe the bug

I am stuck please help me

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Expected behavior

i want to open my bpmn file!

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by smbea** [comment]
In order to be help you, we need some more information as to what is the problem. Please let us know what Modeler version you are using and what plug-ins (if any) you have installed. Is there any error shown?
