### ISSUE TITLE
Linter profile 7.20 does not incorporate 7.19 rules

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3632]
### Describe the bug

Apparently 7.19 introduced rules are now inactive again in 7.20 (alpha) profiles.

![capture 2kMmdc_optimized](https://github.com/camunda/camunda-modeler/assets/58601/4533ef2b-9165-444b-8db6-a12020080095)

### Steps to reproduce

1. Create C7 BPMN diagram
2. Remove history time to live
3. See 7.19 error
4. _Switch to 7.20 (alpha) profile; see no error

### Expected behavior

7.20 inherits all 7.19 rules.

### Environment

- OS: Linux
- Camunda Modeler Version: v5.11.0
- Execution Platform: Camunda 7
- Installed plug-ins: None

**Comment by smbea** [comment]
Ended up having a look at this, and we simply haven't added the 7.20 rules to linting yet. I added a PR for it, I believe that should do it
