### ISSUE TITLE
BPMN Editor crashes when a lint rule fails to execute

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3637]
### Describe the bug

Given one of linter rules is broken and throws an exception, it's correctly handled by bpmnlint, but the LintingTab cannot handle error report and crashes the editor.

### Steps to reproduce

1. Download this plugin with exact or older commit: https://github.com/jonathanlukas/camunda-modeler-linter-default-rules/commit/adf0c99f04584f78843ab1eaa3d80d9db0c3fc44 (it's fixed at HEAD).
2. Open diagram from https://github.com/camunda/camunda-modeler/issues/3625#issuecomment-1565747915
3. now this happens

![image](https://github.com/camunda/camunda-modeler/assets/28307541/4332538b-2232-4746-8400-84128f4cd2ce)

### Expected behavior

Editor should not crash, and we should somehow indicate to the user that the rule is broken. 

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

### Additional context

Follow-up of https://github.com/camunda/camunda-modeler/issues/3625

**Comment by philippfromme** [comment]
We're not handling rule errors at the moment. These are handled by [bpmnlint](https://github.com/bpmn-io/bpmnlint/blob/master/lib/linter.js#L67) by omitting the `id` and setting the `message` to `Rule error: <error message>`. We'll have to decide how we want to handle them on the application side. I see two possibilities:

# 1. Show rule error in _Output_ tab

<img width="625" alt="electron_QIS7ohftZ1" src="https://github.com/camunda/camunda-modeler/assets/7633572/8953247f-8c27-4f1b-b556-396935b6a5dc">

This would mean that every time a rule errors, the _Output_ tab would open. Rule errors would be easy to discover but might be disturbing.

# 2. Show rule error in _Problems_ tab

<img width="625" alt="electron_ZQC1LO0umU" src="https://github.com/camunda/camunda-modeler/assets/7633572/deb0fe55-fe74-4209-87c5-0885955484fe">

This would mean that rule errors do not disturb but show up in the _Problems_ panel. They'd be harder to discover.

In any case, we should probably adjust bpmnlint to add the rule name to the error. Without that information, we cannot tell the user which rule errored.

**Comment by barmac** [comment]
I think (1) makes sense only if we suppress further errors from a failing rule, so that user is not flooded with errors.

**Comment by nikku** [comment]
I'm up for this:

> In any case, we should probably adjust bpmnlint to add the rule name to the error. Without that information, we cannot tell the user which rule errored.
