### ISSUE TITLE
Task type does only change visually

### ISSUE THREAD

**Issue by mxsenel** [camunda/camunda-modeler#3639]
### Describe the bug

User tasks can be converted to a service task. At least the icon of the task changes from a human to a gear. But if you check the properties of the newly converted service task, you will see that they belong to a user task and not to a service task. An example for a property is the Asynchronous continuations. Normally, a user task has only two checkboxes (Before, After) as Asynchronous continuations options. A service task has three (Before, After, Exclusive). But the newly converted service task only displays two of three as if it is a user task. This behaviour also exists when you convert a service task to a user task

### Steps to reproduce

1. Add user task
2. Add service task
3. Compare the properties from both of them --> you will see that they have different options for asynchronous continuations property
4. Convert user task to service task

### Expected behavior

E.g. a user task should be converted visually and more important technically to a service task or vice versa.

### Environment

- OS: Windows 10
- Camunda Modeler Version: 5.9.0
- Execution Platform: Camunda Platform 7
- Installed plug-ins: Transaction Boundaries

**Comment by marstamm** [comment]
Hi @mxsenel ,

I can not reproduce this issue. Both Service and User Tasks have the async continuation options of Before/After/Exclusive.
Can you please share a screenshot or recoding of the bug to help us understand what problem you are facing?

Thank you!

**Comment by smbea** [comment]
Let's close this due to inactivity and re-open there are any updates
