### ISSUE TITLE
Update developer certificate

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3643]
### What should we do?

* Update developer certificate
* [Update documentation](https://github.com/bpmn-io/internal-docs/blob/master/products/modeler/CI.md#macos)

### Why should we do it?

Ensure we can continue to build the app, and know how updating works.

**Comment by nikku** [comment]
Moving to _ready_ due to urgency on this matter.

**Comment by barmac** [comment]
Let's use `cert-test` branch and build-on-demand for testing.

**Comment by nikku** [comment]
Documentation improvements:

* https://github.com/bpmn-io/internal-docs/commit/d3088312fbe3e1ca560aec9b4277d661c5a13349
* https://github.com/bpmn-io/internal-docs/commit/5d357264ce9e31cbac1e3aac1b1b506deaabe90f

**Comment by nikku** [comment]
:clap:
