### ISSUE TITLE
Problems icon in status bar appears as selected after closing panel

### ISSUE THREAD

**Issue by smbea** [camunda/camunda-modeler#3649]
### Describe the bug

Problem icon in status bar appears as selected after closing:

https://github.com/camunda/camunda-modeler/assets/25825387/60c62dd9-2dc8-4d5c-9078-bad2e931d2ec

### Steps to reproduce

1. Toggle bottom panel via errors and warnings button
2. Close panel via same button
3. Notice button still appears with same styling
4. Click canvas and see that that it goes back to normal

### Expected behavior

Button should only appear selected (with darker background color) when panel is open.

### Environment

- OS: MacOS
- Camunda Modeler Version: 5.12.0-rc.0

**Comment by marstamm** [comment]
Might be intended, the light-grey is the "focus" color, although it is confusing that the color is so similar

**Comment by philippfromme** [comment]
I'll look into this as it might be a quick fix.

**Comment by smbea** [comment]
> Might be intended, the light-grey is the "focus" color, although it is confusing that the color is so similar

I just noticed the other status bar buttons also do this so maybe it's not a bug??
