### ISSUE TITLE
Misleading Lint Error Message When Using Date for Timer Boundary and Intermediate Catch Events with Camunda <8.3

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#3653]
### Describe the bug

![image](https://github.com/camunda/camunda-modeler/assets/7633572/a20be5ce-65f5-4e6e-92de-22afd389f180)

### Steps to reproduce

1. Set execution platform to 8.2
2. Create timer boundary event
3. Set type to _Date_
4. _Type must be defined._ error shown

### Expected behavior

Error indicates that date is only supported by Camunda 8.3.

### Environment

- Camunda Modeler Version: 5.12-rc.0

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/3658.
