### ISSUE TITLE
Broken link for "Release Notes on Camunda Blog" 

### ISSUE THREAD

**Issue by vignesh57** [camunda/camunda-modeler#3655]
### Describe the bug

Appears to be a broken link when clicking on **"Release Notes on Camunda Blog"** 

![image](https://github.com/camunda/camunda-modeler/assets/584225/ccf4677d-c842-4aee-a53d-173cffce6409)

Getting 404 after redirecting to this url: 
https://camunda.com/blog/category/modeling/?tag=camunda-modeler&release-note&utm_source=modeler&utm_medium=referral

![image](https://github.com/camunda/camunda-modeler/assets/584225/20be338d-b423-4b73-a22b-c42c4b6e3f5e)

### Steps to reproduce

1. Open a recent version of the Camunda Modeler
2. On the bottom right, click on the version number (eg: 5.11.0)
3. A summary of new changes are displayed. Click on **Release Notes on Camunda Blog** hyperlink.
4. A new browser page opens up, but returns 404 error.

### Expected behavior

Release Notes of the current version should be displayed (eg: 5.11.0 release notes)

## Camunda Modeler system information
 * Version: 5.11.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform 7

### Additional context

Here is another URL that is somewhat close to what might work - 
https://camunda.com/blog/category/releases/?s=modeler
or the changelog...
https://github.com/camunda/camunda-modeler/blob/develop/CHANGELOG.md#5110

**Comment by nikku** [comment]
@smbea Let's ensure this works for the 5.12 release.

**Comment by smbea** [comment]
I believe this used to link to something like https://camunda.com/?s=desktop+modeler&lang=en

**Comment by nikku** [comment]
Probably that, in the [releases](https://camunda.com/blog/category/releases/) category. Maybe there is a way to search within that category?

**Comment by smbea** [comment]
> Maybe there is a way to search within that category?

Doesn't seem like it. As soon as you search, the category is discarded

**Comment by nikku** [comment]
I [reached out to web marketing](https://camunda.slack.com/archives/C034F8NA1G8/p1686299547025329).

**Comment by vignesh57** [comment]
Please see if this link suits the need @nikku @smbea, it appears to be searching under releases - 
https://camunda.com/blog/category/releases/?s=modeler
