### ISSUE TITLE
Version info always needs to be scrolled up on opening

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3659]
### Describe the bug

When we click on the version information we see that there is a need to be scrolled up to read from the beginning

### Steps to reproduce

1. open the desktop modeler version 5.12.0
2. click on the version information in the bottom right
3. We could see that there is a need for scrolling up to read from the beginning and opens up from the middle of the text

https://github.com/camunda/camunda-modeler/assets/85225325/b6f4b7ca-efc3-42d6-a695-053b94853ba7

### Expected behavior

The version information should be displayed from the begining on opening

### Environment

- OS: [ Windows 10]
- Camunda Modeler Version: [5.12.0]

**Comment by smbea** [comment]
This is non-blocking. Thanks for the report

**Comment by smbea** [comment]
I looked into this and I couldn't reproduce on MacOS

**Comment by crobbins215** [comment]
I tested on Windows incase it was OS but in 5.19.0 and it's working correctly.

![Windows](https://github.com/camunda/camunda-modeler/assets/10505316/bfdd933a-1d9a-40c4-b4bd-9ca02a58de54)

**Comment by smbea** [comment]
Let's close and re-open if it pops up again
