### ISSUE TITLE
Adaptive size of the documentation text box

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#3660]
### Problem you would like to solve

Having a huge documentation text, I can increase the size of the textbox to see all at once.

When I select another element and coming back to the one with the huge documentation, the box shrinks again to the default size.

### Proposed solution

* The textbox for Documentation should remember its size after increasing for all elements.
* We want to persist that information across modeler sessions (i.e. in persisted layout configuration)

### Alternatives considered

Show everything by default.

But this could be distracting for users that don't care about the complete documentation and are only interested if a documentation exists or not. 

### Additional context

The diagram converter from https://github.com/camunda-community-hub/camunda-7-to-8-migration generates all migrations into the documentation element. 

Depending on the Camunda 7 element configuration and element content, it could become many characters and sentences.

**Comment by ingorichtsmeier** [comment]
Not exactly.

Here is a screenshot: 
![grafik](https://github.com/camunda/camunda-modeler/assets/7870843/adc3d681-5c43-43de-8dd0-5efa7be60ea6)

I could not show everything, because it contains sensitive information. But the size of the scroll bar shows how long it can become. 

I think it is OK to save the new size of the textbox and apply it to all other BPMN elements. They usually have different content and I have chosen the largest.

**Comment by nikku** [comment]
> The textbox for Documentation should remember its size after increasing for all elements.

We cannot _remember_ across sessions, but we may be able to remember within an individual session.

**Comment by ingorichtsmeier** [comment]
What about adding the size to config.json on disk? 

I found this file in AppData\Roaming\camunda-modeler even touched today without using the modeler. It's still running in background.

**Comment by nikku** [comment]
> What about adding the size to config.json on disk?

That is a away to persist it. Good idea.

**Comment by vishalsingh2972** [comment]
@nikku can you assign this to me, want to give this a try!

**Comment by nikku** [comment]
Happy to take your contribution in the form of a PR.

**Comment by barmac** [comment]
We already have it in the name field of the BPMN editor.

**Comment by jarekdanielak** [comment]
Fixed upstream by https://github.com/bpmn-io/properties-panel/pull/377
