### ISSUE TITLE
provide homebrew cask

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-modeler#367]
It would be cool to install/update the modeler on OSX just by typing

    brew cask install camunda-modeler

This description tells how to do it: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by jangalinski** [comment]
see https://github.com/caskroom/homebrew-cask/pull/22817

once its accepted, we can install via `brew  cask`

would be a good idea to

* provide a checksum
* update the cask for every new version

**Comment by jangalinski** [comment]
Its done!

https://github.com/caskroom/homebrew-cask/blob/master/Casks/camunda-modeler.rb

**Comment by nikku** [comment]
Good work :clap:.

**Comment by jangalinski** [comment]
How can we get this on the downlaod page? I would love to see: Mac users just do: brew cask install .... , all other download here ...

**Comment by jangalinski** [comment]
+ question: would you be willing to provide the cask updates when new modeler versions are build? I can also do this, but then you shoul give me a heads up ... it will really just be: fork homebrew-cask, edit the new version and place a PR

**Comment by nikku** [comment]
I am not part of the Mac world and cannot judge the importance of cask.

It makes more sense if you maintain the distribution until we get a better indication that it is the thing how to get applications in Mac OS.

**Comment by jangalinski** [comment]
Makes sense. It is not "the way", but "a very cool way" that deserves more attention.
How do you think about a note on the download page? 

> Mac users just do: brew cask install ....

**Comment by nikku** [comment]
Which downloads page?

**Comment by jangalinski** [comment]
https://camunda.org/download/modeler/

**Comment by benhoffmann** [comment]
I use brew a lot and tried to use it for the modeler as well. It's a cool thing and I think it should be mentioned on the download page since this way of installing things is quite popular in the Mac world.

However, having to keep the cask file synchronized to the latest version of the modeler is quite some effort if you have to do it manually with every new release. Maybe this could be automated as part of your release process?

**Comment by jangalinski** [comment]
Currently, I do this manually with every new release. Its not that much effort, just typing

    cask-repair --pull origin --push jangalinski camunda-modeler

and set the new version number.

But it would be nice to have a note on the download page.
