### ISSUE TITLE
Completing an external task with variables loses the value and type

### ISSUE THREAD

**Issue by Gindarel** [camunda/camunda-modeler#3692]
### Describe the bug

We are using the External Task pattern with Camunda 7, wanted to complete a user task plus add some variables to the execution by using the variables or localVariables on the way back (according to the documentation) but no matter which way I try to send those only the name of the variable arrives properly, the type and variable get lost somewhere.
![plan](https://github.com/camunda/camunda-modeler/assets/64190972/ce729afa-d5d8-4999-946a-33fbe02eb007)
![variable](https://github.com/camunda/camunda-modeler/assets/64190972/9006f56c-dc97-4ce4-9dca-77489f293981)

I'm trying to use this body for the request.
{
    "workerId": "eb3f6739-6c1b-4d4d-b1f8-84bd3eb08c31",
    "variables": {
        "colour": {
            "value": "blue",
            "type": "string"
        }
    }
}

I also tried to simply use Postman and call this method with the body above but it produces the same result.

### Steps to reproduce

1. Create a process definition containing a User Task and an exclusive gateway (I also added a second user task on the standard way branch so I can check the variables in the execution but I don't know if it's necessary), utilizing the External Worker pattern.
2. Try to call the complete method with a variable that is checked after the gateway.
3. Check the variables in this execution.

### Expected behavior

The variable ("colour" in my example) is set properly with all the info provided.

### Environment

- OS: We use Fedora 35 in a WSL under Win 10
- Camunda Modeler Version: 7

**Comment by ingorichtsmeier** [comment]
Hi @Gindarel,

in Camunda 7, you cannot complete a user task as an external service task. Both task types use different APIs in Camunda 7 (In Camunda 8, a user task is implemented as a service task).

You have to use this REST API to complete the user task: https://docs.camunda.org/rest/camunda-bpm-platform/7.19/#tag/Task/operation/complete

**Comment by ingorichtsmeier** [comment]
It's not a bug
