### ISSUE TITLE
Copying implementation details with diagram elements (i.e. service tasks)

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#370]
When you copy a service task, the Implementation is not copied. 

This is problematic for a service task because, typically the main reason to copy a service task is for it's implementation.

**Details to Copy**
- `camunda:*` (if applicable)
- `extension elements` _?_
- `documentation`

Related to https://github.com/bpmn-io/bpmn-js/issues/558

Tasks:
- Allow adding meta information in `moddle` - [issue](https://github.com/bpmn-io/bpmn-moddle/issues/45)
- Add [Camunda Extension Elements](https://docs.camunda.org/manual/7.6/reference/bpmn20/custom-extensions/extension-elements) to the meta-model, as in being "allowedIn" for replacing in `camunda-bpmn-moddle` - [issue](https://github.com/camunda/camunda-bpmn-moddle/issues/34)
- Add infrastructure that is tested with `moddle` - [issue](https://github.com/bpmn-io/bpmn-js/issues/646)
- Able to replace an element with deeply nested properties - [issue](https://github.com/bpmn-io/bpmn-js/issues/647)
- Able to copy and paste an element with deeply nested properties - [issue](https://github.com/bpmn-io/bpmn-js/issues/648)
---

Related to:
- [SUPPORT-2803](https://app.camunda.com/jira/browse/SUPPORT-2803)
- [SUPPORT-2895](https://app.camunda.com/jira/browse/SUPPORT-2895)

**Comment by nikku** [comment]
That is correct. We do not copy _any_ details yet.

**Comment by iannsp** [comment]
@ricardomatias how this issue is going? I dont find some branch focus on it and I like to help on this.

**Comment by vpagliari** [comment]
@iannsp  Definetly! I guess this issue deserves some attention...

**Comment by StephenOTT** [comment]
This problem would also be a little mitigated if connectors were supported in element templates: https://github.com/camunda/camunda-modeler/issues/308
