### ISSUE TITLE
Create new C7 diagrams with pre-filled process TTL

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3701]
### Problem you would like to solve

As a user I'm creating a new Camunda 7 platform diagram and the first thing I'm faced with is an error message because TTL is missing on the process:

![image](https://github.com/camunda/camunda-modeler/assets/58601/604b594a-ff27-40e5-bd57-ba9354ef6c05)

What I'd expect is that a reasonable TTL is set initially, and I can customize from there (to suit my needs).

### Proposed solution

* TTL is pre-filled for _all_ new diagrams with a reasonable default ([6 months](https://github.com/camunda/camunda-modeler/issues/3701#issuecomment-1623155306))
* This way I'm not faced with an error on diagram creation

### Alternatives considered

None.

### Additional context

Reached out to [C7 maintainers](https://camunda.slack.com/archives/C6M6X3EKZ/p1688544213220479) to figure what a reasonable TTL could be.

**Comment by toco-cam** [comment]
Hey there, thanks for bringing this up. We do agree that the current behavior is not good.

We want to suggest to:
- Set the default value to 6 months
- Extend [Ensure historic data clean-up is considered early#1335](https://github.com/camunda/product-hub/issues/1335) (Planned for 7.20) to:
  - If the default is used (6 months) - Log level:Info: "You are using the default TTL (Time To Live) of 6 months; your data will be deleted by the clean-up after 6 months. We recommend adjusting this to a TTL aligned with your specific requirements"
  - If the field is empty - Do not deploy the model and throw Exception "Model property Time To Live is mandatory for deployment."


Greets Tobias

**Comment by nikku** [comment]
@toco-cam We're ready to pick this issue up any time, as specified in the issue description.

**Comment by psavidis** [comment]
# Kickoff Analysis

## Business Cases

👉  🟢 **New Processes** should have a _default configuration_ for **historyTimeToLive** (happy path of the feature)
	
* Deploying a new process with null HTTL will throw a business exception


👉  🟡  **Existing deployed processes** should remain unaffected by this change. We ignore the new behaviour for already deployed processes which are migrated to 7.20

- The behavior is still questionable if it is desired
- Probably, not many people start from scratch with new processes to get the validation exception of defining a HTTL

- **Pros & Cons**

	➕ Keeping the same HTTL behaviour might be considered as less intrusive by our customers
        ➕  There might be customers that don't want to cleanup their historic data for their business needs e.g custom ETLs, reports etc.

	➖ We will transiently allow our users to continue having the problem that this feature solves
	➖ Introduces another feature flag & relevant logic to alternate between legacy & the new validation logic
        ➖  _Weakens_ the character of the feature from mandatory for all processes to optional.
        ➖  There might be customers who would favour an automatic cleanup. Ignoring the new behaviour for existing processes could result in further support cases that request the feature to be enabled by default for existing deployed processes

👉 🟢 Does this requirement break backwards compatibility?

* No, the legacy behavior will be accessible by using a feature flag in any case. If customers want to stick to it despite the recommendations, they will be able to use it.

- 🟢  Documentation is needed to describe the behaviour of HTTL for new & existing deployed processes

- 🟢 Backporting: This is a new feature request, it does not require any backports to previous versions. It will be available only in 7.20
