### ISSUE TITLE
Breadcrumbs Misaligned

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#3705]
### Describe the bug

The text and arrows of the breadcrumbs seem to be misaligned:

![image](https://github.com/camunda/camunda-modeler/assets/7633572/6d3822e0-095f-4f16-b631-d74143b32138)

Compare to demo.bpmn.io:

![image](https://github.com/camunda/camunda-modeler/assets/7633572/ac01a18d-4a7c-4d4d-a4f5-9fdf0df92395)

### Steps to reproduce

1. Create a collapsed sub-process

### Expected behavior

Breadcrumbs are aligned.

### Environment

- Camunda Modeler Version: 5.13

**Comment by ranjanmangla1** [comment]
can someone assign me this issue? new to the community, would love to work on it!

**Comment by nikku** [comment]
@ranjanmangla1 We accept contributions to fix this issue.

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js/pull/1945.

**Comment by nikku** [comment]
Fixed via https://github.com/camunda/camunda-modeler/commit/87f5025ac67483ff98d2a65c0e824601179eede4.

**Comment by nikku** [comment]
Actually not fixed (yet).

**Comment by philippfromme** [comment]
Closed by https://github.com/camunda/camunda-modeler/pull/3832.
