### ISSUE TITLE
The attribute setting bar is not displayed

### ISSUE THREAD

**Issue by ac3225020** [camunda/camunda-modeler#3706]
### Describe the bug

i have downloaded the camunda model (mac version:5.12.1) from https://camunda.com/download/modeler/
when i create a  new user task and click it, i can not see the attribute setting bar on the right side, but i can do this on windows
![image](https://github.com/camunda/camunda-modeler/assets/10062515/338a9c0a-d0dd-46a2-b3c3-ab87c7bf6382)

### Steps to reproduce

1、download the latest version of mac camunda model from https://camunda.com/download/modeler/
2、create a new bpmn
3、create a new user task

### Expected behavior

i can see the attribute setting bar

### Environment

- OS:  MacOS 12.4
- Camunda Modeler Version: [5.12.1]

**Comment by nikku** [comment]
Toggle the properties panel on using `Window > Toggle Properties Panel` or using the resize handle on the right.
