### ISSUE TITLE
I can copy problem message

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3710]
### Problem you would like to solve

When I encounter a linting problem which I don't understand or is buggy, I cannot copy it and have to take a screenshot instead to report it.

### Proposed solution

Provide a copy button as we already do in output tab.

### Alternatives considered

Leave it as is.

### Additional context

Related to https://camunda.slack.com/archives/CKGH9LR40/p1688637664706059

**Comment by nikku** [comment]
I suggest that we revise our `user-select: none` handling. I recently tried to copy from the whats new communication and failed in the same way.

**Comment by barmac** [comment]
VSCode: 
![image](https://github.com/camunda/camunda-modeler/assets/28307541/de3a9a78-c5d1-4c90-a0c9-e0d402c8933a)

**Comment by ranjanmangla1** [comment]
can someone assign me this issue? would love to work on it!

**Comment by barmac** [comment]
Hi, as a rule we don't assign issues to external contributors. If one feels like providing a solution, we are happy to review pull request. Note however that this issue seems to require some design work, so I'd suggest to look for a well-defined problem for a contribution. Thanks.

**Comment by philippfromme** [comment]
Fixed by https://github.com/camunda/camunda-modeler/pull/3784.
