### ISSUE TITLE
Properties panel does not open up when clicking on the lint error

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3712]
### Describe the bug

While we try to click on the lint error the properties panel does not open up always esp when the user has previously closed the sidebar manually

### Steps to reproduce

1. Create a BPMN diagram in C7/C8.
2. Create a service task with no reference or simply a start event in c7
3. We see a lint error appears for not specifying the " time to live"
4. Close side bar manually
5. Try to click on the lint error to open up the respective error in the properties panel
6. We see the panel does not open up always.

https://github.com/camunda/camunda-modeler/assets/85225325/10b900b8-7657-460a-9255-ba548826a445

### Expected behavior

Clicking on the lint error should open up the respective field in the properties panel

### Environment

- OS: [Windows 10]
- Camunda Modeler Version: [5.13.0 rc-1]
- Execution Platform: [Camunda Platform, Camunda Cloud]

**Comment by barmac** [comment]
I can reproduce the issue. Thanks for reporting.
