### ISSUE TITLE
Investigate incomplete third party notices

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3714]
### What should we do?

With the v5.13.0 release and the [sentry bump](https://github.com/camunda/camunda-modeler/pull/3698) we're seeing incomplete third party notices.

As an example the following is part of the dependency tree:

```json
,
    "app/node_modules/@sentry/node": {
      "version": "7.57.0",
      "resolved": "https://registry.npmjs.org/@sentry/node/-/node-7.57.0.tgz",
      "integrity": "sha512-63mjyUVM6sfJFVQ5TGVRVGUsoEfESl5ABzIW1W0s9gUiQPaG8SOdaQJglb2VNrkMYxnRHgD8Q9LUh/qcmUyPGw==",
      "dependencies": {
        "@sentry-internal/tracing": "7.57.0",
        "@sentry/core": "7.57.0",
        "@sentry/types": "7.57.0",
        "@sentry/utils": "7.57.0",
        "cookie": "^0.4.1",
        "https-proxy-agent": "^5.0.0",
        "lru_map": "^0.3.3",
        "tslib": "^2.4.1 || ^1.9.3"
      },
      "engines": {
        "node": ">=8"
      }
    }
```

It is, however, not part of the [third party notices](https://github.com/camunda/camunda-modeler/blob/develop/THIRD_PARTY_NOTICES).

### Why should we do it?

Ensure we ship a consistent `THIRD_PARTY_NOTICES` file.

**Comment by barmac** [comment]
The library we use to check licenses (license-checker) has not changed since 2019.

**Comment by barmac** [comment]
My gut feeling is that the library reads installed packages which is OK as long as packages are present locally to the `package.json`. However, with hoisting that's mostly not true.

**Comment by barmac** [comment]
Plenty of dependencies were removed in https://github.com/camunda/camunda-modeler/commit/f6733c3f043fb150160956c88ff041152517654b; that was right after we switched to npm workspaces.

**Comment by barmac** [comment]
Another huge cleanup: https://github.com/camunda/camunda-modeler/commit/497ce7698d3a354f01448cf1acc79138c6b102e4; it looks like we lost transitive dependencies of `app` back then.

**Comment by barmac** [comment]
In our process, we rely on installed dependencies, which will give different results for each platform (e.g. on Windows we install a special dependency for SSL certificates extraction). Therefore, I believe our process is broken. I am now looking into how vscode handles the problem.

**Comment by barmac** [comment]
Two ideas how to solve the problem:
1) build own solution which traverses `package-lock.json` and includes non-dev dependencies
2) create wepback config for `app` to use existing plugin for license extraction

I am now trying out 2).

**Comment by barmac** [comment]
The webpack way seems to do the trick, so I will continue with it until I get the final result.

**Comment by barmac** [comment]
OK so the results are quite satisfying but I need to polish the solution.
