### ISSUE TITLE
Edit process properties from Participant

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#372]
Currently the properties are saved on the participant level, rather than on the process level. Execution listeners on the other hand are saved as extensions directly to the process level.

__Screenshot__

![image](https://cloud.githubusercontent.com/assets/58601/16916053/29ab6072-4cfb-11e6-918c-5bf50d0fe403.png)

__Resulting XML__

```xml
  <bpmn:collaboration id="Collaboration_1ry6f86">
    <bpmn:participant id="Participant_0v822ub" processRef="Process_1">
      <bpmn:extensionElements>
        <camunda:properties>
          <camunda:property name="asdasd" value="asdasd" />
        </camunda:properties>
      </bpmn:extensionElements>
    </bpmn:participant>
  </bpmn:collaboration>
  <bpmn:process id="Process_1" isExecutable="false">
    <bpmn:extensionElements>
      <camunda:executionListener class="asdasd" event="start" />
    </bpmn:extensionElements>
    <bpmn:startEvent id="StartEvent_1" />
  </bpmn:process>
```

**Comment by gimbel** [comment]
if this involves the properties panel, we should include that in the next pp-release

**Comment by nikku** [comment]
Gets addressed via https://github.com/bpmn-io/bpmn-js-properties-panel/issues/198.

**Comment by pedesen** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-properties-panel/commit/9db418adacbf521b32edf15c8b80b9038044018c and https://github.com/bpmn-io/bpmn-js-properties-panel/commit/5c82f28057e2e1d04a856a56b0e861721f69a61a
