### ISSUE TITLE
Close tabs via middle mouse button

### ISSUE THREAD

**Issue by hkupitz** [camunda/camunda-modeler#3729]
### Problem you would like to solve

As a user I would like to be able to close tabs with a click of the middle mouse button. This is the default behavior in almost every other application using tabs.

### Proposed solution

When a tab is clicked on with the middle mouse button, it is closed. If the tab's file is dirty, the "Save changes before closing" modal appears.

### Alternatives considered

An alternative would be to keep everything as it is and only allow closing each tab via the "x" button on the right side. This however is not very user-friendly when wanting to close a lot of tabs.

**Comment by nikku** [comment]
@hkupitz We did an internal poll and would like to accept this suggestion. Thanks for opening a feature request to implement it, too. I'll have a look today.
