### ISSUE TITLE
Keyboard shortcuts broke on Mac in 1.2

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#373]
Since the release of 1.2, I cannot longer use the shortcuts S, H, L, C.

**Comment by nikku** [comment]
We need to investigate this. 

May be fixed with [Electron 1.2.7](https://github.com/electron/electron/releases/tag/v1.2.7).

**Comment by nikku** [comment]
Should be fixed with the latest patch release `v1.2.2`. Please verify this.

**Comment by benhoffmann** [comment]
Works again, hooray!
