### ISSUE TITLE
Problems panel does not open via click once it was dragged to close

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3753]
### Describe the bug

https://github.com/camunda/camunda-modeler/assets/28307541/66896ac8-7d1f-498d-9be8-a1259bd0bd16

### Steps to reproduce

1. Open problems panel
2. Drag it to the bottom so that it closes
3. Try to open via click

### Expected behavior

It should open to the default size.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.14.0-rc.0 and 5.12.0
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/3795.
