### ISSUE TITLE
Properties tooltips do not hide on blur when right-clicking links before

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-modeler#3756]
### Describe the bug

The new properties tooltips do not hide on blur when I right-click a link in them before. 

This can lead to this view:

![image](https://github.com/camunda/camunda-modeler/assets/56470362/164b424e-6698-4e76-8539-130ca4f236e5)

### Steps to reproduce

1. Hover a property to spawn a tooltip
2. Right-click a link - no context menu appears
3. Blur/unhover the tooltip - it stays
4. Open another tooltip - you have 2 now on the screen

### Expected behavior

Link interactions should not make a tooltip sticky.

### Environment

- OS: MacOS 13.4 Ventura
- Camunda Modeler Version: 5.14.0-rc.0

**Comment by smbea** [comment]
Fixed upstream via https://github.com/bpmn-io/properties-panel/pull/273
