### ISSUE TITLE
Increase default size for Documentation entry

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#376]
__Problem__

* Type documentation (more than 3 lines)
* Re-focus element
* __Documentation is cut of after 2 lines)__

__Solution__

* [ ] Increase default documentation field size to minimum 10 rows. This gives users the ability to read important parts of the documentation without scrolling.

__Screenshots__

Documentation on edit.

![image](https://cloud.githubusercontent.com/assets/58601/17057845/3782b55e-501d-11e6-8d87-f1f1b5c48258.png)

Documentation on re-select: 

![image](https://cloud.githubusercontent.com/assets/58601/17057873/63ed58c4-501d-11e6-8d88-862aa980f20b.png)

**Comment by nikku** [comment]
Addressed by https://github.com/bpmn-io/bpmn-js-properties-panel/issues/202.

**Comment by nikku** [comment]
With these changes we introduce a few UX regressions:

* cursor does not properly restore on undo/redo
* select all does not work

I'll look into these issues and see if there is easy solutions.

**Comment by nikku** [comment]
Addressed all issues on properties panel branch.

**Comment by pedesen** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-properties-panel/issues/202
