### ISSUE TITLE
CDATA / Multi-line Property values in Camunda:Properties?

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#378]
Currently the Extensions tab on elements that Managers Camudna:Properties: https://docs.camunda.org/manual/7.4/reference/bpmn20/custom-extensions/extension-elements/#properties, is a KeyValue.  The values are single row strings.  Is there support for Multi-Row CDATA such as placing JSON object in a value field?  

Currently if you paste something like JSON into value field its recorded as something like:

```xml
    <bpmn:extensionElements>
      <camunda:properties>
        <camunda:property name="Test1" value="{   &#34;key1&#34;: &#34;val1&#34;,   &#34;key2&#34;: &#34;val2&#34; }" />
      </camunda:properties>
    </bpmn:extensionElements>
```

Is there any issues with supporting a multiline CDATA value for each property?

Is there length limits on the value field?  Stored as a String object?

![properties panel](https://cloud.githubusercontent.com/assets/1994838/17075522/abf459a6-5063-11e6-943e-482a332b2fbb.png)

**Comment by nikku** [comment]
CDATA as a child element if `camunda:property` is not recognized by the engine and addressing this is an engine, not a Camunda Modeler issue.

Please raise your question in the [Camunda Engine Forum](https://forum.camunda.org/c/engine) and see if you get that stuff implemented.
