### ISSUE TITLE
Disable output mapping of an Error End Event

### ISSUE THREAD

**Issue by aleksander-dytko** [camunda/camunda-modeler#3782]
### Problem you would like to solve

Currently, users can define output mapping for Error End Event. Zeebe never applies the output mappings of an Error End Event because the Error End Event is not completed but terminated. 

### Proposed solution

We should remove the Output Mappings from the Error Event in the Modeler.

### Alternatives considered

Keep this field enabled, but it does nothing.

### Additional context

https://github.com/camunda/product-hub/issues/243#issuecomment-1681941104

**Comment by nikku** [comment]
Fixed upstream via https://github.com/camunda/camunda-bpmn-js/pull/299.
