### ISSUE TITLE
Nightly/build-on-demand does not upload source maps to sentry 

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3791]
### Describe the bug

Check the sentry report for nightly releases: https://camunda-modeling.sentry.io/issues/4412110745/?project=5223041&query=release%3A5.15.0-nightly.20230821&referrer=release-issue-stream

### Steps to reproduce

1. Build a nightly
2. cause an error
3. Inspect it in Sentry
4. No source maps are available

### Expected behavior

There are SourceMaps

### Environment

CI

### Additional context

**Root Cause**

When uploading, we use the version info from the package.json. So even for nightly releases, the source-maps are associated with 5.14.0. (cf. build log https://camunda-modeling.sentry.io/issues/4412110745/?project=5223041&query=release%3A5.15.0-nightly.20230821&referrer=release-issue-stream)

In reporting the error, the reported version is `5.15.0-nightly-{{date}}`

We should reference the build version when uploading sourcemaps to avoid confusion

related to https://github.com/camunda/camunda-modeler/issues/3689

**Comment by nikku** [comment]
Oops. Great you pick this up.

**Comment by marstamm** [comment]
Hijacking this issue to also get rid of `uploadLegacySourcemaps`. X-post from slack:

> [fyi] I did some experiments on this and this is the result
> - We do not need uploadLegacySourcemaps after all, now it works fine with the new upload mechanism
> - [We do not need to rewrite paths](https://camunda-modeling.sentry.io/issues/4412554529/?project=5223041&query=release%3A5.15.0-dev+url%3Afile%3A%2F%2F%2Fhome%2Fstamm%2FDevelop%2Fcamunda-modeler%2Fclient%2Fbuild%2Findex.html&referrer=issue-stream&statsPeriod=14d&stream_index=0), the new upload mechanism seems to use debugIDs to associate the files with their uploaded sourcemaps
> - However, this also means it does not harm us to strip the path down, the displayed path in sentry Stack will show relative webpack:// paths. It only affects the url tag
> 
> Proposal: move to new upload mechanism, but keep the URL rewrite. This way, we can minimize collected data and don't send potentially non-anonymized data to sentry.
