### ISSUE TITLE
Update ID when changing activity type

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#380]
when you add a activity the ID is automatically set.  But when you change the activity type, the ID is not updated.

This starts to be confusing when using the IDs as references.  

Example: I changed an End Event to an Intermediate Throw event, but the ID is still End Event.

![screen shot 2016-07-25 at 10 55 05 am](https://cloud.githubusercontent.com/assets/1994838/17105717/5ff67814-5256-11e6-8069-90eb57eced02.png)

**Comment by philippfromme** [comment]
Hi Stephen,

this issue has been discussed [previously](https://github.com/camunda/camunda-modeler/issues/97#issuecomment-193657894) and we decided to change the behavior to [keep the same ID when replacing an element](https://github.com/bpmn-io/bpmn-js/issues/513). Correct identification is more important than naming semantics when it comes to execution and things like diagram diffing.

**Comment by StephenOTT** [comment]
@philippfromme makes sense.  Would something like a "rebuild ID"/"Refresh ID" button in the modeler be a best of both worlds?  Allowing the user to refresh the id with the same generator the modeler already uses but could be manually activated when the user wants a id with the proper activity name in it?

**Comment by berndruecker** [comment]
I personally would love such a button, if it uses naming best practices. So e.g. if a User Task is named "Call customer" the actiivty Id should be userTaskCallCustomer.

So I think the problem with such a button is to agree on what it does :-)

**Comment by nikku** [comment]
I see value in semantically sound IDs (after replace) and think the button could be a valuable addition.

My suggestion is:

* Create a new issue requesting that butto
* Come to an agreement what that button should do

If we have both things we can go ahead implementing it.

**Comment by StephenOTT** [comment]
> I personally would love such a button, if it uses naming best practices. So e.g. if a User Task is named "Call customer" the actiivty Id should be userTaskCallCustomer.

@berndruecker i was thinking something similar: `userTask_CallCustomer_1u62ryy`

@nikku I will create a new issue to discuss 👍

**Comment by ingorichtsmeier** [comment]
Is the name generator exchangeable?
