### ISSUE TITLE
Be able to define collapsed by default groups in an element template

### ISSUE THREAD

**Issue by igpetrov** [camunda/camunda-modeler#3807]
### Problem you would like to solve

Consider any connectors element template, i.e. [HTTP REST](https://github.com/camunda/connectors/blob/main/connectors/http/rest/element-templates/http-json-connector.json).

All properties are structured within _Groups_. All groups are _expanded_ by default. Requesting to add a flag to the `group` element that would indicate that a specific _group_ is collapsed by default.

### Proposed solution

The following construct should make _My Collapsed Group_ collapsed by default:

```
"groups": [
    {
      "id": "myCollapsedGroup",
      "label": "My Collapsed Group",
      "collapsedByDefault": true
    },
...
]
```

### Alternatives considered

Since our use-case is [epic-related](https://github.com/camunda/product-hub/issues/1363), we could dedicate one specific group for the task definition type property and hardcode it being collapsed by default but I would not recommend taking this route.

### Additional context

Via discussion: https://camunda.slack.com/archives/CKGH9LR40/p1693222832075709?thread_ts=1692785474.018059&cid=CKGH9LR40.

This FR is related to the [epic](https://github.com/camunda/product-hub/issues/1363), and is a feature gap related to the epic. See related [explanation](https://camunda.slack.com/archives/CKGH9LR40/p1693221008941389?thread_ts=1692785474.018059&cid=CKGH9LR40).

**Comment by igpetrov** [comment]
@nikku FYI. Please let me know if I can update the ticket with additional information. Thank you!

**Comment by nikku** [comment]
This sounds reasonable, and gives template authors much more freedom to decide which parts of an element template are "initially relevant". This is something we as framework authors cannot and do not want to know.

@marstamm Do you recall where we implement the "initially all open" behavior? I'd imagine this could be a fairly straight forward thing to contribute, depending on how we built "always open".

**Comment by marstamm** [comment]
The default state is defined by a toggle in the Group configuration

https://github.com/bpmn-io/bpmn-js-element-templates/blob/117f64d4c4734a4375efe35eea22748dd5fb170a/src/cloud-element-templates/properties/CustomProperties.js#L111

Currently, it is always `true` for element templates. This would be easy to implement.

**Comment by marstamm** [comment]
However, with the way persistence is implemented, the collapsed state of the group is shared across different templates. So if multiple templates have a `Authentication` group with the same ID and I open them in one element, it will be open in the other as well.

If we want to change this, we would need to add the template-id to the element template group id

**Comment by nikku** [comment]
> However, with the way persistence is implemented, the collapsed state of the group is shared across different templates. 

I think we want to keep this. It is a good feature. Otherwise there is no way to semantically group UI sections across templates.

**Comment by nikku** [comment]
@igpetrov Happy to take a contribution to implement `collapsedByDefault` behavior, cf. https://github.com/camunda/camunda-modeler/issues/3807#issuecomment-1696913777.

Thanks @marstamm for investigating.

**Comment by marstamm** [comment]
> Otherwise there is no way to semantically group UI sections across templates

I agree. If you don't want shared state for your template, you can always namespace the id in your template to decouple it.

**Comment by igpetrov** [comment]
Thanks a lot @nikku @marstamm!

Maybe @bastiankoerber can jump in and also share own thoughts on behalf of the Customers?

**Comment by bastiankoerber** [comment]
@igpetrov from a framework perspective this is absolut fine, we (as consumer) can then decide which behaviour
 we are prefering. In general i like the same behaviour by group, so i am ok with it :-)

**Comment by nikku** [comment]
@marstamm Let's tackle documentation as a follow up / part of this issue.

**Comment by marstamm** [comment]
Created a Draft PR for the docs to be merged after integration: https://github.com/camunda/camunda-docs/pull/2706

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js-element-templates/pull/18 and https://github.com/camunda/element-templates-json-schema/pull/114.
