### ISSUE TITLE
Should not be able to create Execution Listeners for Link Events

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#381]
Link Events do not support Execution Listeners, but you can currently set them in the modeler for Link Throw and Link Catch.

**Comment by ThorbenLindhauer** [comment]
The process engine does not actually execute linkt throw events, so execution listeners for it are ignored (same for IO mappings, etc). It does execute link catch events, so execution listeners for those do work.

**Comment by StephenOTT** [comment]
> Explanation: instead of executing both link throw and catch event, the engine internally connects the sequence flow that targets the throw event directly to the catch event and does not actually wait for any event to occur when execution reaches the catch event. That is somewhat a hack that better fits the internal execution model than actually throwing and then catching an event. Since this is no problem in practice, we are very likely not going to change that behavior any time soon.

👍 makes sense. :)  


------

So would you remove listener tab from Link Throw?
