### ISSUE TITLE
Call Activity Propagation data marker does not update

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3815]
### Describe the bug

![Recording 2023-08-30 at 11 14 06 (1)](https://github.com/camunda/camunda-modeler/assets/21984219/ce21e207-bea1-4d5e-b07f-0d83e0d16407)

### Steps to reproduce

1. Create a Call activity in C8
2. Toggle on Input or Output propagation
3. Toggle off again
4. The Group data marker is still there

### Expected behavior

The data marker is removed when I toggle propagation off.

## Camunda Modeler system information
 * Version: 5.15.0-dev
 * Operating System: Linux x86_64 amd64
 * Execution Platform: BPMN - Camunda Platform 8

https://github.com/camunda/camunda-modeler/pull/3814

### Additional context

The data marker is updated when another property in the `zeebe:calledElement` is updated, e.g. other Propagation or called element ID

**Comment by smbea** [comment]
The [`useEffect` that checks for entry changes](https://github.com/bpmn-io/properties-panel/blob/main/src/components/Group.js#L60) is triggered before the checkbox is actually checked. If we check the toggle value a few milliseconds later, then we would obtain the true value. This is also why the value is corrected after a re-render (caused by other entries).

I'm still not sure why it's not behaving as expected. What I can imagine is the `useEffect` is triggered by the `setValue` and getting the new value from the DOM before the actual re-render has happened:

```
Toggle level: user input -> set checkbox value -> checkbox is rendered accordingly
Group level:                                   ->`useEffect` is triggered -> get value via `domQuery`
```

**Comment by smbea** [comment]
Findings from looking at this with @barmac:

* The marker is updated based on the DOM at the time of the entries changed
* The DOM of the toggle switch is changed after `useEffect` has run
* `isEdited` doesn't depend on DOM entries but variable `entries`

<img width="428" alt="Screenshot 2023-09-22 at 12 10 15" src="https://github.com/camunda/camunda-modeler/assets/25825387/22ea09df-5669-4309-9ca7-c1f479589de0">

**Comment by barmac** [comment]
One idea: use MutationObserver to dispatch marker updates instead of useEffect.

**Comment by barmac** [comment]
We cannot use `:has` because it's not supported in FireFox.

**Comment by smbea** [comment]
I propose we go with the workaround for now. In the future (or if more issues like this one come up), we should consider refactoring the way we check/update if entries are edited.

This could include making entries more aware and having their own `isEdited` method, as opposed to it being a separate utility function. This way, it always checks the actual input value:

```javascript
class ToggleSwitch {
  isEdited() {
    return !!this.state.checked
  }
}
```
