### ISSUE TITLE
Enable signal catch events

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-modeler#3819]
### What should we do?

- Change the linter to allow the following 6 Signal Catch Events in Camunda Platform 8.3 Alpha
  - Signal Boundary Event (Interrupting / Non-Interrupting)
  - Signal Intermediate Catch Event (attached to Event-Based Gateway)
  - and Event Subprocess Signal Start Event (Interrupting / Non-Interrupting) 
- Signal Name is optionally defined as an expression (prefixed by `=`)

<img width="1159" alt="Screenshot 2023-08-31 at 15 54 29" src="https://github.com/camunda/camunda-modeler/assets/3511026/39cc17df-21ad-4bc9-ba90-3439c4e49e0e">

### Tasks

* [x] Editable in properties panel
* [x] Validated (supported with `v8.3.0+`)

### Why should we do it?

Zeebe will support these signal catch events with `8.3.0-alpha5`:

- https://github.com/camunda/zeebe/issues/13241

This issue is similar to:
- #3555

**Comment by nikku** [comment]
Could you clarify the following behavior:

* What is the semantics if no signal is attached (catch all?)
* Do you also support signal intermediate catch?

**Comment by korthout** [comment]
>What is the semantics if no signal is attached (catch all?)

Good question. At this time, a `signalEventDefinition` must reference a `signal`. There is no catch all behavior. 

There is also no signal correlation key. A signal matches all signal catch events that are awaiting it by signal name only. As a workaround, users can prefix or postfix a signal name with some process instance-specific value by defining it as a FEEL expression. This would allow subsets of all signal catch events to be triggered.

>Do you also support signal intermediate catch?

Yes, both standalone and attached to event-based gateway.

**Comment by nikku** [comment]
Thank you for your clarification. I believe due to signal(ing) semantics catch all is probably overkill anyway.
