### ISSUE TITLE
Provide a more useful message when I use the wrong secret format

### ISSUE THREAD

**Issue by CatalinaMoisuc** [camunda/camunda-modeler#3834]
### What should we do?

We should give the user a more helpful error message when they encounter issues when using secrets.

This was reported by multiple people in internal channels over the past few days. See [here](https://camunda.slack.com/archives/C034N0E5YCX/p1694083447915229) and [here](https://camunda.slack.com/archives/C034N0E5YCX/p1693919048982859).

This seems to be related to the switch to the mustache-style format when using secrets:
https://docs.camunda.io/docs/components/connectors/use-connectors/#using-secrets

The current error we show when people use the old secrets format is the following:
<img width="480" alt="Screenshot 2023-09-07 at 13 01 42" src="https://github.com/camunda/camunda-modeler/assets/25924333/a0e7f540-f856-4bbd-b830-1689e3264619">

To mitigate this, we could add a link to the documentation page that explains how people can use the secrets correctly:
https://docs.camunda.io/docs/components/connectors/use-connectors/#using-secrets

### Why should we do it?

To avoid confusion and ensure that our users are supported to quickly understand how they can fix the underlying issue.

**Comment by philippfromme** [comment]
Related to https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/133. What's missing is being able to show warnings instead of errors in the properties panel and to add the link to documentation.

**Comment by nikku** [comment]
Discussed today morning:

* Let's not indicate warnings (or info) in the properties panel as an initial step. Instead keep them on the canvas + in the problems panel, and only focus the respective entry in the properties panel.

**Comment by philippfromme** [comment]
This requires two adjustments so we can ship it as part of `@camunda/linting`:

* enable the rule and change the category to `info` in `bpmnlint-plugin-camunda-compat` (https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/137)
* do not add the `propertiesPanel` property in ´@camunda/linting´
