### ISSUE TITLE
FEEL error reported switches

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3845]
### Describe the bug

Using the modelers validation feature leads to different errors flashing when invalid FEEL content is entered to a field:

![capture CEBm8o_optimized](https://github.com/camunda/camunda-modeler/assets/58601/bb8f0760-a681-422a-a58e-496f116378b5)

It looks like two different validations kick in, resulting in different error messages.

### Steps to reproduce

1. Model a service task
3. Enter broken FEEL expression in type field
4. Re-focus node
5. __See error message switching (cf. above).__

### Expected behavior

A clear, meaningful, and stable error message is shown to me as a user. At best it indicates that `FEEL` is the format of the (expected) language. If possible the editor itself establishes additional context (red caret?).

### Environment

- OS: Linux
- Camunda Modeler Version: v5.15.0
- Execution Platform: Any
- Installed plug-ins: None

**Comment by philippfromme** [comment]
Can reproduce. Probably due to https://github.com/bpmn-io/properties-panel/blob/425c1f6f53fa3607e2c4f4fc0d69d66147346bb3/src/components/entries/FEEL/Feel.js#L526.

**Comment by smbea** [comment]
This happens because the syntax error takes a while to come through, so it uses the error it already has.
I'm not sure it's possible to speed up how the error analysis in the feel editor (I'm not familiar with it but I didn't see any bug that needed fixing). So what should be our strategy for these cases? Maybe delaying would work, but it seems a bit like patch work.

**Comment by philippfromme** [comment]
I think the hierarchy of `const error = localError || temporaryError || validationError;` is quite arbitrary. First local, then global, then local again? We could decide to just change it to `const error = temporaryError || localError || validationError;`, meaning `const error = globalError || localError || editorError;`.

**Comment by smbea** [comment]
So in these cases, we prioritize the linting over the syntax error. Meaning the user just gets a "not valid" feedback

**Comment by barmac** [comment]
If I understand this correctly, the human-readable "This is not a valid FEEL expression" would get priority, but user could still see the exact editor error if they highlight the error.
![image](https://github.com/camunda/camunda-modeler/assets/28307541/e1711d24-6344-45b9-b685-070101652daa)

Makes sense to me.

**Comment by smbea** [comment]
Ah that makes sense then, didn't think of that. Thanks for explaining. I vouch for this then and will follow up.
