### ISSUE TITLE
Improve integration tests (plugin + element template loading)

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3861]
### What should we do?

With Cawemo SaaS changes we may want to adjust [the cloud-connect-plugin tests](https://github.com/camunda/camunda-modeler/blob/develop/docs/.project/INTEGRATION_TEST.md#cawemo-plugin).

I see a bunch of options:

* Amend the integration test, ensure that spinning up Cawemo (self-managed) is clearly documented
* Add an automated end-to-end test to verify the [cloud-connect-modeler-plugin](https://github.com/camunda/cloud-connect-modeler-plugin) works
* Change the plugin to execute its E2E tests periodically (every night), on supported platforms (currently does not execute on Windows)

### Why should we do it?

Ensure we have E2E coverage of Camunda Modeler plug-in capabilities.

**Comment by nikku** [comment]
I quickly sketched out how we could use the cloud-connect plug-in as an E2E integration test, executed every night :arrow_right: https://github.com/camunda/cloud-connect-modeler-plugin/pull/132.

**Comment by philippfromme** [comment]
With https://github.com/camunda/cloud-connect-modeler-plugin/pull/132 how should we continue with this?

> Cawemo SaaS changes

Are you referring to Cawemo SaaS being shut down and self-managed being the only option to test against?

**Comment by nikku** [comment]
I think https://github.com/camunda/cloud-connect-modeler-plugin/pull/132 + it running nightly is fine. We still want to update the documentation (remove the plug-in, or simply link it).
