### ISSUE TITLE
Ability to set default history time to live value in the modeler via flag in flags.json

### ISSUE THREAD

**Issue by HarishMalavade** [camunda/camunda-modeler#3869]
### Problem you would like to solve

Desktop modeler recent version has default History clean up "Time to live" configuration set to 180 days, we had default "historyTimeToLive" set to 30 days in our engine configuration(bpm-platform.xml) but currently due the default value in the recent version of the modeler the engine configuration will be overwritten. 
Can we enhance the modeler to add flag to indicate the default historyttl value like we do for disable-zebee, c7-engine-version etc

![image](https://github.com/camunda/camunda-modeler/assets/41999937/8327134e-6474-4934-9e79-ab83eea968ae)

### Proposed solution

Implement flag to set default-history-ttl setting 

### Alternatives considered

Ask every modeler to change the value to 30 but we have thousands of processes across our organization 

### Additional context

Flag to be named as default-history-ttl

**Comment by nikku** [comment]
Sounds reasonable to have a flag to configure this. Do you want to contribute this?

**Comment by HarishMalavade** [comment]
Yes I can contribute, might need some help with direction. thank you.

**Comment by nikku** [comment]
Superceeded by https://github.com/camunda/camunda-modeler/issues/4062.
