### ISSUE TITLE
Integrate FEEL popup menu

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3877]
_Tracks integration of https://github.com/camunda/product-hub/issues/1016 into the Desktop Modeler._

### Problem you would like to solve

The FEEL popup menu is a new UI component that we want to integrate properly into the Desktop Modeler.

### Proposed solution

* [x] Use [updated libraries](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/main/CHANGELOG.md#540) that ship it
* [x] Ensure it properly integrates with BPMN, DMN, and FORM editor global state / keyboard shortcuts
* [x] Ensure dragging works
* [x] Ensure popup menu is rendered [_globally on top_](https://github.com/camunda/camunda-modeler/issues/3877#issuecomment-1733198745) of existing UI controls (it is a popup)
* [x] Remove feature toggle

### Alternatives considered

None.

### Additional context

Currently blocked by https://github.com/bpmn-io/bpmn-js-properties-panel/issues/974.

**Comment by nikku** [comment]
Likely blocked via https://github.com/bpmn-io/properties-panel/issues/289

**Comment by nikku** [comment]
Integrating this we want to ensure that the popup menu is rendered _on top (globally)_ of existing UI controls.

![capture Wanzen_optimized](https://github.com/camunda/camunda-modeler/assets/58601/e451fd3b-9219-4035-81db-617fe0b86cc1)

**Comment by marstamm** [comment]
https://github.com/bpmn-io/bpmn-js-properties-panel/issues/974 did not unblock us in disabling focus actions, for 2 reasons.

1️⃣ 
When opening the editor, the events are fires as such:

| Fired Event | Focused Element |
|---|----|
| `propertiesPanel.focusout`  | Property panel entry  |
| `propertiesPanel.focusin`  | Open editor Button  |
| `feelPopup.opened`  | Open editor Button  |
| `propertiesPanel.focusout`  | body  |

When these elements are fired, the popup editor is not ready and does not have focus yet. We could debounce the `feelPopup.opened` event and assume it will focus the correct element, but

2️⃣ 
It does not cover the scenario
1. Open the editor, type some stuff (assume actions disabled)
2. Scroll on the canvas (actions enabled again)
3. Focus the editor again (actions stay enabled)

As the editor stays open, we never get notified about the change in focus and can't disable global events again. We need `focusIn/focusOut` events similar to the properties panel events to properly react to focus changes in the editor.

**Comment by marstamm** [comment]
I think we did not post this behavior yet, so for completeness: 

The popup editor (for bpmn-diagrams) stays open and visible when you switch tabs. This can also lead to multiple editors open at the same time

![Recording 2023-10-05 at 11 13 21](https://github.com/camunda/camunda-modeler/assets/21984219/da8cf058-c746-44be-b352-cd9678306662)

**Comment by nikku** [comment]
I believe what you report @marstamm is reported upstream via https://github.com/camunda/camunda-bpmn-js/issues/312, too.
