### ISSUE TITLE
Update FEEL editor Suggestions

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3884]
### What should we do?

`the is defined()` function: the behavior of the function will change with Camunda 8.3

The new version of the FEEL-Scala engine is much more null-friendly. Instead of failing the evaluation, for example, because of missing variables, it returns null. The new behavior is similar to the current behavior of the FEEL JS engine.
Because of the new behavior, the is defined() function is effectively just a null-check. I recommend to replace the usage of is defined(x) with x != null.

It should be marked as deprecated and removed from auto-completion

### Why should we do it?

cf slack: https://camunda.slack.com/archives/CKGH9LR40/p1695628447744909?thread_ts=1695374400.947109&cid=CKGH9LR40

**Comment by marstamm** [comment]
Suggestions are compiled from the platform docs, so changes/removal on the will be reflected once we run the script again.

https://github.com/bpmn-io/feel-editor/blob/main/scripts/compileBuiltins.js

I just noticed that it uses versioned docs instead of latest, this should be tackled in this issue as well

**Comment by barmac** [comment]
I'm moving this to `ready`, and let's discuss it later whether we want to prioritize this.

**Comment by marstamm** [comment]
fixed upstream via https://github.com/bpmn-io/feel-editor/pull/45
