### ISSUE TITLE
Confirmation for Reload

### ISSUE THREAD

**Issue by baalmael** [camunda/camunda-modeler#3886]
### Problem you would like to solve

Ctrl + R instantly reloads the modeler. This is dangerous, as all non saved changes to any open model (tab) are lost by doing this which can be very frustrating.

### Proposed solution

If there are unsaved changes, ask for confirmation before reloading (for example: "Are you sure, you want to reload? All unsaved changes will be lost!"

### Alternatives considered

- Autosave before reloading -> not good, because saving is not what is expected by pressing Reload

**Comment by nikku** [comment]
Thanks for the feedback. We'll investigate if there is some simple fix (ask for confirmation) as you suggested.
