### ISSUE TITLE
Allow ${ } expressions for IDs

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#391]
Currently the modeler regards `SomeProcess_${VERSION_TAG}` as an invalid ID. There is some usage scenarios where these statements are going to be replaced later on (i.e. via a Maven built process). 

During validation we should match for `${...}` and not validate the ID characters as soon the field contains expressions.

See `SUPPORT-2555`. 

__Related__

* CMMN fix: https://github.com/bpmn-io/cmmn-js-properties-panel/issues/51
* BPMN fix: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/201

**Comment by pedesen** [comment]
closed via https://github.com/bpmn-io/cmmn-js-properties-panel/issues/51 and 
https://github.com/bpmn-io/bpmn-js-properties-panel/issues/201
