### ISSUE TITLE
Forms: Cannot set `0` as minimum for Number validation

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3913]
### Describe the bug

In a Camunda Form, I cannot set the `Minimum` to the value of 0
![Recording 2023-10-05 at 14 27 44](https://github.com/camunda/camunda-modeler/assets/21984219/9bfe0d5b-63f5-4b9b-8635-1c19659d7627)

### Steps to reproduce

1. Create a Form
2. add a Number field
3. set Validation => Minimum to `0`
4. Change the selected element
5. Focus Number field again
6. 🐛 the 0 is gone

### Expected behavior

0 Is a valid Minimum and can be persisted

## Camunda Modeler system information
 * Version: 5.16.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: Form - Camunda 8

### Additional context

It is persisted when activating FEEL. 
![Recording 2023-10-05 at 14 30 45](https://github.com/camunda/camunda-modeler/assets/21984219/a6a58467-8728-40a6-85db-4d93db199156)

Assumption: we check if a value is truthy before submitting, which 0 is not

--

[SUPPORT-18691](https://jira.camunda.com/browse/SUPPORT-18691)

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/properties-panel/pull/297.

**Comment by marstamm** [comment]
This was not fixed with an update to the properties panel in https://github.com/camunda/camunda-modeler/pull/3939 because form-js bundles the properties-panel dependency and needs to be bumped in form-js.

**Comment by marstamm** [comment]
closed via #3955
