### ISSUE TITLE
Be able to template (non-interrupting) start events inside event sub processes

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3915]
### Problem you would like to solve

I have a hard time to model non-interrupting start events along with connectors without editing the XML.

### Proposed solution

Non-interrupting start event connectors embed intuitively within the existing modeling UX: Whatever can be modeled as an interrupting start event can also be modeled as a non-interrupting start event. This is because both are the same internally, with non-interrupting simply triggering other external effects (done by the BPMN engine):

* [ ] I can create start event connectors either as interrupting _or_ non interrupting from the _create menu_
* [x] In can replace from interrupting to non-interrupting (connectors) without loosing the connector details
* [x] If I apply a connector template on a non-interrupting start event, then the non-interrupting nature is kept (https://github.com/bpmn-io/bpmn-js-element-templates/issues/20).
* [x] I can create a start event (or any element) within a specific context, binding additional properties (https://github.com/bpmn-io/bpmn-js-element-templates/issues/19)

### Alternatives considered

* Be able to define specific element templates for interrupting and non-interrupting usage
* Be able to define "conditional, based on applied location" element templates (https://github.com/bpmn-io/bpmn-js-element-templates/issues/19)

### Additional context

The following shows the standard interaction that [core modeling](https://demo.bpmn.io/) provides to support interrupting vs. non-interrupting events:

![capture vR0GCU_optimized](https://github.com/camunda/camunda-modeler/assets/58601/92f2c4eb-45d9-493a-ae93-98f6aa20b9f7)

With the proposal we simply want to ensure that templated start events plug into this intuitively.

---

Raised via https://github.com/camunda/product-gaps/issues/109.

**Comment by igpetrov** [comment]
Sounds reasonable, see my comment related to this ticket: https://github.com/camunda/product-gaps/issues/109#issuecomment-1752805359

**Comment by nikku** [comment]
### Initial Investigation

Within event sub-processes a message start event must bind the `correlationKey` to something used-defined to signify how the message is being correlated: 

![capture 9HRr1E_optimized](https://github.com/camunda/camunda-modeler/assets/58601/52262d5b-eff9-4978-a69d-f48852cdc478)

This implies that we need a mechanism for contextual application of a property (https://github.com/bpmn-io/bpmn-js-element-templates/issues/19) or users would need to create two different element templates, for nearly similar templates.

**Comment by marstamm** [comment]
You are right, this is not yet fixed upstream. Only part of it is implemented. Moving back to Ready

**Comment by nikku** [comment]
@marstamm Could you share an update regarding this issue? To me it seems like it is fixed upstream, with all components including https://github.com/bpmn-io/bpmn-js-element-templates/issues/19 taken care of.

**Comment by marstamm** [comment]
We were missing correlation key conditions in the previous release.

Implementation for the conditional correlation keys in element-templates are done and docs are merged. This will be integrated and released with the Web-modeler alpha/Desktop modeler minor release.

**Comment by smbea** [comment]
Included via https://github.com/camunda/camunda-modeler/pull/4009
