### ISSUE TITLE
I can see a list of keyboard shortcuts

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda-modeler#392]
Display a list of all available modeling keyboard shortcuts like in the demo.
The list could be toggled using an entry in the help menu.

![keyboard-shortcuts](https://cloud.githubusercontent.com/assets/2543743/17395929/1fec9aa4-5a31-11e6-9985-19b1a4f0b10a.png)

**Comment by gimbel** [comment]
What is the problem that could be solved?

The user cannot find the following shortcuts (assming that we remove to direct editing tooltip):
- line feed - SHIFT + Enter
- Select multiple elements - ctrl + click
- Select multiple elements with lasso - SHIFT + mouse selection
- Scrolling (Vertical)	ctrl + Scrolling
- Scrolling (Horizontal)	ctrl + ⇧ + Scrolling
