### ISSUE TITLE
Template task in camunda 8

### ISSUE THREAD

**Issue by Supriya-Kate** [camunda/camunda-modeler#3927]
### What should we do?

while creating task under task i did not find out template task in properties panel (i want to create Rest end point)

### Why should we do it?

in desktop modeler some properties are missing as compare to web modeler plz help me out for this

**Comment by Supriya-Kate** [comment]
if it is available then plz guide me

**Comment by nikku** [comment]
You have to install the element templates manually. 

They are available [here](https://github.com/camunda/connectors) for download, and [configuration/installation is documented here](https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/configuring-templates/).

**Comment by Supriya-Kate** [comment]
Thank you.
i installed manually means i downloaded that project from github now i did not get it how to use can you please help me
