### ISSUE TITLE
Link FEEL Documentation from Popup editor

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3929]
_Child of https://github.com/camunda/product-hub/issues/1395._

### Problem you would like to solve

New users who create processes for their first times do not know how to write expressions to map between tasks.

### Proposed solution

- [ ] Extend https://docs.camunda.io/docs/next/components/modeler/feel/what-is-feel/ to act as a landing page for all modeling releated FEEL resources
  - [ ] explain what FEEL is
  - [ ] link to the [expressions concept page](https://docs.camunda.io/docs/next/components/concepts/expressions/)
  - [ ] link to both FEEL playgrounds and explain when each engine is used
- [ ] Add a link to the popup editor https://github.com/bpmn-io/properties-panel/pull/308

### Additional context

Product hub epic with initial breakdown: https://github.com/camunda/product-hub/issues/1395

**Comment by marstamm** [comment]
We should also add https://docs.camunda.io/docs/next/components/modeler/feel/what-is-feel/ to the the list of "stable links" so it redirects should the page move (thanks @barmac for bringing it up)

**Comment by barmac** [comment]
List link: https://github.com/camunda/camunda-docs/blob/main/product-links.txt

**Comment by barmac** [comment]
BTW it looks like it's already included: https://github.com/camunda/camunda-docs/blob/main/product-links.txt#L28

**Comment by marstamm** [comment]
Fixed upstream via https://github.com/bpmn-io/properties-panel/pull/308
