### ISSUE TITLE
Show an indicator that a template is deprecated in Catalog

### ISSUE THREAD

**Issue by codygulley** [camunda/camunda-modeler#3932]
### Problem you would like to solve

If a template has been marked with `deprecated:true` there is not an indication that the template is deprecated in the Catalog list. You only see the `deprecated` badge after the template is applied.  This is the same behavior in both C8 and C7 models.

<img width="761" alt="Screenshot 2023-10-17 at 11 46 13 PM" src="https://github.com/camunda/camunda-modeler/assets/8097956/1a63e170-e964-478d-8915-a8a5a198590c">

<img width="349" alt="Screenshot 2023-10-17 at 11 46 01 PM" src="https://github.com/camunda/camunda-modeler/assets/8097956/4d6e635a-482b-4843-9697-8e47a4c99003">

Here is the example template used in the above screenshots.
```json
{
   "name": "AdditionalProperty",
  "id": "com.camunda.example.deprecated.bool",
  "appliesTo": [
    "bpmn:ServiceTask"
  ],
  "properties": [],
  "deprecated": true
}
```

Camunda Modeler version: 5.16.0
OS: Mac OS 14.0 (Sonoma) 

### Proposed solution

The Catalog show highlight with an icon, badge, or some indicator that the latest version is deprecated.

### Alternatives considered

We are updating the name of templates with {deprecated} at the beginning so that it is clear the template is deprecated and users are aware and not selecting a deprecated template.

Note: we use `{` so that the templates are appear last in the list since `{` is considered alphabetically after A-z .

**Comment by nikku** [comment]
According to good practices established we should not allow to select deprecated templates from the UI. I believe that would solve your issue?

**Comment by nikku** [comment]
We appreciate a contribution to improve this along the lines of https://github.com/camunda/camunda-modeler/issues/3932#issuecomment-1767717791.

**Comment by nikku** [comment]
Never mind the call for contribution. I fixed it via https://github.com/camunda/camunda-modeler/pull/3934 along the lines of https://github.com/camunda/camunda-modeler/issues/3932#issuecomment-1767717791.

**Comment by codygulley** [comment]
I just pulled your branch and tested it and it worked great. I much prefer the approach you've taken to not allow them to be selectable/visible in the catalog at all. Thanks for that and getting this implemented so quick!

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/3934.
