### ISSUE TITLE
Deleting Last Empty Pool Results in Error

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#3941]
### Describe the bug

Deleting the last empty pool results in an error shown in the _Output_ panel.

![Camunda_Modeler_2HtWUDMIJ3](https://github.com/camunda/camunda-modeler/assets/7633572/604ab71a-626c-4ede-9268-3b35d98f08d4)

### Steps to reproduce

1. Create a collaboration with one empty pool
2. Delete the empty pool
3. Error shown in _Output_ panel

### Expected behavior

No error

### Environment

- Camunda Modeler Version: 5.16.0

**Comment by barmac** [comment]
I can reproduce this bug. The call stack leads to https://github.com/camunda/camunda-bpmn-js-behaviors/blob/master/lib/shared/DeleteParticipantBehaviour.js
