### ISSUE TITLE
Support compensation events in C8

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3945]
_Supports https://github.com/camunda/product-hub/issues/219._

### What should we do?

In C8 BPMN editor:

* [x] As a Developer I can use intermediate throw compensation events
* [x] As a Developer I can use compensation end events
* [x] As a Developer I can use compensation boundary events

This will need to be implemented via linting rules.

Only the green compensation activities should be supported:

![Screenshot from 2024-03-22 13-09-31](https://github.com/camunda/camunda-modeler/assets/4305769/548dfab1-3a81-4b98-b5cc-e089454c9174)

### Why should we do it?

Child of https://github.com/camunda/product-hub/issues/219

_EDIT: Updated the supported compensation handlers based on the current implementation status in Camunda 8._

**Comment by barmac** [comment]
This will wait in backlog until the linked epic is ready.

**Comment by nikku** [comment]
As a goody (and supporting this effort) we significantly improved compensation modeling in [bpmn-js@16.3.0](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#1630), to be shipped with Camunda Modeler v5.19.0.

**Comment by barmac** [comment]
I updated the issue with the recent change of scope on the engine side reported in the epic.

**Comment by barmac** [comment]
Since 8.4 is out today, we can pick up this item in the upcoming iterations.

**Comment by nikku** [comment]
Pushed to next time, depending on our capacity.

**Comment by barmac** [comment]
I updated this to not include compensation start events as [compensation event subprocess support](https://github.com/camunda/product-hub/issues/2081) is not planned for the upcoming release.

**Comment by saig0** [comment]
@barmac I updated the issue description based on the current implementation status in Camunda 8.

The following elements were out of scope but will be **supported for 8.5** as compensation activities: :sparkles: 
- Embedded subprocess ([ref](https://github.com/camunda/zeebe/issues/16601))
- Call activity ([ref](https://github.com/camunda/zeebe/issues/16600))
- Multi-instance ([ref](https://github.com/camunda/zeebe/issues/16602))

We will also support the triggering of compensation for given activities ([ref](https://github.com/camunda/zeebe/issues/15459)). On a compensation throw event, a user can optionally define the activity to compensate via the `activityRef` attribute. The activity must be in the same scope as the compensation throw event. This works already in the Modeler. :heavy_check_mark: 

Currently, a user can disable the `Wait for completion` option on a compensation throw event. For Camunda 8.5, we will not support this option. We support only the case that the compensation throw event waits for the completion. In the modeler, we may want to remove this option or define a limiting rule for it. :x: 

![Screenshot from 2024-03-11 10-04-14](https://github.com/camunda/camunda-modeler/assets/4305769/c3949a0e-90ae-4eb3-aff2-f597c2b64bd9)

**Comment by barmac** [comment]
Does implementing Compensation Receive Task even make sense? The spec allows this but I can't really think of a use case for "this activity needs to be compensated, but wait for a message first".

**Comment by barmac** [comment]
On the other hand, I can have a compensation subprocess with message catch inside too.

**Comment by saig0** [comment]
@barmac I updated the description to remove the restriction for compensation handlers. We now allow all kinds of activities to have a compensation boundary event and be attached to a compensation boundary event as a compensation handler. No special linting rules are required for the activity type.

So, we have the following restrictions for version 8.5:
- No compensation start events
- A compensation throw event must have `Wait for completion` set to `true`

**Comment by barmac** [comment]
I think that since no compensation events are allowed pre-8.5, and all compensation activities are allowed from 8.5 onwards, we don't need validation for compensation activities specifically. They are not marked as disallowed right now, so no changes here required. WDYT?

**Comment by barmac** [comment]
The logic here is that the event is marked as not allowed, and as soon as you remove it, the activity stops to be an unsupported compensation activity. So the state where compensation activity is the only disallowed element is impossible to reach within normal modeling.

**Comment by barmac** [comment]
I kept a backup of the rule but removed it from the PR.

**Comment by barmac** [comment]
So after [this PR](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/162) is merged, we only need to update the camunda/linting project to have human-readable error messages and properties panel support.

**Comment by barmac** [comment]
This will be done with https://github.com/camunda/linting/pull/103 merged, released, and integrated.
