### ISSUE TITLE
Allow HTML in Element Templates Description

### ISSUE THREAD

**Issue by vignesh57** [camunda/camunda-modeler#3947]
### Problem you would like to solve

Looking for a way to link to external documentation sites for element templates.

Right now, hyperlinks are allowed on input and output description but not the actual template itself. 

See below, how the link appears, in the element template description. It is not allowing hyperlinks.
![image](https://github.com/camunda/camunda-modeler/assets/584225/ce7c2c51-43c3-4cbe-89b4-571c5da2bddc)

But check out this input parameter, here it allows hyperlinks. 
![image](https://github.com/camunda/camunda-modeler/assets/584225/d1dddf84-43c7-4150-ac46-0aa8e84f34ab)

### Proposed solution

Allow hyperlinks on Template Description, just like input and output does. 

### Alternatives considered

There are no alternatives to do this, except defining at each input level. 

### Additional context

We are on Camunda 7, but this may help all users on 7 & 8 versions.

**Comment by smbea** [comment]
If we implement this, we will need to allow this in replace menu template entries and the element template chooser.

**Comment by nikku** [comment]
We offer [`documentionRef`](https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/element-templates/defining-templates/) for element templates to link to designated (external) documentation. Did you consider that @vignesh57?

**Comment by vignesh57** [comment]
Thanks for looking back at this again and reviewing alternatives @nikku @smbea 

Having a document ref would be very helpful. Will this work on Camunda 7.x modeler versions? I quickly tried it on one of my templates, and it didn't work. Am I using it correctly? 

![image](https://github.com/camunda/camunda-modeler/assets/584225/13d6de63-5bfc-4c7e-971d-e12df7701944)

I would like to see something here:
![image](https://github.com/camunda/camunda-modeler/assets/584225/833dff87-eab0-46aa-959e-0654a9d0f643)

**Comment by nikku** [comment]
@vignesh57 The thing is called `documentationRef` as I wrote.

**Comment by nikku** [comment]
Closing this issue as linking can be better handled via `tooltips`.

**Comment by vignesh57** [comment]
Hi @nikku you are right. I tried again now, and looked harder. I found it. I thought may be it's only for Camunda 8 but the 7 docs states [it's supported](https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/element-templates/c7-defining-templates/). I think the icon is a bit too small, hidden in the top-right corner. It's hard to notice. It would be nice to make it bold and bigger?
![image](https://github.com/camunda/camunda-modeler/assets/584225/421afb0a-bdf1-46ff-9d96-cc5f572b18a0)

Like this may be? 
![image](https://github.com/camunda/camunda-modeler/assets/584225/f4ea009a-6047-4651-9832-6930f1f199d5)
