### ISSUE TITLE
Long select label overflows to the next line

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#3957]
### Describe the bug

![image](https://github.com/camunda/camunda-modeler/assets/28307541/e6a6930a-add9-437d-b9b1-e0dc5a77141d)

### Steps to reproduce

1. Create a select option with very long label
2. Select it
3. now this happens

### Expected behavior

Hide the overflowing content. `text-overflow: ellipsis` would work fine.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

CC: @camunda/human-task-orchestration-dev

**Comment by pinussilvestrus** [comment]
Thanks for reporting @barmac. I guess it's not blocking for the release?

**Comment by barmac** [comment]
I don't think so.
