### ISSUE TITLE
Deleting the FormID resets Type dropdown

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3963]
### Describe the bug

![445a54bd-2679-44f8-9d8e-1d3eb261b5c9](https://github.com/camunda/camunda-modeler/assets/21984219/c1476408-fa70-428c-8612-cd5419b07170)

### Steps to reproduce

1. Use Form type linked 
2. Add a Form ID
3. Remove the Form ID
4. The Dropdown switches to "<none>"

### Expected behavior

Form dropdown keeps "Linked"

## Camunda Modeler system information
 * Version: 5.17.0-dev
 * Operating System: Linux x86_64 amd64
 * Plugins: autosave-plugin, test, test-client, test-editor-events, test-lint-rules, test-script-error
 * Execution Platform: BPMN - Camunda 8

**Comment by philippfromme** [comment]
Interestingly, the behavior is the same for Camunda 7.

![Camunda_Modeler_Ff3GjL4j4F](https://github.com/camunda/camunda-modeler/assets/7633572/7044eed9-2f5c-4ed8-aa1c-c6c09c582eaa)

**Comment by marstamm** [comment]
I assume this is because the field returns `undefined` when you remove the content, which removes the property, which then resets the dropdown.

I can reproduce (in C7) in v5.0.0, so this is not a regression

**Comment by philippfromme** [comment]
The issue is that the select works based on the presence of one of the properties, there is no separate property for the type. Removing the property (e.g. removing `formId`) will cause the select to assume there is no type set. The fix would be to

```js
const setValue = (value) => {
  setFormId(injector, element, isUndefined(value) ? '' : value);
};
```
