### ISSUE TITLE
Update Camunda 8 Docs to Reflect Introduction of Tenant ID in Desktop Modeler

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#3966]
### What should we do?

Update the docs.

### Why should we do it?

So users can learn about the feature.

**Comment by philippfromme** [comment]
For context: https://camunda.slack.com/archives/C0555930H7F/p1696505937202799

**Comment by philippfromme** [comment]
No update beyond our usual updates to the screenshots with every release is needed.

**Comment by akeller** [comment]
I came here from https://github.com/camunda/product-hub/issues/197#issuecomment-1808274757.

No mention of MT support in Desktop Modeler docs? Not even a 1 liner? I'm all for less documentation, but do we need to document any new config for [deploying a diagram to a specific tenant](https://docs.camunda.io/docs/components/modeler/desktop-modeler/connect-to-camunda-8/)? Or how to switch deploying between tenants? No MT enablement [flag](https://docs.camunda.io/docs/components/modeler/desktop-modeler/flags/)?

**Comment by felix-mueller** [comment]
@akeller @philippfromme  - I agree with @akeller here. from my perspective it would be good to explain the deployment for MT from Desktop Modeler. The current screenshots for deployment also only talk about SaaS, so there will be no update?
@philippfromme can you clarify perhaps?

**Comment by nikku** [comment]
@akeller We assessed that no documentation is needed from our end, as the feature in Desktop Modeler is self-explainatory.

---

What is going to happen is that the the [self-managed documentation screenshots](https://docs.camunda.io/docs/self-managed/modeler/desktop-modeler/deploy-to-self-managed/) are going to be updated _eventually_, featuring the new optional tenant ID field:

![image](https://github.com/camunda/camunda-modeler/assets/58601/396f16b1-daf1-4443-9fdc-010342563d5a)

If you feel it is necessary, then we of course can add a _one liner_ to the self-managed deployment guide, linking to the [overview of multi-tenancy](https://docs.camunda.io/docs/self-managed/concepts/multi-tenancy/). 

As multi-tenancy is not available in SaaS at this stage I don't think any addition to the SaaS documentation makes sense at this point. We can of course _also_ add a note that it is not available in SaaS, that is your call.

---

@akeller As we seem to assess the situation differently, please define clear requirements what we should add and what not (I provided some proposals) :arrow_up:.

**Comment by akeller** [comment]
@nikku I would also recommend a single sentence about running/starting diagrams in Desktop Modeler. I assume it's similar to [SaaS](https://docs.camunda.io/docs/components/modeler/desktop-modeler/start-instance/), but again we introduce the concept of a tenant. 

This would give us something users (or Camundi) can reference to help with https://camunda.slack.com/archives/C0693F1NFK5/p1701964504521999 (which I realize is likely a bug at the moment, but reinforces the tenant id concept).

**Comment by nikku** [comment]
I'll look into applying your suggestions today.

**Comment by philippfromme** [comment]
Closed by https://github.com/camunda/camunda-docs/pull/3056.
