### ISSUE TITLE
I can not search the DRD

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3975]
### Describe the bug

With the recent version bumps of dmn-js, we implemented search in DRD: https://github.com/bpmn-io/dmn-js/pull/792

This is also available on the demo, but does not work in the modeler

### Steps to reproduce

1. Open a DRD
2. press Ctrl+F
3. nothing happens

### Expected behavior

I can search the Diagram

## Camunda Modeler system information
 * Version: 5.17.0
 * Operating System: Linux x86_64 amd64
 * Plugins: autosave-plugin, test, test-client, test-editor-events, test-lint-rules, test-script-error
 * Execution Platform: DMN - Camunda 8

**Comment by barmac** [comment]
I guess the custom keyboard component in the Modeler may block this :/

**Comment by barmac** [comment]
I see, it's not allowed in the menu actions.

**Comment by marstamm** [comment]
fixed via #3977
