### ISSUE TITLE
Process Ids are not validated on input

### ISSUE THREAD

**Issue by SeriousBug** [camunda/camunda-modeler#399]
Setting a Process Id and the Id of an element to the same value initially does not cause any warnings. Saving the file and reopening causes errors. To reproduce the problem:

1. Create a new diagram
2. __Create a pool/participant__
3. __Select the pool and change the "Process Id" field to "myid"__
4. __Select any other element, and change its "Id" field to "myid"__
5. Save and close the diagram
6. Reopen the diagram

At this point, "Imported with 1 warning." will be displayed on the top of the screen, and any elements in the pool will be invisible. The only way to resolve the problem is to edit the XML by hand and change either the process id of the pool, or the id of the element.

The issue has been observed in version 1.2.2.

**Comment by nikku** [comment]
This is the intended behavior. IDs are unique and the warning is the modelers indication for that issue.

**Comment by SeriousBug** [comment]
The problem is, there are no warnings when the IDs are being written. The warning is only given after the file is saved and reopened.

**Comment by nikku** [comment]
I cannot reproduce this. In the modeler UI you are not able to assign duplicate IDs.

![image](https://cloud.githubusercontent.com/assets/58601/17691136/20ac3b46-6393-11e6-99b6-449db5bf5dab.png)

How did you do it?

**Comment by nikku** [comment]
:wink: Got it.

**Comment by nikku** [comment]
We'll look into that bug.
