### ISSUE TITLE
TaskListener fields disappear when diagram is edited.

### ISSUE THREAD

**Issue by klajmajk** [camunda/camunda-modeler#400]
When using _camunda:taskListener_ _camunda:fields_ disappear after diagram is edited by the modeler. I am using camunda modeler in latest version (1.2.2).

Example:

**Before**

      <bpmn2:userTask id="referentCheck" name="Kontrola" camunda:formKey="embedded:app:referent.html" camunda:assignee="${AssigneeBean.referentAssignee}" camunda:candidateGroups="#{referentGroup}">
        <bpmn2:extensionElements>
          <camunda:taskListener class="listener.NotificationListener" event="create">
            <camunda:field name="emailServiceExpression" expression="${emailService}" />
            <camunda:field name="identityServiceExpression" expression="${identityService}" />
          </camunda:taskListener>
        </bpmn2:extensionElements>
      </bpmn2:userTask>

**After modeler edit**
    
    <bpmn2:userTask id="referentCheck" name="Kontrola" camunda:formKey="embedded:app:referent.html" camunda:assignee="${AssigneeBean.referentAssignee}" camunda:candidateGroups="#{referentGroup}">
      <bpmn2:extensionElements>
        <camunda:taskListener class="listener.NotificationListener" event="create">
          <camunda:field name="identityServiceExpression" expression="${identityService}" />
        </camunda:taskListener>
      </bpmn2:extensionElements>
    </bpmn2:userTask>

**Comment by nikku** [comment]
What were the modification steps you undertook?
________________________________________

**Comment by klajmajk** [comment]
Any modification causes the problem (for example moving any element).

**Comment by polenz** [comment]
It should be fixed with the next Camunda Modeler release.
