### ISSUE TITLE
Missing DI breaks DMN modeling

### ISSUE THREAD

**Issue by CatalinaMoisuc** [camunda/camunda-modeler#4011]
### Describe the bug

Initially reported via: https://github.com/camunda/web-modeler/issues/7039.

### Bug description

Diagrams with missing DI break DMN modeling. Newly added elements disappear after closing and re-opening the diagram. 
The properties panel is blank when selecting any element and the XML cannot be shown for the diagram. 

### Steps to reproduce
See video.

https://github.com/camunda/web-modeler/assets/4279289/af8f6a1f-517e-4676-92cb-79485617ec08

### Expected Behavior

On the desktop modeler, changes are also lost, however, it remains possible to edit the XML. By adding the <dmndi:DMNDiagram> node the situation can be recovered in the Desktop Modeler. I would expect the same to be possible in the Web modeler

Correct behavior in Desktop Modeler 

https://github.com/camunda/web-modeler/assets/4279289/450581cd-fbe4-4b22-a91a-c0ddf2a31c40

**Comment by nikku** [comment]
@barmac You could double-check my assessment in https://github.com/camunda/web-modeler/issues/7039#issuecomment-1850072109.

I did not find a core bug in the report. If there is one (or something that can be reproduced in Desktop Modeler), let's update the issue accordingly @CatalinaMoisuc.

**Comment by nikku** [comment]
Let's close this one. Happy to re-open whatever we identify as a bug.

**Comment by nikku** [comment]
Let's close this one. Happy to re-open whatever we identify as a bug.
