### ISSUE TITLE
tenantId is not passed to zeebe-api run

### ISSUE THREAD

**Issue by jwulf** [camunda/camunda-modeler#4016]
### Describe the bug

In DM 5.17, deploying a process model to a Self-Managed instance with Multi-tenancy enabled works. However, starting a process instance from the Modeler throws an error in the UI and in the server process.

### Steps to reproduce

1. Set up a Self-Managed, multi-tenant instance (reproducer environment setup described [here](https://github.com/jwulf/zeebe-node-sm-mt-example))
2. Create credentials for the Desktop Modeler to connect
3. Configure the connection in the Modeler
4. Deploy a simple process to the <default> tenant
5. Start an instance of the process
6. Observe the error: Expected to handle gRPC request CreateProcessInstance with tenant identifier '', but no tenant identifier was provided. [ start-instance-error ]

### Expected behavior

Process instance is started

### Environment

- OS: Mac OS
- Camunda Modeler Version: 5.17
- Execution Platform: Camunda 8

### Additional context

The server process error is: 
```
ERROR app:zeebe-api run failed {
  parameters: {
    processId: 'simple',
    tenantId: undefined,
    endpoint: {
      type: 'oauth',
      url: 'http://localhost:26500',
      oauthURL: 'http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token',
      audience: 'zeebe.camunda.io',
      clientId: '******',
      clientSecret: '******'
    },
    variables: {}
  }
}
```

Notice that the `tenantId` is undefined. The error seems to be caused by the tenantId from the configuration not being passed to the point where the `createProcessInstance` call is made.

Discovered via this [Forum post](https://forum.camunda.io/t/how-to-start-a-process-instance-in-a-self-managed-multi-tenant-deployment-v8-3-3/49229)

**Comment by felix-mueller** [comment]
Hey @nikku this sounds rather critical for Multi-Tenancy 🤔 
Do you already know when the team would look into it and if it would be part of next modeler release?

**Comment by ingorichtsmeier** [comment]
Hi @nikku, at some customers/prospects, the developers cannot run a local Zeebe installation via docker-compose. 

These teams think about using multi-tenancy in their lowest, shared test environment to support the single developer. Each developer will become a single tenant.

For them, it is important to deploy and start process instances from the tool they use regularly.

**Comment by felix-mueller** [comment]
> @felix-mueller Processes are typically not run from modeler for production, but only for testing purposes. Even then, they can be deployed from modeler already (no issues).

I agree that it's less a problem for production use-cases. 
I do think though that it's a problem for testing and adopting Multi-Tenancy as a Developer.
I believe that it is for sure friction in the developer journey.

> The team will take on this issue, work on it in the next iteration, and deliver a fix.
Thank you! Sounds good 👍 
Do you already know when the next "fix" would be shipped to Modeler? Is this January?

**Comment by nikku** [comment]
We try to get this patched up with the upcoming 5.18 release, so likely 5.18.1 :slightly_smiling_face:

**Comment by nikku** [comment]
Working setup for C8 self-managed (MT), now testing.

**Comment by nikku** [comment]
Bug fixed, and [pending review](https://github.com/camunda/camunda-modeler/pull/4022).
