### ISSUE TITLE
Make sure diagram is exported after namespace change

### ISSUE THREAD

**Issue by ricardomatias** [camunda/camunda-modeler#403]
When a activiti diagram is migrated to the camunda namespace, we're not exporting the file, unless the diagram is changed manually.

We should make sure the file is marked as dirty after the conversion so that it gets properly exported through saveXML (potentially updating attributes and other things with the conversion).

---

See [SUPPORT-2599](https://app.camunda.com/jira/browse/SUPPORT-2599).

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1133.
