### ISSUE TITLE
Text Annotation of Bondary Event hidden behhind Sub-Process

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#4035]
### Describe the bug

My text annotation is hidden when I add it to a boundary event which is attached to a sub-process
![image](https://github.com/camunda/camunda-modeler/assets/2777965/4ae721ea-f1f8-47e1-b679-68d2b3ad4eab)

### Steps to reproduce

1. model a sub process
2. add a boundary event to the bottom edge of the sub process
3. add a text annotation

### Expected behavior

text annotation is visible 

### Environment

- Camunda Modeler Version: can be reproduced in Desktop and Web Modeler (8.4.0-alpha2)
- Execution Platform: Camunda 8

### Additional context

Potentially depends on https://github.com/bpmn-io/bpmn-js/issues/2049.

**Comment by philippfromme** [comment]
The reason is that the parent of the text annotation is the same as the boundary event's parent. It's basically the same case as this one:

![image](https://github.com/camunda/camunda-modeler/assets/7633572/52df7e80-ddbf-4d53-8f4d-b12ff0d3c60a)

**Comment by philippfromme** [comment]
Maybe text annotations should always be on top like the associations connecting them,

**Comment by philippfromme** [comment]
This issue is covered as part of https://github.com/bpmn-io/bpmn-js/issues/2049 so I'll close it.

**Comment by nikku** [comment]
@philippfromme Let's have it open as distinct issues.

This one specifically would imply that text annotations are _always on top_, the other one may imply no auto-resizing for text annotations only.
