### ISSUE TITLE
Support tooltips for element templates

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4041]
### Problem you would like to solve

Tooltips are a recent addition to the core modeling experience. They are available for the existing panel:

![capture jZFYs9_optimized](https://github.com/camunda/camunda-modeler/assets/58601/36fe8fe5-fd79-4f94-acc8-1bba13c30363)

I don't see a way how to use them [along with element templates](https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/element-templates/defining-templates/). I'm aware I can use `description` fields, but I cannot use `tooltip` or the like as it looks like.

### Proposed solution

* I can use tooltips as a mean to transport additional context in element templates.
* Tooltips support basic markup, including `code` and `[documentation](https://links)`

### Alternatives considered

Consider tooltips a core only feature.

**Comment by smbea** [comment]
We do support tooltips for element templates properties:
<img width="1792" alt="Screenshot 2023-12-22 at 10 13 51" src="https://github.com/camunda/camunda-modeler/assets/25825387/dd5c9c3a-315a-4db9-9bb4-31c2c02bf84e">

**Comment by nikku** [comment]
We actually do, ha! :upside_down_face: 

Also documented in the [next](https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/element-templates/defining-templates/#groups) (not current!) version of our C8 platform documentation.

**Comment by nikku** [comment]
@smbea We don't support styling though, right? Just plain text at this point?

I believe basic markdown styling + linking would be a great addition, cf. issue description.

**Comment by smbea** [comment]
We support text and html which already allows which is already very flexible, I believe. Same as the description
