### ISSUE TITLE
Update documentation (SM) screenshots to latest

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4048]
### What should we do?

The modeler self-managed documentation currently features [modeler 8.2](https://github.com/camunda/camunda-docs/pull/3136#pullrequestreview-1799128822).

* [x] ensure that this part of the documentation features an up-to-date modeler
* [x] screenshots, if possible, are updated as part of our [automated routine](https://github.com/camunda/camunda-docs-modeler-screenshots)

### Why should we do it?

Ensure our users can enjoy the latest and greatest of our modeler, also for self-managed.

**Comment by philippfromme** [comment]
Will be addressed as part of https://github.com/camunda/camunda-docs/pull/3214.

**Comment by nikku** [comment]
Will the shots be automatically updated?

**Comment by nikku** [comment]
Great stuff and thanks for :heavy_check_mark: the boxes!
