### ISSUE TITLE
Document `zeebe:calledElement#propagateAllParentVariables`

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4049]
### What should we do?

As a follow-up to [the implementation](https://github.com/camunda/camunda-modeler/issues/3793#issuecomment-1827903332) we want to [document the feature](https://github.com/camunda/camunda-modeler/issues/3793#issuecomment-1827903332).

### Why should we do it?

Ensure the semantics are clear and there is a reference to link to.

**Comment by philippfromme** [comment]
Already documented: https://github.com/camunda/camunda-docs/pull/3188 Closing this issue.
