### ISSUE TITLE
Propagating All Variables and Explicitly Defined Should Not Be Mutually Exlusive

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#4051]
### Describe the bug

Propagating all variables from the child process to the parent process _and_ additional variables mapped using _Outputs_ is a valid use case. However, the two are mutually exclusive due to a [behavior](https://github.com/camunda/camunda-bpmn-js-behaviors/blob/master/lib/camunda-cloud/UpdatePropagateAllChildVariablesBehavior.js) implemented in camunda-bpmn-js-behaviors.

![electron_z38XTpemny](https://github.com/camunda/camunda-modeler/assets/7633572/8eafe5c8-07ca-45dc-911b-5ed7b7f40593)

### Steps to reproduce

1. Enable _Propagate all child process variables_
2. All _Outputs_ are removed

### Expected behavior

The two are not mutually exclusive.

### Environment

- Camunda Modeler Version: 5.18

### Additional context

Slack thread: https://camunda.slack.com/archives/C0693F1NFK5/p1704183528061299
Related to https://github.com/camunda/camunda-modeler/issues/4049

**Comment by nikku** [comment]
Released upstream fix via https://github.com/camunda/camunda-bpmn-js-behaviors/tree/v1.2.3.
