### ISSUE TITLE
Element Templates Field Tooltips/help text

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#406]
Would be great if you could define help text/tooltip information that could be displayed to the user when select a `i` icon or hover on the field name.  The text would display information about the usage of the field.  The information would come from the JSON template file 

some such as:
```json
...
    {
      "label": "Receivers",
      "type": "String",
      "help": "The email addresses of the people who the email will be sent to. Email addresses are separated by commas (,)",
      "binding": {
        "type": "camunda:inputParameter",
        "name": "receivers"
      },
      "constraints": {
        "notEmpty": true
      }
    },
...
```

**Comment by nikku** [comment]
We already have the `description` field for this.

As part of https://github.com/camunda/camunda-modeler/issues/313 we are going to add support for displaying that field along with properties.

**Comment by StephenOTT** [comment]
Great. Thanks
