### ISSUE TITLE
Improve UX for HTTL mandatory for C7

### ISSUE THREAD

**Issue by toco-cam** [camunda/camunda-modeler#4062]
### Problem you would like to solve

The current user experience around [ensuring HTTL is set](https://docs.camunda.org/manual/7.20/update/minor/719-to-720/#enforce-history-time-to-live) does not suit all user profiles. Users with a HTTL set as a Global Engine Flag are confused about the default values and the error warning.

### Proposed solution

- No default values are displayed in Modeler for HTTL (CMMN, DMN, BPMN):
  * [x] https://github.com/camunda/camunda-modeler/pull/4150
- Modeler displays an info with the suggestion to set the HTTL to 180 days as a starting point, with a link to the linting hints (in the docs) which explains why HTTL is necessary and how to set an engine HTTL
  * [x] https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/160
  * [x] https://github.com/camunda/linting/pull/100
- For Power Users (With engine configuration) the Modeler provides a `disable-httl-hint` flag to disable the info for users with HTTL configured on the engine)
  * [x] https://github.com/camunda/camunda-modeler/pull/4151
- HTTL section in properties panel provides additional context:
  * [x] https://github.com/bpmn-io/dmn-js-properties-panel/pull/82
  * [x] https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1028
- Desktop Modeler integration
  * [x] https://github.com/camunda/camunda-modeler/pull/4157
  * [x] https://github.com/camunda/camunda-modeler/pull/4154
- Document HTTL required in modeling guidance and link from there to other parts of the documentation
  * [x] https://github.com/camunda/camunda-docs-modeler-screenshots/pull/81
  * [x] https://github.com/camunda/camunda-docs-modeler-screenshots/pull/80
  * [x] https://github.com/camunda/camunda-docs/pull/3385
  * [x] https://github.com/camunda/camunda-docs/pull/3324 
  * [x] https://github.com/camunda/camunda-docs/pull/3387
  * [x] https://github.com/camunda/camunda-docs/pull/3393
- (Optional) Users can configure a default HTTL to use for new diagrams in the modeler
  * [x] https://github.com/camunda/camunda-modeler/pull/4147
  * [x] https://github.com/camunda/camunda-modeler/pull/4162

We use the following link to external documentation: https://docs.camunda.org/manual/latest/user-guide/process-engine/history/.

### Alternatives considered

Yes

**Comment by nikku** [comment]
@toco-cam Thanks for opening this issue.

Let's get the documentation that is supposed to be linked in place. We can then go ahead to implement this fairly swiftly.

**Comment by toco-cam** [comment]
@nikku can you share the link to the docs page again please.

**Comment by nikku** [comment]
We feature modeling guidance [here](https://docs.camunda.io/docs/next/components/modeler/reference/modeling-guidance/).

**Comment by prajwolbhandari1** [comment]
Let me work on it.

**Comment by prajwolbhandari1** [comment]
Did we decide on this solution?

On the proposed solution above:
1) No default values are displayed in Modeler for HTTL (CMMN, DMN, BPMN)
-- no default values. 

2) Modeler displays an info with the suggestion to set the HTTL to 180 days as a starting point, with a link to the linting hints (in the docs) which explains why HTTL is necessary and how to set an engine HTTL
-- docs hints this link -> https://docs.camunda.org/manual/7.20/update/minor/719-to-720/#enforce-history-time-to-live

3) For Power Users (With engine configuration) the Modeler provides a flag to disable the info for users with HTTL configured on the engine)
-- which flag are you referring to? Can u please elaborate on this?


Also, are we going to use flags.json file to set historyTimeToLive value in modeler or just leaving empty with a linting doc link as mentioned above. 

Attached: I made historyTimeToLive textfield as an optional. I will add linting hints - a doc link.

https://github.com/camunda/camunda-modeler/assets/147008971/a1aaeb67-53ff-455e-a97a-092594bd50c2

**Comment by prajwolbhandari1** [comment]
@nikku @toco-cam Once we finalize with a solution. Can you please put my name on the ticket? I can work on this.

**Comment by prajwolbhandari1** [comment]
Here is the updated history time to live lint that points to the doc on BMPM side. Please clarify on the above questions.

https://github.com/camunda/camunda-modeler/assets/147008971/b9abd523-02b2-4835-9569-eac9b0817992

**Comment by prajwolbhandari1** [comment]
@toco-cam @nikku any thoughts?s

**Comment by nikku** [comment]
@prajwolbhandari1 Thanks for your work on this. We'll only be able to pick this up starting from next week. If you want to you can already open a PR in the mean time.

Validation for HTTL being missing must be updated via [bpmnlint-plugin-camunda-compat](https://github.com/camunda/bpmnlint-plugin-camunda-compat/blob/main/index.js#L67). Thanks!

**Comment by prajwolbhandari1** [comment]
@nikku thank you for your reply.

We are able to get rid of the validation updating bpmnlint-plugin-camunda-compat (Opening a PR soon) but we have few questions on the proposed solution that I posted above. Do you mind looking at it (few posts above)?

**Comment by prajwolbhandari1** [comment]
@nikku @toco-cam can you guys please help me understand the proposed solution? My question is above.

Also, are you sure we don't want https://github.com/camunda/camunda-modeler/issues/3869 as an option?  It will help to set default value in modeler. I can see it will solve few use cases.

**Comment by nikku** [comment]
@prajwolbhandari1 Not sure which question you refer to. The only one I found was this one:

> > For Power Users (With engine configuration) the Modeler provides a flag to disable the info for users with HTTL configured on the engine)
>
> -- which flag are you referring to? Can u please elaborate on this?

We are going to [introduce a flag](https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/flags/#available-flags), controlled via `flags.json` or command line to opt-out of the HTTL hint. I propose the name of the flag shall be `disable-httl-hint`. We'll _not provide a default value_ via that flag, as either the user shall _explicitly_ set the HTTL _or_  the engine mandates the HTTL to be used.

**Comment by prajwolbhandari1** [comment]
@nikku Thank you for the clarification. 

Can you please provide an example how we can disable/enable hint in modeler? 

This should not be that bad to implement hopefully. I will work on it. #1 and #2 pieces above are done. Will work on the flags.json (disable-httl-hint) next.

**Comment by prajwolbhandari1** [comment]
@nikku appreciate it!

Does it make sense to put user hint as 'Set Time to Live as 180. _<**Link for docs>**_' ?    
             _<**Link for docs>**_ -> https://docs.camunda.org/manual/7.20/update/minor/719-to-720/#enforce-history-time-to-live


Can you point me a place where we can enable/disable user info ?

**Comment by prajwolbhandari1** [comment]
I am working on with the team to raise a PR that we worked on so far. Raising the PR soon tomorrow or day after.

**Comment by nikku** [comment]
@toco-cam We could consider to address this along with https://github.com/camunda/camunda-modeler/issues/4120.

**Comment by prajwolbhandari1** [comment]
@nikku @toco-cam I also see the similar message in cmmn deployments if we don't provide any default values.

**Comment by toco-cam** [comment]
> No default values are displayed in Modeler for HTTL (CMMN, DMN, BPMN)
@prajwolbhandari1 The target is to handle all HTTL models in the same manner.

**Comment by nikku** [comment]
We have an initial draft for the modeling guidance: https://github.com/camunda/camunda-docs/pull/3324.

**Comment by nikku** [comment]
As a start we want to tackle BPMN. Of course DMN and (unlikely but possible) CMMN would follow suite.

**Comment by prajwolbhandari1** [comment]
Looks like cmmn-js-properties-panel is archived. Can't raise a PR on that repo.

**Comment by nikku** [comment]
Yes. We'll not invest into CMMN for the moment.

**Comment by nikku** [comment]
Thanks for your PRs @prajwolbhandari1, I'll look into them today. Great work :clap:

**Comment by nikku** [comment]
Proposed hint to C7 users regarding history time to live - https://github.com/bpmn-io/dmn-js-properties-panel/pull/82.

**Comment by nikku** [comment]
Informative message `info` lint message - https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/160.

**Comment by nikku** [comment]
@toco-cam Two options regarding the power-user flag:

* :a: Opt out of validation (and assume that engine sets HTTL)
* :b: Ensure that diagrams have a defined HTTL (in accordance with flag) => https://github.com/camunda/camunda-modeler/pull/4147.

My assessment:

:b: Ensures HTTL is always configured on a diagram in a nice way.
:a: Allows users to NOT configure HTTL, and not bothering about it (as the contract is that engine configured it).

What do you think?

**Comment by nikku** [comment]
@prajwolbhandari1 Thanks again. You PRs helped a ton to drive this forward.

We're still in the process of clarifying two things:

* https://github.com/camunda/camunda-modeler/issues/4062#issuecomment-1959597395
* Link to documentation page, documenting HTTL and user options => Likely is going to be `https://docs.camunda.org/manual/latest/user-guide/process-engine/history/` (to be created page).

Only then we'll be able to move forward.

**Comment by HarishMalavade** [comment]
> @toco-cam Two options regarding the power-user flag:
> 
> * 🅰️ Opt out of validation (and assume that engine sets HTTL)
> * 🅱️ Ensure that diagrams have a defined HTTL (in accordance with flag) => [feat(client): Ability to set a default history time to live via flags… #4147](https://github.com/camunda/camunda-modeler/pull/4147).
> 
> My assessment:
> 
> 🅱️ Ensures HTTL is always configured on a diagram in a nice way. 🅰️ Allows users to NOT configure HTTL, and not bothering about it (as the contract is that engine configured it).
> 
> What do you think?

I had created similar issue which was closed with a link to this one(https://github.com/camunda/camunda-modeler/issues/3869) - I personally  like the approach of setting it through the flag gives flexibility for both Modeler level configuration and as well as respecting engine level where it is set

**Comment by prajwolbhandari1** [comment]
@nikku thank you for the PR reviews.

Is there anything that you want from my side other than clarifying few things from @toco-cam ?

**Comment by nikku** [comment]
@prajwolbhandari1 consider to update your PR in the BPMN properties panel => https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1028#issuecomment-1960808121.

**Comment by nikku** [comment]
@prajwolbhandari1 As indicated in https://github.com/camunda/camunda-modeler/issues/4062#issuecomment-1959597395 we want to give users the ability to opt out of the HTTL hint completely, for scenarios where this is configured (set to a default and/or disabled) in the engine.

What do you think about updating https://github.com/camunda/camunda-modeler/pull/4147 with the following:

* We allow a special value `false` for the flag
* If provided, no HTTL will be configured, and no informative hint will be provided (https://github.com/camunda/linting/pull/100).

**Comment by nikku** [comment]
Integrating validation ("info") + updated properties panels :arrow_right: https://github.com/camunda/camunda-modeler/pull/4150.

**Comment by nikku** [comment]
Disable HTTL hint via flag - https://github.com/camunda/camunda-modeler/pull/4151.

**Comment by nikku** [comment]
@prajwolbhandari1 I took care of most issues, including disabling the hint via a flag (https://github.com/camunda/camunda-modeler/pull/4151).

What is remaining is the improved UX in the BPMN properties panel: https://github.com/camunda/camunda-modeler/issues/4062#issuecomment-1960809305

**Comment by nikku** [comment]
@prajwolbhandari1 a preview of the upcoming improvements will be available in the [next nightly](https://downloads.camunda.cloud/release/camunda-modeler/nightly/).

**Comment by prajwolbhandari1** [comment]
@nikku just pushed the BPMN properties panel toolkit change.

**Comment by nikku** [comment]
Integration of BPMN properties panel HTTL hint: https://github.com/camunda/camunda-modeler/pull/4157.

Thanks @prajwolbhandari1 for the follow-up!

**Comment by nikku** [comment]
Documentation update is ready for review: https://github.com/camunda/camunda-docs/pull/3324

**Comment by nikku** [comment]
Final batch of documentation updates incoming :tada:.

**Comment by nikku** [comment]
@prajwolbhandari1 Why do you favor diagram configuration over engine configuration?

If you want to go ahead with this, then please updated it on top of the latest `develop` branch (were we added the disable-httl-hint flag). Your PR could be a cherry on top if we see that it could be valueable for a use case.

**Comment by prajwolbhandari1** [comment]
@nikku will do that and let you know.

**Comment by nikku** [comment]
> @prajwolbhandari1 Why do you favor diagram configuration over engine configuration?

Please also allow us to learn about _why_ you think this is a better approach, in your environment. This helps us evaluate how we further proceed.

**Comment by HarishMalavade** [comment]
@nikku in our organization our camunda set up is shared process engine and we have multiple product lines that have different requirements based on process they build. and each product line can have hundreds of process model include parent and call activities. 
For Example our trade processes have requirement to retain history only for 30 days
Where as our Defined contribution processes have requirements to retain history for 180 days and some others beyond 80 days
Since all these processes are deployed to same engine(shared) and we cannot leverage one httl value on the engine side and at the same time we cannot have history retained forever for performance concerns.

We do give different version of desktop modelers to BPM developers across product lines with our custom elements template and settings like disabling cmmn,  httl etc in a package that we give them. 

the changes @prajwolbhandari1 made will allow us to enforce httl on the modeler side during design time (Catch on left) 
We work for Fintech. Please request you if it does not impact anything else to merge code from @prajwolbhandari1 so we can benefit from this contribution.

**Comment by prajwolbhandari1** [comment]
@nikku just pushed the change https://github.com/camunda/camunda-modeler/pull/4147

**Comment by nikku** [comment]
`default-httl` flag is going to be available to customized the default history time to live value to be used for new diagrams.

**Comment by nikku** [comment]
Thanks @prajwolbhandari1, @HarishMalavade and anyone else who contributed to this discussion issue in a meaningful way :heart:.

This is scheduled for release with the next Desktop Modeler. I'm super happy how this turned out.

**Comment by prajwolbhandari1** [comment]
Thanks @nikku for all your help.
