### ISSUE TITLE
Catch-all escalation start event is disallowed

### ISSUE THREAD

**Issue by schattenk** [camunda/camunda-modeler#4064]
### Describe the bug

In the modeler, an escalation start event cannot be a catch-all event, but the engine supports such events.

The modeler shows two error messages
"Element of type < bpmn:EscalationEventDefinition > must have property < escalationRef >." (error panel)
"Global escalation reference must be defined." (property panel)

### Steps to reproduce

Please refer to the attached process: [escalation-start-event.txt](https://github.com/camunda/camunda-modeler/files/13937450/escalation-start-event.txt)

1. Create a process and add an expanded sub-process.
2. In the sub process, throw an escalation end event.
3. In the sub process, create an event sub process with an escalation catch-all event (global reference: < none >).
4. Optionally, for comparison: Attach a boundary escalation event to the sub process and make it an escalation catch-all event (global reference: < none >).
5. Start an instance.

### Expected behavior

There should be no error messages, since an escalation start event can be a catch-all event, just like a boundary escalation event.

### Environment

Camunda Modeler 5.19.0

**Comment by nikku** [comment]
@philippfromme Please verify if this got fixed with https://github.com/camunda/camunda-modeler/issues/4064. I believe so.
