### ISSUE TITLE
Expression editor swallows keystrokes 

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-modeler#4073]
### Describe the bug

Typing a longer expression in the expression editor, it starts randomly swallowing characters. Written chars disappear when clicking somewhere, or deleted chars reappear again.

### Steps to reproduce

1. Write a longer expression
2. The editor starts swallowing updates. They disappear, or deletions are reset

Use the following diagram as an example, and see the video attached

[scan-forum-for-new-relevant-posts.bpmn.zip](https://github.com/camunda/camunda-modeler/files/14026826/scan-forum-for-new-relevant-posts.bpmn.zip)

https://github.com/camunda/camunda-modeler/assets/56470362/3ba279f3-522e-4b4e-9ba5-59f367f3b6a9

### Expected behavior

Every change should be persisted immediately, and not reset after debounce etc.

### Environment

- Camunda Modeler Version: 5.19

**Comment by nikku** [comment]
@marstamm Thanks to your repro. I can confirm it is broken (and needs to be fixed) at the core: https://github.com/nikku/lezer-feel/pull/32.

**Comment by marstamm** [comment]
I'll see if I can create a PR in the core

**Comment by nikku** [comment]
@marstamm I believe https://github.com/nikku/lezer-feel/pull/32 already contains the fix. Please have a look.

**Comment by nikku** [comment]
@marstamm The issue you reported is fixed upstream via [`lezer-feel@1.2.6`](https://github.com/nikku/lezer-feel/releases/tag/v1.2.6).

**Comment by nikku** [comment]
@christian-konrad This will be fixed in upcoming releases of our modeling tools.
