### ISSUE TITLE
Request to add a new capability "tracking fields" to Camunda Modeler 

### ISSUE THREAD

**Issue by kbhogadi** [camunda/camunda-modeler#4088]
### Problem you would like to solve

Please add "Tracking Fields" Capabilty in Camunda Modeler opensource future releases.

### Proposed solution

We are in the process of evaluating BPMN modelers to switch from IBM Blue Works Live. Camunda modeler seems to be a right alternative except few important required features missing. One of them is 'tracking fields' (shown below)

Blueworks Live provides below  **tracking fields** that our business teams use this functionality that helps them to trace their processes which doesn't exist in the Camunda Modeler.

![BWL_Snippet](https://github.com/camunda/camunda-modeler/assets/68969257/9491519f-3dc6-48be-9138-85715bc336bb)

### Alternatives considered

It's useful to have the similar IBM Blue Works Live 'tracking fields' option in Camunda Modeler opensource.

### Additional context

This is Camunda Modeler related request. Thank You !

**Comment by kbhogadi** [comment]
Done. Created another feature request for export functionality. 
Here is the URL : https://github.com/camunda/camunda-modeler/issues/4107

**Comment by kbhogadi** [comment]
Done. Separated 2 feature requests, #4088 and #4107. Thank You!

Thanks,
Kamala

**Comment by barmac** [comment]
What is the use case? What problem does it solve?

**Comment by nikku** [comment]
@kbhogadi?
