### ISSUE TITLE
Unsupported output mappings show for termination end event

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4096]
### Describe the bug

As a user I'm able to define an output mapping for terminate end events, even though it is [not supported by Camunda 8](https://camunda.slack.com/archives/CSQ2E3BT4/p1706882801336469?thread_ts=1706880632.887939&cid=CSQ2E3BT4):

![image](https://github.com/camunda/camunda-modeler/assets/58601/e72b5ce3-aa7c-462a-9f40-77b702817056)

### Steps to reproduce

1. model terminate end event
2. see that output mapping is possible
3. (executing it you'll see it does nothing)

### Expected behavior

Output mappings are disabled for terminate end events.

### Environment

- OS: Linux
- Camunda Modeler Version: v5.19.0
- Execution Platform: Camunda 8
- Installed plug-ins: None

### Additional context

Related to https://jira.camunda.com/browse/SUPPORT-20243.

**Comment by barmac** [comment]
I am moving this to `ready` as it's an easy fix.

**Comment by barmac** [comment]
This will be fixed via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1027
