### ISSUE TITLE
Add OAuth scope field to deploy modal

### ISSUE THREAD

**Issue by wollefitz** [camunda/camunda-modeler#4102]
_Related to https://github.com/camunda/product-hub/issues/2089._

### Problem you would like to solve

As a user, I want to be able to deploy to Zeebe clusters that use OAuth2 as authentication mechanism with a provider that requires a `scope` in the token request, e.g. Microsoft Entra ID.

### Proposed solution

Add a field "Scope" (or better "OAuth Scope" and rename "Audience" to "OAuth Audience") to the deploy modal which gets picked up by the Zeebe client for acquiring a token.

### Alternatives considered

None

### Additional context

- Web Modeler is also missing the field, see https://github.com/camunda/web-modeler/issues/8027
- https://github.com/camunda-community-hub/zeebe-client-node-js has to provide support for passing a `scope` within the token request, see https://github.com/camunda-community-hub/camunda-8-js-sdk/issues/21
- reported via [Slack](https://camunda.slack.com/archives/C06112NS4GJ/p1707169292640159?thread_ts=1706905378.492159&cid=C06112NS4GJ)

----

Depends on https://github.com/camunda-community-hub/zeebe-client-node-js/pull/363

**Comment by nikku** [comment]
We'd need [zeebe-node](https://github.com/camunda-community-hub/zeebe-client-node-js) to support passing a custom `scope` within the token request and this [seems to be not implemented (yet)](https://github.com/search?q=repo%3Acamunda-community-hub%2Fzeebe-client-node-js+scope&type=code). So as it stands we're currently blocked by upstream here I believe? 

Shall I create an upstream issue @jwulf?

**Comment by nikku** [comment]
@wollefitz Thanks for opening this issue!

**Comment by wollefitz** [comment]
> Shall I create an upstream issue @jwulf?

@nikku There's already https://github.com/camunda-community-hub/camunda-8-js-sdk/issues/21 (linked below "Additional Contect") created by Josh.

**Comment by nikku** [comment]
Thanks @wollefitz. I'm a little bit confused as I don't care about camunda-8-js-sdk. We use the zeebe-node client and have not immediate intention to move to something else, unless explicitly required to do so.

**Comment by jwulf** [comment]
@nikku - with the 8.5.0 release we will be supporting the JS SDK. 

The Zeebe Node client published as zeebe-node is going to be unmaintained from 8.5.0. 

The new package will be @camunda8/zeebe. It’s the same code base, but moved to the camunda-8-js-sdk monorepo.

**Comment by nikku** [comment]
Thanks for the heads-up @jwulf.

**Comment by nikku** [comment]
Created https://github.com/camunda/camunda-modeler/issues/4109 from our end. Would be great to get a heads-up when `@camunda8/zeebe` is ready to be migrated to.

It would help us if we'd get `scope` support in one way or the other, so we can integrate it into the modeler.

**Comment by nikku** [comment]
Waiting for upstream https://github.com/camunda-community-hub/zeebe-client-node-js/pull/363 to be merged and released.

**Comment by nikku** [comment]
Continuing to integrate this via https://github.com/camunda/camunda-modeler/pull/4169.

**Comment by nikku** [comment]
This will be released with the next Desktop Modeler release (`v5.21.0`).
