### ISSUE TITLE
"Open recent file" displays new, unsaved diagrams as empty entries

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4110]
### Describe the bug

![image](https://github.com/camunda/camunda-modeler/assets/28307541/251ac5e4-c63c-4c4b-bbc0-80fb8cbc88af)

### Steps to reproduce

1. Create new file
2. Close it without saving
3. Select "Open recent file" in the menu

https://github.com/camunda/camunda-modeler/assets/28307541/7af1e111-f856-4d58-9986-53833c72c2ff

### Expected behavior

Either we don't show it or we display a placeholder.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.20.0
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/4115
