### ISSUE TITLE
Properties panel crashes when file is closed with open FEEL popup editor

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4112]
### Describe the bug

Properties panel crashes when file is closed with open FEEL popup editor. It doesn't work anymore, and the problem is persisted among diagrams until Modeler is reopened.

https://github.com/camunda/camunda-modeler/assets/28307541/80e39219-1e5d-4998-bf73-af2da107035a

### Steps to reproduce

1. Open FEEL popup editor
2. Close the file
3. now this happens

### Expected behavior

It should close without crashes.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.20.0
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

**Comment by barmac** [comment]
This is a regression since I cannot reproduce it in 5.19.0

**Comment by nikku** [comment]
I did a quick check in web modeler and see that they are not affected in the same way.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/4114.
