### ISSUE TITLE
Link to documentation broken for HTML form fields

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#4118]
### Describe the bug

Link to documentation in the HTML form field is broken 

### Steps to reproduce

https://github.com/camunda/camunda-modeler/assets/85225325/bbe99fbd-7c02-4325-8abf-7321863f0b3e

### Expected behavior

Link to documentation should work

### Environment

- OS: [Windows 10]
- Camunda Modeler Version: [5.20.0]
- Execution Platform: [ Camunda 8]
- Installed plug-ins: [...]

**Comment by nikku** [comment]
This is supposedly going to be addressed in a timely manner (with v8.4.0-alpha-1 release) ([ref](https://camunda.slack.com/archives/C043W5V88M7/p1707319200939549?thread_ts=1707318807.376009&cid=C043W5V88M7))

**Comment by nikku** [comment]
Unfortunately this is not published (yet). The documentation is available [under the `next` umbrella](https://docs.camunda.io/docs/next/components/modeler/forms/form-element-library/forms-element-library-html/), but not part of our `latest` train.

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/form-js/pull/1039.
