### ISSUE TITLE
Create/append anything should display exact match first

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4122]
### Problem you would like to solve

I am always frustrated when I try to create Service task, type "Ser", and uSER task appears first.

### Proposed solution

If beginning of the entry matches with given text, display entry on top.

### Alternatives considered

Keep frustration.

### Additional context

https://github.com/camunda/camunda-modeler/assets/28307541/109df8f6-8ed5-4390-871f-f5146b723254

**Comment by nikku** [comment]
Makes loads of sense to fix this, and it will be easy, too.

**Comment by nikku** [comment]
Incorporated at the core via https://github.com/bpmn-io/diagram-js/pull/932, released as [diagram-js@15.1.0](https://github.com/bpmn-io/diagram-js/blob/develop/CHANGELOG.md#1510).

Pending downstream integration.

**Comment by nikku** [comment]
Depends on https://github.com/camunda/camunda-bpmn-js/pull/393 to be released and incorporated.

**Comment by nikku** [comment]
Unfortunately not fully addressed via https://github.com/camunda/camunda-modeler/pull/4711 (yet):

![capture XslAmt_optimized](https://github.com/user-attachments/assets/a9f0cdba-4bf6-4c75-80e8-2cd8c31d69fb)

(Expected `Bewerber` to be priority (first) item, but in certain circumstances huge items get higher precedence).

**Comment by nikku** [comment]
Requires https://github.com/bpmn-io/diagram-js/pull/953 to be fixed and integrated.
