### ISSUE TITLE
Export to PNG of a diagram with webhook connector fails

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4127]
### Describe the bug

In Camunda Modeler 5.20.0, the attached BPMN fails to export to PNG, and an error is printed:

```
This page contains the following errors:error on line 1 at column 723: Unescaped '<' not allowed in attributes values
Below is a rendering of the page up to the first error. [ ERROR ]
```

[insurance.bpmn.txt](https://github.com/camunda/camunda-modeler/files/14239778/insurance.bpmn.txt)

When I remove the event with custom icon, it exports correctly.

### Steps to reproduce

1. Open the attached BPMN
2. Try to export to PNG
3. now this happens

### Expected behavior

It should export.

### Environment

- OS: MacOS
- Camunda Modeler Version: 5.20.0
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

**Comment by nikku** [comment]
This works with all but the webhook connector icon, cf. [test diagram](https://github.com/camunda/camunda-modeler/files/14258065/icon.bpmn.txt).

Hence I think there may be something wrong with the webhook connector icon. Let's update the scope of this issue accordingly.

**Comment by barmac** [comment]
Right, it works with the diagram you provided. I will update the issue accordingly.

**Comment by SamanthaHolstine** [comment]
Had a community member facing the same issue, printing the same error. [Forum question here](https://forum.camunda.io/t/not-working-export-to-png/53735). The forum question includes the diagram having issues.

**Comment by NPDeehan** [comment]
Hey folks, is there any update on this?

**Comment by barmac** [comment]
I can still reproduce it in both 5.27 and the current nightly, so this is not going to be fixed in the upcoming release. Is this reported often? Any other reason we should prioritize this?

**Comment by NPDeehan** [comment]
It comes up fairly frequently and it's a very common feature for business users to come across.

**Comment by barmac** [comment]
Thanks, I'll move it to ready to discuss in the upcoming iteration planning.

**Comment by barmac** [comment]
The 3rd answer to https://stackoverflow.com/questions/3975499/convert-svg-to-image-jpeg-png-etc-in-the-browser could help.

**Comment by barmac** [comment]
I just checked if we can drop canvg and thus fix this issue, but it's not enough: https://github.com/camunda/camunda-modeler/pull/4569

**Comment by barmac** [comment]
So this issue goes all the way up to `tiny-svg`: https://github.com/bpmn-io/tiny-svg/issues/16
Once we fix it there and integrate in the dependencies, the issue will be fixed.

**Comment by nikku** [comment]
Bug [here](https://github.com/bpmn-io/tiny-svg/blob/main/lib/util/serialize.js#L6).

**Comment by barmac** [comment]
Fixed upstream via https://github.com/bpmn-io/tiny-svg/pull/17, and will be closed via https://github.com/camunda/camunda-modeler/pull/4576

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/4576
