### ISSUE TITLE
Maximum call stack size exceeded in variable resolver

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4139]
### Describe the bug

Sentry still reports RangeError despite https://github.com/bpmn-io/variable-resolver/pull/23

[Sentry report](https://camunda-modeling.sentry.io/issues/4744155148/events/16e598c440bf4cfa9fc214665c6eec43/?environment=production&project=5223041&referrer=alert-rule-issue-list)

### Steps to reproduce

I can't tell.

### Expected behavior

No errors.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.20.0
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

**Comment by nikku** [comment]
We have some options:

* Add additional guardrails to ensure that errors are more comprehensive
* Add recursion counter and bail out (with proper context) on, i.e. `> 100` depth
* Wait for customer to report a bug with clear steps to reproduce

**Comment by marstamm** [comment]
This is indeed another problem than what we fixed previously. What is happening here is that the user has a very big context, like 100k+ entries. We use `.push(...arr)`, which creates a stack for every entry in the array it is adding.

We can prevent this from happening by using different methods of [concatenation](https://stackoverflow.com/questions/61740599/rangeerror-maximum-call-stack-size-exceeded-with-array-push). What would be interesting to see is if the user actually creates such contexts or if the big amount of entries is a bug.

**Comment by nikku** [comment]
Waiting integration, fixed upstream via https://github.com/camunda/camunda-bpmn-js/pull/352.

**Comment by barmac** [comment]
Related: https://github.com/bpmn-io/bpmn-js-element-templates/issues/78
