### ISSUE TITLE
Provide convenient way to link resources (Web Modeler like)

### ISSUE THREAD

**Issue by imissar** [camunda/camunda-modeler#4146]
### Describe the bug

On selecting the user task, I'm unable to get the link option on camunda modeler desktop. Find the version details below

<img width="951" alt="image" src="https://github.com/camunda/camunda-modeler/assets/109382227/796afe30-cc93-4cad-866d-fe3b78369e65">

### Steps to reproduce

1. create a user task
2. create a camunda form
3. click on user task

### Expected behavior

A blue linking option must appear to link that form created

<img width="373" alt="image" src="https://github.com/camunda/camunda-modeler/assets/109382227/4621a12a-121a-470e-80c7-a19d599f1a43">

## Camunda Modeler system information
 * Version: 5.20.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda 8

### Additional context

Depends on https://github.com/camunda/camunda-modeler/issues/2508.

**Comment by nikku** [comment]
Moving to `backlog` for the time being.
