### ISSUE TITLE
Improve the "retries" tooltip in the properties panel 

### ISSUE THREAD

**Issue by crobbins215** [camunda/camunda-modeler#4148]
### Problem you would like to solve

Improve tooltip for clarity around "retries" as some users are confused by the description of "retries".

For example, if retries have been configured to 5 then they are expecting 6 executions of the task (initial + 5 retries), instead there are only 5 executions.

Docs show "This number is typically decremented with every attempt to execute the service task. Note that you need to do that in your worker code"
https://docs.camunda.io/docs/next/components/best-practices/development/dealing-with-problems-and-exceptions/#leveraging-retries

Current tooltip
![image](https://github.com/camunda/camunda-modeler/assets/10505316/c040d4b9-6088-40d2-a36f-66e414363cda)

### Proposed solution

Improve the current tooltip with something like 
“The amount of times the engine tries to execute this activity if a worker error is reported. The default is three.”

Optional: Consider adding a link to the documentation.

### Alternatives considered

"Attempt" or "Tries" instead of "retires" but not 100% on either of them.

**Comment by nikku** [comment]
Fix incoming via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1029.
