### ISSUE TITLE
Attached boundary events don't work in 1.3.0

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#415]
Using attached boundary events is really dodgy in the new version. 

Often, morphing event types doesn't work immediately , also labels disappear. 

![sep -13-2016 13-34-09](https://cloud.githubusercontent.com/assets/17595149/18472342/2a445028-79b7-11e6-8055-53f5a7c04335.gif)

**Comment by benhoffmann** [comment]
See also https://forum.camunda.org/t/error-boundary-event-missing/1527

**Comment by felix-mueller** [comment]
+1
