### ISSUE TITLE
Support HTTP Basic authentication for C8 SM deployment

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4160]
### Problem you would like to solve

Modeler supports currently only OAuth for secure deployment to C8 Self-Managed. This is a blocker for users who implement HTTP Basic (username + password) authentication.

### Proposed solution

Add option to provide username and password when deploying to C8 SM.

### Alternatives considered

There are none.

### Additional context

Reported via [SUPPORT-20648](https://jira.camunda.com/browse/SUPPORT-20648).

[HTTP Basic is supported out of the box in zeebe-node](https://github.com/camunda-community-hub/zeebe-client-node-js?tab=readme-ov-file#basic-auth).

**Comment by barmac** [comment]
This is not a lot of work yet a huge blocker for some of the users.

**Comment by nikku** [comment]
In lieu of focus removing from M75 (to re-consider for next milestone).
