### ISSUE TITLE
Update link to forum.camunda.io

### ISSUE THREAD

**Issue by xomiamoore** [camunda/camunda-modeler#4161]
### Describe the bug

The link to the Modeler category in the forum was updated, so it's now broken. It needs to be updated in both desktop and web modeler.

Old link: https://forum.camunda.io/c/modeler/
New link: https://forum.camunda.io/c/bpmn-modeling/ 

### Steps to reproduce

n/a

### Expected behavior

n/a

### Environment

n/a

**Comment by nikku** [comment]
@xomiamoore Not sure if redirects are possible. This will break in _all_ older versions of the modeler otherwise.

**Comment by xomiamoore** [comment]
@nikku I just found the option to redirect within Discourse, so I've turned that on for the old links. But we should still update it for the future versions.

**Comment by nikku** [comment]
Thanks @xomiamoore. Fixed via https://github.com/camunda/camunda-modeler/pull/4164.
