### ISSUE TITLE
Undo in expanded FEEL expression doesn't work for first input

### ISSUE THREAD

**Issue by ev-codes** [camunda/camunda-modeler#4167]
### Describe the bug

After expanding a FEEL expression box, users cannot undo the first input.

This can lead to lost work - e.g., if a user deletes existing text as their first action.

### Steps to reproduce

1. Create a diagram with an Activity
2. Change the Activity to be a User Task
3. Add a new field in Inputs
4. Write some text in the "Variable assignment value" field
5. Click the "expand" button in the "Variable assignment value" field (see screenshot below)
6. Select and delete all the text in the field
7. Try to undo with keyboard shortcut (Cmd-Z on Mac)

Expand button:
![Screenshot 2024-02-29 at 10 48 24 AM](https://github.com/camunda/camunda-modeler/assets/7648845/8d30b465-44a2-4100-bf7b-0f4fe66ea631)

### Expected behavior

Undo works - the deleted text should appear in the field again

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: Desktop v5.18.0, Web - dev.ultrawombat version as of Feb. 29, 10:52am CET
- Execution Platform: Camunda 8
- Installed plug-ins: none

### Additional context

Screen recording:
https://github.com/camunda/camunda-modeler/assets/7648845/144709d6-7ef0-431c-b09b-afc336f66e4d

---

Related to https://github.com/camunda/camunda-modeler/issues/3902.

**Comment by nikku** [comment]
@ev-codes Thanks for the report. As a workaround you can undo once the popup editor is closed.

We already track this problem via https://github.com/camunda/camunda-modeler/issues/3902, hence I'm closing this issue as a duplicate.
