### ISSUE TITLE
Be able to search for additional keywords in popup menu

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4182]
### Problem you would like to solve

As a user of element templates I'm always frustrated if I try to find a connector using the on board facilities. I seem to never find what I'm looking for.

#### Example

My goal is to create a new issue on GitHub. I search for `Create Issue` or `GitHub create issue` or `GitHub issue` and the search remains blank, despite the `GitHub connector` clearly offering this functionality to me.
 
![capture UAKBd5_optimized (1)](https://github.com/camunda/camunda-modeler/assets/58601/196ea70a-baaf-42d7-9b2f-d79a4ca78eb6)

### Proposed solution

I'd love the search to be more humane, and connectors to better expose what they can do (use-case driven)

#### Search

* [ ] Be able to reasonably find what I'm searching for
* [ ] Be forgiving, i.e. on a typo
* [x] Prioritize search results (most relevant first) (https://github.com/camunda/camunda-modeler/issues/4122)

#### Connectors

* [ ] Expose necessary details taking the end user orchestration perspective. I do not want to use the `GitHub connector`, but I want to execute a particular task using the `GitHub connector`, i.e. I want to _create an issue on GitHub_ or _add an issue comment_.

### Alternatives considered

None.

**Comment by sbuettner** [comment]
@bastiankoerber Please provide us a priority on this one.

**Comment by nikku** [comment]
Sharing some updates on this issue:

* The popup menu allows to search for `label`, `description` and `search` (a hidden, can be any context) value. It is up to implementors, i.e. [bpmn-js-element-templates](https://github.com/bpmn-io/bpmn-js-element-templates) to assemble `search` in a meaningful way.
* Since [`diagram-js@15.1.0`](https://github.com/bpmn-io/diagram-js/blob/develop/CHANGELOG.md#1510) we prioritize search works that match from the start of the sentence (https://github.com/camunda/camunda-modeler/issues/3439)
* Via https://github.com/camunda/camunda-bpmn-js/pull/367 work is on the way to match anything on the canvas in a `fuzzy` way; this makes search more forgiving in case of typos or wrong keywords

Moving to `ready` to consider our options once all these things have been merged.

**Comment by nikku** [comment]
Pending integration of [diagram-js@15.1.0+](https://github.com/bpmn-io/diagram-js/blob/develop/CHANGELOG.md#1510).

**Comment by nikku** [comment]
Depends on https://github.com/camunda/camunda-bpmn-js/pull/393 to be released and incorporated.
