### ISSUE TITLE
Multiple spaces between words in labels or annotations break image export

### ISSUE THREAD

**Issue by vkatushenok** [camunda/camunda-modeler#419]
See example diagram (with sample file) with three different cases:

[example.txt](https://github.com/camunda/camunda-modeler/files/484634/example.txt)

<img width="207" alt="screen shot 2016-09-21 at 11 52 40" src="https://cloud.githubusercontent.com/assets/2331533/18706373/ff2ca462-7ff1-11e6-9165-4990dc69baa7.png">

Exported SVG from such a diagram contains `&nbsp` characters instead of additional spaces.

**Comment by philippfromme** [comment]
Can't reproduce with Camunda Modeler 0.16.0

**Comment by vkatushenok** [comment]
Was still broken on 1.4 but fixed in 1.5.
