### ISSUE TITLE
Call activity template associations broken

### ISSUE THREAD

**Issue by ev-codes** [camunda/camunda-modeler#4198]
### Describe the bug

- As a web and desktop modeler user, I expect existing BPMN documents with Call Activity templates applied to still have these templates successfully linked when I open again
- Instead, the template can't be found (screenshot below) even though the template is still in the project (see screenshot)
- 
<img width="1439" alt="Template not found error message" src="https://github.com/camunda/camunda-modeler/assets/7648845/e453dd46-1354-4ce3-8bdf-6103d3272186">

- I also expect to be able to apply Call Activity templates to existing Call Activity Tasks
- Instead, my Call Activity templates to not appear in the search results after clicking the wrench or shapes/Change element button (see video)

https://github.com/camunda/camunda-modeler/assets/7648845/07a6f65f-1ea9-4c20-8c1e-ab40ba7748c0

### Steps to reproduce

1. Add the Call Activity element template to your project (or resources folder for Desktop Modeler) 
[Build New RC, Generation, Cluster.json](https://github.com/camunda/camunda-modeler/files/14670221/Build.New.RC.Generation.Cluster.json)
2. Open BPMN file with Call Activity template associated
[Connectors Artifact Release.bpmn.txt](https://github.com/camunda/camunda-modeler/files/14670216/Connectors.Artifact.Release.bpmn.txt)
3. Click on Task with Call Activity template associated

### Expected behavior

- As a web and desktop modeler user, I expect existing BPMN documents with Call Activity templates applied to still have these templates successfully linked when I open again
- Instead, the template can't be found (screenshot below) even though the template is still in the project (see screenshot)
- 
<img width="1439" alt="Template not found error message" src="https://github.com/camunda/camunda-modeler/assets/7648845/e453dd46-1354-4ce3-8bdf-6103d3272186">

- I also expect to be able to apply Call Activity templates to existing Call Activity Tasks
- Instead, my Call Activity templates to not appear in the search results after clicking the wrench or shapes/Change element button (see video)

https://github.com/camunda/camunda-modeler/assets/7648845/07a6f65f-1ea9-4c20-8c1e-ab40ba7748c0

### Environment

- OS: macOS 13.6.5
- Camunda Modeler Version: 5.18.0
- Execution Platform: Camunda 8
- Installed plug-ins: None

**Comment by nikku** [comment]
Thanks for opening this report. We'll have a look.

**Comment by barmac** [comment]
Hi,

The reason why template is marked as "Not found" in 5.18.0 is that the support for `zeebe:CalledElement` binding was added only in [5.19.0](https://github.com/camunda/camunda-modeler/blob/develop/CHANGELOG.md#5190). The template with unsupported binding type is invalid to the Modeler, and because of that not loaded. You can notice this in the output panel:

![image](https://github.com/camunda/camunda-modeler/assets/28307541/6ab13e92-1292-4ce7-adc0-80df9f153671)

I am closing this as non-issue. Feel free to comment if I got anything wrong.

**Comment by barmac** [comment]
I also had a look at the BPMN and the template that you provided, and the BPMN does not contain any reference to the template of ID `0a8f9c33-a829-4b42-b2f7-f1f4af63748f`, but there is an element with a template with another ID in UUID format: `zeebe:modelerTemplate="f57a6fa9-d77a-4c0e-b303-41c0958cb9ae"`
