### ISSUE TITLE
Windows 10 64 bit version doesn't work

### ISSUE THREAD

**Issue by ricardomatias** [camunda/camunda-modeler#42]
But the 32 bit does.

**Comment by nikku** [comment]
Need to tell users about that for downloading.

**Comment by nikku** [comment]
@NPDeehan Could you check if 64bit is still broken [with the latest nightly](https://camunda.org/release/camunda-modeler/nightly/)?

**Comment by NPDeehan** [comment]
Just checked it - working fine for me in the latest nightly.

**Comment by nikku** [comment]
Thanks for the comment. Closing this then.
