### ISSUE TITLE
Share feedback widget looks broken

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4213]
### Describe the bug

![image](https://github.com/camunda/camunda-modeler/assets/58601/594a9bbe-9567-4843-9639-db945619a2c1)

### Steps to reproduce

Open share feedback widget. See that it looks oddly formatted.

### Expected behavior

No multi-line (checkbox + label).

### Environment

- OS: Linux
- Camunda Modeler Version: v5.22.0 (works in v5.21.0)
- Execution Platform: Any
- Installed plug-ins: None

**Comment by nikku** [comment]
Same for deploy widget:

![image](https://github.com/camunda/camunda-modeler/assets/58601/1d8227bf-4802-4031-95a2-abd7c2026d4d)

**Comment by nikku** [comment]
Root cause: This broke with [this potentially](https://github.com/camunda/camunda-modeler/commit/d9170c39a1f8260b0bfadbb82953367ff349e0a5#diff-1846122c2c83a486a3693f7966aa522c34cf489f674185c4da0d9221683fd81fR52), at least with the commit:

```
deps: update deps
```

**Comment by nikku** [comment]
Addressed via https://github.com/camunda/camunda-modeler/pull/4215

**Comment by barmac** [comment]
I can reproduce the issue. The direct reason is that the `form-control` class is not applied in the RC.

**Comment by barmac** [comment]
Related to this unintentional breaking change: https://github.com/jaredpalmer/formik/issues/3883

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/4215
