### ISSUE TITLE
Add ability to count Flow Nodes in BPMN diagram - Full Diagram and Selection

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#422]
Would be helpful if there was a Statistics tab or some sort of inspector that would allow us to easily count the number of Flow Nodes (Activities-Tasks and Sub-Processes, Gateways, and Events) in a BPMN diagram.

Would be looking for both a diagram wide count and then just being able to count based on the current selection.

**Comment by nikku** [comment]
Why would that be helpful? I personally think this is out of scope for the Camunda Modeler.

**Comment by StephenOTT** [comment]
@nikku, I thought this would be a good item to add to the modeler because the flow node count is a number that is often used to determine level of complexity and the aggregate is often used by support contracts (N number of flow node instances per year will be supported under the contract).
As teams work on their BPMN, it would be helpful for them to understand the number of flow nodes they are creating to allow faster calculations of the total flow node instances being generated in a year (their estimates).  If there is not a auto-count, then people have to manually count.

The count is not a perfect representation because of sub-processes, multi-instance, and branching with percentage variation, but it is a good base.

**Comment by nikku** [comment]
I'd rather have that information as part of the run-time rather than the design time environment. Or are you talking about a design time only use-case here?

**Comment by StephenOTT** [comment]
@nikku I think it is valuable in both locations.  Run-time is good for understanding actual usage.

But at the design time I think it is valuable because someone builds XYZ process and a common question can be "whats the predicted node flow instance impact?" Which would be at the highest level of detail: Node Flow Count * estimated instances.
Either the designer has to manually count and keep recounting during adjustments, or the modeler provides a general count (of course won't be able to account for everything, but it is *much better* than a manual count).

**Comment by nikku** [comment]
> whats the predicted node flow instance impact?

The only way this makes sense to me if we rephrase the question to "What is the process complexity" (flow node instances is one of the metrics there). 

We may provide ways to extend the Modeler beyond element templates some time into the future. This functionality would be a good candidate for such an extension.

**Comment by StephenOTT** [comment]
>The only way this makes sense to me if we rephrase the question to "What is the process complexity" (flow node instances is one of the metrics there).

Sure, that makes sense for my use case.

Thanks

**Comment by nikku** [comment]
We'll not support this any time soon. [Modeler plug-ins](https://github.com/camunda/camunda-modeler-plugins) may be the way to implement such feature.

We're happy to feature such plug-in, if you implement it.
