### ISSUE TITLE
Insufficient validation of example data provided for a BPMN process

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4220]
### Describe the bug

Using [example data](https://docs.camunda.io/docs/components/modeler/data-handling/) users are able  to provide additional completion context to our existing code intelligence. The data, to my knowledge, must be a JSON object literal `{ "someVariable": 1, "otherVariable": 2 }`. However we don't clearly guide our users towards that in our [documentation](https://docs.camunda.io/docs/components/modeler/data-handling/) and/or validation.

![image](https://github.com/camunda/camunda-modeler/assets/58601/de3e1c48-2420-4fb2-bf2b-f84ea00fc37b)

### Steps to reproduce

1. enter non object JSON element into example data
2. validation passes
3. interesting things happen for completion

### Expected behavior

* [ ] We ensure that example data is an object literal
* [ ] The documentation clearly reflects that (example data is not JSON, but a JSON object literal)

### Environment

- OS: Any
- Camunda Modeler Version: Any
- Execution Platform: Camunda 8
- Installed plug-ins: None

### Additional context

Brought up in [this conversation](https://camunda.slack.com/archives/C032H77434N/p1711551948915249).

**Comment by marstamm** [comment]
Released camunda/example-data-properties-provider@1.2.1 with stricter validation, will be integrated for the next release

**Comment by nikku** [comment]
@marstamm Let's proceed with the integration into the Desktop Modeler (`develop`) so we can close this issue.

**Comment by marstamm** [comment]
This was accidentally closed due to me not being on a feature branch when pushing first 🙈 

I reverted the commit on develop and this PR will actually close the issue: https://github.com/camunda/camunda-modeler/pull/4255
