### ISSUE TITLE
get plugin directory

### ISSUE THREAD

**Issue by tayfuncelik** [camunda/camunda-modeler#4222]
### Problem you would like to solve

getPluginsDirectory method is not working because it is deprecated . how can we get plugin directory ?

var img = document.createElement('img');
img.src = getPluginsDirectory() + '/camunda-modeler-plugin-example/logo.png';

### Proposed solution

non

### Alternatives considered

none

**Comment by philippfromme** [comment]
Closed as duplicate of https://github.com/camunda/camunda-modeler/issues/4223.
