### ISSUE TITLE
plugin directory path

### ISSUE THREAD

**Issue by tayfuncelik** [camunda/camunda-modeler#4223]
### What should we do?

getPluginsDirectory method is no working because it is deprecated . how can we get plugin directory ?

### Why should we do it?

to be able to give more freedom for open source support

**Comment by philippfromme** [comment]
The global plug-in helper `getPluginsDirectory()` did not work reliably and got deprecated. You can use paths prefixed with `app-plugins://` (e.g. `app-plugins://{pluginName}/{pathToResource}`) to reference static plug-in assets.
