### ISSUE TITLE
[spike] investigate canvg return to original repo

### ISSUE THREAD

**Issue by ricardomatias** [camunda/camunda-modeler#423]
Needs testing and npm support to merge. (if it actually works)

https://github.com/bpmn-io/canvg-browser/pull/1

**Comment by ricardomatias** [comment]
Posted this comment upstream: https://github.com/canvg/canvg/pull/477#issuecomment-267029932

**Comment by nikku** [comment]
The question is: Will going back to the original repository make maintenance easier for us (patch merges and stuff)?

**Comment by nikku** [comment]
My impression: Nope, we won't.
