### ISSUE TITLE
Modeler freezes when the attached template is applied

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4234]
### Describe the bug

A `RangeError: Maximum call stack size exceeded` is thrown when the attached template is applied. An element can be created from that template without freezing though.

[ms-teams.json](https://github.com/camunda/camunda-modeler/files/14933482/ms-teams.json)

### Steps to reproduce

1. Add the template to `element-templates` folder
2. Apply the template
3. Modeler freezes

### Expected behavior

Modeler should not freeze. The template should be rejected as invalid, or a single runtime error should be thrown.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.21, 5.22
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

Reported via https://camunda.slack.com/archives/C0693F1NFK5/p1712752058487909

Thanks @olegme-camunda!

**Comment by nikku** [comment]
Likely closed via https://github.com/camunda/camunda-modeler/commit/3a4cd3a1f7d4108b5d73dc510e0ef00e4ce39fd2. Unfortunately we failed to integrate this bug fix in v5.22.0

**Comment by nikku** [comment]
Verified this works in nightly:

![capture OiLk6e_optimized](https://github.com/camunda/camunda-modeler/assets/58601/39edbce1-f23a-462d-9980-238d26a3ef5a)
