### ISSUE TITLE
Cannot build application locally on MacOS (`spawnSync zip ENOENT`)

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4236]
### Describe the bug

I cannot build the application locally due to an error: `⨯ spawnSync zip ENOENT  failedTask=build stackTrace=Error: spawnSync zip ENOENT`.

### Steps to reproduce

1. Be on Mac
2. Run `npm run build`
3. now this happens

### Expected behavior

It should work.

### Environment

- OS: MacOS Sonoma 14.4
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

Discovered by @jwulf 

Related to https://github.com/camunda/camunda-modeler/issues/1996

**Comment by jwulf** [comment]
Additional context:

```
jwulf@Joshs-MacBook-Pro camunda-modeler % which zip
/usr/bin/zip
```

**Comment by barmac** [comment]
This seems to be related to https://github.com/electron-userland/electron-builder/issues/6821

**Comment by barmac** [comment]
OK this is actually easier than I thought. In the ZIP step, we use a wrong directory name:

![image](https://github.com/camunda/camunda-modeler/assets/28307541/0ca6cc8d-a05a-45a5-b6e7-b4bb0f65ba02)

Notice that we use `/dist/mac` while only `/dist/mac-arm64` exists.

**Comment by nikku** [comment]
@barmac As we're on it, shall we start to create different distributions for ARM vs. intel?

**Comment by barmac** [comment]
You're reading my mind.

**Comment by barmac** [comment]
With updated file name, it builds correctly on Mac. I will now try out building for both ARM and x86.

**Comment by barmac** [comment]
I was able to build for ARM64 and I gotta tell you the Modeler opens super quickly. It's a major improvement. Expect a PR today.
