### ISSUE TITLE
Update download page at Camunda.com with new MacOS links

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4239]
### What should we do?

Due to https://github.com/camunda/camunda-modeler/pull/4238, the download links for MacOS distros will change with the upcoming release. So instead of the ordinary version number update, we need to add links to both x64 and arm64 distros at 
 https://camunda.com/download/modeler/

### Why should we do it?

To provide correct links on the website.

**Comment by philippfromme** [comment]
Done.
