### ISSUE TITLE
Desktop Modeler 5.22.0 crashes - Needs to be killed with Task Manager

### ISSUE THREAD

**Issue by till-stadtler** [camunda/camunda-modeler#4240]
### Describe the bug

When I try to use the form preview in the attached form, the Desktop Modeler crashes completely. I am unable to use "ctrl + r". I have to kill the program via the Windows Task Manager. (The form works better in Web Modeler, but also has issues there).

I am using the new expression component.

Form, attached as JSON:
[cluster-size-calculator.json](https://github.com/camunda/camunda-modeler/files/14948212/cluster-size-calculator.json)

### Steps to reproduce

1. Open the attached form
2. Use form preview functionality
3. Program crashes

### Expected behavior

I should be able to use the form preview to fill out the form.

### Environment

- OS: [Windows 10]
- Camunda Modeler Version: [5.22.0]
- Execution Platform: [Camunda 8]
- Installed plug-ins: [none]

### Additional context

Might have to do with the "compute on: value change" functionality causing an infinite loop? Difficult to say.

-----

Depends on https://github.com/bpmn-io/form-js/issues/1151

**Comment by nikku** [comment]
Thanks. Forwarded to @camunda/hto-frontend.

**Comment by nikku** [comment]
@Skaiir indicated this is fixed via https://github.com/bpmn-io/form-js/pull/1154 and released with https://github.com/bpmn-io/form-js/blob/develop/packages/form-js/CHANGELOG.md#184.

**Comment by nikku** [comment]
Will be fixed via https://github.com/camunda/camunda-modeler/pull/4251.
