### ISSUE TITLE
As a user I'm able to use the new context pad / improved canvas

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4263]
### Problem you would like to solve

I want to be able to use the [improved canvas](https://github.com/camunda/improved-canvas) that ships with Camunda 8 Web Modeler: As I'm getting used to the new modeling interactions I want to use the same as I work in the Desktop Modeler.

### Proposed solution

* [x] I'm able to enable the improved canvas using a feature flag (https://github.com/camunda/camunda-modeler/pull/4321)
* [x] Flag is documented so folks can enable it (https://github.com/camunda/camunda-docs/pull/3870)

### Alternatives considered

* I'm able to configure it through a [settings page](https://github.com/camunda/camunda-modeler/issues/2913)
* We're rolling it out at the core and remove the existing context pad completely.

**Comment by philippfromme** [comment]
I will pick this up.

**Comment by nikku** [comment]
Missing: Document flag so we can wrap this topic up.

**Comment by nikku** [comment]
Closing as we have all building blocks in place for the v5.24 release. Thanks for your work on this topic :star:
