### ISSUE TITLE
Properties Panel: General: Id field vs "Key"

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#427]
In Camunda the process is referenced by the Key which maps to the `Id` field in the modeler's Property Panel > General page.

Should this more more like `Id (key)` ?

**Comment by nikku** [comment]
We could add a note to the field to make that clear.

**Comment by philippfromme** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-properties-panel/commit/86b4726f48e063583e12450e502fd2a2be105861.
