### ISSUE TITLE
Be able to display multiple decision tables without DRDs

### ISSUE THREAD

**Issue by ricardomatias** [camunda/camunda-modeler#428]
__Tasks__

* [ ] Be able to edit decision tables if diagram contains no DRD and more than one table (default import, i.e. from Signavio)
* [ ] Be able to create DRD from multiple decision tables

---

Related: [SUPPORT-2877](https://app.camunda.com/jira/browse/SUPPORT-2877)

**Comment by mschoe** [comment]
mentioned in [SUPPORT-2877](https://app.camunda.com/jira/browse/SUPPORT-2877)

**Comment by nikku** [comment]
This is entirely possible in the latest version of the Modeler, as all views inside the diagram are accessible via sheet tabs: 

![image](https://user-images.githubusercontent.com/58601/53884054-f2e60900-401a-11e9-8f35-64c960ad6b61.png)

Example diagram file: [no-diagram.dmn](https://github.com/camunda/camunda-modeler/files/2936402/no-diagram.dmn.txt)
