### ISSUE TITLE
5.23  - segmentation fault (core dumped) on Ubuntu 23.10

### ISSUE THREAD

**Issue by jomu78** [camunda/camunda-modeler#4299]
### Describe the bug

In cannot start Modeler 5.23 due to segmentation fault. 

### Steps to reproduce

1. ./camunda-modeler
2. segmenation fault

### Expected behavior

Camunda modeler starts

### Environment

- OS: Ubuntu 23.10
- Camunda Modeler Version: 5.23
- Execution Platform: Camuda 7
- Installed plug-ins: all disabled

INFO app:main:bootstrap starting Camunda Modeler v5.23.0
INFO app:cli parsing [ '/home/user/app/camunda-modeler-5.23.0-linux-x64/camunda-modeler' ] in '/home/user/app/camunda-modeler-5.23.0-linux-x64'
INFO app:flags searching for flags.json in paths [
  '/home/user/app/camunda-modeler-5.23.0-linux-x64/resources',
  '/home/user/.config/camunda-modeler/resources'
]
INFO app:flags found []
INFO app:flags active {}
INFO app:error-tracking Sentry initialized.
INFO app:plugins searching for plugins/*/index.js in paths [
  '/home/user/app/camunda-modeler-5.23.0-linux-x64',
  '/home/user/app/camunda-modeler-5.23.0-linux-x64/resources',
  '/home/user/.config/camunda-modeler/resources',
  '/home/user/.config/camunda-modeler'
]
INFO app:plugins found plug-in entries []
INFO app:plugins registered []
INFO app:main:bootstrap received ready
Segmentation fault (core dumped)

### Additional context

ldd camunda-modeler 
        linux-vdso.so.1 (0x00007fff8b7b8000)
        libffmpeg.so => /home/jmueh/app/camunda-modeler-5.23.0-linux-x64/./libffmpeg.so (0x00007e9ddcc00000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007e9de7f2d000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007e9de7f28000)
        libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007e9ddd379000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007e9ddcab9000)
        libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007e9ddc8e3000)
        libnss3.so => /lib/x86_64-linux-gnu/libnss3.so (0x00007e9ddc7b1000)
        libnssutil3.so => /lib/x86_64-linux-gnu/libnssutil3.so (0x00007e9ddd348000)
        libsmime3.so => /lib/x86_64-linux-gnu/libsmime3.so (0x00007e9ddc789000)
        libnspr4.so => /lib/x86_64-linux-gnu/libnspr4.so (0x00007e9ddc749000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007e9ddc6fa000)
        libatk-1.0.so.0 => /lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007e9ddc6d1000)
        libatk-bridge-2.0.so.0 => /lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x00007e9ddc695000)
        libcups.so.2 => /lib/x86_64-linux-gnu/libcups.so.2 (0x00007e9ddc5f6000)
        libdrm.so.2 => /lib/x86_64-linux-gnu/libdrm.so.2 (0x00007e9ddd331000)
        libgtk-3.so.0 => /lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007e9ddbe00000)
        libpango-1.0.so.0 => /lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007e9ddbd95000)
        libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x00007e9ddbc4e000)
        libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007e9ddbb10000)
        libXcomposite.so.1 => /lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007e9de7f1d000)
        libXdamage.so.1 => /lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007e9de7f18000)
        libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007e9ddc5e1000)
        libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007e9ddd329000)
        libXrandr.so.2 => /lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007e9ddc5d4000)
        libgbm.so.1 => /lib/x86_64-linux-gnu/libgbm.so.1 (0x00007e9ddbaff000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007e9ddbad4000)
        libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007e9ddbaaa000)
        libxkbcommon.so.0 => /lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007e9ddba64000)
        libasound.so.2 => /lib/x86_64-linux-gnu/libasound.so.2 (0x00007e9ddb95e000)
        libatspi.so.0 => /lib/x86_64-linux-gnu/libatspi.so.0 (0x00007e9ddb926000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007e9ddb83b000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007e9ddb817000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007e9ddb600000)
        /lib64/ld-linux-x86-64.so.2 (0x00007e9de7f34000)
        libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007e9ddb5f5000)
        libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007e9ddb55a000)
        libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007e9ddb810000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007e9ddb53b000)
        libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007e9ddb4ef000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007e9ddb4c2000)
        libplc4.so => /lib/x86_64-linux-gnu/libplc4.so (0x00007e9ddb4bb000)
        libplds4.so => /lib/x86_64-linux-gnu/libplds4.so (0x00007e9ddb4b6000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007e9ddb3e0000)
        libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007e9ddb38c000)
        libavahi-common.so.3 => /lib/x86_64-linux-gnu/libavahi-common.so.3 (0x00007e9ddb37e000)
        libavahi-client.so.3 => /lib/x86_64-linux-gnu/libavahi-client.so.3 (0x00007e9ddb36b000)
        libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007e9ddb175000)
        libgdk-3.so.0 => /lib/x86_64-linux-gnu/libgdk-3.so.0 (0x00007e9ddb077000)
        libpangocairo-1.0.so.0 => /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007e9ddb066000)
        libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007e9ddaf5f000)
        libpangoft2-1.0.so.0 => /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007e9ddaf46000)
        libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007e9ddaef8000)
        libfribidi.so.0 => /lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007e9ddaeda000)
        libcairo-gobject.so.2 => /lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x00007e9ddaecd000)
        libgdk_pixbuf-2.0.so.0 => /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007e9ddae9e000)
        libepoxy.so.0 => /lib/x86_64-linux-gnu/libepoxy.so.0 (0x00007e9ddad69000)
        libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x00007e9ddad55000)
        libthai.so.0 => /lib/x86_64-linux-gnu/libthai.so.0 (0x00007e9ddad4a000)
        libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007e9ddad10000)
        libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007e9ddac44000)
        libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007e9ddac37000)
        libxcb-render.so.0 => /lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007e9ddac29000)
        libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007e9ddac24000)
        libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007e9ddab78000)
        libwayland-server.so.0 => /lib/x86_64-linux-gnu/libwayland-server.so.0 (0x00007e9ddab60000)
        libxcb-randr.so.0 => /lib/x86_64-linux-gnu/libxcb-randr.so.0 (0x00007e9ddab4e000)
        libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007e9ddab48000)
        libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007e9ddab40000)
        libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007e9ddab03000)
        libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007e9ddaaf7000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007e9dda9af000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007e9dda97d000)
        libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007e9dda8c6000)
        liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007e9dda8a3000)
        libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007e9dda7d8000)
        libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007e9dda7ac000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007e9dda7a6000)
        libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007e9dda799000)
        libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007e9dda5fb000)
        libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007e9dda5af000)
        libunistring.so.2 => /lib/x86_64-linux-gnu/libunistring.so.2 (0x00007e9dda3f9000)
        libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007e9dda3e2000)
        libnettle.so.8 => /lib/x86_64-linux-gnu/libnettle.so.8 (0x00007e9dda38d000)
        libhogweed.so.6 => /lib/x86_64-linux-gnu/libhogweed.so.6 (0x00007e9dda344000)
        libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007e9dda2bf000)
        libwayland-client.so.0 => /lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007e9dda2ae000)
        libwayland-cursor.so.0 => /lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007e9dda2a2000)
        libwayland-egl.so.1 => /lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007e9dda29d000)
        libXcursor.so.1 => /lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007e9dda291000)
        libXinerama.so.1 => /lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007e9dda28c000)
        libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007e9dda265000)
        libjpeg.so.8 => /lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007e9dda1e0000)
        libdatrie.so.1 => /lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007e9dda1d7000)
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007e9dda1c4000)
        libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007e9dda1b7000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007e9dda1a2000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007e9dda17a000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007e9dda173000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007e9dda161000)
        libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007e9dda13e000)
        libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x00007e9dda12f000)

**Comment by nikku** [comment]
Thanks for your report. We actively support [LTS versions](https://www.releases.ubuntu.com/) of Ubuntu. Do you experience a similar issue on Ubuntu 24 (LTS)?

**Comment by jomu78** [comment]
v5.22 works on 23.10
v5.23 on 24.04 I need to test at home

**Comment by nikku** [comment]
Likely due to the [`electron@30` bump](https://github.com/camunda/camunda-modeler/pull/4246).

**Comment by nikku** [comment]
Expect a nightly build soon that updates the basis from `electron@v30.0.0` to `electron@v30.0.6`. Maybe that fixes your issue ([ref](https://github.com/electron/electron/issues/41839#issuecomment-2112445919)).

**Comment by jomu78** [comment]
I can confirm it is the maximize bug. I stopped camunda-modeler 5.22 in windowed mode and could started 5.23 in exact this window position. When maximizing the window, the modeler crashed.

**Comment by nikku** [comment]
Will be fixed in next nightly as well as the upcoming Camunda Modeler v5.24 release.
