### ISSUE TITLE
Labels of attached boundary events don't stick to the event

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#431]
When moving things around, the labels of attached boundary events get lost.

![okt -19-2016 14-46-34](https://cloud.githubusercontent.com/assets/17595149/19519150/eb4cbb24-960a-11e6-94ae-964c3443c58f.gif)

**Comment by pedesen** [comment]
see https://app.camunda.com/jira/browse/SUPPORT-3423

**Comment by philippfromme** [comment]
Closed via https://github.com/bpmn-io/diagram-js/commit/286151c9adbcca528442e3105558fc599d754cbd
