### ISSUE TITLE
"ID must not be empty" is not displayed in DMN editor

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4319]
### Describe the bug

In 5.20.0, the Modeler stopped to display the ID validation error in the DMN editor:

<img width="1840" alt="image" src="https://github.com/camunda/camunda-modeler/assets/28307541/912bc86b-6f2c-437c-9c06-26bfdc9fcc7f">

Compare that to 5.19.0:

<img width="1840" alt="image" src="https://github.com/camunda/camunda-modeler/assets/28307541/baee19dc-9148-4611-bff5-47b7d5cabb7d">

### Steps to reproduce

1. Open DMN editor
2. Erase the ID
3. now this happens

### Expected behavior

The error is still displayed.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.20.0 and later
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

----

Depends on https://github.com/bpmn-io/dmn-js-properties-panel/issues/85

**Comment by nikku** [comment]
Linked to upstream bug report - https://github.com/bpmn-io/dmn-js-properties-panel/issues/85.
