### ISSUE TITLE
Cannot place existing element onto a sequence flow

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#432]
This used to work, seems to be  a regression bug.

![okt -19-2016 15-03-16](https://cloud.githubusercontent.com/assets/17595149/19519662/34f923fa-960d-11e6-92eb-15db89b53a64.gif)

**Comment by nikku** [comment]
We did never implement this, sorry. Good feature request though :wink:.

**Comment by benhoffmann** [comment]
Great work guys!
