### ISSUE TITLE
Add /operate base path in Operate urls

### ISSUE THREAD

**Issue by houssain-barouni** [camunda/camunda-modeler#4329]
### Problem you would like to solve

In scope of C8 single application creation (part of C8 streamlining project). we need to add  /operate base path in Operate webapp urls: **only webapp UI urls , API urls will remain the same.
This is only applicable to 8.6 of higher versions
Target release: 8.6.0-alpha3**

### Proposed solution

We need to append `/operate` to the [clusterUrl](https://github.com/camunda/camunda-modeler/blob/1f25945b0245795e692cad31fb3f6f65fe23b60b/client/src/plugins/zeebe-plugin/shared/util.js#L16-L25), when the selected C8 version is 8.6 or higher

### Alternatives considered

N/A

### Additional context

Tasklist issue where `/tasklist` and `/operate` are added to the webapps urls: https://github.com/camunda/camunda/issues/18535
Console issue: https://github.com/camunda-cloud/camunda-cloud-management-apps/issues/2917

---

[SUPPORT-24858](https://jira.camunda.com/browse/SUPPORT-24858)

**Comment by nikku** [comment]
@houssain-barouni Do we have to do this for all links to Operate, and why? This breaks any application that links to operate in C8 (SaaS).

**Comment by houssain-barouni** [comment]
> @houssain-barouni Would auto-discovery of the operate URL be applicable in the single application context? Cf. [#4261 (comment)](https://github.com/camunda/camunda-modeler/issues/4261#issuecomment-2107116465).
> 
> If so, let's build discovery of the operate application URLs off a solid infrastructure; we do not want to guess in our modeler(s) where to find the webapp URL.
Hi @nikku ,
if you hit Operate root url, you will be redirected to `{{operateRootUrl}}/operate` , would it make sense to use this redirection? Please note that if your use other urls like `{{operateRootUrl}}/processes,` there will be no redirection

**Comment by houssain-barouni** [comment]
> > We need to append /operate to the [clusterUrl](https://github.com/camunda/camunda-modeler/blob/1f25945b0245795e692cad31fb3f6f65fe23b60b/client/src/plugins/zeebe-plugin/shared/util.js#L16-L25), when the selected C8 version is 8.6 or higher
> 
> @houssain-barouni Do we have to do this for all links to Operate, and why? This breaks any application that links to operate in C8 (SaaS).

@nikku yes Operate and tasklist Webapp URLs will be changed, but not the API urls
this is needed because we are aiming to have a single application that can serve both Tasklist and Operate. So we need a selector between both UIs. We did not want to have different behaviours between single application and standalone Tasklist/Operate

The link updates in SaaS should be covered by https://github.com/camunda-cloud/camunda-cloud-management-apps/issues/2917

**Comment by nikku** [comment]
> Please note that if your use other urls like `{{operateRootUrl}}/processes`, there will be no redirection

This is why I'm wondering if this change is needed (for SaaS), breaking all deep links from existing applications.

---

Could you answer this?

> @houssain-barouni Would auto-discovery of the operate URL be applicable in the single application context? Cf. https://github.com/camunda/camunda-modeler/issues/4261#issuecomment-2107116465.

**Comment by houssain-barouni** [comment]
> Could you answer this?
> 
> > @houssain-barouni Would auto-discovery of the operate URL be applicable in the single application context? Cf. [#4261 (comment)](https://github.com/camunda/camunda-modeler/issues/4261#issuecomment-2107116465).

Would the `.well-known` be served by the cluster endpoint (zeebe endpoint) ? @nikku

**Comment by nikku** [comment]
`.well-known` will be served from the root of the REST API (or whatever API) which is being used:

* I query `http://FOO_BAR_HOST/some-url/a/b/c`
* I search for a related service `XYZ` 
* To find it I query a standardized URI under the root of the host name, i.e. `http://FOO_BAR_HOST/.wellknown/XZY`
* The resulting file, if it exists, tells me where to find the other service (`XZY`)
* I found the other service, and now can use it, wherever it is

In Desktop Modeler we use this pattern to resolve the same issue in C7 context (different place for web apps, auto-discovered from REST endpoint URL).

**Comment by nikku** [comment]
@houssain-barouni I assume given the recent slight change in direction this is not an immediate priority anymore? We're happy to support by building `.well-known` - based discovery of the webapps into the modeler so users can use links wherever operate is.

**Comment by houssain-barouni** [comment]
@nikku our main focus in alpha3 was to have Tasklist in the C8 single application. So, we have implemented the redirection of routes as temporary workaround.
I will talk to @romansmirnov to check how can we proceed with this auto-discovery service implementation

**Comment by barmac** [comment]
I am moving this to `backlog` until any further updates are shared.

**Comment by barmac** [comment]
This issue is related to https://jira.camunda.com/browse/SUPPORT-24858

**Comment by barmac** [comment]
Closing as `wontfix` since there's no need to change the routes on our side due to https://github.com/camunda/camunda-modeler/pull/4742.
