### ISSUE TITLE
Use persistent search in XML tab

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#434]
Instead of auto-closing the search bar on ENTER we should use CodeMirrors persistent search:

https://github.com/codemirror/CodeMirror/commit/404e30823680c94203794a78aa0f91d31a9cdb41

That allows us to ENTER / SHIFT ENTER through the search results.

---

See also [SUPPORT-2939](https://app.camunda.com/jira/browse/SUPPORT-2939)

**Comment by mburke84** [comment]
Related to [SUPPORT-2939](https://app.camunda.com/jira/browse/SUPPORT-2939)
