### ISSUE TITLE
Literal expression editor body has small hitbox

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#4342]
### Describe the bug

In an empty literal expression editor, I need to select the first line to get keyboard focus

![Recording 2024-06-06 at 10 38 04](https://github.com/camunda/camunda-modeler/assets/21984219/48bef520-a372-43b1-900f-2c0cd8b01d3e)

### Steps to reproduce

1. Open a literal expression editor
2. Click around in the function body
3. If you do not hit the first line, Keyboard focus is lost/not achieved

### Expected behavior

I can click anywhere and the cursor gets positioned at the end of the file

### Environment

 * Version: 5.24.0-rc.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: DMN - Camunda 8

### Additional context

The cursor also suggests that I can click anywhere to edit

[SUPPORT-23549](https://jira.camunda.com/browse/SUPPORT-23549)

**Comment by barmac** [comment]
This has been reported as SUPPORT-23549 as well. I moved it to `ready` to discuss in the upcoming iteration planning.

**Comment by barmac** [comment]
Since this is not urgent, it does not need to land in the closest release.

**Comment by jarekdanielak** [comment]
Fixed upstream in https://github.com/bpmn-io/feel-editor/pull/61

**Comment by barmac** [comment]
I created https://github.com/camunda/camunda-modeler/issues/4545 as a follow-up.
