### ISSUE TITLE
Improve documentation for enabling/disabling feature flags

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#4350]
### Describe the bug

Currently while I try to enable the feature flag for a particular feature in the Desktop Modeler there is no sufficient documentation to enable them in Mac OS.

### Steps to reproduce

1. open the documentation to configure feature flags https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/flags/#configuring-flags
2. Try to configure a feature flag in Mac OS.
3. We could see that the documentation lacks the following :

1. The way to reach the {USER_DATA}] or {APP_DATA_DIRECTORY} directory in Mac OS where the .json file could be added
2. Missing step to create a `feature flag` folder
3. Missing mention about restarting the app->,Once the .json file is added to the feature flag folder the app needs to be restarted completely for the changes to be effective

### Expected behavior

All the above missing info should be documented therefore the users are finding it easy configure feature flags from Mac OS

* [ ] As a user I have a [MacOS example](https://docs.camunda.io/docs/components/modeler/desktop-modeler/search-paths/#example-windows-1) showing me where to store the flags file
* [ ] As a user I can learn about app restart being required to [activate flags](https://docs.camunda.io/docs/components/modeler/desktop-modeler/flags/)
 
### Environment

- OS: [e.g. MacOS 10.2]
- Camunda Modeler Version: [e.g. 5.24.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]

**Comment by nikku** [comment]
Let's pick this up as a follow-up action (post release).

**Comment by nikku** [comment]
Will be addressed via two PRs:

* https://github.com/camunda/camunda-docs/pull/3899
* https://github.com/camunda/camunda-docs/pull/3900

**Comment by nikku** [comment]
Closing with [both documentation PRs](https://github.com/camunda/camunda-modeler/issues/4350#issuecomment-2154299929) being merged.
