### ISSUE TITLE
Changing a message start event to a connector leaves some leftovers in the XML

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#4357]
### Describe the bug

On trying to change a message start event to a web hook start event the change is not completely applied as we still see some leftovers of the message start event in the XML of the diagram 

This issue was identified while testing the PR :https://github.com/camunda/web-modeler/pull/9604  and the behaviour is mentioned via this slack thread - https://camunda.slack.com/archives/C032H77434N/p1717750296775919

### Steps to reproduce

1. Create a BPMN diagram with a message start event
2. Now change this message start event -> web hook connector 
3. We could see that in the XML there is still some mentioning about the `message definition ` even though the start event type is now changed to a connector.

https://github.com/camunda/camunda-modeler/assets/85225325/629a4d59-2597-4e0d-ad4e-580aee4a6bad

### Expected behavior

On changing the start event type to a connector the change should be applied both to the diagram and the XML

### Environment

- OS: [e.g. MacOS 10.2,]

**Comment by nikku** [comment]
Moving to `ready`. Having basic interactions blow up the editor must be investigated.

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js-element-templates/pull/111.
