### ISSUE TITLE
Not possible to define the default flow for an InclusiveGateway 

### ISSUE THREAD

**Issue by sixtyeight** [camunda/camunda-modeler#437]
I don't find any field where I could specify the default flow of an InclusiveGateway. It appears that the Modeler does interpret the default flow setting left in the BPMN file from the old Eclipse based Modeler correctly. As you can see the default flow is still annotated.

![camunda_modeler_default_flow](https://cloud.githubusercontent.com/assets/2145723/19935186/6fca353e-a119-11e6-8f58-3ec129c4febb.png)

The other tabs (Listeners, Input / Output and Extensions) of the Gateway are not used and don't have any entries in them. I tried this with the latest version of the modeler (1.4.0).

**Comment by ingorichtsmeier** [comment]
You change the setting with the wrench of the sequence flow.

**Comment by sixtyeight** [comment]
well, that was easy :-)
