### ISSUE TITLE
Add accessible names to the XML/JSON editors

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4370]
### What should we do?

Add accessible names to the XML/JSON editors

### Why should we do it?

Child of https://github.com/bpmn-io/internal-docs/issues/909

**Comment by barmac** [comment]
An additional error is reported in the editors:

![image](https://github.com/camunda/camunda-modeler/assets/28307541/6c3f4240-995b-4a2b-bd2e-853e976704dd)

It is present on the codemirror website as well: https://codemirror.net/

**Comment by nikku** [comment]
> https://github.com/camunda/camunda-modeler/issues/4370#issuecomment-2176268728

This is a false-positive; code mirror editor is absolutely focusable via keyboard.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/4379.
