### ISSUE TITLE
Active tab switches when closing inactive tab

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda-modeler#438]
![modeler-tabs](https://cloud.githubusercontent.com/assets/2543743/19962199/e05f398c-a1b6-11e6-92cd-6a261fc3ed7f.gif)

Steps to reproduce:
1. open three tabs and save them
2. select the rightmost tab
3. click on the x button of the middle tab to close it

Problem:
- the leftmost tab becomes active

Expected Behavior:
- the rightmost tab stays active

Hint:
Problem: If you click on the x button of an inactive tab, it gets selected first and gets closed just after it.

---
See [SUPPORT-2794](https://app.camunda.com/jira/browse/SUPPORT-2794)

**Comment by nikku** [comment]
I [added a few thoughts](https://github.com/camunda/camunda-modeler/commit/e3d0c48308f92de8162c20be7481a098be70d094#comments) to the fix.
