### ISSUE TITLE
C7 properties panel breaks when template variable assignment is disabled

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4382]
### Describe the bug

C7 properties panel freezes when template variable assignment is disabled. The error thrown is related to the inputOutput missing unexpectedly, or outputParameter missing unexpectedly if there are more outputs on the element.

### Steps to reproduce

1. Apply the template below:

```json
[
  {
    "name": "output-test",
    "id": "output-test",
    "appliesTo": [
      "bpmn:Task"
    ],
    "properties": [
      {
        "label": "output",
        "description": "disable assignment to reproduce",
        "binding": {
          "type": "camunda:outputParameter",
          "source": "name"
        }
      }
    ]
  }
]
```

2. Switch toggle for variable assignment
3. Properties panel freezes, and it does not update with element selection

### Expected behavior

No crash.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.24.0 **but not** 5.23.0
- Execution Platform: C7
- Installed plug-ins: [...]

### Additional context

This is a regression.

[SUPPORT-22412](https://jira.camunda.com/browse/SUPPORT-22412)

**Comment by barmac** [comment]
This is first broken in https://github.com/bpmn-io/bpmn-js-element-templates/commit/86a3c0361dac623554125fc1d27afda0ccf501f3

**Comment by barmac** [comment]
The direct cause of the problem is an unhandled error in the rendering when we try to get `camunda:name` of a non-existing output parameter. Somehow after the parameter is removed, we still try to render [this component](https://github.com/bpmn-io/bpmn-js-element-templates/blob/main/src/element-templates/properties-panel/properties/OutputProperties.js#L140), although it should not be rendered according to this `if`: https://github.com/bpmn-io/bpmn-js-element-templates/blob/main/src/element-templates/properties-panel/properties/OutputProperties.js#L67
So this is a race condition. Correct flow is: toggle switch -> remove parameter -> render without `AssignToProcessVariable`; the actual flow is: toggle switch -> remove parameter -> _rerender `AssignToProcessVariable`_ -> 💣

**Comment by barmac** [comment]
I've just confirmed that the bug appears when https://github.com/camunda/camunda-modeler/issues/4382#issuecomment-2178314298 is included.

**Comment by barmac** [comment]
I've just confirmed that the bug appears when https://github.com/camunda/camunda-modeler/issues/4382#issuecomment-2178314298 is included.

**Comment by barmac** [comment]
My current hypothesis is that the incorrect rerender is due to naive `key` implementation which is based on the index of the object.

**Comment by barmac** [comment]
> My current hypothesis is that the incorrect rerender is due to naive `key` implementation which is based on the index of the object.

Setting random keys doesn't help.

**Comment by barmac** [comment]
Today's findings from a session with @nikku :

```
ListGroup.js

  // we need to pass the proper (initial) open state when we 
  // initially render an element
  // 
  // at the same time, we compute the state _only_ in the second PASS
  // 
  // ==> So essentially, by design, we render _once_ with the old state.
  // ==> BOOM (!)
```

**Comment by nikku** [comment]
I have a bug fix in place that removes the aweful hacks we add in `ListGroup`:

![image](https://github.com/camunda/camunda-modeler/assets/58601/9d966f75-6466-45b0-bb4a-7c2613fba014)

To be integration tested (manually) tomorrow.

**Comment by nikku** [comment]
Turned out, as reported, to be a `ListGroup` related issue (old components used for re-rendering against new model).

Fixed upstream via https://github.com/bpmn-io/properties-panel/pull/369.

**Comment by marstamm** [comment]
Closed through https://github.com/camunda/camunda-modeler/pull/4392
