### ISSUE TITLE
Support `bindingType` for called processes/decisions/forms

### ISSUE THREAD

**Issue by jfriedenstab** [camunda/camunda-modeler#4385]
### Problem you would like to solve

As a Camunda 8 user, when I design a BPMN process, I'd like to be able to choose between the binding types `latest` and `deployment` for called processes, called decisions and linked forms. I would also like to understand the differences between them so I can pick the right one for my use case.

### Proposed solution

- [x] Add a new dropdown "Binding" with the options `latest` and `deployment` to the properties panel:
  - [x] to the "Called element" section for a call activity
  - [x] to the "Called decision" section for a business rule task (below "Decision ID")
  - [x] to the "Form" section for a user task; the dropdown must only be displayed in the following cases (for the other ones, the binding type is not applicable):
    - implementation type: `Zeebe user task` + form type: `Camunda Form`
    - implementation type: `Job Worker` + form type: `Camunda Form (linked)`
- [x] Add a tooltip for the dropdown which explains the different options.
  - see suggested design and wording in: https://github.com/camunda/product-design/issues/1811
- [x] We validate the binding type using our usual infrastructure (https://github.com/camunda/camunda-modeler/issues/4386)

#### Implementation Notes

- The binding type should be stored in the new attribute `bindingType` in the diagram's XML:
  ```xml
  <zeebe:calledElement processId="test-process" bindingType="deployment" ... />
  <zeebe:calledDecision decisionId="test-decision" bindingType="deployment" ... />
  <zeebe:formDefinition formId="test-form" bindingType="deployment" ... />
  ```
- If the attribute is not set, select `latest` as the default option.

### Alternatives considered

None.

### Additional context
- product hub epic: https://github.com/camunda/product-hub/issues/1920
- implementation epic: https://github.com/camunda/camunda/issues/19384
- relates to https://github.com/camunda/camunda-modeler/issues/4386

**Comment by nikku** [comment]
Thanks @jfriedenstab. Tagged for 8.6. 

Following our normal procedures we'll work on this once the respective feature is merged in Zebee.

**Comment by nikku** [comment]
This is scheduled on the run-time side of things for `8.6-alpha4`. Let's see if we can support it in the modelers at the same time.

**Comment by philippfromme** [comment]
Question: If the `bindingType` attribute is missing, is `latest` assumed?

**Comment by jfriedenstab** [comment]
@philippfromme Yes, exactly.

**Comment by philippfromme** [comment]
> @philippfromme Yes, exactly.

Sorry, found it in the [original issue](https://github.com/camunda/product-hub/issues/1920#issuecomment-2168146584). 😅

**Comment by barmac** [comment]
This is _fixed upstream_.
