### ISSUE TITLE
Validate `bindingType` property (supported in Camunda 8.6+)

### ISSUE THREAD

**Issue by jfriedenstab** [camunda/camunda-modeler#4386]
### Problem you would like to solve

The new binding type `deployment` will only be supported by Zeebe 8.6 or newer. Users should be warned if they're using the new binding type in their BPMN process, but have selected a lower execution platform version.

### Proposed solution

Add a new linting rule that warns the user if the binding type selected for a called process, called decision or linked form is not yet supported by the current execution platform version, for example:
`A <Call Activity> with <Binding: Deployment> is only supported by Camunda 8.6 or newer`

### Alternatives considered

none

### Additional context

- part of https://github.com/camunda/product-hub/issues/1920
- relates to #4385

**Comment by barmac** [comment]
I see that this is not implemented yet, so it's not coming as part of 8.6-alpha.4. I think it's quite unfortunate that the users can already use the new property, but are left in the dark about the support of the feature.

**Comment by barmac** [comment]
I'm moving this to _ready_.

**Comment by barmac** [comment]
Assigning @philippfromme as the assignee of https://github.com/camunda/camunda-modeler/issues/4385

**Comment by jfriedenstab** [comment]
Thanks, @barmac! Is there any chance that this could be implemented in the next days, @philippfromme? Then we could still try to include it in the release.

**Comment by philippfromme** [comment]
@jfriedenstab I'm on it!

**Comment by jfriedenstab** [comment]
Great, thank you! 🙂

**Comment by philippfromme** [comment]
> In that case, we may also include it in #4439

Yes, I'd like that.

**Comment by barmac** [comment]
I've updated the milestone since this is shipped with the current release.
