### ISSUE TITLE
Edit input/output button flashes when adding new column 

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#4388]
### Describe the bug

When I edit a Decision table and add another coloumn, the edit button flashes briefly. This is unexpected as I can not click on it

Related to https://github.com/bpmn-io/dmn-js/issues/845

![Recording 2024-06-20 at 10 49 06](https://github.com/camunda/camunda-modeler/assets/21984219/66186d83-b5d9-4f5b-9e73-329b8140401d)

### Steps to reproduce

1. Open a Decision Table
2. Add a column using the mouse
3. The Icon briefly flashes

### Expected behavior

Either
 - The button is shown on hover of the Table header and I can use it to open the edit menu
 - It is not shown at all when interacting with mouse only

### Environment

 * Version: 5.25.0-rc.2
 * Operating System: Linux x86_64 amd64
 * Plugins: <no plugins>
 * Execution Platform: DMN - Camunda 8

**Comment by barmac** [comment]
In the tool, we rely on `:focus-within` selector to display the button. We should use `:focus-visible` instead.

**Comment by barmac** [comment]
`:focus-within` -> a descendant has focus
`:focus-visible` -> browser "thinks" focus should be displayed

**Comment by jarekdanielak** [comment]
Fixed upstream in https://github.com/bpmn-io/dmn-js/pull/890
