### ISSUE TITLE
Correctly handle line feed in DMN element name

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4390]
### What should we do?

![image](https://github.com/camunda/camunda-modeler/assets/58601/bf04f1d8-841a-47d2-80e5-922621357956)

* [ ] https://github.com/bpmn-io/dmn-js/issues/884
* [x] https://github.com/bpmn-io/dmn-js-properties-panel/issues/94

### Why should we do it?

Ensure good UX.

Reported via https://camunda.slack.com/archives/C0693F1NFK5/p1718869256259379

**Comment by nikku** [comment]
[Assigned @jarekdanielak as we ](https://github.com/bpmn-io/dmn-js/issues/884)fixed the biggest issue in this bucket via https://github.com/bpmn-io/dmn-js-properties-panel/pull/95; to consider to close this issue, or handle missing aspects as a follow-up.

If this is "fixed upstream", let's move it into the column .

**Comment by jarekdanielak** [comment]
First part of the issue was fixed upstream by https://github.com/bpmn-io/dmn-js-properties-panel/pull/95.

Second part is more tricky and requires more discussion as described in https://github.com/bpmn-io/dmn-js/issues/884.

Moving this issue back to backlog until the underlaying issue is further discussed.

**Comment by nikku** [comment]
@jarekdanielak I don't see how "overlapping with the icon" should block us from progressing on this issue. Overlapping with the icon is a standard behavior in our tools. You have the means (manual newlines) in place to prevent it.

**Comment by jarekdanielak** [comment]
Closing this one.

https://github.com/bpmn-io/dmn-js/issues/884 has some more discussion about UI behavior is case of overlap.
