### ISSUE TITLE
Make directory for open / save / export relative to selected diagram location

### ISSUE THREAD

**Issue by ricardomatias** [camunda/camunda-modeler#440]
__Use Case__

* Whenever a user saves / opens / exports with an existing diagram open, the folder used in open/save is the diagram location.
* Applies for save/open/export
* Whenever no diagram is open, the last open/save location continues to be used

__Example__

* diagram `/home/ricardo/Desktop/diagram_1.bpmn` is selected
* save / open / export as openes in `/home/ricardo/Desktop/`
* user creates new diagram
* base directory remains `/home/ricardo/Desktop/`
* user saves diagram in `/home/diagrams`
* base directory changed to `/home/diagrams`

---

See [SUPPORT-2802](https://app.camunda.com/jira/browse/SUPPORT-2802)

**Comment by StephenOTT** [comment]
+1

**Comment by nikku** [comment]
Need to understand a bit better how other editors in the wild do this:

* Eclipse
* Netbeans
* Word
* Sublime Text
* Atom Editor

**Comment by StephenOTT** [comment]
@nikku Are you looking for their implementations or rules / "experience" ?

**Comment by nikku** [comment]
Yes.

**Comment by gimbel** [comment]
I think we should look into applications which manage multiple files at once (e.g. in Tabs). Word is not comparable here since any file is started in a new instace of the application.

**Comment by nikku** [comment]
You can still test this with Word when having multiple Documents open. Open `doc1`, open `doc2`, switch back to `doc1`, try save as...

**Comment by ricardomatias** [comment]
Sublime Text, Atom:
- Unsaved file: uses last dialog directory
- Saved file: uses that file's directory for save as/open

Inkscape:
- Unsaved file: uses last dialog directory
- Saved file: uses last dialog directory for open and that file's directory for save as

**under development**
