### ISSUE TITLE
No loop rule significantly reduces the application performance on big diagrams

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4401]
### Describe the bug

The diagram from the support ticket makes the application unresponsive, and this is due to the linting (no-loop rule).

![image](https://github.com/camunda/camunda-modeler/assets/28307541/61ecf430-0491-41e9-8945-c8a42b74d0e5)

### Steps to reproduce

1. Open the diagram from the support ticket
2. now this happens

### Expected behavior

The linting should not slow down the application significantly.

### Environment

- OS: MacOS
- Camunda Modeler Version: 5.23.0, current nightly
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

[SUPPORT-22488](https://jira.camunda.com/browse/SUPPORT-22488)

**Comment by barmac** [comment]
Ideas:
1. Run linter in a worker (difficult because we need to pass the model)
2. Limit the number of elements tested for the no-loop rule

The rule is implemented in https://github.com/camunda/bpmnlint-plugin-camunda-compat/blob/main/rules/camunda-cloud/no-loop.js

**Comment by nikku** [comment]
Let's attempt to solve this in an algorithmic manner first. I suggest anyone picking to check the following (or other) resources:

* Solving using [depth first search](https://www.geeksforgeeks.org/detect-cycle-in-a-graph/)
* Solving using [topological sorting](https://stackoverflow.com/a/53714743)
