### ISSUE TITLE
Indicate that there is a new modeler version available

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4407]
### Problem you would like to solve

As a user I get feedback when I have a freshly (new) installed modeler version (via the what's new communcation). However, I do not get feedback when there is a new version of the modeler available, i.e. I skipped the update check in the past. This allows me to forget about the upgrade.

What I'd like to see is that the modeler nudges me more into upgrading, i.e. by indicating in the what's new area that a new version of the modeler is available.

### Proposed solution

* [ ] What's new indicates via a :red_circle: that a new version is available (you're running on an outdated version!)
* [ ] Clicking the button does not show what's new, but a call to upgrade the modeler

### Alternatives considered

Auto-upgrade, which (as we discussed previously) is not always possible.

### Additional context

Example how an upgrade nudge could look like (visually):

![image](https://github.com/camunda/camunda-modeler/assets/58601/e42f87fa-13a7-4a67-982a-b585761931bd)

Clicking the version opens an update notice:

![image](https://github.com/camunda/camunda-modeler/assets/58601/51bf11e3-ff89-4e5a-8e80-86199d85f44c)

Clicking `Learn what's new` opens the update notice.

**Comment by marstamm** [comment]
We have not assigned this in the current planning. Let's discuss if this is the correct place for this hint and what other options we have

**Comment by philippfromme** [comment]
Leaving this as unassigned for now. We still plan on working on this soon.

**Comment by nikku** [comment]
Related discussion and feedback in [this slack conversation](https://camunda.slack.com/archives/GP70M0J6M/p1720035079714139).

I provide many more details to this topic, and also highlight that users are already used to such nudging from other applications, i.e. in Chrome:

![image](https://github.com/user-attachments/assets/508d299a-fd75-4b35-ae8e-91ac4a29e9ba)

**Comment by lmbateman** [comment]
Latest concepts for review (same idea, different colors):

![image](https://github.com/user-attachments/assets/96c9776e-1592-48cb-b5bd-36d53ad430ba)
![image](https://github.com/user-attachments/assets/8869d6e5-ecd7-4c92-aa82-61583ad4fda0)
![image](https://github.com/user-attachments/assets/e2b042e4-13e9-47ae-ac65-de70bb303bf3)

**Comment by lmbateman** [comment]
HFW: https://www.figma.com/design/GOvJLpnAq4r6m3iKf646eI/Nudge-users-to-upgrade-DTM?node-id=77-11

**Comment by nikku** [comment]
@philippfromme As per todays discussion and @lmbateman's [latest wireframes](https://github.com/camunda/camunda-modeler/issues/4407#issuecomment-2340825405) this is ready to be worked on.

**Comment by nikku** [comment]
@philippfromme I'm unassigning you from this topic, so someone else from the team can pick this up.

**Comment by abdul99ahad** [comment]
Since this issue is slightly older, I'm rewriting the assumed proposed changes. 

- [ ] There should be an [Update](https://github.com/camunda/camunda-modeler/issues/4407#issuecomment-2340825405) button.
- [ ] Clicking the button does not show what's new, but a call to upgrade the modeler.
- [ ] The previous logic of User agreeing to Update checks in privacy preference menu will remain the same.

**Comment by lmbateman** [comment]
> Clicking the button does not show what's new, but a call to upgrade the modeler.

> <img width="468" alt="image" src="https://github.com/user-attachments/assets/be611a23-15af-4085-9c56-81bf48307306">

Would it make sense to add a link to the download page in the modal that appears when you click the Update button? I assume most users will want to check out the changes before upgrading, but there may be some that just want to go ahead and update.

**Comment by lmbateman** [comment]
(Posting here for transparency)

I went into the inspector in the Desktop Modeler and identified some colors that might be feasible:

- --color-yellow-47-88-53: hsl(47, 88%, 53%); (aka #F1C31E)
- --color-orange-20-98-52: hsl(20, 98%, 52%); (aka #fd5d0d)
- --color-blue-205-100-40: hsl(205, 100%, 40%); (aka #0077cc)

I then ran [contrast checks](https://webaim.org/resources/contrastchecker/) against
- the standard text color (--text-base-color: var(--color-grey-225-10-15);, aka #22242a)
- white (#fff)
- the gray footer background (--status-bar-background-color: var(--color-grey-225-10-85) aka #d5d7dd)

Ideally, text should have a contrast ratio of 4.5:1 or greater, and the button/footer contrast should be 3:1 or greater (I'm considering the button to be a graphical element). Here are the results:

- Yellow: ✅ passes with standard text color; ❌ fails with white text; ❌ fails against gray footer
- Orange: ✅ passes with standard text color; ❌ fails with white text; ❌ fails against gray footer
- Blue: ❌ fails with standard text color; ✅ passes with white text; ✅ passes against gray footer

I'm therefore recommending that we go with a blue background and white label for the Update button.
