### ISSUE TITLE
copy & Paste dont copy all original object properties but just name, format and type

### ISSUE THREAD

**Issue by iannsp** [camunda/camunda-modeler#441]
When I try to copy a component of a workflow the resultant copy is not a full copy of the original object:
- just the "name", format and type  properties are copied to the new instance.

I check for the implementation and as expected there is an [assign](https://github.com/camunda/camunda-modeler/blob/master/client/lib/util/copy.js).

**Examples of not copied properties**

- Form Data
- Execution Listener of type `Script`
- ListenerType = JavaClass
- "Type = Text"
- Timer Definition Type
- MessageStartEvent > Details > Message
- SignalStartEvent > Details > Signal

My question is: 
- is this the expected behavior for copy&paste (coping few properties instead of a full copy)? 

_aditional information of the test:_
- browser: Firefox 49.0.2.
- despite all the issues about copy paste, I do not found a discussion about deep copy the workflow objects.

Follow a code we wrote just to support the issue idea. We know it is not for production but hope it happen to be a good place for discussion:

**Comment by ricardomatias** [comment]
Closing since we already have a ticket for this #370.

**Comment by MaxTru** [comment]
@nikku any reason this was reopened?

**Comment by nikku** [comment]
Because @philippfromme re-opened it: 

![image](https://user-images.githubusercontent.com/58601/157686671-fc2a37d5-a572-420e-8609-26894e96fcbb.png)

@philippfromme What is up with this one?

**Comment by philippfromme** [comment]
What the hell?
