### ISSUE TITLE
Name text area doesn't auto resize if General tab isn't open

### ISSUE THREAD

**Issue by jarekdanielak** [camunda/camunda-modeler#4419]
### Describe the bug

If General tab on properties panel isn't already open when selecting an element, the text area for name won't properly resize to fit multiple lines of text.

https://github.com/camunda/camunda-modeler/assets/24656920/4541be1f-9c7f-4a98-b159-ef27de5ab556

### Steps to reproduce

1. Create an element with multiline Name.
2. Close General tab in properties panel.
3. De-select the element.
4. Select the element and open General tab in properties panel.

### Expected behavior

Name text area should always resize to fit multiple lines of text.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

Related to https://github.com/bpmn-io/properties-panel/issues/314

**Comment by nikku** [comment]
@jarekdanielak Is this related to https://github.com/bpmn-io/properties-panel/issues/314? If so, let's link both issues.

**Comment by jarekdanielak** [comment]
Fixed upstream with https://github.com/bpmn-io/properties-panel/pull/372

**Comment by nikku** [comment]
Unfortunately this does not seem to be fully addressed by https://github.com/camunda/camunda-modeler/pull/4429:

![capture SujP1p_optimized](https://github.com/user-attachments/assets/0502d522-d07f-4b97-a72a-25c631b28e8b)
