### ISSUE TITLE
Notify user when deleting or preforming a action that is going to delete element confirmation

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#442]
Very often there is all sorts of configuration of sequence flows and other elements that are not visible without selecting through multiple tabs in the properties panels.  Need some notification/alert / "Are you sure you want to do this?" notice when you are preforming a action that will delete/remove that configuration.

Common Example:
There is config on a Sequence flow's condition type.  Say you are executing a script. It is VERY easy to be moving sequence flows around or modify settings such as "Default Flow", and you delete your script and never realize it was deleted.

**Comment by nikku** [comment]
How should that interaction work? Generally I tend not to sacrifice ease of use for export modelers for a bit of fail-safety for newbees.

**Comment by StephenOTT** [comment]
@nikku a few different implementations come to mind (not in any specific order):

1. a simple yes/no confirmation popup to have the user confirm the move/change which will delete the configuration.

1. On hover, a indicator (colour, symbol, etc) is used to visually indicate that there is configuration on that sequence flow / element.

1. An app preference that is configurable (off by default) that will turn on the confirmation popups for making changes that delete configuration of a sequence flow/element.

Thoughts?

**Comment by nikku** [comment]
We'd rather not implement any kind of blocking interactions, such as `Do you really want to do ...?` alerts.

Instead, if at all, we should make the fact that an element is special regarding implementation details, default flow, ... more visible to the user.

This is already covered by https://github.com/camunda/camunda-modeler/issues/452.
