### ISSUE TITLE
Camunda Play in Web Modeler cannot find call activity that has user task and linked form

### ISSUE THREAD

**Issue by jphillips-bp3** [camunda/camunda-modeler#4425]
### Describe the bug

I have a process that has a call activity. The call activity is linked to a process that itself has a user task with a linked form.

When I start a process instance using the Play function, it fails to call the call activity, claiming it cannot find the process by its BPMN Id.

Play is able to display the form from a user task in the top level process. It is also able to invoke a call activity if that call activity does not have a user task with a linked form.

I suspect that Play is trying to deploy all the resources to its temporary cluster, but is unable to do so for forms that are linked to a process that is then linked from a call activity.

### Steps to reproduce

I have attached the process application that can re-produce the error. If you run the process you should see the following:

1. First you will see that it has called the call activity that does not have the user task successfully:
![image](https://github.com/user-attachments/assets/b2a1fd08-3563-47ae-8ad0-db8a732377b6)

2. Then you should be able to select to show the form:
![image](https://github.com/user-attachments/assets/fb4da8f3-26ac-4ba5-9386-71245db0d28f)

3. When you complete the form, you should then see the following error:
![image](https://github.com/user-attachments/assets/8b3f1cb2-0c29-4150-a3b8-1a8833b5e136)

### Expected behavior

I would expect to be able to display the linked form regardless of where in the call hierarchy the user task is placed.

### Environment

Camunda SaaS:
![image](https://github.com/user-attachments/assets/660c6928-0961-455b-be7a-a8496e3c0008)

Here is the process application to re-produce the error: [Play Form Test.zip](https://github.com/user-attachments/files/16264018/Play.Form.Test.zip)

**Comment by jphillips-bp3** [comment]
Apologies, this has been logged in the wrong project, it for Web Modeler and not the Desktop Modeler.

**Comment by barmac** [comment]
I'll close this as it's not a Desktop Modeler issue, but will forward it to the WM team. Thanks for your feedback.
