### ISSUE TITLE
Integrate DRD modeling

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#443]

**Comment by nikku** [comment]
__Review Nodes__

* [ ] Export to PNG not available for DRD (is available for BPMN and CMMN diagrams)
* [ ] Tab should read `Diagram` instead of `Table` when editing DRD
* [ ] Blank page only allows creating of tables and not DRD diagrams (would personally replace create table with create DRD diagram)
* [ ] When creating a new DRD it is always called `Dish` with ID `dish` Should call it `Decision` with randomly generated ID instead
* [ ] When creating a DMN table, the name / ID combination assigned is always `decision` / `decision`. Would change that to `Decision` / randomly generated ID to avoid collisions, too (especially if users only work with tables on a bigger scale they will quickly run into issues due to decision ID clashes otherwise).

I'd love to see [dmn-js#168](https://github.com/bpmn-io/dmn-js/issues/168) integrate, but that is a cherry on top.

**Comment by ricardomatias** [comment]
The PNG export doesn't work for me, so I disabled it.

**Comment by ricardomatias** [comment]
- Label Editing has conflicts with shortcuts that don't have a modifier
- XML Export is broken due to DMN having 2 editors (modelers)

**Comment by nikku** [comment]
Could you have another look at my review hints, especially the comments I added on https://github.com/camunda/camunda-modeler/compare/443-integrate-drd#diff-85cd966da56f8b501a78b1b121e2be4c? I believe the commandStack magic [you added](https://github.com/camunda/camunda-modeler/compare/443-integrate-drd#diff-48f408fad22d2abc0434f7e4879cde00R149) may be the reason for the remaining test cases failing.
