### ISSUE TITLE
Add color picker with basic colors to modeler toolbar

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#445]
See https://github.com/camunda/camunda-modeler/issues/390

**Comment by vkatushenok** [comment]
@philippfromme Think you missed adding ['setColor'](https://github.com/camunda/camunda-modeler/compare/445-color-picker#diff-9ea22a1b32b417b23e77ccaa782e7c13R241) into EditorActions in bpmn-js.

**Comment by vkatushenok** [comment]
@philippfromme You have added [`disabled`](https://github.com/camunda/camunda-modeler/compare/445-color-picker#diff-cc981476ee9fc1ed25c1875081a21c2dR26) but not really using it (should update based on selection).
