### ISSUE TITLE
Support user task priority in C8

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4450]
### What should we do?

Support adding priority for user tasks in C8:

```xml
<userTask id="" name="">
  <bpmn:extensionElements>
    <zeebe:priorityDefinition priority="15" />
  </bpmn:extensionElements>
</userTask> 
```

* [x] https://github.com/camunda/zeebe-bpmn-moddle/issues/62
* [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/1069
* [x] https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/170
* [x] https://github.com/camunda/linting/issues/113
* [ ] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/1073

### Why should we do it?

Related to https://github.com/camunda/product-hub/issues/217

**Comment by Skaiir** [comment]
Added myself for tracking purposes.

**Comment by nikku** [comment]
Follow-up (left-over) - https://github.com/bpmn-io/bpmn-js-properties-panel/issues/1073.
