### ISSUE TITLE
Cannot Add Annotation to Pool via New Context Pad

### ISSUE THREAD

**Issue by sarahekelley** [camunda/camunda-modeler#4451]
### Describe the bug

I no longer have the ability to add a Text Annotation to a Pool with the "New" context menu. I can add Text Annotations to other elements using the new Append Element Context Menu (Blue Plus Icon). 

This was an action that was previously available with the "Old" context menu. 

### Steps to reproduce

1. Select Pool
2. No options available to add a Text Annotation

<img width="600" src="https://github.com/user-attachments/assets/f64f6dd3-1f9c-47dc-a29e-cfd3f26bab5e">

### Steps from "Old" Context Menu
1. Select Pool
2. Select Append Text Annotation

<img width="600" src="https://github.com/user-attachments/assets/fa21b448-c297-4d29-a0f2-2c20c3794711">

### Expected Steps with "New" Append Element Menu
1. Select Pool
2. Select Append Element Context Menu (Blue Plus)
3. Select Add Text Annotation

<img width="600" alt="2024-08-08_13-40-58" src="https://github.com/user-attachments/assets/c177f591-26d2-48fd-97b8-539fc89ce150">

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

Available Workaround: I can still add a Text Annotation to the Pool if I copy/paste a Text Annotation attached to another element and then connect the Pool to the pasted Text Annotation via the "Connect to other element" action off of the "New" Context Menu.

**Comment by barmac** [comment]
Thank your for your report. This is a known issue https://github.com/camunda/improved-canvas/issues/69, and there's already an upstream PR which should fix this: https://github.com/camunda/improved-canvas/pull/71

**Comment by barmac** [comment]
Assigning @philippfromme as the author of the upstream PR.

**Comment by barmac** [comment]
@philippfromme I assume this is `fixed upstream` since https://github.com/camunda/improved-canvas/issues/69 is closed. Let's make sure the dependency is updated in the Modelers.

**Comment by barmac** [comment]
WIP branch: https://github.com/camunda/camunda-modeler/compare/electron-32-adjustment?expand=1
