### ISSUE TITLE
Add support for setting a version tag for a DMN decision

### ISSUE THREAD

**Issue by jfriedenstab** [camunda/camunda-modeler#4454]
### Problem you would like to solve

As a Camunda 8 user, I'd like to be able to specify a custom version tag for a DMN decision (so that the decision will be available under this version tag when it gets deployed later on and can be referenced from a BPMN business rule task using `versionTag` binding).

### Proposed solution

- [x] A new (optional) input field "Version tag" is added to the "General" section of the properties panel for a decision in a DMN diagram.
- [x] The version tag is stored in the `value` attribute of a `zeebe:versionTag` extension element:
  ```xml
  <decision id="test-decision" name="Test Decision">
      <extensionElements>
          <zeebe:versionTag value="v1.0.0" />
      </extensionElements>
  </decision>
  ```

### Additional context

- part of https://github.com/camunda/camunda/issues/19812
- relates to https://github.com/camunda/camunda-modeler/issues/4453
- relates to https://github.com/camunda/camunda-modeler/issues/4461

**Comment by philippfromme** [comment]
Released as https://www.npmjs.com/package/dmn-js-properties-panel/v/3.5.0 and ready to be integrated into both modelers through https://www.npmjs.com/package/camunda-dmn-js/v/2.8.0.
