### ISSUE TITLE
Simplify enabling of connectors within modeler

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4455]
### What should we do?

Related to https://github.com/camunda/camunda-modeler/issues/4302 we want to ensure that it is simple to enable connectors within the app, i.e. on first time startup. This allows users to get a better out-of-the-box [experience for Camunda + connectors](https://github.com/camunda/product-hub/issues/2253#issuecomment-2277522319).

* [x] We explore introducing a minimal settings page to accomplish this, hence it is related to  https://github.com/camunda/camunda-modeler/issues/2913
  * [x] Not part of first iteration
* [x] We want to load/update connector templates lazily, only when a user opens a Camunda 8 diagram (https://github.com/camunda/camunda-modeler/pull/4474)
* [x] We want connectors to be enabled automatically, and indicate ability to configure via the what's new communication (https://github.com/camunda/camunda-modeler/pull/4474)
* [x] We want to update documentation accordingly (https://github.com/camunda/camunda-docs/pull/4187)

### Why should we do it?

Ensure users have a simpler out-of-the-box experience for [Camunda + connectors](https://github.com/camunda/product-hub/issues/2253#issuecomment-2277522319).

**Comment by crobbins215** [comment]
Discussed on slack, adding info to the ticket. 

Let's enable it by default but with a settings page so it can be disabled if required.

**Comment by nikku** [comment]
Decided in [the kick-off](https://miro.com/app/board/uXjVKo9OY6U=/):

* [ ] We want to load/update connector templates lazily, only when a user opens a Camunda 8 diagram
* [ ] We want connectors to be enabled automatically, and indicate ability to disable them via the what's new communication
* [ ] We want to update documentation accordingly

**Comment by nikku** [comment]
Work in progress PR (iteration 1, missing tests and updated what's new communication) is available via https://github.com/camunda/camunda-modeler/pull/4474.

**Comment by nikku** [comment]
Typical time it takes to update connectors is around 40 (!) seconds:

![image](https://github.com/user-attachments/assets/8113722d-23c0-4dd9-ba6d-853b14f663af)
