### ISSUE TITLE
I can see and edit a conditionExpression without xsi:type

### ISSUE THREAD

**Issue by saig0** [camunda/camunda-modeler#446]
The attribute `xsi:type` is optional for the element `conditionExpression` (parent element is `sequenceFlow`). 

Currently, the modeler ignores a `conditionExpression` if it has no `xsi:type` attribute.

E.g.:

```xml
<bpmn:sequenceFlow id="SequenceFlow_0rcq1rn" sourceRef="ExclusiveGateway_052bk7y" targetRef="Task_0sd1xtp">
    <bpmn:conditionExpression>${foo}</bpmn:conditionExpression>   
</bpmn:sequenceFlow>
```

AT:
* I can see and edit an expression which is defined on `conditionExpression` without `xsi:type` attribute

--- 

Via [SUPPORT-2835](https://app.camunda.com/jira/browse/SUPPORT-2835)

**Comment by nikku** [comment]
This is supported by recent versions of our BPMN modeling toolkit.
