### ISSUE TITLE
Add support for setting a version tag for a Form

### ISSUE THREAD

**Issue by jfriedenstab** [camunda/camunda-modeler#4463]
### Problem you would like to solve

As a Camunda 8 user, I'd like to be able to specify a custom version tag for a Form (so that the Form will be available under this version tag when it gets deployed later on and can be referenced from a BPMN user task using `versionTag` binding).

### Proposed solution

- [ ] A new (optional) input field "Version tag" is added to the "General" section of the properties panel for a Form.
- [ ] The version tag is stored in a new `versionTag` JSON property:
```
{
  "id": "Form_1",
  "type": "default",
  "versionTag": "v1",
  "components": [],
}
```

### Additional context

- part of https://github.com/camunda/camunda/issues/19812
- relates to https://github.com/camunda/camunda-modeler/issues/4462

**Comment by philippfromme** [comment]
Ready to be integrated into both modelers once https://github.com/bpmn-io/form-js/pull/1243 is released.
