### ISSUE TITLE
Missing correlation key for message start event

### ISSUE THREAD

**Issue by bespaltovyj** [camunda/camunda-modeler#4466]
### Describe the bug

The [documentation](https://docs.camunda.io/docs/components/modeler/bpmn/message-events/#message-start-events) says that I can use the correlation key to create processes idempotently, but there is no way to specify it in the modeler

![image](https://github.com/user-attachments/assets/8567d3cd-46fa-4c21-a67e-e5c78c80f936)

![image](https://github.com/user-attachments/assets/188b69e9-d382-4e40-bea1-29c78edb8bed)

As a temp solution i have to specify it directly in xml
![image](https://github.com/user-attachments/assets/1e683abe-c81a-4fb5-8f24-43f77a4fd019)

### Steps to reproduce

1. Create new empty process for camunda 8
2. Create message start event
3. Find "Message" section in right panel
4. Check exists input "Subscription correlation key"

### Expected behavior

If I create a process with message start event "Subscription correlation key" field exists in menu

### Environment

- OS: Windows 11
- Camunda Modeler Version: 5.26.0 and earlier
- Execution Platform: Camunda 8
- Installed plug-ins: -

**Comment by nikku** [comment]
@bespaltovyj This is a miss-understanding. 

The correlation key must be provided as you publish the message. This time you can ensure that the message effect, in case multiple messages with the same key are published, is only happening once.

**Comment by bespaltovyj** [comment]
>The correlation key must be provided as you publish the message

@nikku do you checked the link from the documentation I attached?

![image](https://github.com/user-attachments/assets/12751784-bb64-499e-8b09-985257b28ded)


Message event can be used for create a process instance and correlation key used for idempotence creating

![image](https://github.com/user-attachments/assets/7a3f50fd-acf7-4968-abe2-d508198bd358)

I incorrectly defined the expected behavior?

**Comment by nikku** [comment]
> ### Expected Behavior
> 
> If I create a process with message start event "Subscription correlation key" field exists in menu

I read your message carefully. What you expect is not what you get with Camunda 8 and we'll use your issue as trigger to rework the documentation.

To start a process you _cannot_ provide a correlation key. Rather, the process will be tagged with the correlation key of the message that starts it, and follow-up messages will be checked ("did a message with the same correlation key already start an instance of this process").

**Comment by mesellings** [comment]
@nikku For this page, would editing the text as follows and adding a note provide the required clarity on this issue do you think?

### Message start events

A process can have one or more message start events (besides other types of start events). Each message event must have a unique message name.

When a process is deployed, it creates a message subscription for each message start event. Message subscriptions of the previous version of the process (based on the BPMN process id) are closed.

- When the message subscription is created, a message can be correlated to the start event if the message name matches. 
  - On correlating the message, a new process instance is created and the corresponding message start event is activated.
  - Messages are not correlated if they were published before the process was deployed, or if a new version of the process is deployed without a proper start event.

The `correlationKey` of a published message can be used to control the process instance creation. 
* If an instance of this process is active (independently from its version) and it was triggered by a message with the same `correlationKey`, the message is not correlated and no new instance is created. If the message has a time-to-live (TTL) > 0, it is buffered.

* When the active process instance is completed or terminated, and a message with the same `correlationKey` and matching message name is buffered (i.e. TTL > 0), the message is correlated and a new instance of the latest version of the process is created.

If the `correlationKey` of a message is empty, it creates a new process instance and does not check if an instance is already active.

> Note: You do not provide a `correlationKey` when starting a process. The process is tagged with the `correlationKey` of the message that starts the process. Follow-up messages are then checked against the `correlationKey` (for example, did a message with the same `correlationkey` already start an instance of this process?).

**Comment by nikku** [comment]
> Message subscriptions of the previous version of the process (based on the BPMN process id) are closed.

This could also be a `note` block, that "The latest version of a process define the active subscriptions"; the same applies for conditional start events, timer start events and any other explict (not a non start event) start trigger.

----

I think the change is a good improvement :+1:

**Comment by mesellings** [comment]
@bespaltovyj Would the suggested docs change above help to mitigate this issue do you think, or is there more required do you think?

**Comment by bespaltovyj** [comment]
@mesellings I would add a clarification like this "You do not provide a `correlationKey` **in bpmn schema** when starting a process..."
