### ISSUE TITLE
DropDown Boxes not working on Modeler for MacOS

### ISSUE THREAD

**Issue by andrlange** [camunda/camunda-modeler#4467]
### Describe the bug

Dropboxes are not working creating 7 models

### Steps to reproduce

1. create a new version 7 model
2. try to open any dropbox
3. no dropbox is opening or shows the content. 

### Expected behavior

clicking a dropbox opens the content with the options

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

**Comment by nloding** [comment]
To follow up: the user has reported that this only occurs when the app first starts in fullscreen mode.

>I found something interesting:
If you start the Modeler in fullscreen from beginning drop downs don’t work.
But if you exit fullscreen and enter fullscreen again: All dropdown boxes are working. So this is a workaround, if the app starts in fullscreen just leave fullscreen and renter fullscreen.


Relevant forum link: https://forum.camunda.io/t/creating-model-7-using-modeler-5-26-no-dropdown-showing-on-macos/54308

**Comment by barmac** [comment]
I can reproduce this issue. Thanks for the fullscreen tip @nloding
