### ISSUE TITLE
Lane Label Obscures Text During Editing

### ISSUE THREAD

**Issue by sarahekelley** [camunda/camunda-modeler#4477]
### Describe the bug

When editing a Lane label, the text being typed is obscured by the old label, making it difficult to see what's being entered. The new text only becomes visible after the edit is completed.

### Steps to reproduce

1. Create a diagram with a Pool and at least two Lanes.
2. Label one of the lanes.
3. Double-click to edit the label, select the existing text, and begin typing. 

![camunda-lane-label_bug](https://github.com/user-attachments/assets/09258fc9-3f35-49b5-b5ea-d5d70ebcd45f)

### Expected behavior

The new text should be visible as it's being typed, replacing the old label text in real-time.

![camunda-lane-label_expected-behavior](https://github.com/user-attachments/assets/d7c595ac-060a-4604-907e-891b1876664c)

### Environment

- OS: Windows 11
- Camunda Modeler Version: 5.26
- Installed plug-ins: None

**Comment by nikku** [comment]
Thanks for the report. I can reproduce the issue.

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js/pull/2224.
