### ISSUE TITLE
Alignment of start event off in initial diagram

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4488]
### Describe the bug

As I'm working off the default BPMN diagram template I notice that the alignment of the start event is off. 

If I continue to model, i.e. a sub-process with a contained start event, then I cannot align both events with each other:

![capture DqNlIi_optimized](https://github.com/user-attachments/assets/e4db2a6b-ea07-4469-af5d-97687c9d9d11)

### Steps to reproduce

1. Create a new BPMN file
2. Add a Sub-Process
3. Place a Start Event into the Sub-Process and try to align it with the incoming Sequence Flow

### Expected behavior

* [ ] Start event in sub-process and start event outside are aligned

### Environment

- OS: Linux
- Camunda Modeler Version: v5.26.0
- Execution Platform: Any
- Installed plug-ins: None

### Additional context

Related, if I change the start event position manually (in the XML) and use the align (vertical) tool, then the start event snaps back to the original (not aligned) position:

![capture WO41fs_optimized](https://github.com/user-attachments/assets/6b06f8a9-2cb8-4436-a9c2-cd7d2dd76417)

----

Raised in [internal discussion](https://camunda.slack.com/archives/C0693F1NFK5/p1724829789844679)

**Comment by nikku** [comment]
Moving to `spring cleaning`.

**Comment by philippfromme** [comment]
Closed by https://github.com/camunda/camunda-modeler/pull/4642
