### ISSUE TITLE
Update the Camunda Docs about model a DMN

### ISSUE THREAD

**Issue by saig0** [camunda/camunda-modeler#450]
Update the [Camunda Docs](https://docs.camunda.org/manual/latest/modeler/camunda-modeler/dmn/) about model a DMN in the Camunda Modeler. 

* updated the screenshots
* add how to model a DRD

**Comment by lizergsav** [comment]
Hello

I have checked the documentation but I didn't found info about the DRD on the link.
Could you help where is that?

Thanks: Gábor

**Comment by SebastianStamm** [comment]
- Screenshots do not have the correct size. Please refer to https://github.com/camunda/camunda-docs-manual#how-do-i-make-screenshots-for-documentation
- The text on the Camunda Modeler overview page needs updating for the DMN section (currently states "How to model executable DMN 1.1 decision tables.")
