### ISSUE TITLE
I can use the new built-in functions from Camunda 8.6

### ISSUE THREAD

**Issue by saig0** [camunda/camunda-modeler#4500]
### Problem you would like to solve

Camunda 8.6 will add the following new built-in functions for the FEEL runtime (i.e. FEEL-Scala): 
* [is empty()](https://docs.camunda.io/docs/next/components/modeler/feel/builtin-functions/feel-built-in-functions-list/#is-emptylist)
* [trim()](https://docs.camunda.io/docs/next/components/modeler/feel/builtin-functions/feel-built-in-functions-string/#trimstring)
* [uuid()](https://docs.camunda.io/docs/next/components/modeler/feel/builtin-functions/feel-built-in-functions-string/#uuid)
* [to base64()](https://docs.camunda.io/docs/next/components/modeler/feel/builtin-functions/feel-built-in-functions-string/#to-base64value)

We should make sure that a user can use these functions in a BPMN/DMN model.

### Proposed solution

Add the new built-in functions to the FEEL editor.

### Alternatives considered

None.

**Comment by nikku** [comment]
To be re-built via [feel-editor](https://github.com/bpmn-io/feel-editor) so the functions are available for completion.

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/feel-editor/releases/tag/v1.9.0. Needs integration into editor.
