### ISSUE TITLE
Larger element names reduces the icon size in variables tab

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#4505]
### Describe the bug

When we have larger text names the icon of the actvitiy/event gets shrunk in the variables tab

### Steps to reproduce

1. Create a activity/event with a larger name that has input/output variables
2. Open the variables tab
3. We could see that the icon size of the respective element is shrunk with the length  of the name

https://github.com/user-attachments/assets/52dc1a4d-3712-4739-9300-f3e190e891dd

### Expected behavior

Larger element names could be cut short by adding ellipsis 

### Environment

- OS: [MacOS 10.2]
- Camunda Modeler Version: [5.27.0]
- Execution Platform: [Camunda 8]

**Comment by nikku** [comment]
This needs a fix in the [variable outline project](https://github.com/bpmn-io/variable-outline).

**Comment by misiekhardcore** [comment]
Is ellipsis the right approach here?
If so shouldn't we display the full name on hover (with `title` prop for example?
Or should we simply block shrinking the icon element?

**Comment by misiekhardcore** [comment]
Also I can see another problem, when the name is really long, it not only overflows the element list, but also it does not fit in the element on the diagram. Is this something what should also be addressed?
![Screenshot from 2024-10-31 10-21-29](https://github.com/user-attachments/assets/ec4f5eff-085c-4568-9fb4-aa92e4370178)

**Comment by abdul99ahad** [comment]
> Is ellipsis the right approach here? If so shouldn't we display the full name on hover (with `title` prop for example? Or should we simply block shrinking the icon element?

We are also doing the same in Problems tab and it doesn't display full element name on hover so imo, the variable tab should behave the same. 
<img width="822" alt="Screenshot 2024-11-04 at 20 00 19" src="https://github.com/user-attachments/assets/bd95eb84-f4c5-4a50-8ca8-3448e7c2741e">

**Comment by abdul99ahad** [comment]
> Also I can see another problem, when the name is really long, it not only overflows the element list, but also it does not fit in the element on the diagram. Is this something what should also be addressed? ![Screenshot from 2024-10-31 10-21-29](https://private-user-images.githubusercontent.com/58469680/381894533-ec4f5eff-085c-4568-9fb4-aa92e4370178.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MzI2NDksIm5iZiI6MTczMDczMjM0OSwicGF0aCI6Ii81ODQ2OTY4MC8zODE4OTQ1MzMtZWM0ZjVlZmYtMDg1Yy00NTY4LTlmYjQtYWE5MmU0MzcwMTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE0NTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNDYwNDRiNzNhMzFkNDg5OWU3YjgzMTFiZGM2YThiOWU5ZmIxYmI3M2Y1MTRjMWRlMDkxMzY4OGI3YzE5ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6iA0molldaAlHnBEvqgcOVe2_pOOMn0dJ3lt5-TUo3M)

As mentioned in the PR, this is out of scope for variable outline. This needs fix in [diagram-js](https://github.com/bpmn-io/diagram-js). Feel free to open the issue.

**Comment by nikku** [comment]
@abdul99ahad Let's go forth and integrate the upstream fix, closing this issue.
