### ISSUE TITLE
In empty state diagram elements are not displayed in variables tab

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#4506]
### Describe the bug

While there is no input/output variables and we Click anywhere outside in the process without selecting any element clicking on the process dropdown does not show any elements present in the process until we click on any element itself 

### Steps to reproduce

1. Create a process diagram that has no input/output variables
2. Click anywhere outside in the process without selecting any element
2. Open the variables tab
3. click on the dropdown beside the process name
4. No elements in the diagram is displayed
5. Click on any element and now clicking on the dropdown displays the element beneath the process. This is not the case when there is input/output variables are available in the process 

https://github.com/user-attachments/assets/1ea3ecf3-17e6-4703-8011-8202d10017ca

### Expected behavior

Display elements in the process even in empty state on clicking the dropdown

### Environment

- OS: [MacOS 10.2]
- Camunda Modeler Version: [5.27.0]
- Execution Platform: [Camunda 8]

**Comment by barmac** [comment]
The way it's implemented right now is to display only the elements which read or write variables. 

<img width="295" alt="image" src="https://github.com/user-attachments/assets/728541ac-2d88-482f-8722-056271189da8">

Does this notion change anything regarding your report?

**Comment by GeethaParthasarathy** [comment]
Hey @barmac just to re-clarify what you mentioned above , 

> display only the elements which read or write variables.

means there is no empty state if only when we have process variables added to the element . On that note the empty state msg makes sense. Thanks for clarifying !!

**Comment by barmac** [comment]
Thanks, I will then close the issue.
