### ISSUE TITLE
Sometimes tooltip in the variable tab makes dropdown inaccessible

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#4507]
### Describe the bug

The tooltip displayed for "elements" in the variables tab is displayed even if we hover away from the text and thus making the dropdown beneath it for expanding the elements in the process inaccessible

### Steps to reproduce

1. Open the variables tab 
2. Hover on the "elements" text
3. Try to move a bit further down to click on the dropdown of the process
4. We could see that tooltip text makes clicking on the dropdown not possible

https://github.com/user-attachments/assets/bc50d98a-8b4b-4dd4-9791-83c8d0ca516b

### Expected behavior

Display the hover text only while hovering on the "elements" text

### Environment

- OS: [MacOS 10.2]
- Camunda Modeler Version: [5.27.0]
- Execution Platform: [Camunda 8]

**Comment by barmac** [comment]
The tooltip keeps being displayed as long as you hover it. This is the same behavior as in the properties panel.

https://github.com/user-attachments/assets/719f08bf-40a2-42ea-9c8c-e54e820854eb

If we get rid of that behavior, the links in the tooltips will become inaccessible, or we need to maintain two different types of tooltips: hoverable and non-hoverable, which is in my opinion a bad UX.

![image](https://github.com/user-attachments/assets/5fa0c9a3-73a6-4595-aabe-2dd8f7b16c01)

Did I understand your report correctly? What do you think about the assessment above?

**Comment by GeethaParthasarathy** [comment]
@barmac Thanks for having a look at the issue. I get your point that the tooltip is displayed as long as we hover the text + the tooltip itself. In that case,
can we re-position that tooltip "Elements" so it does not hinder the dropdown selection?

**Comment by barmac** [comment]
If we position it to the right, it will cover the "Variables" title. I am afraid we will stay with what we have.

**Comment by nikku** [comment]
Let's close this as "won't fix". It is an inherent problem of using tooltips heavily.
