### ISSUE TITLE
"No matching variables" text does not disappear even after deleting the search string

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#4508]
### Describe the bug

"No matching variables" text does not disappear even after deleting the search string

### Steps to reproduce

1. Enter a search string in the variables tab such that itv results in " no matching variables found"
2. Close the dropdown of the process
3. Delete the search sting
4. Now all the process and its elements are displayed
5. But the search sting is taken to account and displays the text " no matching variables found"

https://github.com/user-attachments/assets/edee5d9f-ce62-4836-89a1-256f2f130a71

### Expected behavior

After deletion of search string the text should not be displayed

### Environment

- OS: [MacOS 10.2]
- Camunda Modeler Version: [5.27.0]
- Execution Platform: [Camunda 8]

**Comment by barmac** [comment]
I cannot reproduce this problem. Can you please share the diagram in which you experienced the problem? Do you have a simplified diagram in which I can reproduce it? I noticed there are multiple elements on the capture.

**Comment by GeethaParthasarathy** [comment]
@barmac Somehow I could not reproduce the issue as well now. With the same diagram and also on a different one. I will close the issue for now

**Comment by barmac** [comment]
I removed the milestone as we did not fix anything here.
