### ISSUE TITLE
Version tag binding input loses focus

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#4513]
### Describe the bug

When typing in the _Version tag input of a business rule task, call activity or user task the input loses focus.

![Camunda_Modeler_3PyQMsnuct](https://github.com/user-attachments/assets/e2beedbc-eab7-409c-bc20-c261439599d2)

### Steps to reproduce

1. Focus Version tag input
2. Start typing
3. Focus lost

### Expected behavior

Focus not lost.

### Environment

- Camunda Modeler Version: 5.27

**Comment by nikku** [comment]
@jfriedenstab previously reported that validation for `versionTag` not being empty is not happening at all, which I can reproduce on Camunda Modeler v5.27.0:

![image](https://github.com/user-attachments/assets/84dffc49-3529-4264-9bb1-ce72d8036bd8)

At the same time "not supported" seems to validate both fields, the `versionTag` field, and the chooser, where I'd expect that the chooser only is the error, as this is where the user has to *fix* things:

![image](https://github.com/user-attachments/assets/e9878e59-b689-4a9f-af37-084726ca3630)

**Comment by philippfromme** [comment]
The reason for the focus loss is the use of `withProps` (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/blob/main/src/provider/zeebe/properties/CalledDecisionProps.js#L56) and the fact that we effectively create a new component on every render. The _Binding_ select uses `withProps` and has the same issue but it's not as obvious since there is no caret indicating focus.

To fix this issue we only want to create the component once (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1076)  so that React doesn't replace it in the DOM on every render assuming it's a different component.
