### ISSUE TITLE
Improve variables integration into Desktop Modeler

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4516]
### Problem you would like to solve

As a user I want to use the new variables tab, in order to do so I need to open the problems panel, discover the "variables" tab, and switch to it. It is very likely I'll not discover it, as I need it.

![capture YdHMwl_optimized](https://github.com/user-attachments/assets/ff4a0c0d-036c-487d-bc26-7970a560f786)

### Proposed solution

* [ ] The variables tab is properly integrated in the modeler, so I can discover (and switch to it) using standard means
  * [ ] Available via keyboard shortcut and menu item to "jump to", if it is available
  * [ ] (optional) Available via footer, such as the problems panel

### Alternatives considered

None. If we integrate a feature, then we want to ensure it is discoverable, and accessible.

### Additional context

See integration into [web modeler](https://modeler.camunda.io). It checks accessibility and discoverability boxes:

![capture z1bq6x_optimized](https://github.com/user-attachments/assets/dec2e476-db1a-4356-9daa-f1af21931990)

----

Related to https://github.com/camunda/camunda-modeler/issues/4267

**Comment by nikku** [comment]
Moving this to `ready` because I believe a sensible improvement could be a simple thing to do.

**Comment by abdul99ahad** [comment]
Feature Understanding:

- The Variables tab needs to be accessible from the menu bar.
- There should also be a keyboard shortcut to open the Variables tab.
- Additionally, it should be possible to open the Variables tab from the footer, similar to how it works in the Web Modeler.
