### ISSUE TITLE
Boolean type input elements throw output errors

### ISSUE THREAD

**Issue by DenovVasil** [camunda/camunda-modeler#4517]
### Describe the bug

When we create a scheme with aws textract connector in Desctop modeler, errors appear in the output section.

### Steps to reproduce

1. Add this [template](https://github.com/camunda/connectors/blob/main/connectors/aws/aws-textract/element-templates/aws-textract-outbound-connector.json) to modeler
2. prepare simple schema with aws textract outnound connector
3. see errors in output 
<img width="1427" alt="image" src="https://github.com/user-attachments/assets/2a8739ca-819a-45d2-9fd8-0165aa6142fa">

### Expected behavior

Output should not contains errors.
We think that errors in output are the reason for the  [e2e tests to fail](https://github.com/camunda/web-modeler/issues/10726)

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

**Comment by nikku** [comment]
@DenovVasil any particular reason this ended up in [this project](https://github.com/orgs/camunda/projects/121)?

**Comment by DenovVasil** [comment]
> @DenovVasil any particular reason this ended up in [this project](https://github.com/orgs/camunda/projects/121)?

sorry, changed

**Comment by marstamm** [comment]
Hi @DenovVasil ,

thank you for the bug report. I can reproduce this. We do have a fix in the element templates here: https://github.com/bpmn-io/bpmn-js-element-templates/pull/121

Input/output mappings need to be feel expressions. While we do cast Number and Boolean fields to feel on change, we did not do it for default values. As a workaround, you can change the default values for the Boolean properties from `"value": true` to `"value": "=true"` until the PR above is merged and integrated.

**Comment by nikku** [comment]
Pending downstream integration of https://github.com/bpmn-io/bpmn-js-element-templates/releases/tag/v2.2.1.
