### ISSUE TITLE
Have a summary view of all properties in the diagram

### ISSUE THREAD

**Issue by vkatushenok** [camunda/camunda-modeler#452]
It would be good to have something like  _"properties summary panel"_ that, for example, displays all configurable properties in a hierarchic structure.

If a property was set on an element, the property is added as a leaf of the corresponding property in the panel (marked, for example, by the name and id of the element).

If one moves in the "properties summary panel" and activates the leaf, the corresponding element is activated in the model and the configured properties are displayed (so the corresponding tab is also opened). This way, one can, for example, see how many executions listeners are defined in a model and can easily navigate to those points in the model and can then see the configured properties. 

Needs discussion/opinions on how to best approach this task.

__Tasks__

* [ ] As a user I'm able to see configured implementation details configured for all diagram elements
* [ ] As a user, I'm able to see whether details are configured for an individual element (https://github.com/camunda/camunda-modeler/issues/442) 

See original [request](https://app.camunda.com/jira/browse/SUPPORT-2852) for more info.

**Comment by philippfromme** [comment]
Thanks to https://github.com/umb/camunda-modeler-property-info-plugin this is no longer needed.
