### ISSUE TITLE
Missing BPMN elements in the 'Append element' menu

### ISSUE THREAD

**Issue by sarahekelley** [camunda/camunda-modeler#4524]
### Describe the bug

The 'Append element' menu is not displaying several BPMN elements, including Inclusive gateway, Complex gateway, Send task, Receive task, and Manual task. These elements are only accessible through the Search box within the Append Element menu, but they do not appear in the standard scrollable list of elements.

### Steps to reproduce

1. Open Camunda Modeler
2. Create or open a BPMN diagram
3. Select an existing element on the Canvas (e.g., Start event)
4. Click on the Append Element Context Pad to activate it (blue plus icon)
5. Select the 'Append element' option (... icon)
6. Scroll through the menu of elements to append

Gateways on the Append Element Menu
![gateways-on-append-menu](https://github.com/user-attachments/assets/f3158b13-5263-4fb6-8d92-09bb342a0962)

Tasks on the Append Element Menu
![tasks-on-append-menu](https://github.com/user-attachments/assets/1634b936-4eb8-4f25-85a7-b96d9be9ab91)

### Expected behavior

All appropriate BPMN elements for the selected source element should be visible and selectable in the scrollable list of the 'Append element' menu without needing to use the Search box. The menu should dynamically adjust its options based on the selected element, showing only valid append choices for that particular BPMN element type.

### Environment

- OS: Operating System: Windows 11
- Camunda Modeler Version: 5.27
- Installed Plug-Ins: None

### Additional context

The missing elements can still be accessed by using the Search box within the Append Element menu. This suggests that the elements are implemented but not properly displayed in the standard menu view. This issue may impact user workflow and efficiency, especially for users who are unaware that these elements can be found through the search function.

**Comment by sarahekelley** [comment]
This behavior is also present on the Create element menu. 

![image](https://github.com/user-attachments/assets/5b445608-d502-4242-96ef-598f4f9a775c)

**Comment by nikku** [comment]
Thanks for opening this report. 

> ### Expected Behavior
> 
> All appropriate BPMN elements for the selected source element should be visible and selectable in the scrollable list of the 'Append element' menu without needing to use the Search box. 

What you see here is us being "opinionated". 

There is certain elements that are rarely being used, sometimes even discouraged by common practices. Hence the existing UI de-prioritizes these elements.

We don't plan to "always show everything", but think that the existing behavior benefits most users, in the happy path, for common modeling operations. Advanced users that know what they are looking for will find the full palette of BPMN elements, through the search.

> The menu should dynamically adjust its options based on the selected element, showing only valid append choices for that particular BPMN element type.

This, again, is where we trade of ease of use against correctness. Assume the following scenario, how would I create an event sub-process (that cannot be appended), without loosing the local diagram context, if the element was hidden from the append menu? 

![capture ko451E_optimized](https://github.com/user-attachments/assets/009d84e7-32ea-43db-8274-2e826abe9270)

If we were strict with the options provided the following would be the effects for our users: 

* You'd need to resort to the palette (or create menu), hence spending valuable time moving your mouse that you don't need if append is forgiving.
* You'll be late to discover what is available, especially as a new user, and have to remember what is available where

The current solution gives you peace of mind, and [don't make me think](https://en.wikipedia.org/wiki/Don't_Make_Me_Think), and we plan to stick to it.
