### ISSUE TITLE
Invalid BPMN elements in the 'Appened element' menu

### ISSUE THREAD

**Issue by sarahekelley** [camunda/camunda-modeler#4525]
### Describe the bug

The 'Append element' menu is displaying and allowing selection of elements that cannot be validly appended to the selected element. Specifically, Boundary Events are showing as available options for elements that should not have them, such as Start Events, Intermediate Events, and Gateways of all types.

### Steps to reproduce

1. Open Camunda Modeler
2. Create or open a BPMN diagram
3. Select an element that should not have Boundary Events (e.g., Start Event, Intermediate Event, or Gateway)
4. Click on the Append Element Context Pad to activate it (blue plus icon)
5. Select the 'Append element' option (... icon)
6. Observe that Boundary Events are available in both the scrollable list and search results
7. Attempt to append a Boundary Event:
a. If an interrupting Boundary Event is selected, it can be placed on the Canvas. However, since Boundary Events can only be placed on Activities, it is actually placed as an Intermediate Event.
b. If a non-interrupting Boundary Event is selected, it cannot be placed on the canvas at all.

![invalid-elements-on-append-menu](https://github.com/user-attachments/assets/6a0b3046-344d-4cb6-9d46-9b6df060dd7e)

### Expected behavior

The 'Append element' menu should be context-sensitive and only display elements that can be validly appended to the selected element. Boundary Events should not appear as options for elements that cannot have them, such as Start Events, Intermediate Events, and Gateways. The menu should only show valid append choices for the particular BPMN element type selected.

### Environment

- Operating System: Windows 11
- Camunda Modeler Version: 5.27
- Installed Plug-Ins: None

### Additional context

This issue can lead to confusion for users and potential modeling errors. The fact that interrupting Boundary Events can be placed but transform into Intermediate Events is particularly problematic, as it may result in incorrect diagrams without the user realizing the mistake.

**Comment by nikku** [comment]
Similar rationale / explaination to https://github.com/camunda/camunda-modeler/issues/4524#issuecomment-2357913074, with two additions:

Boundary events and intermediate events are interchangeable, and providing an unforgiving UX will hurt our users. We aim to [empower them](https://github.com/bpmn-io/design-principles#empower-the-user).

The following capture shows an existing usage pattern (append anything, anywhere), including attaching a boundary event from the append menu:

![capture 8o3RWz_optimized](https://github.com/user-attachments/assets/72c83049-be85-4f71-9e2a-34bd73a4ac4f)

---

> The menu should only show valid append choices for the particular BPMN element type selected.

Maybe I'm not seeing it, but what are the negative effects of having these elements in there?
