### ISSUE TITLE
Element Template Runtime Versions

### ISSUE THREAD

**Issue by jarekdanielak** [camunda/camunda-modeler#4530]
This is a tracking issue for [Element Template Runtime Versions epic](https://github.com/camunda/product-hub/issues/2368).

### Description

We want to detect, communicate and help users solve incompatibilities between their platform version and element template version.

We want to warn the user about the incompatibility in a non-blocking way, allowing them to fix the problem or continue with the deployment.

### To do:

- [x] https://github.com/camunda/element-templates-json-schema/issues/146
    - https://github.com/camunda/element-templates-json-schema/pull/152
- [x] Ensure user is always offered the most relevant template version for their execution platform version
    - https://github.com/bpmn-io/bpmn-js-element-templates/pull/132
- [x] Add linting for incompatible templates
- [x] Integration with Desktop Modeler
    - https://github.com/camunda/camunda-modeler/pull/4744
    - [x] Integration testing 
- [x] Integration with Web Modeler
  -  https://github.com/camunda/web-modeler/pull/12273
- [ ] Update [Camunda docs page](https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/element-templates/defining-templates).
    - https://github.com/camunda/camunda-docs/pull/4780
 - [ ] Refresh [element-templates documentation](https://github.com/bpmn-io/element-templates/)

### Follow up:

- https://github.com/camunda/marketplace-api/issues/102
- https://github.com/camunda/camunda-modeler/issues/4751
- https://github.com/camunda/camunda-modeler/issues/4760
- @lmbateman feedback on integration pull request
    - https://github.com/camunda/camunda-modeler/pull/4744#issuecomment-2541828239
- https://github.com/camunda/camunda-modeler/issues/4766
 
### Note:

- Make sure the solution covers applying a template through both properties panel and element context menu.
- Supported platform versions JSON field should be optional.
- Current template upgrade feature should not offer an upgrade to an incompatible version.

### Additional documentation

- [User flow chart](https://www.figma.com/board/iDDbABRzfXeIiq09WY8SAt/Element-template-runtime-versions---User-flow?node-id=0-1&node-type=canvas&t=1oWCbjQ2JdQCihQb-0)
- [Define kick-off board](https://miro.com/app/board/uXjVLfuFjQY=/)

**Comment by nikku** [comment]
> Detect and act upon incompatibilities:

I'd add "User is offered templates relevant to his context".

**Comment by lmbateman** [comment]
Yana has done some work on missing templates that might be informative. I'll go through it and see if there's anything we need to be aware of.

- [User journey for missing templates](https://www.figma.com/board/JYHiIrG2tlLWIP0x3FtVI5/Missing-resources-user-journey?node-id=0-1&t=82ePZiA6Zl38BZaI-1)
- [LFW for missing templates](https://www.figma.com/design/nrB4K2EXZju7JqJGjODU5L/process-bluepront-dialog?node-id=677-4043&t=LTGn4b9tmGs8KAFG-4)

**Comment by jarekdanielak** [comment]
Updated after latest discussions.

**Comment by jarekdanielak** [comment]
Decision tree of choosing the latest compatible version of element template along with some edge use-cases.

![excali-el-templates](https://github.com/user-attachments/assets/77c02bc6-d3b1-45c9-b105-d4cf6c302272)

**Comment by jarekdanielak** [comment]
Reopening as there are still some integration and documentation tasks to do.

**Comment by jarekdanielak** [comment]
With the feature integrated in both modelers and documentation pending to be merged, I consider this closed now.
