### ISSUE TITLE
When you have a search term that does not resolve it still highlights the element that was previously searched upon.

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#4538]
### Describe the bug

When you have a search term that does not resolve it still highlights the element that was previously searched upon.

### Steps to reproduce

1. Create a simple bpmn diagram
2. Add a search term that resolves to an element -> respective element highlighted
3. Then add a random search term that does not resolve yet we could see that the previously highlighted element still remains highlighted.

Note: This is not the case when no element was highlighted as part of the first search term
Also I used the term "user" and I am not sure how it resolved to the sequence flow

https://github.com/user-attachments/assets/2fc8ae81-b9c4-4014-b8b3-acaf8587d798

### Expected behavior

When no element is resolved for a search term do not focus/highlight on any element in the canvas

### Environment

 OS : Mac os
env : Web Modeler

---

Depends on https://github.com/bpmn-io/diagram-js/pull/931

**Comment by philippfromme** [comment]
This issue will be addressed by https://github.com/bpmn-io/diagram-js/pull/931.
