### ISSUE TITLE
Parameterless functions are suggested with non-existing parameter

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4539]
### Describe the bug

It should suggest `now()`.

<img width="662" alt="image" src="https://github.com/user-attachments/assets/159aebbb-390a-45a3-84b6-2027be908678">

### Steps to reproduce

1. Type "now"
3. now this happens

### Expected behavior

No parameters suggested.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

Reported already in https://github.com/bpmn-io/dmn-js/issues/898

**Comment by nikku** [comment]
Requires integration of https://github.com/bpmn-io/feel-editor/releases/tag/v1.9.1.
