### ISSUE TITLE
Literal expression editor body has small hitbox in BKM

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4545]
### Describe the bug

In an empty literal expression editor of BKM, I need to select the first line to get keyboard focus

![Recording 2024-06-06 at 10 38 04](https://github.com/camunda/camunda-modeler/assets/21984219/48bef520-a372-43b1-900f-2c0cd8b01d3e)

### Steps to reproduce

1. Open a literal expression editor
2. Click around in the function body
3. If you do not hit the first line, Keyboard focus is lost/not achieved

### Expected behavior

I can click anywhere and the cursor gets positioned at the end of the file

### Environment

 * Version: 5.24.0-rc.0, v5.28.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: DMN - Camunda 8

### Additional context

The cursor also suggests that I can click anywhere to edit

[SUPPORT-23549](https://jira.camunda.com/browse/SUPPORT-23549)

Follow-up of https://github.com/camunda/camunda-modeler/issues/4342

**Comment by nikku** [comment]
As this is a follow-up to a [proclaimed fix](https://github.com/camunda/camunda-modeler/issues/4342) I'm moving this to ready.

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/dmn-js/pull/905.

**Comment by nikku** [comment]
@jarekdanielak Let's release + integrate the fix for this.
