### ISSUE TITLE
Searching makes diagram shift down in the canvas

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#4547]
### Describe the bug

When you enter a search term it makes diagram shift down in the canvas

### Steps to reproduce

1. Create any diagram
2. Press CTRL+F and enter a search term
3. We could see that the diagram in the canvas is shifted down as it resolves to any element

https://github.com/user-attachments/assets/35d1ae1a-157c-4309-b5fd-27faa80030a7

### Expected behavior

Diagram position should remain the same even when a element is resolved as a result of search

### Environment

- OS: [MacOS 10.2]
- Camunda Modeler Version: [5.28.0.]
- Execution Platform: [Camunda 8]
- Installed plug-ins: [...]

**Comment by barmac** [comment]
I can reproduce this. It's not blocking the release.

**Comment by barmac** [comment]
@philippfromme Perhaps this is related to the recent changes in search?

**Comment by philippfromme** [comment]
This is fixed upstream by https://github.com/bpmn-io/diagram-js/pull/931.
