### ISSUE TITLE
Definition id and name properties editing is always triggered

### ISSUE THREAD

**Issue by ricardomatias** [camunda/camunda-modeler#455]
How to reproduce:
- Edit the definitions name or id
- Select an element
- Click on a random letter key or try to trigger Lasso tool
- boom!

Expected:
- The inputs are blurred once I click outside

**Comment by nikku** [comment]
Due to https://github.com/bpmn-io/diagram-js/issues/200 we cannot fully fix this.

Clicking on diagram elements will still not unfocus the `{ id, name }` inputs. Clicking on the canvas will work though.

**Comment by nikku** [comment]
Created https://github.com/camunda/camunda-modeler/issues/463 for the remaining parts we cannot fix right now.
