### ISSUE TITLE
Welcome tab changes font size

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4555]
### Describe the bug

If I close the last tab, then the welcome tab has a huge font-size:

![capture LbBb3a_optimized](https://github.com/user-attachments/assets/5d695f0e-d7e8-4f2d-8aa0-49fd2da4715b)

### Steps to reproduce

1. Open a new tab
2. Close it
3. **Observe huge font-size in welcome tab**

### Expected behavior

Font size stays consistent.

### Environment

- OS: Linux
- Camunda Modeler Version: v5.28.0
- Execution Platform: any
- Installed plug-ins: none

**Comment by nikku** [comment]
Potentially related to https://github.com/camunda/camunda-modeler/issues/4550.

**Comment by jarekdanielak** [comment]
Closed by https://github.com/camunda/camunda-modeler/pull/4599
