### ISSUE TITLE
Indentation in XML/JSON view broken

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#4556]
### Describe the bug

The indentation in the XML and JSON view isn't working anymore. It's not displayed and I cannot indent a line using <kbd>SPACE</kbd> or <kbd>TAB</kbd>.

![Camunda_Modeler_IsoCjuc5I9](https://github.com/user-attachments/assets/909f93ca-d24d-43af-9130-df9b808630a8)

### Steps to reproduce

1. Open XML or JSON view
2. Indentation not working
3. Cannot indent

### Expected behavior

Indentation works.

### Environment

- Camunda Modeler Version: 5.28-rc.1

**Comment by barmac** [comment]
I've run `git bisect`, and the first commit to break it is the form-js update: https://github.com/camunda/camunda-modeler/commit/8f6662dc5a8e6e558a6d2052a747b5654673d031

**Comment by barmac** [comment]
The update installs new versions of multiple codemirror packages. I will update in the client and see if it fixes the problem.

**Comment by barmac** [comment]
I've got a fix for this, and will create a PR in a second.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/4560.
