### ISSUE TITLE
Input field looses focus

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4559]
### Describe the bug

If I type in the `Task Definition > Retries` field the input looses focus. The same issue can be replicated across different types of `FEEL (optional)` fields.

![capture wR68uZ_optimized](https://github.com/user-attachments/assets/dfa2b203-7afd-47bb-b558-64a198b6779e)

### Steps to reproduce

1. Write `= some expression` into a `Task Definition > Retries` field
2. Remove expression (all content)
3. Type `= s` again in the field
4. **Input is no longer focussed**

### Expected behavior

Input keeps focus when field turns into an expression field

### Environment

- OS: Linux
- Camunda Modeler Version: v5.28.0 (works in v5.27.0)
- Execution Platform: Camunda 8
- Installed plug-ins: None

**Comment by barmac** [comment]
I can reproduce it in v5.28 but cannot in v5.27.

**Comment by nikku** [comment]
I cannot reproduce this in the core libraries ([bpmn-js-properties-panel](https://github.com/bpmn-io/bpmn-js-properties-panel) `main`) either.

**Comment by barmac** [comment]
Let's check if we can reproduce it before the form-js update.

**Comment by barmac** [comment]
`camunda-bpmn-js#main` works fine

**Comment by barmac** [comment]
74bf2252e24e2883384ade79d4933a32cd218e9c is good (before form-js update)

**Comment by barmac** [comment]
This one is broken by 8f6662dc5a8e6e558a6d2052a747b5654673d031 too. So it's form-js update again.

**Comment by barmac** [comment]
Right now I am puzzled. The bug is not present in the forms though (there's flickering but it's a different topic):


https://github.com/user-attachments/assets/37df1521-1f99-4846-88d8-c4b12daf1cac

**Comment by barmac** [comment]
Current guess is that it's something about preact or diagram-js-ui.

**Comment by barmac** [comment]
So `@bpmn-io/properties-panel` ships with `preact@10.19.3`, and there is also `preact@10.11.3` in `node_modules`.

**Comment by nikku** [comment]
Both are (_should be_) isolated from each other though.

**Comment by barmac** [comment]
Yes, and this does not change with the broken commit.

**Comment by barmac** [comment]
Any ideas?

**Comment by barmac** [comment]
Right now, the only solution I can see is to revert the update, and figure this out later.

**Comment by barmac** [comment]
Let's try this.

**Comment by barmac** [comment]
LOL. I installed the outdated forms dependencies and pinned them, but that did not fix the problem :D

**Comment by barmac** [comment]
"Fix" coming via https://github.com/camunda/camunda-modeler/pull/4563

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/4563.
