### ISSUE TITLE
Cannot open nightly from 2024-10-07 on MacOS Sequoia (15)

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4588]
### Describe the bug

I just downloaded the latest nightly, and MacOS refuses to open it:

![image](https://github.com/user-attachments/assets/b7527612-50bb-4b31-abd4-438325afb4e4)

This may be related to my recent upgrade to MacOS Sequoia, but also to https://github.com/camunda/camunda-modeler/pull/4579

I can open v5.28.0 though so it's less likely that this is solely due to MacOS upgrade.

### Steps to reproduce

1. Download nightly from https://downloads.camunda.cloud/release/camunda-modeler/nightly/
2. Try to open
3. now this happens

### Expected behavior

Nightly opens without problem.

### Environment

- OS: MacOS 15.0.1
- Camunda Modeler Version: nightly
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

**Comment by barmac** [comment]
I am moving this to the ready as this may block the next release.

**Comment by barmac** [comment]
Maybe it's due to missing notarization?

>   • skipped macOS notarization  reason=`notarize` options were unable to be generated
https://github.com/camunda/camunda-modeler/actions/runs/11221353989/job/31191526949#step:7:219

**Comment by nikku** [comment]
I think this goes in line with https://github.com/camunda/camunda-modeler/issues/4578.

**Comment by barmac** [comment]
Nightly works again.

**Comment by barmac** [comment]
I think it was a temporary problem with Mac.
