### ISSUE TITLE
Support user task listeners

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4590]
### What should we do?

Implement user task listeners in Camunda 8

```xml
<userTask id="my_user_task" name="my_user_task">
 <extensionElements>
   <zeebe:userTask/>
   <zeebe:taskListeners>
     <zeebe:taskListener eventType="create" type="create_listener" retries="2"/>
     <zeebe:taskListener eventType="assignment" type="assignment_listener"/>
     <zeebe:taskListener eventType="update" type="update_listener" retries="8"/>
     <zeebe:taskListener eventType="complete" type="complete_listener"/>
   </zeebe:taskListeners>
   <zeebe:priorityDefinition/>
   <!--other extension props e.g. assignmentDefinition, priorityDefinition-->
 </extensionElements>
 <!--other props-->
</userTask>
```

* [x] I can define task listeners on user task
  * [x] type (string, FEEL expression)
  * [x] eventType: `complete`, `assignment`
  * [x] retries (string, FEEL expression, default is 3)
* [x] TLs can be used in Camunda 8.7 or newer
* [x] When I switch from Zeebe user task to job worker, the task listeners are removed

Projects:
* [x] https://github.com/camunda/zeebe-bpmn-moddle/pull/67
* [x] https://github.com/camunda/camunda-bpmn-js-behaviors/pull/88
* [x] https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1088
* [x] https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/181
* [x] https://github.com/camunda/linting/pull/123

### Why should we do it?

Product hub epic: https://github.com/camunda/product-hub/issues/1316

**Comment by barmac** [comment]
This is blocked until we clarify the XML structure: https://camunda.slack.com/archives/C0622NWC9LK/p1729161860084329

**Comment by barmac** [comment]
We clarified the XML structure, but the list of event types needs to be decided upon yet.

**Comment by barmac** [comment]
The duplicate listeners won't be rejected by the engine as decided in https://camunda.slack.com/archives/C0622NWC9LK/p1729762326243379?thread_ts=1729176573.663119&cid=C0622NWC9LK
We may consider to have a warning though as it's hard to imagine anybody defines duplicates on purpose.

**Comment by barmac** [comment]
I updated the event types according to https://camunda.slack.com/archives/C0622NWC9LK/p1730303397300139?thread_ts=1730288591.575289&cid=C0622NWC9LK
Note that the stretch goal is to support more events, so it's not fixed yet.

**Comment by barmac** [comment]
Task listeners on process are out of scope: https://camunda.slack.com/archives/C0622NWC9LK/p1730311452811039?thread_ts=1730288591.575289&cid=C0622NWC9LK

**Comment by barmac** [comment]
This is ready now.

**Comment by misiekhardcore** [comment]
@barmac what do you mean? where do you want to put this file?

**Comment by barmac** [comment]
I prepared this as an example BPMN (cf. https://camunda.slack.com/archives/C0622NWC9LK/p1730909451217819). There's no need to include it anywhere in the source code, but we can use it as way to verify the solution.

**Comment by barmac** [comment]
> We could use this BPMN as an example to open once the feature is implemented:
> 
> [user-task-listener.bpmn.txt](https://github.com/user-attachments/files/17661353/user-task-listener.bpmn.txt)

The file was broken, but replaced it with a fixed one.

**Comment by misiekhardcore** [comment]
@barmac All the parts of this issue are now done. What are the next steps?

**Comment by barmac** [comment]
As the feature is implemented in the upstream libraries, we can now move the issue to `fixed upstream`. Then, to close it, we will need to open and merge a pull request which integrates the respective dependency updates into the Modeler.

**Comment by barmac** [comment]
I will open an integration PR for this once https://github.com/camunda/camunda-modeler/pull/4620 is merged.
