### ISSUE TITLE
Remember Advanced Mode toggle globally

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#460]
Specially in the context of DRDs it is annoying to select the advanced mode every time you enter a decision table.

__Expected__

- [x] The modeler remembers if the user has entered the advanced mode or not.

__Todo__

* [x] Implement
* [ ] Merge to Camunda Modeler

**Comment by nikku** [comment]
Looks good to me. 

Postponing the merge until `M10`, as the implementation on Camunda Modeler side requires a dmn-js minor release.

**Comment by nikku** [comment]
Advanced / Simple mode is now remembered per diagram.
