### ISSUE TITLE
Consistent Reference Direction of created DRD Elements

### ISSUE THREAD

**Issue by saig0** [camunda/camunda-modeler#461]
Reproduce:
* create a new DRD
* create a decision, input data and knowledge source from the initial decision

Problem:
* reference directions are different:
  * input data -> decision 
  * decision -> new decision
  * decision -> knowledge source

![image](https://cloud.githubusercontent.com/assets/4305769/20556784/f6f87444-b168-11e6-8072-d06152ba62ce.png)

I would expect that all reference directions go from the created element to the decision (like for input data). This would also allows to model top-down (instead of buttom-up), e.g. create a required decision from a decision.

**Comment by SebastianStamm** [comment]
We should reconsider if the context pad is the right way to create new elements in the drd context, as the preferred modeling "direction" is not as clear as e.g. in bpmn.

One way to solve this would be to remove the possibiity to create new elements from the context pad (except text annotations), allow an easy way to create from the palette (maybe with keyboard shortcuts, or hold shift to create multiple instances of the same element type) and offer a global connect tool.

**Comment by nikku** [comment]
Improving this is not on our short term roadmap.

**Comment by nikku** [comment]
Related to https://github.com/bpmn-io/dmn-js/issues/216.
