### ISSUE TITLE
Multiline sript editor isn't working

### ISSUE THREAD

**Issue by tamaserdfalvi** [camunda/camunda-modeler#4612]
### Describe the bug

I'm unable to edit a multiline script in the "Script" field of a script task for a Camunda7 BPMN flow.

### Steps to reproduce

1. Create a script task
2. Set it to "inline script"
3. It'll always be single-line. I cannot add linebreak with neither enter,ctrl+enter,alt+enter, etc.

### Expected behavior

Enter would create a new line and I'll be able to edit a multiline script

### Environment

- MacOS 15.0.1
- Camunda Modeler Version 5.28.0
- Installed plug-ins: none

**Comment by tamaserdfalvi** [comment]
It's actually seems to be connected to some problem on my computer, so I'm closing it. Even downgrading to 5.27.0 produces it from time to time, which used not to, and a modeler restart solves it

**Comment by tamaserdfalvi** [comment]
It's actually seems to be connected to some problem on my computer, so I'm closing it. Even downgrading to 5.27.0 produces it from time to time, which used not to, and a modeler restart solves it

**Comment by barmac** [comment]
As a confirmation, I cannot reproduce it:

https://github.com/user-attachments/assets/52128d17-7c11-4cef-bda3-093f533eb88e
