### ISSUE TITLE
Template selector is misplaced

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4617]
### Describe the bug

The `template` selection is misplaced (very low in the properties panel), so that it can easily be overlooked:

![image](https://github.com/user-attachments/assets/8b554dc5-57ba-4d61-b730-d209300f0fe4)

### Steps to reproduce

1. Open any diagram
2. Model any task
3. Locate template picker -> very low in the properties panel

### Expected behavior

Template picker is prominently displayed in the properties panel, below the "Documentation" section.

### Environment

- OS: Any
- Camunda Modeler Version: v5.28.0
- Execution Platform: Camunda 8
- Installed plug-ins: None

**Comment by barmac** [comment]
Let's clarify:

> Template picker is prominently displayed in the properties panel.

So below documentation like in 5.25:

<img width="277" alt="image" src="https://github.com/user-attachments/assets/b50e9458-4981-4a21-acab-b6a4c7d33c85">

**Comment by barmac** [comment]
This needs to be fixed in https://github.com/bpmn-io/bpmn-js-element-templates/blob/main/src/cloud-element-templates/properties-panel/ElementTemplatesPropertiesProvider.js#L61

**Comment by barmac** [comment]
We still want to display the execution listeners above the template when it's applied, correct?

**Comment by barmac** [comment]
Example:
<img width="270" alt="image" src="https://github.com/user-attachments/assets/ae3976d6-6137-40a6-9cbd-1444518bfe13">

**Comment by misiekhardcore** [comment]
I think this needs to be fixed in `bpmn-js-properties-panel` as well, so the `Zeebe_ExecutionListener` group is also above the other groups. Otherwise if `Zeebe_ExecutionListener` is down on the list, and we put `Templates` below, those two will always be on the bottom

**Comment by nikku** [comment]
@misiekhardcore Where else could we anchor the element template selector, so we don't have to move Zeebe execution listeners?

**Comment by misiekhardcore** [comment]
Looking at @barmac comment above, we want to also move the execution listeners higher

**Comment by nikku** [comment]
You mean this?

> We still want to display the execution listeners above the template when it's applied, correct?

What would be practical reasons to put execution listeners above the template selector? I don't see it.

**Comment by misiekhardcore** [comment]
sounds reasonable to me, I just tried to follow whats was written in the comments. If you are both fine with just moving the templates group right below the Documentation group, then I will do that

**Comment by barmac** [comment]
I moved the template group below execution listeners for a templated element to prevent conflating execution listeners with the template-specific properties. However, if we see the templated element as just one of the elements, then I agree that there should be no change in positioning. So it's OK to position the template group right below the documentation regardless if template is applied or not, and execution listeners group on the bottom.

**Comment by barmac** [comment]
> We still want to display the execution listeners above the template when it's applied, correct?

So I take back this.

**Comment by nikku** [comment]
This issues is not closed by https://github.com/bpmn-io/bpmn-js-element-templates/pull/130, but instead awaits integration of the upstream change to be fixed. I re-opened and attached `fixed upstream` to it.

**Comment by philippfromme** [comment]
Ooops, sorry I missed that it included a `closes`. Indeed it's only `related to`.
