### ISSUE TITLE
Clean nightly builds

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4619]
### What should we do?

As [reported](https://camunda.slack.com/archives/GP70M0J6M/p1729193214816219) by @lmbateman the [nightly builds](https://downloads.camunda.cloud/release/camunda-modeler/nightly/) still contain the old, vastly outdated all in one DMG for MacOS. We should remove it.

### Why should we do it?

Allow our users to use latest nightlies.

**Comment by barmac** [comment]
I've reached out to infra via https://github.com/camunda/team-infrastructure/issues/703

**Comment by barmac** [comment]
Done! https://github.com/camunda/team-infrastructure/issues/703#issuecomment-2421772310
