### ISSUE TITLE
cannot save DRD

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#462]
Reproduce:
- create new DRD
- create a second decision element (table or literal expression)
- enter the new decision element
- save

Problem:
saving the diagram is not possible

**Comment by mschoe** [comment]
@ricardomatias , @gimbel I think this is a blocking one

**Comment by gimbel** [comment]
I agree, let's have a follow up on this again

**Comment by nikku** [comment]
Missing: An integration test that verifies that stuff works (now and in the future).
