### ISSUE TITLE
I can use BPMN group elements for modeling

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#464]
Why do we need this?

Group artifacts can help a lot to structure models and make them more understandable - just like text annotations.

People ask for them in trainings and I think they should be available in the modeler. Also, you guys promise to provide full BPMN coverage in the modeler ;) 

https://docs.camunda.org/manual/7.5/modeler/camunda-modeler/bpmn/#bpmn-2-0-coverage 

Cheers, Ben

---

Depends on https://github.com/bpmn-io/bpmn-js/issues/343

**Comment by nikku** [comment]
What about [using colors](https://github.com/camunda/camunda-modeler/issues/390) for semantic grouping instead?

**Comment by nikku** [comment]
Needs to be addressed via https://github.com/bpmn-io/bpmn-js/issues/343.

**Comment by benhoffmann** [comment]
I wouldn't like using colors as a replacement for groups since they are not part of the standard. Also colors could be used for different concepts in the same model, e.g. use a light shaded color for the happy path and use groups to structure the process by stages/places/involved external services etc.

**Comment by nikku** [comment]
Got it. Thanks for your feedback.

**Comment by Kirrrr** [comment]
Groups are one of three basic artifats of BPMN standard. They are not exotic at all. To have no support of Groups is to not conform the standard.

Additionally, most of alternative BPMN modeling tools (e.g. wide spreaded free Bizagi Modeler) do have Gropups and some additional means (like colors or pool milestones) for designating general structure of process and these means don't seem to be excessive or inconsistent.
With such environment Comunda BPMN Modeller is looking slightly faded.

**Comment by nikku** [comment]
Thanks for your feedback. We'll support groups eventually, I'm pretty sure of that.

**Comment by StephenOTT** [comment]
Any update on this?  I am looking to use this to supoort adding security rules on Bpmn execution. So someone can create a group over multiple elements and write security rules such as "who ever starts the first task of this group must be the user who does all the tasks". Or "the user who does task 1 cannot be the user who does any other task in the group"

This would be implemented as a parse listener on the engine show de that would find the groups and find the tasks in the groups and apply the configs to the Bpmn based on the group properties/extensions.

**Comment by pinussilvestrus** [comment]
We are currently planning to implement groups in our next milestone. Exactly today we started to define the tasks on this topic 🙂

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1404. 

:tada:

**Comment by pinussilvestrus** [comment]
❤️

**Comment by StephenOTT** [comment]
@nikku is there any docs on how this was implemented and intended to be used?  Does a group has the ability to detect/know what objects are within it?  Does Camunda engine have this parsing capability ?

**Comment by nikku** [comment]
Groups are visual only at the moment. We do not maintain categorized elements at the moment.

Please open an additional feature request, clearly making your case for that enhancement if you would like us to look into it, some day maybe.

**Comment by StephenOTT** [comment]
@nikku I originally did this in the original issue as above.... https://github.com/camunda/camunda-modeler/issues/464#issuecomment-476661202
