### ISSUE TITLE
Modeler creates invalid `Job Worker` type user task

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4648]
### Describe the bug

Zeebe user tasks are the standard, and job worker type user tasks are completely removed from Camunda 8.7+. We initially [solved this through linting](https://github.com/camunda/product-hub/issues/2126#issuecomment-2446685106), however the default user task created still is of type "job worker". This means I always receive an error initially, and always manually need to  switch to Zeebe User Task everytime I create a new user task. 

This is not a friendly user journey:

![capture CMfhOu_optimized](https://github.com/user-attachments/assets/91cd357b-ce43-458b-9bc2-4f1e4cf18bf3)

### Steps to reproduce

1. Create user task
2. See error (in 8.7), "not supported"
3. Change to Zeebe user task, so everything is good

### Expected behavior

I expect that I'm not bothered with random error messages, when my clear intention is to 

(1) just model a user task (no implementation)
(2) implement a user task for a modern Camunda version, where I expect Zeebe Usertask to be the default

We need to investigate if "just modeling" a user task (not attaching any form) is an acceptable scenario; in the past we received back-preasure trying to mark user tasks without a form as an error. In that case I'd expect to not see any error, too.

### Environment

- OS: Any
- Camunda Modeler Version: v5.29.0
- Execution Platform: Camunda 8
- Installed plug-ins: None

### Additional context

Related to [this converstion](https://camunda.slack.com/archives/GP70M0J6M/p1730281952981719?thread_ts=1730185382.562069&cid=GP70M0J6M), and [follow-up](https://camunda.slack.com/archives/GP70M0J6M/p1730284150150019?thread_ts=1730185382.562069&cid=GP70M0J6M).

----

Related to https://github.com/camunda/product-hub/issues/2126

Related to https://github.com/camunda/product-hub/issues/2126#issuecomment-2432323017

**Comment by nikku** [comment]
CC @volodymyr-melnykc

**Comment by nikku** [comment]
Will be tackled as part of https://github.com/camunda/product-hub/issues/2126 by @camunda/hto-frontend.

**Comment by Skaiir** [comment]
This is fixed upstream in `camunda-bpmn-js-behaviors@1.8.0`
