### ISSUE TITLE
Filepicker component not valid for Tasklist

### ISSUE THREAD

**Issue by okaeiz** [camunda/camunda-modeler#4660]
### Describe the bug

I got [camunda-modeler](https://github.com/camunda/camunda-modeler) v5.30.0-dev and noticed it had a Filepicker component for forms. I also updated my [camunda-platform](https://github.com/camunda/camunda-platform) to its latest version (8.6+gen3 if I am not mistaken) and tried the newly-added component in a form. I could deploy it but Tasklist did not recognize the component and raised the following error:
> Invalid form schema

Is it not stable or I am doing wrong?

### Steps to reproduce

1. Clone and build Camunda Modeler v5.30.0-dev
2. Update Camunda platform
3. Create a form including a Filepicker component and assign it to a user task in your process
4. Deploy the process and form
5. Try to start the process in Tasklist

### Expected behavior

I expect every component in Modeler to be valid in Tasklist

### Environment

- OS:Windows 10, WSL 
- Camunda Modeler Version: 5.30.0.-dev
- Execution Platform: Camunda 8 Self-Managed

**Comment by nikku** [comment]
@okaeiz The guidance (which [albeit can be improved](https://github.com/camunda/camunda-modeler/issues/4646)) should note that this is not compatible with 8.6, try with 8.7-alpha.1 :slightly_smiling_face:.

---

![capture TcgadK_optimized](https://github.com/user-attachments/assets/a929fc19-1ffb-437b-bc92-22224cdc6f4b)

**Comment by okaeiz** [comment]
I think you misunderstood the issue. The problem is not with Modeler. The error is raised in Tasklist and I am already using the latest version which is apparently [8.6+gen3](https://github.com/camunda/camunda-platform/releases/tag/8.6%2Bgen3).

If the latest released version of Tasklist is not compatible with the newly-added component, I don't know why a new form component would be implemented.

**Comment by nikku** [comment]
@okaeiz You should be able to use the upcoming 8.7-alpha-1 version once it is released.

**Comment by nikku** [comment]
I also suggest you to wait for update notifications from the modeler, as we'll role out changes across our tools in an aligned fashion. If you subscribe to GitHub releases (which you probably did), then you may be early to the new things party :cake:

**Comment by okaeiz** [comment]
> @okaeiz You should be able to use the upcoming 8.7-alpha-1 version once it is released, which is in one week from now.

Thank you for the response. Genuinely looking forward to it. I'd be grateful if you take a look at other useful components as well, such as the [datepicker](https://github.com/camunda/camunda-modeler/issues/4308) we discussed before.
