### ISSUE TITLE
External file change reload dialog opened multiple times

### ISSUE THREAD

**Issue by ricardomatias** [camunda/camunda-modeler#468]
- Open an existing file (f.ex bpmn)
- Edit it on a text editor
- Go back to the modeler
- Reload dialog should be there
- Focus another application (like the text editor)
- Focus again the camunda modeler

Results:
- Opens a new external file change dialog, everytime it focuses the modeler

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1150.

**Comment by nikku** [comment]
@pinussilvestrus

**Comment by pinussilvestrus** [comment]
No, it's not. #1150 also revealed to fix this. Tested it under MacOS 10.14 + Windows 8.

**Comment by pinussilvestrus** [comment]
Maybe someone can double check it on Linux again.

**Comment by nikku** [comment]
Closed via #1150.
