### ISSUE TITLE
Duplicated deprecation report for user task implemented as job worker

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4718]
### Describe the bug

A single user task with implementation "job worker" triggers two linting reports:

![image](https://github.com/user-attachments/assets/e4b1899d-8576-46f6-a095-cf6198f5c16d)

### Steps to reproduce

1. Create a user task
2. Set execution platform to Camunda 8.7
3. now this happens

### Expected behavior

Single report, or even no report since there was a decision to postpone deprecation of job worker implementation.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.30.0-rc.0
- Execution Platform: C 8.7
- Installed plug-ins: [...]

**Comment by philippfromme** [comment]
For some reason the second one is reported the `task-listener` rule which doesn't seem to make any sense.

![image](https://github.com/user-attachments/assets/0bc110c6-4c10-42fd-b806-ad1f0e8051c2)

**Comment by philippfromme** [comment]
The `task-listener` rule [reports missing `zeebe:UserTask` extension elements](https://github.com/camunda/bpmnlint-plugin-camunda-compat/commit/5e72cc83976ec9ef7f13c149a6dc0850e7a76251#diff-1af4e5745a4bd28006cc439827945981ff1ecc2825a38c896c3c12353c1a8dd8R23). It's supposed to report an error only if there is a task listener without it being a Zeebe user task. It currently doesn't work like that. The respective test case is broken: https://github.com/camunda/bpmnlint-plugin-camunda-compat/commit/5e72cc83976ec9ef7f13c149a6dc0850e7a76251#diff-d5248d13c56ad890a6422c34bdd0acbf09123180008ce3451a328afaf2c6b22fR31

**Comment by barmac** [comment]
Thanks for the insight @philippfromme.

**Comment by barmac** [comment]
This will be fixed via https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/182

**Comment by barmac** [comment]
Fixed upstream in https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/182, and pending linting release.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/4724
