### ISSUE TITLE
Resing of an external label  with text readjusting 

### ISSUE THREAD

**Issue by DevAutomationInf** [camunda/camunda-modeler#4725]
### Problem you would like to solve

It is not possible to resize the external text label of elements such as groups, start events, flows, etc., and readjust the text position when the label box is resized. 

### Proposed solution

When the external label of a group, start event, or flow is resized, the text should readjust according to the box size. It should behave like the label of a task element, for example.

### Alternatives considered

I tried to achieve this by extending the RuleProvider and the BaseRenderer with no success. See https://stackblitz.com/~/github.com/DevAutomationInf/bpmn-angular?file=src/app/custom/custom-renderer.ts:L12-L62

### Additional context

In this stackblitz [example ](https://stackblitz.com/~/github.com/DevAutomationInf/bpmn-angular?file=src/app/custom/custom-rules.ts:L4) I am extending the RuleProvider to apply the resizing, but I see the following issue, the text doesn’t readjust based on the box size:
![9ba26x](https://github.com/user-attachments/assets/ddbe49ea-a6f6-4313-9348-2a418154cd52)

I tried to obtain the readjusting of text by extending the BaseRender without success ( see [stackblitz](https://stackblitz.com/~/github.com/DevAutomationInf/bpmn-angular?file=src/app/custom/custom-renderer.ts:L39)). It seems like the text is readjusted according to the box but only when the box is moved and not when resized. That is because only in this case the drawShape is triggered. Also, when the drawShape method is called again, the text positioning is changed, making it impossible to predict the behavior.

![readjust-text](https://github.com/user-attachments/assets/b96d3054-2bcc-4caa-aa5a-fc7442c3c164)

**Comment by barmac** [comment]
Hi, thanks for opening the issue. Is this a proposal for a solution in Camunda Modeler, or a request for help with your integration? I can see "resizable labels" as a valid feature request, especially given that BPMN allows it.

**Comment by barmac** [comment]
In order to publish to the forum, you need to spend some time reading. Perhaps somebody has already solved your problem before? Why don't you try to search for it?

> If it is possible to obtain this result by making the customization in my project, then help with my integration would be enough.

Given that, I will close the issue as not planned. If there are more requests for resizable labels, we can always reopen.

**Comment by DevAutomationInf** [comment]
Hello, barmac! Thank you for the information. I didn't find a solution for my question in the forum. What are the exact requirments in order to be able to ask a question on the formum?

**Comment by barmac** [comment]
Spend some time, read a few topics with comments. I don't want to reveal the details.

**Comment by DevAutomationInf** [comment]
Ok, thank you for the information.
