### ISSUE TITLE
Cannot define condition for conditional start event

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda-modeler#473]
__Environment__

Camunda Modeler 1.5.0

__Expected Behavior__

* [ ] I can maintain `camunda:variableName` and `camunda:variableEvents` for conditional start events inside event subprocesses

**Comment by meyerdan** [comment]
Note: should only be added for start events of event subprocesses

**Comment by nikku** [comment]
Updated the issue according to your comments. Thanks for reporting.

**Comment by philippfromme** [comment]
Can't reproduce using Camunda Modeler 1.5.0

**Comment by nikku** [comment]
![image](https://cloud.githubusercontent.com/assets/58601/21770217/9ccb26c6-d682-11e6-9935-ac3e3cf123d1.png)

Already implemented, as @philippfromme and seen in the screenshot above.

**Comment by ThorbenLindhauer** [comment]
Ah, I see. Actually, if the containing sub process is an event sub process, then I can edit the condition, too. If the containing sub process is not (yet) an event sub process, I am allowed to morph the start event to conditional, but cannot edit the condition. Is that intended?

![snippet](https://cloud.githubusercontent.com/assets/586648/21848219/0d3c4d12-d800-11e6-9077-745406345265.PNG)

**Comment by nikku** [comment]
Yes, that is intended.

The BPMN supports Conditional Start Events, also top-level. It is just not supported by Camunda (including the extensions).

**Comment by ThorbenLindhauer** [comment]
It's not a top-level start event here, though. Is non-event sub process with conditional start event indeed valid BPMN? What are its semantics?

**Comment by nikku** [comment]
Well, that should not be allowed. Good point.

**Comment by nikku** [comment]
Cf. https://github.com/camunda/camunda-modeler/issues/498
