### ISSUE TITLE
File Picker and Camunda 7

### ISSUE THREAD

**Issue by guilhermep** [camunda/camunda-modeler#4733]
### Describe the bug

When trying to view a form containing a file picker in Camunda 7.22, the following error message is shown:

> Form failure: form field of type &lt;filepicker&gt; not supported

Is Camunda Modeler failing to flag file picker as not supported by v7.22? The latest version being flagged as a problem is 7.20: 

> A `<Filepicker>` is not supported by Camunda Platform 7.20

### Steps to reproduce

1. Deploy a form with a file picker to Camunda 7.22
2. The error message is displayed instead of the form

### Expected behavior

The form is displayed.

### Environment

- OS: Windows 11
- Camunda Modeler Version: 5.30
- Execution Platform: Camunda 7

**Comment by barmac** [comment]
This is `fixed upstream` via https://github.com/camunda/form-linting/pull/111, and will be fixed in the next Modeler release (probably 5.31)
