### ISSUE TITLE
Rename instances of `Zeebe user task` to `Camunda user task`

### ISSUE THREAD

**Issue by Skaiir** [camunda/camunda-modeler#4749]
### What should we do?

We should rename all textual instances of `Zeebe user task` to `Camunda user task`. We do not have to change how they are defined in the code however.

What this comes down to in practice is that we need to change:
- [x] `camunda/linting` message instances that include zeebe user task
- [x] properties panel entry

### Why should we do it?

This is a company wide renaming of the user task type. 

The product hub epic is here: https://github.com/camunda/product-hub/issues/2126 and decisions are traceable there if you're interested.

**Comment by barmac** [comment]
We need to adjust the tooltips yet (https://github.com/camunda/camunda-bpmn-js):

![image](https://github.com/user-attachments/assets/f5c6e757-33a5-4407-9736-c7e3f8386214)

**Comment by barmac** [comment]
This is now fixed upstream.
