### ISSUE TITLE
Annotations should not be resized on import

### ISSUE THREAD

**Issue by vkatushenok** [camunda/camunda-modeler#475]
__Environment__

Camunda Modeler 1.5

__How to reproduce__
- Import diagram with annotations that have lines wrapping inside bounding box
- Annotation has been automatically resized and lines are not wrapped anymore

__Expected__
- Annotation should look same was, as during initial imprort

See [original post](https://forum.camunda.org/t/cant-resize-annotations/2155) for details.

__Notes__

From usage perspective better behaviour would be to resize bounding box and update DI only on edit. On import - use existing DI width and height information.

**Comment by nikku** [comment]
Needs to be addressed via https://github.com/bpmn-io/bpmn-js/issues/634 and https://github.com/bpmn-io/bpmn-js/issues/628.

**Comment by nikku** [comment]
Reverted the broken automatic text annotation resizing feature. Will be released as part of the next Camunda Modeler patch release.
