### ISSUE TITLE
Syntax highlighting for embedded Scripts

### ISSUE THREAD

**Issue by The-Crocop** [camunda/camunda-modeler#480]
It would be awsome to have syntax highlighting inside the camunda modeler  when writing scripts.
Using some library like https://github.com/ajaxorg/ace could maybe be integrated.

Additionally a button to open an external editor for those scripts would be neat.

If someone gives me some hints I could try to make a PR

**Comment by philippfromme** [comment]
dmn-js doesn't aim to be a full-fledged code editor. For script editing there are much better alternatives (Atom, VS Code, Sublime Text...).
