### ISSUE TITLE
Make <camunda:field> configurable with Element Templates

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#483]
__Task__

* [ ] [Field Injections](https://docs.camunda.org/manual/7.6/user-guide/process-engine/delegation-code/#field-injection) can be configured via element templates
* [ ] Feature is [documented](https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates)
* [ ] [Example](https://github.com/camunda/camunda-modeler/blob/master/resources/element-templates/samples.json) is updated with `camunda:field` configuration

---

See [forum thread](https://forum.camunda.org/t/custom-properties-in-element-template-for-service-task-field-injections/2199/4).

**Comment by galenhollins** [comment]
See also comment about potential support for `<camunda:property>` here:

https://forum.camunda.org/t/custom-properties-in-element-template-for-service-task-field-injections/2199/11?u=galen_hollins

**Comment by nikku** [comment]
@felix-mueller Are you interested in closing this task, too? Would require adding documentation as well as updating our example element template config (see tasks in issue description for links).

**Comment by felix-mueller** [comment]
@nikku sure, I can try to do this, too

**Comment by nikku** [comment]
Thanks for your contribution.
