### ISSUE TITLE
Increase image resolution for exported PNGs

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#486]
Users want to embed images and print them to wall papers. For that to happen the images need to be exported with a much higher resolution (at least 600dpi).

**Comment by benhoffmann** [comment]
It would be really cool if a user could specify the default resolution somewhere as a global setting. If the standard resolution is too high then image file size can get pretty big. 

As a workaround, I always export svg and export the png with the resolution I need with Inkscape.

**Comment by nikku** [comment]
Exporting with higher DPI may be possible, making the DPI configurable is not an easy pick and out of scope of this issue.

Any ideas for a specific DPI / scale factor that may be a better default (current is 96dpi).

**Comment by mburke84** [comment]
Linked Support Issue: https://app.camunda.com/jira/browse/SUPPORT-3540

**Comment by mburke84** [comment]
Linked Support Issue: https://app.camunda.com/jira/browse/SUPPORT-3540
