### ISSUE TITLE
[spike] Copy implementation details

### ISSUE THREAD

**Issue by ricardomatias** [camunda/camunda-modeler#487]
What's needed:
- A list of which properties from each element do we want to copy/paste
- (morphing, A -> B) A kind of mapping which makes it easier to know if element B can have the properties of element A.

Possible solutions:
- A man in the middle (cloning service), could help with having one place where copy/replace details (properties) is defined.

__Hints__

* What is applicable to which element is defined in the [Camunda Extension reference](https://docs.camunda.org/manual/7.6/reference/bpmn20/custom-extensions/).

__Initial Tasks__

When morphing...

* [x] a `UserTask` to a `ServiceTask` the `camunda:asyncBefore` property is preserved
* [x] a `UserTask` to a `ServiceTask` the `camunda:assignee` property is ditched
* [x] a `UserTask` into a `ServiceTask` the `bpmn:Documentation` is preserved
* [x] a `UserTask` into a `ServiceTask` the `camunda:formData` extension element is ditched
* [x] a `UserTask` into a `ServiceTask` the `camunda:executionListener` extension elements are preserved
* [x] Nested element, i.e. `camunda:inputOutput` are taken over including child elements, if applicable

**Comment by ricardomatias** [comment]
Possible kind of mapping below (properties that are not nested, can also just be omitted from it)

```
ELEMENTS: {
  "type": "bpmn:ServiceTask",
  "properties": [
    "async",
    "asyncBefore",
    "asyncAfter",
    "isForCompensation",
    "camunda:ExecutionListener"
  ],
  "type": "bpmn:UserTask",
  "properties": [
    "async",
    "asyncBefore",
    "asyncAfter",
    "isForCompensation",
    "jobPriority",
    "camunda:ExecutionListener",
    "camunda:TaskListener"
  ]
}

PROPERTIES: { 
  "async": "value",
  "asyncBefore": "value",
  "asyncAfter": "value",
  "isForCompensation": "value",
  "jobPriority": "value",
  "camunda:ExecutionListener": { 
    "type": "extensionElements",
    "values": [
      { 
        "type": "camunda:ExecutionListener",
        "properties": [ "class", "event" ]
      }
    ]
  },
  "camunda:TaskListener": { 
    "type": "extensionElements",
    "values": [
      { 
        "type": "camunda:ExecutionListener",
        "properties": [ "class", "event" ]
      }
    ]
  }
}
```

**Comment by nikku** [comment]
```xml
<bpmn>
  
  // (1) how to know whether attributes can be taken over?
  <bpmn:process camunda:asyncBefore="true">

    // (2) be able to take over documentation extension
    <!-- // (2.1) other BPMN attributes to preserve ? -->
    <bpmn:documentation>
      FOASDDSADSDSAASD
    </bpmn:documentation>

    <bpmn:documentation>
      FOASDDSADSDSAASD
    </bpmn:documentation>

    <bpmn:extensionElements>
      // (3) how to know whether to take over camunda extension elements
      // (3.1) how to copy / recreate nested extension elements ?
      <camunda:inputOutput>
        <camunda:in name="foo" value="bar" />
        <camunda:in businessKey="true" />
      </camunda:inputOutput>
    </bpmn:extensionElements>
  </bpmn:process>
</bpmn>
```
