### ISSUE TITLE
It should not be possible to model inputOutput mappings for gateways

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#491]
Right now we are able to model `camunda:inputOutput` on gateways. This is not allowed by the engine and results in an error during deployment.

Gets addressed by https://github.com/bpmn-io/bpmn-js-properties-panel/issues/221.

**Comment by pinussilvestrus** [comment]
Waiting for pending properties panel release, cf. https://github.com/bpmn-io/bpmn-js-properties-panel/commit/a7b5d7bfe2fd599f85a942d42eef8e1570a15ae0

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1468.
