### ISSUE TITLE
Modeling DRG breaks diagram

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#492]
__Problem__

The Camunda Modeler removes empty Description and Text tags inside a rule definition. This results in invalid BPMN 2.0 being saved. Engine parser complains that Description and Text are expected.

_Original Snippet_

```xml
      <rule id="row-365404946-15">
        <description></description>
        <inputEntry id="UnaryTests_1aoyo3z">        <text></text>
</inputEntry>
        <inputEntry id="UnaryTests_0baiv0h">        <text></text>
</inputEntry>
        <inputEntry id="UnaryTests_0jskwjn">        <text><![CDATA["Java", "C", "C-Sharp", "Python", "JavaScript"]]></text>
</inputEntry>
        <outputEntry id="LiteralExpression_0qzfffu">        <text><![CDATA["Douglas Adams"]]></text>
</outputEntry>
      </rule>
```

_Saved Snippet_

```xml
  <rule id="row-365404946-15">
    <inputEntry id="UnaryTests_1aoyo3z" />
    <inputEntry id="UnaryTests_0baiv0h" />
    <inputEntry id="UnaryTests_0jskwjn">        <text><![CDATA["Java", "C", "C-Sharp", "Python", "JavaScript"]]></text>
</inputEntry>
    <outputEntry id="LiteralExpression_0qzfffu">        <text><![CDATA["Douglas Adams"]]></text>
</outputEntry>
  </rule>
```

__Expected__

* [ ] Rules get serialized in a BPMN 2.0 compliant way; diagram can be deployed to engine after modification.

__Reproduce__

Use the following files to reproduce the issue (source: https://github.com/bpmn-io/moddle-xml/issues/18#issuecomment-270769424). 

- [diagram_1 - step2.txt](https://github.com/bpmn-io/moddle-xml/files/688474/diagram_1.-.step2.txt)
- [diagram_1 - step1.txt](https://github.com/bpmn-io/moddle-xml/files/688463/diagram_1.-.step1.txt)

---

Related to https://github.com/bpmn-io/moddle-xml/issues/18, [forum post](https://forum.camunda.org/t/modeller-breaks-drg/2347)

**Comment by nikku** [comment]
Fixes this in `moddle-xml`.

**Comment by SebastianStamm** [comment]
I can still reproduce the problem in Modeler Release 1.7.2

**Comment by mburke84** [comment]
Linked to SUPPORT-3229

**Comment by nikku** [comment]
Yep, stuff wasn't actually ever released.

Doing that now.

**Comment by nikku** [comment]
Gets released with next Camunda Modeler release.
