### ISSUE TITLE
Keyboard shortcuts are enabled when editing labels on Mac with version 1.6

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#494]
When I edit labels, the global shortcuts get activated. This should not happen because it causes delays while typing.

![jan -10-2017 14-33-41](https://cloud.githubusercontent.com/assets/17595149/21808115/1c75c60a-d742-11e6-9cc5-27a505c24988.gif)

**Comment by ricardomatias** [comment]
This won't be easily fixed. The problem here is that the general shortcuts are triggered (by the OS) before they actually reach to our side of the application.

**Comment by benhoffmann** [comment]
Hm, 

those shortcuts used to be deactivated when one edited labels in previous versions of the modeler.

<img width="735" alt="bildschirmfoto 2017-01-26 um 10 07 19" src="https://cloud.githubusercontent.com/assets/17595149/22325670/6f2a7d54-e3af-11e6-8886-e591d8afa937.png">

**Comment by ricardomatias** [comment]
It will be fixed with the next release. The fix for [#495](https://github.com/camunda/camunda-modeler/issues/495) also fixes this.
