### ISSUE TITLE
Copy and paste does not work on Mac with version 1.6

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#495]
I can't copy text into property panel text boxes or labels anymore 😭

Copy and paste of elements still works, though.

![jan -10-2017 14-41-25](https://cloud.githubusercontent.com/assets/17595149/21808281/f55398da-d742-11e6-9e82-2d469984ccb1.gif)

**Comment by felix-mueller** [comment]
It starts working again when you start typing something in the field. After typing suddenly the paste button is available... (Just as a workaround..)

**Comment by RomanTruba** [comment]
@ricardomatias Cmd+A still doesn't work for text.

**Comment by ricardomatias** [comment]
@RomanTruba I'll create an issue for that.

**Comment by vkatushenok** [comment]
Cmd + A fixed under #520
