### ISSUE TITLE
Only blank Start Events should be allowed inside Sub Process (non-event based)

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#498]
As taken from the docs:

![image](https://cloud.githubusercontent.com/assets/58601/21848807/094e12e6-d803-11e6-9d3e-cf41fa13bad0.png)

__Tasks__

* [ ] Transform typed start events to _None_ start events when moving inside sub process
* [ ] Do not allow changing to a typed start event using the replace menu (wrench)

**Comment by benhoffmann** [comment]
Also, only a single none start event is allowed I think.

**Comment by nikku** [comment]
Needs to be addressed via https://github.com/bpmn-io/bpmn-js/issues/831.

**Comment by barmac** [comment]
Fixed via https://github.com/camunda/camunda-modeler/pull/1903 (bpmn-js update).
