### ISSUE TITLE
I can configure a cycle duration for a Timer Intermediate Catching Event

### ISSUE THREAD

**Issue by mburke84** [camunda/camunda-modeler#501]
Currently, it is possible to define a cycle duration for a timer intermediate catching event. However, this doesn't make sense because a timer intermediate catching event should only be triggered once. When it is triggered the first time, execution continues beyond the event. When it is triggered for the second time, there is no token waiting at the event.

![grafik](https://cloud.githubusercontent.com/assets/7465644/21894647/3660186e-d8e0-11e6-9005-6145c0bf67e9.png)

Cheers

**Comment by nikku** [comment]
We'll revert this change in a future version of the Modeler, as there is an actual use-case for cycle(s). Cf. [this issue](https://github.com/camunda/camunda-modeler/issues/792#issuecomment-384652043) for more details.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/792#issuecomment-384652043.
