### ISSUE TITLE
CMMN formKey invisible after reopening file

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#502]
Add a formKey to a user task in CMMN, close the model and reopen it. The formKey is correct in the XML, but not shown in property panel. Readding the property results in a duplicate XML attribute which is rejected by the engine parser. 

Tested in 1.5.1, 1.6.0, 1.7-nightly

**Comment by falko** [comment]
My current customer is affected by this.

**Comment by mschoe** [comment]
I cannot reproduce this issue with version 1.8.2.
