### ISSUE TITLE
Correct ApplicatIon Logo

### ISSUE THREAD

**Issue by SimGra** [camunda/camunda-modeler#503]
![image](https://cloud.githubusercontent.com/assets/8511238/21954904/1d067f90-da5f-11e6-941b-f6fd16028df0.png)

I think someone mixed something up.

__Tasks__

* [ ] Fix Camunda Modeler Icon to match [camunda.org](https://camunda.org/), [bpmn.io](https://bpmn.io/)

**Comment by nikku** [comment]
Yes, good catch!
