### ISSUE TITLE
Add more color and/or allow arbitrary colors

### ISSUE THREAD

**Issue by instinct-vfx** [camunda/camunda-modeler#510]
Would be helpful to have more colors or to be able to set arbitrary colors.

For example i often use color to group items and shades to differentiate within the same "group".

If arbitrary colors is not an option it would be good to have multiple shades per color. Also having some more colors would be good. I tend to avoid red and green as that is often misinterpreted as "good vs. bad" or "unimportant vs. critical". That leaves me with 3 colors and that's not really enough for me.

**Comment by nikku** [comment]
> I tend to avoid red and green as that is often misinterpreted as "good vs. bad" or "unimportant vs. critical".

Agreed.

> If arbitrary colors is not an option it would be good to have multiple shades per color. 

Sounds good.

In the spirit of keeping things simple, we started with only a few colors. Feel free to propose an alternative palette, including a few shades. We are open for proposals on a better color palette!

**Comment by instinct-vfx** [comment]
I will think about it a bit, but the first thing that came to mind was original ansi colors, select a pretty vibrant main color and then have one or two shades up and one or two shades down for each. By the way i would also prefer to eventually have different colors for the labels as they get hard to read for some colors (like orange). Will try and come up with a proposal for the palette first.

P.S. that was a crazy fast reply there :)

**Comment by instinct-vfx** [comment]
Sorry for the long delay here. Got carried away for a bit here. I thought about this some more and i think something that spans the spectrum more or less and some shades of it (maybe normal/bright/dark?) I looked around a bit and found this quite nice:

http://colrd.com/palette/26730/

It's not a plain spectrum and the colors are more pleasing. Also available as CSS directly so i don't need to type a lot ;)

**Comment by instinct-vfx** [comment]
So i played with it a little and made a quick local patch. It became apparent that it would be really beneficial to be able to set text and border color independently. I am not sure how much effort that would be though. Anyways. I took the following palette and used the middle three colors per color range. http://colrd.com/palette/28419/

It probably would need some tweaking but gives an idea. I kept the current green and red ones so they could be used as "good/success" vs "warning/errors" besides the other colors.

![image](https://user-images.githubusercontent.com/243828/28011349-4d7451f0-6562-11e7-94ea-775d23cbdadb.png)

**Comment by falko** [comment]
There is a [Color Picker Plugin](https://github.com/camunda-consulting/code/tree/master/snippets/camunda-modeler-plugins/bpmn-js-plugin-color-picker) with support for arbitrary colors.

**Comment by lldata** [comment]
More colors would be nice. We use it to communicate which systems/teams our main process hits.

I think we could make due with just six more light colors. 
Since we want the elements to be consistently colored a arbitrary color picker is not that useful.

It would be cool though, if the default palette could be customized (and stored) in the bpmn file.

**Comment by nikku** [comment]
We'll not follow up on this one.

Adding advanced color pickers can be done via our plug-in system.
