### ISSUE TITLE
Copy and Paste not working for any text based fields

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#521]
The copy and paste appears to be very buggy in any text fields.  Text wont copy. text wont paste from another app or within the modeler

MacOS
Modeler: Version 1.6.0 (1483441347)

**Comment by StephenOTT** [comment]
Seems you have to hit enter a few times to add whitespace and then you can paste....

**Comment by nikku** [comment]
Duplicate of https://github.com/camunda/camunda-modeler/issues/495?

**Comment by StephenOTT** [comment]
@nikku ah yes!  I searched for "copy" but did not look in closed issues.
