### ISSUE TITLE
ConditionalEventDefinition created with out condition leads to invalid BPMN 2.0 XML

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#526]
`bpmn:ConditionalEventDefinition` is only valid with an attached condition. Right now, we do not attach it on creation and produce invalid XML (according to the BPMN 2.0 XML schema.

__Expected__

* [x] We attach an empty `bpmn:FormalExpression` element so that the generated BPMN 2.0 XML is schema compliant

**Comment by nikku** [comment]
Will be addressed via https://github.com/bpmn-io/bpmn-js/issues/747.

**Comment by philippfromme** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/1f5c69a58bfea6a3fbdd3e07c60c040f744ed553.

**Comment by philippfromme** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/1f5c69a58bfea6a3fbdd3e07c60c040f744ed553.
