### ISSUE TITLE
Ability to lock or not as easily move a pool?

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#528]
The way pools are moved as of 1.6.0 mean that whenever you are zoomed in on a process and you need to move on the canvas, you end up moving the pool rather than transversing the canvas.  This can be avoided by using the hand tool, but a user can to manually switch into this.  Is there a way to avoid this by allowing a user to click and drag on white space of a pool?  Maybe only allow a pool to be moved if you are selected on the left side in the pool name?  Would be a huge convenience

Thanks

**Comment by nikku** [comment]
There is the `h` shortcut that allows you to toggle the hand tool quickly.

Other than that, yes, having some modifier to use the hand would definitely be a big convenience.

**Comment by StephenOTT** [comment]
ya have been using `h`, but it is not intuitive once you are "trained" to click and drag on white space ;P

**Comment by StephenOTT** [comment]
This is also a common problem when dealing with large pools.  you quickly forget that you are inside of a pool when zoomed in.

**Comment by StephenOTT** [comment]
@nikku any further thoughts on this?  It is a MAJOR ux problem when working with larger pools and you zoom in.  Having to remember to use `h` is a constant problem.

**Comment by philippfromme** [comment]
I would also love to have this feature. Gonna look into this.

**Comment by nikku** [comment]
I guess this is addressed via https://github.com/camunda/camunda-modeler/issues/629? People should not be required to drag the canvas on pools anymore.
