### ISSUE TITLE
Using "Undo" to remove a pool shifts all lables right

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#530]
When you add a pool to a model and then use Ctrl+Z to undo it all of the labels on the elements are shifted to the right and pretty much get stuck that way. 

![removepoolproblem](https://cloud.githubusercontent.com/assets/10612634/23159273/7817a84c-f822-11e6-8ca3-3be542a17356.gif)

**Comment by nikku** [comment]
Should be fixed in v1.7.2.
