### ISSUE TITLE
dmn-js performance issues when working with big decision tables

### ISSUE THREAD

**Issue by vkatushenok** [camunda/camunda-modeler#531]
When working with decision tables with hundrets of rules dmn-js becomes painfully slow. Working with such decision tables is practically impossible.

See related [dmn-js ticket](https://github.com/bpmn-io/dmn-js/issues/202).
See support [ticket](https://app.camunda.com/jira/browse/SUPPORT-3119) and [second ticket](https://app.camunda.com/jira/browse/SUPPORT-3199) for more details.

**Comment by nikku** [comment]
A little bit of context: We're currently investigating a rewrite of dmn-js with focus on performance with large tables. Until that point we cannot improve anything here.

**Comment by bruno-lopes** [comment]
Thanks @nikku. In my opinion this feature is vital.

**Comment by philippfromme** [comment]
We're going to release the first version of the rewritten dmn-js in December. All basic functionality will be included. See the [corresponding dmn-js milestone](https://github.com/bpmn-io/dmn-js/milestone/7) for the features we'll include.

Things we're not going to include in this release:
* drag & drop/copy & paste for rules/inputs/outputs
* simple editing of cells through context menus
* editing of literal expressions

**Comment by mikele** [comment]
Hi Phillipp, that sounds promising! Right now I use dmn.js to visualise a Table with 3 input + 1 output and about 600 Rules - it takes really long to render it...
So I am looking forward to the new Release - some sort of sliding window technique would be great in order to improve rendering performance...
Kind regards,
Michael

**Comment by nikku** [comment]
Prototype shipped with Camunda Modeler `1.12.0-alpha-1`.

**Comment by nikku** [comment]
We're going to release Camunda Modeler `1.12.0` once we got feature parity with the old dmn-js / Camunda Modeler `1.11.x`.

**Comment by nikku** [comment]
Any reason this re-opened?

**Comment by nikku** [comment]
Likely due to https://github.com/bpmn-io/internal-docs/issues/531. Closing again.
