### ISSUE TITLE
Element Template Form

### ISSUE THREAD

**Issue by kjordan2001** [camunda/camunda-modeler#533]
I'd like to be able to create an Element Template for a User Task that automatically has formFields added in when selected. An example of possible syntax:
"properties": [{
"label": "Formfield 1",
"type": "String",
"value": "[predefined value for the formfield]",
"editable": true,
"binding":
{ "type": "camunda:formField", "name": "formFieldId" }
,
"constraints":
{ "notEmpty": true }
}]

**Comment by philippfromme** [comment]
Will not build this anytime soon.

**Comment by philippfromme** [comment]
We're not going to build new Camunda 7 element template features. When using Camunda 8 we recommend using Camunda forms which are not part of the BPMN and can therefore not be supported by element templates.
