### ISSUE TITLE
Mystified sequence flow connection after element drop

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#534]
Reproduce:
Drop element on sequence flow bend point, without element snapping.

Problem:
New sequence flow connection looks ugly.
![sequenceflow_drop_1](https://cloud.githubusercontent.com/assets/2777965/23555899/e5b3ed2e-002a-11e7-8cb2-b8c08ca25728.JPG)

**Comment by pedesen** [comment]
We could always snap elements during drop on flow operations, like proposed here: https://github.com/bpmn-io/bpmn-js/issues/398

We should also consider to always drop on flow, during snapping, which is currently not the case: 

![bla](https://user-images.githubusercontent.com/2543743/27921415-0a07de4c-6278-11e7-9152-04c09c568a7d.gif)

**Comment by hanbar** [comment]
Is it possible to turn off this behaviour completely? So when I drop an element on sequence flow, nothing happens?

**Comment by nikku** [comment]
Unfortunately you cannot simply opt out of it.

What exactly is the issue with this feature?
