### ISSUE TITLE
Lost event definition after morphe from catch to throw (Message, Signal and Link Event)

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#537]
Description applies for Message, Signal and Link Events
Reproduce:
- Add Link Event 
- Add link name
- Morphe event from catch to throw or vice versa

Problem
link name lost

**Comment by nikku** [comment]
Fixed now as https://github.com/camunda/camunda-modeler/commit/2415cf9ba925b1b303923187c3556db468a0db0f / `bpmn-js@5.0.0-beta` are integrated.
