### ISSUE TITLE
Morphed Gateways loose Input/Output and Extension Properties 

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#538]
Reproduce:
- Add Input/Output parameter and extension properties to a gateway
- Morphe gateway to another type

Problem:
Input/Output parameter and extension properties lost

**Comment by nikku** [comment]
The following properties are now kept as https://github.com/camunda/camunda-modeler/commit/2415cf9ba925b1b303923187c3556db468a0db0f / `bpmn-js@5.0.0-beta` are integrated: 

* extension properties
* listeners

Whether input and output should be kept is not clear. Based on the [offical Camunda extension docs](https://docs.camunda.org/manual/7.11/reference/bpmn20/custom-extensions/extension-elements/#inputoutput) these are not allowed at all.
