### ISSUE TITLE
Properties lost on replace with send task/copy and paste send task

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#540]
Reproduce:
- Add Listener, Input/Output and Extension Properties to an element
- Morphe element to Send Task

Problem:
Listener, Input/Output and Extension Properties lost

Hints:
Same happens when copying a Send Task

**Comment by metabrain** [comment]
Similar to my issue #679

**Comment by nikku** [comment]
Still an issue in latest stable / nightly.

**Comment by nikku** [comment]
This is fixed via https://github.com/camunda/camunda-modeler/commit/2415cf9ba925b1b303923187c3556db468a0db0f / `bpmn-js@5.0.0-beta`.
