### ISSUE TITLE
Support sorting of xml nodes

### ISSUE THREAD

**Issue by AlexanderYastrebov** [camunda/camunda-modeler#546]
Would be nice to have an option to automatically sort xml nodes based on `(node name, node id)` on save so that change to xml is reviewable via text diff.

**Comment by nikku** [comment]
Right now, we only change what has actually moved. Or is there any place where we changing produces more noise than needed?

**Comment by AlexanderYastrebov** [comment]
For example if I swap two tasks (`-->[task 1]-->[task 2]-->` changed to `-->[task 2]-->[task 1]-->`) then their xml nodes are also swapped and moved within the file. The better way would be if only `<incoming>/<outgoing>` subnodes of respective `<serviceTask>`'s change.

**Comment by AlexanderYastrebov** [comment]
I am using modeller 1.6.0

**Comment by nikku** [comment]
XML elements are sorted on a recently used basis. We don't plan to change this behavior.

We're open to contributions though.
