### ISSUE TITLE
As a developer I can extend the Camunda Modeler with custom modules

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#547]
...so that I can offer my modeling users a customized Modeling interaction.

__Tasks__

* Identitfy extension points
* Implement extension points
* Document extension points
* Create extension example
* Blog about extensibility

**Comment by philippfromme** [comment]
Camunda Modeler Plugin Example: https://github.com/camunda/camunda-modeler-plugin-example
Camunda Modeler Plugins: https://github.com/camunda/camunda-modeler-plugins

Remaining questions:
* [ ] Should we publish https://github.com/camunda/camunda-modeler-plugin-example/blob/master/client/registerClientPlugin.js as a NPM module?
* [ ] Tests for plugins implementation?

**Comment by nikku** [comment]
Regarding your questions:

* How easy can we test that stuff? If easily, write tests where appropriate. Reason: We are providing a contract for others here and should recognize if we break it.
* Regarding helpers for user: Depend on [`camunda-modeler-plugin-helpers`](https://github.com/camunda/camunda-modeler-plugin-helpers) which provides registration endpoints, i.e. `register-bpmn-js-plugin`.
* Regarding stability: We should test how the modeler behaves on malformed plug-ins and try to be as stable as possible here.

**Comment by philippfromme** [comment]
For review:

* [Plugin Implementation](https://github.com/camunda/camunda-modeler/tree/501-minimap)
* [Plugin Example](https://github.com/camunda/camunda-modeler-plugin-example)
* [Plugins Repository](https://github.com/camunda/camunda-modeler-plugins)
* [Plugin Helpers](https://github.com/camunda/camunda-modeler-plugin-helpers)

**Comment by pedesen** [comment]
The tests haven't been executed due to changes in Gruntfile. Some of them are failing: https://travis-ci.org/camunda/camunda-modeler/builds/218808295
