### ISSUE TITLE
Diagram frozen after dropping Element on sequence label - regression

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#548]
Reproduce:
- Drop an element on a a sequence flow label

Problem:
It is not possible to drop the element but after this action I cannot move any element in the diagram

Hint:
Affects sequence flows labels only.

**Comment by mschoe** [comment]
Related to [SUPPORT-3139](https://app.camunda.com/jira/browse/SUPPORT-3139)

**Comment by nikku** [comment]
Released with bpmn-js v0.20.3, to be released with Camunda Modeler.

**Comment by nikku** [comment]
Released with Camunda Modeler 1.7.2.
