### ISSUE TITLE
copy paste from camunda to word as a vector picture

### ISSUE THREAD

**Issue by trozman** [camunda/camunda-modeler#549]
(v1.3.1)Hello,
it would be very helpful, if the camunda modeler would allow copy pasting diagram to word (e.g. as WMF/EMF).
Currently, I export the diagram as SVG, open it with InkScape, Export it as PNG and import it to word. Very lenghty.
Thanks!

**Comment by nikku** [comment]
You know that you can save diagrams as images, too? That should save you from one step in your workflow.

**Comment by trozman** [comment]
Yes, I know. But if I save it as bitmap (JPG or PNG), the resolution is not very good and not appropriate for printed media, e.g. books. 
When I save it as SVG, I render it with InkScape as PNG with 300dpi resolution.  
So, still, 3 steps. It is a little lenghty in case of multiple changes of the diagram. 
Anyway, a great modeller!

**Comment by nikku** [comment]
SVG is vector graphics, too. Isn't it possible to paste SVG into Office Documents?

**Comment by nikku** [comment]
Works in LibreOffice :tada:.

**Comment by trozman** [comment]
Thanks for the hint. Yes, it works in Libre (importing or drag&drop, not copy-pasting). But not in MSOffice, because MsOffice does not support SVG import. If it would, I wouldn't post tickets here :)
Unfortunately, it isn't always feasible to work in LibreOffice, especially because I collaborate in teams where Ms Office is preferred.
