### ISSUE TITLE
Cell dropdown not visible on smaller resolutions

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-modeler#550]
See screenshot: If you use the modeler on a smaller resolution you cannot access the Expression Language Box in the menu. I moved a row up to access it, but then I cannot select JUEL (too far down in the list).

![grafik](https://cloud.githubusercontent.com/assets/1217596/23797924/726b0348-05a2-11e7-93f2-9ff20982c747.png)

**Comment by philippfromme** [comment]
Not an issue in latest dmn-js.
