### ISSUE TITLE
Wrong Connections made when places an element outside a subprocees

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#554]
A sequence flow should not leave a subprocess but you also cannot create an association to an element outside the subprocess. 
![elementfromsubprocess](https://cloud.githubusercontent.com/assets/10612634/24197969/236dc1d4-0f04-11e7-9f09-3f63318e0a5d.gif)

It should refuse to create the element

**Comment by nikku** [comment]
Just curious: An association can be drawn between any elements, right? Or is there any rule that forbids it.

I get the point that it doesn't make sense for users to get this result so :+1: for a fix.

**Comment by NPDeehan** [comment]
You can only draw an association to an Artifact (like a data object)  or a compensation task, but nothing else as far as i know. :)

**Comment by philippfromme** [comment]
Associations can now only connect flow objects with artifacts. As far as I understand and as stated [here](https://www.lucidchart.com/pages/bpmn-symbols-explained) they can only be used for that purpose. Connecting flow objects through associations makes no sense, I think.

**Comment by philippfromme** [comment]
TODO

* [ ] figure out if association between gateway and data object is allowed

**Comment by nikku** [comment]
I would allow it, if we do not get an explicit indication that it isn't.

**Comment by philippfromme** [comment]
Connecting data objects to start events or gateways is not possible currently. Connecting data objects to end events is possible for some reason. I've only ever seen them connected to tasks, though. For now, I would leave it like it is.

**Comment by nikku** [comment]
Let's leave it as it is and wait for feedback.
