### ISSUE TITLE
Camunda modeler should mark processes as executable per default

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-modeler#555]
The most common mistake when starting is to not mark your processes as executable - which typically ends up in minutes or hours of researching the problem.

We should make all processes tickets with "executable=true" per default when creating them. If you do NOT want to have them exectuable you either don't care (because you are not developing for an engine) or you will easily recognize (as Camunda deploys the process). 

This rather small change has a huge positive impact on the getting starting experience.

**Comment by meyerdan** [comment]
+1

________________________________

**Comment by lizergsav** [comment]
I agree as well

**Comment by ThorbenLindhauer** [comment]
But this puts @NPDeehan out of work in the forum ;)

**Comment by falko** [comment]
+1

**Comment by NPDeehan** [comment]
Even with the understanding that this makes my job on the forum obsolete... +1

**Comment by berndruecker** [comment]
Maybe you can still answer questions around "startProcessInstanceByKey"

**Comment by nikku** [comment]
Just to understand it a bit better: What does the engine currently log to the user if...

* A process diagram with 3 process definitions is deployed, one executable
* A process diagram with X process definitions is deployed, non executable

**Comment by ThorbenLindhauer** [comment]
It logs `Ignoring non-executable process with id '{}'. Set the attribute isExecutable="true" to deploy this process.` for every non-executable process definition, regardless how many (non-)executable processes there are in the XML. If part of a process application deployment, it also logs a summary of all deployed definitions, which only includes those that are executable.

**Comment by nikku** [comment]
Good. The only improvement I see is logging that in CAPSLOCK but I guess unless we fail the deployment without executable things in it any warning can easily be ignored.

**Comment by ThorbenLindhauer** [comment]
The above log message is logged on INFO, as it can be intended to have non-executable processes as part of the deployment. Perhaps we should log a WARNING if a bpmn file does contain no executable process. Then again, from my experience there are plenty of people who ignore logs entirely, so this ticket remains valid.

**Comment by berndruecker** [comment]
I agree with Thorben, people are not really reading the log properly

**Comment by falko** [comment]
I agree that logging cannot solve this.

When people try an Open Source software and don't get something running within 5 to 10 minutes they quickly turn away from it. Let's not loose new users by setting up traps like this.

**Comment by nikku** [comment]
Guys, there is no need to discuss this, because everyone agrees on it :wink:.
