### ISSUE TITLE
Multi instance user task with built in form

### ISSUE THREAD

**Issue by aminmc** [camunda/camunda-modeler#556]
Hello,

I have a process model with a user task which has been marked as multi instance. I've added a few form fields to the user task with default ids (for example FormField_2666blb).  The issue is that once i start the process, the engine creates n number of user tasks and each task has the same form id.  This means the each user task overwrites the variable value from the previous user task.  Has anyone encountered this before? Is there a best practice for implementing something like this? 

Thanks

**Comment by Jorntie** [comment]
I have the same issue, did you solved it?
