### ISSUE TITLE
Change the labels on gateways to be on top by default

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#558]
I've realized recently that i almost ALWAYS move the lable on a gateway to the top. Because generally it's best practice to have a task directed ahead of it and the alternative below it. It would be nice if the label above by default
![gateway lable](https://cloud.githubusercontent.com/assets/10612634/24614889/f507adfe-188c-11e7-9e97-7115563686ff.gif)

**Comment by nikku** [comment]
@NPDeehan could you cross post this issue in the [Camunda Forum](https://forum.camunda.org/c/modeler) to gather additional feedback on this topic?

**Comment by NPDeehan** [comment]
Done - https://forum.camunda.org/t/labels-on-gateways-should-default-to-above/3302 
Now i just play the waiting game...

**Comment by nikku** [comment]
This is addressed via adaptive label positioning (https://github.com/bpmn-io/bpmn-js/issues/738).
