### ISSUE TITLE
Pasting same object twice causes ID duplication

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#561]
![copypasteerror](https://cloud.githubusercontent.com/assets/10612634/24922384/152e8a1e-1ebc-11e7-925c-0e8524d3be9e.gif)

When i copy an item and then past multiple copies of it - it seems to maintain the same object ID resulting in some weird behavior.

**Comment by nikku** [comment]
Someone reported the same issue in the [bpmn.io forum](https://forum.bpmn.io/t/copy-then-multiple-paste-problem/1459).
