### ISSUE TITLE
Modeler recognized unchanged files as externally changed

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda-modeler#563]
**Steps to reproduce**
* open two diagrams
* do changes in both diagrams and save
* close Modeler
* open Modeler
* don't change the diagrams
* right click on a tab
* select Close All Tabs

**Problem**
* Dialog appears: "The file has been changed externally. Would you like to reload it?"

**Expected behavior**
* The Modeler should just close all tabs, because the files haven't changed externally.
---
via https://app.camunda.com/jira/browse/SUPPORT-3244

**Comment by philippfromme** [comment]
Can't reproduce reliably on Windows 10. Worked 4 times before bug appeared.
