### ISSUE TITLE
Configured Default Template properties not being shown for bpmn:Process

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#566]
Creating a default template on `bpmn:Process` won't not show the custom fields configured for it.

__Steps to Reproduce__

* Create a template

    ```json
    {
      "name": "Process Extension",
      "id": "a.b.c.d",
      "isDefault": true,
      "appliesTo": [
        "bpmn:Process"
      ],
      "properties": [
        {
          "label": "Stuff",
          "description": "This is a description",
          "type": "String",
          "binding": {
            "type": "camunda:property",
            "name": "stuff"
          },
          "constraints": {
            "notEmpty": true
          }
        }
      ]
    }
    ```

* Set the default template on the Process Level

* Custom Fields not being shown

__Screenshot__

![image](https://cloud.githubusercontent.com/assets/58601/25433180/cc31ff1c-2a87-11e7-875c-ea1fe8d377eb.png)

__Expected__

* Custom fields show for `bpmn:Process`, too

---

Related to [SUPPORT-3265](https://app.camunda.com/jira/browse/SUPPORT-3265).

**Comment by dominikhrn** [comment]
The same applies to the StartEvent, that is generated by default when a process is created.
If I deleted the StartEvent and create it again it works.

**Steps to Reproduce**
Almost same as above:

```
{
    "name": "Standard",
    "id": "com.camunda.event.default",
    "isDefault": true,
    "appliesTo": [
      "bpmn:Event"
    ],
    "properties": [
      {
        "label": "Some Property",
        "type": "String",
        "value": "",
        "binding": {
          "type": "property",
          "name": "someproperty"
        }
      }
    ]
}
```

...

**Screenshot 1**
Before deleting

<img width="323" alt="bildschirmfoto 2017-05-10 um 13 12 38" src="https://cloud.githubusercontent.com/assets/27461050/25895935/602e1156-3582-11e7-8248-41c664a9f741.png">

**Screenshot 2**
After deleting and creating it again

<img width="324" alt="bildschirmfoto 2017-05-10 um 13 20 27" src="https://cloud.githubusercontent.com/assets/27461050/25896264/c05374ee-3583-11e7-8169-6db5ff8922f4.png">

**Comment by nikku** [comment]
With this fix, you can now apply the default template for elements that are imported blank, i.e. the start event and the process that are created when you specify _create new BPMN diagram_.

These won't automatically be touched and get the default template applied though.

This is due to the fact that we generally do not perform any magic on diagram open.

You can inspect the changes in the [latest nightly](https://camunda.org/release/camunda-modeler/nightly/).
