### ISSUE TITLE
Zooming on minimap by pinching zooms whole application

### ISSUE THREAD

**Issue by vkatushenok** [camunda/camunda-modeler#568]
Camunda Modeler Version: 1.8.0

![kapture 2017-05-04 at 11 19 04](https://cloud.githubusercontent.com/assets/2331533/25697515/88b54bd8-30bb-11e7-808b-643b68f9b41d.gif)

**Comment by nikku** [comment]
May need to prevent default on pinching.

**Comment by philippfromme** [comment]
Fixes it: https://github.com/electron/electron/blob/master/docs/api/web-frame.md#webframesetvisualzoomlevellimitsminimumlevel-maximumlevel

**Comment by nikku** [comment]
Is this still an issue?
