### ISSUE TITLE
File change detection does not work for BPMN and CMMN (DMN works)

### ISSUE THREAD

**Issue by vkatushenok** [camunda/camunda-modeler#569]
Camunda Modeler Version: 1.8.0

Also changes are ignored when re-opening closed tab.

**Comment by nikku** [comment]
Works on Linux.

It seems however that the general file change detection is somewhat broken.

* We check for changed files on app re-open 
* We check for file change on tab re-open

In both cases, I'd expect the new version of the diagram to just get opened.

**Comment by nikku** [comment]
Related to #563

**Comment by nikku** [comment]
Should be fixed via #563?

**Comment by nikku** [comment]
Cannot reproduce anymore.
