### ISSUE TITLE
Application should quit completely when explicitly chosen in the dock menu

### ISSUE THREAD

**Issue by vkatushenok** [camunda/camunda-modeler#570]
Camunda Modeler Version: 1.8.0

Works in menu but not in the dock.

__Steps to Reproduce__

*  Open Modeler
* Via dock, close app
* App windows are closed but app itself is still opened; need another close to actually close it

__Expected__

* [ ] Closing via dock closes all windows _and_ quits the app

**Comment by nikku** [comment]
@pinussilvestrus Is this still an issue with `v3.0.0`?

**Comment by pinussilvestrus** [comment]
Yes, it is.

**Comment by barmac** [comment]
This is not an issue anymore. Not sure when it was fixed.
