### ISSUE TITLE
Closing modeler with unsaved changes for existing diagram would not reopen it on next launch

### ISSUE THREAD

**Issue by vkatushenok** [camunda/camunda-modeler#572]
Camunda Modeler Version: 1.8.0.

Bug applies to all Platforms.

__Steps to Reproduce__

* Open Diagram
* Edit (diagram Unsaved)
* Close modeler, when asked to save, say "Don't save"
* Reopen modeler
* __Previously opened diagram not open anymore__

__Expected Behavior__

* [ ] The diagram, which I did not intentionally close is re-opened

**Comment by nikku** [comment]
Related to #563
