### ISSUE TITLE
Remember mini map toggle state in Workspace

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#577]
As a user, I want the mini map to either be open for all diagrams or not.

* [x] Store current mini map toggle state in workspace
* [x] Apply state on diagram switch

Classified this as a UX bug, as users cannot efficiently use / not use the minimap without this fix.

**Comment by nikku** [comment]
This is not working as expected when switching between diagrams:

* Toggle minimap open
* Open diagram A
* Open diagram B
* Switch of Minimap (on diagram B)
* Switch to diagram A
* __Minimap still open__

Generally speaking, the minimap should behave exactly like the properties panel.

**Comment by philippfromme** [comment]
Actually, the palette should also behave like the properties panel. 😅

**Comment by nikku** [comment]
WIP changes on `minimap-2` branch in Camunda Modeler and Minimap,

TODOs documented [here](https://github.com/camunda/camunda-modeler/commit/f6bad31b452083e108f44a3aeb20b0fca1c4a2e1).

**Comment by philippfromme** [comment]
@nikku Can we merge this before the patch release?

**Comment by nikku** [comment]
Yea, should I carry out the merge? I thought you'd do the review of my changes and merge things.

**Comment by nikku** [comment]
:+1:

**Comment by nikku** [comment]
Let's decide how we handle https://github.com/camunda/camunda-modeler/issues/594, too, tomorrow.
