### ISSUE TITLE
I can define a history time to live for a Decision

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda-modeler#581]
It should be possible to set the attribute `camunda:historyTimeToLive` [1] for a decision.

[1]: http://stage.docs.camunda.org/manual/develop/reference/dmn11/custom-extensions/camunda-attributes/#historytimetolive

**Comment by philippfromme** [comment]
Implemented by https://github.com/bpmn-io/dmn-js-properties-panel/commit/73d3124183dcd8ee0d6dca8ee52ccbf10e0e828a.

**Comment by nikku** [comment]
Closed via 267c44a67f1d97fe5fc74e6ed7b05e67642b5321.
