### ISSUE TITLE
Minimap preview does not correlate with process

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#584]
Problem:
Minimap displays element that is not existing in the process
![modeler_mini_view](https://cloud.githubusercontent.com/assets/2777965/25943330/ce70a378-363f-11e7-8ecc-b38f99033f87.JPG)

**Comment by nikku** [comment]
Please add steps how to reproduce this bug.

**Comment by mschoe** [comment]
Of course! To reproduce the behavior 

1. open a new bpmn file
2. change the type of the start event
3. move the start event
