### ISSUE TITLE
Modeler generating orphaned associations: The content of element 'bpmn:dataInputAssociation' is not complete

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#587]
seeing a lot of errors being generated when creating associations with DataStores

```
"ENGINE-09005 Could not parse BPMN process. Errors: \n* cvc-complex-type.2.4.b: The content of element 'bpmn:dataInputAssociation' is not complete. One of '{\"http://www.omg.org/spec/BPMN/20100524/MODEL\":sourceRef, \"http://www.omg.org/spec/BPMN/20100524/MODEL\":targetRef}' is expected.
```

The modeler seems to create orphaned associations.

anyone else seeing this?  It is not every time.  have not locked down the pattern yet.

**Comment by nikku** [comment]
Did not occur to me yet. If you come across concrete steps to reproduce we may look into this issue.

**Comment by falko** [comment]
Morphing leaves empty Data Output Association (not schema-valid)
1. Create a None Start Event and a Data Stores and conntect them with a Data Output Association.
2. Morph the None Start Event into a Signal Start Event

expected:

    <bpmn:startEvent id="StartEvent_1">
      <bpmn:dataOutputAssociation id="DataOutputAssociation_1remc38">
        <bpmn:targetRef>DataStoreReference_0ujxij0</bpmn:targetRef>
      </bpmn:dataOutputAssociation>
      <bpmn:signalEventDefinition />
    </bpmn:startEvent>

actual:

    <bpmn:startEvent id="StartEvent_1">
      <bpmn:dataOutputAssociation />
      <bpmn:dataOutputAssociation id="DataOutputAssociation_1remc38">
        <bpmn:targetRef>DataStoreReference_0ujxij0</bpmn:targetRef>
      </bpmn:dataOutputAssociation>
      <bpmn:signalEventDefinition />
    </bpmn:startEvent>

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/bdc5463c369dd57a0181c999078f363eb2ce650b.
