### ISSUE TITLE
Wrong label for "Align Elements to Bottom" tool 

### ISSUE THREAD

**Issue by sebwarnke** [camunda/camunda-modeler#590]
The label of the activated tool in the image below is "Align Elements to Middle"
<img width="70" alt="bildschirmfoto 2017-05-23 um 13 49 49" src="https://cloud.githubusercontent.com/assets/26740468/26353303/0e64e14a-3fc0-11e7-9039-8fe1b1bd6ada.png">

I expected it to be "Align Elements to Bottom".

**Comment by nikku** [comment]
Nice catch :tada:.

**Comment by sebwarnke** [comment]
common blocker issue
