### ISSUE TITLE
Add Data Object Reference to Context Pad

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#592]

**Comment by nikku** [comment]
Which context pad would you like to add it to? Every element?

**Comment by falko** [comment]
Every element that can have a Data Output Association, e.g. for Start & Intermediate Events, Tasks. Not for End Events, Gateways, Embedded Sub-Processes, Pools, Lanes.

**Comment by nikku** [comment]
We will not do this. It is not commonly used enough.
