### ISSUE TITLE
Dialog fonts are scrambled

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#594]
With the latest nightly the dialog fonts are scrambled / glyphs won't be found on my Linux machine. We need to investigate, if this is an issue on one of the important platforms (Windows, MacOS), too.

__Reproduce__

* Open Modeler
* Perform open file
* I see a dialog like this: 
    
![image](https://cloud.githubusercontent.com/assets/58601/26628038/d01e4a5a-45fc-11e7-945b-613d1097708e.png)

__Environment__

Arch Linux

__Modeler__

Latest [nightly](https://camunda.org/release/camunda-modeler/nightly/)

**Comment by nikku** [comment]
Need to reproduce with others using Linux whether this is an issue on my machine only.

**Comment by nikku** [comment]
Upgrading to latest electron (https://github.com/camunda/camunda-modeler/commit/97038607618b87740c7fcf98301c1a0e4f10412d) fixes the issue for me.

**Comment by menski** [comment]
I also noticed this problem today with modeler v1.8.0 on Arch Linux. I also downloaded modeler v1.0.0 and experience the same problem. So I assume that this is more an Arch Linux then modeler issue.

**Comment by nikku** [comment]
Thanks for taking your time to reproducing his.

I'd still like to collect some feedback from other Linux distributions to understand the impact of this change.

**Comment by philippfromme** [comment]
Works on Windows 10.

**Comment by nikku** [comment]
Should postpone this update for the next minor release, as it will increase the modeler(s) bundle sizes quite significantly.

**Comment by Zelldon** [comment]
![screenshot](https://user-images.githubusercontent.com/2758593/27023232-ea720294-4f51-11e7-8b0f-ffb6893abf51.jpg)

I also have this problem on `4.11.3-1-ARCH`. I tried  camunda-modeler-1.5.1-linux-x64 and camunda-modeler-1.8.2-linux-x64. Is also reinstalled my font packages.

**Comment by arkhan** [comment]
I have the same issue in Archlinux 4.11.3-1-ARCH and  camunda-modeler-1.8.2-linux-x64

**Comment by Chris81T** [comment]
Like arkhan I also have this issue in Arch 4.11.3-1-ARCH / camunda modeler 1.8.0 and 1.8.2-linux-x64

https://forum.camunda.org/t/only-rectangles-are-visible-in-dialogs-of-camunda-modeler-under-arch-linux/3930

**Comment by menski** [comment]
see also: https://github.com/electron/electron/issues/9616

**Comment by hoestreich** [comment]
Having the same issue with 
`Linux version 4.4.73-1-MANJARO`
and 
`camunda-modeler (1.8.2-1)` from AUR.
Installing electron (1.4.16-2) did not help and also cloning the repo and building the application manually dit not solve this issue.
Would really appreciate a solution for this :)

**Comment by meyerdan** [comment]
@pedesen This could be the first one you take over.

We should update electron to the lastest version and check whether that solves the problem.
If true we can merge that into the current milestone.

If updating to latest electron does not solve the issue or if updating is not easily possible we need to re-consider.

**Comment by mati865** [comment]
The same on Fedora 26.

**Comment by pedesen** [comment]
I can not reproduce it on
* my machine: Linux Mint 17.1 (Cinnamon)
* VirtualBox: Ubuntu 17.04 (Unity 8)
* VirtualBox: Arch Linux 2017.05 (KDE Plasma)
