### ISSUE TITLE
Plugins folder and element-templates folder in different locations on Mac

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-modeler#597]
On macOS you have to add plugins to the folder:
/Users/{user_name}/Library/Application Support/camunda-modeler/plugins
For element-templates following folder is used:
/Users/{user_name}/Library/Application Support/camunda-modeler/resources/element-templates

From my point of view one should follow the same structure for element-templates & plugins, so that we have either:
/Users/{user_name}/Library/Application Support/camunda-modeler/plugins
/Users/{user_name}/Library/Application Support/camunda-modeler/element-templates
or
/Users/{user_name}/Library/Application Support/camunda-modeler/resources/plugins
/Users/{user_name}/Library/Application Support/camunda-modeler/resources/element-templates

**Comment by philippfromme** [comment]
Same problem on Windows. We should fix that to avoid confusion.
