### ISSUE TITLE
Dragging an activity results in strange behaviour

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#601]
This happens a lot but it's quite hard to reproduce. Sometimes it happens when I create a new model and start working, but sometimes also with existing ones.

Click on an activity and try to drag it somewhere else. The activity won't be released and goes crazy, whenever I click, it shows up somewhere else. Sometimes this can be stopped by hitting Esc, sometimes only restarting the modeler helps.

![things_are_strange](https://user-images.githubusercontent.com/17595149/26917535-ec8b9ffc-4c2e-11e7-8fb7-6aaff9236fe9.gif)

**Comment by philippfromme** [comment]
Thank you for reporting this issue. Next time this happens can you please open the developer tools (F12 or Window -> Toggle DevTools) and see if there are any errors? That would be very helpful.

**Comment by benhoffmann** [comment]
Hi Philipp, 

I'll do that and let you know what I can find. Didn't think about that in the first place.

**Comment by nikku** [comment]
Seems the bug is gone now?

**Comment by benhoffmann** [comment]
I guess so, haven't experienced it recently.
