### ISSUE TITLE
Share working directory with client

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#602]
Plugins might want to request resources like images from their directory. In order to access this directory they should be able to access the current working directory of the Camunda Modeler like
```
requestResource(getModelerDirectory() + '/plugins/my-plugin/image.png');
```
or
```
requestResource(getPluginsDirectory() + '/my-plugin/image.png');
```

**Comment by vkatushenok** [comment]
@philippfromme LGTM

**Comment by vkatushenok** [comment]
@philippfromme What about also not in CWD `plugins` folder (there are several folders that you can put plugins in)?
