### ISSUE TITLE
It is possible to open 'save diagram as..' dialog multiple times

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#603]
Reproduce:
* Save new diagram --> _Save Diagram as..._ dialog appears
* focus the modeler application
* Save the diagram again

Problem:
A new _Save Diagram as..._ dialog appears. This way it is possible to open multiple save dialog

Expected behavior:
Focus remains on the _Save Diagram as..._ dialog. It is not possible to focus the modeler app.

**Comment by nikku** [comment]
We once switched to non-modal dialogs to workaround rendering issues. Would be interesting, if these are still present in current versions of electron. If not, switching back to blocking dialogs would solve this issue.

**Comment by nikku** [comment]
Still an issue.

**Comment by nikku** [comment]
Fixed with latest version of the modeler.
