### ISSUE TITLE
Element Templates - replace existing field

### ISSUE THREAD

**Issue by dikey94** [camunda/camunda-modeler#604]
I'd appreciate if someone told me how can I override existing input. I have to replace text field (Service Task -> Implementation -> Delegate Expression) with select input. I've been searching here: https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates1 

Thanks.

**Comment by philippfromme** [comment]
In order to do this you would have to override the current implementation in the properties panel with your own. Please contact the Camunda [forum](https://forum.camunda.org/) or the bpmn.io (forum)[https://forum.bpmn.io/] for general questions.
