### ISSUE TITLE
Pool resizing snaps to neighbouring pools

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#608]
Would be a great QOL enhancements to have Pools snap to the sizes of neighbouring pools when resizing.

Related / the same issue as https://github.com/camunda/camunda-modeler/issues/609.

Depends on #1290

**Comment by nikku** [comment]
Will be fixed with the introduction of a general snap on resize feature (https://github.com/camunda/camunda-modeler/issues/1290).

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1404.
