### ISSUE TITLE
Make it possible to resize text annotations to the same size

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#609]
Would be great to have a small px counter for length and width of the annotation text boxes so that we can resize multiple annotations to the same size.

Depends on https://github.com/camunda/camunda-modeler/issues/1290.

**Comment by nikku** [comment]
As an alternative to this feature we could simply introduce snapping for resizing, i.e. only offer resize in 10 pixel intervals.

**Comment by StephenOTT** [comment]
I would be fine with that

**Comment by nikku** [comment]
Will be fixed with the introduction of a general snap on resize feature (https://github.com/camunda/camunda-modeler/issues/1290).

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1404.
