### ISSUE TITLE
Sign released binary for Mac

### ISSUE THREAD

**Issue by itohiro73** [camunda/camunda-modeler#612]
Please kindly sign released binary.

Camunda Modeler app for Mac gives security warning due to missing sign (I used camunda-modeler-1.8.2-darwin-x64.tar.gz). Because of this, I cannot install it to my machine due to the firm's security policy. 

https://camunda.org/download/modeler/

For Electron build, it should be as easy as passing `--sign` parameter to `electron-packager` command with Apple Developer ID as per the reference below. Please kindly handle it and release signed binary at your earliest convenience.

Ref: https://nulab-inc.com/blog/typetalk/3-necessary-things-to-correctly-release-a-product-based-on-the-electron-app/

Thanks in advance!

**Comment by itohiro73** [comment]
Hi,

Just wanted to check if this could be handled at some point by any chance. 

Since this is not particularly about code change, please let me know if there is any other appropriate channel I should raise this.

Please kindly advise.

Thanks,
Hiroshi

**Comment by nikku** [comment]
Unfortunately, signing the Mac distribution is not an easy thing to do for us right now. We have this issue on our radar but cannot promise any solution right now.

**Comment by nikku** [comment]
Fixed via https://github.com/camunda/camunda-modeler/pull/820.
