### ISSUE TITLE
DMN: Unable to edit last output column after resizing the modeler windows

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#617]
I cannot edit the value of the last output column out of 2  of a decision table after resizing the modeler window.

How to reproduce:
1. Open this decision table [Dish and Drink](https://github.com/ingorichtsmeier/dmn-test-tool/blob/master/dmn-excel-tester/src/test/resources/unexpected/dish-and-drink-fails.dmn) in the modeler. The decision table appears.
2. Resize the modeler window from full size window to a smaller size. Other windows appear on the screen
3. Edit a value of the last output column 'Drink'

Expected:
1. I can edit the value.

Result:
1. It is not possible to edit the value.

But I can edit a value from the output column 'Dish'

Modeler 1.8.2. Windows 10 64-Bit.

**Comment by meyerdan** [comment]
Hey @mburke84, could you please see if you can reproduce this?

**Comment by mburke84** [comment]
I can reproduce this with Modeler Version 1.8.2 and Windows 10 64-Bit.
