### ISSUE TITLE
Business Knowledge Model Decision Table

### ISSUE THREAD

**Issue by HeinnE** [camunda/camunda-modeler#618]
We need to create decision tables linked to Business Knowledge Models - the same as with Decisions.

I understand that on a lower implementation level Decision Tables get executed regardless their origin (Decision / Business Knowledge), but in terms of modelling and documentation I need to differentiate it as it will make it more clear for business and for communicating to others – hence the need to conform to standards. We need to get models signed-off and approved before we can progress to implementation stage.

**Comment by meyerdan** [comment]
Thank you for your feedback. @falko what is your opinion on this?

**Comment by falko** [comment]
@HeinnE I don't fully understand what you want to achieve and how a BKM would help. Could you give an example diagram?

**Comment by falko** [comment]
If you just need an annotation, you could try to work with BPMN-style text annotations.

**Comment by HeinnE** [comment]
[DMN_formal-16-06-01.pdf](https://github.com/camunda/camunda-modeler/files/1114998/DMN_formal-16-06-01.pdf)
@falko Please refer to the OMG Group DMN Standard attached - Fig 2 on page 17 & Fig 9 page 24 as examples. Business Knowledge gets modelled separately as input for the Decision Table associated with the decision. I need to differentiate between the Business Knowledge decision table as from the Decision logic - hope it makes better sense now.

**Comment by falko** [comment]
Here are the figures that you mentioned...

**Figure 2 – DMN Constructs:**
![dmn-figure-002](https://user-images.githubusercontent.com/40038/28321390-71ce0d62-6bd3-11e7-8a51-fba82ff05b25.jpg)

**Figure 9 - Business knowledge model and corresponding decision table:**
![dmn-figure-009](https://user-images.githubusercontent.com/40038/28321501-b1fe7804-6bd3-11e7-9fc2-45e34cc6d727.jpg)

What do you want to express by your distinction between a Decision Table implementing a Decision versus a Decision Table encapsulated inside a BKM that is invoked by a Decision? BKMs are primarily meant for reuse of decision logic. Do you want to make your Decision Table reusable or invokable? If so, have you thought about using simple Information Requirements to reuse a Decision Table?

**Comment by falko** [comment]
@HeinnE since we haven't heard back from you, I'll close this issue.

**Comment by bhoefman** [comment]
Hi @falko ,
I would like to iterate over the following model:

![drd no iteration](https://user-images.githubusercontent.com/41187066/45954134-77fcd900-c00c-11e8-860e-00c1715a0856.png)

using a literal expression that looks like
```
for something in somethings return someLevel(something)
```

For this I believe I need either a decision service, which calls the whole DRD, or the possibility to invoke the decision tables through business knowledge models.

For the latter option, using business knowledge models, this could look like the below for the top 2 levels of the original model:
![drd hint of iteration](https://user-images.githubusercontent.com/41187066/45954539-944d4580-c00d-11e8-97be-582c7eb51487.png)
Note that the Business Knowledge Models would be invoking the decision tables that you see here visually on the right.

For the bottom part, 
![image](https://user-images.githubusercontent.com/41187066/45954723-0b82d980-c00e-11e8-9353-417fabf761ed.png)
I believe it would be best to model the iteration version as a boxed context, with two context entries each of which calls one of the decision tables.
