### ISSUE TITLE
Users of the script editor in DMN should be able to insert newlines

### ISSUE THREAD

**Issue by linus-gubenis** [camunda/camunda-modeler#619]
Currently it is not possible for a user to enter newlines when editing a script.

Steps to reproduce:
1. Create a new DMN diagram.
2. Click on the first elements green table icon to open the table underlying this DMN.
3. Click on `Enter Advanced Mode` on the upper right corner.
4. Click on an empty cell (above string for example)
5.  In the opening popup, click on Script
6. You should now be presented with something similar to this: https://www.dropbox.com/s/vudfc1v7dogjrwn/Screenshot%202017-06-27%2014.08.54.png?dl=0
7. Enter text into the Editor and try to add a newline by pressing, enter, or cmd + enter or ctrl + enter or shift + enter

- Expected: add a new line
- Actually happening: nothing, or weird stuff (moving textarea etc.)

JIRA ISSUE: https://app.camunda.com/jira/browse/SUPPORT-3451

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/70a7641b408677090f351eab3e3d0b378fa21aab
