### ISSUE TITLE
Inaccessible dialog options in DMN editor

### ISSUE THREAD

**Issue by stsc-pentasys** [camunda/camunda-modeler#620]
The "Edit String Expression" dialog does not work for large tables and more than a few options.
### How to reproduce
1. Load the attached file Example.dmn (from Example.zip) in Camunda Modeler
2. "Exit advanced mode", if necessary
3. Scroll down to rule #28
4. Left-click input column Assetklasse in line #28
5. Try to scroll down to the last option in dialog "Edit String Expression" -> does not work with mouse or keyboard (see screenshot)
### Expected behavior
All input options are reachable.
### Workaround
Enter advanced mode and edit value directly.

![inaccesible_dialog](https://user-images.githubusercontent.com/6389280/27588137-5e13d230-5b47-11e7-97ad-a02c65228a6f.PNG)
[Example.zip](https://github.com/camunda/camunda-modeler/files/1105293/Example.zip)

**Comment by nikku** [comment]
This is fixed with the latest alpha release of the Camunda modeler.
