### ISSUE TITLE
Allow inserting new lines using ENTER when editing script

### ISSUE THREAD

**Issue by linus-gubenis** [camunda/camunda-modeler#621]
Related to: #619 

It is to discuss whether we allow the user using the script editors textarea to insert new lines by just pressing enter, without addition of a meta key.

Related Support Ticket: [SUPPORT-3451](https://app.camunda.com/jira/browse/SUPPORT-3451)

**Comment by philippfromme** [comment]
This is actually a bug that was introduced by https://github.com/camunda/camunda-modeler/commit/0f8759d153597b776e9b1c465b1f2ca9f3f35fa3. Therefore it should be fixed.
