### ISSUE TITLE
Unable to delete listener after morphing the task type

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#625]
A listener is not deleted after morphing the task and deleting the listener. It appears again after seleting the task again.

Steps to reproduce:
1. Model a task
2. Morph it to service task
3. Add a listener without filling the details.
4. Morph the task to manual task
5. delete the listener
6. select the start event
7. select the manual task

expected: the listener is gone
behavoir: the listener appears again.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/d32437deb8577d54e757b012684b04784fb52c1d.
