### ISSUE TITLE
Missing Camunda icon in task bar in linux systems

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda-modeler#627]
Linux Mint:
![selection_108](https://user-images.githubusercontent.com/2543743/28660701-56b7295e-72b4-11e7-84b9-0874f3c4a954.png)

**Comment by nikku** [comment]
How to add these on linux?

**Comment by pedesen** [comment]
We actually have this functionality already: https://github.com/camunda/camunda-modeler/tree/master/resources/platform/linux

I just tested and it worked...

**Comment by dschulten** [comment]
The /support folder of the linux package contains xdg_register.sh
