### ISSUE TITLE
Support default gestures for two finger scroll/zoom via touch pad (Mac / Windows / ...)

### ISSUE THREAD

**Issue by tsabirgaliev** [camunda/camunda-modeler#629]
> __Edit__: Updated for clarity.

The default mapping of two finger move on most desktop platforms is _scrolling_ (horizontally or vertically) rather than zooming. Two finger pinching on the other hand is the default gesture for _zooming in_.

Switching to the default operating system behavior would improve the usability of the Camunda Modeler for average users. See suggested mappings / scroll directions below.

__Tasks__

* [ ] Support default 2-finger scroll / zoom gestures on all OS(s)

__Note__

* This needs changes in the underlying modeling toolkits. We need to investigate, whether to provide fallbacks to the current behavior there.

----

__Suggested Mappings__

| gesture | action |
|:--|:--|
| two finger vertical move | scroll vertically |
| two finger horizontal move | scroll horizontally |
| two finger pinch | zoom in/out |

__Document/Canvas Scroll Directions__

The following table summarizes the __document scroll direction on two finger gestures__ for the different OS(s):

| gesture | default | Mac |
|:--|:--|:--|
| 2-finger-up | to top | to bottom |
| 2-finger-down | to bottom | to up |
| 2-finger-left | to left | to right |
| 2-finger-right | to right | to left |
| pinch-in `*`| zoom out | zoom out |
| pinch-out `**` | zoom in | zoom in |

`*` moving fingers closer to each other
`**` moving fingers away from each other

**Comment by pouledodue** [comment]
yup, did you find a workaround? I tried with BetterTouchTool to at least "cancel" the current behaviour with no luck

**Comment by StephenOTT** [comment]
@nikku would be great if we had a fix for this!  Very problematic on trackpad users.

**Comment by nikku** [comment]
Sounds like quite bad usability. What do you guys expect? Just a revert to the pre 1.8.1 behavior?

**Comment by tsabirgaliev** [comment]
@nikku no, sorry for my wording, "as of 1.8.1" merely means "I confirm this behavior at 1.8.1". Probably it works the same in all versions.

**Comment by tsabirgaliev** [comment]
@nikku What is needed is to actually change the current behavior and make touchpad horizontal/vertical scroll gestures actually scroll instead of zooming

**Comment by philippfromme** [comment]
We should fix this ASAP.

**Comment by pouledodue** [comment]
it's the default mac behavior, no-brainer

**Comment by kayazeren** [comment]
I wanted to join this discusssion as a windows user instead of creating new one. Basically I also need to exchange the scroll and zoom behaviours. Please find my summary and suggestions as attached:

![camunda navigation suggestions](https://user-images.githubusercontent.com/4479335/30578223-6ea83c6a-9d1b-11e7-9bc8-4e1e8d0407c4.PNG)

**Comment by tsabirgaliev** [comment]
@kayazeren this issue is specifically about Mac scroll/zoom behaviour. I think it is better to keep this issue focused. And the issue is not about "what I need". The core problem is that the current Mac UX doesn't align with a traditional Mac experience (aka unintuitive)

**Comment by kayazeren** [comment]
@tsabirgaliev thank you for your fast repy. Taking with your words; I guess Mac scroll/zoom behavior is very similar to Windows and Windows User Interface also does not align with traditional Windows experience. So plase take my "what I need" phrase as a "Which experience a Windows user need.."

I will create new issue on Windows navigation. Sorry for inconvenience.

**Comment by nikku** [comment]
Thanks all for your valuable feedback :heart:. 

As mentioned by @kayazeren native-like support for two finger gestures this is not specific to Mac but relevant across all platforms. Because of that I've edited the issues title and provided a detailed summary of the mapping in the issue description. Feel free to double check and correct me, if I'm wrong! 

Good user experience is important for the Camunda Modeler and proper support for these core touch gestures is something we plan look into in the future.

**Comment by tsabirgaliev** [comment]
@nikku why the proposed scroll direction is opposite for Windows and Mac? The direction depends on user preference set in System Preferences. I hope it is possible to delegate the direction to OS setting (or at least, have an app level setting for that)

**Comment by tsabirgaliev** [comment]
@nikku this is what I mean by 'OS setting':
<img width="664" alt="screen shot 2017-10-23 at 18 54 06" src="https://user-images.githubusercontent.com/225910/31890020-96e273bc-b823-11e7-862e-fa917fba86df.png">

**Comment by oscheller1** [comment]
I concur with @tsabirgaliev. Not everybody enjoys Mac's "natural" scroll direction. This camunda setting should be system setting dependent.

**Comment by nikku** [comment]
> @nikku why the proposed scroll direction is opposite for Windows and Mac?

Because there is different default behaviors for Mac and other platforms.

Unfortunately, we'll most likely not be able to react to users special settings. This is due to the fact, that we need to work with raw pointer events and interpret these

**Comment by nikku** [comment]
Adding a switch to toggle between natural scrolling and default (Windows / other OS(s)) would be an addition to consider.

**Comment by nikku** [comment]
Needs fix via https://github.com/bpmn-io/diagram-js/issues/240.

**Comment by nikku** [comment]
Will be addressed in the next version of the Camunda Modeler.

**Comment by nikku** [comment]
You can get a sneak peek of the the new interaction patterns at [demo.bpmn.io](https://demo.bpmn.io/s/application-processing).

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/bdc5463c369dd57a0181c999078f363eb2ce650b.

**Comment by oscheller1** [comment]
Feels fantastic! Thank you for this

**Comment by kayazeren** [comment]
Great... and what a luck. I'm just at the end of the mapping 250+ processes...
Next week I will deploy Camunda Modeler and process maps to the users for change management.
Now teaching them how to use the Modeler will be easier.
Thanks a lot.
