### ISSUE TITLE
File icons are not shown in Finder

### ISSUE THREAD

**Issue by tasso94** [camunda/camunda-modeler#633]
In Finder...
# Expected behavior
...BPMN, CMMN and DMN files are recognisable as they are marked with the camunda modeler icon.

# Observed behavior
...BPMN, CMMN and DMN files are **not** recognisable as they are **not** marked with the camunda modeler icon. The icon type is *undefined*.
![screen shot 2017-08-02 at 11 14 10](https://user-images.githubusercontent.com/3015690/28866605-bd5eb5dc-7773-11e7-8127-d7ed8addeae5.png)

**Comment by nikku** [comment]
We appreciate contributions to improve this behavior.
