### ISSUE TITLE
Disallow multiple incoming sequence flows to target events of event-based gateway

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda-modeler#637]
I can currently model diagrams like

![grafik](https://user-images.githubusercontent.com/586648/28958374-67560814-78f6-11e7-985e-4773a09664ab.png)

Having two incoming sequence flows for the upper message event is not allowed by the BPMN spec section 10.5.6:

![534dfd021c773bc1945c81edcf372adee22cb37e](https://user-images.githubusercontent.com/586648/28958429-9b556e20-78f6-11e7-9afd-c9e246716295.png)

The modeler should prevent users from modeling this.

**Comment by ThorbenLindhauer** [comment]
Evidence that people make this mistake: https://forum.camunda.org/t/incoming-sequenceflow-for-intermediatecatchevent/6341/2

**Comment by pinussilvestrus** [comment]
Waiting for unreleased changes in `bpmn-js`.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1404.
