### ISSUE TITLE
Resizing properties panel not working when using external monitor in 1.9.0

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#638]
![2017-08-04_11-39-46](https://user-images.githubusercontent.com/7633572/28963788-bb661bf6-790a-11e7-87b6-305538f2a6c3.gif)

**Comment by jdupont22** [comment]
Same here, very annoying

**Comment by meyerdan** [comment]
@philippfromme I think we should fix this rather sooner than later. What is your opinion, should we look into  it in the current or next milestone?

**Comment by philippfromme** [comment]
I think we could look into it for the next milestone. I'm afraid it's going to be quite tricky.

**Comment by igieon** [comment]
What i can add to this that this happen if your external monitor has normal resolution (1920x...) and main screen 4k display so resizing is working correctly on  main monitor but not on external.

**Comment by MVII3IV** [comment]
for some reason this solution didn't work for me, what I did was remove this folder : C:\Users\yourUserName\AppData\Roaming\camunda-modeler

by doing this the modeler restarts all its configurations

**Comment by philippfromme** [comment]
@MVII3IV yes, that resets everything but is quite inconvenient. As of v0.10.0 you can reset the properties panel using the menu/keyboard. Hope that helps in the meantime.

<img width="536" alt="fix" src="https://user-images.githubusercontent.com/7633572/30312089-5e68c2bc-9798-11e7-871f-26982a68e547.png">

**Comment by vt512** [comment]
As philippfromme pointet out, in current versions of the modeler you can reset and toggle the properties panel with keystrokes or the menu. But this only resets the panel to 250px.

I wanted bit more width. With the following workaround it is possible:
Close Camunda Modeler.
Edit the config.json file (on my linux system in $HOME/.config/camunda-modeler) and search for "propertiesPanel". Change the width from 250 to e.g. 350.
Reopen Camunda Modeler.
