### ISSUE TITLE
editor freeze when opening from path (1.9.0), windows 64b)

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-modeler#640]
I copy the path of a process in IDEA and then say "open" in modeler and paste the path in the location bar of the file-dialog".

Result: process shows but editor is frozen.

Closing and opening: file still open, editor works.

strange.

**Comment by philippfromme** [comment]
Can't reproduce using IDEA, Camunda Modeler 1.9.0 and Windows 10.

I copy the path using

<img width="313" alt="foo" src="https://user-images.githubusercontent.com/7633572/29069374-0edf675a-7c3b-11e7-9109-54e894eac131.png">

**Comment by jangalinski** [comment]
I am using Windows 7.

**Comment by nikku** [comment]
Unfortunately we cannot reproduce this issue.
