### ISSUE TITLE
Scrolling via mouse wheel not deterministic (bpmn-js, cmmn-js, dmn-js)

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#646]
diagram-js ticket: https://github.com/bpmn-io/diagram-js/issues/224

Reproduce:

* zoom in 4 steps using mouse wheel
* zoom out 4 steps using mouse wheel

Expected behavior:
* zoom is 1

Actual behavior:
* zoom is 0.74

![2017-08-21_12-02-03-compressor](https://user-images.githubusercontent.com/7633572/29517201-3c464d7e-8674-11e7-8665-2375af761b1b.gif)

**Comment by philippfromme** [comment]
This was actually supposed to be fixed by https://github.com/bpmn-io/diagram-js/commit/472d7753d5865f61260e99d2d99705484e5783fe. For some reason it's not.

**Comment by mburke84** [comment]
Related Support Case: [SUPPORT-3571](https://app.camunda.com/jira/browse/SUPPORT-3571)
