### ISSUE TITLE
When changing a condition start event in an event process from interrupting to non-interrupting the condition is lost

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-modeler#647]
Whenever I morph the type of the conditional start event in an event subprocess from interrupting to non-interrupting (or the other way round) the condition is loist.

Might apply to other types as well - haven't checked.

![grafik](https://user-images.githubusercontent.com/1217596/29618859-ba478200-8819-11e7-93ca-d838e6126b1d.png)

**Comment by berndruecker** [comment]
Also true for timer start event

**Comment by nikku** [comment]
Duplicate of https://github.com/camunda/camunda-modeler/issues/678.

**Comment by nikku** [comment]
This is fixed via https://github.com/camunda/camunda-modeler/commit/2415cf9ba925b1b303923187c3556db468a0db0f / `bpmn-js@5.0.0-beta`.
