### ISSUE TITLE
[enhancement] Remember selected tab in the Properties panel

### ISSUE THREAD

**Issue by pouledodue** [camunda/camunda-modeler#648]
#I click a task, click 'Forms' tab then I describe form fields;
Now I go click another task.
I then come back to continue editing the previous form but now the selected Tab is 'General';
It would be great if it could remember that the Forms tab were selectedand the tabpanel be in the exact state it was ;

**Comment by nikku** [comment]
Makes a lot of sense.

**Comment by nikku** [comment]
We've reconsidered your request and decided to not build this.

The reason for it is, that this conflicts with another interaction we already support in the properties panels: Whenever we switch a selection we ensure the selected tab is preserved, if it exists on the newly selected element, too.
