### ISSUE TITLE
Move elements pixel by pixel using keyboard

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#651]
Snap lines do a good job in aligning things, but sometimes one needs a bit of extra precision.

Depends on https://github.com/bpmn-io/bpmn-js/issues/376.

**Comment by nikku** [comment]
This depends on https://github.com/bpmn-io/bpmn-js/issues/376.

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/bd46b6763591203d7cc6d874f32d9d3e84987a7f.
