### ISSUE TITLE
Keep positions of Boundary Events and edge waypoints when resizing a Sub-Process

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#655]
![2017-08-29 resizing a sub-process](https://user-images.githubusercontent.com/40038/29805125-e2df103a-8c87-11e7-81f6-ef9fd302548c.gif)

**Comment by falko** [comment]
The expected result would have been:
![2017-08-29 rezising a sub-process expected result](https://user-images.githubusercontent.com/40038/29805199-65fa7be4-8c88-11e7-8728-6aab279b019a.png)

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/79dc1a4e218ac9eabbfc3d1d585821fb12c7a297.
