### ISSUE TITLE
Fix/improve minimap

### ISSUE THREAD

**Issue by franzheidl** [camunda/camunda-modeler#662]
Once the Navigator* is opened, I can't find a way to close it again. 

Once it is opened, it will also be open on any other diagram I create. A newly created document will always only consist of a single starting event, there really is no need for the navigator to be open.

* Add option to close Navigator
* Handle Navigator state per diagram/document

(*) I presume that's what it is called, I'm on about the small representation of the whole diagram that opens once you click the map icon in the upper right of the modeller screen

**Comment by franzheidl** [comment]
Ah, I think you generally refer to that thing as mini-map. This issue is, at least in parts, a duplicate of  #583.

**Comment by philippfromme** [comment]
You can close the minimap like this:

![minimap-gifsicle](https://user-images.githubusercontent.com/7633572/30103261-5da0e95e-92f2-11e7-84c0-0580dc9dd2c0.gif)

And yes, this is very bad UX, we are aware of this issue and would like to improve this.

As for the open/closed state of the minimap being remembered globally this is intended. We decided to to that the same way the open/closed state of the properties panel is remembered globally. I personally am always open for discussion, though.

**Comment by philippfromme** [comment]
We should generally discuss if it makes sense to treat all elements the same way (as in persisting their state). Especially when you create a new diagram there is little to no use for the minimap.

Related to https://github.com/camunda/camunda-modeler/issues/583
