### ISSUE TITLE
Space tool is only activated upon mouse move after using keyboard shortcut

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#664]
1. Hit 'S' on the keyboard to choose the Space tool
2. Do not move the mouse and immediately click and drag to make space

Expected: The cursor changes immediately after pressing 'S' and dragging actually creates space.
Actual: Making space doesn't work and the Space tool doesn't activate at all. The cursor only changes after moving the mouse.

**Comment by philippfromme** [comment]
This is a known bug which unfortunately hasn't been fixed yet. There's a [ticket in bpmn-js](https://github.com/bpmn-io/bpmn-js/issues/584), too. Thanks for reporting.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/2040.
