### ISSUE TITLE
Associations of annotations disappear when used for Pools

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-modeler#665]
Camunda Modeler 1.10 MacOS

Actual:
1. Create Annotation on Pool and place annotation outside pool
2. Move annotation inside of pool
3. Move annotation outside of pool
4. Notice that association is gone

**Comment by philippfromme** [comment]
This is a bug due to the rules not allowing the association anymore when moving the annotation to a new parent which is the participant itself. Thanks for reporting.

**Comment by nikku** [comment]
There is no easy way to fix this. The work around is to keep text annotations outside pools; the association will be delete once it is moved inside the pool only.
