### ISSUE TITLE
Selecting an element with a colour cause the Log panel to open

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#666]
![colourselecterror2](https://user-images.githubusercontent.com/10612634/30273917-64b560dc-96fb-11e7-916e-4b7e3efb9e59.gif)

This seems to happen to any element selected after a colour is added.

**Comment by NPDeehan** [comment]
This is actually a problem with an a plugin... not to point any fingers... 👉 👉  @felix-mueller

**Comment by felix-mueller** [comment]
Thanks @NPDeehan - I am waiting for a PR 👯‍♂️

**Comment by philippfromme** [comment]
Is this an issue with token simulation??

**Comment by felix-mueller** [comment]
Don't worry, @philippfromme . Token Simulation is fine. It's a bug in another plugin that we have :-) I will fix it soon

**Comment by NPDeehan** [comment]
I would never want a bad word said about token simulation - it's work of genius!
