### ISSUE TITLE
If I "break" the diagram, I can never fix it back

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda-modeler#667]
Steps to reproduce:
1. Create new diagram with one start event
2. Go on XML tab and remove all diagram information (the whole BPMNDiagram tag and content)
3. Go back on Diagram tab -> Error "no diagram to display"
4. Go back on XML tab and Undo the changes to return all diagram data back (so XML is now again as it was after step 1)
5. Go back on Diagram tab

Currently:
Error "bo.get is not a function" (the diagram is "broken" unless we reopen the Modeler)

Expected behaviour:
the diagram is correctly shown

**Comment by philippfromme** [comment]
I cannot reproduce this in Camunda Modeler v1.13.1. After undoing the changes in the XML editor I don't get any error.

**Comment by nikku** [comment]
[Comments on commit](https://github.com/bpmn-io/bpmn-js-properties-panel/commit/0b8d10b279abad11f921ae555c4502379eb5531c#comments).
