### ISSUE TITLE
Right click menu in the bottom of the large table

### ISSUE THREAD

**Issue by vabue** [camunda/camunda-modeler#668]
Hi

If user makes right click in the bottom of the table which more than one screen - menu goes under the border of the app. 

See - http://take.ms/OmAEu

Mac OS X/Camunda Modeler 1.10

**Comment by philippfromme** [comment]
Thanks for reporting. We're currently in the process of revamping dmn-js, the DMN viewing/modeling library and will try to fix this and other issues in an upcoming version.

**Comment by nikku** [comment]
The new version of `dmn-js` and the next stable of the Camunda Modeler will place the menu in the appropriate place.
