### ISSUE TITLE
Plugins: improve getPluginsDirectory to point to folder of plugin

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#670]
Currently `getPluginsDirectory` only returns the base path to the plugins folder. Therefore things like renaming the folder of a plugin or nesting it in another folder will break paths to assets that are requested like

```javascript
var img = document.createElement('img');
img.src = getPluginsDirectory() + '/camunda-modeler-plugin-example/logo.png';
```

**Comment by nikku** [comment]
We decided to go for logical path to retrieve plug-in assets instead. 

Plugin authors may use urls of the style `app-plugins://{name}/{path-to-asset}` and we figure out the actual file system location for her.
