### ISSUE TITLE
Windows Mouse/Trackpad Navigation Suggestions

### ISSUE THREAD

**Issue by kayazeren** [camunda/camunda-modeler#671]
Hello,
I have some suggestions over Windows user experience to discuss
![camunda navigation suggestions](https://user-images.githubusercontent.com/4479335/30580021-ced4e356-9d23-11e7-96c4-b091b2bb6c60.PNG)
.

**Comment by nikku** [comment]
Should be covered with https://github.com/camunda/camunda-modeler/issues/629.
