### ISSUE TITLE
Recalculate sequence flows w/ corner when reconnecting elements

### ISSUE THREAD

**Issue by franzheidl** [camunda/camunda-modeler#672]
When I have a diagram with sequence flows 
And my sequence flows have one or more corner
when I disconnect one of them
and I connect them to another element
then it should look exactly the same way as if I had connected it this way in the first place

<img width="814" alt="screen shot 2017-09-20 at 10 45 30" src="https://user-images.githubusercontent.com/1186274/30647299-560196ec-9e1b-11e7-9f62-6bf15a6b68b6.png">

**Observed behavior**

Only the part of the sequence flow after the last (yellow) point before the arrow end changes:

<img width="797" alt="screen shot 2017-09-20 at 10 45 41" src="https://user-images.githubusercontent.com/1186274/30647309-5dbb1db8-9e1b-11e7-8bb1-2180fd750f81.png">

**Desired behavior**

The whole sequence flow element should be re-calculated in the same way as if it was placed to connect these two elements in the first place:

<img width="585" alt="screen shot 2017-09-20 at 10 47 51" src="https://user-images.githubusercontent.com/1186274/30647317-6500f03e-9e1b-11e7-8d90-e1f775de137e.png">

---

Depends on https://github.com/bpmn-io/bpmn-js/issues/718

**Comment by nikku** [comment]
I agree that the diagram should be somewhat better layouted after the reconnection. Could you provide us with the diagram so we can reproduce your issue?

**Comment by philippfromme** [comment]
+1 This would really improve things!

**Comment by franzheidl** [comment]
@nikku Sure, here’s the diagram: [https://cl.ly/mhwU](https://cl.ly/mhwU)

**Comment by nikku** [comment]
Seems like we're missing the auto-layout hook on element re-connection. I'll have a look into this one. :+1:

**Comment by ragnarnevries** [comment]
In trainings this would significantly improve the "first impression" for users.

**Comment by nikku** [comment]
Gets addressed via bpmn-io/bpmn-js#718

**Comment by pinussilvestrus** [comment]
Closed via aafbda44795d7e2c0bb00aa8a4bbe81956b17b1b
