### ISSUE TITLE
Export DMN as .ods, .xlsx or PNG

### ISSUE THREAD

**Issue by pvermeil** [camunda/camunda-modeler#673]
It could be a good idea to get export features for DMN tables, typically to share it with non technical collaborators as sheet files, or as PNG for illustrate our documentations.

Thanks for taking note, and thanks to camunda team for their great job.

**Comment by nikku** [comment]
Unfortunately we don't have the resources to act on this topic any time soon.

We'd appreciate contributions and/or pointers to related work on this, though.

**Comment by HollyMGiles** [comment]
Please resurrect this requirement!  We need confirmation from business users on our logic and have captured it all in DMN tables. They have requested PDF versions that they can show to their leadership but we can't do it, and therefore are recreating everything in Excel.

**Comment by nikku** [comment]
Adding DMN view / edit support in [Cawemo](https://cawemo.com/), our cloud-based, collaborative and business user friendly modeling environment is on our roadmap.

Consider Cawemo to bring business users and technical stakeholders closer together, not PDF support.
