### ISSUE TITLE
DRD: Opening Literal Expression shows edit sign on file tab though nothing changed

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-modeler#675]
Reproduce:
1. Create new DRD
2. Place Literal Expression 
3. save dmn file
4. click on literal expression button to open it
5. click "show drd"
5. notice that the circle for changes is shown on file tab though nothing changed

**Comment by nikku** [comment]
This must be addressed via https://github.com/camunda/camunda-modeler/issues/706.

Closing this ticket as a duplicate.
