### ISSUE TITLE
DRD: Expression Language changes gone sometimes or not reflected in xml

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-modeler#677]
I had an issue today, that when editing script in expressions in a DRD and I saved the file and went back to the script it was suddenly gone.
Also I noticed that sometimes removing the variable type wasn't reflected in the XML.
There was no error on the log (at least the console did not open).
I am unable to reproduce it at the moment with the same DRD. The only difference was that I was connected to an external screen.
I will try to reproduce this again but wanted to file the issue in case anyone experienced the same problem.

**Comment by nikku** [comment]
Did you manage to reproduce it? Otherwise I'd close this issue, as we don't have a proper way to reproduce it ourself.

**Comment by felix-mueller** [comment]
Cannot reproduce it at the moment, so we can close this for now.
