### ISSUE TITLE
BPMN - Change from interrupting escalation boundary event to non-interrupting escalation boundary event properties lost

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-modeler#678]
Reproduce:
1. Model Task
2. Place Interrupting Escalation Boundary Event on Task
3. Add Escalation Name & Code
4. Change to Non-Interrupting Escalation Boundary Event
5. Notice that all properties are gone

Expected:
1. Model Task
2. Place Interrupting Escalation Boundary Event on Task
3. Add Escalation Name & Code
4. Change to Non-Interrupting Escalation Boundary Event
5. Notice that all properties are still there

**Comment by nikku** [comment]
This has been substantially improved via https://github.com/camunda/camunda-modeler/commit/2415cf9ba925b1b303923187c3556db468a0db0f / `bpmn-js@5.0.0-beta`.

Two related problems remain, I've created separate issues for them: https://github.com/camunda/camunda-modeler/issues/1463, https://github.com/camunda/camunda-modeler/issues/1464.
