### ISSUE TITLE
Property loss after copying/morphing event element

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#681]
**Reproduce**
- add a property to an event
- copy or morph the element

**Problem**
- properties of the copied/morphed element get lost 

**List of properties**
- Retry Time Cycle
- Listeners
- Input/Output Mapping

**Hint**
this issue is related to https://github.com/camunda/camunda-modeler/issues/586 and https://github.com/camunda/camunda-modeler/issues/540

**Comment by nikku** [comment]
This is fixed via https://github.com/camunda/camunda-modeler/commit/2415cf9ba925b1b303923187c3556db468a0db0f.
