### ISSUE TITLE
Sequence Flow not connected with the element edge

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#683]
- Given
  - I want to reconnect a sequence flow to another element
- When 
  - I drop the sequence flow tip on the outline of the element
- Then
  - The sequence flow is visually not attached to the element. There is a gap.
- Expected
  - The sequence flow tip is connected to the element edge. Without gap.

![modeler_snapping_fool](https://user-images.githubusercontent.com/2777965/31379405-6d479462-adae-11e7-9081-7c54e8863ba5.gif)

**Comment by nikku** [comment]
Needs fix in https://github.com/bpmn-io/bpmn-js/issues/529.

**Comment by nikku** [comment]
Closing this in favor of https://github.com/camunda/camunda-modeler/issues/1624.
