### ISSUE TITLE
how to use bpmn-js

### ISSUE THREAD

**Issue by flynetgao1** [camunda/camunda-modeler#685]
how to use bpmn-js  requrie module  ?   in  express?  angular ? vue?

**Comment by nikku** [comment]
What exactly would you like to achieve? What did you try?

If you got a specific questions regarding how to use our libraries, ask it in [our forums](https://forum.bpmn.io) or the specific [project repository](https://github.com/bpmn-io).

**Comment by flynetgao1** [comment]
thanks to replay me , i used it to vue .

**Comment by flynetgao1** [comment]
thanks to reply me , i used it to vue .
