### ISSUE TITLE
Export to Image from commandline

### ISSUE THREAD

**Issue by windischb** [camunda/camunda-modeler#687]
Hi!

Is it possible to export the BPMN Model from commandline?
I would like to integrate this in our CI Pipeline.
Everytime i push the Model to our GitLab Server, a new Image should be created for the Wiki.

**Comment by nikku** [comment]
That functionality does not exist in the Camunda Modeler. We'll probably not add it any time soon, too.

Please turn to the [bpmn.io forums](https://forum.bpmn.io) to ask this question and see if someone already created a CLI utility based on [bpmn-js](https://github.com/bpmn-io/bpmn-js).
