### ISSUE TITLE
new line breaks on task names should prioritize hyphens and underscores

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#692]
Current example:
![screen shot 2017-10-29 at 2 14 15 pm](https://user-images.githubusercontent.com/1994838/32146795-8ae48886-bcb3-11e7-8371-cb42206502b8.png)

what would be great!

![screen shot 2017-10-29 at 2 15 23 pm](https://user-images.githubusercontent.com/1994838/32146804-9eb168ac-bcb3-11e7-8c48-e3e8942f418e.png)

Basically if there was a hyphen or underscore it should prioritize these for new line breaks to make the task name more human readable.

**Comment by StephenOTT** [comment]
through hyphens seem to have prioritization

![screen shot 2017-10-29 at 2 17 38 pm](https://user-images.githubusercontent.com/1994838/32146845-fe8d8eae-bcb3-11e7-957f-f5ce70f3c3ba.png)

@nikku can you confirm this?

**Comment by nikku** [comment]
We appreciate a contribution to improve the existing behavior. The right place to do this is [diagram-js](https://github.com/bpmn-io/diagram-js/blob/master/lib/util/Text.js).
