### ISSUE TITLE
Can't run camunda-modeler

### ISSUE THREAD

**Issue by yregaieg** [camunda/camunda-modeler#693]
I am on a Ubuntu 16.04 variant, I downloaded and installed camunda-modeler but couldn't get it to work.

When I try running it from installation path using CLI I get this output :

```
yregaieg@younes-laptop:/opt/camunda-modeler$ ./camunda-modeler 
./camunda-modeler: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

Since the message suggested a missing lib, I tried to install it but it was already there:

```
yregaieg@younes-laptop:/opt/camunda-modeler$ locate libgconf-2.so.4
/usr/lib/x86_64-linux-gnu/libgconf-2.so.4
/usr/lib/x86_64-linux-gnu/libgconf-2.so.4.1.5
```
Any tip/workaround is appreciated !

**Comment by menski** [comment]
I guess you are missing the gconf2 package?

```
sudo apt-get install gconf2
```

**Comment by yregaieg** [comment]
@menski gconf2 is already there... but It seems that I got the wrong distribution package : switched to x64 and every thing seems fine now !

Thanks for your reactivity !

**Comment by yregaieg** [comment]
It would've been nice though if I got an expressive error message or something...
