### ISSUE TITLE
Integrate new dmn-js

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda-modeler#697]
__Tasks__

* [x] dmn-js is integrated and does not break the modeler
* [x] basic operations (change detection, switching between dmn-js and XML work

**Comment by nikku** [comment]
Test fail on CI due to missing links between the modeler and our unreleased DMN libraries.

You need to link all projects 

* dmn-js
* dmn-js-shared
* dmn-js-decision-table
* dmn-js-drd

for the modeler to function.

**Comment by nikku** [comment]
Closed but not merged?
