### ISSUE TITLE
Minimap crashes when updating element with attacher

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#698]
See related [issue in JIRA](https://app.camunda.com/jira/browse/SUPPORT-3811) and [diagram-js-minimap issue](https://github.com/bpmn-io/diagram-js-minimap/issues/11).

**Comment by mburke84** [comment]
Related Support case: [SUPPORT-3811](https://app.camunda.com/jira/browse/SUPPORT-3811)
