### ISSUE TITLE
Compensation: waitForCompletion="false" is currently unsupported, but default in Modeler

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#699]
compensateEventDefinition/@waitForCompletion should either be "true" by default or not shown/set at all.

See also: https://docs.camunda.org/manual/7.7/reference/bpmn20/events/cancel-and-compensation-events/#intermediate-throwing-compensation-event

"Current limitations: waitForCompletion="false" is currently unsupported."

**Comment by falko** [comment]
When a throwing compensation event is created through the Modeler the attribute waitForCompletion is not set in the XML: 

```xml
<bpmn:compensateEventDefinition />
```

This is good since the default value is true anyway. However, the checkbox shows as false in the property panel.

**Comment by falko** [comment]
screenshot:
![2017-11-28 - seleccion 001](https://user-images.githubusercontent.com/40038/33323690-97e5078e-d44d-11e7-84f8-44928f001634.png)

**Comment by nikku** [comment]
So to summarize: `true` is the default value. The checkbox should be checked per default. Correct?

**Comment by nikku** [comment]
This is a bug in our meta-model. We're not correctly setting the default value for `bpmn:CompensateEventDefinition#waitForCompletion`. Cf. https://github.com/bpmn-io/bpmn-moddle/commit/f77235f1709584aa1cacb30d1e8fdf6cdf102b8d.

**Comment by nikku** [comment]
Will be fixed with the upgrade to `bpmn-js@0.25.x`.

**Comment by falko** [comment]
Awesome, thank you!

**Comment by nikku** [comment]
Should be fixed with Camunda Modeler `v1.12.0-alpha1`.
