### ISSUE TITLE
Property Panel jumps to fill the entire screen and cannot be resized

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#701]
Sometimes when resizing the Property Panel it jumps to fill the entire screen and cannot be resized anymore:
![2017-11-28 - camunda modeler 002](https://user-images.githubusercontent.com/40038/33329406-c294f476-d45c-11e7-9e32-294bc6f85499.png)

Customers have experienced this, too.

**Comment by nikku** [comment]
Did you discover a reliable way to reproduce this behavior?

**Comment by falko** [comment]
What I can definitely reproduce, is manually dragging it to the left end of the screen until I can't drag it back again. That alone feels like a bug. If we would prevent dragging the handle of the property panel outside the visible screen area, we might prevent the jumping behavior as well, even if we don't know how to reproduce it.

Wait, I noticed something:
The moment I start dragging the property panel it expands to the left of my mouse pointer. With a smaller window, this effect increases. I tried with today's nightly and without any plugins, but still the same.

![2017-11-28 property panel resize bug 03](https://user-images.githubusercontent.com/40038/33340900-9c19e128-d47d-11e7-9b74-6def812a7490.gif)

**Comment by huksley** [comment]
Hello I have the same behaviour which is reproducible 100%.
![image](https://user-images.githubusercontent.com/1594349/33884873-7fbc644e-df52-11e7-86cb-d03659f3af53.png)

Environment:
  * Linux Mint 18.2
  * Second monitor (non-primary)

Steps to reproduce:
  * Move window to second monitor
  * Try to drag properties panel handle for resize
  * Properties panel immediately resizes to full window width

If doing the same on primary monitor everything works OK.

**Comment by nikku** [comment]
Interesting. Works fine on primary monitor?

@falko You're using the secondary monitor, too?

**Comment by huksley** [comment]
> Interesting. Works fine on primary monitor?
Yep. Saves state to file, which I need to remove to use Camunda Modeler again.

**Comment by falko** [comment]
I have this on a single monitor setup as well.

**Comment by tewald** [comment]
Happens to me too, when on secondary monitor.
Primary monitor works fine.

OS: Fedora 27, using xorg

**Comment by falko** [comment]
@nikku I still have this bug with the latest nightly. You could try reproducing it by making the window a lot smaller than your screen size. Do you see any weird behavior, in the moment when you start resizing the property panel?

**Comment by nikku** [comment]
This is fixed with Camunda Modeler v1.13.1.
