### ISSUE TITLE
Wrong 'Edit' menu on direct editing activation

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#708]
Activating direct editing causes all instantiated editors to update the window menu due to the fact that they all globally listen to 'input:focus' events. The order in which they update the menu is not deterministic and so it happens that after activating direct editing in a DRD modeler the BPMN modeler is the last one to update the edit menu resulting in wrong menu entries.

**Comment by nikku** [comment]
Who globally listens to this? Only one editor should be active at a time, listening to anything.

**Comment by philippfromme** [comment]
This is not an issue anymore thanks to https://github.com/camunda/camunda-modeler/commit/d89c50cb52e7835bc602883d5229da77e2bcbb7c#diff-57e075e7ecec913e23ddff72c76bf914 and https://github.com/camunda/camunda-modeler/commit/2c6a7d520fcd0cf3dd646daf6af216154fc00c24#diff-64ba97946e52a9cd45fbd4ccdf9de36c.
