### ISSUE TITLE
Inserting line breaks results in text duplication

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#709]
- Given
  - Cell content: **foo bar**
- When 
  - I remove the whitespace and press (accidently) ENTER and press BACKSPACE and press TAB
- Then
  - the substring **bar** will be duplicated. Result "foobarbar"

Feature?

**Comment by nikku** [comment]
Due to the use of `dangerouslySetInnerHtml` this introduced a XSS hole:

![image](https://user-images.githubusercontent.com/58601/34988896-aca457b2-fac0-11e7-903c-69dc36d8c4b8.png)
