### ISSUE TITLE
Cursor lost after double double click (DRD)

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#710]
- Given
  - I've entered the direct editing mode in the DRD view via double click on an element
- When 
  - I perform a second double click in the element
- Then
  - The cursor is lost and I cannot continue to edit the element text

**Comment by nikku** [comment]
This is related to the integration of dmn-js into the Camunda Modeler.

**Comment by mschoe** [comment]
Cannot reproduce this with the latest release 3.0.0-beta-0. @nikku feel free to close the issue
