### ISSUE TITLE
Automatically create message flow in correct direction

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda-modeler#714]
Scenario:

* Create a message flow connection from a message receive to a message throw event

Current behavior:

* This is not possible because it is the wrong direction
* I have to start over and create the flow in the right direction

Preferred behavior:

* Modeler creates the connection but automatically corrects the flow direction from throw to receive event

Context:

* Assuming the user knows the difference of throw and catch, this is a convenience feature that saves time.
* Users not knowing the difference may be surprised why the direction is reversed. I think this is acceptable.

**Comment by nikku** [comment]
> Modeler creates the connection but automatically corrects the flow direction from throw to receive event

From my point of view, this violates the _don't make me think_ property:

* As a user knowing BPMN I would not even attempt to do this (as it is forbidden).
* As a user _not_ knowing BPMN I see things to _just work_ while in fact the modeler inverted my intend (message flowing from source to target).

What I could think of is some advanced assistance, telling the user that _X_ is not possible but he could do _Y_ instead. _Y_ in the scenario you describe could be "Make source a send event and target a receive task", too, just to show one more possible intend the user may have.

**Comment by nikku** [comment]
Please cross link additional feedback on this topic, if you got some.

**Comment by ThorbenLindhauer** [comment]
I noticed this while modeling myself. I modeled a diagram with a lot of message events to describe the interaction of two systems. As a user knowing BPMN I actually attempted to do this because I was lazy :). I get your point, though.

**Comment by nikku** [comment]
> edit: elaborating on lazy: It is more convenient to start the message flow at the event where the mouse pointer is nearest to.

It is always possible to implement a Keyboard shortcut that triggers the creation of the _inverse_ connection. You'd need to know the shortcut (you're an expert) and newbees don't get confused.

**Comment by nikku** [comment]
Closing this as won't fix for now. We'll reconsider this feature request if we receive additional feedback on this issue.
