### ISSUE TITLE
I can deploy a process directly from the Camunda Modeler

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#718]
As a Camunda Modeler user

*Given:*
I model a process

*Then:*
* [ ] I can click a button in the menu bar to deploy directly the process to the process engine.
* [ ] I can configure the process engine API url.

*So That:*
I don't need to write any Java code to bundle a process application.

**Comment by romansmirnov** [comment]
@siffogh,

I've made two fixes:

1) prevent re-rendering when the input field gets focused (see https://github.com/camunda/camunda-modeler/commit/bfe95b6b675df43c6ee3dcb0131f5b8c7f0468ce)
2) storing of the configured endpoint in workspace (see https://github.com/camunda/camunda-modeler/commit/25bd9c880dd839bfdd2d6a111ffb9e954a8c5881)

Re 1) We should ask @nikku and @philippfromme if this quick fix is okay.

Best,
Roman

**Comment by nikku** [comment]
@siffogh This is ready for a second round with [numerous comments](https://github.com/camunda/camunda-modeler/commit/c9c5a5b02db57fd3c45883ac0ab2049060bda93c#comments). 

In general, I'd ask you not to include code-reformatings or empty line additions / removals in places where you did not change things. This reduces the amount of noise in your changes.

We can perform code re-formating, if we agree on a particular code style.

**Comment by nikku** [comment]
I've found another bug / issue: 

* deployment works with saved diagrams only. We should either work around this limitation _or_ automatically save the diagram pre-deploy.

**Comment by siffogh** [comment]
@nikku Thanks for the review hints. Please check the new commit.
