### ISSUE TITLE
I get feedback when source or target attribute of <camunda:in/> element has trailing whitespace

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda-modeler#720]
__Context:__

* BPMN Properties Panel

__Expected behavior:__

* [ ] Show a validation error message on whitespace in `source` or `target`
* [ ] Allow whitespace in `source expression`

---

Cf. [SUPPORT-3961](https://app.camunda.com/jira/browse/SUPPORT-3961)

**Comment by nikku** [comment]
We've decided to validate instead of automatically trimming whitespace, as the later was too much magic.

**Comment by nikku** [comment]
Fails locally and on CI.

**Comment by nikku** [comment]
I've fixed the minor issue that made the stuff fail on CI.

Further change is needed though:

* We must not validate source expression, as it may contain whitespace: `foo(a + b)`
* We must validate source / target, these are variables that must not contain whitespace: `abCD`

I've updated the issue description accordingly.
