### ISSUE TITLE
Drag and Drop problem at the Camunda Modeler

### ISSUE THREAD

**Issue by mehmetgursul** [camunda/camunda-modeler#724]
Hello,
I have started to learn Camunda BPM for few days. I watched “Camunda Tutorial for Java Developers” video (https://vimeo.com/235728986) by Niall Deehan. It was a really nice explanation about Camunda, thanks first of all.

According to this video, when I wanted to drag and drop “Process ended” element into another place, I couldn’t put it and bpmn model looked following at the Camunda Modeler:
![camundamodeler](https://user-images.githubusercontent.com/9787563/35483142-ab1b97be-044f-11e8-8380-6d490687bd2d.png)

Regards,
Mehmet

**Comment by nikku** [comment]
> I wanted to drag and drop “Process ended” element into another place, I couldn’t put it and bpmn model looked following at the Camunda Modeler.

Into which "other place" did you want to put it?

**Comment by mehmetgursul** [comment]
Hi,
I did the same action explained in "Camunda Tutorial for Java Developers" video https://vimeo.com/235728986. (Action started second is 6:39).

Regards,
Mehmet

**Comment by nikku** [comment]
Please try to reproduce the issue you're seeing in a way that allows us to repeat it (and fix it).

![foo.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54c634fe2a007b0300531f68/125516c66e82c728ace21e0d46ee9b9561cec1b99de6b546a749b2ce6b1371272c01fa7e7587b12dba167e500b5f4eae415c0d43afeb9539e4e76224d50152a7842f4d7ed43c18a6b9871eb802bb248c4d86bebf895e8d.gif)

I could not reproduce you're bug report.

**Comment by mehmetgursul** [comment]
Hello,
I tried again, but I also couldn't reproduce the bug. It was a non-deterministic bug, I mean not always happening. If I again reproduce, I 'll report with its XML code also, for better understanding.

Meanwhile, when I tried to reproduce the bug, I found another bug which was not related to this issue. I'll open another issue to explain. 

Thanks for your reply.
