### ISSUE TITLE
After removing element its text annotations remained at the model

### ISSUE THREAD

**Issue by mehmetgursul** [camunda/camunda-modeler#725]
Hi,
Steps to reproduce:
1. Add element.
2. Add text annotations to added element.
3. Remove added element.
4. Element removed successfully from the model, but its text annotations remained at the model.

**Adding annotations:**

![addingannotation](https://user-images.githubusercontent.com/9787563/35568353-b9286298-05d9-11e8-984c-a3fc691a8410.png)

**After deleting element:**
![annotationremainedafterdeletingelement](https://user-images.githubusercontent.com/9787563/35568388-d896b5e4-05d9-11e8-9d9e-7577a5e0e027.png)

**Note:** I searched similar bug at the existing issues. I could not find a similar one. Meanwhile, this can be a feature, not a bug, if a user removes element accidentally. On the other hand, there is a working very well undo mechanism supported by Camunda Modeler:)

**Comment by nikku** [comment]
This is a feature as the relationship between Text Annotations and elements is not _containment_. The following may be rarely used but is perfectly fine BPMN:

![image](https://user-images.githubusercontent.com/58601/35582518-5a4265ba-05ef-11e8-8822-d282bcaf29e4.png)

Use multi-select + `DEL` to remove them together.

**Comment by nikku** [comment]
Thanks for reporting though. Once we get enough user feedback on this we will re-assess our current behavior.

**Comment by mehmetgursul** [comment]
Thank you for your information. I thought that relationship between "element" and "text annotation" is a **composition** but it is an **aggregation** you mean. And you're right it is a nice feature.

I'll share my finding if I find new issues. Thanks again for this good tool:)
