### ISSUE TITLE
Editing a call with comma doesnt work in new DMN Editor

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-modeler#728]
1.12.0-alpha2

1. Open new DMN Table
2. Click on Edit Icon in first cell
3. Enter Values like "abc","def" and hit enter

See that nothing happens, in console we get a type error
"Cannot read property 'type' of undefined
at SimpleStringEditContextMenuComponent.addUnaryTestsListItem()

Note: Also on outside click the box closes, but nothing happens, values are not persisted.

**Comment by nikku** [comment]
We'll have a look at this :thumbsup:

**Comment by philippfromme** [comment]
This is fixed in dmn-js@2.
