### ISSUE TITLE
I get feedback about deployment

### ISSUE THREAD

**Issue by siffogh** [camunda/camunda-modeler#730]
As a Camunda Modeler user

*Given:*
- I model a process.
- I click on deployment button.

*Then:*
* [x] I get feedback whether the deployment was successful or not.

*So That:*
- I know whether my deployment was successful or not.
- If there is an error, I can see what it is and fix it.

**Comment by nikku** [comment]
Suggestion: Keep the deploy dialog open until a response is received; display the deploy response (positive or negative) within the modal. The current behavior (dialog closing while stuff still happens in background) is not intuitive for me.

**Comment by siffogh** [comment]
@nikku I added your suggestion in #729

**Comment by siffogh** [comment]
@philippfromme @nikku The logic for displaying system dialogs and html modals seem to be coupled, i.e. displaying system dialogs hides modals (and vice versa). 
This causes an issue particularly in this case since: deploying an unsaved new file opens the save file system dialog which closes the deployment modal leaving the used without any feedback about the status of the deployment.
Do you suggest opening a separate issue to change the coupling between display system dialogs and html modals? Or should we change the save behaviour when deploying processes?

**Comment by nikku** [comment]
There is two options:

* ensure saving using the system dialog happens before the modal is opened
* decouple both.

I'd go with option (1): safe before opening the deploy dialog.

Why would you open the deploy dialog anyway if the diagram is not saved (and thus not deployable) yet?

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/0d1708447fcf0511bb57c2360f1d1f98ab97a3ac.
