### ISSUE TITLE
Different entries shown for connection and connection label

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#731]
bpmn-js-properties-panel issue: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/254

Expected behavior:
* same entries shown for connection and connection label

Actual behavior:
* different entries shown

__Tasks__
* [x] show all entries for labels and connections (verify message flow, sequence flow)

---

Related to [SUPPORT-4053](https://app.camunda.com/jira/browse/SUPPORT-4053).

**Comment by mburke84** [comment]
Related Support Ticket [SUPPORT-4053](https://app.camunda.com/jira/browse/SUPPORT-4053).

**Comment by nikku** [comment]
From my point of view this is the expected behavior. See [my comment on #254](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/254#issuecomment-364063491).
