### ISSUE TITLE
I can deploy a DMN file directly from the Camunda Modeler

### ISSUE THREAD

**Issue by siffogh** [camunda/camunda-modeler#733]
As a Camunda Modeler user

*Given:*
I create a DMN decision table or decision requirements graph

*Then:*
* [x] I can click a button in the menu bar to deploy directly the DMN file.
* [x] I can configure the process engine API url.

*So That:*
I don't need to write any Java code to bundle a process application.

**Comment by siffogh** [comment]
@nikku since this is based on 730, it is rebased on it. Therefore, if this ever gets merged to master all what is needed to do is to drop the 730 commit before merging.

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/b09ff8daa2ec61dc25331dedde2a4018ffcb0cd4.
