### ISSUE TITLE
I can deploy a CMMN file directly from the Camunda Modeler

### ISSUE THREAD

**Issue by siffogh** [camunda/camunda-modeler#734]
As a Camunda Modeler user

*Given:*
I create a CMMN case

*Then:*
* [x] I can click a button in the menu bar to deploy directly the CMMN file.
* [x] I can configure the process engine API url.

*So That:*
I don't need to write any Java code to bundle a process application.

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/2c6a7d520fcd0cf3dd646daf6af216154fc00c24.
