### ISSUE TITLE
BPMN ID in <bpmn definitions> is always 'Definitions_1'

### ISSUE THREAD

**Issue by steffinger** [camunda/camunda-modeler#736]
When creating a new BPMN diagram with camunda-modeler, the ID attribute always is 'Definitions_1' like in the prototype 'initial.bpmn' file. 

Wanted behaviour: 
The ID should be changed to a randomized unique ID, similar to the functionality in bpmn-js 

I see this in camunda modeler from the master branch and version 1.11.3. Other versions were not tested.

**Comment by nikku** [comment]
A great suggestion. Will be adressed via https://github.com/camunda/camunda-modeler/pull/737.

**Comment by steffinger** [comment]
Thanks. This was really very fast. 
I just built and tested the branch '736-random-diagram-ids' under linux and it works. 
When I create a new diagram (bpmn, dmn, cmmn) they get a random id after the prefix 'Definitions'
Works as expected.

Thanks a lot for the effort.

**Comment by nikku** [comment]
We'll close this once the branch hits `master`. Thanks for the double check.
