### ISSUE TITLE
Deployment configuration with authentication options

### ISSUE THREAD

**Issue by tewald** [camunda/camunda-modeler#741]
Hi!

I'm using the dev version, testing the deploy functionality, and it works as expected.
But here our camunda rest API has a filter that uses JWT to set user and tenantId for the request.
So, to make it work, I added the Authentication header, with the bearer token, and it's all good again.
I think it should be nice to set some auth options, like in Insomnia REST client, for example.
I'm hacking some code here to add at least basic and token auth options to the configuration modal.

My JS-foo is not the strongest, but I did manage to do something like this:
![no](https://user-images.githubusercontent.com/1534061/36538638-0278e20c-17b3-11e8-8b8e-32983d0a2394.png)
![basic](https://user-images.githubusercontent.com/1534061/36538645-06def7b4-17b3-11e8-84dc-7171abb22918.png)
![bearer](https://user-images.githubusercontent.com/1534061/36538654-0b4d90da-17b3-11e8-9f8e-60da1f3e63d7.png)

What are you thoughts?

(On a side note, it could be nice to also load the diagrams from the rest api, making the modeler a full-online tool for camunda)

Thanks!
Thomas

**Comment by nikku** [comment]
Hey @tewald. Could file a PR adding the changes?

We're still in the process of discussing which authentication options to offer, especially given that we (Camunda) don't impose any constraints to our users. 

The two options you provide seem like two popular ones to go for.

**Comment by tewald** [comment]
OK, my fault.
I'll fix the CI errors. :-(

**Comment by nikku** [comment]
Thanks for the PR. We'll merge it with one of our next releases.

**Comment by volodya327** [comment]
Hi, Comunity is still waiting for this fix. Could you tell me, please, about your plans/future relases ?

**Comment by nikku** [comment]
We cannot promise an exact availability date of this feature but rest assured this will land in one of the next Camunda Modeler releases.

**Comment by nikku** [comment]
Integrated your work into the `next` branch. Our upcoming modeler will feature deployment against authenticated engines :tada:.

![screely-1544532777363](https://user-images.githubusercontent.com/58601/49802082-34cd1f00-fd4c-11e8-919e-18abdde2756d.png)

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/906.
