### ISSUE TITLE
Deployment without tenant Id gets empty string instead of null on camunda

### ISSUE THREAD

**Issue by tewald** [camunda/camunda-modeler#743]
Hi,

When deploying a diagram without informing a tenant Id in the "Deployment Configuration" modal, the process is deployed using an empty string as tenant Id.
This way, a process that should be visible to all tenants does not appear in REST API or camunda cockpit.

Thanks,
Thomas

**Comment by nikku** [comment]
@siffogh Could you have a look at this?
