### ISSUE TITLE
Deploy should give an option to deploy only changed resources

### ISSUE THREAD

**Issue by tewald** [camunda/camunda-modeler#744]
Hi!

Every time I deploy a process, a new version is created on camunda, even if nothing changes.
Reading the docs, there's a parameter called **deploy-changed-only** that checks if anything changed and deploys only the changed resources.
Maybe a checkbox in the deploy modal should be enough?

Thanks!
Thomas

**Comment by nikku** [comment]
This should probably be the default behavior, right?

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/17065ec475932ac396ef7b5bea88d67b369ca378.
