### ISSUE TITLE
Missing plugins when opening modeler trough double click on file

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#746]
Reproduce:

1. Open a .bpmn/.dmn/.cmmn file through double click

Expected Beavior:

* plugins available

Actual behavior:

* plugins missing

---
Support ticket: https://app.camunda.com/jira/browse/SUPPORT-4109

**Comment by nikku** [comment]
Please fix the plug-in resolution according to my comment.

Is it possible for us to write a test-case for one or more scenarios here?
