### ISSUE TITLE
Adjust styling for deploy functionality

### ISSUE THREAD

**Issue by siffogh** [camunda/camunda-modeler#751]
The current status messages in the deployment functionality resemble Bootstrap alert notifications. 
Instead, we can restyle them to get something that looks more like the status alerts in the token simulation plugin.

![success-status](https://user-images.githubusercontent.com/4761023/36841011-2ee0c4c4-1d47-11e8-99e1-4c9ba1f16caa.png)
![error-status](https://user-images.githubusercontent.com/4761023/36841023-367b195a-1d47-11e8-9d2c-5b7fc2b4a727.png)

**Comment by nikku** [comment]
Closing this, as we got no intention to work on this issue as a standalone topic.
