### ISSUE TITLE
external forms + SpringAutoDeployment

### ISSUE THREAD

**Issue by lewi12s** [camunda/camunda-modeler#755]
Hi,
Why contextPath is null when SpringAutoDeployment is used to deploy bpmn process?

Form http response: {"key":"app:forms/custom-form.html","contextPath":null}
url: http://localhost:8080/camunda/api/engine/engine/default/task/9fd23d72-2cf7-11e8-acb5-f85971ac21c4/form

I am using camunda-webapp-tomcat-standalone (version 7.8.0) + bpmn file + external forms (trying to get it working)

Regards

**Comment by nikku** [comment]
Not sure how this is related to the Camunda Modeler? A better place to ask would be the [Camunda forum](https://forum.camunda.org).
