### ISSUE TITLE
Copy paste in DMN decision table on Mac not working

### ISSUE THREAD

**Issue by nevries** [camunda/camunda-modeler#758]
Modeler-Version: 1.12.0-alpha-5
OS-Version: macOsHigh Sierra 10.13.3 (17D102)

Neither the CMD-C CMD-V shortcuts nor the context menu work for copy/paste cell content in the DMN Table editor.

It works in Safari on: https://demo.bpmn.io/dmn/new

**Comment by nikku** [comment]
Will be addressed via https://github.com/bpmn-io/dmn-js/issues/338.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/079b05ec69b8c86e174afd6829babc49064fc277.
