### ISSUE TITLE
XML character entities (&gt; &lt;) are diplayed raw when serialized in CDATA

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#760]
The decision table editor and the literal expression editor do not decode XML character entities like `&gt;` or `&lt;` when they are included in `CDATA` section in the XML.

![2018-03-23 - camunda modeler 002](https://user-images.githubusercontent.com/40038/37842647-f297980c-2ec2-11e8-9a6c-bb3b9203ad12.png)

![2018-03-23 - camunda modeler 003](https://user-images.githubusercontent.com/40038/37842956-d6c16e0e-2ec3-11e8-9731-7962a1936084.png)

Tested with today's nightly build using DMN TCK models, e.g.:
https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-2/0004-simpletable-U/0004-simpletable-U.dmn
https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-3/0013-sort/0013-sort.dmn

**Comment by nikku** [comment]
Characters inside `CDATA` are not meant to be decoded. 

The diagrams however contain to-be-decoded entities outside a CDATA section. The fact that we don't decode them is due to a bug in our underlying `moddle-xml` library (cf. https://github.com/bpmn-io/moddle-xml/issues/30).

**Comment by falko** [comment]
@nikku thank you for the feedback. I double checked with the [XML CDATA Spec](https://www.w3.org/TR/REC-xml/#sec-cdata-sect) and will file a bug for the DMN TCK.

**Comment by falko** [comment]
I created a [TCK issue](https://github.com/dmn-tck/tck/issues/133) and noticed that the original TCK files don't have CDTATA-sections. They seem to be introduced by our Modeler. In that case there are two issues here:
1. The [missing decoding of character entities](https://github.com/bpmn-io/moddle-xml/issues/30) which you already fixed.
2. The introduction of CDATA in the XML, which is legal but not ideal for any kind of diffing, merging or roundtripping.

**Comment by falko** [comment]
Keith commented to me:
> It is my opinion that one should never use CDATA at all, because there is no adequate way to escape the end sequence (]]>) if it was to occur in the text. If you are generating the XML with a program, just go an encode the string properly.

and I agree because that sequence can easily occur in FEEL expressions.

**Comment by nikku** [comment]
> They seem to be introduced by our Modeler. In that case there are two issues here:

Exactly. This is what I meant with this statement:

> The diagrams however contain to-be-decoded entities outside a CDATA section. 

What you mention needs to be addressed in our underlying XML infrastructure. I've created https://github.com/bpmn-io/moddle-xml/issues/31 to track this.

**Comment by xzxiaoshan** [comment]
The forced removal of CDATA has actually caused problems for more developers. This should be a choice decision, not a default forced decision.
[https://forum.bpmn.io/search?q=CDATA](https://forum.bpmn.io/search?q=CDATA)

**Comment by xzxiaoshan** [comment]
I think this issue has been raised by developers from all sides. The author should consider whether their initial decision was wrong?
Using a configuration to determine whether to use CDATA seems to be a more appropriate decision.

**Comment by nikku** [comment]
> I think this issue has been raised by developers from all sides. 

What is "all sides", is it [this link](https://forum.bpmn.io/search?q=CDATA)? We usually reach out to anyone asking, but I have not received a strong reason why CDATA should be preferred.
