### ISSUE TITLE
I can configure a payload for throwing signal events

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda-modeler#763]
**Given:**
- a throwing signal event (intermediate throw event or end event) is modeled

**When:**
- the throwing signal event is selcted

**Then:**
- it is possible to configure a payload

**So That:**
- the configured payload is passed to catching signal event when the throwing signal event is executed during the runtime

**Hint:**
- it is possible to definie multiple payloads (i.e. paramters)
- each parameter either has a source or sourceExpression and a target
- as a alternative to configure parameters it is possible to pass all variables
- when selecting "all variables" as source of a parameter, it is possible to pass only local variables
- the resulting xml should look like this:
```xml
<intermediateThrowEvent>
  <signalEventDefinition signalRef="newCustomerSignal">
      <extensionElements>
          <camunda:in source="throwingVariableName" target="catchingVariableName" />
          <camunda:in sourceExpression="${X + 5}" target="Y" />
          <camunda:in variables="all" />
          <camunda:in variables="all" local="true" />
          <camunda:in businessKey="${execution.processBusinessKey}" />
      </extensionElements>
  </signalEventDefinition>
</intermediateThrowEvent>
```
- it is the same apprach like it is already implemented for call activity input parameters

**Comment by ThorbenLindhauer** [comment]
Could it be that this was not implemented for the business key property? The business key checkbox that we have in the case of call activities seems to not be there for signal throw events. Asking for the guy in https://forum.camunda.org/t/setting-business-key-when-signalling-an-event-in-modeler/8854. I can't find it either.

**Comment by kornysietsma** [comment]
Bump - this definitely seems to be a problem - you can't set the business key via `<camunda:in businessKey="#{execution.processBusinessKey}" />` in the modeller.  And if you set it in the XML it's not visible in the modeller.

Is it worth re-opening this issue or should I raise a new issue?

**Comment by nikku** [comment]
Please open a separate issue and attach concrete steps to reproduce.
