### ISSUE TITLE
Not allowed to load local resource.

### ISSUE THREAD

**Issue by TheoVitkovskiy** [camunda/camunda-modeler#768]
When I try to run `npm run dev` on the version 1.12.0, the app boots, but then inside the dev tools, I see the message:
Not allowed to load local resource: file:///C:/Users/Theo/Desktop/OpenSource/camunda-modeler/public/index.html

And if I go to the camunda-modeler directory, I don't see that any public folder was created. 
Here are the last lines in the console before the Electron window opens.

`[cli] [WARN] cannot open directory C:\Users\Theo\Desktop\OpenSource\camunda-mode                                               ler\app\develop
[cli] [WARN] ENOENT: no such file or directory, lstat 'C:\Users\Theo\Desktop\Ope                                               nSource\camunda-modeler\-r process' C:\Users\Theo\Desktop\OpenSource\camunda-mod                                               eler\-r process`

I'm using Windows 10 x64.

**Comment by philippfromme** [comment]
I can not reproduce this issue using Windows 10 x64.

**Comment by nikku** [comment]
@TheoVitkovskiy What is the actual issue you'd like to report?
