### ISSUE TITLE
Task description not being saved, when chosing task type

### ISSUE THREAD

**Issue by theelectricsoul** [camunda/camunda-modeler#770]
**Tested version: Desktop, 1.12.0**

[Video](https://streamable.com/hoa9x)

Thank you for the awesome modeler.

**Comment by philippfromme** [comment]
For the time being this is expected behavior. The name is only saved once you finish editing using ENTER.

**Comment by nikku** [comment]
I'd like to re-open this, as it is clearly a very annoying bug from the user perspective.

We've fixed a similar behavior along with appending shapes (https://github.com/bpmn-io/bpmn-js/issues/764).

**Comment by theelectricsoul** [comment]
@philippfromme @nikku 
Hey, I'd like to stress one thing, maybe this will influence your further decisions. I develop software myself, so I know there and bugs/requests that are being prioritized as low. I'm with you. That said!!!

I am relentlessly pushing BPMN in my company. And it is hard to do. And the very first thing the employees come into contact with, is not Signavio and fancy super duper reporting features that only the Quality Department uses. No... the very first thing the get to see is a BPMN overview and a modeling tool.

In a company, there is not much room for inefficiency. Especially not if you present BPMN as a innovation, which it is. And there is definetly no room for tedious and constant model corrections, like sequence flows going in god damn circles. People lose focus if they have to deal with shitty modelling tools.

We are probably going to sign up with signavio, because it comes with great analytic features. But camundas modeller is going nowhere. And I've tested enough tools. I can put a total novice onto it, and it flys. We can actually concentrate a 100% on our business processes while modelling. I do not care if it doesn't handle subprocesses at the moment or is still not handling the full OMG specs. For what it does, it slams every BPMN modeller out of the shoes. And people notice that we get shit done, instead of making jokes about reoccuring usability issues.

**Camunda modeler simply works.**

**Comment by nikku** [comment]
> For what it does, it slams every BPMN modeller out of the shoes. And people notice that we get shit done, instead of making jokes about reoccuring usability issues.

@theelectricsoul Thanks for that compliment. We try hard to achieve that goal every day. 

I'd like to state that most of the feel good factor is attributed to the underlying [bpmn.io modeling toolkits](https://bpmn.io/).
