### ISSUE TITLE
Modeler 1.12.0 accidently created sequence flows on top of each other

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-modeler#777]
New Autoplace feature:

Reproduce:
1. Modeler a gateway
2. choose end event from context pad
3. go back to gateway and choose task from context pad
4. task is placed on top of existing sequence flow sometimes and then it creates a second sequence flow
5. now i move the task and i end up with two sequence flows going to the end event.

Happens in many different scenarios that I end up with multiple sequence flows using auto-place. 

This happens a lot for participants at trainings etc. 
Also see https://forum.camunda.org/t/too-many-notify-calls-for-external-task-on-executionlistener/6823

**Comment by nikku** [comment]
This issue is probably related to the fact that people use auto place + insert the placed elements into existing flows afterwards. 

Could this get fixed by https://github.com/bpmn-io/bpmn-js/issues/774?

**Comment by nevries** [comment]
In the attached model, select gateway and click on task in the pad. Is that what you mean, @felix-mueller ?
[777.bpmn.txt](https://github.com/camunda/camunda-modeler/files/1897995/777.bpmn.txt)

**Comment by nikku** [comment]
The later would be fixed by https://github.com/bpmn-io/bpmn-js/issues/757.

**Comment by felix-mueller** [comment]
Combination of both would fix the mentioned problem I guess. Thanks @nikku 

Besides this: Maybe it would be good to visualize two sequence flows on each other differently?
I dont have a specific idea at the moment how - I think colors are not a good idea.

**Comment by nikku** [comment]
I'd rather disallow the situation where two sequence flows overlap (where possible). As an example, the toolkit could make sure that two sequence flows with the same source and target are not shown as _overlapping_:

![image](https://user-images.githubusercontent.com/58601/38609273-ed4ff960-3d7d-11e8-9d6e-7e8c507315de.png)

**Comment by benhoffmann** [comment]
I think the new task should always be placed beneath the existing sequence flow, like nikku already proposed in https://github.com/bpmn-io/bpmn-js/issues/757

This would mean that you cannot insert elements directly and use auto place at the same time, but I would consider this at least a consistent behavior.

**Comment by benhoffmann** [comment]
> Besides this: Maybe it would be good to visualize two sequence flows on each other differently?
I dont have a specific idea at the moment how - I think colors are not a good idea

Maybe it is already sufficient to display sequence flows always in the foreground to prevent them being hidden behind tasks or other activities?

**Comment by nikku** [comment]
The latest nightly will ensure that there won't be duplicate sequence flows anymore.

Closed via https://github.com/camunda/camunda-modeler/commit/ae264722f6abbf6cc23da1227589bfe3ed008336.

**Comment by nikku** [comment]
The actual fix happened here: https://github.com/bpmn-io/bpmn-js/issues/774.
