### ISSUE TITLE
Boundary Event on a Receive Task following an Event based Gateway

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda-modeler#784]
I'm able to set a Timer Boundary event on a Receive Task that follows an Event based Gateway. Should this be possible?

![receivetaskboundaryevent](https://user-images.githubusercontent.com/1534291/38682886-7a5c475c-3e6c-11e8-8c70-36ce6a3c0114.png)

**Comment by nikku** [comment]
This needs a fix in bpmn-js / [`BpmnRules`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/rules/BpmnRules.js).

**Comment by nikku** [comment]
Waiting for bpmn-js to be released.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/00f3ec8e7d3e5d74b098e716abc3de83ba50e149.
