### ISSUE TITLE
add script for simplifying release

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda-modeler#79]
* [ ] bumping the version in package.json (patch, minor or major)
* [ ] commit
* [ ] tag `git tag -a 'vX.Y.Z' -m 'vX.Y.Z'`
* [ ] push changes
* [ ] push tags `git push origin --tags`

**Comment by nikku** [comment]
What about `npm version (major|minor|patch) -m "chore(project): release v%s"`.

**Comment by nikku** [comment]
Ah, as I just saw we got `grunt` and `grunt release` already...
