### ISSUE TITLE
No more option for cycle in timer intermediate events

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#792]
Why did the cycle option disappear from the property panel? That's very useful for cron expressions and also it's supported by the engine.

<img width="799" alt="bildschirmfoto 2018-04-26 um 15 33 14" src="https://user-images.githubusercontent.com/17595149/39309306-f0abc4ea-4967-11e8-9d96-3fbb887e3ba1.png">

**Comment by nikku** [comment]
It was removed via https://github.com/camunda/camunda-modeler/issues/501 upon user request.

Timer catch events fire _once_ which continues the process execution. Because of that the _cycle_ type makes no sense for them.

As always, correct us, if we're wrong :wink:.

**Comment by benhoffmann** [comment]
It makes sense for cycles of one :) Because otherwise it's hard to say something like "wait for the beginning of the next day" without having to use a Java Date.

**Comment by nikku** [comment]
Could you provide us with an actual use case? What cycle duration would you configure to more concisely express this behavior?

**Comment by benhoffmann** [comment]
The one you can see in the screenshot. 

> Because otherwise it's hard to say something like "wait for the beginning of the next day" without having to use a Java Date.

**Comment by nikku** [comment]
We'll bring that back.

**Comment by benhoffmann** [comment]
Well, I agree that cycle can be confusing for intermediate events, maybe there is a better approach to this requirement. The cron thing is a bit of a dirty hack here. Discussions are going on in consulting right now ...

**Comment by benhoffmann** [comment]
> Support CRON expressions in Date field (new engine feature)

That would be my preferred solution. But it seems like no one else wished for it yet.
