### ISSUE TITLE
Copy & paste not possible in case model

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-modeler#794]
I want to c&p rule expressions and listener expressions but its not possible (shortcut ignored, clipboard is empty)

**Comment by nikku** [comment]
Please provide more context, i.e. a screenshot in which part of the Camunda Modeler your currently floating around.

**Comment by nikku** [comment]
Thanks for the clarification.

**Comment by jangalinski** [comment]
Just found with 1.14.0 on osx: c&p is not possible in DMN (i copied cell-content and tried to paste in other cell).
So this seems to be a general problem.

**Comment by philippfromme** [comment]
Which keyboard shortcut have you been using?

**Comment by jangalinski** [comment]
cmd+c - cmd+v (osx)

**Comment by nikku** [comment]
Closing this one. We'll not follow up on CASE improvements for now.
