### ISSUE TITLE
osx - 1.13.1 - context menu does not appear on cursor position for broad dmn tables

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-modeler#795]
When the dmn table has so many inputs that horizontal scrolling is required, the behavior of the context menu (add/remove column, change label/expression, ...) becomes awkward, it does not appear on the click-location but in the left (originally visible) area.
In case of context-click to remove column, it does not even scroll, you have to manually go all the way left to slect the action.

Note, this also happens on Ubuntu, did not check with windows.

See screencast

![long-dmn mov-out](https://user-images.githubusercontent.com/814032/39356719-0bb7b4d4-4a11-11e8-9ecf-45545d5af762.gif)

**Comment by nikku** [comment]
This should be fixed in Camunda Modeler v1.14.0.
