### ISSUE TITLE
Labels of connections overlap subprocess

### ISSUE THREAD

**Issue by TilmanK** [camunda/camunda-modeler#799]
I created a large BPMN diagram with some subprocesses. When I expand the subprocess, all elements that are overlapped from the larger element are shown faded in the background, except the labels on some connections.

I moddeled an example to show the problem:
![collapsed](https://user-images.githubusercontent.com/8856390/39513848-e3a0dc3a-4df5-11e8-9892-c52921f7902a.PNG)
![expanded](https://user-images.githubusercontent.com/8856390/39513900-0602e642-4df6-11e8-94b6-f9c31770210d.PNG)

**Comment by nikku** [comment]
This is the expected behavior. As of today, labels are shown always on top.
