### ISSUE TITLE
Support HTTP (in addition to file system) as source for element-templates

### ISSUE THREAD

**Issue by jjaenike** [camunda/camunda-modeler#801]
It would be nice if I could provide a REST service to connect my modeller to, to get all available templates for my company/system/network/landscape (other than letting all workflow modeller update the resources-folder themselves)

**Comment by nikku** [comment]
The Camunda Modeler is an offline application. By depending on some online resource you effectively require users to be able to access that resources (possibly secured) before they can use the Camunda Modeler effectively. What if an internet connection is temporarily not available? 

To properly implement this we'd need to hook up the Modeler to some repository, version the templates and cache retrieved results. Not a small topic to work on.

**Comment by nikku** [comment]
A workaround for you could be to wrap the modeler in a shell script (`BATCH` file on Windows) and download / update resources on every modeler start.

**Comment by ingorichtsmeier** [comment]
Isn't this done with Cawemo Catalogs and templates? https://docs.camunda.org/cawemo/latest/user-guide/templates/

**Comment by MaxTru** [comment]
This is indeed solved by using Cloud Connect Plugin and storing templates in Cawemo. https://docs.camunda.org/cawemo/latest/user-guide/templates/

I am closing this for now, feel free to re-open if this solution does not work
