### ISSUE TITLE
DMN table breaks visually when multiple entries added

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#805]
![brokentable](https://user-images.githubusercontent.com/10612634/39991076-a4cc6268-576e-11e8-89be-ca7d1ef81ef6.gif)

If i use the UI to add multiple entries to an input field the boundaries of the columns break.

**Comment by nikku** [comment]
Unfortunately I cannot reproduce this issue on Linux / Camunda Modeler v1.14.0.

Which version of the Camunda Modeler / operating system do you run at?

**Comment by NPDeehan** [comment]
Using V1.14.0 on Windows 10

**Comment by nikku** [comment]
@philippfromme Could you try to reproduce the behavior on Windows 10?

@NPDeehan Is it generally reproducible or does it require a special decision table to yield the behavior?

**Comment by philippfromme** [comment]
I can reproduce this if I use long words. 

Using `white-space: pre-wrap; word-wrap: break-word;` fixes the issue. Not sure why it only pops up now, though.

**Comment by philippfromme** [comment]
Electron@2 fixes this issue on Windows.

**Comment by nikku** [comment]
Great to hear.

Closed via https://github.com/camunda/camunda-modeler/issues/808.
