### ISSUE TITLE
API Support for create camunda elements?

### ISSUE THREAD

**Issue by dingchaoyan1983** [camunda/camunda-modeler#806]
Is there any moddle api to support the function which I want to create camunda property and extensionElements, becuase right now the bpmn properties panel is used for developers, I just want to show high level settings instead of developer settings suchs as java class and condition variables. thanks in advance

**Comment by dingchaoyan1983** [comment]
I want to do some development base on api and implement the same functions which don't show the developer settings, but use my own ui to generate camunda property

**Comment by nikku** [comment]
You can drive our toolkits entirely via API, the question is what is the best place to hook into.

Please provide a few mock ups that help us understand your use case better.
