### ISSUE TITLE
Integration test on MacOS

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#812]
Execute our [integration tests](https://github.com/camunda/camunda-modeler/blob/master/docs/.project/INTEGRATION_TEST.md) against the [Camunda Modeler nightly](https://camunda.org/release/camunda-modeler/nightly/) on MacOS.

**Comment by fh48** [comment]
# Integration Test

We use a number of pre-defined steps to ensure the stability of our releases through integration tests.

__Target:__ Perform tests on nightly builds on supported platforms.


### Test Procedure

* [x] fetch [latest release/nightly](https://camunda.org/release/camunda-modeler/)
* [x] click like crazy (see [below](#test-checklist))


### Test Checklist

Manual integration tests:

#### BPMN Modeling

* [x] create a new BPMN diagram
* [x] build [this diagram](./test.bpmn.png) from scratch
* [x] save file on disk as `test.bpmn`
* [x] save file with other file name on disk
* [x] export as SVG
* [x] export as PNG
* [x] export as JPG
* [x] SVG, PNG and JPG exports open in browser

##### Copy/Paste

* [x] create a new diagram
* [x] `CTRL + A` + `CTRL + C` in previously created diagram
* [x] remove start event in empty diagram
* [x] `CTRL + V` in empty diagram pastes all contents

##### BPMN properties panel

* [x] configure service task in properties panel
* [x] add `async:before`
* [x] add executionn listener
* [x] add input mapping
* [x] verify results in XML tab

##### Keep implementation Details (Copy/Paste and Morph)

Based on the [test diagram](./test.bpmn.png):

* [x] Add Form configuration (FormField + FormData) to "Inspect Invoice" UserTask
    * [x] Copy / Paste task; properties are kept
    * [x] Change task to ServiceTask; properties are gone from XML
    * [x] Undo last step `CTRL + Z`; properties are back
    * [x] Redo last step `CTRL + Y`; Task changed to Service Task without form properties
* [x] Add Properties, Input/Output Mapping, `asyncBefore`, Retry Time Cycle and implementation to "Check" ServiceTask
    * [ ] Copy / Paste task; properties are kept
    * [x] Change task to Send Task; properties are kept
    * [x] Change task to UserTask; implementation property is gone from XML (except Retry Time Cycle and `asyncBefore`)


####  CMMN modeling // Not Tested

* [ ] create a new CMMN diagram
* [ ] save diagram on disk
* [ ] save as SVG, PNG and JPG
* [ ] SVG, PNG and JPG open in browser (i.e. Chrome)


#### DMN modeling

* [x] create a new DMN diagram
* [ ] build [this diagram](./test.dmn.png) from scratch
* [x] morph `Go on Holidays` to a decision table
* [x] morph `Which Season` to a decision table
* [x] morph `Which Region` to a literal expression
* [x] click onto green overlay on `Go on Holidays` jumps into table editing mode
* [x] changing name reflects in DRD
* [x] save file on disk as `test.dmn` from table editing mode
* [x] save file on disk as `test2.dmn` from diagram mode
* [x] both import correctly after save
* [x] export DRD as SVG
* [x] export DRD as PNG
* [x] export DRD as JPG
* [x] SVG, PNG and JPG exports open in browser


#### FS integration (platform specific)

* [x] external change detection works
    * [x] change file in external editor
    * [x] focus editor with file open
    * [x] message to reload displays
* [x] double click in FS opens file in editor (existing instance _?_)
    * [x] `.bpmn`
    * [x] `.cmmn`
    * [x] `.dmn`


#### Other (platform specific)

* [x] key bindings work (Mac = CMD, CMD+SHIFT+Z, Other = CTRL)
* [x] restore workspace on reopen (diagrams, properties panel)
* [x] drag and drop
* [x] icons are present
* [x] OS specific menus are being displayed
* [x] menu bar (icons, correctly disabled + enabled)
* [x] correct modeler version displayed in about menu

**Comment by fh48** [comment]
I have tested with the Version 1.15.0-nightly. There have been 2 major issues.

* **Copy & Paste of Activities.**
  Given 
  I create a new activity 
  When
 I press cmd + c & cmd + v.
 Then
  Nothing happens.

After dragging the activity anywhere, cmd + c & cmd + v works once. Then it the activity needs to be moved again. 

* **Write Text with character 'e' in dmn elment** 
  Given 
  I create a DMN Diagram and add an element.
  When
  I label it and hit the 'e' character.
  Then
  The whole previously written text is deleted.

**Comment by StephenOTT** [comment]
@fh48 what version of MacOS was this tested on? ref to #817

**Comment by fh48** [comment]
@StephenOTT I have tested on macOS High Sierra 10.13.4
