### ISSUE TITLE
I can't paste in the search field of the XML view on MacOS.

### ISSUE THREAD

**Issue by fh48** [camunda/camunda-modeler#814]
Given
I use the modeler on MacOS.

When
I open the xml view and the search input (cmd + shift + f) 

Then
I can't paste (cmd + v ) into the input. 

---

Related to [SUPPORT-6136](https://app.camunda.com/jira/browse/SUPPORT-6136)

**Comment by nikku** [comment]
Works on Linux.

**Comment by srazavi** [comment]
This popped up in support. I linked relevant support case in issue description.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1443.
