### ISSUE TITLE
Scrolling causes UI craziness: OSX 10.12.6

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#817]
Mac OS, 10.12.6
Modeler: 1.15.1

![screen shot 2018-06-01 at 1 03 34 pm](https://user-images.githubusercontent.com/1994838/40853503-4961b04a-659c-11e8-82f3-b87ac03195ad.png)

Makes the modeler essentially useless.

Scroll with the trackpad (2 fingers)

![screen shot 2018-06-01 at 1 05 19 pm](https://user-images.githubusercontent.com/1994838/40853556-841a65f6-659c-11e8-8336-dab81bfd416d.png)
![screen shot 2018-06-01 at 1 05 28 pm](https://user-images.githubusercontent.com/1994838/40853558-85192140-659c-11e8-8f0d-45c50d72ddf4.png)

**Comment by felix-mueller** [comment]
I cannot reproduce this on MacOS 10.13.2 and Modeler 1.15.1
Looks very weird though

**Comment by nikku** [comment]
As it looks like this is an issue with Mac OS 10.12.x.

As a workaround please continue to use `v1.14.x` on that older Mac OS version.

**Comment by StephenOTT** [comment]
@nikku is this likely to get fix in the near future?

**Comment by nikku** [comment]
Unfortunately not. As [mentioned above](https://github.com/camunda/camunda-modeler/issues/817#issuecomment-394273174) this appears to be an issue with MacOS Sierra and the latest version of Electron we use under the hood. 

Please stick to `v1.14.x` until things get fixed upstream on the Electron side.

**Comment by StephenOTT** [comment]
@nikku you have identified this as a specific electron bug? and not just a modeler's implementation of electron?

**Comment by nikku** [comment]
Likely related to https://github.com/electron/electron/issues/13252.

**Comment by StephenOTT** [comment]
@nikku thanks

**Comment by nikku** [comment]
This is odd. Reported to work on MacOS 10.13.4 and 10.13.2. 

I can try if I get the latest MacOS installed on my test machine.

**Comment by StephenOTT** [comment]
possible its a hardware issue as well: Using Macbook Air 13-inch, Mid 2011 which is using Intel HD Graphics 3000 384 MB

Could be something to do with the Intel HD 3000

**Comment by felix-mueller** [comment]
I use: Intel Iris Pro 1536 MB, MacBook Pro (Retina, 15-inch, Mid 2015), 10.13.2 and no issues.

**Comment by HarmPrinsDEX** [comment]
I had the same problem on High Sierra, but using version 1.14 solves it.

**Comment by nikku** [comment]
We are at Electron@3 in our latest nightly. Could you @StephenOTT check whether the artifacts still occur? Download the nightly from [here](https://camunda.org/release/camunda-modeler/nightly/).

**Comment by HarmPrinsDEX** [comment]
Hi Nico,

It works fine now.

Met vriendelijke groet / kind regards,

Harm Prins
(+31) 6 434 97449
harm.prins@dataexplorers.nl
www.dataexplorers.nl

**Comment by nikku** [comment]
Fixed via https://github.com/camunda/camunda-modeler/commit/d2e91cf583f79002dd3538d84aa4c3aacf1ecad9.

**Comment by StephenOTT** [comment]
Seems to still be broken.

![screen shot 2018-10-17 at 1 32 45 pm](https://user-images.githubusercontent.com/1994838/47105195-3fb67800-d211-11e8-8fb0-4fa0c324aac0.png)

**Comment by StephenOTT** [comment]
This appears to be fixed in atleast 2.2.4.

Can be closed if you wish.
