### ISSUE TITLE
Target attribute not removed from signal payload

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda-modeler#818]
__Reproduce__

* Add signal throw intermediate event.
* On Variables properties tab add new mapping, select Type=Source and fill in Source and Target.
* Change Type on All.
* Switch on XML view.

__Observed Behavior__
  
* `target` attribute still present in `camunda:in` tag.
   
__Expected Behavior__
    
* [ ] no `target` attribute is present in `camunda:in` tag.

---

Related issue: https://github.com/camunda/camunda-modeler/issues/819

**Comment by nikku** [comment]
Thanks for reporting.

**Comment by nikku** [comment]
I've split both issues. into https://github.com/camunda/camunda-modeler/issues/819 and https://github.com/camunda/camunda-modeler/issues/818.
