### ISSUE TITLE
Local flag in signal payload configuration makes sense with Type=All only

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#819]
`Local` checkbox on Variable tab makes sense only when Type=All is selected.

__Expected Behavior__

* [ ] Hide checkbox _and_ remove corresponding attribute in XML if other types are selected

**Comment by sdorokhova** [comment]
Hi @philippfromme ,
I checked now in code, and this flag actually DOES affect also other cases (not only All case), though it's not documented and not tested. It looks like, it's just an edge case, nobody thought about, but who knows, maybe people use it. This is valid for both call activity and signal throw event.

So, I would propose to leave this thing as it is for now and close the issue.
