### ISSUE TITLE
Unable to open DMN using old namespace

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#821]
This file can't be opened:
[simple-expressions.dmn.txt](https://github.com/camunda/camunda-modeler/files/2072103/simple-expressions.dmn.txt)

Rename it to .dmn before. Every time you open the modeler, he reads it again and ends with an error message.

Where can I cleanup the recent files?

---

Related to [`SUPPORT-4944`](https://app.camunda.com/jira/browse/SUPPORT-4944)

**Comment by ingorichtsmeier** [comment]
I'm running the modeler on windows 10.

**Comment by nikku** [comment]
Seems like something got awry in the error handling in the latest modeler. We'll investigate this.

Regarding your diagram: It contains the old (and wrong) DMN 1.1 namespace URI: 

```
http://www.omg.org/spec/DMN/20151101/dmn11.xsd
```

The correct one should be

```
http://www.omg.org/spec/DMN/20151101/dmn.xsd
```

**Comment by nikku** [comment]
Released in `v1.16.x`.

**Comment by philippfromme** [comment]
Shouldn't we offer correcting the namespace as we do in the case of BPMN?

There's another support case regarding this issue: https://app.camunda.com/jira/browse/SUPPORT-4944

**Comment by nikku** [comment]
Support case closed with the workaround provided.
