### ISSUE TITLE
Labels are not generated anymore for start events/gateways

### ISSUE THREAD

**Issue by bs11234** [camunda/camunda-modeler#824]
In Camunda Modeler v1.15.1 on Windows 64bit: Names of elements are not displayed anymore.

Steps to reproduce:
1. Create a PBMN diagram
2. Edit properties of StartEvent
3. Type 'Start' in Name property

No label 'Start' is added to diagram. In previous versions, a bpmndi:BPMNLabel was generated for the BPMNShape and the name was displayed in the diagram.

**Comment by bs11234** [comment]
Works in v1.14.0 on Windows 64bit but not anymore in v1.15.1.

**Comment by nikku** [comment]
Thanks for reporting.

**Comment by nikku** [comment]
This will be fixed with proper external label updating on name changes (https://github.com/camunda/camunda-modeler/issues/631).

**Comment by philippfromme** [comment]
Closed via 4a0f6da814c45268e8a324e73a53479bd2435bbe.
