### ISSUE TITLE
Removing text in input behaves weirdly

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#826]
Reproduce:

1. Edit output name
2. Hold down remove to clear text

Expected behavior:

1. Text is removed

Actual behavior:

1. Text is reset to original value again and again

Hint: There seems to be an issue with only committing changes with a debounce of 300ms

![foobar](https://user-images.githubusercontent.com/7633572/41233080-944fa8ac-6d88-11e8-8a2e-a355a9b85c7d.gif)

**Comment by oguzeroglu** [comment]
Fixed via https://github.com/bpmn-io/dmn-js/pull/416

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1593.
