### ISSUE TITLE
Please verify ckecksum for camunda modeler in brew cask repository

### ISSUE THREAD

**Issue by pschalk** [camunda/camunda-modeler#833]
Hi,

the cask for the camunda modeler contains a wrong checksum, and therfore it can not be installed. I have tried to fix that, but the maintenance team of the repository need a verification by the developers, that the new checksum is correct:

https://github.com/Homebrew/homebrew-cask/pull/48437

**Comment by nikku** [comment]
[Done.](https://github.com/Homebrew/homebrew-cask/pull/48437#issuecomment-397956667)
