### ISSUE TITLE
Variable Events for Conditional Events are stored in wrong property

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda-modeler#836]
__Steps to reproduce:__

1) create a new model
2) model a conditional intermediate event
3) configure a "Variable Event" `create` in properties panel

Resulting model: [`variableEvent.bpmn`](https://github.com/camunda/camunda-modeler/files/4159073/variableEvent.bpmn.txt)

__Observed Behavior:__
The variable event `create` is stored in the property `camunda:variableEvent`.

__Expected Behavior:__
The variable event `create` must be stored in the property `camunda:variableEvents`.

__Hint:__
The character `s` is missing at the end of the property name. Should be also fixed in the [moddle descriptors](https://github.com/camunda/camunda-bpmn-moddle/blob/5d62e55f30a48169812e914050f7ad1c1ebbf84b/resources/camunda.json#L1074).

---

Also see [SUPPORT-4526](https://app.camunda.com/jira/browse/SUPPORT-4526)
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/355

**Comment by Jo-IE** [comment]
Hi, I am interested in the recent React Frontend Developer position at Camunda and would like to learn more about Camunda's code bases by contributing. Is it ok if I get started with this issue?


Thanks!

**Comment by nikku** [comment]
Hi @Jo-IE!

This is a super interesting issue to deep dive into the Camunda Modeler and related tooling code base for sure. However, in our sphere, you'll touch React only on the surface. Quite soon you'll dive into plain old JavaScript libraries that do things libraries do. Just a disclaimer :wink:.

Your contribution is appreciated. If you'd like to look into the issue you can rely on us to help.

**Comment by Jo-IE** [comment]
@nikku thank you, sounds good!

**Comment by Jo-IE** [comment]
Hi, I am having some trouble recreating this issue. I am able to run the Modeler locally and create an Intermediate event. However, I'm not clear on how to proceed with step 3.

Any insight on what I might be missing? 
Thanks!

**Comment by nikku** [comment]
See screenshot below: 

![image](https://user-images.githubusercontent.com/58601/73836081-cdefac80-480e-11ea-9647-d228ff3b5ed9.png)

**Comment by Jo-IE** [comment]
Thank you @nikku !
