### ISSUE TITLE
Deployment popup should close automatically after successful deployment

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#839]
__Description__

As a user I'd like to receive deployment progress indication and result notification outside the deploy dialog.

__Tasks__

* [ ] Pressing deploy button closes dialog
* [ ] Notification (cf. [example](https://ant.design/components/notification/#header)) shows deployment status and result.
* [ ] On success, notification closes automatically
* [ ] On failure, user is able to re-open the dialog _or_, depending on the failure, is directed to the logs to inspect parse errors

__Additional Context__

Cf. [mock ups](https://docs.google.com/presentation/d/136nEfebFSh-JfBq4_PfFTzzF7BnKcTysvOgcu8ppx2A/edit#slide=id.g5db3e0a2d5_0_2)

--- 

Child of https://github.com/camunda/camunda-modeler/issues/1439

**Comment by nikku** [comment]
Yea. Deploying in background + a slick notification on success could be a thing / alternative, too.

**Comment by barmac** [comment]
Regarding notifications, [this](https://ant.design/components/message/) looks to me like an alternative candidate. Still, I don't have a strong opinion on which option to follow.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1491
