### ISSUE TITLE
SVG export of 1.16 looks different then 1.8

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#840]
If you export the a diagram as SVG in the latest version and import it to Inkscape, the labels moved slighly to the right and are not centered anymore.

See the content of the zip. agenda-16.svg is exported with Camunda Modeler 1.16, agenda.svg is exported with Camunda modeler 1.8

At a first glance you find different fonts used in svgs.

[svg-export-to-png.zip](https://github.com/camunda/camunda-modeler/files/2128113/svg-export-to-png.zip)

#### 1.8 export

![agenda-16 svg-marked](https://user-images.githubusercontent.com/58601/42018646-07e9e3cc-7ab3-11e8-8765-38d44aab13b2.png)

#### 1.16 export

![agenda svg-marked](https://user-images.githubusercontent.com/58601/42018670-17c2dfa6-7ab3-11e8-8989-2896f07aa661.png)

**Comment by nikku** [comment]
Could you post how it looks like? We did updates in 1.16 that aimed to improve the label rendering and positioning so a little bit of _change_ is expected.

**Comment by ingorichtsmeier** [comment]
Examples are in the zip, attached to my post. svg and png.

**Comment by nikku** [comment]
As seen in the images the SVG uses the default system font which is Calibri or whatever on Windows.

We've introduced that change in bpmn-js to provide a better native experience for users, did not consider that it may break diagram exports though (cf. [this issue](https://github.com/bpmn-io/bpmn-js/issues/819)). 

On Linux for instance, the newly generated diagram + the default system font lead to a slightly improved visual appearance for multi-line text:

#### Before

![image](https://user-images.githubusercontent.com/58601/42020056-16e58166-7ab7-11e8-997a-2da91a186ebf.png)


#### After

![image](https://user-images.githubusercontent.com/58601/42020077-231fc7e8-7ab7-11e8-8854-cf64d58976f6.png)

**Comment by ingorichtsmeier** [comment]
Hi @nikku ,

at the first glance I did't see a difference. Could you please highlight one?

Thanks, Ingo

**Comment by nikku** [comment]
We improved the used line height, making dense text more readable. This is not visible to most people but will make a difference when ready diagrams regardless :wink:.
