### ISSUE TITLE
How to switch the interface language in the Modeler (Windows)?

### ISSUE THREAD

**Issue by GitMensch** [camunda/camunda-modeler#841]
Using a download version we see the locales folder with many .pak files. Starting the Modeler shows an English interface.

How can we change the language (ideally the default until chosen otherwise is the system-specific locale and there's an built in option to switch the language [which is itself stored along to the open model files for the next start]).

**Comment by nikku** [comment]
We don't support other languages than English at the moment.

**Comment by GitMensch** [comment]
That is perfectly fine "at the moment", but why are locales shipped if other languages aren't supported?

**Comment by nikku** [comment]
The language files you see shipped are part of the infrastructure we use and not directly related to the app itself. Closing this issue for now, as we have no intention to add multi-language support any time soon.
