### ISSUE TITLE
Deploy Embeded Task Forms with the deploy button

### ISSUE THREAD

**Issue by smalewski** [camunda/camunda-modeler#844]
It should be possible to deploy a diagram with its **Embedded Task Forms** using the **Deploy Diagram Button**.

Maybe deploy all HTML files in a form folder.

So I can deploy, for example, a diagram with a **User Task** with 
`Form Key = embedded:deployment:form/exampleForm.html`
and the file `form/exampleForm.html` at the same time.

**Comment by musbenlahrech** [comment]
> It should be possible to deploy a diagram with its **Embedded Task Forms** using the **Deploy Diagram Button**.
> 
> Maybe deploy all HTML files in a form folder.
> 
> So I can deploy, for example, a diagram with a **User Task** with
> `Form Key = embedded:deployment:form/exampleForm.html`
> and the file `form/exampleForm.html` at the same time.

please can you explain further, because i tried to deploy the  Embedded Task Forms using the Deploy Diagram Button. but this error shows up in taskslist 
![image](https://user-images.githubusercontent.com/47721088/58577847-a8ee7700-8247-11e9-90b9-58166dd39fdb.png)

**Comment by rpsjr** [comment]
musbenlahrech, smalewski is asking this feature as an enhancement.
by the way, i would also appreciate this hack.

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2137.
