### ISSUE TITLE
DRD label editing causes shortcut conflict

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#845]
1. Select a DRD (activates E shortcut for edit)

2. Double-click or hit E to actually start editing

3. if you type e as part of your label, the shortcut is triggered again which results in deletion of the newly typed text.

(tested with 1.16.1 on Windows and Mac)

![drd-bug](https://user-images.githubusercontent.com/17595149/42283076-b098fcb6-7fa8-11e8-9d8d-fef746ffd585.gif)

**Comment by nikku** [comment]
Fixed in [Camunda Modeler v1.16.2](https://github.com/camunda/camunda-modeler/blob/master/CHANGELOG.md#1162).
