### ISSUE TITLE
I get a proper exception message when deploying of a moddiagramel fails

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda-modeler#846]
_Steps to reproduce:_
1) Download a Camunda Bpm Platform Distribution
2) Enable BasicAuthentication in Engine Rest API
3) Model a BPMN diagram in Camunda Modeler
4) Try to deploy this BPMN diagram

_Observed Behavior:_
The following error is displayed:
![modeler-unauthorized](https://user-images.githubusercontent.com/2368139/42505453-0ef7e21e-843f-11e8-9bb3-b298fc002474.png)

_Expected Behavior:_
An error is displayed, saying the user is unauthorized to deploy the BPMN diagram.

---
related to [SUPPRT-4606](https://app.camunda.com/jira/browse/SUPPORT-4606)

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1041.
