### ISSUE TITLE
Add DMN properties panel

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#847]
In order to be able to edit more technical properties of decisions a properties panel will be added.

* properties panel will be visible independently from current editor (DRD, decision table, ...)
* in DRD editor properties panel will display properties of currently selected element or definitions if no element is selected
* in decision table view properties panel will always display propterties of currently opened decision

Tasks

* [x] remove Camunda extension from dmn-moddle https://github.com/bpmn-io/dmn-moddle/pull/1
* [x] create camunda-dmn-moddle https://github.com/camunda/camunda-modeler/issues/849
* [x] create dmn-js-properties-panel
* [x] release dmn-js-properties-panel as npm module
* [x] integrate properties panel into Camunda Modeler
* [x] test integration into Camunda Modeler

Related to https://github.com/bpmn-io/dmn-js/issues/364.
Depends on https://github.com/bpmn-io/dmn-js-properties-panel/issues/1.

**Comment by nikku** [comment]
I tested it and it works.

Personally I don't like the fact that we waste a lot of space on the Table _and_ Literal Expression views through: 

![image](https://user-images.githubusercontent.com/58601/43397065-e27b368a-9403-11e8-8aa0-343d63ed23cb.png)

Why can't we let the properties panel overlap and wait for feedback?

**Comment by nikku** [comment]
Making the space unusable is contra-productive if we discuss issues like [this one](https://github.com/camunda/camunda-modeler/issues/853) one in parallel, too.

**Comment by nikku** [comment]
My suggestion would be:

* Add a general toggle shortcut, available for all editors 
* Allow properties panel to be toggled via menu for all editors
* Make hide toggle in collapsed state on literal expression and decision table editor and wait for feedback that tells us to show it.

**Comment by philippfromme** [comment]
Sure, why not.
