### ISSUE TITLE
Create camunda-dmn-moddle

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#849]
In order to add a DMN properties panel to the Camunda Modeler a moddle extension for DMN 1.1 has to created first.

Repository of the project: https://github.com/camunda/camunda-dmn-moddle

Related to https://github.com/camunda/camunda-modeler/issues/847.

**Comment by nikku** [comment]
Could we add a CI environment, best Travis to the project?

**Comment by philippfromme** [comment]
Would be a good idea, we should also add this to the other *-moddle projects.

**Comment by nikku** [comment]
Please add CI to the project so we can proceed. Thanks!

**Comment by nikku** [comment]
Additional note: Why didn't you call the `camunda` extension for `dmn:InputClause` `camunda:InputClause`, similar to the `camunda:Decision` (cf. [this line](https://github.com/camunda/camunda-dmn-moddle/blob/master/resources/camunda.json#L30))?

Is it for backwards compatibility reasons?

**Comment by philippfromme** [comment]
@nikku No specific reason, I simply didn't change it when taking it from dmn-moddle.

**Comment by philippfromme** [comment]
@nikku I've adjusted the name and added Travis.

**Comment by nikku** [comment]
Released as [`v1.0.0`](https://github.com/camunda/camunda-dmn-moddle/blob/master/CHANGELOG.md#100).
