### ISSUE TITLE
Microsoft word crashes importing a svg from Camunda Modeler

### ISSUE THREAD

**Issue by TilmanK** [camunda/camunda-modeler#850]
I found the following issue, that is, at least on my computer, reproducible.

I can create whatever diagram I want and export it as a svg file, when importing it into a MS Word dokument as image, Word always crashes. This does not happen with any other svg file for me, only for those that I exported from Camunda.

I'm using Word from Office 365 ProPlus Version 1708 Build 8431.2236 on Windows 10 64bit.

Could you verify that this is not a problem in the svg generated?

**Comment by nikku** [comment]
I'm sorry to hear that your Word has issues importing Camunda Modeler exported SVGs. I'd guess that Word is not very forgiving when it comes to SVG support.

Could you share a minimal diagram that reproduces the crash for you?

**Comment by TilmanK** [comment]
Sure, it's crashing even with the simplest example. Please find the bpmn and svg file attached.

[word_crash_example.zip](https://github.com/camunda/camunda-modeler/files/2210028/word_crash_example.zip)

**Comment by TilmanK** [comment]
Some additional information: I was experiencing this issue on 1.13.1 and just upgraded to 1.16.2. The issue is still there, unchanged.

**Comment by nikku** [comment]
Unfortunately we cannot reproduce your issue with a fresh installation of `Word / Office 365 Business on Windows 10 64bit`.

Steps we undertook:

* Create empty document
* Insert > Image
* Choose `word_crash_example.svg` provided by you

So unless you got more information regarding the crash (error messages or related) there is nothing we can do. A workaround exists though: You could export your diagrams as images and import these into your MS Word documents.
