### ISSUE TITLE
Update installation documentation

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#852]
Document installation and wiring (Window, Linux) [here](https://docs.camunda.org/manual/7.9/installation/camunda-modeler/).

__Tasks__

* [x] Documentation is updated (register file association hint) ([camunda-docs-manual#852-modeler-docs](https://github.com/camunda/camunda-docs-manual/tree/852-modeler-docs) branch)
* [x] Download + open instructions are updated ([camunda.com-new#852-modeler-docs](https://github.com/camunda/camunda.com-new/tree/852-modeler-docs) branch)

Depends on https://github.com/camunda/camunda-modeler/issues/851 to be addressed.

**Comment by nikku** [comment]
Merge strategy:

* Merge docs changes ([camunda-docs-manual#852-modeler-docs](https://github.com/camunda/camunda-docs-manual/tree/852-modeler-docs) branch) once Modeler is released
* Merge camunda.com changes ([camunda.com-new#852-modeler-docs](https://github.com/camunda/camunda.com-new/tree/852-modeler-docs) branch) once Modeler is stable

**Comment by philippfromme** [comment]
Should I just comment my okay since I can't close and merge right now?

**Comment by nikku** [comment]
Yes. :cake:

**Comment by philippfromme** [comment]
Looks 👍 to me!

**Comment by nikku** [comment]
Closing this as all relevant documentation updates are merged.
