### ISSUE TITLE
Palette cannot be collapsed anymore

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#853]
In the latest nightly build, the palette cannot be collapsed anymore. On small screen resolutions, the extra space gained by collapsing the palette is important for navigating larger models.

**Comment by nikku** [comment]
We removed this feature as it was reported to us as a bug on multiple instances (cf. https://github.com/bpmn-io/diagram-js/issues/257).

The collapse / toggle logic itself is still there; you may create your own Camunda Modeler plugin to make it available via the menu or a keyboard shortcut.

**Comment by nikku** [comment]
As a side note you should try out the new minimap for navigating if screen space is limited.

**Comment by nikku** [comment]
We may consider re-introducing it, hidden behind a menu entry / keyboard shortcut.

**Comment by falko** [comment]
Wasn't there some research prototype to really maximize screen space and even remove the toolbar? Maybe you would like to consider this as a menu entry / keyboard shortcut and hide all overlays?

**Comment by nikku** [comment]
Let's step back and discuss the actual use case first. You'd like to see all of the process but you don't have a lot of screen size to do so? Which means collapsing / hiding everything + going full screen would help?

Would you like to model in that mode or is it just meant for navigating?

What does collapsing / hiding include:

* Palette (Collapse)
* Properties Panel (Collapse)
* Minimap (Collapse)
* Log view (Hide)
* Menu Bar (Hide)
* Tool Bar (Hide)
* Tab Bar (Hide)

Should we save the prior open state to toggle back to it?

**Comment by falko** [comment]
Yes, all that. I would like to model in fullscreen mode and unfold palette and properties panel as needed.

**Comment by nikku** [comment]
Closing this issue as we won't bring click toggling back.

I added https://github.com/camunda/camunda-modeler/issues/883 to provide a keyboard shortcut to toggle the palette.

**Comment by nikku** [comment]
Added another issue that depicts the _focus_ mode I've mentioned: https://github.com/camunda/camunda-modeler/issues/884.
