### ISSUE TITLE
Rogue Sequence Flows added by moving element

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#854]
In the current nightly build, new sequence flows are added when moving an element around. All of them are loops from and to the element that is moved. I also observed this with tasks.

The following screencast shows three unwanted sequence flows that get created (one of them even untouchable behind the event):
![2018-07-20 rogue sequence flows added by moving element](https://user-images.githubusercontent.com/40038/42993822-abba0e36-8c0c-11e8-8fec-122a3fa7145e.gif)

---

Cf. [bpmn-js issue](https://github.com/bpmn-io/bpmn-js/issues/836).

**Comment by nikku** [comment]
Great catch!

This is caused by the fact that the latest nightly allows you to model cyclic connections.

We need to address https://github.com/bpmn-io/bpmn-js/issues/774 in order to properly address this issue.
