### ISSUE TITLE
Pasting text into text annotation removes new lines

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#855]
__Reproduce__

* create a BPMN diagram
* copy multi line text, e.g.:
    ```
    X:
    - foo
    - bar
    ```
* create Text annotation
* direct edit
* paste from clip board

__Expected Behavior__

* [ ] Multi line text is preserved

__Actual Behavior__

* newlines are dropped 

---

Related to [SUPPORT-4633](https://app.camunda.com/jira/browse/SUPPORT-4633)

**Comment by michaldytko** [comment]
Hi @nikku, this seems to be resolved with Modeler 4.7.0 (haven't checked with older versions).

**Comment by nikku** [comment]
Fixed with `v4.7.0` indeed. Also verified it works with `v4.8.1`.

Thanks for the hint @michaldytko!
