### ISSUE TITLE
Copy and Paste is not possible inside of XML view (1.14)

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#868]
Copy and Paste is not possible inside of XML view (1.14)

There is no way to copy and paste text in the xml view?

---

Related to [SUPPORT-6136](https://app.camunda.com/jira/browse/SUPPORT-6136)

**Comment by StephenOTT** [comment]
@philippfromme i am using 10.12.6 MacOS.

When in XML view, the copy/paste options in the Menu system are not even visible 

![screen shot 2018-08-14 at 8 59 21 pm](https://user-images.githubusercontent.com/1994838/44126218-f460747a-a004-11e8-9277-cf1758aed1e0.png)

**Comment by benhoffmann** [comment]
Hey guys, what is the status about this? 

I don't know how hard it is to bring back copy & paste, but this is a quite annoying thing, especially when trying to find sequence flows or gateways that don't have a meaningful ID but show up in exception logs.

**Comment by philippfromme** [comment]
Do you mean bringing it back at all or bringing back the menu entries?

**Comment by benhoffmann** [comment]
Isn't that kind of the same thing? 

I can't use the keyboard shortcuts which I guess might be because of the functionality not being available at all which results in the menu entries not being shown?

If these are two different stories, I'd like to have them both back :)

**Comment by srazavi** [comment]
This popped up in support. I linked relevant support case in issue description.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1443.
