### ISSUE TITLE
Remove last input/output clause should not be possible

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda-modeler#87]
steps to reproduce:
* create a new DMN table
* select a text field in the input column
* choose edit -> remove clause from the menu

problem:
* The input clause gets removed, so there is none left, but at least one should be there.

expected behavior:
* If there is only one input clause left, it should not be possible to delete it from the menu.

Note: Same applies for the output clause

**Comment by nikku** [comment]
This is a DMN issue right? Could you open a ticket in [dmn-js](https://github.com/bpmn-io/dmn-js) and see if we get that fixed?

**Comment by ricardomatias** [comment]
This has been fixed. The remove option is disabled.
