### ISSUE TITLE
'Export as image' should export overlays

### ISSUE THREAD

**Issue by Ichigo85** [camunda/camunda-modeler#878]
I am using [this plugin](https://github.com/sharedchains/camunda-modeler-property-info-plugin/tree/feat_open_link) to create and organize flows, but when exporting a model as image, every overlay on any element is not exported as well. 
I think this could be a good feature, maybe with an option to add overlays or not.

**Comment by Ichigo85** [comment]
We need it to make our documentation.

**Comment by nikku** [comment]
Why don't you refer to the live diagram as part of your documentation? This way you'd be able to navigate the diagram and _see_ what is behind individual tokens / overlays?

**Comment by nikku** [comment]
We won't build this feature any time soon, as there is many better ways of solving this issue (i.e. by generating HTML that embeds [bpmn-js](https://github.com/bpmn-io/bpmn-js), showing the diagram and related overlays.
