### ISSUE TITLE
Deploy all files within a folder or same folder as BPMN - REST API Deployment

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#880]
Similar to the use case of https://github.com/StephenOTT/camunda-deployment-maven-plugin where the plugin will grab all files within the defined folder and upload these as part of the deployment, it would be great to have the same feature as part of the Modeler deployment function:
You are often deploying many files, BPMN, script files, templates, CMMN, DMN, etc, all part of the same deployment.

Thanks

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2137.
