### ISSUE TITLE
Error occurs on dragging and line snapping

### ISSUE THREAD

**Issue by stephanpelikan** [camunda/camunda-modeler#888]
If you use sequence flows to visualize message flows between pools and you label them an error occurs during dragging once line snapping happens (see video: [Error occurs on dragging and line snapping.zip](https://github.com/camunda/camunda-modeler/files/2309255/Error.occurs.on.dragging.and.line.snapping.zip) - sorry for the typo in the label inside the video).

I use version 1.16.2

**Comment by nikku** [comment]
Thanks for reporting. 

Tracking the actual error + fix in https://github.com/bpmn-io/bpmn-js/issues/849.
