### ISSUE TITLE
Restore tab scrolling/dragging

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#895]
__Tasks__

* [x] Tabs can be re-ordered via drag and drop
* [x] Tabs are shown in one line and can be scrolled via arrow and wheel

Hints:

* try reusing bpmn.io tab scrolling and dragging util libraries

**Comment by philippfromme** [comment]
What does navigate via arrow mean? This doesn't work in the current Camunda Modeler and would also clash with the arrow keys being used for moving the canvas. There could be a shortcut (CTRL/CMD + PAGE UP/DOWN).

**Comment by nikku** [comment]
What is meant is simply restoring the old scrolling behavior:

![image](https://user-images.githubusercontent.com/58601/47280341-3b55da80-d5d6-11e8-98ad-78a951641ca2.png)

**Comment by philippfromme** [comment]
@barmac I've simplifyied finding the tab. The scrolling speed issue should be handled separately.
