### ISSUE TITLE
DMN: Add Aggregation LIST to hit policy COLLECT

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#900]
This feature is missing in dmn-js@2. It was available in dmn-js@0.x.x.

---

Depends on https://github.com/bpmn-io/dmn-js/issues/370

See also [SUPPORT-4767](https://app.camunda.com/jira/browse/SUPPORT-4767)

**Comment by barmac** [comment]
This will be implemented as NO LIST AGGREGATION.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1593.

**Comment by sebwarnke** [comment]
The term `NO LIST AGGREGATION` is very misleading as Hit Policy without an operator actually returns a list.

**Comment by nikku** [comment]
What would be an appropriate label in this case? Could you [open a bug regarding this](https://github.com/camunda/camunda-modeler/issues/new?template=BUG_REPORT.md) and propose a better name?

**Comment by sebwarnke** [comment]
sure. i just collected some information from the standard. gonna open a bug ticket soon.
