### ISSUE TITLE
MacOS: Dock Icon too big Modeler 2.0

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-modeler#901]
Since Modeler 2.0 the Dock Icon for MacOSX is larger than icons of other software - is this intended? Looks strange:

<img width="418" alt="screen shot 2018-08-31 at 09 57 38" src="https://user-images.githubusercontent.com/20283848/44900296-8d7c2d00-ad04-11e8-880d-31fe19b1a6da.png">

**Comment by nikku** [comment]
This is not intended but a side-effect of the new icon generation we use.

Could you provide me with the size of the Slack and Settings icons and a screenshot of the dock with Camunda Modeler 1.6.x?

That would help us to bring back the icon with an appropriate size.

**Comment by felix-mueller** [comment]
<img width="231" alt="screen shot 2018-08-31 at 10 16 47" src="https://user-images.githubusercontent.com/20283848/44901226-1005ec00-ad07-11e8-8d9f-280e2add7a65.png">

**Comment by nikku** [comment]
:cake:

**Comment by tsabirgaliev** [comment]
@nikku it is not practical to measure icon size in MacOS, because it scales with dock size

**Comment by felix-mueller** [comment]
https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

**Comment by nikku** [comment]
<img width="304" alt="screen shot 2018-09-04 at 13 58 58" src="https://user-images.githubusercontent.com/58601/45033280-55eae900-b054-11e8-81b4-664db1005f8f.png">

Updated it to the slack / sublime text / settings icon size.

**Comment by nikku** [comment]
(small => old)
(bigger => new)

**Comment by nikku** [comment]
Will be released with upcoming version `v2.0.1`.
