### ISSUE TITLE
Trouble with boundary event to activity loops

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#903]
It is this intended? And where is the arrow of the sequence flow?

![boundary-event](https://user-images.githubusercontent.com/17595149/44979581-c834ce00-af6d-11e8-8a45-740974ed3f8b.gif)

**Comment by benhoffmann** [comment]
Hey @nikku ,

thanks for the hint with moving the boundary event somewhere else. This actually makes the situation better, even after placing the sequence flow. 

I just figured out what I did in the gif: I am connecting the wrong end of the sequence flow to the task which results in something like this: 

![bildschirmfoto 2018-09-06 um 09 37 42](https://user-images.githubusercontent.com/17595149/45142320-89df1f00-b1b8-11e8-9ff1-c3b5fb9c3af5.png)

Conclusion: The sequence flow is not completely broken, but still it would be nice to improve the algorithm to provide better usability.  Besides that - thanks for introducing this, it's a great feature!

- Ben

**Comment by philippfromme** [comment]
In the meantime, you can simply avoid placing boundary events in the middle of a shape. The algorithm isn't smart enough yet.

![20-03-_2019_16-09-22](https://user-images.githubusercontent.com/7633572/54695627-9a3e6200-4b2a-11e9-9a10-ea2653fd7b15.gif)

**Comment by barmac** [comment]
@benhoffmann Can you please let me know which of these two layouts would be preferable in your opinion? I added also the standard loop for comparison.

<img width="501" alt="Screenshot 2019-06-06 at 13 45 47" src="https://user-images.githubusercontent.com/28307541/59030636-d055cd00-8861-11e9-94ef-d78cfc1247e0.png">
<img width="469" alt="Screenshot 2019-06-06 at 13 46 49" src="https://user-images.githubusercontent.com/28307541/59030637-d0ee6380-8861-11e9-8ca9-c9b006184737.png">
<img width="509" alt="Screenshot 2019-06-06 at 13 47 40" src="https://user-images.githubusercontent.com/28307541/59030638-d0ee6380-8861-11e9-9557-14bdf19b45ba.png">

**Comment by benhoffmann** [comment]
I would say keep it similar to the standard loop - so the right alternative

**Comment by philippfromme** [comment]
I'd go for the version on the right. Savest option and the easiest to implement.

**Comment by barmac** [comment]
Great! Thank you for your feedback!

**Comment by nikku** [comment]
Right one :+1:

**Comment by barmac** [comment]
Second round ;)

<img width="362" alt="Screenshot 2019-06-06 at 14 50 19" src="https://user-images.githubusercontent.com/28307541/59034091-93da9f00-886a-11e9-8838-a3bd6172c6b2.png">
<img width="685" alt="Screenshot 2019-06-06 at 14 51 19" src="https://user-images.githubusercontent.com/28307541/59034092-93da9f00-886a-11e9-9825-b5710b4503a7.png">

**Comment by philippfromme** [comment]
Left. For the same reason.

**Comment by barmac** [comment]
And the last one...

<img width="677" alt="Screenshot 2019-06-06 at 14 53 58" src="https://user-images.githubusercontent.com/28307541/59034349-27ac6b00-886b-11e9-91f3-18523b7f1667.png">

**Comment by benhoffmann** [comment]
bottom left. sequence flows should never enter elements from the right

**Comment by barmac** [comment]
Thank you once more for your feedback :). This helped me a lot in preparing the PR.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1404.
