### ISSUE TITLE
Pinch-to-zoom stopped working in 2.0.0 on Mac

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#904]
I cannot use the 2-finger gesture to zoom anymore. Is that expected behavior?

**Comment by tsabirgaliev** [comment]
@benhoffmann can't reproduce on High-Sierra with 2.0.0. What is your env?

**Comment by benhoffmann** [comment]
MaxOS 10.13.6 (17G65)

It works from time to time, but sometimes not. Strange and close to impossible to reproduce. I guess we can also close the issue for now...
