### ISSUE TITLE
Restore persistent workspace

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#910]

**Comment by nikku** [comment]
What should I review?

**Comment by philippfromme** [comment]
https://github.com/camunda/camunda-modeler/commit/7929584166b1b06042175107480fec703f4d91d3

Sorry, I forgot to merge the branch into our development branch.

**Comment by nikku** [comment]
I would have expected a feature branch, mentioning this issue in the commit via `Closes #910` instead :wink:.

Added some review hints via https://github.com/camunda/camunda-modeler/commit/7929584166b1b06042175107480fec703f4d91d3.
