### ISSUE TITLE
Restore global layout concept

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#911]
* App knows about global layout but doesn't care about the details
* Tab can call App#onLayoutChange to let App know that layout has changed
* App will only take care of persisting changes

Related to https://github.com/camunda/camunda-modeler/issues/910.

**Comment by nikku** [comment]
Added [a couple of comments](https://github.com/camunda/camunda-modeler/commit/ed0a483c44aaba96d255a5a3f86514bb48857a41) to the feature commit.
