### ISSUE TITLE
Links for download on this (https://camunda.com/bpmn/tool/) page are not working 

### ISSUE THREAD

**Issue by mrandi** [camunda/camunda-modeler#913]
Hi,

I just saw that the links to download the modeler on [this page](https://camunda.com/bpmn/tool/) are not working.

OS: macOS High Sierra

Thanks for this great project :) 

PS: here is the download working well: https://camunda.com/download/modeler/

**Comment by apfeiffer85** [comment]
The link on the Page: https://camunda.org/release/camunda-modeler//2.0.1/camunda-modeler-2.0.1-darwin-x64.tar.gz?__hstc=252030934.604c50396abc96348b57e24a5b0c5391.1536846965136.1536846965136.1536846965136.1&__hssc=252030934.1.1536846965137&__hsfp=3291276868 

And a screenshot of the Error Page attached. 

![screen shot 2018-09-13 at 15 56 52](https://user-images.githubusercontent.com/10416399/45492902-c4732980-b76d-11e8-9acd-70d92e0bca1a.png)

**Comment by nikku** [comment]
Fixed.
