### ISSUE TITLE
Improve context pad tooltip for exclusive gateway 

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#917]
**Given**
An event based gateway

**When**
I use the context menu to append an intermediate catching event and hover over the event symbols

**Then**
I get the same tooltip for all events:  `Append IntermediateCatchEvent`

**Expected Behavior**
The tooltip contains the exact event type (Signal, Message, etc.)

**Comment by nikku** [comment]
This needs a fix in [bpmn-js](https://github.com/bpmn-io/bpmn-js), our underlying modeling toolkit.

**Comment by nikku** [comment]
Pending bpmn-js release.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/00f3ec8e7d3e5d74b098e716abc3de83ba50e149.
