### ISSUE TITLE
Set focus to new row when adding new rule

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#928]
__Is your feature request related to a problem? Please describe.__

When I click on the bottom row of a dmn table in order to add a new rule the focus is not on the new rule

__Describe the solution you'd like__

1. If I click in a specific cell of the button row the focus is in the respective cell of the new rule
2. if I click on the plus icon the focus is on the first cell of the new rule

__Describe alternatives you've considered__

no alternative

---

Related to [SUPPORT-6122](https://app.camunda.com/jira/browse/SUPPORT-6122)
This has to be fixed in [dmn-js](https://github.com/bpmn-io/dmn-js/blob/3f998debd1df9b96067b052bdb7b250db99f6657/packages/dmn-js-decision-table/src/features/editor-actions/DecisionTableEditorActions.js#L10).

**Comment by srazavi** [comment]
Related to [SUPPORT-6122](https://app.camunda.com/jira/browse/SUPPORT-6122)

**Comment by srazavi** [comment]
This popped up in support. I linked relevant support case in issue description.

**Comment by prithviraj-maurya** [comment]
Is it possible to get screenshot for this so as to reproduce it.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/d03c2a69a1adc4dcf236afd049b195e40e098a77
