### ISSUE TITLE
Migrate from Gulp to Grunt

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda-modeler#94]
This includes:

* [ ] release (patch, minor, major), related to #79
* [ ] build
* [ ] package electron app (platform specific)
* [ ] compress to (g)zip (platform specific)
* [x] mocha tests (partly platform specific)
* [ ] compile less
* [ ] copy relevant files (partly platform specific)

**Comment by nikku** [comment]
Implemented that via #142 and #141.
