### ISSUE TITLE
Connect message flows to call activities

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#942]
__Is your feature request related to a problem? Please describe.__

In a collaboration diagram I'd like to visualize the fact that the process process referenced via a call activity interacts with other activities / participants via message passing.

~~This is not allowed per BPMN spec.~~ __It turns out, according to @falko's interpretation it is allowed by the spec, it is simply not correctly represented in UML _and_ the meta-model__. 

It is not supported by our tools, as the call activity is not an interaction node:

![foo](https://user-images.githubusercontent.com/58601/46738534-bc3fd880-cc9e-11e8-9f68-ff4e3865de79.gif)

__Describe the solution you'd like__

I'd like us to allow an exception to the BPMN spec and allow call activities to be sources / targets of message flows. 

__Describe alternatives you've considered__

Stick to the status quo.

__Additional Context__

From the users point of view we already do something similar by allowing data stores to be modeled between participants (cf. https://github.com/camunda/camunda-modeler/issues/183).

---

Related to SUPPORT-4858, SUPPORT-10808

Depends on https://github.com/bpmn-io/bpmn-js/issues/1467

**Comment by MaxTru** [comment]
Also requested by https://jira.camunda.com/browse/SUPPORT-10808

**Comment by barmac** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js/pull/1468

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2335.
