### ISSUE TITLE
Pool with lanes contains space (and elements in that area) that are not in lane

### ISSUE THREAD

**Issue by nevries** [camunda/camunda-modeler#953]
__Describe the Bug__

See attached diagram, is that standard conform? Even more, how to get rid of the "not in lane"-space of the pool?

__Steps to Reproduce__

Sorry, only got the failing diagram.

__Expected Behavior__

There should be no space in a pool that is not part of a lane (as long is there is at least one lane).

[laneOrNoLane.bpmn.txt](https://github.com/camunda/camunda-modeler/files/2493410/laneOrNoLane.bpmn.txt)

**Comment by nikku** [comment]
> See attached diagram, is that standard conform? 

I guess. Lanes have no strictly defined semantics.

> There should be no space in a pool that is not part of a lane (as long is there is at least one lane).

If you're able to create this diagram with the Camunda Modeler it is a bug. In that case we'd need concrete steps to reproduce this issue

> Even more, how to get rid of the "not in lane"-space of the pool?

Simply resize the middle lane to take up all the space. Then you'll be able to split it up again.

**Comment by nikku** [comment]
> See attached diagram, is that standard conform? 

I guess. Lanes have no strictly defined semantics.

> There should be no space in a pool that is not part of a lane (as long is there is at least one lane).

If you're able to create this diagram with the Camunda Modeler it is a bug. In that case we'd need concrete steps to reproduce this issue

> Even more, how to get rid of the "not in lane"-space of the pool?

Simply resize the middle lane to take up all the space. Then you'll be able to split it up again.

**Comment by nikku** [comment]
> See attached diagram, is that standard conform? 

I guess, lanes don't really have strict semantics.

>  Even more, how to get  rid of the "not in lane"-space of the pool?

Resize the second lane to take all open space. Split it afterwards into two to restore the old behavior.
