### ISSUE TITLE
Issue Installing Camunda Modeler

### ISSUE THREAD

**Issue by ciaranrennais** [camunda/camunda-modeler#957]
I am installing Camunda Modeler on Mac OS (10.13.6). My node version is v8.10.0.

The tests pass (using npm run all). 

__Describe the Bug__

When starting the system (using npm run dev), only a white screen appears possible due to the Reference error (see screen shot).

![image](https://user-images.githubusercontent.com/430172/47387177-dce04780-d70e-11e8-933d-fd890f3a3052.png)

__Steps to Reproduce__

I have reinstalled browserify but this does not help.

__Environment__

Please complete the following information:

 - OS: MacOS 10.16.6
 - Camunda Modeler Version: next branch

**Comment by nikku** [comment]
I cannot reproduce the behavior your seeing.

What exact steps (including git clone) did you undertake to end up with this result?

**Comment by ciaranrennais** [comment]
I downloaded the ZIP to start with.

I have repeated the exercise using git clone -b next and the result is the same. Also, I have moved to Mac OS 10.14 Mojave.

**Comment by nikku** [comment]
Please provide the _exact_ steps to reproduce your issue as mentioned in [my previous comment](https://github.com/camunda/camunda-modeler/issues/957#issuecomment-433047839). 

We cannot help you otherwise.

**Comment by nikku** [comment]
This installs just fine and opens the Camunda Modeler application on my machine.

Make sure to press `CMD+R` in the app once webpack finished compiling (and don't go to `localhost:3000` as indicated by the commandline) and you are fine.

**Comment by ciaranrennais** [comment]
That did it. Thanks!
