### ISSUE TITLE
When pasting into Documentation field, the paste is not style free

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#961]
OSX using 1.14

when you paste from certain applications like a web browser, the style of the copy is being pasted into the text box.  This is occurring for the Documentation field.

![screen shot 2018-10-25 at 1 20 33 pm](https://user-images.githubusercontent.com/1994838/47518444-00afa480-d859-11e8-8493-efbd2eda48b8.png)

Related to https://github.com/camunda/camunda-modeler/issues/702

**Comment by nikku** [comment]
Needs fix via https://github.com/bpmn-io/bpmn-js-properties-panel/issues/265.

**Comment by nikku** [comment]
Needs fix in dmn-js-properties-panel and cmmn-js-properties-panel, too.

**Comment by barmac** [comment]
Fixed via https://github.com/camunda/camunda-modeler/pull/1730
