### ISSUE TITLE
Show empty tab when tabs are overflowing

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#968]
When tabs are overflowing the empty tab is not shown. It should always be shown.

![image](https://user-images.githubusercontent.com/7633572/47782189-e9acfe80-dcff-11e8-96a1-14ab1ebf426c.png)

Hint: Due to the way [scroll-tabs](https://github.com/bpmn-io/scroll-tabs) works it's difficult to make this work.

**Comment by pinussilvestrus** [comment]
Reproduced it

**Comment by philippfromme** [comment]
This is not a bug but a possible enhancement. In the current version of the Camunda Modeler the empty tab is not visible whenever the tabs are overflowing.

**Comment by nikku** [comment]
What is the benefit of having the `+` button if you already got 40 tabs open? If you are a heavy user of the application (you opened many tabs already) you are probably aware of how to open / create diagrams without using the `+` button.

I'd be _hapy_ to close this issue as _won't fix_.

**Comment by philippfromme** [comment]
This was listed as a requirement in the original scroll and drag ticket.
________________________________

**Comment by nikku** [comment]
Let us relax the original requirement(s) and close this issue then.

**Comment by philippfromme** [comment]
Relaxing sounds good! ??
________________________________
