### ISSUE TITLE
Refactor Saving Denied Dialog

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#973]
This is part of the overall dialog refactoring #959 

- remove hardcoded `saving-denied` dialog in favor of reusable dialogs
- implement new dialog in a way that it is configured through the client

**Comment by philippfromme** [comment]
_Saving denied_ is referring to the user cancelling the _Save_ dialog which is already being handled by https://github.com/camunda/camunda-modeler/blob/next/client/src/app/App.js#L797
