### ISSUE TITLE
I can save all diagrams at once

### ISSUE THREAD

**Issue by gimbel** [camunda/camunda-modeler#98]

**Comment by vladimirskatusenoks** [comment]
Checklist:
- [ ] Menu entry and shortcut (Cmd/Ctrl + Option/Alt + S), positioned below 'Save File As'
- [ ] Action on client side to save all tabs
- [ ] New icon in the menu-bar next to the 'save-as'

**Comment by vladimirskatusenoks** [comment]
Relatest to #146
