### ISSUE TITLE
Normalize scrolling through tabs

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#981]
Depending on how you scroll (mouse wheel, touchpad) the speed is different. We've fixed this issue in [diagram-js](https://github.com/bpmn-io/diagram-js/blob/master/lib/navigation/zoomscroll/ZoomScroll.js) before and we should do the same here.

__Tasks__

* [ ] Improve touchpad scrolling in scroll-tabs library
* [ ] Integrate improved scroll-tabs library

**Comment by barmac** [comment]
Please note that in `diagram-js` we bind to `wheel` event and use its specific `delta[x,y,z]` properties. However, for tabs scrolling, we use [scroll event](https://developer.mozilla.org/en-US/docs/Web/Events/scroll) which apparently lacks such properties. Thus, the only way to measure scrolling _speed_ is the quantity of events per unit of time.

**Comment by philippfromme** [comment]
Problem is: Throttling doesn't work for this. When using the mouse wheel it feels super slow because I can only switch tabs every 100ms. With touchpad it feels alright. But it's not a good solution.

**Comment by barmac** [comment]
Indeed, this is actually a inherent problem of `scroll-tabs` library. It binds directly to `wheel` events and changes tabs with each event: https://github.com/bpmn-io/scroll-tabs/blob/master/index.js#L259

**Comment by felix-mueller** [comment]
+1

**Comment by nikku** [comment]
We'll not fix this, as we moved to all elements being visible (and no scrolling is needed, anymore) with Camunda Modeler 5+.
