### ISSUE TITLE
Uncaught exception in the main process when right clicking BPMN diagram 

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#986]
__Describe the Bug__

<img width="1680" alt="screenshot 2018-11-02 at 09 24 26" src="https://user-images.githubusercontent.com/28307541/47901972-88149d80-de81-11e8-8529-a7ef0bec1129.png">

__Steps to Reproduce__

1. Open a BPMN diagram
2. Right click (touch with two fingers on MacBook)

__Expected Behavior__

No uncaught exception

__Environment__

Please complete the following information:

 - OS: MacOS 10.14 Mojave
 - Camunda Modeler Version: `next@12db137` (2.03)

**Comment by pinussilvestrus** [comment]
Reproduced a lot of times before, thanks for opening 🎉

**Comment by nikku** [comment]
Will be fixed by #1000.
