### ISSUE TITLE
DOM should be cleaned after tests

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#989]
__Describe the Bug__

At least some of the tests seem to leave components mounted to DOM which may affect other DOM-dependant tests.

<img width="1668" alt="screenshot 2018-11-05 at 10 52 34" src="https://user-images.githubusercontent.com/28307541/47991011-3f5f1d80-e0e9-11e8-83db-026467ea8508.png">

__Steps to Reproduce__

1. Run tests

__Expected Behavior__

Components should be unmounted after tests. This can be done by calling `tree.unmount()`.

See: https://github.com/airbnb/enzyme/blob/master/docs/api/mount.md

__Environment__

 - Camunda Modeler Version: `next@2.0.3`

**Comment by nikku** [comment]
Removed the `bug` label, as this is not a user facing problem.

Can we provide a general solution that handles automatic mounting / unmounting as part of the test cycle for us?

**Comment by nikku** [comment]
Note to self: Unless we address this issue any time soon there is a high likelyhood it will never be closed.
