### ISSUE TITLE
Event Gateway does not provide proper names of intermediate Events for drag and drop helpers:

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#993]
Mac OSX 10.13.6

Modeler 1.14

Event Gateway does not provide proper names of intermediate Events for drag and drop helpers:

![screen shot 2018-11-05 at 12 53 05 pm](https://user-images.githubusercontent.com/1994838/48016575-f4013b00-e0f9-11e8-9712-707930a96a33.png)

All the events appear as `IntermediateCatchEvent` and not as the properly named event.

**Comment by pinussilvestrus** [comment]
Thats done with https://github.com/camunda/camunda-modeler/issues/917. There is a pending release, so it will be live soon.

**Comment by StephenOTT** [comment]
thanks
