### ISSUE TITLE
Token Simulation Plugin crashes Camunda Modeler

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#999]
See: https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/12

---

__Tasks__

* [x] Fix bpmn-js-token-simulation and release it ([v0.8.0](https://github.com/bpmn-io/bpmn-js-token-simulation/blob/master/CHANGELOG.md#080))
* [x] Build and publish new plug-in

**Comment by pinussilvestrus** [comment]
I can reproduce this error.

**Comment by falko** [comment]
Any news on using the Token Simulation with current Camunda Modeler builds? Is it a Modeler issue or a plugin issue?

**Comment by nikku** [comment]
Which Camunda Modeler version is affected by this?

**Comment by falko** [comment]
The nightly of the day when I opened the issue was effected.

**Comment by nikku** [comment]
This does not help us to track down and reproduce this issue.

Is the latest release (`v2.2.0`) or latest nightly affected. @pinussilvestrus Maybe you can step in and provide the necessary details.

**Comment by falko** [comment]
I tested it again. The current nightly is affected. One has to kill the modeler.

**Comment by falko** [comment]
The latest release (v2.2.0) is affected, too.

**Comment by falko** [comment]
IRC the last release still worked.

**Comment by nikku** [comment]
Thanks for investigating. We will have a look.
